### ISSUE TITLE
Improve docs for mode arg of spark_write_*()

### ISSUE THREAD

**Issue by russellpierce** [rstudio/sparklyr#1005]
The sparklyr docs for spark_write_*() include a mode arg but lack a reference to where one can determine the set of possible values for that arg.  I think the correct reference is http://spark.apache.org/docs/latest/sql-programming-guide.html#save-modes.  

I had intended to make a PR, but I noticed multiple occurrences of `#' @param mode` for each function in conjunction with `#' @inheritParams spark_write_csv`.  So, I wasn't certain whether the same ref could serve all funcs (and if so whether the individual `#' @param mode` lines should be dropped in favor of a single inherited param.  

Some guidance would be appreciated.  [Relevant R file](https://github.com/rstudio/sparklyr/blob/master/R/data_interface.R).

**Comment by javierluraschi** [comment]
@russellpierce all the instances of `@param mode` under `data_interface.R` would support those. Would be great if you can send a PR with something like:

```
#' @param mode Specifies the behavior when data or table already exists. Supported values include: error, append, overwrite and ignore.
```

You would also have to regenerate the docs with `roxygen`, using RStudio `Build Menu -> Document`

**Comment by russellpierce** [comment]
Should that text be provided at each function or just once under spark_write_csv with the individual @param mode entries dropped?

**Comment by russellpierce** [comment]
I'll pick this up next week.  I'll default to dropping the extra mode statements unless I hear otherwise.

**Comment by javierluraschi** [comment]
@russellpierce we would want to change each function since all of the functions under the `data_interface.R` support those values.

I don't think we are currently sharing doc `@param` across that file, so unless you want to refactor into a single parameter block, we would want to change each of them.

Thanks for giving this a shot.
