### ISSUE TITLE
consider how reference labels should be chosen / selected for ml routines

### ISSUE THREAD

**Issue by kevinushey** [rstudio/sparklyr#101]
There's a couple over-arching things we'd like to make easily configurable:
1. Given a categorical variable `x` with some labels `yes`, `no`, etc., we should provide some mechanism for mapping labels to dummy variable names; e.g. the column such that `x == "yes"` is called `RespondedYes`, or something to that effect. This is primarily to allow for nicer model / summary output.
2. We should provide some mechanism for allowing users to configure what level should be considered the reference label, for categorical variables. Normally, for R, this is done just by encoding the variable as a `factor`, with the first level implicitly acting as the reference label.

For 1., I think we could allow the user to supply a list of mappings for these generated names, e.g.

```
metadata = list(
  x = list(
    reference = "no",
    mapping = list(
      yes = "RespondedYes"
    )
  )
)
data_tbl %>% ml_linear_regression(y ~ x, metadata = metadata)
```

And we could provide helpers for constructing that metadata -- although it's a bit verbose, it should provide what we need.

**Comment by Jiang-Li** [comment]
Any update about how to assign the reference level, like the relevel function in R and H2O? Thx!

**Comment by kevinykuo** [comment]
@Jiang-Li this is a little tricky since it's not natively supported in Spark – in fact, Spark 2.3.0 will only support [setting reference level by frequency or alphabetically](https://issues.apache.org/jira/browse/SPARK-14659). However, I'll make a note to look at this as part of the ML refactoring that's in progress. There might be a way to tweak column metadata cleanly.

**Comment by kevinykuo** [comment]
Closing this as wontfix since it's a Spark limitation and I'd rather not add features that won't be compatible with pipelines. Hopefully this isn't too big of an issue (e.g. one can always recompute relativities for GLMs after getting the fitted results.)
