### ISSUE TITLE
sparklyr connects to existing spark applications

### ISSUE THREAD

**Issue by yeshwanth43** [rstudio/sparklyr#1011]
# sparklyr connects to existing spark applications if set.seed() is called before spark_connect

---

we are running sparklyr on CDH cluster, and noticed this behavior with the following code.
at first, we saw this in between multiple users,
if two users sets same seed value and initiates spark connection, 
instead of  getting a new spark app in yarn , it connects to one of the existing app.

when i tried to reproduce this, i saw the same behavior across different sessions of same user.
i didn't noticed anything ,when i compared  different user session environments side by side.
i do not have a clue why this is happening.

following are the version details
RStudio server pro - 1.0.153
Sparklyr - 0.6.2

in order to reproduce this issue, for single user create 3 sessions,
1st session open spark connection without seed
2nd session open spark connection with seed
do the same as above for 3rd session.
instead of getting 3 different spark applications in Yarn, you will see only 2.
3rd session will connect to one of the existing spark applications

it doesn't make any sense why set.seed() changes the way spark connects

```r
library(sparklyr)
set.seed(12345)
sc <-spark_connect(master = "yarn-client", config = list())
```

**Comment by javierluraschi** [comment]
Thank you @yeshwanth43, fix will be merged later today.

**Comment by yeshwanth43** [comment]
Thanks @javierluraschi .
can you explain the issue.
