### ISSUE TITLE
Improve serialization from JDBC Sources

### ISSUE THREAD

**Issue by JakeRuss** [rstudio/sparklyr#1013]
Per @javierluraschi's comments in #941 I have opened this new issue. 

The problem is that date and date time fields from MySQL (and possibly other JDBC sources) are read into Spark (via `spark_read_jdbc`) as character instead of preserving the datetime structure.

In #941 you requested a sample schema and I have modified your example to include the three MySQL date/datetime types. This updated schema below is very similar to the schema's we're using for our database. In the real schema we use datetime for both the `created` and `updated` fields but for this testing example I have made one a timestamp field to cover all of the use cases. 

```
CREATE TABLE EMPLOYEES(
   ID INT PRIMARY KEY       NOT NULL,
   NAME           TEXT      NOT NULL,
   AGE            INT       NOT NULL,
   ADDRESS        CHAR(50),
   SALARY         REAL,
   DOB            DATE      NOT NULL,
   CREATED        DATETIME  NOT NULL,
   UPDATED        TIMESTAMP NOT NULL
);
```
Thanks for taking a look!

**Comment by javierluraschi** [comment]
Thank you! Closing to address this with: https://github.com/rstudio/sparklyr/issues/941
