### ISSUE TITLE
Issues with Mutate in Sparklyr

### ISSUE THREAD

**Issue by hlendway** [rstudio/sparklyr#1015]
I've been playing around with mutate in sparklyr and I keep running into oddities where a mutate seems to be skipped or will give an error when combined into one statement.  When broken out into multiple mutates or seperate statements it seems to work better.   I want to do an sdf_pivot which seems to have issues when the new column names are more than oen word so I need to change my type to be a single word.  When I run this, the "Advisor Meeting" line doesn't seem to run but all other lines do.  Has anyone experienced this or similar issues? 
[sampledata.docx](https://github.com/rstudio/sparklyr/files/1307134/sampledata.docx)

It won't allow be to upload a csv but I attached a doc with sample data.  If you load the data into a spark table named data you can hopefully try the code below.  

data <- data %>% 
  mutate(type = ifelse((type == "Outbound Call"),"Outbound",type),
         type = ifelse((type == "Advisor Meeting"),"Meeting",type), 
         type = ifelse((type == "Left Message"),"Message",type),
         type = ifelse((type == "Inbound Call"),"Inbound",type))

**Comment by javierluraschi** [comment]
@hlendway which error are you getting? I think you might be hitting a bug in `dplyr` tracked by https://github.com/rstudio/sparklyr/issues/1015.

One workaround is to split your mutates as in...

```r
data <- data %>%
  mutate(type = ifelse((type == "Outbound Call"),"Outbound",type)) %>%
  mutate(type = ifelse((type == "Advisor Meeting"),"Meeting",type)) %>%
  mutate(type = ifelse((type == "Left Message"),"Message",type)) %>%
  mutate(type = ifelse((type == "Inbound Call"),"Inbound",type))
```

**Comment by hlendway** [comment]
@javierluraschi Thank you!  That fixed a few of my issues!  I thought it was always the 3rd mutate that wasn't working so that makes sense now.  Appreciate the quick response!

**Comment by javierluraschi** [comment]
No worries, please track the issue with https://github.com/tidyverse/dplyr/issues/3095, I'll close this one. We can also consider providing a fix in `sparklyr`, but it would be ideal to get this fixed in `dplyr`, thanks you @hlendway!
