### ISSUE TITLE
Spark SQL ``inline`` not supported

### ISSUE THREAD

**Issue by schlichtanders** [rstudio/sparklyr#1024]
Dear dev-team,

I stumpled upon ``inline`` returning *multiple columns*, however dplyr/sparklyr syntax does not seem to support something like this. Take for instance the following minimal example:

```r
> df
# Source:   table<df> [?? x 4]
# Database: spark_connection
       x     y     g     w
   <int> <int> <dbl> <dbl>
 1     2     2     1     1
 2     1     4     1     1
 3     3     4     1     1
 4     3     2     2     1
 5     3     3     2     1
 6     2     3     2     1
 7     1     3     3     1
 8     4     4     3     1
 9     1     3     3     1
10     3     2     3     1
```
This should be something like the identity function (with "col1" and "col2" as new column names), however it fails.
```r
> df %>% group_by(g) %>% summarize(xy = collect_list(struct(x, y))) %>% mutate(inline(xy))
Error: org.apache.spark.sql.AnalysisException: The number of aliases supplied in the AS clause does not match the number of columns output by the UDTF expected 2 aliases but got inline(xy) ;
```

Is there a way to use ``inline`` sql function within sparklyr?

best regards,
Stephan

**Comment by javierluraschi** [comment]
@schlichtanders `dplyr` supports pass-through functions that become SQL functions if no r-function overrides them, so for instsance `df %>% select(inlin(g))` would become `SELECT inline(g) FROM df`, is this what you mean?

**Comment by schlichtanders** [comment]
that sounds really good!, thank you a lot
