### ISSUE TITLE
columns lost when converting from json to parquet

### ISSUE THREAD

**Issue by randomgambit** [rstudio/sparklyr#1025]
Hello @javierluraschi @kevinykuo ,

I hope all is good!

I am facing a serious issue here and I am not sure this is a bug or not. I have a bunch of large json files, and _some of them_ contain one more column than the others. Because of their size, I convert them to parquet using

```
for(i in 51:length(file_names)){
  df <- spark_read_json(sc, paste("/mypath/",file_names[i], sep = ""),
                        repartition = 0,
                        name = "df",
                        memory = FALSE,
                        overwrite = TRUE)
  spark_write_parquet(df,paste("/mypath/","parquet_",file_names[i], sep = ""), mode = "overwrite" )
  dplyr::db_drop_table(sc, "df")
}

```

Then, in my spark code I can easily do

`df_new <- spark_read_parquet(sc, "/mypath/parquet_**", overwrite = TRUE, name = "df_new", memory = FALSE)
`

to load everything at once.

Unfortunately, I now  realize that when I do so, `df_new` does not include the extra column that is present in some of the `json` files. Is that a bug?

Thanks!

**Comment by randomgambit** [comment]
@javierluraschi @kevinykuo this may have to do with `'spark.sql.parquet.mergeSchema'='true'` ? but how to set that correcly there? there is no info in the documentation...

Thanks!

**Comment by javierluraschi** [comment]
Looks like you need to use `options = list(mergeSchema = "true")`, as in:

```
df_new <- spark_read_parquet(
  sc,
  "/mypath/parquet_**",
  overwrite = TRUE,
  name = "df_new",
  memory = FALSE,
  options = list(mergeSchema = "true")
)
```

See also https://spark.apache.org/docs/1.6.1/sql-programming-guide.html#schema-merging.

Going to close this one since it's closer to a question than an issue.
