### ISSUE TITLE
Reduce `spark_apply()` package depedencies

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#1027]
`spark_apply()` could scope down the packages it copies to each worker using an explicit `packages = (.packages())` parameter that defaults to the current loaded ones and gets all the dependencies with `tools::package_dependencies()`

CC: @edgararuiz

**Comment by randomgambit** [comment]
@javierluraschi I am actually having problems with `spark_apply`. do you mean there is way not to copy the packages over each worker every time?

**Comment by javierluraschi** [comment]
The packages are copied for each application session, read, each time `spark_connect()` is run we copy at most once to each worker node while running `spark_apply()`. You could not use r packages with `packages = FALSE`. @randomgambit

**Comment by javierluraschi** [comment]
@randomgambit could be a disk space issue according to: http://odino.org/tar-web-tar-wrote-only-x-of-y-bytes/ - @edgararuiz ran the following in a similar situation:

```
ssh -i file.pem user@hostname

sudo du -sh /
sudo rm -rf /home/ubuntu/spark-2.1.0-bin-hadoop2.7/work
sudo mkdir /home/ubuntu/spark-2.1.0-bin-hadoop2.7/work
sudo du -sh /
exit
```

**Comment by randomgambit** [comment]
@javierluraschi  thanks! let me try that
