### ISSUE TITLE
Unable connect to Spark 2.1.0

### ISSUE THREAD

**Issue by englianhu** [rstudio/sparklyr#1028]
I tried to run `devtools::install_github("rstudio/sparklyr")` to install the package. I refer to https://github.com/rstudio/sparklyr/issues/288 for the solution but there error keep exist.

When I tried to connect to Spark, the system prompt me invalid java's version.
```diff
spark_version <- "2.1.0"
sc <- spark_connect(master = "local", version = spark_version)
- Error in get_java(throws = TRUE) : 
-   Java is required to connect to Spark. JAVA_HOME is set but does not point to a valid version. Please fix - JAVA_HOME or reinstall from: https://www.java.com/en/
```
But I had installed Java when I tried to check if system detected.
![capture](https://user-images.githubusercontent.com/7227582/30697259-4e258970-9f19-11e7-9c24-5536ae940001.JPG)

```r
> devtools::session_info()$platform
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 os       Windows >= 8 x64            
 system   x86_64, mingw32             
 ui       RStudio                     
 language en                          
 collate  Japanese_Japan.932          
 tz       Asia/Tokyo                  
 date     2017-09-21
```

**Comment by javierluraschi** [comment]
@englianhu looks like JAVA_HOME is not pointing to the right path, from PS I believe we want to run `$Env:JAVA_HOME` to see what the value is, could you follow that by listing the directory it points to with `Get-ChildItem $Env:JAVA_HOME`?

**Comment by englianhu** [comment]
Solved with modify the path https://d.cosx.org/d/419485-sparklyr-spark-2-1-0
