### ISSUE TITLE
Cluster mode doesn't wait for ACCEPTED application to be resourced by YARN

### ISSUE THREAD

**Issue by samurainate** [rstudio/sparklyr#1033]
Testing cluster mode on our internal Hortonworks cluster shows launch sometimes succeeds and sometimes fails.  Failures appear to be due to timeout waiting for the application to start.  However, the application is in ACCEPTED state and a state-aware client could handle launch more robustly.  Propose a new logic to make launch more likely to succeed and give user control over timeouts at each stage.

Current behavior:
Sparklyr receives RM output which shows new SPARK application in ACCEPTED state.
Sparklyr polls RM until sparklyr.yarn.cluster.start.timeout
Sparklyr reports failure to launch after timeout.

Desired behavior:
Sparklyr receives RM output which shows new SPARK application in ACCEPTED state.  
Sparklyr stores the application id for the ACCEPTED application
Sparklyr client enters a polling loop (with a sleep shorter than the sparklyr shell connection timeout), and monitors the application status for change to RUNNING, FAILED, FINSHED or KILLED states.
On running state, sparklyr client attempts connection to remote.
On any other state, sparklyr client reports failure to launch.

There is potential to just increase the sparklyr.yarn.cluster.start.timeout, but a YARN-state awareness would have better results for the end user.  Failure to detect the application in a period of time may indicate a failure to submit, but detecting an application in ACCEPTED state indicates a succesful submit. There may also be a failure to start the remote spark application, but that cannot be resolved until the application enters the RUNNING state.  The same is true for failure to connect.

I propose separating timeouts for cluster mode, with a submit timeout, resource timeout, and a connect timeout.  This gives the user with knowledge of how they expect their cluster to behave control over how sparklyr waits for each stage.

### R stderr
```
Error in force(code) : 
  Failed to retrieve new sparklyr yarn application from http://rm1:8088/ws/v1/cluster/apps?startedTimeBegin=1506368729992&applicationType=SPARK&user=nm5144 after 50 secs, last result: list(app = list(list(id = "application_1506205345273_74438", user = "nm5144", name = "sparklyr.Shell", queue = "bdcoe5", state = "ACCEPTED", finalStatus = "UNDEFINED", progress = 0, trackingUI = "UNASSIGNED", diagnostics = "[Mon Sep 25 15:46:19 -0400 2017] Application is Activated, waiting for resources to be assigned for AM. User capacity has reached its maximum limit. Details : AM Partition = <DEFAULT_PARTITION> ; Partition Resource = <memory:149811200, vCores:36575> ; Queue's Absolute capacity = 5.5575 % ; Queue's Absolute used capacity = 7.521531 % ; Queue's Absolute max capacity = 19.6875 % ; ", 
    clusterId = 1506205345273, applicationType = "SPARK", applicationTags = "", priority = 0, startedTime = 1506368737980, finishedTime = 0, elapsedTime = 41454, allocatedMB = 0, allocatedVCores = 0, runningContainers = 0, memorySeconds = 0, vcoreSeconds = 0, queueUsagePercentage = 0, clusterUsagePercentage = 0, preemptedResourceMB = 0, preemptedResourceVCores = 0, numNonAMContainerPreempted = 0, numAMContainerPreempted = 0, resourceRequests = list(list(capability = list(memory = 32768, memorySize = 32768, 
        virtualCores = 4), nodeLabelExpression = "", numContainers = 1, priority = list(priority = 0), relaxLocality = TRUE, resourceName = "*")), logAggregationStatus = "NOT_START", unmanagedApplication = FALSE, amNodeLabelExpression = "")))
In addition: Warning messages:
1: In value[[3L]](cond) :
  Failed to open http:///ws/v1/cluster/info. Error in curl::curl_fetch_memory(url, handle = handle): Couldn't resolve host 'ws'

2: In value[[3L]](cond) :
  Failed to open http:///ws/v1/cluster/info. Error in curl::curl_fetch_memory(url, handle = handle): Couldn't resolve host 'ws'

trace:
withr::with_options(list(warning.length = 8000), {
    stop("Failed to retrieve new sparklyr yarn application from ", 
        resourceManagerQuery, " after ", format(Sys.time() - 
            commandStart, digits = 1), ", last result: ", yarnApps)
})
spark_yarn_cluster_get_app_property(config, start_time, resourceManagerWebapp, 
    "amHostHttpAddress")
spark_yarn_cluster_get_gateway(config, start_time)
start_shell(master = master, spark_home = spark_home, spark_version = version, 
    app_name = app_name, config = config, jars = spark_config_value(config, 
        "sparklyr.jars.default", list()), packages = spark_config_value(config, 
        "sparklyr.defaultPackages"), extensions = extensions, 
    environment = environment, shell_args = shell_args, service = service, 
    remote = remote)
shell_connection(master = master, spark_home = spark_home, app_name = app_name, 
    version = version, hadoop_version = hadoop_version, shell_args = shell_args, 
    config = config, service = spark_config_value(config, "sparklyr.gateway.service", 
        FALSE), remote = spark_config_value(config, "sparklyr.gateway.remote", 
        spark_master_is_yarn_cluster(master)), extensions = extensions)
sparklyr::spark_connect(app_name = my.app.name, version = "2.0.0", 
    hadoop_version = "2.7", master = "yarn-cluster", spark_home = "/opt/app/hdp/current/spark2-client", 
    config = config)
```

### R launch script
```
# point this to your preferred hive-site.xml or use the default
my.hive.site.xml <- "/opt/app/hdp/current/hive-client/conf/hive-site.xml"

# name for this application in YARN
my.app.name <- "SparklyR"      

# how big are each of your executors
my.app.executor.cores <- "4" 
my.app.executor.memory <- "28G"

# how big is your driver
my.app.driver.cores <- "4"   
my.app.driver.memory <- "28G"   

### Startup

# set necessary environment and library paths
Sys.setenv(JAVA_HOME="/opt/app/java/jdk/jdk180") 
Sys.setenv(SPARK_HOME="/opt/app/hdp/current/spark2-client")
Sys.setenv(HADOOP_CONF_DIR="/opt/app/hdp/current/hadoop-client/conf")
.libPaths(c(file.path(Sys.getenv("SPARK_HOME"),"R","lib"), .libPaths()))

config = list(
        "sparklyr.sanitize.column.names"="true",
        "sparklyr.shell.executor-memory"=my.app.executor.memory, 
        "sparklyr.shell.executor-cores"=my.app.executor.cores, 
        "sparklyr.shell.driver-memory"=my.app.driver.memory, 
        "sparklyr.shell.driver-cores"=my.app.driver.cores, 
        "sparklyr.shell.files"=c(my.hive.site.xml),
        "sparklyr.yarn.cluster.start.timeout"=50,
        "spark.rpc.askTimeout"="300s",
        "spark.yarn.max.executor.failures"="300",
        "spark.sql.hive.convertMetastoreOrc"="false",
        "spark.shuffle.service.enabled"="true",
        "spark.dynamicAllocation.enabled"="true"
    )

# start spark cluster on YARN
sc <- sparklyr::spark_connect(
    app_name = my.app.name, 
    version="2.0.0", 
    hadoop_version="2.7", 
    master="yarn-cluster",
    spark_home="/opt/app/hdp/current/spark2-client",
    config=config
)
```

**Comment by javierluraschi** [comment]
@samurainate thank you for this detailed write-up, two things come to mind:

1. Yes, I do agree that `sparklyr` should validate and track additional yarn states like `RUNNING`, `FAILURE`, etc.
2. Regarding timeouts, we currently have a yarn `submit timeout` and a `connect timeout`. I understand you are proposing we introduce a `resource timeout` which would allow users to wait for resources to become available. The biggest benefit would be to allow users to wait for resources but abort on failure conditions without having to wait for significant amounts of time. The use case here would be a cluster under load, where a user is willing to wait for resources, say `1hr`, but if the connection fails from other non-resource related issues, we would want that to the user to wait for only the default connection timeout. Is this the main motivation you see as well?

**Comment by samurainate** [comment]
Unless cancelled, the ACCEPTED application will eventually be resourced and enter RUNNING state, or fail to.  Normally, I would wait indefinitely because I have work to do and I expect eventually the application will get resources.  It's possible I might be impatient, and prefer to try again later after waiting a set period.  Since YARN allocation is an independent process from submit and connect and it is observable, I do propose separate timeouts for the three.  Without that, if we wait for submit and then start waiting for connect, we have a window of time where the client will attempt connections and a window of time where the server will accept connections.  If resource allocation takes longer than the client connect window, there is no chance for a successful connection.  The server will still wait for a connection that isn't coming until timeout.

There's a case I haven't considered, if the application doesn't register with the RM until after a client connection is successfully made, then the running state wouldn't happen until after connection and this would be moot.  I didn't think of that yesterday.  Do you know which order connection and registration happen in?

**Comment by javierluraschi** [comment]
@samurainate made some improvements here... first, `sparklyr` was not waiting for `ACCEPTED` state, now this can be controlled using `sparklyr.yarn.cluster.accepted.timeout`. However, I found out that `ACCEPTED` is not enough, in order for an application to be fully ready to use, one also needs to wait for the running container to be available `sparklyr` is mostly interested in finding the host address of the running container, which we can wait for now using: `sparklyr.yarn.cluster.hostadddress.timeout`.

In retrospect, YARN states should be more granular and move from `ACCEPTED` -> `ALLOCATED` -> `RUNNING`, but that's another story.

Here is the step by step logs I got:

(1) I started a `sc <- spark_connect(master = "yarn")` application and made sure it utilized all resources
(2) I started a `yarn-cluster` conneciton using `sc <- spark_connect(master = "yarn-cluster")` and got this from the Yarn API:

```xml
<app>
<id>application_1509474750063_0067</id>
<user>hadoop2</user>
<name>sparklyr.Shell</name>
<queue>default</queue>
<state>ACCEPTED</state>
<finalStatus>UNDEFINED</finalStatus>
<progress>0.0</progress>
<trackingUI>UNASSIGNED</trackingUI>
<diagnostics/>
<clusterId>1509474750063</clusterId>
<applicationType>SPARK</applicationType>
<applicationTags/>
<startedTime>1509563844214</startedTime>
<finishedTime>0</finishedTime>
<elapsedTime>541</elapsedTime>
<allocatedMB>0</allocatedMB>
<allocatedVCores>0</allocatedVCores>
<runningContainers>0</runningContainers>
<memorySeconds>0</memorySeconds>
<vcoreSeconds>0</vcoreSeconds>
<preemptedResourceMB>0</preemptedResourceMB>
<preemptedResourceVCores>0</preemptedResourceVCores>
<numNonAMContainerPreempted>0</numNonAMContainerPreempted>
<numAMContainerPreempted>0</numAMContainerPreempted>
<resourceRequests>
<capability>
<memory>1408</memory>
<virtualCores>1</virtualCores>
</capability>
<emrLabel>CORE</emrLabel>
<nodeLabelExpression/>
<numContainers>1</numContainers>
<priority>
<priority>0</priority>
</priority>
<relaxLocality>true</relaxLocality>
<resourceName>*</resourceName>
</resourceRequests>
</app>
```

Notice the state is `ACCEPTED` but `runningContainers` is `0`. This state blocks indefinetely, until...

(3) Ran `spark_disconnect_all()` from first session holding the yarn-client resources, as to which the blocked app changed to:

```xml
<app>
<id>application_1509474750063_0067</id>
<user>hadoop2</user>
<name>sparklyr.Shell</name>
<queue>default</queue>
<state>ACCEPTED</state>
<finalStatus>UNDEFINED</finalStatus>
<progress>0.0</progress>
<trackingUI>UNASSIGNED</trackingUI>
<diagnostics/>
<clusterId>1509474750063</clusterId>
<applicationType>SPARK</applicationType>
<applicationTags/>
<startedTime>1509563844214</startedTime>
<finishedTime>0</finishedTime>
<elapsedTime>67051</elapsedTime>
<amContainerLogs>
http://ip-10-46-7-95.us-west-2.compute.internal:8042/node/containerlogs/container_1509474750063_0067_01_000001/hadoop2
</amContainerLogs>
<amHostHttpAddress>ip-10-46-7-95.us-west-2.compute.internal:8042</amHostHttpAddress>
<allocatedMB>1408</allocatedMB>
<allocatedVCores>1</allocatedVCores>
<runningContainers>1</runningContainers>
<memorySeconds>3704</memorySeconds>
<vcoreSeconds>2</vcoreSeconds>
<preemptedResourceMB>0</preemptedResourceMB>
<preemptedResourceVCores>0</preemptedResourceVCores>
<numNonAMContainerPreempted>0</numNonAMContainerPreempted>
<numAMContainerPreempted>0</numAMContainerPreempted>
<resourceRequests>
<capability>
<memory>1408</memory>
<virtualCores>1</virtualCores>
</capability>
<emrLabel>CORE</emrLabel>
<nodeLabelExpression/>
<numContainers>0</numContainers>
<priority>
<priority>0</priority>
</priority>
<relaxLocality>true</relaxLocality>
<resourceName>*</resourceName>
</resourceRequests>
</app>
```

Now this shows `runningContainers` as `1` and `sparklyr` can use `amHostHttpAddress` to communicate with the node... at which time `sparklyr client` connects and the app changes to:

```xml
<app>
<id>application_1509474750063_0067</id>
<user>hadoop2</user>
<name>sparklyr.Shell</name>
<queue>default</queue>
<state>RUNNING</state>
<finalStatus>UNDEFINED</finalStatus>
<progress>10.0</progress>
<trackingUI>ApplicationMaster</trackingUI>
<trackingUrl>
http://ip-10-43-8-113.us-west-2.compute.internal:20888/proxy/application_1509474750063_0067/
</trackingUrl>
<diagnostics/>
<clusterId>1509474750063</clusterId>
<applicationType>SPARK</applicationType>
<applicationTags/>
<startedTime>1509563844214</startedTime>
<finishedTime>0</finishedTime>
<elapsedTime>76264</elapsedTime>
<amContainerLogs>
http://ip-10-46-7-95.us-west-2.compute.internal:8042/node/containerlogs/container_1509474750063_0067_01_000001/hadoop2
</amContainerLogs>
<amHostHttpAddress>ip-10-46-7-95.us-west-2.compute.internal:8042</amHostHttpAddress>
<allocatedMB>11520</allocatedMB>
<allocatedVCores>2</allocatedVCores>
<runningContainers>2</runningContainers>
<memorySeconds>58800</memorySeconds>
<vcoreSeconds>15</vcoreSeconds>
<preemptedResourceMB>0</preemptedResourceMB>
<preemptedResourceVCores>0</preemptedResourceVCores>
<numNonAMContainerPreempted>0</numNonAMContainerPreempted>
<numAMContainerPreempted>0</numAMContainerPreempted>
<resourceRequests>
<capability>
<memory>1408</memory>
<virtualCores>1</virtualCores>
</capability>
<emrLabel>CORE</emrLabel>
<nodeLabelExpression/>
<numContainers>0</numContainers>
<priority>
<priority>0</priority>
</priority>
<relaxLocality>true</relaxLocality>
<resourceName>*</resourceName>
</resourceRequests>
<resourceRequests>
<capability>
<memory>10112</memory>
<virtualCores>1</virtualCores>
</capability>
<nodeLabelExpression/>
<numContainers>0</numContainers>
<priority>
<priority>1</priority>
</priority>
<relaxLocality>true</relaxLocality>
<resourceName>*</resourceName>
</resourceRequests>
</app>
```

Notice that I used EMR, so it's possible that this might be an EMR-specific issue and configuring `sparklyr.yarn.cluster.accepted.timeout` might be enough for some clusters.
