### ISSUE TITLE
consider how to incorporate string-related feature transformers

### ISSUE THREAD

**Issue by kevinushey** [rstudio/sparklyr#104]
We should think about what common string transformations users might want to perform on a Spark dataset, and how we could best make those accessible from R.

**Comment by javierluraschi** [comment]
as in http://spark.apache.org/docs/latest/ml-features.html?

**Comment by kevinushey** [comment]
Right, e.g. the [`Tokenizer`](http://spark.apache.org/docs/latest/ml-features.html#tokenizer)s. Unfortunately, those feature transformers are a bit awkward to use as-is since they return a column vector with row elements being vectors themselves, and those are awkward to interact with from the R side.

However, we might want to build an interface on top of that, for e.g. extracting data from a column in a structured way, or splitting in a structured way, etc.

**Comment by kevinykuo** [comment]
Think this is mostly solved now, closing.
