### ISSUE TITLE
Can't install sparklyr

### ISSUE THREAD

**Issue by Benknightdark** [rstudio/sparklyr#105]
Hello, I can't install sparlyr. And, here is my error message and R version infomation, please help me . Thanks .
![image](https://cloud.githubusercontent.com/assets/5799487/16793958/6627c768-4907-11e6-9036-3e46829933f4.png)

**Comment by javierluraschi** [comment]
@Benknightdark I would recommend manually installing the `testthat` package, let us know if there is a problem afterwards.

**Comment by Benknightdark** [comment]
@javierluraschi , I have installed the testthat package , but it is still output the error message
![image](https://cloud.githubusercontent.com/assets/5799487/16794260/2cd552d0-4909-11e6-8cfd-69fde294e9a9.png)

**Comment by javierluraschi** [comment]
@Benknightdark try uninstalling `testthat`, reinstalling and re-starting your r session.

BTW. That `testthat` version looks really old, I'm on version`1.0.2`.

**Comment by Benknightdark** [comment]
@javierluraschi  I  change the R version  to 3.2.5 and update the testthat to latest version , and  install sparklyr again. But there is still error
![image](https://cloud.githubusercontent.com/assets/5799487/16794806/92887780-490c-11e6-9e55-6627dd560506.png)

**Comment by javierluraschi** [comment]
@Benknightdark you are past the testthat issue. Please install the 'config' package from CRAN and the sparkapi package using:

devtools::install_github("rstudio/sparkapi")

That said, in not sure why you are hitting these issues since devtools should be installing these dependencies for you. Once we move this package to CRAN, installation will be significantly easier.

**Comment by Benknightdark** [comment]
@javierluraschi ,thanks for your help .But , I install the config and sparkapi package and then install the sparklyr package , but  there is some comfused error message 
![image](https://cloud.githubusercontent.com/assets/5799487/16795946/97053ad6-4912-11e6-946a-9559902a8edc.png)

I can't understand the latest DBI package version is 0.3.1, but the error message said, it need >0.3.1 version DBI package

**Comment by javierluraschi** [comment]
@Benknightdark which versions of `devtools` do you have (run `packageVersion("devtools")`, if it's not `1.12.0` run `install.packages("devtools")`; afterwards, retry reinstalling `sparklyr`

If that doesn't work, keep installing the package dependencies, from the last error, you would have to install `DBI` package as well.

**Comment by kevinushey** [comment]
It's possible that R is being picky about `testthat` not being on a separate line. I'll modify the `sparkapi` sources to resolve this.

**Comment by Benknightdark** [comment]
@javierluraschi  Thansk for your help, after I install the latest version  `devtools `from github , and then,  I finally install the `sparlyr` successfully

**Comment by javierluraschi** [comment]
@Benknightdark good to hear this! Once this gets to CRAN, the installation will get much easier, thanks for holding on through this.
