### ISSUE TITLE
Improve sample_n error comment for Spark < 2.x

### ISSUE THREAD

**Issue by FavioVazquez** [rstudio/sparklyr#1050]
We noticed that with Spark < 2.x the function sdf_sample will work. So this could be a more useful suggestion for the user.

```r
spark_version <- "1.6.0"
sc <- spark_connect(master = "yarn-client", version = spark_version)
data <- data %>% sample_n(size = 10, replace = T) 
```

It returns a table with 0 registers. 

So we used sdf_sample() and it worked.

Blame @jared275.

The PR that solves this is: #1048. 

utils::sessionInfo() (Most of it is private)

R version 3.3.2 (2016-10-31) Platform: x86_64-redhat-linux-gnu (64-bit) Running under: Red Hat Enterprise Linux Server release 6.8 (Santiago)

tidyr_0.4.1 dplyr_0.5.0 DBI_0.5-1 sparklyr_0.5.1 loaded via a namespace (and not attached).

**Comment by javierluraschi** [comment]
PR resolved this one.
