### ISSUE TITLE
Conversion between R and Scala

### ISSUE THREAD

**Issue by schlichtanders** [rstudio/sparklyr#1058]
Dear sparklyr team,

according to some tries and errors on my side, I found out that 
- a ``scala Map`` seems to be well translateable to a ``R named list``
- however a ``R named list`` will be translated to an java Array which is recognized as ``scala Seq`` of respective Type, i.e. it looses its name information
- a ``R environment`` in fact gets translated to ``java Map``, which however unfortunately does not translate that easily to a scala Map

These three observations together suggest to me that:
1. ``scala Maps`` as well ``java Maps`` should be translated to ``R environments`` instead of ``R lists``
1. ``scala Maps`` might be very much preferable over ``java Maps`` as the translation of ``R environments``, just because all suggested examples of extending sparklyr use scala code and not java

what do you think?

**Comment by javierluraschi** [comment]
For (2), we could make a change in [here](https://github.com/rstudio/sparklyr/blob/master/java/spark-1.5.2/serializer.scala#L178-L188); that said, that change would be risky and could change users code. A safer approach would be to introduce something like `ensure_scala_map()` and `ensure_java_map()`.

(1) would also be risky to change, but rather, might be better to encourage users to use `as.environment()` and `as.list()`.

@schlichtanders could you explain a bit more how were you planning to use this and if having `ensure_scala_map()` and `ensure_java_map()` would be sufficient?

**Comment by schlichtanders** [comment]
Thanks for you comments,
for (2) definitely ``ensure_scala_map()`` and ``ensure_java_map()`` are totally sufficient. (This already exists [on scala side](https://docs.scala-lang.org/overviews/collections/conversions-between-java-and-scala-collections.html), and I am using it to circumvent the odd behaviour). No functionality is missing at all. It is just that it seems unexpected. Sparklyr seems focussed on Scala rather than Java, but still this method you are referencing returns a ``java.util.Map[Object, Object]``. Why? Even the function is written scala. I feel like I miss an important information the one who wrote that code had to consider.

for (1) it is even not only unexpected, but seems inconsistent to me. Again, of course no functionality is lost in principle, but it looks just unexpected, even unwanted.

I never managed a package used by more than a couple of people, so I don't know really about the drawbacks of changing this kind of code. I expect only a few users use this and they had to spend some time to get into sparklyr's details so that they are able to fix everything quite fast.

Having a clean and consistent interface between R and Scala via sparklyr would be a great feature I think. Please, don't underestimate this.

**Comment by schlichtanders** [comment]
can someone explain why the current version explicitly converts to a Java Map?

**Comment by schlichtanders** [comment]
The conversion to java.util.Map is now becoming more crucial as there are issues with scala-java converters and Serializability, which is only fixed for Scala 2.12 https://issues.scala-lang.org/browse/SI-8911

furthermore I realiazed that it is not possible to write a wrapper on R site which guarantees a scala map, as this is immediately back converted to a named_list...

the current workaround seems to be to hardcode two methods for each functionality on scala side: one which accepts java.utils.Map and one which accepts a normal scala.collections.Map

**Comment by nathaneastwood** [comment]
This is possibly linked to #1324?

**Comment by vidhyamanisankar** [comment]
Hi Sparklyr Team,
aMap <- invoke_new(sc,"java.util.HashMap")  is giving a R list instead of **spark_jobj in Environment**. Here 'sc' is a spark connection.  
Is there any work around to convert 'R named list' to 'Java Map' then scala mutable Map ? 

Getting this error:
_Error: Unable to retrieve a spark_connection from object of class list_

Code:
`x <- c("DEF_X13_val1","DEF_X13_val2")
  names(x) <- c("JQ2Y","JQ32")
  amap <- invoke_new(sc, "java.util.HashMap")
  lapply(
    seq_along(x),
    FUN = function(y,n,i) {
      invoke(amap, "put",key = n[[i]],value = y[[i]])
    },y=x, n=names(x)
  )
 `

**Comment by dkincaid** [comment]
Seems like others have run into this problem working with Map objects too with no solution thus far. I'm working on a Spark NLP extension and am currently stuck trying to call a method on a Scala object that takes a Map[String, String] as an argument type. I have so far been unsuccessful finding an R object that will work. The sparklyr web page on extensions seems to say that an environment type should be used, but I still get a "No matched method found for class" error using it. 

Has anyone figured out how to work with Scala Map's when required?

**Comment by kevinykuo** [comment]
@dkincaid taking a look to see if the change to serializing environments as Scala `Map` would break existing tests. I feel like this change would unblock more people than it breaks. The other leg of the trip (Scala -> R) we can probably keep as is, since it's pretty easy to convert a list to an environment.
