### ISSUE TITLE
Dynamic column names 

### ISSUE THREAD

**Issue by Jiang-Li** [rstudio/sparklyr#1062]
In dplyr, the column name can be represented by a variable. For example, if I want to replace the value less than 0.5 as 0:

```
library(dplyr)

data <- data.frame(group = sample(c("A", "B"),size = 10, replace = T),
                  value = rnorm(10))

var <- "value"
data %>% mutate( !!var := ifelse(
  .[[var]] < 0.5,
  0,
  .[[var]] 
))
```

I cannot do this in sparklyr. Error: org.apache.spark.sql.catalyst.parser.ParseException was reported.
```
conf <- spark_config()
conf$`sparklyr.shell.driver-memory` <- "8G"  
conf$spark.memory.fraction <- 0.8
sc <- spark_connect(master = "local", config = conf, version = "2.2.0")

dt <- copy_to(sc, data, "test", overwrite = TRUE)

var <- "value"
dt %>% mutate( !!var := ifelse(
  .[[var]] < 0.5,
  0,
  .[[var]] 
))
```

Any suggestions?

Here is my system information:

R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2      dplyr_0.7.3.9000  sparklyr_0.6.2    data.table_1.10.4
[5] h2o_3.10.5.2     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12     dbplyr_1.1.0     compiler_3.4.1   plyr_1.8.4       bindr_0.1       
 [6] bitops_1.0-6     base64enc_0.1-3  tools_3.4.1      digest_0.6.12    jsonlite_1.5    
[11] tibble_1.3.4     nlme_3.1-131     lattice_0.20-35  pkgconfig_2.0.1  rlang_0.1.2     
[16] psych_1.7.5      shiny_1.0.5      DBI_0.7          rstudioapi_0.6   yaml_2.1.14     
[21] parallel_3.4.1   withr_2.0.0      stringr_1.2.0    httr_1.3.1       rappdirs_0.3.1  
[26] rprojroot_1.2    grid_3.4.1       glue_1.1.1       R6_2.2.2         foreign_0.8-69  
[31] purrr_0.2.3      tidyr_0.7.0      reshape2_1.4.2   magrittr_1.5     backports_1.1.0 
[36] htmltools_0.3.6  assertthat_0.2.0 mnormt_1.5-5     mime_0.5         xtable_1.8-2    
[41] httpuv_1.3.5     config_0.2       stringi_1.1.5    lazyeval_0.2.0   RCurl_1.95-4.8  
[46] broom_0.4.2

**Comment by JohnMount** [comment]
Roughly `.[[var]]` is a column of values, but what `dplyr` needs for `spark` is the name of the column as a symbol (not as values).  With in-memory systems, values and names are fairly interchangeable.  But with `Spark`/`Sparklyr` the distinction is a bit stronger.  The other issue is for the value parts the short-cut of using a string as a symbol for `!!` fails, and you have to use a symbol (as I show below in the non-working and then working example).

``` r

suppressPackageStartupMessages(library("dplyr"))
#> Warning: package 'dplyr' was built under R version 3.4.2
packageVersion("dplyr")
#> [1] '0.7.4'
library("sparklyr")
#> Warning: package 'sparklyr' was built under R version 3.4.2
packageVersion("sparklyr")
#> [1] '0.6.3'
conf <- spark_config()
conf$`sparklyr.shell.driver-memory` <- "8G"  
conf$spark.memory.fraction <- 0.8
sc <- spark_connect(master = "local", config = conf, version = "2.2.0")

data <- data.frame(group = sample(c("A", "B"),size = 10, replace = T),
                   value = rnorm(10))
dt <- copy_to(sc, data, "test", overwrite = TRUE)

var <- "value"
dt %>% mutate( !!var := ifelse(
  !!var < 0.5,
  0,
  !!var 
))
#> # Source:   lazy query [?? x 2]
#> # Database: spark_connection
#>    group value
#>    <chr> <chr>
#>  1     B value
#>  2     B value
#>  3     B value
#>  4     A value
#>  5     A value
#>  6     A value
#>  7     B value
#>  8     A value
#>  9     B value
#> 10     B value
#> # ... with more rows

var <- rlang::sym("value")
dt %>% mutate( !!var := ifelse(
  !!var < 0.5,
  0,
  !!var 
))
#> # Source:   lazy query [?? x 2]
#> # Database: spark_connection
#>    group      value
#>    <chr>      <dbl>
#>  1     B  0.2167239
#>  2     B -0.9342853
#>  3     B  1.6992893
#>  4     A -0.2549944
#>  5     A  2.3146143
#>  6     A -0.5073107
#>  7     B  1.2174802
#>  8     A -1.2117536
#>  9     B  1.6511656
#> 10     B -0.9806912
#> # ... with more rows

spark_disconnect(sc)
```

**Comment by Jiang-Li** [comment]
Thanks! I got the same results on my side. However, the assignment of value is still not correct; i.e. the number less than 0.5 should be 0.

**Comment by kevinykuo** [comment]
Another repro:

```
var <- rlang::sym("value")
set.seed(100)
df <- dbplyr::memdb_frame(group = sample(c("A", "B"), size = 10, replace = T),
                    value = rnorm(10))
df %>%
  mutate(!!var := ifelse(!!var < 0.5, 0, !!var)) %>%
  head()
# Source:   lazy query [?? x 2]
# Database: sqlite 3.19.3 [:memory:]
group       value
<chr>       <dbl>
1     A  0.31863009
2     A -0.58179068
3     B  0.71453271
4     A -0.82525943
5     A -0.35986213
6     A  0.08988614
```

@lionel- do you know if this relates to an existing issue? we can file one in dplyr if not.

**Comment by JohnMount** [comment]
I got so caught up in the `rlang` stuff I failed to notice the second version did not work.

**Comment by lionel-** [comment]
There are two problems here:

```r
!!var < 0.5
```

- You are trying to compare a string to a number with `<`. What you want is to compare the column values, so you should unquote a symbol that will evaluate to the column rather than a string.

- `!` has low precedence so it will capture almost everything on its right-hand side. You need to use parentheses to adjust for operator precedence:

```r
((!! sym(var)) < 0.5
```

Or use prefix form

```r
UQ(sym(var)) < 0.5
```

**Comment by kevinykuo** [comment]
Thanks @lionel- !

This seems to work

```
df %>%
  mutate(!!var := ifelse(UQ(var) < 0.5, 0, !!var)) %>%
  head()
# Source:   lazy query [?? x 2]
# Database: sqlite 3.19.3 [:memory:]
group     value
<chr>     <dbl>
1     A 0.0000000
2     A 0.0000000
3     B 0.7145327
4     A 0.0000000
5     A 0.0000000
6     A 0.0000000
```

@Jiang-Li

**Comment by lionel-** [comment]
Great!

To debug this kind of issue it's helpful to wrap the whole statement with `expr()`. This way you can look at the result of unquoting:

```r
expr(
  df %>% mutate(!!var := ifelse(UQ(var) < 0.5, 0, !!var))
)
```

**Comment by JohnMount** [comment]
Yes here is my re-run without the forgetting the parens bug:

``` r
suppressPackageStartupMessages(library("dplyr"))
#> Warning: package 'dplyr' was built under R version 3.4.2
packageVersion("dplyr")
#> [1] '0.7.4'
library("sparklyr")
#> Warning: package 'sparklyr' was built under R version 3.4.2
packageVersion("sparklyr")
#> [1] '0.6.3'
conf <- spark_config()
conf$`sparklyr.shell.driver-memory` <- "8G"  
conf$spark.memory.fraction <- 0.8
sc <- spark_connect(master = "local", config = conf, version = "2.2.0")

data <- data.frame(group = sample(c("A", "B"),size = 10, replace = T),
                   value = rnorm(10))
dt <- copy_to(sc, data, "test", overwrite = TRUE)

var <- rlang::sym("value")

data %>% mutate( !!var := ifelse(
  (!!var) < 0.5,
  0,
  !!var 
))
#>    group     value
#> 1      B 0.0000000
#> 2      B 0.8537737
#> 3      A 1.2059743
#> 4      B 0.0000000
#> 5      B 0.0000000
#> 6      A 0.0000000
#> 7      A 0.0000000
#> 8      B 0.0000000
#> 9      B 0.0000000
#> 10     B 0.7956946

dt %>% mutate( !!var := ifelse(
  (!!var) < 0.5,
  0,
  !!var 
))
#> # Source:   lazy query [?? x 2]
#> # Database: spark_connection
#>    group     value
#>    <chr>     <dbl>
#>  1     B 0.0000000
#>  2     B 0.8537737
#>  3     A 1.2059743
#>  4     B 0.0000000
#>  5     B 0.0000000
#>  6     A 0.0000000
#>  7     A 0.0000000
#>  8     B 0.0000000
#>  9     B 0.0000000
#> 10     B 0.7956946
#> # ... with more rows


data %>% mutate( !!var := if_else(
  (!!var) < 0.5,
  0,
  !!var 
))
#>    group     value
#> 1      B 0.0000000
#> 2      B 0.8537737
#> 3      A 1.2059743
#> 4      B 0.0000000
#> 5      B 0.0000000
#> 6      A 0.0000000
#> 7      A 0.0000000
#> 8      B 0.0000000
#> 9      B 0.0000000
#> 10     B 0.7956946

dt %>% mutate( !!var := if_else(
  (!!var) < 0.5,
  0,
  !!var 
))
#> # Source:   lazy query [?? x 2]
#> # Database: spark_connection
#>    group     value
#>    <chr>     <dbl>
#>  1     B 0.0000000
#>  2     B 0.8537737
#>  3     A 1.2059743
#>  4     B 0.0000000
#>  5     B 0.0000000
#>  6     A 0.0000000
#>  7     A 0.0000000
#>  8     B 0.0000000
#>  9     B 0.0000000
#> 10     B 0.7956946
#> # ... with more rows


spark_disconnect(sc)
```

Also notice the bug that the remote table is saying "with more rows" when it has displayed all 10 out of 10 rows.

**Comment by Jiang-Li** [comment]
Cool! Thank you all!
