### ISSUE TITLE
ml_save and ml_load fail HDFS Error

### ISSUE THREAD

**Issue by YoNoFui** [rstudio/sparklyr#1070]
We've encountered an error in the loading and saving methods for ML. 

```r
spark_version <- "1.6.0"
sc <- spark_connect(master = "yarn-client", version = spark_version)

# Here is the model ....
#......
# Saving model
ml_save(model, "directory_hdfs")
```

returns:

```r
Error in gzfile(file, mode) : cannot open the connection In addition: Warning message: In gzfile(file, mode) : cannot open compressed file 'directory_hdfs/metadata.rds', probable reason 'No such file or directory'
```

We will create a PR with a possible solution.

Related: #336.

Blame: @faviovazquez.

utils::sessionInfo() (Most of it is private)

R version 3.3.2 (2016-10-31) Platform: x86_64-redhat-linux-gnu (64-bit) Running under: Red Hat Enterprise Linux Server release 6.8 (Santiago)

tidyr_0.4.1 dplyr_0.5.0 DBI_0.5-1 sparklyr_0.5.1 loaded via a namespace (and not attached).

**Comment by kevinykuo** [comment]
@YoNoFui This should work better now in devel. Could you give it a try?

**Comment by kevinykuo** [comment]
Close to track in https://github.com/rstudio/sparklyr/issues/1088
