### ISSUE TITLE
Why the head() function is so slow for large datasets?

### ISSUE THREAD

**Issue by jadermcs** [rstudio/sparklyr#1077]
When I run things like:

``` R
massive_data <- spark_read_csv(sc, name, path, memory = FALSE) #120GB+
massive_data %>% head()
```
takes 7minutes~, as I just need the first n rows, why this takes so long?

**Comment by kevinykuo** [comment]
Try setting `infer_schema = FALSE` when reading in the csv

**Comment by kevinykuo** [comment]
Closing, feel free to file another one if this is still an issue.
