### ISSUE TITLE
structured streaming support

### ISSUE THREAD

**Issue by geoHeil** [rstudio/sparklyr#1082]
Spark now supports structured streaming in sparkR as outlined https://spark.apache.org/docs/latest/structured-streaming-programming-guide.html when you select a code snippet with R code.

When will sparklyR support this as well?

**Comment by javierluraschi** [comment]
We've been keeping an eye on streaming under our big features board: https://github.com/rstudio/sparklyr/projects/1. Closing this one to track progress/suggestions here instead: https://github.com/rstudio/sparklyr/issues/1131
