### ISSUE TITLE
ml_load on a cluster

### ISSUE THREAD

**Issue by tKozDrivin** [rstudio/sparklyr#1088]
We are having issues loading a model into out spark cluster. The model was trained using sparklyr and saved using a function ml_save
ml_save(model, file = "home/cluster/model")

After saving we would like to load this model for predictions but we keep getting the error below. 
model <- ml_load(sc, file = "home/cluster/model")
Error in gzfile(file, "rb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file 'home/cluster/model/metadata.rds', probable reason 'No such file or directory'

On a different note this functionality works when we do it using a local spark cluster on a local machine started using spark_connect( 
                    master = "local",
                    version = "2.2.0", 
                    config = config)

**Comment by kevinykuo** [comment]
Hey @tKozDrivin thanks for the report! This should become much easier once https://github.com/rstudio/sparklyr/issues/944 is addressed over the next few days.

**Comment by tKozDrivin** [comment]
Got it thanks. Any workarounds currently for this? Or any current docs that will let us know what will be developed as part of 944?

**Comment by kevinykuo** [comment]
The PR is currently brewing here: https://github.com/rstudio/sparklyr/pull/1079

Feel free to check it out before it's merged. For model persistence we're enabling the saving and loading of pipeline models which will be able to interop with the Scala and PySpark API. Docs are scarce at the moment but more will be coming. I'd recommend looking at the unit tests for some examples.

**Comment by tKozDrivin** [comment]
Cool thanks. So this will enable us to build the model using Sparklyr somewhere else and save using ml_save and deploy in production on a cluster using ml_load? Will all mlib algorithms be supported?

**Comment by kevinykuo** [comment]
That's correct. All supervised learning and clustering algorithms and ALS and most feature transformers will be implemented at the first iteration. We also plan to have FP-growth and the rest of the feature transformers supported prior to the 0.7 release.

**Comment by tKozDrivin** [comment]
Awesome. Thanks for the great work guys!!!

**Comment by kevinykuo** [comment]
@tKozDrivin the PR has been merged. Could you try giving save/load a shot in the cluster environment?

**Comment by jajimenezf** [comment]
Hey @kevinykuo.

I'm still having the same problem

Error in gzfile(file, "rb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file 'path/metadata.rds', probable reason 'No such file or directory'

I'm attaching the session info

R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] foreach_1.4.3  SparkR_2.2.0   sparklyr_0.6.4 Rcpp_0.12.14

**Comment by kevinykuo** [comment]
@jajimenezf you'll need to use the dev version and save/load the model again. You can install via `devtools::install_github("rstudio/sparklyr")`.

**Comment by jajimenezf** [comment]
Hi @kevinykuo thank you so much for the suggestion. I tried it and I was able to save the file without any problem but I'm not being able to load it yet.

I'm getting the following error:

Error in open.connection(con, "rb") : cannot open the connection
In addition: Warning message:
In open.connection(con, "rb") :
  cannot open file '/tmp/model/metadata/part-00000': No such file or directory
 
but when I check the folder using "ls /tmp/model/metadata" I can see the following files:

path							    name		     size
/tmp/model/metadata/_SUCCESS	    _SUCCESS	     0
/tmp/model/metadata/part-00000     part-00000	     206

Aditional information:

I'm training a elastic net model using databricks and I'm saving the model using the following script
`results_model <- "model"
output_results_path <- file.path('','tmp',results_model)
ml_save(enet.model, output_results_path, overwrite = TRUE)`

**Comment by kevinykuo** [comment]
@jajimenezf could you update to the latest devel and see if your code works locally (with a subset of data if it's large)? Want to see if it's a Databricks specific issue so we can better look into it.

I'm also guessing you passed `sc` to `ml_load()`.

**Comment by kevinykuo** [comment]
There seems to be some issues reading models saved into HDFS. Will investigate.

**Comment by kevinykuo** [comment]
@tKozDrivin @jajimenezf @yonofui

A fix to this has ben merged to master. We expect to have a CRAN release next week. If you're still having issues with saving/loading please file another issue and we'll prioritize it.

Note that if you're working on a cluster, you'll need to write to/load from hdfs/wasb/etc. If you saved a pipeline locally and want to load it in the cluster, you'll have to put the data into distributed storage before you can access it. Similarly, if you save a model while working in e.g. `yarn-client` mode, you'll need to explicitly move the model directory to local filesystem before you can load it via local mode. These are Spark limitations that we can investigate working around in the future, but for the time being cluster-save/cluster-load and local-save/local-load should work.
