### ISSUE TITLE
Pull data from remote Cassandra database with sparklyr?

### ISSUE THREAD

**Issue by JakeRuss** [rstudio/sparklyr#1091]
Hi guys, 

Is it currently possible to use `sparklyr` to connect and read data from a remote Cassandra database? I've read the other Cassandra issues in this repo, but since they focus on connecting to Cassandra locally, I'm still confused as to whether the remote connection is currently supported. 

I'll post the code I'm trying below, but I should mention that the Cassandra database I want to connect to is part of a DataStax Enterprise.

Also, would port forwarding help me here? If I forwarded the remote port 9042 to my local 9043 (or something else), would that improve my chances?

```
library(sparklyr)
library(dplyr)

config <- spark_config()
config$`sparklyr.defaultPackages`             <- c("datastax:spark-cassandra-connector:1.6.9-s_2.10")
config$`spark.cassandra.connection.host` <- "spark://localhost:9043" 

sc <- spark_connect(master         = "local",
                    version        = "1.6.0",
                    hadoop_version = 2.6, 
                    config         = config)

cass_tbl <- sc %>%
  spark_read_source(name    = "employees", 
                    source  = "org.apache.spark.sql.cassandra", 
                    options = list(keyspace = "test",
                                   table    = "employees"))
```

**Comment by sdanielzafar** [comment]
Yes you can, use `library(crassy)`

**Comment by JakeRuss** [comment]
Hi @sdanielzafar, thanks for the pointer. I did have a look at `crassy` before posting here. The thing I'm not understanding is how to properly establish the **remote** connection to Cassandra. For security I can't connect to the server directly, but I'm forwarding the remote port `9042` over ssh to my local `9043` (and let's assume I'm using the right connector, I can try others).

But I've tried setting the configuration in several ways without success,

A)
```
config <- spark_config()
config$`sparklyr.defaultPackages`        <- c("datastax:spark-cassandra-connector:1.6.9-s_2.10")
config$`spark.cassandra.connection.host` <- "spark://localhost:9043"
```

B)
```
config <- spark_config()
config$`sparklyr.defaultPackages`        <- c("datastax:spark-cassandra-connector:1.6.9-s_2.10")
config$`spark.cassandra.connection.host` <- "localhost"
config$`spark.cassandra.connection.port` <- "9043"
```

C)
```
config <- spark_config()
config$`sparklyr.defaultPackages`        <- c("datastax:spark-cassandra-connector:1.6.9-s_2.10")
config$`spark.cassandra.connection.host` <- "localhost:9043"
```
I would be happy for the moment to simply read the Cassandra table into Spark. While `crassy` may help me achieve this goal in the short term, a separate issue is whether this connection method will be part of the long term path for `sparklyr`. Eventually, I plan to use this code in production so I'd like to follow the guidelines that are (or will be) officially supported by `sparklyr`.

**Comment by JakeRuss** [comment]
As it turns out, if you correctly specify the remote port forwarding command, then the right `sparklyr` config syntax is `B)`. Pulling the data from Cassandra was trivial from there.

**Comment by abdkumar** [comment]
@JakeRuss did you find any solution for commenting remote Cassandra using sparklyr?

**Comment by JakeRuss** [comment]
@abdkumar Yes, as I mentioned above, you have to do remote port forwarding over ssh tunnel. Forward the remote port 9042 to your local's port 9043 and then the following config will work. 

```
config <- spark_config()
config$`sparklyr.defaultPackages`        <- c("datastax:spark-cassandra-connector:1.6.9-s_2.10")
config$`spark.cassandra.connection.host` <- "localhost"
config$`spark.cassandra.connection.port` <- "9043"
```
Best of luck!
