### ISSUE TITLE
Combining multiple paths into a single spark_read_csv call

### ISSUE THREAD

**Issue by amir-ghasemi** [rstudio/sparklyr#1094]
In Spark 2.0 I can combine several file paths into a single load().

How can I achieve this with sparklyr's spark-read-csv? Using a similar syntax on the path variable doesn't seem to work.

**Comment by kevinykuo** [comment]
It should just work. Could you tell us a bit more about the directory structure and the Scala and R code you tried?

**Comment by amir-ghasemi** [comment]
You are right. Looks like wildcards can be used similar to SparkR interface so it's actually easy to do. Thank you!

**Comment by Giannettig** [comment]
hi guys can you add this to the documentation? 

this: does not indicate at all that I can use this feature to load multiple csv 

path | The path to the file. Needs to be accessible from the cluster. Supports the "hdfs://", "s3a://" and "file://"protocols.
-- | --
