### ISSUE TITLE
spark_apply() can not find Rscript

### ISSUE THREAD

**Issue by JohnMount** [rstudio/sparklyr#1099]
I can run a [simple `spark_apply()` script](https://github.com/WinVector/ODSCWest2017/blob/master/SparklyRMachineLearning/Exercises/solutions/06-Spark-Extension.Rmd) on my local machine, and it works find.  However if I run the same script on a Hortonworks cluster I get the following error:

```
## Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 13.0 failed 4 times, most recent failure: Lost task 0.3 in stage 13.0 (TID 16, mksd1sldscbs005.c.iron-potion-771.internal, executor 2): java.io.IOException: Cannot run program "Rscript": error=2, No such file or directory
```

I believe there is an Rscript binary in `/usr/local/bin/Rscript`, but I don't see any in the `Spark` software install directory (I don't see `Rscript` in the `Spark` software install directory on my local machine either).  For control of `R` software version should not `spark_apply()` only use `R` binaries found in the `Spark` install (perhaps use `R` in batch mode if there is no `Rscript`)?

Link to stand-alone example script [here](https://github.com/WinVector/ODSCWest2017/blob/master/SparklyRMachineLearning/Exercises/solutions/06-Spark-Extension.Rmd).

I guess I am asking: is spark_apply() supposed to use the `R` that is part of the `Spark` install (and match versions), or is it supposed to use an `R` that is separately globally installed on the worker nodes?

**Comment by AjarKeen** [comment]
I think `sparklyr` needs R to be installed uniformly (same OS, location, and version) on all nodes (master & worker).

**Comment by dalloliogm** [comment]
If you don't have the admin rights to install R on all worker nodes, you can create a conda environment containing R and any other package, and distributed it using Yarn. See Option 2 here: https://blog.cloudera.com/blog/2017/09/how-to-distribute-your-r-code-with-sparklyr-and-cdsw/
