### ISSUE TITLE
Documentation question: is there any way to control how many rows spark_apply() cuts data into?

### ISSUE THREAD

**Issue by JohnMount** [rstudio/sparklyr#1104]
Documentation question: is there any way to control how many rows spark_apply() cuts data into?

On my small machine it seems to work in about one quarter million row blocks (which is fine), but on a production server cluster it seems to send all of the rows to a single worker (which I do not want to happen).

Is there a control that says what the maximum number of rows per-chunk are?  Or is this something we can achieve through the `group_by` argument somehow?

**Comment by AjarKeen** [comment]
I think the main knobs you have to control partitioning are:

1. `sdf_repartition` lets you partition by the unique values of one column in Spark 2.0+.

2. `sdf_partition` lets you partition with random weighted sampling, e.g. for train/test splits.

3. Set `spark.dynamicAllocation.enabled: true` in your conf, and Spark will handle data splitting and number of executors itself. This is fine if you want parallelism but aren't too concerned about how much.

**Comment by javierluraschi** [comment]
Right! Also, worth adding that `spark_apply()` transfers data to each worker role in-memory; therefore, `spark_apply()` really benefits from creating many small partitions using the partition functions mentioned by AjarKeen.

I wouldn't recommend using `group_by` for the purpose of repartitioning, `sdf_repartition` or `sdf_partition` should be preferred here.

Closing this one seems the question seems answered.
