### ISSUE TITLE
Better interface for passing context to spark_apply()

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/sparklyr#1128]
See https://github.com/rstudio/sparklyr/pull/1107

**Comment by javierluraschi** [comment]
@kevinykuo parameters on the closure are currently not named: https://github.com/rstudio/sparklyr/blob/master/R/worker_apply.R#L84-L98

So the example from #1107 already works an expected:

```r
spark_apply(sdf_len(sc, 1), function(e, a) {
   e + a
}, context = {a <- 1})
```
```
# Source:   table<sparklyr_tmp_4b4a10f5d530> [?? x 1]
# Database: spark_connection
     id
  <dbl>
1     2
```

Maybe at some point they were named parameters? In any case, looks like this is good for now.

**Comment by jyk** [comment]
How the syntax of context will look like in case of several parameters ?

i.e. Adding "b":
spark_apply(sdf_len(sc, 1), function(e, a, b) {
   e + a + b
}, context = {a <- 1} ?????   )
