### ISSUE TITLE
append to existing table

### ISSUE THREAD

**Issue by jwijffels** [rstudio/sparklyr#113]
What would be the preferred way to append a data.frame to an existing spark table.
I see that sparklyr depends on DBI > 0.4 which has dropped the `append` argument of `dbWriteTable`
This doesn't seem to work. Is there another way?

```
sc <- spark_connect(master = "local")
x <- Lahman::Batting
batting_tbl <- copy_to(sc, x, "batting", memory = FALSE, overwrite = TRUE)
dbWriteTable(sc, "batting", x, append = TRUE)
sqlAppendTable(sc, "batting", x, row.names = FALSE)
```

**Comment by kevinushey** [comment]
You should be able to use `rbind` for this currently:

```
batting_tbl <- copy_to(sc, x, "batting", memory = FALSE, overwrite = TRUE)
doubled <- rbind(batting_tbl, batting_tbl, name = "double")
```

We can also look into implementing a method for `sqlAppendTable`.

**Comment by javierluraschi** [comment]
@jwijffels I believe Kevins suggestion addresses this, but feel free to reactivate if this is not sufficient.
