### ISSUE TITLE
Streaming

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#1131]
See:
- https://github.com/rstudio/sparklyr/issues/1082
- https://github.com/rstudio/sparklyr/issues/1509

Related:
- https://github.com/rstudio/sparklyr/issues/1545

**Comment by harryprince** [comment]
+ integrate with kafka-10.0

**Comment by javierluraschi** [comment]
Implemented with https://github.com/rstudio/sparklyr/pull/1569
