### ISSUE TITLE
ml_pipeline not found

### ISSUE THREAD

**Issue by pierma63** [rstudio/sparklyr#1136]
Hi, working with Rstudio 3.4.2 and Spark 2.2.0, "local" on Windows, trying to use ml_pipeline() function but looks like it is not there (even help doesn't find docs).

sc <- spark_connect(master = "local", spark_home = "c:\\users\xxxxxxl\\xxxx\\spark",version="2.2.0")
library(dplyr)
library(sparklyr)

 > ml_pipeline()
Error in ml_pipeline() : could not find function "ml_pipeline"

**Comment by kevinykuo** [comment]
@pierma63 are you using the development version of `sparklyr`? The pipeline feature isn't on CRAN yet.

**Comment by pierma63** [comment]
Realized it wasn't in CRAN afterward, then used the dev version . Thanks
