### ISSUE TITLE
Text Mining Guide 404 error?

### ISSUE THREAD

**Issue by pgensler** [rstudio/sparklyr#1145]
It seems like there are some links that are dead, which I'm assuming is from the move to blogdown? Below is what I have found:

text mining guide is not found:
https://spark.rstudio.com/articles/guides-textmining.html

dplyr link does not work:
https://spark.rstudio.com/extensions/

**Comment by kevinykuo** [comment]
Found this through this nav bar on the left on the new site:

https://spark.rstudio.com/guides/textmining/
https://spark.rstudio.com/dplyr/
