### ISSUE TITLE
Links on spark.rstudio.com broken

### ISSUE THREAD

**Issue by tarunparmar** [rstudio/sparklyr#1148]
I noticed some of the links on spark.rstudio.com are now broken.

E.g. http://spark.rstudio.com/reference/sparklyr/latest/ml_tree_feature_importance.html

**Comment by kevinykuo** [comment]
@tarunparmar could you share how you got to that link?

http://spark.rstudio.com/reference/ml_tree_feature_importance/ seems to work

cc @edgararuiz

**Comment by edgararuiz** [comment]
Right, most links changed, but I created what they call "aliases" to make sure that old links got re-routed to the new page.  That was not the case with Reference pages, I'll look into this

**Comment by tarunparmar** [comment]
The links are mostly on the main pages ... e.g. the Machine Learning link on left which takes you here http://spark.rstudio.com/mlib/ and then try clicking on any link on that page.

![image](https://user-images.githubusercontent.com/17690950/33342729-11d4660e-d451-11e7-8f13-03d4144fdbc7.png)

**Comment by edgararuiz** [comment]
Oh, thank you! I was wondering where the link's path was coming from.  I'm half way through putting together a solution for that, so I hope it'll be fixed in short order.  Thanks again!

**Comment by tarunparmar** [comment]
No problem, I now know where the link is taking me anyway :wink:

**Comment by edgararuiz** [comment]
cc @fereshtehRS
