### ISSUE TITLE
extend "Deployment" page with a wider YARN cluster connection description

### ISSUE THREAD

**Issue by MarcinKosinski** [rstudio/sparklyr#115]
What if one does not have spark cluster but has yarn cluster instead? Is there a way to connect to yarn cluster?

For `SparkR` it was very simple and doable from RStudio

http://r-addict.com/2016/04/06/FAQ-SparkR.html#q9-can-i-run-spark-application-locally-or-only-on-yarn-hadoop-cluster

**Comment by jjallaire** [comment]
@javierluraschi I think we need to add some documentation to the "Deployment" page about connecting to yarn clusters as this has come up a number of times.

**Comment by javierluraschi** [comment]
@jjallaire deployments page enhanced with YARN reference and example.

**Comment by jjallaire** [comment]
Great, thanks!

**Comment by MarcinKosinski** [comment]
Thanks guys.

Do I somehow need to specify YARN_DIR or HADDOP_CONF_DIR or any other global/system environemnt If I have more than one YARN cluster and would like to use few of them simultanously?

**Comment by javierluraschi** [comment]
@MarcinKosinski correct, point the `YARN_CONF_DIR` environment variable to the desired cluster config directory.

**Comment by jjallaire** [comment]
Javier should we add that to the documentation as well or can we assume
this knowledge for anyone accessing a YARN cluster?

**Comment by MarcinKosinski** [comment]
I have 4 years experience in R, 1 year experience with yarn clusters configuration via dockers and I would say this is not obvious and not intuitive for regular R users. I would definitely advice you to extend documentation with this information.

Maybe for next time I could provide PR with suggestions on how to extend documentation? Then you'll have to tell me in which directory are you creating your website :)

**Comment by jjallaire** [comment]
The website is here: https://github.com/rstudio/spark.rstudio.com

We would absolutely welcome any and all improvements to our documentation
you can provide!!!!

**Comment by MarcinKosinski** [comment]
Moved to https://github.com/rstudio/spark.rstudio.com/issues/4
