### ISSUE TITLE
Casting variables

### ISSUE THREAD

**Issue by l4mun** [rstudio/sparklyr#116]
Hi,

I would like to know if there is an option yet to cast variable types. I got some numeric columns which are recognized as character ones. Running dataWrangling is ok but when i do a linear regression, due to the fact that factor are binarised, it fails.

Best regards,
Jacques

**Comment by javierluraschi** [comment]
@l4mun for basic variable casts, you could use dplyr, for inaces:

```
copy_to(sc, iris)
tbl(sc, "iris") %>% mutate(SW = as.integer(Sepal_Width))
```

Please update to the latest `sparklyr` version to ensure additional `dplyr` cast operations are avaialble.

**Comment by l4mun** [comment]
I guess i didn't get the last version that's why.

Thank you.

**Comment by javierluraschi** [comment]
Sounds, closing.
