### ISSUE TITLE
Can the sparklyr jars be rebuilt (at least for spark 2 versions)?

### ISSUE THREAD

**Issue by mattpollock** [rstudio/sparklyr#1171]
This will support using read schemas where the data type is `long` given this addition: https://github.com/rstudio/sparklyr/blob/master/inst/livy/spark-1.5.2/sqlutils.scala#L31

Trying to read longs as doubles (using the read schema) seems to cause issues:
```
java.lang.UnsupportedOperationException: org.apache.parquet.column.values.dictionary.PlainValuesDictionary$PlainLongDictionary at org.apache.parquet.column.Dictionary.decodeToDouble(Dictionary.java:60) at org.apache.spark.sql.execution.vectorized.OnHeapColumnVector.getDouble(OnHeapColumnVector.java:375) at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source) at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43) at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395) at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408) 
```

**Comment by javierluraschi** [comment]
My recommendation here would be to deprecate the `schema` parameter in Spark 1.5.2 by checking for the parameter to be not null and the version to be less than 1.6 and calling stop() with an error message.

Very few people are using 1.5.2 and is not officially supported. Most functionality works in 1.5 but we make no claim or guarantee that it will work.

In general, we do support multiple jars per version, so you could special case this for 1.5.2 if you choose to. These are the jars that we compile:

<img width="501" alt="screen shot 2017-12-19 at 7 22 23 am" src="https://user-images.githubusercontent.com/3478847/34164160-b14bb736-e48d-11e7-88f0-d734329b09d0.png">

**Comment by mattpollock** [comment]
I may be confused here. What I'm trying to support is specifying `LongType` for read schemas using spark 2.2 (e.g., like https://github.com/mitre/sparklyr.nested/blob/master/R/data_types.R#L83 but for `long`s)

The only place where I found the `SQLUtils` class was in the `inst/livy/spark-1.5.2` directory and so added a long type there in the PR from the other day. I supposed that the naming convention might be some sort of "as of this version" support or something. Is there a different place where I should make modifications to update `SQLUtils`?

**Comment by kevinykuo** [comment]
Currently the way to make changes to the Scala code is in the `java/` directory, e.g. https://github.com/rstudio/sparklyr/blob/master/java/spark-1.5.2/sqlutils.scala. Then you'll want to run https://github.com/rstudio/sparklyr/blob/master/configure.R to update the other directories appropriately and compile.

Regarding the naming scheme, it works exactly like you guessed, e.g. `spark-VERSION` means the functionality is supported by Spark `VERSION` and above. So if your change only works for 2.2+, you should put it a `spark-2.2.0` folder otherwise it won't compile.

Before release we should move all the 1.5 stuff to the 1.6 folder. (https://github.com/rstudio/sparklyr/issues/1129)

**Comment by mattpollock** [comment]
Thanks very much @kevinykuo. I added a PR with the change (works for any spark version since `long` was always supported by spark) in https://github.com/rstudio/sparklyr/pull/1173. With your help I was able to rebuild `sparklyr` jars for my own use, though a commit (assuming the PR is merged) of rebuilt jars after the merge would make the change more easily used by others.

**Comment by javierluraschi** [comment]
I'll rebuild the jars, thanks for the follow up!

**Comment by mattpollock** [comment]
Thanks very much for the update!
