### ISSUE TITLE
[ft_stop_words_remover()] How to apply custom stopwords?

### ISSUE THREAD

**Issue by iamkbpark** [rstudio/sparklyr#1176]
I do appreciate the new `ft_stop_words_remover()`! Just wondered if there is any way to build additional custom stopwords to use it together with `ft_stop_words_remover()`.
This is how I normally do in R.

` STOP_TOTAL <- unique (c(tm::stopwords('en'), CUSTOM_STOP))`
`CORPUS_CLEAN <- CORPUS_ALL %>%  tm_map (removeWords, STOP_TOTAL)`

I wonder if the similar tactic is available in `sparklyr`. Thank you in advance!

**Comment by kevinykuo** [comment]
If you're using dev sparklyr you can pass a vector to `stop_words`, e.g.
```
sc <- spark_connect(master = "local")
df <- data.frame(words = "I like cats")
df_tbl <- sdf_copy_to(sc, df, overwrite = TRUE)
df_tbl %>%
  ft_tokenizer("words", "tokenized") %>%
  ft_stop_words_remover(input_col = "tokenized", output_col = "clean_words",
                        stop_words = c("i", "like")) %>%
  dplyr::glimpse()
```

You can also augment your stop words with `ml_default_stop_words()`:
```
ml_default_stop_words(sc, "english") %>%
  head()
```

**Comment by iamkbpark** [comment]
It works beautifully! Thank you for your help!
