### ISSUE TITLE
Creating a custom function in scala used after `group_by`

### ISSUE THREAD

**Issue by raphaelvannson** [rstudio/sparklyr#1178]
Hello,

*This is a question, not a bug report.*

I would like to write a custom function in scala and use it in simple `group_by` chain.

The idea is that it would operate exactly like this example:
```
df %>% 
  group_by(column1) %>% 
  summarize(mu = mean(column2))
```

... but I would use `my_custom_function` to calculate the results instead (the custom function would run an optimizer on each group or rows given by `group_by()` and return the last value of the objective function):

```
df %>% 
  group_by(column1) %>% 
  summarize(my_values = my_custom_function(column2))
```

 1. Is this possible?
 2. What are the specifications `my_custom_function()` should have? (Especially its signature and what should it return? I assume just a numeric for the latter).
 3. Is there anything specific which needs to be done to make sure `my_custom_function()` is registered with the Spark backend? (I was thinking of going into the documentation explaining how to create UDFs - hoping it would do the trick).

Thanks!

**Comment by javierluraschi** [comment]
Not possible today, tracked with https://github.com/rstudio/sparklyr/issues/1052
