### ISSUE TITLE
Add Disqus panel to spark.rstudio.com

### ISSUE THREAD

**Issue by MarcinKosinski** [rstudio/sparklyr#118]
Have you thought about Disqus panel on your website - https://disqus.com/ ?
This panel is used in rmarkdown.rstudio.com and is a convenient way of asking simple, quick and short questions, so that one does not have to open issue for every FAQ : )

**Comment by javierluraschi** [comment]
Thanks, will consider this @MarcinKosinski. Short-term plan is to use github issues.
