### ISSUE TITLE
Use dplyr on existing tables within Spark cluster.

### ISSUE THREAD

**Issue by zhf526** [rstudio/sparklyr#119]
If I already have a table (e.g. "accountcapacitydailyv3") in the cluster, how can I pass it to dplyr functions?

I tried this:

```
test <- accountcapacitydailyv3 %>% 
  select(timeperiod, accountname)
```

But it does not work.

**Comment by javierluraschi** [comment]
Is the table already registered as a hive table? If that's the case you can use `tbl()`, for instance:

`tbl(sc, "accountcapacitydailyv3") %>% select()`

**Comment by zhf526** [comment]
Yes. It works!

**Comment by javierluraschi** [comment]
Great! Closing this issue.
