### ISSUE TITLE
Consider officially supporting `features` and `response` arguments in ml_ routines

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/sparklyr#1192]
With the new API we've soft-deprecated `features` and `response` in favor of the formula interface, which supports interactions [among other things](https://spark.apache.org/docs/2.2.0/ml-features.html#rformula). These arguments are still respected for backwards compatibility. I'm thinking about bringing these back as officially supported, mainly for the use case where users manipulate a long features vector. Also, these parameters (either as `response, features`, `y, x`, or variations thereof) are common in other ML APIs.

@edgararuiz thoughts?

**Comment by edgararuiz** [comment]
I'm trying to picture how would that work, any examples?

**Comment by kevinykuo** [comment]
Basically something like
```
ml_linear_regression(mtcars_tbl, response = "mpg", features = c("cyl", "wt"))
```
works but is undocumented (and hence "discouraged"). This issue discusses whether to document this usage and guarantee that it'll work in the future.

**Comment by edgararuiz** [comment]
Doesn't `tensorflow` packages follow a similar way to train models?  If so, I think we may need to keep.

**Comment by kevinykuo** [comment]
Yeah that's what prompted me to revisit this actually. I'll have these documented then so we'll have a somewhat consistent UX.
