### ISSUE TITLE
implement spark_read_feather()

### ISSUE THREAD

**Issue by slopp** [rstudio/sparklyr#126]
Submitted on behalf of McKinsey and QB

**Comment by javierluraschi** [comment]
Well we are planning to support Arrow natively with https://github.com/rstudio/sparklyr/pull/1611, so probably you don't even need to use feather, but if you had to use feature, you should be able to use feather in `sparkl_apply()` to read write from feather and transfer data efficiently. Closing to track with open PR.

**Comment by paristj** [comment]
Thanks Javier! Keep up the great work :)
