### ISSUE TITLE
Handling nulls and NA in dataframes 

### ISSUE THREAD

**Issue by ElianoMarques** [rstudio/sparklyr#127]
Hi there,

I was trying to handle NA and nulls directly against the dataframe without success. 

Perhaps this could be integrated probably as part of the dplyr package?

```
tbl1 = tbl1 %>% mutate( avg_mileage = ifelse(is.null(avg_mileage) | is.na(avg_mileage)  ,20,avg_mileage),
```

tbl1 is a spark dataframe. 
I then collect a sample to memory and check the null in the above feature and realized that is not picking up the NaN. This results in a further down the road error with the ft_bucketizer because it doesn't accept nulls. Spark has the function na.fill which could be another option. Or even add to all ft_ functions the na.fill option which under the hood calls the na.fill option in spark. 

See also this link from the community: https://github.com/apache/spark/pull/13084 

Let me know if this is part of the roadmap or would be. 

Thanks,
Eliano

**Comment by ElianoMarques** [comment]
Just to follow up on this:

```
spark_dataframe(tbl1) %>% invoke("drop", "any") %>% collect()
```

This should be dropping any row with NULL or NA values. I tried this in a data.frame and didn't work, i.e. it returned the same dataframe.

On another note, for the function in scala 
def fill(value: Double, cols: Seq[String])  how would you write the column in R? I tried 
```
spark_dataframe(tbl1) %>% invoke("fill", as.double(20), "avg_mileage")  
```
And got the following error:
failed to invoke spark command (unknown reason)

Thank you,
Eliano

**Comment by kevinushey** [comment]
I'm a little confused:

> spark_dataframe(tbl1) %>% invoke("drop", "any") %>% collect()

This code would attempt to drop a column named `any`, not drop rows with NULL / NA values. (As per the Scaladocs at https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.sql.Dataset)

Similarly, `fill` is not a function defined for Spark DataFrame (Dataset)s. What exactly are you trying to do?

**Comment by ElianoMarques** [comment]
I was using the dataframenafunctions from [here](https://spark.apache.org/docs/1.6.2/api/java/org/apache/spark/sql/DataFrameNaFunctions.html):
Basically I was trying to find a workaround to remove na and nulls, going directly to the scala API. Perhaps I have to look into dataset options first or use invoke_static as you mention above.

**Comment by kevinushey** [comment]
Ah, I see -- to get at that interface, you need to first invoke the method that gives you the `DataFrameNaFunctions` object:

```
na <- invoke(sdf, "na")
```

Then, on that `na` object, you can invoke the methods as needed:

```
dropped <- invoke(na, "drop", as.list("any"))
```

I'm not sure if Scala actually has a special interpretation for the string `"any"` in this context, but I believe that's what you need.

**Comment by ElianoMarques** [comment]
I will give it a try. I think this should also be added somehow to the package. Rather via dplyr and/or as new ft_ function given i'm sure everyone will have this issues when doing ML and/or ft function that don't accept nulls.

**Comment by kevinushey** [comment]
For what it's worth, we now implement `na.omit` and provide `na.replace` for handling this, e.g.

```
omitted <- na.omit(sdf, columns = <...>)
replaced <- na.replace(sdf, <column> = <value>, ...)
```

**Comment by ElianoMarques** [comment]
Thanks @kevinushey for this. I saw your commit a few hours ago for this. I wonder if the na.omit or na.replace should be added as parameters in all ML and FT functions. what do you think?

**Comment by javierluraschi** [comment]
Additionally, one can filter directly form `dplyr`:

```{r}
> tbl(sc, "nycflights13::flights") %>% filter(is.na(dep_delay)) %>% summarise(n = n())
Source:   query [?? x 1]
Database: spark connection master=local[8] app=sparklyr local=TRUE

      n
  <dbl>
1  8255

> nycflights13::flights %>% filter(is.na(dep_delay)) %>% summarise(n = n())
# A tibble: 1 × 1
      n
  <int>
1  8255
```

Looks to me like we can close this.

**Comment by richy1996** [comment]
filter(is.na(x)) is filtering out double values. i have a column with no NAs, using this technique, all rows are being removed. any reason for this?
