### ISSUE TITLE
Can not set "livy.session.start.timeout"

### ISSUE THREAD

**Issue by jmexe** [rstudio/sparklyr#1270]
I am experiencing a long waiting time on server side and need to set a longer timeout. If I set the "livy.session.start.timeout" in the config and try to connect, an error is thrown:

Here is the connection codes:

```r
s_config <- spark_config()
s_config["spark_version"] <- "2.1.1"
s_config["livy.session.start.timeout"] <- 120
config <- livy_config(s_config, "***username***", "***pwd***")
sc <- spark_connect(master = "***url***", method="livy", config=config)
```
Here is the error:
```r
Error in livy_validate_http_response("Failed to create livy session",  : 
  Failed to create livy session (Client error: (400) Bad Request): "Unrecognized field \"session.start.timeout\" (class com.cloudera.livy.server.interactive.CreateInteractiveRequest), not marked as ignorable (15 known properties: \"executorCores\", \"conf\", \"driverMemory\", \"name\", \"driverCores\", \"pyFiles\", \"archives\", \"queue\", \"kind\", \"executorMemory\", \"files\", \"jars\", \"proxyUser\", \"numExecutors\", \"heartbeatTimeoutInSecond\" [truncated]])\n at [Source: HttpInputOverHTTP@6a20dd3f; line: 1, column: 79] (through reference chain: com.cloudera.livy.server.interactive.CreateInteractiveRequest[\"session.start.timeout\"])"
```

It seems this config is also sent to livy in the session config and it doesn't exist in livy's config. Livy failed to create the InteractiveRequest. Code is here:
https://github.com/rstudio/sparklyr/blob/8bf5d24ddebd0c5281e0758fd094f34b95f20ddc/R/livy_connection.R#L193

For further verification, I also set the CreateInteractiveRequest to ignore unknown configs and solves the problem. However, I thought this is a issue from this package and should be fixed.

**Comment by javierluraschi** [comment]
@jmexe thanks, will make a fix available soon, this fix can be installed using `devtools::install_github("rstudio/sparklyr")`.
