### ISSUE TITLE
Transforming numerical fields into categories and then model

### ISSUE THREAD

**Issue by ElianoMarques** [rstudio/sparklyr#128]
If we have a numerical field which we want to bucketize and then use in a ML model:

for example:

```
tbl4 = sdf_mutate(tbl3,
                comp_factor = ft_string_indexer("comp"),
                avg_temp_factor = ft_bucketizer( "avg_temp", splits = c(-Inf,0,5,10,20,30,Inf)),
                avg_temp_factor2 = ft_one_hot_encoder("avg_temp_factor"),
                stdev_temp_factor = ft_bucketizer("sdev_temp", splits = c(-Inf,0,4.4,6.3,8.3,16,Inf)),
                stdev_temp_factor2 = ft_string_indexer("stdev_temp_factor"),
                stdev_temp_factor3 = ft_one_hot_encoder("stdev_temp_factor2") 
                 )

model_parameters <- c('avg_temp_factor2',
                'stdev_temp_factor3',
                'comp_factor',
model = ml_survival_regression(tbl4, response = "time",features = model_parameters, censor = "status", intercept = TRUE)
```
model$coefficients print the value as if it was a numerical parameter, not a category.
```
model$coefficients
            (Intercept)        avg_temp_factor2      stdev_temp_factor3             comp_factor 
             0.67959997              0.00000000              0.39217879             -0.42696859 
```
Is this the right way via the package to transform numerical values into categories?

Eliano

**Comment by slopp** [comment]
You can do this with the sparklyr function ml_create_dummy_variable. This function expects  a character labels, so you would do something like:

```
tbl3 %>% 
    sdf_mutate(avg_temp_factor = ft_bucketizer( "avg_temp" , splits = c(-Inf, 0, 5, 10, 20, 30, Inf))) %>% mutate(avg_temp_factor = as.character(avg_temp_factor)) %>%
ml_create_dummy_variable("avg_temp_factor")
```
   
Note that this will create n columns, where n is the number of splits. If you were to pass these columns into a regression routine you'd want to omit one of them to avoid perfect collinearity. 

A cleaner way to do this would be to pass the label column directly into the regression routine, and sparklyr will automatically do this for you:

tbl3 %>% 
    sdf_mutate(avg_temp_factor = ft_bucketizer( "avg_temp" , splits = c(-Inf, 0, 5, 10, 20, 30, Inf))) %>% mutate(avg_temp_factor = as.character(avg_temp_factor)) %>%
ml_survival_regression(response = "time", features = "avg_temp_factor")

**Comment by ElianoMarques** [comment]
Ok I did not look into ml_create_dummy_variable, I thought the ft_one_hot_encoder did the job. Of course the second approach is easier, thanks for the reply. 

Eliano

**Comment by ElianoMarques** [comment]
Just tried this approach: 
```
tbl3 %>% 
sdf_mutate(avg_temp_factor = ft_bucketizer( "avg_temp" , splits = c(-Inf, 0, 5, 10, 20, 30, Inf))) %>% mutate(avg_temp_factor = as.character(avg_temp_factor)) %>%
ml_survival_regression(response = "time", features = "avg_temp_factor")
``` 
and got this error:
```
Error: org.apache.spark.sql.AnalysisException: Cannot resolve column name "avg_temp_factor2.0"
```

Seems that parsing the character into column name is causing the issue, i.e. should not try to use 2.0 but something like column_name_1 or columna_name_2.

**Comment by slopp** [comment]
Yes, my apologies. A simple fix is to force the bins to integers first:

```
iris_tbl <- tbl(sc, "iris")
iris_tbl %>% 
  sdf_mutate(sepal_width_bin = ft_bucketizer("Sepal_Width", splits = c(1,2,3,4,5))) %>% 
  mutate(sepal_width_bin = as.character(as.integer(sepal_width_bin))) %>% 
  ml_linear_regression(Sepal_Length ~ sepal_width_bin)
```

**Comment by ElianoMarques** [comment]
yap. this works and brings the bucket number into the column. Thanks again, Eliano
