### ISSUE TITLE
Spark connection hung showing "Loading Objects" message

### ISSUE THREAD

**Issue by tarunparmar** [rstudio/sparklyr#1285]
I am seeing a "Loading Objects" message after initiating spark connection. Never seen this before. 
The command line is not responsive so I could not get sessionInfo. This is a blank session with just sparklyr and dplyr loaded as part of connection.
R version is 3.3.2 and sparklyr is 0.6. This was working 2 days back.

Here's the connection initiation code:
```r
library(sparklyr)
library(dplyr)
spark_version <- "2.0.0"
sc <- spark_connect(master = "spark://sparkmaster:7077")

```
![image](https://user-images.githubusercontent.com/17690950/35757925-473e2948-083f-11e8-91a7-0b6695d53ce6.png)

Another observation on the Spark Master url is this:
![image](https://user-images.githubusercontent.com/17690950/35757998-acff7638-083f-11e8-9174-371531b03679.png)

The first row is my app which shows 0 cores while the second row is from another user whose app is in RUNNING for 10+ hours. I do not know if the other user may still be running his app so did not want to kill his app and try to  connect. 

Any thoughts on what could be going on here?

**Comment by javierluraschi** [comment]
@tarunparmar does `spark_connect()` finish executing in the console? Is this really specific to the connection pane?

It does seem possible that not having resources assigned at all causes the Spark tohang waiting for resources, so this might not be necessarily a bug per se.

**Comment by tarunparmar** [comment]
I also tried commands in console directly and then it was showing the Loading message in the connection pane. Today I decided I would kill the other user's session and try connecting myself after that. 

It worked, I was able to connect .
