### ISSUE TITLE
Spark NLP

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#1286]
- CoreNLP

**Comment by kevinykuo** [comment]
https://github.com/JohnSnowLabs/spark-nlp should be more scalable and is compatible with pipelines.

Depends on https://github.com/rstudio/sparklyr/issues/1180

**Comment by randomgambit** [comment]
@kevinykuo @javierluraschi guys I just tried to run some state-of-the-art NLP algos on my machine, and it is S L O W !!!!! we really need NLP on spark! better yet, NLP on sparklyr ! :) do you think this is doable soon?

**Comment by kevinykuo** [comment]
@randomgambit Yes, I should have this moving in December. Shoot me an email if I don't update by the end of the year.

**Comment by randomgambit** [comment]
@kevinykuo itssssssss tiiiiiiiimee ! :) any good news on that??? thanks guys!

**Comment by kevinykuo** [comment]
@randomgambit Yeah still on track to get to this this year. The prerequisite is https://github.com/rstudio/sparklyr/pull/1778 which I'm working on at the moment together with the xgboost extension (which will be in a public repo soon.)

**Comment by randomgambit** [comment]
happy new year buddy! any update on this much needed extension? :)

**Comment by dkincaid** [comment]
It would be really, really awesome if we could get this in. We've just started evaluating Spark-NLP and I am really impressed with it. We'll likely be using it as our core NLP platform and I would really like to be able to continue working in R instead of shifting to Python or Java. Is there anything we can do to push this along?

**Comment by kevinykuo** [comment]
@dkincaid Yes! I'd started working on it but haven't touched the branch in a while. If your team has some cycles to spare we can definitely use the help. If you're interested, shoot me a note at kevinykuo at gmail.

**Comment by kevinykuo** [comment]
https://github.com/r-spark/sparknlp
