### ISSUE TITLE
spark_connect not using "version" argument

### ISSUE THREAD

**Issue by datapixie** [rstudio/sparklyr#129]
`spark_connect` tries to use `sparkapi::spark_version_from_home` even when I pass an explicit spark version.

```
> sc <- spark_connect(master = "yarn-client",  config = spark_config(), version = "1.6.1")

Error in sparkapi::spark_version_from_home(spark_home) : 
  Failed to detect version from SPARK_HOME or SPARK_HOME_VERSION. Try passing the spark_version explicitly.
```

**Comment by javierluraschi** [comment]
@datapixie Thanks for finding this, fix is in. Give this a shot with sparkly version `0.2.32` (current latest version). Let us know if this doesn't work as expected.

**Comment by datapixie** [comment]
Thanks @javierluraschi ! Works great.
