### ISSUE TITLE
is ft_regex_tokenizer ready for use?

### ISSUE THREAD

**Issue by randomgambit** [rstudio/sparklyr#1293]
Hello, 

I use Sparklyr `0.7.0-9106` and I see that a function `ft_regex_tokenizer` is available. 

However, I do not see this `ft` transformer being mentioned on the main website https://github.com/rstudio/sparklyr/blob/master/vignettes/guides-mllib.Rmd#transformers

That does mean the function is not ready for production use?

Thanks again for the clarification. I really need to use it.

**Comment by randomgambit** [comment]
@kevinykuo @javierluraschi I am asking this because I have noticed the following problem.
I have a parquet dataframe with about 35 million rows. 

Running the following code will work as expected:

```
df_new %>%
  head() %>% 
  ft_regex_tokenizer(input.col='myweirdstring',
                     output.col = 'myoutput', pattern = '\\b[^\\d\\W]+\\b', gaps =FALSE) %>% 
  select(myoutput, myweirdstring) %>% 
  mutate(myword = explode(myoutput)) %>% 
  group_by(myword) %>% 
  summarize(mycount = n())

# Source:   lazy query [?? x 2]
# Database: spark_connection
   myword    mycount
   <chr>       <dbl>
 1 country       2.00
 2 original      4.00
 3 nice          5.00
 4 hello         2.00
```
Here I simply use `ft_regex_tokenizer` on a character column (looking for words but not numbers) and then I explode the result so that I can actually count the occurrences of each word in the dataset. **Note that I use `head()` here.**

Now here is the big issue: if I run that same code on the full 35 million rows (that is without the `head()` ) I immediately get the error:

`Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 9 in stage 13.0 failed 4 times, most recent failure: Lost task 9.3 in stage 13.0 (TID 1321, 10.11.1111.111, executor 2): org.apache.spark.SparkException: Failed to execute user defined function($anonfun$createTransformFunc$2: (string) => array<string>)`

what does that even mean??? is this a bug??
Thanks again for your help!!!!

**Comment by randomgambit** [comment]
@kevinykuo @javierluraschi actually after a few tests, using `head(5000)` will generate the same error which likely rule out some possible memory issues I guess. Do you have any idea?

What does the ` function($anonfun$createTransformFunc$2: (string) => array<string>)` error mean?

Thanks!

**Comment by kevinykuo** [comment]
@randomgambit I'd try to identify the rows that contain the problematic string and eyeball them.

`ft_regex_tokenizer()` is good to go and this looks like a Spark or data issue.

**Comment by randomgambit** [comment]
thanks. I would add to the documentation that all of the spark ml functions are available. not only the one you mention on the sparklyr website because this is confusing (at least to me).

thanks!!

**Comment by randomgambit** [comment]
@kevinykuo can I please ask a follow up question related to that?
I have a variable that contains strings like `"KEVIN10 KUO SPARK KUO30 HELLO"`

Assume I want to filter the rows that contain `KUO` somewhere in the string. 

Then doing 
`df %>% filter(mycolumn %rlike% 'KUO') 
`
works as expected.

HOWEVER, if I want to filter out the rows where I have `KUO` immediately followed by a number (such as `KUO30`, doing the following:

`
filter(mycolumn %rlike% 'KUO\\d+')  
`

**never** works...
 Is there something special with the syntax I must use here?

**Comment by kevinykuo** [comment]
Try `"KUO[0-9]"` for the pattern

**Comment by randomgambit** [comment]
@kevinykuo Okay thanks that worked! 

So now we are back to the fundamental question of this issue: lets assume I want to **extract** the number that is next to 'KUO'.

I tried the following:

```
df_new  %>%   
ft_regex_tokenizer(input.col='mystring',
                              output.col = 'myoutput', 
                              pattern = '(?<=KUO)([0-9]+)', gaps =FALSE) %>% 
  mutate(myword = explode(myoutput))
```

but this always returns an empty frame. Are the `lookarounds` supported by `ft_regex_tokenizer` ?

**Comment by kevinykuo** [comment]
`ft_regex_tokenizer()` should take Java regular expressions so I'd google with that

**Comment by randomgambit** [comment]
@kevinykuo I believe I am using the right syntax here... even 

`pattern = "(?<=KUO)([0-9])"`

does not work. 

In contrast, using

`pattern = ".*(?<=.*KUO)([0-9]).*"`

seem to run forever... I am lost here :(

**Comment by randomgambit** [comment]
**HOLY COW**. I found the bug

running 

`pattern = "(?<=kuo)([0-9])"` with lower case `kuo` will match against all the upper case `KUO`s in the data). Any reason for that?

I see some hidden option in `ft_regex_tokenizer(to_lower_case = TRUE)` but no documentation about it on https://www.rdocumentation.org/packages/sparklyr/versions/0.6.4/topics/ft_regex_tokenizer. Could it be it? 

Thanks!

**Comment by kevinykuo** [comment]
Check out the latest version of the docs https://www.rdocumentation.org/packages/sparklyr/versions/0.7.0/topics/ft_regex_tokenizer
