### ISSUE TITLE
ml_decision_tree failing with response-features syntax

### ISSUE THREAD

**Issue by khueyama** [rstudio/sparklyr#1302]
First off, thanks to everyone for the great work on this package. 

We recently upgraded to v0.7.0 and are running into issues with some ML function calls that use response-features and that worked under v0.6.4. A simple reprex similar to what we're running:

``` r
library(sparklyr)
config <- spark_config()
sc <- spark_connect(master = 'local')
iris_spark <- dplyr::copy_to(sc,iris, name = 'iris_spark')
```

This response-features syntax worked in v0.6.4, but fails in v0.7.0:

``` r
ml_decision_tree(iris_spark, 
                 response = 'Sepal_Length',
                 features = c('Sepal_Width', 'Petal_Length'))
```

    ## Error in ml_formula_transformation(): only one of 'formula' or 'response'-'features' should be specified

Reading through the source for `ml_formula_transformation` we thought this might work, but no such luck:

``` r
ml_decision_tree(iris_spark,
                 formula = NULL,
                 response = 'Sepal_Length',
                 features = c('Sepal_Width', 'Petal_Length'))
```

    ## Error in ml_formula_transformation(): only one of 'formula' or 'response'-'features' should be specified

However calling `ml_decision_tree_regressor` directly works:

``` r
ml_decision_tree_regressor(iris_spark, 
                           response = 'Sepal_Length',
                           features = c('Sepal_Width', 'Petal_Length'))
```

    ## Call: ml_decision_tree_regressor.tbl_spark(iris_spark, response = "Sepal_Length", features = c("Sepal_Width", "Petal_Length"))  
    ## 
    ## Formula: Sepal_Length ~ Sepal_Width + Petal_Length
    ## 
    ## DecisionTreeRegressionModel (uid=decision_tree_regressor_248c4ac46b8a) of depth 5 with 57 nodes

``` r
devtools::session_info()
```

    ## Session info -------------------------------------------------------------

    ##  setting  value                       
    ##  version  R version 3.4.3 (2017-11-30)
    ##  system   x86_64, mingw32             
    ##  ui       RTerm                       
    ##  language (EN)                        
    ##  collate  English_United States.1252  
    ##  tz       America/New_York            
    ##  date     2018-02-13

    ## Packages -----------------------------------------------------------------

    ##  package    * version date       source        
    ##  assertthat   0.2.0   2017-04-11 CRAN (R 3.4.2)
    ##  backports    1.1.2   2017-12-13 CRAN (R 3.4.3)
    ##  base       * 3.4.3   2017-12-06 local         
    ##  base64enc    0.1-3   2015-07-28 CRAN (R 3.4.1)
    ##  bindr        0.1     2016-11-13 CRAN (R 3.4.2)
    ##  bindrcpp   * 0.2     2017-06-17 CRAN (R 3.4.2)
    ##  broom        0.4.3   2017-11-20 CRAN (R 3.4.2)
    ##  compiler     3.4.3   2017-12-06 local         
    ##  config       0.2     2016-08-02 CRAN (R 3.4.2)
    ##  datasets   * 3.4.3   2017-12-06 local         
    ##  DBI          0.7     2017-06-18 CRAN (R 3.4.2)
    ##  dbplyr       1.2.0   2018-01-03 CRAN (R 3.4.3)
    ##  devtools     1.13.4  2017-11-09 CRAN (R 3.4.3)
    ##  digest       0.6.15  2018-01-28 CRAN (R 3.4.3)
    ##  dplyr        0.7.4   2017-09-28 CRAN (R 3.4.2)
    ##  evaluate     0.10.1  2017-06-24 CRAN (R 3.4.2)
    ##  foreign      0.8-69  2017-06-22 CRAN (R 3.4.3)
    ##  glue         1.2.0   2017-10-29 CRAN (R 3.4.2)
    ##  graphics   * 3.4.3   2017-12-06 local         
    ##  grDevices  * 3.4.3   2017-12-06 local         
    ##  grid         3.4.3   2017-12-06 local         
    ##  htmltools    0.3.6   2017-04-28 CRAN (R 3.4.2)
    ##  httpuv       1.3.5   2017-07-04 CRAN (R 3.4.2)
    ##  httr         1.3.1   2017-08-20 CRAN (R 3.4.2)
    ##  jsonlite     1.5     2017-06-01 CRAN (R 3.4.2)
    ##  knitr        1.18    2017-12-27 CRAN (R 3.4.3)
    ##  lattice      0.20-35 2017-03-25 CRAN (R 3.4.3)
    ##  lazyeval     0.2.1   2017-10-29 CRAN (R 3.4.2)
    ##  magrittr     1.5     2014-11-22 CRAN (R 3.4.2)
    ##  memoise      1.1.0   2017-04-21 CRAN (R 3.4.3)
    ##  methods    * 3.4.3   2017-12-06 local         
    ##  mime         0.5     2016-07-07 CRAN (R 3.4.1)
    ##  mnormt       1.5-5   2016-10-15 CRAN (R 3.4.1)
    ##  nlme         3.1-131 2017-02-06 CRAN (R 3.4.3)
    ##  openssl      1.0     2018-02-02 CRAN (R 3.4.3)
    ##  parallel     3.4.3   2017-12-06 local         
    ##  pillar       1.1.0   2018-01-14 CRAN (R 3.4.3)
    ##  pkgconfig    2.0.1   2017-03-21 CRAN (R 3.4.2)
    ##  plyr         1.8.4   2016-06-08 CRAN (R 3.4.2)
    ##  psych        1.7.8   2017-09-09 CRAN (R 3.4.2)
    ##  purrr        0.2.4   2017-10-18 CRAN (R 3.4.2)
    ##  R6           2.2.2   2017-06-17 CRAN (R 3.4.2)
    ##  rappdirs     0.3.1   2016-03-28 CRAN (R 3.4.2)
    ##  Rcpp         0.12.15 2018-01-20 CRAN (R 3.4.3)
    ##  reshape2     1.4.3   2017-12-11 CRAN (R 3.4.3)
    ##  rlang        0.1.6   2017-12-21 CRAN (R 3.4.3)
    ##  rmarkdown    1.8     2017-11-17 CRAN (R 3.4.2)
    ##  rprojroot    1.3-2   2018-01-03 CRAN (R 3.4.3)
    ##  rstudioapi   0.7     2017-09-07 CRAN (R 3.4.2)
    ##  shiny        1.0.5   2017-08-23 CRAN (R 3.4.2)
    ##  sparklyr   * 0.7.0   2018-01-23 CRAN (R 3.4.3)
    ##  stats      * 3.4.3   2017-12-06 local         
    ##  stringi      1.1.6   2017-11-17 CRAN (R 3.4.2)
    ##  stringr      1.2.0   2017-02-18 CRAN (R 3.4.2)
    ##  tibble       1.4.1   2017-12-25 CRAN (R 3.4.3)
    ##  tidyr        0.7.2   2017-10-16 CRAN (R 3.4.2)
    ##  tools        3.4.3   2017-12-06 local         
    ##  utils      * 3.4.3   2017-12-06 local         
    ##  withr        2.1.1   2017-12-19 CRAN (R 3.4.3)
    ##  xtable       1.8-2   2016-02-05 CRAN (R 3.4.2)
    ##  yaml         2.1.16  2017-12-12 CRAN (R 3.4.3)

**Comment by kevinykuo** [comment]
@khueyama Thanks for the report! Should be fixed now in dev. Please let me know if you run into further issues.

**Comment by khueyama** [comment]
Thanks for the quick fix! Much appreciated.

**Comment by Ethannical** [comment]
<error>
message: `call` must be a quoted call
class:   `rlang_error`
backtrace:
  1. sparklyr::ml_decision_tree_regressor(...)
 10. sparklyr:::ml_new_stage_modified_args()
 11. rlang::lang_name(caller_frame)
 13. rlang::call_name(lang)
 14. rlang:::abort_call_input_type("call")
 15. sparklyr::ml_decision_tree_regressor(...)
Call `rlang::last_trace()` to see the full backtrace

**Comment by Ethannical** [comment]
what is wrong with it?
