### ISSUE TITLE
serialization date filtering in Sparklyr 0.7?

### ISSUE THREAD

**Issue by randomgambit** [rstudio/sparklyr#1321]
Hello,

I am sorry to ask this, but serialization is new in 0.7 and nobody can know the answer to this question except for the great `sparklyr` team ;-)

I am loading a large parquet file and with `spark_read_parquet` I can see that my date variable has a `date` type. However, I have no idea what is the proper way to `filter` a date variable?

I tried `filter(mydate <= as.Date('2016-06-06'))` with and I got an error.
`filter(mydate <= '2016-06-06')` seemed to work but it seems weird to me to compare a date type with a string.

Any help appreciated. Thanks again!

**Comment by javierluraschi** [comment]
This works for me just fine:

```r
spark_read_parquet(sc, "dates_parquet", "dates.snappy.parquet.txt") %>%
  filter(dates < as.Date("2018-04-20"))
```
```
# Source:   lazy query [?? x 1]
# Database: spark_connection
  dates     
  <date>    
1 2018-04-16
2 2018-04-17
3 2018-04-18
4 2018-04-19
```

[dates.snappy.parquet.txt](https://github.com/rstudio/sparklyr/files/1904600/dates.snappy.parquet.txt)

I would need a sample parquet file and the error output to help out more here.

**Comment by randomgambit** [comment]
hum, interesting. it now works with `sparklyr 0.7.0-9010`.
Did you fix something about dates/serialization in that version already?

**Comment by javierluraschi** [comment]
Yes, there were a couple date fixes, should have resolved this one, glad it works!
