### ISSUE TITLE
nrow no longer working...

### ISSUE THREAD

**Issue by schlichtanders** [rstudio/sparklyr#1323]
since the new sparklyr 0.7.0 it seems that nrow does not work anylonger, I am actually not a 100% sure whether this worked before, however I had scripts which seemed to break because of this

currently, in RStudio, pressing ``F2`` on ``sparklyr:::dim.tbl_spark`` will show the following
```
function (x) 
{
  c(NA_real_, sdf_ncol(x))
}
```

and ``F2`` on  ``nrow`` shows
```
function (x) 
dim(x)[1L]
```

So indeed, this seems not supported currently?

**Comment by Afustin** [comment]
You have `sdf_nrow(x)` for that matter:

[Look here :)](https://www.rdocumentation.org/packages/sparklyr/versions/0.7.0/topics/sdf_dim)

**Comment by schlichtanders** [comment]
thanks a lot for the pointer!

**Comment by kevinykuo** [comment]
Yeah this was done so we don't force a count job when calling things like `glimpse()`
