### ISSUE TITLE
Hive's rand for sparklyr syntax

### ISSUE THREAD

**Issue by nviets** [rstudio/sparklyr#1326]
Hello,

Could hive's rand function be supported in sparklyr syntax?  I'd like to generate a random number based on a column input.  In hive/spark-sql, I'd write:

select myVal, rand(myVal) as myRand from myTable;

Is there some other way of achieving the same result?

Thank you,
Nathan

**Comment by harryprince** [comment]
you can use sparklyr::spark_apply to generate random number by R native function like `dnorm()`;
or register your dataframe and run sparksql

**Comment by mattpollock** [comment]
You can use any Hive functions inside `mutate`. For example

```r
df <- copy_to(sc, data.frame(a=c(1,2,3)))
df %>% mutate(random=rand()) %>% head()
# # Source:   lazy query [?? x 2]
# # Database: spark_connection
#       a random
#   <dbl>  <dbl>
# 1  1.00  0.213
# 2  2.00  0.420
# 3  3.00  0.131
```

Sometimes I'll wrap hive-named functions (like `percentile`) around R functions (`quantile` in this example) so that my stuff works in both spark and local `dplyr` mode.

**Comment by nviets** [comment]
Hi Matt and Harry,

Thanks for the replies.  I realized today what I was really looking for was hash, which takes an input and creates a number.

Best,
Nathan

**Comment by nviets** [comment]
I'll watch out for percentile, as that would be useful.  Currently I use ft_quantile_discretizer, and the hive function would be much more convenient.
