### ISSUE TITLE
What are the Apache Arrow integration plans?

### ISSUE THREAD

**Issue by mattpollock** [rstudio/sparklyr#1327]
It looks like Arrow integration with spark v2.3 [will improve serialization for `pySpark`](https://arrow.apache.org/blog/2017/07/26/spark-arrow/). What does `sparklyr` do here? Are there plans to use Arrow (or [feather](https://github.com/wesm/feather)) to improve UDF performance?

Thanks

**Comment by mattpollock** [comment]
My question was more timely than I realized. http://spark.apache.org/news/spark-2-3-0-released.html

**Comment by javierluraschi** [comment]
Yes, for sure, this would be pretty awesome but is no trivial amount of work, tracking this work here: https://github.com/rstudio/sparklyr/issues/1457

**Comment by mattpollock** [comment]
Thanks much - I'm sure this isn't easy.
