### ISSUE TITLE
Predict(...) on large newData seems unordered

### ISSUE THREAD

**Issue by l4mun** [rstudio/sparklyr#133]
Hi,

Sorry for not providing a reproductible example. However the problems seems to arise when dataset are not "small".
I tried by my own Sparklyr on a bigger dataset. I picked up Airlines2007 and 2008. Merge with Weather on Date. Trained a model on 2007 (300k rows) and predicted on 2008 ((300k rows). 

At the end i train a linear regression and a RandomForest. 

```
my_ml_rf = ml_random_forest(x = train ,response = "ArrDelay", features = myFeatures)
p1 = predict(my_ml_rf, validation)
p2 = predict(my_ml_rf, validation)
qplot(p1, p2)

my_ml_linear = ml_linear_regression(x = train ,response = "ArrDelay", features = myFeatures)
p11 = predict(my_ml_linear, validation)
p22 = predict(my_ml_linear, validation)
qplot(p11, p22)
```

However and surprinsingly, here are the graphs
![image](https://cloud.githubusercontent.com/assets/15957925/17210968/b16e1536-54c6-11e6-9610-77b5a1718b1d.png)

![image](https://cloud.githubusercontent.com/assets/15957925/17211016/00daea04-54c7-11e6-9c6a-b3851c8f14c9.png)

```
p11[120000:110000] == p22[120000:110000]
```

![image](https://cloud.githubusercontent.com/assets/15957925/17211252/a72b67b6-54c8-11e6-8f5f-855e3ea958a3.png)

It clearly seems that "bloc" order change sometimes. I guess it is due to the inner functionnement of Spark. The first returned block are the first processed. However it is an annoying problem.

Best regards,
Jacques

**Comment by kevinushey** [comment]
This is the code we use for implementing `predict()`:

```R
predict.ml_model <- function(object, newdata, ...) {
  params <- object$model.parameters
  predicted <- sdf_predict(object, newdata, ...)
  column <- sdf_read_column(predicted, "prediction")
  if (is.character(params$labels) && is.numeric(column))
    column <- params$labels[column + 1]
  column
}
```

I wonder if the issue could be that the row order in the predicted `data.frame`, as returned by `sdf_predict`, is not as expected? What does the output from `sdf_predict` look like?

**Comment by l4mun** [comment]
Not sure to have fully understood what you wanted. (PS i work on a small cluster of 2 workers, not in local mode).
``sdf_predict(my_ml_linear, validation) %>% str() ``
````
List of 2
 $ src:List of 1
  ..$ con:List of 10
  .. ..$ master       : chr "yarn-client"
  .. ..$ spark_home   : chr "/usr/hdp/2.4.2.0-258/spark"
  .. ..$ app_name     : chr "sparklyr"
  .. ..$ config       :List of 3
  .. .. ..$ sparklyr.cores.local              : int 8
  .. .. ..$ spark.sql.shuffle.partitions.local: int 8
  .. .. ..$ sparklyr.defaultPackages          : chr [1:2] "com.databricks:spark-csv_2.11:1.3.0" "com.amazonaws:aws-java-sdk-pom:1.10.34"
  .. .. ..- attr(*, "config")= chr "default"
  .. .. ..- attr(*, "file")= chr "/home/spark/R/x86_64-redhat-linux-gnu-library/3.2/sparklyr/conf/config-template.yml"
  .. ..$ backend      :Classes 'sockconn', 'connection'  atomic [1:1] 4
  .. .. .. ..- attr(*, "conn_id")=<externalptr> 
  .. ..$ monitor      :Classes 'sockconn', 'connection'  atomic [1:1] 3
  .. .. .. ..- attr(*, "conn_id")=<externalptr> 
  .. ..$ output_file  : chr "/tmp/RtmpPmTw7W/filec3626a93e72_spark.log"
  .. ..$ spark_context:Class 'spark_jobj' <environment: 0x5862d68> 
  .. ..$ java_context :Class 'spark_jobj' <environment: 0x5880140> 
  .. ..$ hive_context :Class 'spark_jobj' <environment: 0x58dad20> 
  .. ..- attr(*, "class")= chr [1:3] "spark_connection" "spark_shell_connection" "DBIConnection"
  ..- attr(*, "class")= chr [1:3] "src_spark" "src_sql" "src"
 $ ops:List of 3
  ..$ src :List of 1
  .. ..$ con:List of 10
  .. .. ..$ master       : chr "yarn-client"
  .. .. ..$ spark_home   : chr "/usr/hdp/2.4.2.0-258/spark"
  .. .. ..$ app_name     : chr "sparklyr"
  .. .. ..$ config       :List of 3
  .. .. .. ..$ sparklyr.cores.local              : int 8
  .. .. .. ..$ spark.sql.shuffle.partitions.local: int 8
  .. .. .. ..$ sparklyr.defaultPackages          : chr [1:2] "com.databricks:spark-csv_2.11:1.3.0" "com.amazonaws:aws-java-sdk-pom:1.10.34"
  .. .. .. ..- attr(*, "config")= chr "default"
  .. .. .. ..- attr(*, "file")= chr "/home/spark/R/x86_64-redhat-linux-gnu-library/3.2/sparklyr/conf/config-template.yml"
  .. .. ..$ backend      :Classes 'sockconn', 'connection'  atomic [1:1] 4
  .. .. .. .. ..- attr(*, "conn_id")=<externalptr> 
  .. .. ..$ monitor      :Classes 'sockconn', 'connection'  atomic [1:1] 3
  .. .. .. .. ..- attr(*, "conn_id")=<externalptr> 
  .. .. ..$ output_file  : chr "/tmp/RtmpPmTw7W/filec3626a93e72_spark.log"
  .. .. ..$ spark_context:Class 'spark_jobj' <environment: 0x5862d68> 
  .. .. ..$ java_context :Class 'spark_jobj' <environment: 0x5880140> 
  .. .. ..$ hive_context :Class 'spark_jobj' <environment: 0x58dad20> 
  .. .. ..- attr(*, "class")= chr [1:3] "spark_connection" "spark_shell_connection" "DBIConnection"
  .. ..- attr(*, "class")= chr [1:3] "src_spark" "src_sql" "src"
  ..$ x   :Classes 'ident', 'sql', 'character'  chr "sparklyr_tmp_c364d62b85a"
  ..$ vars: chr [1:10] "DayOfWeek" "DepTime" "ArrTime" "TMIN" ...
  ..- attr(*, "class")= chr [1:3] "op_base_remote" "op_base" "op"
 - attr(*, "class")= chr [1:4] "tbl_spark" "tbl_sql" "tbl_lazy" "tbl"
````

**Comment by kevinushey** [comment]
I should have been more clear -- what if you use the output from `sdf_predict(object, newdata)` directly to try to generate your plots. Do you see the same weirdness?

**Comment by l4mun** [comment]
I should have been more clever too ;)

````
p111 = sdf_predict(my_ml_linear, validation)
p222 = sdf_predict(my_ml_linear, validation)
local_p111 = as.data.frame(p111)
local_p222 = as.data.frame(p222)
head(local_p111)
head(local_p222)
# ArrDelay is the response variable
all.equal(local_p111$ArrDelay, local_p222$ArrDelay)
sqrt( mean( (local_p111$ArrDelay-local_p111$prediction)^2 ) ) # Calcul du RMSE
sqrt( mean( (local_p222$ArrDelay-local_p222$prediction)^2 ) ) # Calcul du RMSE
````

![image](https://cloud.githubusercontent.com/assets/15957925/17290629/ba1e1e12-57df-11e6-9218-966cc115032c.png)

Same RMSE. Each observation is linked to its good prediction.

 I guess you're right, the row order is not the same. If i want to export locally my prediction, i think i've to add an index column. Hence i'll be able to link it to the right observation. 

However ``predict(...)`` is a bit confusing right now to me. And i don't think i'll the only one to miserably fail with it. Using ``sdf_predict(...)`` seems a bit more intuitive to use right now.

Thank you for your help.

**Comment by kevinushey** [comment]
Thanks for the update -- it looks likes we definitely need to make sure `predict` does the right thing as well; it should produce a column vector in the same row order as the input `newdata` data set.

**Comment by MarcinKosinski** [comment]
+1

**Comment by javierluraschi** [comment]
Looks like https://github.com/rstudio/sparklyr/commit/7eb70d0f55e30a68eebec1f69a152e2304542a77 fixed this issue since I can't repro the ordering issue with the newest bits, correct @kevinushey?

```{r}
x <- flights_tbl %>% sdf_partition(training = 0.1, test = 0.9)
my_ml_linear <- ml_linear_regression(x = x$training, response = "dep_delay", features = c("dep_time", "sched_dep_time", "arr_delay"))
p1 <- predict(my_ml_linear)
p2 <- predict(my_ml_linear)

qplot(p1, p2)
```

**Comment by kevinushey** [comment]
Yes, I believe we should be handling this correctly now (although we might need to revisit this in the future for performance reasons)
