### ISSUE TITLE
Problem to connect to rsparkling using standalone 

### ISSUE THREAD

**Issue by joscani** [rstudio/sparklyr#1347]
My code looks like this 

```r
library(rsparkling)
library(sparklyr)
library(h2o)
library(dplyr)

sc <- spark_connect("local")
```
I'm using ubuntu and I can connect to spark in standalone without calling rsparkling, but when I try to use rsparkling I get 

```
* Using Spark: 2.2.1
Spark version 2.2 detected. Will call latest Sparkling Water version 2.2.10
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (25670): Gateway in port (8880) did not respond.
    Path: /home/jose/spark/spark-2.2.1-bin-hadoop2.7/bin/spark-submit
    Parameters: --class, sparklyr.Shell, --packages, 'ai.h2o:sparkling-water-core_2.11:2.2.10','ai.h2o:sparkling-water-ml_2.11:2.2.10','ai.h2o:sparkling-water-repl_2.11:2.2.10','no.priv.garshol.duke:duke:1.2', '/home/jose/R/x86_64-pc-linux-gnu-library/3.4/sparklyr/java/sparklyr-2.2-2.11.jar', 8880, 25670
    Log: /tmp/RtmpbPCbdJ/file217a60b31a6_spark.log
```

I'm using the rigth version of rsparkling and h2o. Any idea?

Thanks

**Comment by javierluraschi** [comment]
@joscani can you retry with the latest versions of `sparklyr` and `rsparkling`? H2O recently simplified versions and I remember seeing a similar error until a fix was performed in our readme. Have you tried running the H2O section in the `sparklyr` [readme](https://github.com/rstudio/sparklyr)?

**Comment by joscani** [comment]
You're right. It was a problem with the version

**Comment by joscani** [comment]
You're right. It was a problem with the version
