### ISSUE TITLE
How to move customize stop words in ft_stop_words_remover??

### ISSUE THREAD

**Issue by connieshen0503** [rstudio/sparklyr#1349]
With the latest version sparlyr (0.7), how to use ft_stop_words_remover to remove some customize stop words? 

I tried the example assign words to 'stop_words', but didn't work well.
''
df <- data.frame(words = "I like cats")
df_tbl <- sdf_copy_to(sc, df, overwrite = TRUE)
df_tbl %>%
  ft_tokenizer("words", "tokenized") %>%
  ft_stop_words_remover(input.col = "tokenized", output.col = "clean_words",
                        stop_words = c("cats", "like")) %>%
  dplyr::glimpse()
''
The code above can only remove the standard stop words, but not the customized ones. 

Thanks

**Comment by kevinykuo** [comment]
What are you seeing as the output?

This is what shows up on my end:
```
Observations: ??
Variables: 3
$ words       <chr> "I like cats"
$ tokenized   <list> [["i", "like", "cats"]]
$ clean_words <list> [["i"]]
```

**Comment by connieshen0503** [comment]
Here is my output.

Observations: 1 
Variables: 3 
$ words       <chr> "I like cats" 
$ tokenized   <list> [["i", "like", "cats"]] 
$ clean_words <list> [["like", "cats"]]
--

**Comment by connieshen0503** [comment]
Here is my output.

Observations: 1
Variables: 3
$ words       <chr> "I like cats"
$ tokenized   <list> [["i", "like", "cats"]]
$ clean_words <list> [["like", "cats"]]

**Comment by kevinykuo** [comment]
Could you share the output of `sessionInfo()`?

**Comment by connieshen0503** [comment]
``
> sessionInfo() R version 3.4.1 (2017-06-30) Platform: x86_64-redhat-linux-gnu (64-bit) Running under: CentOS release 6.9 (Final)  Matrix products: default BLAS: /usr/lib64/R/lib/libRblas.so LAPACK: /usr/lib64/R/lib/libRlapack.so  locale:  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8     [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C         attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages:  [1] tm_0.7-3           NLP_0.1-11         text2vec_0.5.1     stringr_1.2.0      wordcloud_2.5      RColorBrewer_1.1-2 Matrix_1.2-11      data.table_1.10.4   [9] dplyr_0.7.4        sparklyr_0.7.0      loaded via a namespace (and not attached):  [1] Rcpp_0.12.15          lattice_0.20-35       tidyr_0.7.1           assertthat_0.2.0      rprojroot_1.2         digest_0.6.12         psych_1.7.8            [8] foreach_1.4.3         mime_0.5              slam_0.1-42           R6_2.2.2              plyr_1.8.4            futile.options_1.0.0  backports_1.1.1       [15] evaluate_0.10.1       httr_1.3.1            rlang_0.1.2           lazyeval_0.2.0        rstudioapi_0.7        rmarkdown_1.6         config_0.2            [22] readr_1.1.1           servr_0.8             foreign_0.8-69        proxy_0.4-21          shiny_1.0.5           broom_0.4.2           compiler_3.4.1        [29] httpuv_1.3.5          pkgconfig_2.0.1       base64enc_0.1-3       mnormt_1.5-5          htmltools_0.3.6       openssl_0.9.7         tibble_1.3.4          [36] codetools_0.2-15      dbplyr_1.1.0          withr_2.0.0           grid_3.4.1            nlme_3.1-131          jsonlite_1.5          xtable_1.8-2          [43] DBI_0.7               magrittr_1.5          RcppParallel_4.3.20.2 stringi_1.1.5         reshape2_1.4.2        bindrcpp_0.2          xml2_1.1.1            [50] futile.logger_1.4.3   lambda.r_1.2          LDAvis_0.3.2          iterators_1.0.8       tools_3.4.1           RJSONIO_1.3-0         glue_1.1.1            [57] mlapi_0.1.0           purrr_0.2.3           hms_0.3               parallel_3.4.1        yaml_2.1.16           knitr_1.17            bindr_0.1
--

**Comment by connieshen0503** [comment]
![capture11](https://user-images.githubusercontent.com/22944879/37300140-a4c5e52c-25fb-11e8-9830-52eef6ee9709.PNG)

**Comment by kevinykuo** [comment]
Thanks will take a look. Btw you can include code and output on GitHub by marking the code chunks with pairs of three backticks, e.g.

```` 
```
code
``` 
````

**Comment by connieshen0503** [comment]
Thanks ! I am a fresh man on Github, thanks for your advice.

**Comment by edgararuiz** [comment]
Hi, can you share with us the `spark_connect()` code that you're using too please? Feel free to redact any server names

**Comment by connieshen0503** [comment]
Sure.
```
sc <- spark_connect(master = "spark:ip_address:7077", spark_home = "/opt/spark-2.2.0-bin-hadoop2.7", app_name = "sparklyr_test", config = spark_config())

```

**Comment by edgararuiz** [comment]
Can you make sure to have all of the packages listed in the Imports section in the CRAN page to their latest versions please? https://cran.r-project.org/web/packages/sparklyr/index.html

**Comment by connieshen0503** [comment]
Hi, I checked the all of the packages listed the Imports section in the CRAN page, and all the packages version are higher than the requirement.

**Comment by connieshen0503** [comment]
Problems fixed. It is the version problem. I installed two different versions of "rlang" package and the set the wrong lib. Please close the issue, thanks.

**Comment by kevinykuo** [comment]
Glad to hear you were able to resolve it!
