### ISSUE TITLE
defaul config YAML for cluster deployment

### ISSUE THREAD

**Issue by MarcinKosinski** [rstudio/sparklyr#136]
So far you have default `config-template.yml` for local Spark applications https://github.com/rstudio/sparklyr/blob/master/inst/conf/config-template.yml

According to #115 and #131, have you thought about adding `config-template-yarn.yml` or something so that a user could use

````{R}
spark_connect(master = "yarn-client", 
              config = 
                spark_config(
                  file = system.file(
                    file.path("conf", "config-template-yarn.yml"), 
                    package = "sparklyr"),
                  use_default = FALSE))
````

**Comment by jjallaire** [comment]
For this use case it might make sense to have a `yarn` parameter on `spark_config` rather than requiring a reference to a file in the package.

**Comment by MarcinKosinski** [comment]
So do you recommend to add `use_default_yarn = FALSE` parameter ? I could then provide a PR with `spark_config` extension`

**Comment by jjallaire** [comment]
I'd recommend just `yarn = FALSE`. @javierluraschi What do you think?

**Comment by MarcinKosinski** [comment]
semi PR is here https://github.com/rstudio/sparklyr/pull/142

**Comment by MarcinKosinski** [comment]
moved to #142
