### ISSUE TITLE
The "spark_connection" and "spark_jobj" S4 classes are not exported

### ISSUE THREAD

**Issue by lawremi** [rstudio/sparklyr#1374]
If a package expects other packages to use an S4 class, it should use `exportClasses()` to export them from `NAMESPACE`.

**Comment by kevinykuo** [comment]
Could you elaborate on the use case? These things are S3 in sparklyr.

**Comment by lawremi** [comment]
They are promoted to S4 classes via `setOldClass()`. As far as the use case, I want to use these classes from another package.
