### ISSUE TITLE
support for Java `char` type

### ISSUE THREAD

**Issue by lawremi** [rstudio/sparklyr#1395]
How does one pass Java `char` values from R? 

Example:
```
> invoke_new(con, "java.lang.Character", "f") 
Error: java.lang.Exception: No matched constructor found for class java.lang.Character
```

Not sure how best to support this. Could have a `java_char()` function that wraps a single-character string in R, marking it for conversion to `char`.

Come to think of it, there should probably also be a `java_short()`, `java_long()`, and `java_float()`.

**Comment by lawremi** [comment]
Any thoughts on this? I'm not aware of any workarounds, so it's a blocker for me. I could put together a PR if the above idea sounds reasonable.

**Comment by kevinykuo** [comment]
Taking a look. There are a couple issues here, one is method matching for one-character-string inputs, and the other is that `char`s get automatically serialized back to R character vectors so you can't pass it on to another Scala method using `invoke*`.

**Comment by lawremi** [comment]
Right. The idea (from rjava) is to have constructors like `java_char()` that just slap an S3 class on these types to get dispatch.

**Comment by kevinykuo** [comment]
@lawremi This should work now:
```
> invoke_new(sc, "java.lang.Character", "f") 
[1] "f"
```
Feel free to give us a shout if you run into further issues!

**Comment by lawremi** [comment]
Awesome, thanks!

**Comment by lawremi** [comment]
Turns out that I need to send a `java.lang.Character` to a method. How can I do that, since they are automatically converted to R character vectors? I guess you could support passing these single char strings to `java.lang.Character` parameters. Please let me know if you want a separate issue.

**Comment by kevinykuo** [comment]
It should just work like it does with the `java.lang.Character` constructor, which takes a `char`. Could you give it a try and let us know the result?

**Comment by lawremi** [comment]
Does not seem to work. I think the problem is here https://github.com/rstudio/sparklyr/blob/871d951cb36feae36e932128aa34535a6cff1fa3/java/spark-1.5.2/invoke.scala#L36

It checks that `parameterType` is of type `char` but it must also allow `java.lang.Character`. Otherwise it falls through and checks for whether the `java.lang.String` (from deserialization) is a `java.lang.Character`, which fails.

**Comment by kevinykuo** [comment]
@lawremi could you provide a sample function where this fails, to make sure I'm interpreting the use case correctly? Thanks!

**Comment by lawremi** [comment]
Just something like
```
public static void method(Character c) { }
```
I've fixed it locally by changing the line mentioned above as well as a similar condition later in the file. Something similar should be done for `java.lang.Long` and `java.lang.Short`.

**Comment by kevinykuo** [comment]
Oh got it, these are wrappers around the primitive types so they aren't matching.

Do you mind sending a PR?

**Comment by javierluraschi** [comment]
Fixed, missed to close.
