### ISSUE TITLE
GLM when observations of one variable are all the same

### ISSUE THREAD

**Issue by rtargino** [rstudio/sparklyr#1425]
Hello everyone,
I'm a new Spark user (through sparklyr) so sorry if I'm reporting this to the wrong people!

The title is pretty much self explanatory: When one of the variables of a table are all the same the GLM routine throws an error, which is not very clear (at least to me!). Wouldn't it be easier if the user got just a warning, instead? 

Also, would anyone suggest a quick workaround to this? As I have several variables, I really don't want to spend time checking if each one of them is all the same (specially knowing this test will also be performed on Scala...).

Here is a minimal reproducible example. Note that the behaviour is different from the glm routine from base R.

```r
library(sparklyr)
library(dplyr)

sc <- spark_connect(master = "local")

x = cbind(rep(1,5), 1:5)
y = rnorm(5)

df = as.data.frame(cbind(x,y))

copy_to(sc, df)

ml_generalized_linear_regression(x= tbl(sc, "df"), formula = y ~. , family = "gaussian", link = "log")


glm(formula = y ~. , family = gaussian(link = "log"), data = df, start = rep(1,3))

```

**Comment by kevinykuo** [comment]
Seems to be a convergence issue? With identity link:
```
> ml_generalized_linear_regression(x= tbl(sc, "df"), formula = y ~. , family = "gaussian", link = "identity")
Coefficients:
(Intercept)          V1          V2 
 -0.2234908   0.0000000  -0.1019399 

Degress of Freedom:  4 Total (i.e. Null);  2 Residual
Null Deviance:       0.7395
Residual Deviance:   0.6356	AIC: 11.88
```

**Comment by kevinykuo** [comment]
Closing since this doesn't seem to be a sparklyr issue.
