### ISSUE TITLE
skip.header.line.count not respected, results in header row in data

### ISSUE THREAD

**Issue by shabbybanks** [rstudio/sparklyr#1433]
Similar to [this SO issue](https://stackoverflow.com/q/49891914/6636442), I loaded the `iris` dataset from `R` into a table in hive via something like:
```sql
use dbname;
DROP TABLE IF EXISTS iris_clean;
CREATE EXTERNAL TABLE IF NOT EXISTS iris_clean(
  Sepal_Length DOUBLE,
  Sepal_Width DOUBLE,
  Petal_Length DOUBLE,
  Petal_Width DOUBLE,
  Species STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
LOCATION 'hdfs://nameservice1001/something/something/dbname.db/iris_clean'
TBLPROPERTIES ("skip.header.line.count"="1");

LOAD DATA INPATH 'hdfs://nameservice1001/something/something/dbname.db/iris_clean/iris.csv'
INTO TABLE iris_clean;

SELECT COUNT(*) FROM iris_clean;

+------+--+
| _c0  |
+------+--+
| 150  |
+------+--+

SELECT
species,
COUNT(*) as numrow
FROM iris_clean
GROUP BY species;

+-------------+---------+--+
|   species   | numrow  |
+-------------+---------+--+
| setosa      | 50      |
| versicolor  | 50      |
| virginica   | 50      |
+-------------+---------+--+
```

Then in R:
```R
suppressMessages({
  library(rlang)
  library(sparklyr)
  library(magrittr)
  library(dplyr)
  library(knitr)
  kbl <- knitr::kable
})

# set up spark#FOLDUP
get_sc <- function() {
  # this is *CRITICAL* to get na.omit to work properly
  # see https://github.com/rstudio/sparklyr/issues/988
  # might be fixed in sparklyr >=0.8.0 ?
  options(na.omit.cache=FALSE)

  config <- spark_config(file='~/config.yml')
  config$`sparklyr.log.console` <- FALSE

  sc <- spark_connect(master     = 'yarn',
                      config     = config,
                      app_name   = 'test_hive_sparklyr',
                      spark_home = Sys.getenv('SPARK_HOME'),
                      version    = '2.2.0')
}
sc <- get_sc()
#UNFOLD

tbl_change_db(sc,'dbname')

# show first 5 rows:
tbl(sc,'iris_clean') %>%
  collect() %>%
  head() %>%
  kbl()
```
I get the following:

| sepal_length| sepal_width| petal_length| petal_width|species |
|------------:|-----------:|------------:|-----------:|:-------|
|          NaN|         NaN|          NaN|         NaN|Species |
|          5.1|         3.5|          1.4|         0.2|setosa  |
|          4.9|         3.0|          1.4|         0.2|setosa  |
|          4.7|         3.2|          1.3|         0.2|setosa  |
|          4.6|         3.1|          1.5|         0.2|setosa  |
|          5.0|         3.6|          1.4|         0.2|setosa  |

**Comment by kevinykuo** [comment]
Don't think this is specific to sparklyr, see e.g. https://stackoverflow.com/questions/15751999/hive-external-table-skip-first-row. Please open a new issue if you're unable to reproduce in Scala.

**Comment by shabbybanks** [comment]
I should note that other apps built on top of Hive do respect this parameter, _e.g._ [presto](https://github.com/prestodb/presto/issues/1848), and it should be considered the canonical way to represent external CSV files with header lines.

**Comment by kevinykuo** [comment]
@shabbybanks Right, and unfortunately our hands are tied. You might have seen this, but there's more discussion in this PR https://github.com/apache/spark/pull/14638.

**Comment by shabbybanks** [comment]
I was not sure what you meant by 'hands are tied', but think I do now. If I can be explicit:
`sparklyr` is a layer built on top of bindings to Spark via scala, and since the Spark devs have decided not to respect this property of Hive tables, we have to pass through their decision, right or wrong, to `sparklyr` users.

Is that about right?

**Comment by kevinykuo** [comment]
That's exactly correct!

**Comment by shabbybanks** [comment]
OK, I vote to close, although I object to the Spark devs' decision on this. The canonical 'solution' appears to be to onboard CSV into a temporary table in Hive, then copy all but the first line of each CSV into the final table, then delete the temporary table, which sounds horrible but relatively easy to implement.
