### ISSUE TITLE
ml_tree_feature_importance() doesn't work for pipeline model stage

### ISSUE THREAD

**Issue by eddjberry** [rstudio/sparklyr#1436]
It seems that `ml_tree_feature_importance()` doesn't work when called on the `ml_random_forest_classification_model` stage of a pipeline model.

Reproducible example below.

Thanks!

```r
# Load packages
library(dplyr)
library(sparklyr)

# Set up connect
sc <- spark_connect(master = "local")

# Create a Spark DataFrame of mtcars
mtcars_sdf <- copy_to(sc, mtcars)

# The feature cols
feature_cols <- 
  c("mpg", "cyl", "disp", "hp", "drat", "wt", "qsec", "vs", "gear", "carb")

# Vector assembler
vector_assembler <- 
  ft_vector_assembler(
    sc,
    input_cols = feature_cols,
    output_col = "features")

# Estimator
estimator <- 
  ml_random_forest_classifier(
    sc, 
    label_col = "am") 

# Create the pipeline
pipeline <- ml_pipeline(vector_assembler, estimator)

# Fit the pipeline
pipeline_model <- pipeline %>%
  ml_fit(mtcars_sdf)

# Feature importance (doesn't work)
ml_tree_feature_importance(
  ml_stage(pipeline_model, 2)
)

# But they're there
ml_stage(pipeline_model, 2)$feature_importances

# Do it without the pipeline (works)
model <- ml_random_forest_classifier(
  mtcars_sdf,
  formula = am ~ mpg + cyl + disp + hp + drat + wt + qsec + vs + gear + carb
)

ml_tree_feature_importance(model)
```

**Comment by jkylearmstrong** [comment]
Thank you for reporting this issue I have been wondering the same thing. 

From looking at the example, it would appear that the output given by ``` ml_stage(pipeline_model, 2)$feature_importances ``` is in the same order as which the features are fed into the model so I wrote the following:

```r
library('tidyverse')
my_importance <- as.data.frame(cbind(feature_cols, ml_stage(pipeline_model, 2)$feature_importances))
colnames(my_importance) <- c('feature','importance')
my_importance  <- my_importance  %>% arrange(-as.numeric(importance))
```

**Comment by eddjberry** [comment]
I went for the same work around 😄. I meant to mention it in my initial post but I felt it was getting a bit long.

**Comment by nik-maheshwari** [comment]
This is not useful if you have a large number of features and your formula looks something like `response ~ .`. In this case, the feature importances are not arranged in the same order as the feature names, hence combing them together in a data.frame is misleading. How can one get identical results as `ml_tree_feature_importance(model)` ?
