### ISSUE TITLE
Dealing with multiple databases

### ISSUE THREAD

**Issue by ElianoMarques** [rstudio/sparklyr#144]
currently for you to leverage the tbl function you have to specify upfront the database. 

Its normal in projects that you need to use tables from multiple databases. 

So would be great if we can find a way to as part of the tbl statement add the database name prior to table name.

```
tbl(sc, "databasename.tablename") 
```

perhaps another feature that could be added is src_databases(sc) similar to src_tbls(sc) 

This will smooth the joins of tables from multiple databases and avoid multiple dbGetQuery(sc, "use database"). 

Thanks

**Comment by chezou** [comment]
I found it depends on dplyr behavior. dplyr assumes the second argument of `tbl()` is only for the table name and it doesn't handle database name.

https://github.com/hadley/dplyr/blob/master/R/sql-escape.r#L241-L248

**Comment by ElianoMarques** [comment]
Great stuff thanks
