### ISSUE TITLE
Failed to connect to Spark (SPARK_HOME is not set).

### ISSUE THREAD

**Issue by hiltonmbr** [rstudio/sparklyr#145]
sparklyr returns the following error on start a connection:

library(sparklyr)
sc <- spark_connect(master="local[*]")

Error in spark_connect(master = "local[*]") : 
  Failed to connect to Spark (SPARK_HOME is not set).

spark_installed_versions()
  spark hadoop                       dir
1 2.0.0    2.7 spark-2.0.0-bin-hadoop2.7
It only works if I use:

sc <- spark_connect(master="local[*]",
      spark_home=paste0(sparklyr::spark_install_dir(),
     "/",sparklyr::spark_installed_versions()$dir))

Any idea?

**Comment by ElianoMarques** [comment]
I typically start by specifying spark home env. variables and also the hadoop conf dir. Once you do that, it no longer complains about this. Alternatively you could add this to your startup script, like this in the terminal:

```
cat <<EOF >> ~/.Renviron
Sys.setenv(HADOOP_CONF_DIR="/etc/hadoop/conf")
Sys.setenv(SPARK_HOME='/usr/hdp/current/spark-client')
EOF
```

**Comment by hiltonmbr** [comment]
Thanks. I've solved this issue using
sc <- spark_connect(master = "local", version = "2.0.0")

**Comment by javierluraschi** [comment]
Just fixed this with https://github.com/rstudio/sparklyr/commit/b93b8e9a9a2ccd3ed2c1411a4dcfb7617f1e4ab3, this was a recent regression. Thanks for pointing this out!
