### ISSUE TITLE
Error: 'could not find function "connection_is_open" ' 

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/sparklyr#147]
- new cluster
- sparklyr version 0.3.0
- spark_connect() works fine
- But then spark_read_xxx() gives this error after operation is completed:

```
Error: could not find function "connection_is_open"
```

**Comment by jjallaire** [comment]
It's a stale IDE connection. I'll invalidate old connections in the next
daily build, in the meantime just restart R, navigate to the connection in
the IDE, then click the "Trash" icon in the top right corner of the Spark
tab.

**Comment by kevinushey** [comment]
I'm going to close this; @fereshtehRS please re-open if you're still seeing an issue here. Thanks!
