### ISSUE TITLE
investigate failure with Spark 2.0.0

### ISSUE THREAD

**Issue by kevinushey** [rstudio/sparklyr#148]
```
> flights_tbl <- copy_to(sc, flights, overwrite = TRUE)
 Error in invoke_method.spark_shell_connection(sc, TRUE, class, method,  : 
  No status is returned. Spark R backend might have failed. 
```

Most likely fallout from the sparkapi merge -- perhaps some code changes are needed in our backend port.

**Comment by kevinushey** [comment]
I believe this was fixed up with some recent changes from @javierluraschi.

**Comment by mkaja** [comment]
is there any update on this issue ?

**Comment by kevinushey** [comment]
This particular issue was resolved, but if you're seeing the same / a similar issue, then please file a new issue (with information about your system and what commands you're running).
