### ISSUE TITLE
Invoke toDebugString() with ml_decision_tree

### ISSUE THREAD

**Issue by yhu5** [rstudio/sparklyr#1482]
I am using sparklyr on databricks and trying to invoke the toDebugString() to extract rules from the decision tree model built with ml_decision_tree() function. I read from [another post](https://github.com/rstudio/sparklyr/issues/424) that I should use invoke but I got the below errors. How can i extract the decision tree rules correctly here?

```r
ml_dt <- ml_decision_tree(data_tbl3,
                    dt_formula,
                   impurity='gini',
                   type='classification')

invoke(ml_dt$model, "toDebugString")

Error in UseMethod("invoke") : 
  no applicable method for 'invoke' applied to an object of class "c('ml_decision_tree_classification_model', 'ml_prediction_model', 'ml_transformer', 'ml_pipeline_stage')"
```

**Comment by harryprince** [comment]
@yhu5 your syntax is wrong, make sure `ml_dt$model` is an object that can be invoked.

probably you need to wrap your `ml_dt$model` by `spark_jobj` or `spark_dataframe` and so on.

**Comment by shwetapurushe** [comment]
@harryprince is right. This seems to work
