### ISSUE TITLE
Sparklyr with Hadoop SequenceFile input type (key-value pairs)

### ISSUE THREAD

**Issue by yuying273** [rstudio/sparklyr#1488]
I have a question about the data input type for sparklyr. I want to work on the pair RDD (key-value pairs). Is there a way to write and load sequenceFile type in sparklyr?

What I want to do is to simulate a big data frame (size vary from GB to TB), partition it into subsets and work on each subset in parallel. Is there a good way to simulate big Spark Data Frame in sparklyr and save on hdfs? 

Thank you very much!

Sincerely,

Yuying

```r
spark_version <- "2.2.0"
sc <- spark_connect(master = "yarn-client", version = spark_version)

# your reproducible example here
```

**Comment by harryprince** [comment]
I recommend you read your sequence File via Hive table, and save your data as Parquet File.

**Comment by yuying273** [comment]
@harryprince 
I am sorry I reply late. Thank you very much!!

Yuying
