### ISSUE TITLE
Problems with Rstudio overall

### ISSUE THREAD

**Issue by golnar-bt** [rstudio/sparklyr#1490]
I am having a lot of issues with my Rstudio overall (It keeps crashing on me. Every time i open it—even after removing objects, quitting, and restarting my laptop— I have some files in my environment that I do not even know where they come from. It runs codes sometimes and does not at other times without me making any changes at all)
I had already committed and pushed my part1. But now it is giving me trouble to rerun the codes even though I have made absolutely no changes to my part 1.  First it was giving me error when I was trying to create a function for scoring. After a few restarts, it now gives me error before even getting there. I try to split my data into train and test:

partition <- titanic2_tbl %>% 
  mutate(Survived = as.numeric(Survived)) %>%
  select(Survived, Pclass, Sex, Age) %>%
  sdf_partition(train = 0.75, test = 0.25, seed = 1234)

I get the following error.
"Error in (function (classes, fdef, mtable) : unable to find an inherited method for function ‘select’ for signature ‘"tbl_spark" 

I have all my libraries loaded and even packages updated. My problems show up, come and go so randomly that I don't know how to submit my homework!

**Comment by javierluraschi** [comment]
@golnar-bt could you share your `sessionInfo()`?

**Comment by harryprince** [comment]
@golnar-bt 
maybe you load package is wrong.

**Comment by golnar-bt** [comment]
Thank you. There was something wrong with Rstudio on my laptop. I had to take it in to IT bar on my campus. Thank you all for responding !
