### ISSUE TITLE
ICONV spark_apply

### ISSUE THREAD

**Issue by mimeides2** [rstudio/sparklyr#1495]
Hi, i would like your light....
I want to use Iconv in a spark_apply but it seems to use only one executor and I don t know

A <- A %>% spark_apply(function(e) {
e$var <- iconv(e$var,to='ASCII/IGNORE/TRANSLIT')
return(e)
})

thanks a lot

Mimeides

**Comment by javierluraschi** [comment]
@mimeides2 the number of executors used in `spark_apply` is determined by how the Spark data frame is partitioned in your cluster, you could try using `sdf_repartition()` before `spark_apply()` to redistribute your data frame across many executors to run all of them.

**Comment by javierluraschi** [comment]
@mimeides2 the number of executors used in `spark_apply` is determined by how the Spark data frame is partitioned in your cluster, you could try using `sdf_repartition()` before `spark_apply()` to redistribute your data frame across many executors to run all of them.

**Comment by mimeides2** [comment]
greatttttt !!!!!!
It works very weelllll .....
  Great package, great man, great team
