### ISSUE TITLE
Livy connection curl_fetch_memory timeout

### ISSUE THREAD

**Issue by ckrietemeyer** [rstudio/sparklyr#1500]
I am receiving the following error, when trying to connect to Spark via Livy:
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Connection timed out after 10001 milliseconds

I have been able to connect to Spark via a Livy connection all last week; however this error has just arise the past few days.

I have tried to connect using sparklyr versions:
                      - 0.7.0
                      - 0.8.0
                      - 0.8.1
                      - 0.8.3

As well as Spark versions 2.2.1 and 2.3.0.

I have been unable to find any online resources to better explain a potential solution to this issue.

If anyone has dealt with this issue a solution would be greatly appreciated!

I am not able to obtain the detailed logs, but I have a screenshot of the code I was running (minus the IP address), the error, and sessionInfo().

Thank you.

![image](https://user-images.githubusercontent.com/22913819/40138536-8ddea142-5912-11e8-8a2f-7ada73607eb5.png)

**Comment by harryprince** [comment]
@ckrietemeyer 
using `config = sparklyr::spark_config()` instead of `livy_config(xxx)`

**Comment by ckrietemeyer** [comment]
@harryprince 
The issue has been solved. It was a combination of Maven not being installed correctly as well as the two server environments being on the same subnet.
