### ISSUE TITLE
sparklyr kafka stream

### ISSUE THREAD

**Issue by matesio** [rstudio/sparklyr#1509]
Hi 
Apologies. I know this can not be an issue,  I am using sparklyr  to run jobs on my spark clusters now i have large amount of data coming from kafka, but i do not know how can i handle it in sparklyr.  
Thank you.

**Comment by javierluraschi** [comment]
Yes, we are planning to add Spark Streaming support, we are tracking this work with https://github.com/rstudio/sparklyr/issues/1131.
