### ISSUE TITLE
Optimize performances of glimpse() by adding a LIMIT statement

### ISSUE THREAD

**Issue by dalloliogm** [rstudio/sparklyr#1515]
By running explain on a call to the glimpse function, I've realized that it queries the whole table ("SELECT * FROM mytable" ), while it would be much more efficient to query just the first lines of the table ("SELECT * FROM mytable LIMIT 10").

In fact, running mytable %>% head %>% glimpse runs much faster than mytable %>% glimpse.

What would be needed to change this behaviour, and add a "LIMIT 10" to the query?

```r
> spark_version <- "2.1.0"
> sc <- spark_connect(master = "local", version = spark_version)

> mytable = data.frame(x=rnorm(100)) %>% copy_to(sc, .)
> mytable %>% glimpse %>% explain
Observations: ??
Variables: 1
$ x <dbl> 0.46503227, 0.14146764, 0.33220509, -0.15956371, 1.29380242, -1.4...
<SQL>
SELECT *
FROM `sparklyr_5b0658e82f67`


<PLAN>
```

Thanks,
Gio

**Comment by kevinykuo** [comment]
This is already done at https://github.com/tidyverse/tibble/blob/master/R/glimpse.R#L45

**Comment by javierluraschi** [comment]
Fixed by https://github.com/tidyverse/tibble/commit/4368f401a8757a18fcebe3f6b718f7d32df7e8b6
