### ISSUE TITLE
Kubernetes

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#1525]
One can launch Spark in Kubernetes from sparklyr as:

```r
sc <- spark_connect(
  master = "k8s://http://127.0.0.1:8001"
  config = list(
    spark.executor.instances = 2,
    spark.kubernetes.container.image = "spark-image"
  )
)
```

However, connectivity to Kubernetes would be blocked since `sparklyr` would not be able to find the application master.

See also https://spark.apache.org/docs/latest/running-on-kubernetes.html

**Comment by javierluraschi** [comment]
Here is some initial ongoing investigation to get this working, not ready for consumption...

In `sparklyr` you can run something similar to [spark with kubernetes](https://kubernetes.io/blog/2018/03/apache-spark-23-with-native-kubernetes/) to launch a Spark Kubernetes cluster; afterwards, `sparklyr` needs to find out which is the driver node using `kubectl` and connects to the driver node. Once connected, `sparklyr` should work in the same way as when working with any other cluster manager: Yarn, Mesos, etc.

To use kubernetes locally:
- Install the [kubernetes-cli](https://kubernetes.io/docs/tasks/tools/install-kubectl/) and [minikube](https://github.com/kubernetes/minikube/releases), from OS X you can run: `brew install kubernetes-cli minikube`.
- Run `minikube start` as described in the [quickstart](https://kubernetes.io/docs/setup/minikube/#quickstart)
- Get the master address by running `kubectl cluster-info`.
- Create a `sparklyr` folder in `SPARK_HOME` and copy the `sparklyr` jars from ``.
- Modify the Spark `kubernetes/dockerfiles/spark/Dockerfile` to create a `/opt/sparklyr` path and copy the `sparklyr` jars. For instance by adding `mkdir -p /opt/sparklyr && \` and `COPY sparklyr /opt/sparklyr`.
- Generate the cluster [docker images](https://github.com/apache/spark/blob/master/docs/running-on-kubernetes.md#docker-images) by running from SPARK_HOME: `./bin/docker-image-tool.sh -m -t sparklyr build`. However, you might hit an error with a workaround available in [this](https://iamninad.com/running-spark-job-on-kubernetes-minikube/) post.

Launch `sparklyr` as follows:

```r
sc <- spark_connect(
  master = "k8s://https://192.168.99.100:8443",
  config = list(
    "sparklyr.shell.master" = "k8s://https://192.168.99.100:8443",
    "sparklyr.shell.deploy-mode" = "cluster",
    "sparklyr.shell.name" = "sparklyr",
    "sparklyr.shell.conf" = c(
      "spark.kubernetes.container.image=spark:sparklyr",
      "spark.kubernetes.driver.pod.name=spark-pi-driver"
    ),
    "sparklyr.app.jar" = "local:///opt/sparklyr/sparklyr-2.3-2.11.jar"
  ),
  spark_home = spark_home_dir()
)
```

**Comment by javierluraschi** [comment]
Implemented with https://github.com/rstudio/sparklyr/pull/1599

**Comment by kkeenan02** [comment]
@javierluraschi Thank you for making the effort to build kubernetes support into sparklyr. 

I'm trying to understand how to implement this for myself, and am hoping you could shed a bit more light, please. I am trying to connect to a remote spark master on the same kubernetes cluster as my rstudio-server instance (with sparklyr installed), with the aim of being able to execute sparklyr commands against the spark cluster from within rstudio. I have added the sparklyr jars to the spark container, but when I try to run the spark_connect code above (substituting my local urls etc.), I get the following error

```r
Error in shell_connection(master = master, spark_home = spark_home, app_name = app_name,  : 
  Failed to connect to Spark (SPARK_HOME is not set).
```

Am I misunderstanding something fundamental here? For example, does the spark master and rstudio instance have to co-exist on the same container?

Any insight you can provide would be greatly appreciated.

Kevin

**Comment by javierluraschi** [comment]
@kkeenan02 this work was only to enable connection to new kubernetes clusters... if you have an existing kubernetes clusters, you probably don't even need this work, let me elaborate.

One option to use Kubernetes is for someone to start a Spark cluster, usually your system admin or someone in your team, you can use Kubernetes to start a team cluster running Yarn, Cloudera or why not. Then you can connect to this cluster from `sparklyr` as "usual", the recommended approach is to also start RStudio Server while creating the kubernetes cluster, such that, once the cluster starts, you can navigate to a URL with RStudio Server and connect using `sc <- spark_connect(master = "local")`, I'm assuming Yarn is running inside kubernetes, but spark standalone or other options could be in place. For this use case, you don't even need the work of sparklyr 0.9. From what you mention, sounds like you might be in this situation.

The other option which this PR enables in sparklyr 0.9, is for cases where a generic kubernetes cluster is provided, read a bunch of machines without anything installed. In these cases, you can create your own VM image for the cluster that while connecting with `spark_connect()` triggers the creation of Spark inside the cluster by initializing the right VMs with the right image and then establishing the connection. To be honest, this is a pretty advance use case, so again, my guess is that you are on the former use case and you don't need to worry about where the cluster is actually running.

**Comment by alokgogate** [comment]
@javierluraschi, I was trying the other option that you have mentioned with version of sparklyr 1.0.0 with spark (2.4.0) running on kubernetes and yet face the issue that @kkeenan02 has.
Here is my code so far:

```
config <- spark_config_kubernetes(master="k8s://192.168.1.1:6443",
                              config = list(
                                spark.submit.deployMode = "client",
                                spark.kubernetes.namespace = "spark-project1",
                                spark.driver.host = "192.168.1.1",
                                spark.driver.port = 7787,
                                spark.kubernetes.container.image = "http://192.168.1.1:5000/spark/spark-r",
                                spark.executor.instances = 2,
                                spark.kubernetes.driver.request.cores = 32,
                                spark.kubernetes.driver.limit.cores = 32,
                                spark.kubernetes.executor.request.cores = 12,
                                spark.kubernetes.executor.limit.cores = 13,
                                spark.executor.core = 12,
                                spark.executor.memory = "20G",
                                spark.kubernetes.authenticate.driver.serviceAccountName = "spark"
                              ))
 

sc <- spark_connect(config = config)
```

Any suggestions as to what's wrong here ?
