### ISSUE TITLE
Is there an example how to write ORC format from sparklyr?

### ISSUE THREAD

**Issue by JohnMount** [rstudio/sparklyr#1548]
Is there an example of how to write in ORC SERDE from spakrlyr?  I see examples for parquet (though I would also like to know how to set the compression format for those), but haven't found ORC yet.

**Comment by javierluraschi** [comment]
There wasn't but now there is: https://github.com/rstudio/sparklyr/pull/1551 - I'll merge the PR once test succeed, would be great if you could validate this works for you, @JohnMount.

**Comment by javierluraschi** [comment]
The new functions are named: `spark_write_orc()` and `spark_read_orc()`, they work in the same way as parquet, csv, etc.

**Comment by JohnMount** [comment]
Sounds great.  I'll have to test it locally as the client isn't at a stage they can upgrade right now. So if I understand after you merge the PR I can try the dev version of sparklyr and see if I get it right.

**Comment by javierluraschi** [comment]
Yes, it's merged now, so you can be the first to give this a shot.

**Comment by JohnMount** [comment]
I'l try to do that later today. And thank you very much.
