### ISSUE TITLE
Prefix span implementation is not there?

### ISSUE THREAD

**Issue by anubnair** [rstudio/sparklyr#1560]
I am trying to implement prefix span from https://spark.apache.org/docs/2.2.0/mllib-frequent-pattern-mining.html 
https://spark.apache.org/docs/2.2.0/api/scala/index.html#org.apache.spark.mllib.fpm.PrefixSpan

Is it available in sparklyr?

**Comment by kevinykuo** [comment]
Only spark.ml, i.e. the DataFrame-based API, is implemented. See https://github.com/rstudio/sparklyr/blob/3789825d2ae683ca758465b3fe0fc15455fbfef9/tests/testthat/test-ml-fpm-fpgrowth.R for usage example for FPGrowth.

**Comment by emilyriederer** [comment]
I noticed that the current version of Spark ML has now implemented [PrefixSpan](https://spark.apache.org/docs/latest/ml-frequent-pattern-mining.html) Does this re-open the possibility of it being added to `sparklyr` in the future? Thanks!
