### ISSUE TITLE
A minor issue in livy_validate_master 

### ISSUE THREAD

**Issue by ciasom** [rstudio/sparklyr#1562]
I'm not sure why there is no "break" in the while loop when livy_get_sessions doesn't throw. Is that intentional or a little bug?

```r
  while (retries >= 0) {
    tryCatch({
      livy_get_sessions(master, config)
    }, error = function(err) {
      retriesErr <- err
    })

    retries <- retries - 1;
    Sys.sleep(1)
  }
```

**Comment by The-Dub** [comment]
`break` is only needed for `repeat`. The condition to exit the `while`loop is at the beginning (in this case, the while loop exit when `retries < 0`)

no bug :)

**Comment by ciasom** [comment]
Thanks @The-Dub.  Yes, no bug.  But is it necessary to check the site 6 times even if the master is available?
