### ISSUE TITLE
long operations do not always cancel

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#157]
In general, it would be nice to be able to cancel all operations cleanly, for instance, while hitting <stop> in the RStudio console (feedback from Nathan). This needs some investigation on what it would take to improve this.

**Comment by slopp** [comment]
I've experienced that in the IDE, if you're running a long-running piece of code and hit stop, it will kill the whole connection to Spark (very annoying)

**Comment by MarcinKosinski** [comment]
I have experienced that when you type stop on one bit of a code (e.g. k-means clustering on 2 columns and 7 mln observations) then it does not stop in the SPARK UI.

**Comment by kevinushey** [comment]
Indeed, and that's a big problem in general -- interrupting the R session without interrupting Spark basically places the R connection to Spark in a bad state, and effectively you'll just see a cascade of errors as the connections effectively become out of sync. :/

**Comment by javierluraschi** [comment]
The current workaround is to manually kill the Spark application from the Spark UI, but we do want to consider improving this.

**Comment by kevinykuo** [comment]
Killing the job from the Spark UI also loses the connection from sparklyr, which requires a new `spark_connect()` and can be pretty annoying. Related: https://github.com/rstudio/sparklyr/issues/297

**Comment by javierluraschi** [comment]
Tracked now by https://github.com/rstudio/sparklyr/issues/948
