### ISSUE TITLE
WITH clause not supported in Spark SQL

### ISSUE THREAD

**Issue by tdsmith** [rstudio/sparklyr#1585]
Spark SQL supports the WITH clause for common table expressions. Sparklyr assumes that it can execute any SQL handed to it from e.g. `tbl(sc, sql(some_sql))` as a subquery, but WITH clauses do not seem to be supported as subqueries.

For example, a trivial example:
```sql
WITH demo AS ( SELECT 1 AS n ) SELECT n FROM demo
```

succeeds when run from a Databricks SQL cell.

Called from R, it fails:
```
> tbl(sc, sql("WITH demo AS ( SELECT 1 AS n ) SELECT n FROM demo"))

Error : org.apache.spark.sql.catalyst.parser.ParseException: 
mismatched input 'FROM' expecting <EOF>(line 2, pos 0)

== SQL ==
SELECT *
FROM (WITH demo AS ( SELECT 1 AS n ) SELECT n FROM demo) `zzz17`
^^^
WHERE (0 = 1)
```

The wrapper around the query seems to be applied by `db_query_fields.spark_connection` since abba9a24f.

**Comment by harryprince** [comment]
don't need use WITH function in spark SQL. because which can cache as a variable naturally.

**Comment by javierluraschi** [comment]
@tdsmith  Use `DBI` instead, `dplyr` is best used for writing `dplyr` queries, but if you need access to SQL functionality, `DBI` has you covered, for instance:

```r
DBI::dbGetQuery(sc, "WITH demo AS ( SELECT 1 AS n ) SELECT n FROM demo")
```
```
  n
1 1
```
