### ISSUE TITLE
how to use data from Hive on  YARN cluster with sparklyr?

### ISSUE THREAD

**Issue by MarcinKosinski** [rstudio/sparklyr#159]
When one finally connects to YARN cluster with those commands https://github.com/rstudio/sparklyr/issues/131#issuecomment-238604605, how then one can use datasets stored on Hive/HDFS to apply e.g. `ml_kmeans` on them?

I imagine it would be: 

````{R}
dataset <- tbl(sc, sql("simple select"))
````

but `src_tbls()` does not find datasets stored on Hive/HDFS.

Is there any HiveContext/SQLContext?

**Comment by RobClaxton** [comment]
I ran into the same issue and resolved it by copying /etc/hive/conf/hive-site.xml into the conf directory of my Spark installation.

Then you can use something like below to make your table available.

```library(DBI)  
dbGetQuery(sc, "USE mydatabase")  
t <- tbl(sc, "mytable")
```

**Comment by MarcinKosinski** [comment]
Wow.
The most amazing magic and witchcraft that I have seen so far : D

I'll check that out and let you know.

@RobClaxton have you thought about extending the deployment `Tricks and Tips` https://github.com/rstudio/spark.rstudio.com/blob/master/deployment.Rmd ?

**Comment by MarcinKosinski** [comment]
@RobClaxton do you think that specifying `HIVE_HOME` to the folder `/etc/hive/` might help instead of copying that file to `SPARK_HOME` dir?

**Comment by MarcinKosinski** [comment]
You were right. I haven't had Hive configured for my machine. After I proceed with the configuration, the `hive-site.xml`, `core-site.xml` and `hdfs-site.xml` appeared in the `HADOOP_CONF_DIR` as this is suggested here http://spark.apache.org/docs/latest/sql-programming-guide.html#hive-tables [for R]

> Configuration of Hive is done by placing your hive-site.xml, core-site.xml (for security configuration), and hdfs-site.xml (for HDFS configuration) file in conf/.

**Comment by slopp** [comment]
In case anyone stumbles across this. As of Spark 0.6, there is now `tbl_change_db` to help!
