### ISSUE TITLE
coefficients from logistic regression have arbitrary sign?

### ISSUE THREAD

**Issue by shabbybanks** [rstudio/sparklyr#1591]
I have found that _sometimes_ the sign of coefficients from `ml_logistic_regression` are opposite what I would expect, although predictions from the model come out sensibly, which makes me think there is some kind of remapping under the hood. Here is a minimal example illustrating what I would consider a problem:
```r
library(sparklyr)
library(dplyr)
# sc is a spark context.
# make dummy data
train_data <- iris %>%
  mutate(is_setosa=as.numeric((Species=='setosa'))) %>%
  mutate(is_not_setosa=1-is_setosa) %>%
  setNames(gsub('\\.','_',names(.)))
# fit logistic models in R
r_mod_fwd <- glm(formula=is_setosa ~ Sepal_Length,data=train_data,family=binomial(link='logit'))
r_mod_rev <- glm(formula=is_not_setosa ~ Sepal_Length,data=train_data,family=binomial(link='logit'))
# copy data to spark
spark_data <- copy_to(sc,train_data,'like_iris',overwrite=TRUE)
# fit logistic models in spark
s_mod_fwd <- spark_data %>% ml_logistic_regression(formula = is_setosa ~ Sepal_Length)
s_mod_rev <- spark_data %>% ml_logistic_regression(formula = is_not_setosa ~ Sepal_Length)
# get the coefficients:
# in R they are opposites
coefficients(r_mod_fwd)
coefficients(r_mod_rev)
# in spark, not so much:
coefficients(s_mod_fwd)
coefficients(s_mod_rev)
# why?
```
When I run this, I get the output: (sorry for the cut and paste job; `reprex` was being fussy about my spark context)
```
> coefficients(r_mod_fwd)
 (Intercept) Sepal_Length
      27.829       -5.176
> coefficients(r_mod_rev)
 (Intercept) Sepal_Length
     -27.829        5.176
> # in spark, not so much:
> coefficients(s_mod_fwd)
 (Intercept) Sepal_Length
      27.829       -5.176
> coefficients(s_mod_rev)
 (Intercept) Sepal_Length
      27.829       -5.176
```
Logistic regression in `R` does the right thing, flipping the sign of coefficients when I fit the 'opposite' model. However, the fit via `ml_logistic_regression` seems to choose the reference class the same way in both fits, and remaps them later.

I checked, and prediction seems fine here, respecting whatever remapping is going on, so we have
```r
# prediction is fine, of course
sdf_predict(s_mod_fwd,spark_data) %>% collect(n=3) %>% dplyr::select(Sepal_Length,label,rawPrediction,predicted_label) %>% knitr::kable()
sdf_predict(s_mod_rev,spark_data) %>% collect(n=3) %>% dplyr::select(Sepal_Length,label,rawPrediction,predicted_label) %>% knitr::kable()
```
These give, respectively, 

| Sepal_Length| label|rawPrediction |predicted_label |
|------------:|-----:|:-------------|:---------------|
|          5.1|     1|-1.432, 1.432 |1.0             |
|          4.9|     1|-2.468, 2.468 |1.0             |
|          4.7|     1|-3.503, 3.503 |1.0             |

And 

| Sepal_Length| label|rawPrediction |predicted_label |
|------------:|-----:|:-------------|:---------------|
|          5.1|     1|-1.432, 1.432 |0.0             |
|          4.9|     1|-2.468, 2.468 |0.0             |
|          4.7|     1|-3.503, 3.503 |0.0             |

**Comment by shabbybanks** [comment]
Poking around in the objects, it looks like the remapping might be encoded in _e.g._ `s_mod_fwd$.index_labels`. In my examples, these have the values:
```
> s_mod_fwd$.index_labels
[1] "0.0" "1.0"
> s_mod_rev$.index_labels
[1] "1.0" "0.0"
```
Thus the model coefficients are 'reversed' when the index labels are `c('1.0', '0.0')` and are correct when they are `c('0.0', '1.0')`.

**Comment by shabbybanks** [comment]
I have added tests for this error in my fork of the repo, but am unable to make a PR of the single commit (and my institution blocks github access other than via browser).

**Comment by kevinykuo** [comment]
If we flip the labels shouldn't the coefficients be flipped, too? Where is sparklyr not consistent/buggy here?

**Comment by kevinykuo** [comment]
Oh just kidding I see it now, will investigate

**Comment by kevinykuo** [comment]
It looks like this behavior is expected given the design, since we're indexing the label column regardless of its type. In the case of `s_mod_rev`, `1.0` is being mapped to `0` where `0.0` is being mapped to `1`. If we change the behavior to not index when the column is numeric, we would break existing code, and attempting to run a binary classification on a dataset with label column values `c(1, 2)` would result in a 3-class classification model.

However, this behavior can be confusing, especially in this example. One way forward is to print the label mappings with the coefficients, and export a helper function to easily retrieve the mappings.

**Comment by shabbybanks** [comment]
I am not sure how else to perform binary logistic regression with `ml_logistic_regression`. I have found that this 'reversal' of classes occurs for double as well as integer data, while the classifier errors out for boolean data:
```r
library(datasets)
data(iris)
set.seed(1234)
train_data <- iris %>%
  mutate(Random_x = rnorm(n())) %>%
  mutate(is_setosa=as.numeric((Species=='setosa'))) %>%
  mutate(is_not_setosa=1.0-is_setosa) %>%
  mutate(int_setosa=as.integer((Species=='setosa'))) %>%
  mutate(int_not_setosa=1L - int_setosa) %>%
  mutate(bool_setosa=(Species=='setosa')) %>%
  mutate(bool_not_setosa=! bool_setosa) %>%
  setNames(gsub('\\.','_',names(.)))

# copy it into spark
spark_data <- copy_to(sc,train_data,'delete_me_iris',overwrite=TRUE)
# model it in sparklyr:
s_mod_dbl0 <- spark_data %>% ml_logistic_regression(formula = is_setosa ~ Sepal_Length + Random_x)
s_mod_dbl1 <- spark_data %>% ml_logistic_regression(formula = is_not_setosa ~ Sepal_Length + Random_x)
s_mod_int0 <- spark_data %>% ml_logistic_regression(formula = int_setosa ~ Sepal_Length + Random_x)
s_mod_int1 <- spark_data %>% ml_logistic_regression(formula = int_not_setosa ~ Sepal_Length + Random_x)

# this errors out:
s_mod_bol0 <- spark_data %>% ml_logistic_regression(formula = bool_setosa ~ Sepal_Length + Random_x)
s_mod_bol1 <- spark_data %>% ml_logistic_regression(formula = bool_not_setosa ~ Sepal_Length + Random_x)
```
The latter throws errors like:
```
Error: java.lang.IllegalArgumentException: requirement failed: The input column bool_setosa must be either string type or numeric type, but got BooleanType.
```

The coefficients are reversed for all reverse models, however:
```r
coef(s_mod_dbl0)
coef(s_mod_dbl1)
coef(s_mod_int0)
coef(s_mod_int1)
```
gives:
```
> coef(s_mod_dbl0)
 (Intercept) Sepal_Length     Random_x
     27.4355      -5.1196      -0.4089
> coef(s_mod_dbl1)
 (Intercept) Sepal_Length     Random_x
     27.4355      -5.1196      -0.4089
> coef(s_mod_int0)
 (Intercept) Sepal_Length     Random_x
     27.4355      -5.1196      -0.4089
> coef(s_mod_int1)
 (Intercept) Sepal_Length     Random_x
     27.4355      -5.1196      -0.4089
```
and
```r
s_mod_dbl0$.index_labels
s_mod_dbl1$.index_labels
s_mod_int0$.index_labels
s_mod_int1$.index_labels
```
yields
```
> s_mod_dbl0$.index_labels
[1] "0.0" "1.0"
> s_mod_dbl1$.index_labels
[1] "1.0" "0.0"
> s_mod_int0$.index_labels
[1] "0" "1"
> s_mod_int1$.index_labels
[1] "1" "0"
```

**Comment by javierluraschi** [comment]
Notice that a few test cases were provided in https://github.com/rstudio/sparklyr/pull/1598, just FYI.

**Comment by kevinykuo** [comment]
@shabbybanks Currently, using the formula interface, i.e. via the signature `ml_logistic_regression(tbl_spark, formula)`, there's no way to specify how the label column is indexed. The `RFormula` estimator uses `frequencyDesc` (https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.ml.feature.RFormula) so how your labels are mapped is dependent on how often each level occurs in the dataset. You can specify the exact mapping if you use the pipelines API, via the `labels` argument of `ft_string_indexer()`. However, thinking about this some more, we may want to introduce a breaking change, since the current behavior is potentially dangerous.

I'll work on a change now, and we can test it out.

**Comment by shabbybanks** [comment]
As I understand it, it is a design goal to make the interface of `ml_logistic_regression` familiar to the `R` user. In that regard it's behavior should be as close to `glm` as possible. Remapping labels would violate the principle of least surprise, and seems very dangerous to me.

For that matter, it might be worthwhile to consider what input `glm` accepts for labels. In my experimentation, I have found that it will accept 0/1 numeric labels, but errors out for 0/2 numeric labels. (I think `glm` might accept other labels for _weighted_ logistic regression when the weights are number of trials.) On the contrary, `ml_logistic_regression` of course happily accepts 0/2 numeric (or integer) labels. So some decision has to be made about how closely to conform to `glm` in terms of what input to accept/reject.
