### ISSUE TITLE
Contradicting error with sparklyr and spark 2.3

### ISSUE THREAD

**Issue by andreysharapov** [rstudio/sparklyr#1600]
Hi 

I am running into strange problems with the latest sparklyr

1. When I set "SPARK_HOME" = "/usr/hdp/current/spark2-client" I get an error
[ERROR] 2018-07-12 08:25:07 [base::source] Error: org.apache.spark.sql.AnalysisException: Table or view not found: `ia01ca_pvt`.`PV_MODEL_QUEUE`; line 1 pos 35;
'Aggregate ['CONCAT('q_werbejahr, -, 'q_werbewoche, -, 'q_client_id)], ['MAX('q_timestamp) AS ts#0]
 +- 'UnresolvedRelation `ia01ca_pvt`.`PV_MODEL_QUEUE`

2. When I remove the variable SPARK_HOME I get another error

Error in shell_connection(master = master, spark_home = spark_home, app_name = app_name,  : 
  Failed to connect to Spark (SPARK_HOME is not set).
Calls: source ... get.spark.session -> spark_connect -> shell_connection

scala and pyspakr work ok.

Please suggest a solution. 

```r
spark_version <- "2.3.0"

library(sparklyr)
library(dplyr)
Sys.setenv("SPARK_HOME" = "/usr/hdp/current/spark2-client")
sc <- spark_connect(master = "yarn-client", config = spark_config())
hive <- hive_context(sc)
hive %>% invoke("sql", query = "SELECT MAX(q_timestamp) as ts FROM ia01ca_pvt.PV_MODEL_QUEUE GROUP BY CONCAT(q_werbejahr,'-',q_werbewoche,'-',q_client_id)") %>% collect()

# your reproducible example here
```

**Comment by javierluraschi** [comment]
@andreysharapov don't remove `SPARK_HOME`, this is required to connect correctly.

For the `ia01ca_pvt.PV_MODEL_QUEUE` not found error, can you double check the table name? Have you tried escaping with as ``FROM `ia01ca_pvt.PV_MODEL_QUEUE` ``? Do you see the table when running `src_tbls(sc)`?

**Comment by andreysharapov** [comment]
The problem is that after the update PySpark and Spark on Scala work just fine and all there queries work. I tried to read the value of SPARK_HOME and it was correctly set (for scala).

**Comment by andreysharapov** [comment]
@javierluraschi 
To answer your question

> src_tbls(sc)
character(0)

**Comment by andreysharapov** [comment]
@javierluraschi 

Hi, do you have any suggestions here or you think it is related to our platform setup?

**Comment by andreysharapov** [comment]
@javierluraschi

We have investigated and debugged this issue:
The default SQL catalog implementation for Spark 2.3.0 is "in-memory" instead of "hive". The sparklyr library cannot properly cope with correctly setting/enabling hive-support programmatically.

We added the following cluster-wide setting (via Ambari) to /etc/spark2/conf/spark-defaults.conf:
spark.sql.catalogImplementation hive

This is a breaking change from the previous versions and should be made public.

**Comment by sdanielzafar** [comment]
@andreysharapov 

Strange, I'm on a similar setup- Ambari with HDP 3.0 and I set the `spark.sql.catalogImplementation` config to `hive` and I'm getting the same error on the most recent version of sparklyr:

`Error: org.apache.spark.sql.AnalysisException: Hive support is required to CREATE Hive TABLE (AS SELECT);;`

Was there anything else you did?

**Comment by kevinykuo** [comment]
@and @sdanielzafar closing to track at https://github.com/rstudio/sparklyr/issues/1496
