### ISSUE TITLE
Installing Spark fails because of version mismatches

### ISSUE THREAD

**Issue by kmace** [rstudio/sparklyr#1602]
Using `spark_install` requires spark versions listed in `spark_available_versions()` which are:

```
1  1.6.3
2  1.6.2
3  1.6.1
4  1.6.0
5  2.0.0
6  2.0.1
7  2.0.2
8  2.1.0
9  2.1.1
10 2.2.0
11 2.2.1
12 2.3.0
```
However, you can only install spark versions available on `https://www-us.apache.org/dist/spark/`. Which are:

```
[DIR] spark-2.1.3/            2018-06-29 21:32    -   
[DIR] spark-2.2.2/            2018-07-03 18:14    -   
[DIR] spark-2.3.1/            2018-06-08 20:33    -   
```

There is therefore no compatible versions one can use?

**Comment by javierluraschi** [comment]
@kmace you should be able to run any of the following commands to instsall whichever version you need, is this not working for you?

```
spark_install("1.6.3")
spark_install("1.6.2")
spark_install("1.6.1")
spark_install("2.0.0")
spark_install("2.0.1")
# ... etc
```

**Comment by javierluraschi** [comment]
I see what you mean... download URLs changed, pushing a fix.

**Comment by kmace** [comment]
Thanks!
