### ISSUE TITLE
queue in livy_config

### ISSUE THREAD

**Issue by ciasom** [rstudio/sparklyr#1624]
Two issues here.

1. The documentation for function livy_config has 2 items with the name "queue":
```r
#'   \item{\code{queue}}{The name of the YARN queue to which submitted}
#'   \item{\code{queue}}{The name of this session}
```

2. The "queue" parameter doesn't work.
I tried something like the following to specify the queue, the connection is always in my default queue.
```r
cnfg <- livy_config(queue = "dev") 
```
while I used "spark.yarn.queue" to set the queue name, it worked.
```r
spkconfig = spark_config()
spkconfig$spark.yarn.queue = "dev"
cnfg <- livy_config(config = spkconfig) 
```

sparklyr version 0.8.4.  
spark version 2.1.0

**Comment by yutannihilation** [comment]
For the first issue, I guess the documentation comes from here. The parameter of "the name of this session" should be `name`.

https://livy.incubator.apache.org/docs/latest/rest-api.html

**Comment by yutannihilation** [comment]
For the second issue, `queue` is not supported before the version v0.4.0 and newer of Livy. Do you use the newer Livy than this...?

https://github.com/apache/incubator-livy/commit/7212e3f3bbed07ab8ea372cd7a56ee1cd2b56693
