### ISSUE TITLE
Databricks connection is broken in master

### ISSUE THREAD

**Issue by mengxr** [rstudio/sparklyr#1650]
After https://github.com/rstudio/sparklyr/pull/1646, sparklyr master stopped working on Databricks. See https://github.com/rstudio/sparklyr/pull/1646/files#r213158586.

~~~R
> sc <- spark_connect(method = "databricks")

Error in value[[3L]](cond) : 
  Failed during initialize_connection:Failed during initialize_connection: Unable to retrieve a spark_connection from object of class NULL
~~~

cc: @falaki @javierluraschi @kevinykuo

**Comment by kevinykuo** [comment]
Thanks for the report! Will take a look.

**Comment by kevinykuo** [comment]
Have a pretty good idea what's going on here. I'm trying to get access to RStudio + Databricks so I can better test a patch (installing in the notebook takes 20min a pop). Will report back when I have a fix or run into issues.

**Comment by kevinykuo** [comment]
@mengxr @falaki should be fixed in `master` now, let me know if you run into any issues in your testing, thanks!
