### ISSUE TITLE
Spark connection not found when running a shiny rmarkdown document

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/sparklyr#166]
My RMarkdown or flexdashboard documents (that include shiny apps) stopped working with this error:

`Error: object 'sc' not found`

It seemed to be an rmarkdown, or flexdashboard package issue, or error in my document. But I was able to narrow it down to a change between `sparklyr` versions 0.3.2 and 0.3.3. Everything else the same, a small test document works fine in 0.3.2 and gives error in 0.3.3.

- Create a test document using:  File -> New -> Rmarkdown -> Shiny
- Add a spark connection and access of that to the top of document:

```
library(dplyr)
library(nycflights13)
library(ggplot2)
library(flexdashboard)
library(sparklyr)

sc <- spark_connect("local", version = "1.6.1")
copy_to(sc, nycflights13::flights, "flights")
```

**Comment by fereshtehRS** [comment]
This is kind of blocking the work on the cluster. 

I am trying to deploy Shiny applications and Rmd documents to a Connect Server on the cluster, but everything fails with this error (even Rmd documents without shiny runtime are failing in this case).

**Comment by kevinushey** [comment]
I believe this is resolved by @javierluraschi's recent commit: https://github.com/rstudio/sparklyr/commit/b218612f1498a8bd66a237d64570ff6994c2ad26
