### ISSUE TITLE
ml_fpgrowth() not working

### ISSUE THREAD

**Issue by tpollok** [rstudio/sparklyr#1664]
I'm trying to conduct market basket analysis using R on a Spark cluster, and instead of using the `arules` package in R (can you use this on Spark??) I wanted to use `ml_fpgrowth` instead when constructing a pipeline for production. However, the `ml_fpgrowth` function doesn't appear to work. Here's an example of the input

```r

sc <- spark_connect(master = "local", version = "2.2.0")

df <- data.frame(items = c("1 2 5", "1 2 3 5", "1 2"))
  df_tbl <- sdf_copy_to(sc, df, overwrite = TRUE) %>%
    mutate(items = split(items, " "))
  fp_model <- df_tbl %>%
     ml_fpgrowth(min_support = 0.5, min_confidence = 0.6)
```

And the output:

`Error in ml_fpgrowth(., min_support = 0.5, min_confidence = 0.6) : 
  unused arguments (min_support = 0.5, min_confidence = 0.6)`

When removing the specified parameters and simply running:

```r
fp_model <- df_tbl %>%
     ml_fpgrowth()
```

I get the error:

`Error in do.call(.f, args, envir = .env) : 'what' must be a function or character string`

Is this an issue with the `ml_fpgrowth()` function? Or is the example given incorrect?

And if I may ask, is it possible to use R packages such as `arules` that work with R data frames, `data.frame` when building a pipeline opposed to having to use Spark's ML Lib?

**Comment by harryprince** [comment]
`sparklyr::spark_apply` can execute `arules` package with native R data frames

**Comment by tpollok** [comment]
I figured it'd be possible to use `spark_apply`, which would allow me to use the `arules` package, but I'm unsure about how to coerce a Spark DataFrame to a particular R data.frame type and then to a `transactions` dataset...  `as(data.frame, "transactions")` is a little fussy.

@harryprince as this question posed to you isn't directly related to the issue with `ml_fpgrowth`, could I contact you elsewhere about this?

**Comment by kevinykuo** [comment]
@tpollok I can't repro this. What sparklyr and Spark versions are you using?

**Comment by tpollok** [comment]
@kevinykuo I've been using Spark 2.2.0, and I was recently using `install.packages("sparklyr")`, which I believe was an older version. After using `devtools::install_github("rstudio/sparklyr")` I'm now using `sparklyr_0.8.4.9008`. The code in the original comment now works fine, albeit I'm getting large Spark error messages whenever I try to call the association rules on another, much larger, dataset.

**Comment by kevinykuo** [comment]
Feel free to open another issue with the details for the error message!
