### ISSUE TITLE
Can't connect to Spark on Qubole since 0.9.1

### ISSUE THREAD

**Issue by The-Dub** [rstudio/sparklyr#1694]
Hi,

Since the new update was released on CRAN yesterday, we can't connect anymore to Spark, using the Qubole UI.

Using the example code on the sparklyr website fails with the following error:

> Error in force(code) : 
>   Failed during initialize_connection: Failed to detect version from SPARK_HOME or SPARK_HOME_VERSION. Try passing the spark version explicitly.

The code used was as follows:

```
library(sparklyr)

print(Sys.getenv("SPARK_HOME"))

conf <- spark_config()

conf$spark.executor.memory <- "3G"
conf$spark.executor.cores <- 2
conf$spark.executor.instances <- 3
conf$spark.dynamicAllocation.enabled <- "false"

sc <- spark_connect(master = "yarn-client", 
                    spark_home = "/usr/lib/spark/",
                    version = "2.3.1",
                    config = conf)

print(sc)

spark_disconnect(sc)
```

FYI, the result from `Sys.getenv("SPARK_HOME")` was `/usr/lib/spark`.

Any ideas why this doesn't work anymore? Any changes to make on the cluster?

Thank you for your help

Cheers,
Richard

PS: I found this in the logs as well, just a warning though. The doc should probably be changed
`App > Warning: Master yarn-client is deprecated since 2.0. Please use master "yarn" with specified deploy mode instead.`

**Comment by The-Dub** [comment]
UPDATE

While diving into the source code of the package, I found a workaround which is to specify the environment variable `SPARK_HOME_VERSION` such as `Sys.setenv(SPARK_HOME_VERSION = "2.3.1")`

I also looked into why sparklyr wasn't able to find the spark_version, even if it was specified.

I couldn't find out why out why the `version` parameter doesn't pass on to `sparklyr:::spark_version_from_home`, while it's expressly passed to the function, but I found an "improvement" (bug?) in the function.

On the version of spark installed on our cluster (2.3.1), the `spark-2.3.1-yarn-shuffle.jar` file is under `lib/shuffle`, and not under `yarn`. Maybe by making the function more general, it would find the version even when the structure of the folder changes.

For example, setting `recursive = TRUE` and searching more generally under `lib`or `spark_home`

```
useAssemblies = function() {
        **candidateVersions <- list(list(path = "lib", pattern = "spark-assembly-([0-9\\.]*)-hadoop.[0-9\\.]*\\.jar"), 
            list(path = "yarn", pattern = "spark-([0-9\\.]*)-preview-yarn-shuffle\\.jar"), 
            list(path = "yarn", pattern = "spark-([0-9\\.]*)-yarn-shuffle\\.jar"))
        candidateFiles <- lapply(candidateVersions, function(e) {
            c(e, list(files = list.files(file.path(spark_home, 
                e$path), pattern = e$pattern)))
        })**
        filteredCandidates <- Filter(function(f) length(f$files) > 
            0, candidateFiles)
        if (length(filteredCandidates) > 0) {
            valid <- filteredCandidates[[1]]
            e <- regexec(valid$pattern, valid$files[[1]])
            match <- regmatches(valid$files[[1]], e)
            if (length(match) > 0 && length(match[[1]]) > 1) {
                return(match[[1]][[2]])
            }
        }
    }
```

```
useAssemblies = function() {
        **candidateVersions <- list(list(path = "lib", pattern = "spark-assembly-([0-9\\.]*)-hadoop.[0-9\\.]*\\.jar"), 
            list(path = "lib", pattern = "spark-([0-9\\.]*)-preview-yarn-shuffle\\.jar"), 
            list(path = "lib", pattern = "spark-([0-9\\.]*)-yarn-shuffle\\.jar"))
        candidateFiles <- lapply(candidateVersions, function(e) {
            c(e, list(files = list.files(file.path(spark_home, 
                e$path), pattern = e$pattern, recursive = TRUE)))
        })**
        filteredCandidates <- Filter(function(f) length(f$files) > 
            0, candidateFiles)
        if (length(filteredCandidates) > 0) {
            valid <- filteredCandidates[[1]]
            e <- regexec(valid$pattern, valid$files[[1]])
            match <- regmatches(valid$files[[1]], e)
            if (length(match) > 0 && length(match[[1]]) > 1) {
                return(match[[1]][[2]])
            }
        }
    }
```

This works for me, but don't know if it would work for other version of spark...

Let me know if you want me to make some tests

Cheers,
Richard

**Comment by javierluraschi** [comment]
@The-Dub Could you validate [this fix](https://github.com/rstudio/sparklyr/pull/1696) work for you by installing:

```r
devtools::install_github("rstudio/sparklyr", ref = "bugfix/1694")
```

It' is likely that a couple fixes will be required to be push to CRAN in the next couple weeks, so I'll include this one once you verify this. Thanks.!

**Comment by The-Dub** [comment]
Thank you @javierluraschi! 
I'll do that tomorrow & let you know
