### ISSUE TITLE
Bug in ml_save / ml_load

### ISSUE THREAD

**Issue by slopp** [rstudio/sparklyr#170]
ml_load creates the modelName with the following:

```
modelName <- paste(r$model.parameters$model, "Model", sep = "")
```

However this is not the correct model name for any of the classifiers. For instance, the model type for a random forest is RandomForestClassifier  whereas the fitted model name is RandomForestClassificationModel. 

This leads to an error when you try to invoke_static on a type that doesn't exist, in this example: org.apache.spark.ml.classification.RandomForestClassifierModel

**Comment by kevinushey** [comment]
Thanks -- I guess we need a bit of indirection to correctly select the reader class based on the model class.
