### ISSUE TITLE
Can't copy_to local instance

### ISSUE THREAD

**Issue by nietzschetmh** [rstudio/sparklyr#1702]
Hello, trying to import data into local sparklyr instance.

Data size is 16.8 gb, memory size is 16gb, which is smaller than the data size.
Trying to copy the data into local disk not memory.

```
sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] sparklyr_0.9.1    dplyr_0.7.4       plyr_1.8.4       
[4] data.table_1.10.4 ffbase_0.12.3     ff_2.2-13        
[7] bit_1.1-12       

```

I tried to do the following

```
config <- spark_config()
spark_dir = "C:/spark"

config$`sparklyr.shell.driver-java-options` <-  paste0("-Djava.io.tmpdir=", spark_dir)
config$`sparklyr.shell.driver-memory` <- "4G"
config$`sparklyr.shell.executor-memory` <- "4G"
config$`spark.yarn.executor.memoryOverhead` <- "1g"

sc = spark_connect(master = "local", config = config)
copy_to(sc, my_data, 'mi')

```
I tried to increase ```sparklyr.shell.driver-memory``` to 8G but still don't work.

Error message:

```
Error: cannot allocate vector of size 25.0 Mb
In addition: Warning messages:
1: In `[.ff`(p, i2) :
  Reached total allocation of 16307Mb: see help(memory.size)
2: In `[.ff`(p, i2) :
  Reached total allocation of 16307Mb: see help(memory.size)
3: In `[.ff`(p, i2) :
  Reached total allocation of 16307Mb: see help(memory.size)
4: In `[.ff`(p, i2) :
  Reached total allocation of 16307Mb: see help(memory.size)
5: In `[.ff`(p, i2) :
  Reached total allocation of 16307Mb: see help(memory.size)
6: In `[.ff`(p, i2) :
  Reached total allocation of 16307Mb: see help(memory.size)
```

I understand this is caused by not enough memory but i tried to copy the data to local disk instead of memory.

**Comment by edgararuiz** [comment]
Hi, I think that you would want to read the data from file directly into Spark using something like `spark_read_csv()`, with the argument `memory` set to `FALSE`.  We have an article about that in our spark.rstudio.com site: http://spark.rstudio.com/guides/caching/#the-memory-argument

**Comment by nietzschetmh** [comment]
@edgararuiz , thanks a lot, it works very well if i use 

```
spark_read_csv()
```
A quick question, ``` memory = FALSE``` will load data into disk, how could i find its location? It's not in the folder i set in config
``` 
spark_dir = "C:/spark"

config$`sparklyr.shell.driver-java-options` <-  paste0("-Djava.io.tmpdir=", spark_dir)
```
If i close my spark connection and later reconnect, do i need to run ```spark_read_csv`` again to load data? Or it will be there ready for use?


Just wondering if we could copy something already in memory to disk using ```copy_to```. Right now, i'm using package ff/ffbase in R to handle very large dataset. Basically, my understanding is that it only stores "pointers" in memory and put actual data on disk drive. So small amount of memory is occupied compared with the actual dataset size.

If i want to use ``` spark_read_csv()```,  i have to first load the ff data, and then write them to csv format. And then use ```spark_read_csv``` . This is kind of very inconvenient and takes a long time. 

Is it possible to add a feature for ```copy_to``` that we could choose cache the data or not? Thanks.

**Comment by edgararuiz** [comment]
Right, so the data is already on disk, Spark does not load or copy it anywhere else.  Spark just "maps" the files and saves that meta data on memory, so nothing is really imported.  That's what's so cool about it.  Because now, I can query files as if they were SQL, and also have the option to only load the needed columns and rows into memory if needed.  Having said that, a `memory = FALSE` `copy_to()` would not really make sense, because it would mean for Spark to "map" something that's already in memory.

**Comment by nietzschetmh** [comment]
Thanks @edgararuiz . It's very clear.
