### ISSUE TITLE
Errors trying to install sparklyr.

### ISSUE THREAD

**Issue by ScrapCodes** [rstudio/sparklyr#1716]
On trying to install sparklyr, I am getting the following error.
version of RStudio: Version 1.2.1047
ubuntu 14.04.1
R version 3.4.4 

> install.packages("sparklyr")
Installing package into ‘/home/prashant/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/sparklyr_0.9.1.tar.gz'
Content type 'application/x-gzip' length 3804005 bytes (3.6 MB)
==================================================
downloaded 3.6 MB

* installing *source* package ‘sparklyr’ ...
** package ‘sparklyr’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
Error : object ‘sendToConsole’ is not exported by 'namespace:rstudioapi'
ERROR: lazy loading failed for package ‘sparklyr’
* removing ‘/home/prashant/R/x86_64-pc-linux-gnu-library/3.4/sparklyr’

The downloaded source packages are in
	‘/tmp/RtmphHDFZ4/downloaded_packages’
Warning message:
In install.packages("sparklyr") :
  installation of package ‘sparklyr’ had non-zero exit status
>

**Comment by javierluraschi** [comment]
@ScrapCodes thanks! `sparklyr` is not requesting the correct version of `rstudioapi`, will fix this shortly in CRAN, but int the meantime, upgrade `rstudioapi` as follows:

```
install.packages("rstudioapi")
```
