### ISSUE TITLE
SQL translation turns aggregation into window function on SPARK

### ISSUE THREAD

**Issue by ossianmogensen** [rstudio/sparklyr#1738]
I'm using sparklyr on Databricks (though the issue is not databricks specific) and I see an issue in the SQL translation for aggregation functions. 

When using a simple aggregation function in a mutate clause, this is translated as a window function in SparkSQL. In a traditional database this is not a big deal, but on SPARK this causes all data to be pulled to a single node which causes poor performance/crashes. 

I'm on Databricks runtime 4.3 (spark version 2.3.1). This appears to be an issue in sparklyr's SQL translation that causes issues with SparkSQL.

I have previously loaded the "diamonds" dataset into a table; any example dataset would work.

```r
spark_version <- "2.3.1"
sc <- spark_connect(method = "databricks")

tbl(sc, 'diamonds') %>%
  mutate(average_carat = mean(carat)) %>%
  show_query()
```

The output is:
SELECT `carat`, avg(`carat`) OVER () AS `average_carat`
FROM `diamonds`

The culprit is the OVER() which turns this into a window function with the whole dataframe as the window. Spark knows how to implement avg('carat') efficiently in a distributed manner, but avg('carat') OVER() pulls all the data onto a single worker node.

**Comment by harryprince** [comment]
related to https://github.com/rstudio/sparklyr/issues/1638

**Comment by kevinykuo** [comment]
@ossianmogensen we'll get the fix upstream looked at ASAP. Do you recall what the performance hit was for your case (and how big the dataset is?)

**Comment by ossianmogensen** [comment]
My dataset is around 57 million rows. In my case, the code wouldn't even
run on my cluster - I believe the worker ran out of RAM. When I tested it
on a smaller dataset it worked, but the operation became single-threaded
plus the overhead of sending all the data to a single worker node.

**Comment by hadley** [comment]
What SQL do you expect here? Any aggregation function in a `mutate()` must be translated to a window function. Did you mean to use `summarise()` instead?

**Comment by mtoto** [comment]
It is not possible to add an aggregate column to a Spark DataFrame without window functions,  and so the current behavior of sparklyr is correct. Consider what happens if we attempt this in plain Spark SQL:

```
diamonds_tbl <- copy_to(sc, diamonds)

diamonds_tbl %>%
  mutate(average_carat = mean(carat)) %>%
  show_query()

sqlfunction <- function(sc, block) {
  spark_session(sc) %>% invoke("sql", block)
}
sqlfunction(sc, "SELECT carat, avg(carat) AS average_carat FROM diamonds")
```
The relevant bit from the error message is:

> Error: org.apache.spark.sql.AnalysisException: grouping expressions sequence is empty, and 'diamonds.`carat`' is not an aggregate function. Wrap '(avg(diamonds.`carat`) AS `average_carat`)' in windowing function(s) or wrap 'diamonds.`carat`' in first() (or first_value) if you don't care which value you get.

An alternative to window functions could be to calculate the aggregate value in a separate query and then append that value as a new column to the original DataFrame.

**Comment by ossianmogensen** [comment]
You are correct. I must have made some mistake when I was testing this before; I can not get 
"
SELECT carat, avg(carat) AS average_carat
FROM diamonds
"
to run. I think the issue can be closed.

**Comment by kevinykuo** [comment]
Thanks y'all!
