### ISSUE TITLE
Get value from spark environment

### ISSUE THREAD

**Issue by RudyiVT** [rstudio/sparklyr#176]
Using sdf_predict I got following result. How I can select values?
Thanks!
<jobj[37792]>
  class org.apache.spark.ml.linalg.DenseVector
  [0.9789499814426139,0.021050018557386158]

**Comment by kevinushey** [comment]
Can you provide more information? What kind of model fit did you call `sdf_predict` on? (What code are you running?)

Given that you have a Spark DenseVector returned, you'll likely need to explicitly collect it, e.g.

    invoke(dv, "toArray")

or something to that effect would effectively return it to R.

**Comment by RudyiVT** [comment]
```
> model_test = test %>%
>   ml_random_forest(
>     response = "label",
>     features = c("list_cat_sim","price"))
> 
> test = sdf_predict(model_test, test, type = "prob")
```
After running this code I got the following result:
![2016-08-18 14 42 11](https://cloud.githubusercontent.com/assets/9803147/17772534/f9f87008-6551-11e6-8e56-cf6991f80bc2.png)

**How to transform probability and rawPrediction variables to numeric values?**

**Comment by kevinushey** [comment]
I see -- the issue here is, I guess, running a random forest regression with a categorical response; the return value here is a 'vector of vectors' and so does not serialize back to R as cleanly.

@seanlopp have you tried working with model output like this yet?

**Comment by slopp** [comment]
The following worked for me (we hope to export the `sdf_read_column` function:

```r
r <- sparklyr:::sdf_read_column(res, "probability")
sapply(r, function(l){invoke(l, "toArray")})
```

where `res

**Comment by kevinushey** [comment]
We now have `sdf_read_column` as an available function, so we should be good to go here now.

**Comment by joscani** [comment]
I have the same problem but in my case the response variable is numerical. My response variable is "response" and the features are numerical too.  
`head(pred1)
Source:   query [?? x 6]
Database: spark connection master=local[4] app=sparklyr local=TRUE

  respuesta  edad nhijos    rawPrediction      probability prediction
      <dbl> <dbl>  <dbl>           <list>           <list>      <dbl>
1         0    21      1 <S3: spark_jobj> <S3: spark_jobj>          0
2         0    21      1 <S3: spark_jobj> <S3: spark_jobj>          0
3         0    21      1 <S3: spark_jobj> <S3: spark_jobj>          0
4         0    21      1 <S3: spark_jobj> <S3: spark_jobj>          0
5         0    21      1 <S3: spark_jobj> <S3: spark_jobj>          0
6         0    21      1 <S3: spark_jobj> <S3: spark_jobj>          0`

**Comment by kevinushey** [comment]
Should we be sending these back to R as a list-of-lists?

**Comment by yarrick19** [comment]
@kevinushey I think it would he helpful to have these structured as a list of lists.  Even more useful would be to have `sdf_predict` just return the actual probability value.  Is that possible?

**Comment by yarrick19** [comment]
@kevinushey Is it possible to have `sdf_predict` return the actual probability value?

**Comment by kevinushey** [comment]
I'll try to take a look, but I'm not sure 'actual probability value' makes sense here -- for classification with multiple groups, don't we expect to obtain one probability value per group?

**Comment by yarrick19** [comment]
@kevinushey @slopp 
Kevin - good point.  The way many libraries in R handle this is by returning a matrix with the probabilities (`randomForest` package is a good example of this).  What I'm asking is if its possible for `sdf_predict` to return a usable array of the probabilities in the spark df as opposed to the densevector format which you then have to read the data to `R` and recursively loop through a list and parse out the probability values.  

Another disadvantage with the dense vector approach is that when you parse the probability values in R, you can't tell which class the probabilities are associated with.  For example, this is the predicted probabilities from a random forest classification model run on the iris data set with Species as the dependent variable.  
![image](https://cloud.githubusercontent.com/assets/9707200/20044424/bdd63ee4-a44d-11e6-8734-0716854b2adb.png)
It is unclear which value is associated with setosa, versicolor, and virginica.

**Comment by yarrick19** [comment]
Just following up to see if my ask in the post above is possible.  

If not, is there a way to parse the dense vector without having to first move the data to `R`?  It seems like the `apply` and `toArray` methods should be able to parse the probability values but I'm unsure how to apply these methods directly to the spark df column...

**Comment by kevinushey** [comment]
Yes, this should be possible -- sorry; we'll try to take a look at this soon!

**Comment by yarrick19** [comment]
@kevinushey 
That's great - super excited about this!  I think having easy access to the probability values will be very useful to anyone creating classification models.

**Comment by yarrick19** [comment]
Hi @kevinushey 

Curious where this request is at priority wise.  

Have `sdf_predict` return a usable array (or seperate columns?) of the probabilities in the spark df as opposed to the densevector format which you then have to read the data to R and recursively loop through a list and parse out the probability values

I think this is going to be extremely useful to have.  Thanks.

**Comment by kevinushey** [comment]
@yarrick19 I'm taking a look today -- this may prove to be trickier than I first anticipated but hopefully defining some transformation when pushing `DenseVector`s over the wire will be sufficient.

**Comment by kevinushey** [comment]
@yarrick19 this has now landed on master -- please try downloading the latest version of `sparklyr` and let us know if you encounter any issues.

```
devtools::install_github('rstudio/sparklyr')
```

**Comment by yarrick19** [comment]
@kevinushey Thanks for your work on this!  

The list format makes it pretty strait forward and natural (for an R user) to parse the probability values in R.

Is there any equivalent way of parsing the list in the spark DF without having to use `collect()` to pull the data into R?  I tried a few ways using `mutate` but wasn't successful.  I also see in the spark documentation something called `VectorSlicer` which seems like it would do the trick but I'm unsure if this is available via `sparklyr`.  

```
library(sparklyr)
library(dplyr)


sc <- spark_connect(master = "local", version = "2.0.1")

iris_tbl <- copy_to(dest = sc, name = "test", df = iris, overwrite = TRUE)

new_iris_tbl <- iris_tbl %>%
    mutate(target = as.character(ifelse(Species == "setosa", 1, 0)))

frmla <- formula(target ~ Sepal_Length + Sepal_Width + Petal_Length + Petal_Width)

logit <- ml_logistic_regression(new_iris_tbl, frmla)

pred_tbl <- sdf_predict(logit, newdata = new_iris_tbl) %>%
  sdf_register("pred")


# Get probability value in R

r_prob <- pred_tbl %>%
  select(probability, prediction) %>%
  collect()

r_prob$prob <- sapply(r_prob$probability, function(x){x[2]})



# Get probability value in Spark DF (Is this possible?!)

spark_pred <- pred_tbl %>%
  mutate(prob = ?????)
```

**Comment by kevinushey** [comment]
Unfortunately `VectorSlicer` does not quite cut it here as it still returns an array, not a single element. There's still likely something we can do here; I'll take a look.

**Comment by yarrick19** [comment]
@kevinushey 
Hi Kevin, just wanted to circle back on this one and see if you've been able to come up with a solution for this.

**Comment by Maiae** [comment]
I'm keen to see if there is a solution for this. I am dealing with as 17M records dataset and it is impractical to collect data into R memory. A solution for this would make my day.
Cheers

**Comment by Maiae** [comment]
Adding some more information to this.
I am fitting a decision tree to this data and trying to get the probabilities as a numeric value rather than a list vector.

```r
library(sparklyr)
library(dplyr)

sc <- spark_connect(master = "local", version = "2.0.0")

iris_tbl <- copy_to(dest = sc, name = "test", df = iris, overwrite = TRUE)

new_iris_tbl <- iris_tbl %>%
  mutate(target = as.character(ifelse(Species == "setosa", 1, 0)))

dt.model <- new_iris_tbl %>% 
  ml_decision_tree(response = "target",
                   features = c(
                     "Sepal_Length",
                     "Sepal_Width",
                     "Petal_Length",
                     "Petal_Width"),
                    type = "classification")
  

pred_tbl <- sdf_predict(dt.model, newdata = new_iris_tbl) %>%
  sdf_register("pred")

pred_tbl_subset <- pred_tbl %>% 
  filter(prediction == 1) %>% 
  mutate(prob = matrix(unlist(probability), ncol=2, byrow=TRUE)[, 2]) %>%
  sdf_register("pred_subset")
```

The last dplyr query is followed by:
```r
Error in unlist(probability) : object 'probability' not found
```
I get the same result if `sdf_mutate()` is used instead of `mutate()` which is very strange.
However, if I first collect the data into R memory, everything runs as it suppose to:
```r
pred_tbl <- sdf_predict(dt.model, newdata = new_iris_tbl) %>%
  collect()

pred_tbl %>% 
  filter(prediction == 1) %>% 
  mutate(prob = matrix(unlist(probability), ncol=2, byrow=TRUE)[, 2]) %>% 
  select(prediction, prob)

# A tibble: 50 × 2
   prediction  prob
        <dbl> <dbl>
1           1     1
2           1     1
3           1     1
4           1     1
5           1     1
6           1     1
7           1     1
8           1     1
9           1     1
10          1     1
# ... with 40 more rows

```


My `sparklyr` version is 0.5.3 and my `dplyr` version is 0.5.0

**Comment by dwy904** [comment]
Has the problem been solved ? I wanna see all class probabilities from the random forest model.

**Comment by kevinushey** [comment]
This can be handled through the use of `sdf_separate_column()` in the development version of `sparklyr`. Following from @Maiae's example:

```
library(sparklyr)
library(dplyr)

sc <- spark_connect(master = "local", version = "2.0.0")

iris_tbl <-
  copy_to(
    dest = sc,
    name = "test",
    df = iris,
    overwrite = TRUE
  )

new_iris_tbl <- iris_tbl %>%
  mutate(target = as.character(ifelse(Species == "setosa", 1, 0)))

dt.model <- new_iris_tbl %>%
  ml_decision_tree(
    response = "target",
    features = c("Sepal_Length",
                 "Sepal_Width",
                 "Petal_Length",
                 "Petal_Width"),
    type = "classification"
  )


pred_tbl <- sdf_predict(dt.model, newdata = new_iris_tbl) %>%
  sdf_register("pred")

separated <- sdf_separate_column(pred_tbl, "probability", c("p0", "p1"))
select(separated, p0, p1)
```

This will produce:

```
> select(separated, p0, p1)
# Source:   lazy query [?? x 2]
# Database: spark_connection
      p0    p1
   <dbl> <dbl>
 1     0     1
 2     0     1
 3     0     1
 4     0     1
 5     0     1
 6     0     1
 7     0     1
 8     0     1
 9     0     1
10     0     1
# ... with 140 more rows
```

**Comment by Maiae** [comment]
Thanks @kevinushey. Great stuff!

Adding a snippet that will create a neat spark df when running predictions with `sdf_predict`:

```r
pred_tbl <- sdf_predict(dt.model, newdata = new_iris_tbl) %>%
              sdf_separate_column(column = "probability", into = c("prob_0", "prob_1")) %>%
              sdf_separate_column(column = "rawPrediction", into = c("pred_0", "pred_1")) %>% 
              select(-rawPrediction, -probability) %>% 
              sdf_register("pred")
```

**Comment by dwy904** [comment]
Why I did not find this function in my sparklyr package ? Error: object
'sdf_separate_column' not found

**Comment by kevinushey** [comment]
@dwy904 you likely need to install the development version of `sparklyr`:

```
devtools::install_github("rstudio/sparklyr")
```

Then restart your R session.

**Comment by dwy904** [comment]
Thank you so much. I have the function after install the development
version. However, another error shows up when I connect to spark cluster:

> sc <- spark_connect(master = "local")

Error in shell_connection(master = master, spark_home = spark_home,
app_name = app_name,  :
  Failed to connect to Spark (SPARK_HOME is not set).

I am wondering if I need to change anything ?

Best,
Michael

**Comment by kevinykuo** [comment]
@dwy904 could you try explicitly passing `version` to `spark_connect()`?

**Comment by dwy904** [comment]
I think I have successfully solved this problem by change the code to:

sc <- spark_connect(master = "local", config = config,
                                 spark_home =
'~/Library/Caches/spark/spark-1.6.2-bin-hadoop2.6')

Thank you so much. I got one more question, do you have any code example
about how to use multilayer perceptron model ? I tried a few times but it
didn't work out.

Best,
Michael
