### ISSUE TITLE
Consider renameing max.iter parameter to iter.max in ml_kmeans

### ISSUE THREAD

**Issue by MarcinKosinski** [rstudio/sparklyr#177]
You are using the name `max.iter` for Spark's `setMaxIterations` in `ml_kmeans` https://github.com/rstudio/sparklyr/blob/master/R/ml_kmeans.R#L19, what is confusing for regular R user who's used to work with `iter.max` from `stats::kmeans`

**Comment by kevinushey** [comment]
I'd be happy with this change as well.

**Comment by MarcinKosinski** [comment]
So, to be consistent and to use one roxygen-template in as many functions as possible

`@template roxlate-ml-max-iter`, thus `max.iter` parameter, is used in

- ml_survival_regression
- ml_multilayer_perceptron
- ml_logistic_regression
- ml_linear_regression
- ml_generalized_linear_regression
- ml_kmeans
- ml_als_factorization

funcitons. If we are about to rename `max.iter` to `iter.max` in `ml_kmeans` than I think we should also rename them in the rest of above functions. What do you think about that?

**Comment by kevinushey** [comment]
This should be resolved now -- `iter.max` is preferred (and is the documented argument), but `max.iter` is accepted for backwards compatibility.
