### ISSUE TITLE
Value matching under sparklyr

### ISSUE THREAD

**Issue by klausmiller** [rstudio/sparklyr#1774]
I tried value matching under sparklyr using:

    spark_parquet %>% filter(customer_id %in% spark_unique_customer_ids)

However, I received the following error:

    Error in UseMethod("escape") : no applicable method for 'escape' applied to an object of class "c('tbl_spark', 'tbl_sql', 'tbl_lazy', 'tbl')"

Any suggestions how to tackle this?

**Comment by benmwhite** [comment]
I'm not getting this error with the following (either locally or on a YARN-managed cluster, sparklyr dev build):

```
copy_to(sc, iris, "iris_tbl")
vec <- c("versicolor", "virginica")
tbl(sc, "iris_tbl") %>% filter(Species %in% vec)
# output is correct query
``

You might want to double check your `spark_unique_customer_ids`. Also, what sparklyr version are you using?

**Comment by klausmiller** [comment]
I am using sparklyr_0.9.2, however the issue was indeed my spark_unique_customer_ids. Thanks for the help and keep up the good work!
