### ISSUE TITLE
Deploy R kernel into Jupyter

### ISSUE THREAD

**Issue by mdivk** [rstudio/sparklyr#1780]
We need to build a R kernel in Jupyter on our Cloudera Cluster, here is my questions:

1. The cluster does not have R, a preferred way is to use Anaconda to install R;
2. After R is installed, create IRkernel and register it to Jupyter;

The problem is that will install R into the Anaconda pacels location on that particular host only, meaning all other nodes do not have that.

We will need the R be able to generate a spark context and work with the data on the HDFS that resides on the cluster instead of single host;

We don't want to install any extra tools into Anaconda's parcel location;

What option do we have here?

Thank you very much.

**Comment by harryprince** [comment]
it's pretty easy for `sparklyr::spark_apply` with default `packages = TRUE`, which will upload your local R packages into HDFS and then distribute to each workers automatically. Do not need to pre-install any R packages in worker.

**Comment by mdivk** [comment]
Thank you very much.
