### ISSUE TITLE
No tidy() support for pipeline output

### ISSUE THREAD

**Issue by sz-cgt** [rstudio/sparklyr#1789]
The following examples are conceptually equivalent, yet only the first works.  This makes building exploratory models that rely on `ft_*()` operations difficult

``` r
library(sparklyr)
sc <- 
  spark_connect(master = "local")
mt <- 
  sdf_copy_to(sc, mtcars)
mt %>% 
  ml_linear_regression(am ~ cyl + mpg) %>% 
  tidy()
#> # A tibble: 3 x 5
#>   term        estimate std.error statistic p.value
#>   <chr>          <dbl>     <dbl>     <dbl>   <dbl>
#> 1 (Intercept)  -0.460     0.929     -0.495  0.624 
#> 2 cyl          -0.0117    0.0793    -0.147  0.884 
#> 3 mpg           0.0467    0.0235     1.99   0.0564
mt %>% 
  ft_r_formula(am ~ cyl + mpg) %>% 
  ml_linear_regression() %>% 
  tidy()
#> Error: No tidy method for objects of class ml_linear_regression_model
```

<sup>Created on 2018-11-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Given that 
`mt %>% ft_r_formula(am ~ cyl + mpg) %>% ml_linear_regression(fit_intercept = FALSE) %>% coef()`
and
`mt %>% ft_r_formula(am ~ cyl + mpg) %>% ml_linear_regression(fit_intercept = FALSE) %>% summary()`
work correctly, it is surprising that I cannot use tidy() against the pipeline output.

> devtools::session_info()
- Session info -----------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_Australia.1252      
 ctype    English_Australia.1252      
 tz       America/Chicago             
 date     2018-11-28                  

- Packages ---------------------------------------------------------------------------
 package     * version    date       lib source                          
 assertthat    0.2.0      2017-04-11 [1] CRAN (R 3.5.0)                  
 backports     1.1.2      2017-12-13 [1] CRAN (R 3.5.0)                  
 base64enc     0.1-3      2015-07-28 [1] CRAN (R 3.5.0)                  
 bindr         0.1.1      2018-03-13 [1] CRAN (R 3.5.0)                  
 bindrcpp      0.2.2      2018-03-29 [1] CRAN (R 3.5.0)                  
 broom         0.5.0      2018-07-17 [1] CRAN (R 3.5.1)                  
 callr         3.0.0      2018-08-24 [1] CRAN (R 3.5.1)                  
 cli           1.0.1      2018-09-25 [1] CRAN (R 3.5.1)                  
 config        0.3        2018-03-27 [1] CRAN (R 3.5.0)                  
 crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.0)                  
 DBI           1.0.0      2018-05-02 [1] CRAN (R 3.5.0)                  
 dbplyr        1.2.2      2018-07-25 [1] CRAN (R 3.5.1)                  
 debugme       1.1.0      2017-10-22 [1] CRAN (R 3.5.0)                  
 desc          1.2.0      2018-05-01 [1] CRAN (R 3.5.0)                  
 devtools      2.0.1      2018-10-26 [1] CRAN (R 3.5.1)                  
 digest        0.6.18     2018-10-10 [1] CRAN (R 3.5.1)                  
 dplyr         0.7.8      2018-11-10 [1] CRAN (R 3.5.1)                  
 forge         0.1.0      2018-08-31 [1] CRAN (R 3.5.1)                  
 fs            1.2.6      2018-08-23 [1] CRAN (R 3.5.1)                  
 glue          1.3.0      2018-07-17 [1] CRAN (R 3.5.1)                  
 htmltools     0.3.6      2017-04-28 [1] CRAN (R 3.5.0)                  
 htmlwidgets   1.3        2018-09-30 [1] CRAN (R 3.5.1)                  
 httpuv        1.4.5      2018-07-19 [1] CRAN (R 3.5.1)                  
 httr          1.3.1      2017-08-20 [1] CRAN (R 3.5.0)                  
 jsonlite      1.5        2017-06-01 [1] CRAN (R 3.5.0)                  
 later         0.7.5      2018-09-18 [1] CRAN (R 3.5.1)                  
 lattice       0.20-35    2017-03-25 [2] CRAN (R 3.5.1)                  
 lazyeval      0.2.1.9000 2018-09-17 [1] Github (hadley/lazyeval@93c455c)
 magrittr      1.5        2014-11-22 [1] CRAN (R 3.5.0)                  
 memoise       1.1.0      2017-04-21 [1] CRAN (R 3.5.0)                  
 mime          0.6        2018-10-05 [1] CRAN (R 3.5.1)                  
 nlme          3.1-137    2018-04-07 [2] CRAN (R 3.5.1)                  
 openssl       1.1        2018-11-15 [1] CRAN (R 3.5.1)                  
 packrat       0.5.0      2018-11-14 [1] CRAN (R 3.5.1)                  
 pillar        1.3.0      2018-07-14 [1] CRAN (R 3.5.1)                  
 pkgbuild      1.0.2      2018-10-16 [1] CRAN (R 3.5.1)                  
 pkgconfig     2.0.2      2018-08-16 [1] CRAN (R 3.5.1)                  
 pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.5.1)                  
 prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.5.0)                  
 processx      3.2.0      2018-08-16 [1] CRAN (R 3.5.1)                  
 promises      1.0.1      2018-04-13 [1] CRAN (R 3.5.0)                  
 ps            1.2.1      2018-11-06 [1] CRAN (R 3.5.1)                  
 purrr         0.2.5      2018-05-29 [1] CRAN (R 3.5.0)                  
 r2d3          0.2.2      2018-05-30 [1] CRAN (R 3.5.1)                  
 R6            2.3.0      2018-10-04 [1] CRAN (R 3.5.1)                  
 Rcpp          1.0.0      2018-11-07 [1] CRAN (R 3.5.1)                  
 remotes       2.0.2      2018-10-30 [1] CRAN (R 3.5.1)                  
 rlang         0.3.0.1    2018-10-25 [1] CRAN (R 3.5.1)                  
 rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.0)                  
 rstudioapi    0.8        2018-10-02 [1] CRAN (R 3.5.1)                  
 sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.5.1)                  
 shiny         1.2.0      2018-11-02 [1] CRAN (R 3.5.1)                  
 sparklyr    * 0.9.2      2018-10-17 [1] CRAN (R 3.5.1)                  
 testthat      2.0.1      2018-10-13 [1] CRAN (R 3.5.1)                  
 tibble        1.4.2      2018-01-22 [1] CRAN (R 3.5.0)                  
 tidyr         0.8.2      2018-10-28 [1] CRAN (R 3.5.1)                  
 tidyselect    0.2.5      2018-10-11 [1] CRAN (R 3.5.1)                  
 usethis       1.4.0      2018-08-14 [1] CRAN (R 3.5.1)                  
 withr         2.1.2      2018-03-15 [1] CRAN (R 3.5.0)                  
 xtable        1.8-3      2018-08-29 [1] CRAN (R 3.5.1)                  
 yaml          2.2.0      2018-07-25 [1] CRAN (R 3.5.1)                  

[1] C:/Users/szander/R/win-library/3.5
[2] C:/Program Files/R/3.5.1/library

**Comment by sz-cgt** [comment]
Experimenting, I note that `mt %>% ml_linear_regression(mpg ~ .) %>% tidy()` works as expected.

Given that 
`mt %>%
  ft_r_formula(am ~ cyl + mpg) %>%
  ml_linear_regression(fit_intercept = FALSE) %>%
  coef()`
and
`mt %>%
  ft_r_formula(am ~ cyl + mpg) %>%
  ml_linear_regression(fit_intercept = FALSE) %>%
  summary()`
also work correctly, it is surprising that I cannot use tidy() against the pipeline output

**Comment by kevinykuo** [comment]
When you pass a formula to an `ml_` method, you invoke the formula API which will return an `ml_model` object. This is basically a wrapper around a pipeline model object with some metadata (such as variable names.) The broom functions require these metadata so they only work for `ml_model` objects.

The output of

```
mt %>% 
  ft_r_formula(am ~ cyl + mpg) %>% 
  ml_linear_regression()
```

is just a pointer to the `LinearRegressionModel` object. This object contains no information on variable names and just has a vector of coefficients (https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.ml.regression.LinearRegressionModel), so it's not possible to implement broom methods for it.

**Comment by sz-cgt** [comment]
I'd buy that argument if `mt %>% ft_r_formula(am ~ cyl + mpg) %>% ml_linear_regression(fit_intercept = FALSE) %>% coef()` didn't work.

But it does.

**Comment by kevinykuo** [comment]
@sz-cgt it does, but it doesn't produce names of the covariates, so we can't put it into a broom-compliant format. There's no straightforward way to capture that information since you can put arbitrary estimators in a pipeline, so `ml_linear_regression()` in this case doesn't know what came before it. It's only using the `features` and `label` columns from the output of `mt %>% ft_r_formula(am ~ cyl + mpg)`.
