### ISSUE TITLE
Support for yarn-cluster mode

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#181]
Currently, sparklyr submits a custom `sparklyr.jar` file through spark-submit with a given ports file. Then the jar initializes a socket and saves the socket details in the ports file. This file is used by sparklyr to rea this socket definition and connect to the running application within the jar in the driver machine. This works as expected for `yarn-client`; however, for `yarn-cluster` the file is located on a different machine that the r process running `sparklyr` won't be able to locate since it's not local anymore.

Marking this as feature request for discussion and planning work for next release.

**Comment by javierluraschi** [comment]
**UPDATE:** A PR (https://github.com/rstudio/sparklyr/pull/238) has been committed which removed the use of a ports file mentioned above. However, there are still a few settings that need to be exposed in order to connect to the remove driver. If someone is interesting in helping out here, feel free to contact me at javier at rstudio.com (not much work left). Otherwise, I'll take a look at this as time permits.

**Comment by statmatt** [comment]
+1 on this ASAP.

**Comment by samurainate** [comment]
Works if the primary RM is online.  If ha is enabled and the primary RM is not online, it doesn't try the list of ha RMs in round robin.

**Comment by javierluraschi** [comment]
@samurainate give it another shot, #997 got enough fixes to enable connection in HA mode. Issue is still open due to HIVE auth issue, but looks like that might not be related to `sparklyr`.
