### ISSUE TITLE
Error during spark_connect

### ISSUE THREAD

**Issue by dkincaid** [rstudio/sparklyr#1810]
When trying to connect to Spark using `spark_connect` with the latest development version of sparklyr we're getting the following error:

```
> sc <- spark_connect(master = "yarn", config = config)
Error: `nm` must be `NULL` or a character vector the same length as `x`
Call `rlang::last_error()` to see a backtrace
> rlang::last_error()
<error>
message: `nm` must be `NULL` or a character vector the same length as `x`
class:   `rlang_error`
backtrace:
 ─sparklyr::spark_connect(master = "yarn", config = config)
 ─sparklyr:::register_mapping_tables()
 ─sparklyr:::read_extension_mappings(file_name = "param_mapping.json")
 ─purrr::map_chr(...)
 ─purrr::keep(., nzchar)
 ─purrr::map(., jsonlite::fromJSON)
 ─purrr::set_names(., pkgs)
 ─rlang:::set_names_impl(x, x, nm, ...)
```
Our connection code looks like this:
```R
config <- spark_config()
config$sparklyr.log.console <- FALSE
sc <- spark_connect(master = "yarn", config = config)
```

reverting to the 0.9.2 version on CRAN fixes the issue.

**Comment by dkincaid** [comment]
The only sparklyr extension is sparkavro (https://cran.r-project.org/web/packages/sparkavro/index.html)

Other packages being explicitly loaded include:
futile.logger
glue
aws.ec2metadata
aws.s3

**Comment by kevinykuo** [comment]
Thanks, will investigate.

**Comment by mattpollock** [comment]
Possibly related (possibly not): I hit a snag today where spark-avro 2.11 v4.0.0 (via the `sparkavro` package) caused a failed spark connection. Reverting to the 3.2.0 version I was able to establish a connection. I need to maintain dependencies in my local maven repo, but the log said that all dependencies were resoled, but the connection timed out waiting for something anyway.

**Comment by kevinykuo** [comment]
Should be fixed on master, let me know if it's still giving you trouble.
