### ISSUE TITLE
Error in if (n > 0) c(NA_integer_, -n) else integer()

### ISSUE THREAD

**Issue by hanfernandes** [rstudio/sparklyr#1829]
I'm connected to the cluster.

`sc <- spark_connect(master = "yarn-client", version = "2.3.1")`

and i create one data.frame and copy to tbl_spark:

`df<- copy_to(sc, data.frame(x=c(1, NA, 2), y=c(NA, 2, NA), z=42))`

the following error arises, when I try to view or do any operation:

`df`
> Error in if (n > 0) c(NA_integer_, -n) else integer() : 
  missing value where TRUE/FALSE needed

**Comment by javierluraschi** [comment]
Fix on its way, CRAN will be also patched in the next couple days.

**Comment by javierluraschi** [comment]
@hanfernandes fix available by reinstalling with:

`devtools::install_github(“rstudio/sparklyr”)`

**Comment by hanfernandes** [comment]
it's works! @javierluraschi 

thanks so much!

I really admire your work, keep to help thousands of people!
