### ISSUE TITLE
mutate does not work in spark 2.0.0 when prediction is not a long

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#183]
From Nathan:

mutate(prediction = if_else(prediction > 0.5, 1L, 0L)) #works

mutate(prediction = if_else(prediction > 0.5, 1, 0)) #produces a list: <dbl [1]>

for spark 2.0.0

**Comment by slopp** [comment]
+1  - I had to wrap the statements in as.numeric to force the second to work

**Comment by javierluraschi** [comment]
Implemented collecting decimal columns which fixes the spark 2.0.0 list issue, but is still required to cast the parameters for now.

**Comment by marciz** [comment]
Also `if_else(condition, true, false, missing = NULL)` parameter missing is not supported

**Comment by javierluraschi** [comment]
Cast is acceptable, also improvement to auto-casts tracked by https://github.com/rstudio/sparklyr/issues/940, closing.
