### ISSUE TITLE
Broken link on Rstudio Webpage

### ISSUE THREAD

**Issue by samstiyer** [rstudio/sparklyr#1832]
Apologies if this is not the correct place to post this. 

However on this link is broken on Rstudio: 
[Broken Link](https://spark.rstudio.com/reference/sdf_register/sdf_copy_to.html)

Hope this helps!

**Comment by benmwhite** [comment]
I think issues with the `sparklyr` website itself go on [this repo](https://github.com/rstudio/spark.rstudio.com).

**Comment by javierluraschi** [comment]
Tracked by https://github.com/rstudio/spark.rstudio.com/issues/82
