### ISSUE TITLE
Single thread after data manipulation + writing out RDD

### ISSUE THREAD

**Issue by nhamwey** [rstudio/sparklyr#1835]
I posted a stackoverflow question here, but figured it might be suitable ask here as well:
https://stackoverflow.com/questions/54121555/sparklyr-single-thread-when-caching-writing-out-rdd-or-converting-to-h2o-frame

I've noticed very poor performance when reading in a parquet file + performing data manipulation operations, followed by caching, writing out to parquet/csv, or converting an h2o frame (using rsparkling).

This isn't an issue when simply reading in the file, then directly writing it back out or converting to an h2o frame.

Looking at my running processes, it appears spark runs these operations using a single core (only after the manipulation steps).

I noticed these messages in the spark log:

WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.

INFO ExternalAppendOnlyUnsafeRowArray: Reached spill threshold of 4096 rows, switching to org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter

Details on my Spark configuration:
sparklyr 0.9.3
spark 2.3.2

config$`sparklyr.shell.driver-memory` <- "200G"
config$`sparklyr.shell.executor-memory` <- "200G"
config$`spark.executor.memoryOverhead` <- "5G"
config$`spark.executor.cores` <- '50'
config$`spark.ext.h2o.nthreads` <- '50'
config$`spark.sql.shuffle.partitions` <- '50'
increased heartbeat since spark jobs were timing out, but still running
config$`spark.executor.heartbeatInterval` <- '1000000s'
config$`spark.network.timeout` <- '10000000s'
sc <- spark_connect(master = "local[50]", config = config)

Comparisons I ran:

- Load-in 40 GB parquet file: 3 minutes (always)

- Perform no operations, write back out to parquet takes 3 minutes (same when converting to h2o.frame using rsparkling)

- Perform any data manipulation operations, write to parquet/csv/h2o.frame all take ~40 minutes

What I've tried:

- sdf_repartition(partitions = 50)... it appears setting the repartition option in spark_read_parquet() isn't working on my machine...

- Messing around with other config options:

1. config$`spark.sql.windowExec.buffer.spill.threshold` <- '40000000'

2. config$`spark.dynamicAllocation.enabled` <- "false"

- Manually caching the table before running manipulation operations (but I don't think I should have to do this, since the spark_read_parquet by default loads the data into memory.)

**Comment by javierluraschi** [comment]
CC: @navdeep-G

**Comment by nhamwey** [comment]
Apologies if my question was too vague, I think we found the reason:

Using ifelse within mutate, combined with mean() function seems to forcing single partition.

Is this expected? Is it best practice to use an alternative method? (simplistic imputation method)

Ex:
`mutate(mileage_imputed = ifelse(is.na(mileage), mean(mileage, na.rm = T), mileage))`

**Comment by benmwhite** [comment]
@nhamwey Have you tried `ft_imputer()`?
