### ISSUE TITLE
Get a spark dataframe after using invoke 

### ISSUE THREAD

**Issue by ElianoMarques** [rstudio/sparklyr#184]
Hi all, 

As part of a comparison we are limiting the dataframe using invoke and then trying to run a model against it. 

```
d_train <- data %>% arrange(random_row_label) %>% filter(TrainTest == 'Train')  %>% invoke("limit",100000) 
or
d_train <- data %>% arrange(random_row_label) %>% filter(TrainTest == 'Train')  
sdf_register(d_train, "d_train") 
d_train <- hive_context(sc) %>% invoke("sql",paste0("select * from d_train limit ",100000))
```
either way the object returns a dataset and no longer can be used as a dataframe. 

Question do we have to registertemptable everytime an invoke is executed against a dataframe? 

```
d_train <- data %>% arrange(random_row_label) %>% filter(TrainTest == 'Train')  %>% invoke("limit",100000)  %>% invoke("registerTempTable",d_train) %>% tbl("d_train")
```

If there is a simple way to limit that could also do the job! 

Thank you

**Comment by kevinushey** [comment]
Generally, `invoke` takes a `spark_jobj`, and returns a `spark_jobj` -- ie, a lower-level reference to a JVM Spark object. If you call `invoke` and get a `spark_jobj` referencing a Spark `Dataset` (or, `DataFrame for Spark <2.0.0), then you'll need to explicitly register it to manipulate it as a `spark_tbl` / with the `dplyr` interface.

The set of `sdf_` wrapper functions generally do that automatically for you (all those routines call `sdf_register()` in the end), so I think if you're doing this lower-level programming with Spark you'll need to explicitly call `sdf_register()` to get a `tbl_spark` back.

**Comment by ElianoMarques** [comment]
Makes sense thanks. 
Eliano

**Comment by ElianoMarques** [comment]
@kevinushey , @javierluraschi here a weird behaviour I have observed that I'm not 100% sure but i think it's related with the package and a potential improvement. as part of a ML benchmark we were doing on public flights dataset with 20m records we have done this code:

```
#input data is the 20m rows dataset from the flights public dataset
data = tbl(sc, "input_data") 
data_2 <- (data %>% arrange(random_row_label) %>%
                    sdf_mutate(month_idx=ft_string_indexer(Month),
                                month_flags = ft_one_hot_encoder( month_idx),
                                DayofMonth_idx=ft_string_indexer(DayofMonth),
                                DayofMonth_flags = ft_one_hot_encoder(DayofMonth_idx),
                                DayOfWeek_idx=ft_string_indexer(DayOfWeek),
                                DayOfWeek_flags = ft_one_hot_encoder(DayOfWeek_idx),
                                UniqueCarrier_idx=ft_string_indexer(UniqueCarrier),
                                UniqueCarrier_flags = ft_one_hot_encoder(UniqueCarrier_idx),
                                Origin_idx=ft_string_indexer(Origin),
                                Origin_flags = ft_one_hot_encoder(Origin_idx),
                                Dest_idx=ft_string_indexer(Dest),
                                Dest_flags = ft_one_hot_encoder(Dest_idx)
                            ))

data_2 %>% sdf_register(name = "temp_train")
tbl_cache(sc,name = "temp_train")
trainsize = 10
trainlimit = as.integer(trainsize*10^6)
testsize = 0.1
testlimit = as.integer(testsize*10^6)
d_train <- spark_dataframe(data_2  %>% filter(TrainTest == 'Train'))  %>% invoke("limit", trainlimit) %>% sdf_register(name = 'temp_train1') 
tbl_cache(sc, name = 'temp_train1')
```

Please note the following: 

1. Input data was partitioned as a Hive table by year, month, dayofweek and uniquecarrier
2. Table was saved as a parquet file
3. We are reading the parquet file and confirm we keep the same partitions 

When I go to the spark ui and check the table temp_train1, it only had one partition in memory make the block RDD to big ~400mb instead of n blocks RDDs with smaller size which is better for ML procedures. We run several tests against the random forest algorithm and were already receiving a know error from Spark [https://issues.apache.org/jira/browse/SPARK-1476](https://issues.apache.org/jira/browse/SPARK-1476). 

I tried the same code in pypsark and just runs nicely. After a lot of debugging i found this:

Instead of using this code
```
d_train <- spark_dataframe(data_2  %>% filter(TrainTest == 'Train'))  %>% invoke("limit", trainlimit) %>% sdf_register(name = 'temp_train1') 
tbl_cache(sc, name = 'temp_train1')
```
Which leverages spark_dataframe and invokes limit, i use:
```
d_train <- data_2  %>% filter(TrainTest == 'Train'))  %>% sdf_register(name = 'temp_train1') 
tbl_cache(sc, name = 'temp_train1')
```
Which doesn't call spark_dataframe and the invoke, the cache keep the original partitions and the ML random forest algorithm worked just fine. In the above case, instead of 10m train records it actually leverages 14m as there is no limit being applied. 

Here is the ML model:

```
varchars <- c("month_flags","DayofMonth_flags","DayOfWeek_flags","UniqueCarrier_flags","Dest_flags","Dest_flags")
varnumeric <- c("DepTime","Distance")
featvars <- c(varchars,varnumeric)
md <- d_train3 %>% ml_random_forest( max.depth = 20, num.trees = 50 , response = "dep_delayed_15min_int",features=featvars)
```

So there seems to be something wrong with rather using spark_dataframe or invoking which doesn't keep the original partitions. 

Looking forward to hear back from you guys and potential ways to ensure that when leveraging spark_dataframe or invoking something from the dataset api the original partitions are kept the same. 

Eliano

**Comment by ElianoMarques** [comment]
This is not related to the package.
