### ISSUE TITLE
sparklyr return an error when trying to connect to AWS S3

### ISSUE THREAD

**Issue by solunsteve** [rstudio/sparklyr#1848]
I am a bit confused as I have followed the tutorials on the web and stackoverflow.

Here is the issue:

I have a bucket containing parquet files on S3 in AWS.

However I can't connect/download/work with these files.

Here is what I have done based on some tutorials from the web:

    
```
library(sparklyr)
    
 # Install Spark and Hadoop:
    
  # spark_install(version = "2.3.2", hadoop_version = "2.7")
    
    # Set configuration:
    conf <- spark_config()
    # conf$`sparklyr.cores.local` <- 8
    conf$`sparklyr.shell.driver-memory` <- "16G"
    conf$spark.memory.fraction <- 0.9
    
    # Connect to Spark:
    sc <- spark_connect(master = "local", 
                        version = "2.3.2",
                        config = conf)
    
    # Get spark context 
    ctx <- sparklyr::spark_context(sc)
    
    # Use below to set the java spark context 
    
    jsc <- invoke_static( sc, "org.apache.spark.api.java.JavaSparkContext", "fromSparkContext", ctx)
    
    # Set the S3 configs: 
    hconf <- jsc %>% invoke("hadoopConfiguration") 
    hconf %>% 
      invoke("set","fs.s3a.access.key", "ffvfvfvfv") 
    hconf %>% 
      invoke("set","fs.s3a.secret.key", "erfevvevefvevevefv")
    
    user_tbl <- spark_read_parquet(sc,name = "test_parquet_df_1",path = "s3a://mybucket/parquet_all/kuku.parquet")  
```

Running this returns NULL on each `hconf %>% invoke` combination and an error:

> Error: java.io.IOException: No FileSystem for scheme: https 	at
> org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
> 	at
> org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
> 	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94) 	at
> org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
> 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
> 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373) 	at
> org.apache.hadoop.fs.Path.getFileSystem(Path.java:295) 	at
> org.apache.spark.sql.execution.datasources.DataSource$.org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary(DataSource.scala:709)
> 	at
> org.apache.spark.sql.execution.datasources.DataSource$$anonfun$15.apply(DataSource.scala:390)
> 	at
> org.apache.spark.sql.execution.datasources.DataSource$$anonfun$15.apply(DataSource.scala:390)
> 	at
> scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
> 	at
> scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
> 	at scala.collection.immutable.List.foreach(List.scala:381) 	at
> scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
> 	at scala.collection.immutable.List.flatMap(List.scala:344) 	at
> org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:389)
> 	at
> org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:239)
> 	at
> org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227)
> 	at
> org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:622)
> 	at
> org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:621)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at
> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at
> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498) 	at
> sparklyr.Invoke.invoke(invoke.scala:139) 	at
> sparklyr.StreamHandler.handleMethodCall(stream.scala:123) 	at
> sparklyr.StreamHandler.read(stream.scala:66) 	at
> sparklyr.BackendHandler.channelRead0(handler.scala:51) 	at
> sparklyr.BackendHandler.channelRead0(handler.scala:4) 	at
> io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
> 	at
> io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at
> io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at
> io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	at
> io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
> 	at
> io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at
> io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at
> io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	at
> io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
> 	at
> io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
> 	at
> io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at
> io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at
> io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	at
> io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
> 	at
> io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at
> io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at
> io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
> 	at
> io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
> 	at
> io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
> 	at
> io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
> 	at
> io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) 	at
> io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
> 	at
> io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
> 	at java.lang.Thread.run(Thread.java:748)

AND

> Error: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
> 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2195)
> 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2654)
> 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
> 	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
> 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
> 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
> 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
> 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
> 	at org.apache.spark.sql.execution.datasources.DataSource$.org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary(DataSource.scala:709)
> 	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$15.apply(DataSource.scala:390)
> 	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$15.apply(DataSource.scala:390)
> 	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
> 	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
> 	at scala.collection.immutable.List.foreach(List.scala:381)
> 	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
> 	at scala.collection.immutable.List.flatMap(List.scala:344)
> 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:389)
> 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:239)
> 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227)
> 	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:622)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at sparklyr.Invoke.invoke(invoke.scala:139)
> 	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
> 	at sparklyr.StreamHandler.read(stream.scala:66)
> 	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
> 	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
> 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
> 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
> 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2101)
> 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2193)
> 	... 53 more

**Comment by edgararuiz** [comment]
Hi, this is how I've been able to connect and work with S3 buckets:

### AWS keys
```
Sys.setenv(AWS_ACCESS_KEY_ID="[Your access key]")
Sys.setenv(AWS_SECRET_ACCESS_KEY="[Your secret access key]")
```
### AWS S3 integration for Spark

https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-aws

Example:
```
conf$sparklyr.defaultPackages <- "org.apache.hadoop:hadoop-aws:2.7.3"
```

You may also need a parquet package, but I'm not sure, I've only used it with CSV files
