### ISSUE TITLE
`copy_to` turns Dates into numeric columns (with only the year)

### ISSUE THREAD

**Issue by dgrtwo** [rstudio/sparklyr#187]
When copying over a data frame (or tbl_df) with a Date column, it is rounded to the year:

``` r
library(sparklyr)
library(dplyr)

sc <- spark_connect(master = "local")

example <- data_frame(a = 1,
                      b = "text",
                      c = Sys.Date())

example_tbl <- copy_to(sc, example)

example_tbl
collect(example_tbl)
```

The resulting `c` column contains only 2016, not the full date:

```
Source:   query [?? x 3]
Database: spark connection master=local[16] app=sparklyr local=TRUE

      a     b     c
  <dbl> <chr> <dbl>
1     1  text  2016
```

**Comment by AjarKeen** [comment]
I'm encountering this problem as well. I have a Spark DataFrame that I want to join on a timestamp column, so I generate a time series in R and then use `copy_to` so that I can do the join, but

**Comment by fr-reuben** [comment]
Yes, this is an issue for me too. I am currently working around this by converting the date to epoch with `as.integer` but ideally would like a `cast()` or `to_date()` wrapper, or simply just have `copy_to()` preserve dates.

**Comment by javierluraschi** [comment]
This work is now being tracked by https://github.com/rstudio/sparklyr/issues/941

**Comment by imanojkumar** [comment]
My date are in the format "2018-12-01" in R dataframe and column is Date type but when copy_to spark dataframe, the output looks like this:

 bank_name  Date  Open  High   Low Close T           Q
  <chr>     <dbl> <dbl> <dbl> <dbl> <dbl>         <int>
1 AB           14613 1700  1728. 1693. 1706.             305049
2 AB           14614 1710  1725  1705  1707.             838660

why so?

**Comment by samuel-bohman** [comment]
I have the same problem.

```
economics_rdf <- ggplot2::economics

head(economics_rdf, 3)
# A tibble: 3 x 6
  date         pce    pop psavert uempmed unemploy
  <date>     <dbl>  <dbl>   <dbl>   <dbl>    <dbl>
1 1967-07-01  507. 198712    12.6     4.5     2944
2 1967-08-01  510. 198911    12.6     4.7     2945
3 1967-09-01  516. 199113    11.9     4.6     2958

dplyr::copy_to(sc, economics_rdf, overwrite = TRUE)
# Source: spark<economics_rdf> [?? x 6]
    date   pce    pop psavert uempmed unemploy
   <dbl> <dbl>  <dbl>   <dbl>   <dbl>    <dbl>
 1  -915  507. 198712    12.6     4.5     2944
 2  -884  510. 198911    12.6     4.7     2945
 3  -853  516. 199113    11.9     4.6     2958

sparklyr::sdf_copy_to(sc, economics_rdf, overwrite = TRUE)
# Source: spark<economics_rdf> [?? x 6]
    date   pce    pop psavert uempmed unemploy
   <dbl> <dbl>  <dbl>   <dbl>   <dbl>    <dbl>
 1  -915  507. 198712    12.6     4.5     2944
 2  -884  510. 198911    12.6     4.7     2945
 3  -853  516. 199113    11.9     4.6     2958
```
