### ISSUE TITLE
consider implementing additional types for sdf collect

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#188]
From this list: https://github.com/rstudio/sparklyr/blob/master/inst/scala/utils.scala#L130-L135

would make sense to implement all the types mapping as listed here:

https://spark.apache.org/docs/1.6.0/api/java/org/apache/spark/sql/types/package-tree.html

**Comment by ElianoMarques** [comment]
@javierluraschi could you also add sdf_cache and uncache? Currently this only works with tbl (tbl_cache) but if you apply some transformations prior to the cache you can't invoke tbl_cache. Several examples of invoke("cache") %>% sdf_register didn't really work as expected. Perhaps theres something in addition to the sdf_register needed but in either case, adding a sdf_cache makes total sense i think.

**Comment by javierluraschi** [comment]
@ElianoMarques do you remember the example of `invoke("cache") %>% sdf_register`? In general, it's a goal for sparklyr to never have to use `invoke` unless you are writing an extension. Thanks!
