### ISSUE TITLE
streaming not working

### ISSUE THREAD

**Issue by boofhead** [rstudio/sparklyr#1901]
```r
spark_version <- "2.4.0"
config <- spark_config()
config$sparklyr.shell.packages <- "org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0"
 sc <- spark_connect(master = "local", config = config)
```
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.1                         
year           2018                        
month          07                          
day            02                          
svn rev        74947                       
language       R                           
version.string R version 3.5.1 (2018-07-02)
nickname       Feather Spray     

# your reproducible example here
I can't get sparklyr streaming to function at all. Running the example form the docs below produces an empty stream. The Kafka example shown below that also looks empty and calling stream_view() or stream_stop() give the following error:
Error in UseMethod("invoke") : 
  no applicable method for 'invoke' applied to an object of class "c('tbl_spark', 'tbl_sql', 'tbl_lazy', 'tbl')"

Example 1.
```r
> if(file.exists("source")) unlink("source", TRUE)
> if(file.exists("source-out")) unlink("source-out", TRUE)
> 
> stream_generate_test(iterations = 1)
> read_folder <- stream_read_csv(sc, "source") 
> write_output <- stream_write_csv(read_folder, "source-out")
> invisible(future(stream_generate_test(interval = 0.5)))
Error in future(stream_generate_test(interval = 0.5)) : 
  could not find function "future"
> 
> stream_view(write_output)
Loading required package: shiny

Listening on http://127.0.0.1:4090
```

Example 2.
```r
test_options <- list(kafka.bootstrap.servers = 'aws-host:9092', subscribe='test')
test_stream <- stream_read_kafka(sc, options=test_options)
stream_view(test_stream)
Error in UseMethod("invoke") : 
  no applicable method for 'invoke' applied to an object of class "c('tbl_spark', 'tbl_sql', 'tbl_lazy', 'tbl')"
```

**Comment by boofhead** [comment]
Hi, is anyone looking at this? Can I provide any extra information to help out?

**Comment by javierluraschi** [comment]
Can you share `packageVersion("sparklyr")`, there were a few streaming issues in `sparklyr 0.9.x` that where solved until `sparklyr 0.9.4`, since you are using streams, definitely upgrade to `sparklyr 0.9.4`

Also, `stream_view()` only works with streams, not tables, so you would want to do something like:

```
test_stream <- stream_read_kafka(sc, options=test_options) %>% stream_write_kafka(options = test_options2)
stream_view(test_stream)
```

**Comment by boofhead** [comment]
Thanks Javier, Updating to R 3.5.2 and Sparklyr 0.9.4 fixed it.

**Comment by DSoot** [comment]
Hi javierluraschi, following the above that `strem_view` only works with streams, if I only want to consume (read) a topic is there any workaround?
