### ISSUE TITLE
Scala version used with latest sparklyr (spark version 2.4.0)

### ISSUE THREAD

**Issue by IyarLin** [rstudio/sparklyr#1902]
Hi,

This is a brief question: The ecosystem I work with has spark 2.4.0 built against Scala 2.12. Does the latest sparklyr (which supports spark 2.4.0) support Scala 2.12? I know it used to support Scala 2.11 but I couldn't find any documentation for that on the newest version.

Many thanks,

Iyar

**Comment by kevinykuo** [comment]
We don't currently build 2.12 jars (since 2.12 support is experimental in 2.4.) Could you give it a shot to see if it works?

**Comment by IyarLin** [comment]
Sure, will do. Thanks!
