### ISSUE TITLE
Add support for anonymous Scala functions

### ISSUE THREAD

**Issue by AlexIoannides** [rstudio/sparklyr#191]
It would be useful if there could be some way to parse basic Scala code declared from R, such that the following types of call are possible:

``` r
new_data_frame <- 
  spark_dataframe(auto_data) %>% 
  invoke("map", "(x: Row) => x")
```

This would remove the need to perform basic data manipulation elsewhere so that all code could be kept in once place. 

I would like to be able to use Scala functions like `map` as we can't (currently) apply/mutate using native R functions (although the more I Iearn about `ft_sql_transformer()` and Hives' UDFs the less of a need this becomes). 

I've had a quick look through the Scala docs and can't figure-out how Scala creates lambda functions (in a vain attempt to refer to the underlying Java object). I understand that I couple compile a custom JAR and use the Extensions API, but I'm looking for something more on-the-fly, if at all possible.

**Comment by kevinushey** [comment]
I wonder if it would be possible to compile + load jars 'on the fly', and use it in this way? It's definitely possible to build `sparklyr` extensions (e.g. http://spark.rstudio.com/extensions.html) but that's probably not quite as on-demand as we'd like here.

**Comment by AlexIoannides** [comment]
That idea did cross my mind, but I think it's a little too convoluted. We'd have to create a class, define a method, compile a jar, and then clean-up at some point.

My knowledge of Scala isn't good enough to know if this is even possible, but I was hoping to invoke 'some fundamental class' in the language that creates functions in a similar way that functions can be created in R using meta-programming methods. Maybe something along the lines of: http://www.scala-lang.org/api/current/#scala.Function1 ?

**Comment by javierluraschi** [comment]
Going to close this one to continue the discussion under https://github.com/rstudio/sparklyr/issues/940, which is tracking all the work related to making `invoke*()` better across `sparklyr`.
