### ISSUE TITLE
cross validation function and parameter tuning 

### ISSUE THREAD

**Issue by dwy904** [rstudio/sparklyr#196]
Does sparklyr support cross validation and parameter tuning in the machine learning section.

I did not find this capability and will you add that features in the future version ?

Best,
Mike

**Comment by kevinushey** [comment]
It looks like Spark does indeed provide a class that provides tooling for cross validation:

https://github.com/apache/spark/blob/master/mllib/src/main/scala/org/apache/spark/ml/tuning/CrossValidator.scala

We should investigate whether this is something we can support easily in `sparklyr`.

**Comment by ledell** [comment]
@dwy904 If you choose to use [H2O machine learning with sparklyr](http://spark.rstudio.com/h2o.html), then you can make use of many extra utilities like cross-validation and hyperparameter tuning.

**Comment by latinostats** [comment]
It would be very valuable to add the Crossvalidation and Hyper-Parameter search capabilities of SPARK into sparklyr.  Thanks

**Comment by dwy904** [comment]
It will be extremely helpful to have the cross validation and parameter tuning features in sparklyr 👍

**Comment by javierluraschi** [comment]
We are cleaning up a bit feature requests, this one is now part of https://github.com/rstudio/sparklyr/issues/196, feel free to comment on that one instead. Thanks for suggesting this one!

**Comment by efh0888** [comment]
So any update on this?

**Comment by dwy904** [comment]
I switched to h2o.

**Comment by kevinykuo** [comment]
@efh0888 Yes, this is on the roadmap for `0.7` and I should have something ready for testing in the next couple weeks. Will update/reopen this issue and ping the folks here.

**Comment by efh0888** [comment]
Sounds good.  

I haven't found much documentation on how the algorithms currently choose values for the hyperparameters, e.g. mtry in random forests?   I could construct the k-fold cv process myself if there's a way to provide these parameter values as inputs.

**Comment by dwy904** [comment]
Yes, there is a way to do parameter tuning by writing for loops.  I hope this
<https://github.com/dwy904/Tips_Prediction_NYC_Green_Taxi>can help.

**Comment by efh0888** [comment]
Nice.  I'm constructing something similar but trying to keep the data in spark.  

Using ml_random_forest, as in the example, we'd only be able to tune parameters made explicitly available as inputs like max.bins, max.depth, and num.trees, but nothing else such as mtry -- @kevinykuo is that right?  Or is it possible to pass in other parameters, perhaps through ml_options()?

**Comment by kevinykuo** [comment]
@efh0888 you can probably hack something together via but I'd recommend holding off for now. The improved sparklyr ML API will have support for all hyperparameters (so no need for `ml_options()`) and you'll be able to tune parameters for multiple pipeline transformers simultaneously. Basically we'll expose [this](https://spark.apache.org/docs/latest/ml-tuning.html#cross-validation) API.

**Comment by dwy904** [comment]
Hi,

I have not used sparklyr for a while since I have switched to h2o. I am
wondering if someone can discuss the advantages and disadvantages between
sparklyr and h2o in details?

Best,
Michael

**Comment by efh0888** [comment]
@kevinykuo thanks for the info.  In that case, I'll probably stick with other frameworks like caret for the time being.  

@dwy904 unfortunately, we don't have access to h2o in our current development environment...

**Comment by kevinykuo** [comment]
Cross validation is now supported in devel. See https://github.com/rstudio/sparklyr/blob/master/tests/testthat/test-ml-tuning.R#L60-L85 for example usage.
