### ISSUE TITLE
Error with ML 

### ISSUE THREAD

**Issue by ElianoMarques** [rstudio/sparklyr#197]
I keep getting this error on a 2-3 hours ML job:

```
Error in invoke_method.spark_shell_connection(spark_connection(jobj),  : 
  No status is returned. Spark R backend might have failed.
```

Spark UI is still on and the job have completed. 

Any hints on how to get back the session and respective results?

Eliano

**Comment by kevinushey** [comment]
Are you running with RStudio Server? I wonder if the issue here is that the R session is suspending / resuming, and the Spark connection is lost during that suspend / resume?

**Comment by ElianoMarques** [comment]
I'm leveraging RStudio Server indeed. I can try to run in a shell to see if the behaviour changes. 

Eliano

**Comment by ElianoMarques** [comment]
Same error in shell:

```
Error in invoke_method.spark_shell_connection(spark_connection(jobj),  : 
  No status is returned. Spark R backend might have failed.
Calls: ML_train_test_save_store ... invoke_method -> invoke_method.spark_shell_connection
Execution halted
```

**Comment by kevinushey** [comment]
Thanks. My best guess so far -- we've seen some similar errors when the Spark runs out of memory, so perhaps the job is very memory-hungry?

**Comment by ElianoMarques** [comment]
Spark continues to run normally. Sometimes it finishes the job, sometimes doesn't but when this message appears it's clearly running. This message shows around 2 hours after a job starts.

**Comment by kevinushey** [comment]
We might have to investigate if there's something in the Spark R backend that just times out on long-running jobs :/

**Comment by ElianoMarques** [comment]
thanks @kevinushey, that would be great. On a separate note, how do you add parameters missing in the ml models? e.g. 

```
model = ml_logistic_regression(train_df, alpha = 0, lambda = 0.01, iter.max = 5, response = "label",features=featvars) 
```
There is no variable for Standardization and/ or GLM the regularization parameters are also not there. I see the ml.options, is that the way to other those things? 

Eliano

**Comment by slopp** [comment]
@ElianoMarques and @kevinushey I'm opening this previous request as a new issue: https://github.com/rstudio/sparklyr/issues/207

@ElianoMarques fyi - the ml.options is currently used as an interface to control the resulting column names (id, response, and features) after the input data frame is prepared for the ml model via ml_prepare_dataframe. This is important if you wish to save the model and use it another language (ie pyspark). See `?ml.options` for more info.

**Comment by ElianoMarques** [comment]
Thanks for the note. I have looked inside the function further and realized the ml.options was being used in the pre-modelling process.

**Comment by MarcinKosinski** [comment]
I receive the same error as @ElianoMarques for long time ML operations.
My whole clustering takes about 2-3 hours, in the Spark UI I see the job is running but in the RStudio Server I receive:

````{R}
> system.time({
+   do_clustering %>%
+     ml_kmeans(centers = 8, compute.cost = TRUE) -> model_kmeans_8
+ }) -> klastrowanie_time8

 Error in invoke_method.spark_shell_connection(spark_connection(jobj),  : 
  No status is returned. Spark R backend might have failed.
 
Timing stopped at: 9.696 11.724 6059.916 
````

but what's weird that the Spark havent finished yet

![sparklyr_ui](https://cloud.githubusercontent.com/assets/6773454/18917686/c89cad3c-8598-11e6-953e-a50d15a54605.png)

**Comment by javierluraschi** [comment]
@MarcinKosinski Looks like we could be hitting a timeout here: https://github.com/rstudio/sparklyr/blob/299fba7da57a6f11c99a545a4ccd67b6877d3c9f/R/spark_shell.R#L188-L193

We inherited this timeout from `sparkR` and was set to `6000` or about `~1.6` hours but I can't think of a good reason why this would be set to this arbitrary number. Therefore, increased the timeout significantly with this commit: https://github.com/rstudio/sparklyr/commit/a492d23f004cbd336af473d732f2626b693c83bb

Could you retry using the latest version of `sparklyr` in `master`?

**Comment by ElianoMarques** [comment]
great that you found the issue and i also you add this as a config. Thanks @javierluraschi

**Comment by MarcinKosinski** [comment]
Thanks @javierluraschi . I think this issue can be closed (if maybe previously renamed).

**Comment by javierluraschi** [comment]
K! Closing.

**Comment by jmuhlenkamp** [comment]
Having a similar issue, will devtools:::install_github(‘rstudio/sparklyr’) fix this issue or do I need to actually fork the repo?  Thanks!

**Comment by kevinushey** [comment]
Running `devtools::install_github('rstudio/sparklyr')` will install the latest version of `sparklyr`, and that should ensure that you get the fixes recently added by @javierluraschi here.

If you're still having problems with the latest development version of `sparklyr`, please let us know!

**Comment by jmuhlenkamp** [comment]
Thanks, will do!
