### ISSUE TITLE
tbl_cache() broken

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/sparklyr#1975]
```
> sc <- spark_connect(master = "local")
* Using Spark: 2.4.0
> iris_tbl <- copy_to(sc, iris)
> iris_tbl %>% tbl_cache()
 Error: Unable to retrieve a spark_connection from object of class NULL
```

**Comment by Greezy07** [comment]
The function tbl_cache() is supposed to take as parameters the connection and  the name of your table view 
`
> iris_tbl %>%sdf_register(name="iris_view")
>tbl_cache(sc,name="iris_view)
`

**Comment by kevinykuo** [comment]
`sdf_persist()` was the right function to use here. Thanks!
