### ISSUE TITLE
Second spark connection could hang (waiting state) in certain scenarios

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/sparklyr#199]
Using sparklyr 0.3.12, and Spark 2.0.0
EMR Cluster r3.2xlarge, 1 master, 2 worker nodes

- `flights` data (full set) is used. Data is copied from S3 to HDFS in csv format, and then loaded into Hive tables.
- In IDE, open a spark connection 
- Run this command to cache `flights` data:

```
tbl_cache(sc, 'flights')
```

- Create a Shiny application on Shiny Server that does some interaction with Spark and `flights` data.
- Add the same command on top so data gets cached.
- Launch the application on Shiny Server. This hangs indefinitely.

Note: The same Shiny app without any changes loads fine (after the long delay) if the first spark connection from IDE is closed.

**Comment by javierluraschi** [comment]
I performed a similar investigation locally, here is my setup:

Starting spark standalone:

```{bash}
./start-master.sh
./start-slave.sh spark://Javiers-MBP-2.domain:7077
```

Running this from the first r session would work, but the second session would hang:

```{r}
sc <- spark_connect(master = "spark://Javiers-MBP-2.domain:7077", spark_home = "/Users/javierluraschi/Library/Caches/spark/spark-1.6.1-bin-hadoop2.6")

copy_to(sc, iris)
```

The problem was resource starvation for the second application:

<img width="1422" alt="screen shot 2016-09-01 at 11 13 26 am" src="https://cloud.githubusercontent.com/assets/3478847/18178945/32ad6d20-7035-11e6-96f1-4ff9fff3c8c6.png">

@fereshtehRS Do you see the second application also in `waiting` state?

If that's the case, we need to make sure there are enough resources in the cluster to run a second application. In my case, I was able to fix this as follows:

```{r}
sconf <- spark_config()
sconf[["spark.cores.max"]] <- 1

sc <- spark_connect(
    master = "spark://Javiers-MBP-2.domain:7077",
    spark_home = "/Users/javierluraschi/Library/Caches/spark/spark-1.6.1-bin-hadoop2.6",
    config = sconf)

copy_to(sc, iris)
```

Notice that when the second application started is now available also in `running` state and the commands succeed:

<img width="1420" alt="screen shot 2016-09-01 at 11 17 26 am" src="https://cloud.githubusercontent.com/assets/3478847/18179076/b7298304-7035-11e6-84da-83e40923b351.png">

**Comment by nwstephens** [comment]
I have simpler workflow that demonstrates the same issue (I think):
1. Connect to a cluster: sc <- spark_connect(master="yarn")
2. Cache a hive table: tbl_cache(sc, "hivetable")
3. Start a new R session
4. Connect to the same cluster (should create a new context)
5. Cache the same hive table
6. Caching hangs on second session

**Comment by javierluraschi** [comment]
@nwstephens right, we need to make sure the second application is no longer in `waiting` state, this is independent of sparklyr. Is the second application in `waiting` state?

If that's the case, we can start by reducing the number of cores to troubleshoot the resource that is blocking the app to start:

```{r}
sconf[["spark.cores.max"]] <- 1
```

**Comment by fereshtehRS** [comment]
@javierluraschi The Web UI on the EMR cluster is different, and not always helpful. In this case I don't see the WAITING status for the job while it is hanging. This is what is displayed for the `job`:

![spark-job-status](https://cloud.githubusercontent.com/assets/4906984/18292030/281125aa-7459-11e6-9442-21cdf5e080c8.png)


And if I drill into the job, this is what is displayed for `stages`:

![spark-stages-status](https://cloud.githubusercontent.com/assets/4906984/18292045/37482816-7459-11e6-87bf-745372376d43.png)

And nothing is displayed if I drill further down.

But definitely the job is waiting, nothing is running for it (based on the UI). I tried with some different configurations with `flights` table (the big table), and got same results.
However, trying with another table that is much smaller didn't show this issue. So seems to be a resources issue.

**Comment by fereshtehRS** [comment]
I should also mention that when we terminate that operation from IDE, that doesn't terminate the Spark job. Therefore any operation we run after this also hangs. For example `spark_disconnect(sc)` wouldn't work.

**Comment by javierluraschi** [comment]
@fereshtehRS did

```{r}
sconf[["spark.cores.max"]] <- 1
```

helper at all? If you could grab me tomorrow to debug this together, that would be great, I still think there is probably a resource constraint somewhere that is blocking execution. I'll try to find you in slack as well.

**Comment by javierluraschi** [comment]
Investigation follow up with Fereshteh: A resource constraint on Spark seems to be causing this issue since we found out that the second connection can succeed with different resource allocation for the connection. We could use this issue to consider providing better error reporting; however, this might be unfeasible without changing in Spark itself since I'm not yet aware of an API that would provide this functionality.

**Comment by fereshtehRS** [comment]
@javierluraschi  (and @nwstephens ) I have done more testing around this. This is definitely a resource constraint, and may be a bug in Spark with dynamicAllocation enabled. I will write up a document, but the summary is this:

- With dynamicAllocation enabled, when the first context starts a heavy job, it requests and is being granted a large number of executors
- When this job is completed the resources are not always freed (this might be a bug)
- There is a configuration setting `spark.dynamicAllocation.executorIdleTimeout` with default value of 60s. I have set this to even lower values, but doesn't seem to take effect. Or may be because the executors don't seem to be idle (even after the job is done)
- Second context starts a heavy job, requests a large number of executors, but not much is available. So this hangs until resources become available. Id we disconnect the first context, then this one runs smoothly.

A different scenario:
- First context starts with a small job, and completes it.
- Second context also starts with a small job, and completes it.
- At this point both of the contexts have some executors allocated to them.
- After this, each context could start a heavy job, and they both finish (no waiting).

Disabling dynamicAllocator:
- With this, we need to pre-allocate resources. These parameters must be set such that the expected number of contexts could each have enough resources:

```
spark.executor.instances         10
spark.executor.cores             2
```

- With correct settings, then the second context could also start a heavy job, and it completes in a normal fashion (no waiting).

**Comment by fereshtehRS** [comment]
Found this parameter for `dynamicAllocation`:

`spark.dynamicAllocation.maxExecutors`

We should be able to get around the "hang" issue using a reasonable max.

**Comment by javierluraschi** [comment]
Great! Should we close this issue then? @fereshtehRS

**Comment by fereshtehRS** [comment]
sure; closing it.
