### ISSUE TITLE
Convert UTC date time to local date time in sparklyr?

### ISSUE THREAD

**Issue by yogi-srcc-iimb** [rstudio/sparklyr#2004]
I am struggling to convert utc timestamp to local time using different time zones in sparklyr . 

df<-data.frame(utc_time_stamp=c("2019-04-28 18:35:26","2019-04-28 21:28:58","2019-04-28 18:59:01"),time_zonne=c("Asia/Tokyo","Australia/Brisbane","Etc/GMT-12"))

#loading to spark 
rd_1<-copy_to(sc,df,"mydf)

**Comment by benmwhite** [comment]
What outputs are you expecting? Your data frame has character-valued columns.

There are [some Spark SQL functions](https://spark.apache.org/docs/latest/api/sql/index.html#to_utc_timestamp) you can use within dplyr verbs if you want to convert the schema from characters to timestamp, e.g. `df %>% mutate(new_dtime = to_timestamp(chr_dtime))`.

**Comment by yogi-srcc-iimb** [comment]
I want to create new_local_time column (i was able to do that in R  ,not in Sparklyr) that converts utc time stamp to local time stamp using time zone . For your reference , pls follow below script ...

I have to create a new column (new_local_time) in spark r using utc time stamp n time zone for different locations...

df$utc_time_stamp <- as.POSIXct(df$utc_time_stamp, format="%Y-%m-%d %H:%M:%S", tz='GMT')

tz_v <- Vectorize(function(x,y) {format(x, tz=y, usetz=TRUE)})

df$new_local_time <- tz_v(df$utc_time_stamp, df$time_zone)
df

Expected Output in Spark R
>>>        utc_time_stamp          time_zone           new_local_time
>>> 1 2019-04-28 18:35:26         Asia/Tokyo  2019-04-29 03:35:26 JST
>>> 2 2019-04-28 21:28:58 Australia/Brisbane 2019-04-29 07:28:58 AEST
>>> 3 2019-04-28 18:59:01         Etc/GMT-12  2019-04-29 06:59:01 +12

Hope you get it now ....

**Comment by benmwhite** [comment]
[Try this Spark SQL function](https://spark.apache.org/docs/latest/api/sql/index.html#from_utc_timestamp) inside a `mutate()` call. You also need to convert the column in your Spark table from character to timestamps first, but I'd try something like `mutate(new_local_time = from_utc_timestamp(utc_time_stamp, time_zone))` after that.

**Comment by yogi-srcc-iimb** [comment]
Thanks a lot , it worked finally ...
