### ISSUE TITLE
facebook prophet stuck when using with spark_apply

### ISSUE THREAD

**Issue by tedapham** [rstudio/sparklyr#2005]
# Reporting an Issue with sparklyr
No output with spark_apply and prophet
---
0

I'm trying to test if I can run prophet with sparklyr to make forecast for data in cluster. But when I use spark_apply the program is stuck.

Running sparklyr on an edgenode connected to a yarn-client with spark 2.2.0. The data is sales by locations spanning last 4 years.

The plan is to create a dataframe with all the data and partition the data by locations then call prophet on each location and get prediction for the next 7 days.

Here I tried to pull data for one location and apply prophet but sparklyr was stuck.

```r
library("sparklyr")
library("prophet")

sc <- spark_connect(master = "yarn-client",version = "2.2.0"))
query = "select * from saletable"
df <- sdf_sql(sc,query) %>%
         filter(locationid=="1111") %>% 
         select(date,sales) %>%
         sdf_repartition(partitions=1) %>%
         select(ds=date,y=sales)

## try to predict sales the next 7 days and get the predictions

sparkly_prophet <- function(df){
    m <- prophet::prophet(df)
    future <- prophet::make_future_dataframe(m,periods=7,freq='day')
    forecast <- predict(m,future)
    return (dplyr::select(forecast,yhat) %>% tail(7))
}


## then I run but it stucked

spark_apply(df,sparkly_prophet)
```

**Comment by javierluraschi** [comment]
Notice that without loading `library(prophet)` this does not work either:

```r
data <- read.csv("https://raw.githubusercontent.com/facebook/prophet/master/examples/example_air_passengers.csv")

sparkly_prophet <- function(df){
    m <- prophet::prophet(df)
    future <- prophet::make_future_dataframe(m,periods=7,freq='day')
    forecast <- predict(m,future)
    return (dplyr::select(forecast,yhat) %>% tail(7))
}

sparkly_prophet(data)
```
```
Disabling weekly seasonality. Run prophet with weekly.seasonality=TRUE to override this.
Disabling daily seasonality. Run prophet with daily.seasonality=TRUE to override this.
Error in cpp_object_initializer(.self, .refClassDef, ...) : 
  could not find function "cpp_object_initializer"
failed to create the optimizer; optimization not done
 Error in matrix(m$params[[name]], nrow = n.iteration) : 
  'data' must be of a vector type, was 'NULL' 
```

So instead, you want to define `sparkly_prohet` as follows, also notice that you can't use `%>%` without importing `dplyr` or `magrittr`:

```r
sparkly_prophet <- function(df) {
    library(prophet)
    library(dplyr)
    
    model <- prophet(df)
    future <- make_future_dataframe(model, periods=7, freq='day')
    predict(model, future) %>% select(yhat) %>% tail(7)
}
```

Which would work appropriately with `sparklyr`, a simple local example:

```r
library(sparklyr)
sc <- spark_connect(master = "local")

air_data <- copy_to(sc, data)

spark_apply(air_data, sparkly_prophet)
```
```
# Source: spark<?> [?? x 1]
   yhat
  <dbl>
1  447.
2  443.
3  439.
4  434.
5  430.
6  425.
7  421.
```

Please beware that you'll have to properly group your your data when using `spark_apply()` since it does not apply a transformation across the entire dataset but rather, it applies a transformation over each Spark partition.

**Comment by tedapham** [comment]
Thanks @javierluraschi.
Can you help me understand better the following:

1. I realized that I need either installing R+prophet on the worker nodes or send a conda zip to the worker nodes (per https://blog.cloudera.com/blog/2017/09/how-to-distribute-your-r-code-with-sparklyr-and-cdsw/). Is this still the case with sparklyr 1.0? Right now I only have R on an edge node.

2. After the transformation on each partition, is the result saved at that partition or distributed? How will the result be saved or accessed with spark_apply?

**Comment by benmwhite** [comment]
You need R installed on each worker node, [but you can ship out the required external packages through sparklyr](https://spark.rstudio.com/guides/distributed-r/#distributing-packages) instead of installing them on each node manually.

**Comment by supermdat** [comment]
I'm having some trouble getting the above reprex to run (I'm using `sparklyr` in Databricks), and I'm wondering if there's anything I may be missing. Any tips here would be appreciated.

Below is my version of the reprex.

```
%python

print("Databricks Runtime and Scala Versions: " + spark.conf.get("spark.databricks.clusterUsageTags.sparkVersion"))
print("Spark Version: " + spark.version)
```

> Databricks Runtime and Scala Versions: 7.5.x-scala2.12
> Spark Version: 3.0.1


`sessionInfo()`

> R version 3.6.3 (2020-02-29)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 18.04.5 LTS
> 
> Matrix products: default
> BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
> LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so
> 
> locale:
>  [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
>  [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
>  [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
> [10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] prophet_0.6.1   rlang_0.4.10    Rcpp_1.0.6      forcats_0.5.1  
>  [5] stringr_1.4.0   dplyr_1.0.5     purrr_0.3.4     readr_1.4.0    
>  [9] tidyr_1.1.3     tibble_3.1.0    ggplot2_3.3.3   tidyverse_1.3.0
> [13] sparklyr_1.6.1  remotes_2.2.0  
> 
> loaded via a namespace (and not attached):
>  [1] hwriterPlus_1.0-3  tidyselect_1.1.0   forge_0.2.0        haven_2.3.1       
>  [5] colorspace_2.0-0   vctrs_0.3.6        generics_0.1.0     htmltools_0.5.1.1 
>  [9] base64enc_0.1-3    utf8_1.2.1         SparkR_3.0.0       pillar_1.5.1      
> [13] glue_1.4.2         withr_2.4.1        DBI_1.1.1          Rserve_1.8-7      
> [17] dbplyr_2.1.0       modelr_0.1.8       readxl_1.3.1       lifecycle_1.0.0   
> [21] munsell_0.5.0      gtable_0.3.0       cellranger_1.1.0   rvest_0.3.6       
> [25] hwriter_1.3.2      htmlwidgets_1.5.3  codetools_0.2-18   ps_1.6.0          
> [29] fansi_0.4.2        broom_0.7.2        r2d3_0.2.5         backports_1.2.1   
> [33] scales_1.1.1       jsonlite_1.7.2     fs_1.5.0           TeachingDemos_2.12
> [37] hms_1.0.0          digest_0.6.27      stringi_1.5.3      rprojroot_2.0.2   
> [41] grid_3.6.3         cli_2.3.1          tools_3.6.3        magrittr_2.0.1    
> [45] crayon_1.4.1       pkgconfig_2.0.3    ellipsis_0.3.1     xml2_1.3.2        
> [49] reprex_1.0.0       lubridate_1.7.10   assertthat_0.2.1   httr_1.4.2        
> [53] rstudioapi_0.13    R6_2.5.0           compiler_3.6.3    

```
data <- 
  read.csv("https://raw.githubusercontent.com/facebook/prophet/master/examples/example_air_passengers.csv") %>% 
  dplyr::mutate(
    ds = lubridate::as_date(ds)
  )
print(class(data))
print(glimpse(data))
```

> [1] "data.frame"
> Rows: 144
> Columns: 2
> $ ds <date> 1949-01-01, 1949-02-01, 1949-03-01, 1949-04-01, 1949-05-01, 1949-0…
> $ y  <int> 112, 118, 132, 129, 121, 135, 148, 148, 136, 119, 104, 118, 115, 12…


```
sparkly_prophet <-
  function(data) {
    library("prophet")
    library("dplyr")

    m        = prophet(df = data)
    future   = make_future_dataframe(
                 m = m,
                 periods = 5,
                 freq = "month"
               )
    forecast = predict(
                 object = m,
                 df = future
                )
    
    return(forecast %>% tail(5))
  }
```


```
air_data <- sparklyr::copy_to(dest = sc, df = data, overwrite = TRUE)

print(class(air_data))
print(glimpse(air_data))
```

> [1] "tbl_spark" "tbl_sql"   "tbl_lazy"  "tbl"      
> Rows: ??
> Columns: 2
> Database: spark_connection
> $ ds <date> 1949-01-01, 1949-02-01, 1949-03-01, 1949-04-01, 1949-05-01, 1949-0…
> $ y  <int> 112, 118, 132, 129, 121, 135, 148, 148, 136, 119, 104, 118, 115, 12…


`sparklyr::spark_apply(x = air_data, f = sparkly_prophet)`

> Error : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 185.0 failed 4 times, most recent failure: Lost task 0.3 in stage 185.0 (TID 530, 172.22.66.134, executor 0): java.lang.Exception: sparklyr worker rscript failure with status 255, check worker logs for details.
> 	at sparklyr.Rscript.init(rscript.scala:83)
> 	at sparklyr.WorkerApply$$anon$2.run(workerapply.scala:133)
> 
> Driver stacktrace:
> 	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2519)
> 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2466)
> 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2460)
> 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
> 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
> 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
> 	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2460)
> 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1152)
> 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1152)
> 	at scala.Option.foreach(Option.scala:407)
> 	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1152)
> 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2721)
> 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2668)
> 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2656)
> 	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
> 	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:938)
> 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2333)
> 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2428)
> 	at org.apache.spark.sql.execution.collect.Collector.runSparkJobs(Collector.scala:273)
> 	at org.apache.spark.sql.execution.collect.Collector.collect(Collector.scala:308)
> 	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:82)
> 	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:88)
> 	at org.apache.spark.sql.execution.collect.InternalRowFormat$.collect(cachedSparkResults.scala:61)
> 	at org.apache.spark.sql.execution.collect.InternalRowFormat$.collect(cachedSparkResults.scala:57)
> 	at org.apache.spark.sql.execution.ResultCacheManager.$anonfun$getOrComputeResultInternal$1(ResultCacheManager.scala:479)
> 	at scala.Option.getOrElse(Option.scala:189)
> 	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResultInternal(ResultCacheManager.scala:479)
> 	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:423)
> 	at org.apache.spark.sql.execution.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:401)
> 	at org.apache.spark.sql.execution.SparkPlan.executeCollectResult(SparkPlan.scala:389)
> 	at org.apache.spark.sql.Dataset.collectResult(Dataset.scala:3013)
> 	at org.apache.spark.sql.Dataset.collectFromPlan(Dataset.scala:3736)
> 	at org.apache.spark.sql.Dataset.$anonfun$collect$1(Dataset.scala:2980)
> 	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3728)
> 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$5(SQLExecution.scala:116)
> 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:248)
> 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:101)
> 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:841)
> 	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:77)
> 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:198)
> 	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3726)
> 	at org.apache.spark.sql.Dataset.collect(Dataset.scala:2980)
> 	at sparklyr.Utils$.collect(utils.scala:137)
> 	at sparklyr.Utils.collect(utils.scala)
> 	at sun.reflect.GeneratedMethodAccessor439.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at sparklyr.Invoke.invoke(invoke.scala:147)
> 	at sparklyr.StreamHandler.handleMethodCall(stream.scala:136)
> 	at sparklyr.StreamHandler.read(stream.scala:61)
> 	at sparklyr.BackendHandler.$anonfun$channelRead0$1(handler.scala:58)
> 	at scala.util.control.Breaks.breakable(Breaks.scala:42)
> 	at sparklyr.BackendHandler.channelRead0(handler.scala:39)
> 	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
> 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.Exception: sparklyr worker rscript failure with status 255, check worker logs for details.
> 	at sparklyr.Rscript.init(rscript.scala:83)
> 	at sparklyr.WorkerApply$$anon$2.run(workerapply.scala:133)

**Comment by yitao-li** [comment]
@supermdat The error message says the function you passed to `spark_apply()` failed on some Spark worker node(s). You should be able to see the R stack trace somewhere in the Spark worker log.

You can also try manually running the function you passed to `spark_apply()` on a worker node with some small subset of data as input.

Also, please double-check R is installed on each worker node and you have followed https://therinspark.com/distributed.html#packages to copy required packages to each worker node too (or alternatively, install required R packages on each worker node).
