### ISSUE TITLE
SparkUI and Log errors out - cannot open file 'log4j.spark.log': No such file or directory

### ISSUE THREAD

**Issue by ganeshmailbox** [rstudio/sparklyr#201]
@javierluraschi 
I have the same issue as @EricAugust , this is with the latest version of sparklyr (0.3.12) on windows, the issue is that when I click on the any of SparUI in RStudio or on the "Log" icon i get the exact same error as mentioned by EricAugust. Note that i had to do a tweak to create the spark context (this was mentioned also mentioned in this thread). i.e.,
`config <- spark_config()`
`config[["sparklyr.defaultPackages"]] <- NULL`
`sc <- spark_connect(master = "local", config = config)`

I used the `spark_install(version = "1.6.2")` to install spark on local m/c.
As requested above i have uploaded the hive-site.xml (i have zipped it to avoid error)
[hive-site.zip](https://github.com/rstudio/sparklyr/files/452563/hive-site.zip)

when i click on the SparkUI i get this error as below

> Error in open.connection(con, "rb") : cannot open the connection
> In addition: Warning message:
> In open.connection(con, "rb") :
> cannot open file 'log4j.spark.log': No such file or directory

**EDIT:** My RStudio is version 1.0.4 .

**Comment by javierluraschi** [comment]
Opened from https://github.com/rstudio/sparklyr/issues/125

**Comment by javierluraschi** [comment]
Sorry it took us this long to get to this @ganeshmailbox, we've definitely made improvements for Windows for launching the Spark UI and logs, so far, we haven't spotted any additional isues, but do open a new issue with details of RStudio/sparklyr versions to assist further. We also created the github channel for direct chat with us if you want to resolve this sooner.
