### ISSUE TITLE
Date comparison in filter

### ISSUE THREAD

**Issue by wilvancleve** [rstudio/sparklyr#202]
I have two parquet files with Date columns, and I'd like to be able to effectively use date arithmetic, which is possible in SparkR using functions in the Spark API that it exposes. 

I need to test whether one date is one day less than another. In SparkR, this would be : 

newdf <- filter(origdf, DATE1 = date_sub(DATE2, 1))

I cannot determine how to effectively do this in sparklyr. Is what I'm trying to achieve possible, or is testing for Date (and/or string) equality the only comparison possible for Date columns?

**Comment by javierluraschi** [comment]
@wilvancleve `date_sub` is currently not supported in sparklyr, you could try:

```{r}
# connect to spark
sc <- spark_connect(master = "local")

# load data with table name dates_csv
df <- data.frame(a = c(1, 2), b = c(as.Date("2016/1/1"), as.Date("2017/1/1")))
readr::write_csv(df, "dates.csv")
spark_read_csv(sc, "dates_csv", "dates.csv", overwrite = TRUE)

# perform sql query directly using a sql statement
one_day_less <- tbl(sc, sql(
   "SELECT * FROM `dates_csv` WHERE (`b` = date_sub(Date('2017-01-02'), 1))"
))

# optionally, perform additional dplyr operations
one_day_less %>% filter(a < 3)
```

**Comment by ZeccaLehn** [comment]
@javierluraschi Any way to import POSIXct --i.e., with hours/minutes?

**Comment by ZeccaLehn** [comment]
@javierluraschi Any way to import POSIXct into sparklyr without loosing the minute/second information? I can import as a numeric, but would make querying difficult within SparkSQL.

**Comment by javierluraschi** [comment]
We are planning to address proper serialization of Dates with this instead: https://github.com/rstudio/sparklyr/issues/941, feel free to continue the discussion/suggestions there.
