### ISSUE TITLE
connect to Apache Cassandra

### ISSUE THREAD

**Issue by ChingChuan-Chen** [rstudio/sparklyr#205]
My config.yml:

``` yml
default:
  # local-only configuration
  sparklyr.cores.local: !expr parallel::detectCores()
  spark.sql.shuffle.partitions.local: !expr parallel::detectCores()

  # default spark packages to load
  sparklyr.defaultPackages:
    - com.databricks:spark-csv_2.11:1.3.0
    - com.amazonaws:aws-java-sdk-pom:1.10.34
    - com.datastax.spark:spark-cassandra-connector_2.11:2.0.0-M1
```

R code:

``` R
library(pipeR)
library(sparklyr)

spark_master <- "mesos://zk://192.168.0.121:2181,192.168.0.122:2181,192.168.0.123:2181/mesos"
sc <- spark_connect(master = spark_master, config = spark_config("config.yml", FALSE))

sparkSession <- invoke_static(sc, "org.apache.spark.sql.SparkSession", "builder") %>>%
  invoke("config", "spark.cassandra.connection.host", 
         "192.168.0.121,192.168.0.122,192.168.0.123") %>>%
  invoke("getOrCreate")

cass_df <- invoke(sparkSession, "read") %>>% 
  invoke("format", "org.apache.spark.sql.cassandra") %>>%
  invoke("option", "keyspace", "test") %>>% invoke("option", "table", "kv") %>>%
  invoke("load")
```

There is an error occurred:
```
rror: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.spark.sql.hive.client.IsolatedClientLoader.createClient(IsolatedClientLoader.scala:258)
	at org.apache.spark.sql.hive.HiveUtils$.newClientForMetadata(HiveUtils.scala:359)
	at org.apache.spark.sql.hive.HiveUtils$.newClientForMetadata(HiveUtils.scala:263)
	at org.apache.spark.sql.hive.HiveSharedState.metadataHive$lzycompute(HiveSharedState.scala:39)
	at org.apache.spark.sql.hive.HiveSharedState.metadataHive(HiveSharedState.scala:38)
	at org.apache.spark.sql.hive.HiveSharedState.externalCatalog$lzycompute(HiveSharedState.scala:46)
	at org.apache.spark.sql.hive.HiveSharedState.externalC
```

I try to know what I done is wrong, and why I can't use sparklyr to connect to Cassandra.
I have check that the Cassandra connector is loaded with following error occurred:

```
cass_df <- invoke(sparkSession, "read") %>>% 
  invoke("format", "org.apache.spark.sql.cassandra") %>>% invoke("load")
# Error: java.util.NoSuchElementException: key not found: table
# 	at scala.collection.MapLike$class.default(MapLike.scala:228)
# 	at org.apache.spark.sql.execution.datasources.CaseInsensitiveMap.default(ddl.scala:117)
# 	at scala.collection.MapLike$class.apply(MapLike.scala:141)
# 	at org.apache.spark.sql.execution.datasources.CaseInsensitiveMap.apply(ddl.scala:117)
# 	at org.apache.spark.sql.cassandra.DefaultSource$.TableRefAndOptions(DefaultSource.scala:122)
# 	at org.apache.spark.sql.cassandra.DefaultSource.createRelation(DefaultSource.scala:54)
# 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:315)
# 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:149)
# 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:122)
# 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
# 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
# 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodA
```

Is there some things can be done for connecting to Cassandra?
Thanks.

Otherwise, I succeeded to connect to Cassandra with SparkR, does it help me to use sparklyr?

``` R
library(SparkR)
spark_settings <- list()
sc <- sparkR.session(master = spark_master, 
                     sparkJars = "/usr/local/spark/extraClass/spark-cassandra-connector-assembly-2.0.0-M1.jar")
cass_tbl <- read.df(NULL, source = "org.apache.spark.sql.cassandra",
                 keyspace = "test", table = "kv")
collect(cass_tbl)
#    key value
# 1 key3   6.3
# 2 key2   2.5
# 3 key5  17.0
# 4 key6   5.0
# 5 key1   1.1
# 6 key4   4.7
```

------- update ----------
I don't know why, I restart my computer and it works....

``` R
cass_df_tbl <- sparklyr:::spark_partition_register_df(sc, cass_df, "test_kv", 0, TRUE)

cass_df_tbl %>>% filter(value > 5)
# Source:   query [?? x 2]
# Database: spark connection 
# master=mesos://zk://192.168.0.121:2181,192.168.0.122:2181,192.168.0.123:2181/mesos app=sparklyr # local=FALSE

#     key value
#   <chr> <dbl>
# 1  key3   6.3
# 2  key5  17.0
```

**Comment by peterfig** [comment]
I'm interested in getting this to work too.

Can you get data from Cassandra from your Spark shell?

**Comment by ChingChuan-Chen** [comment]
Please see the update above, it can work now.
In addition, I try sparklyr in another computer and I had encountered the same error, java.lang.reflect.InvocationTargetException. After I reboot the computer, it also works.

@peterfig I can access tables in Cassandra from Spark shell.

**Comment by javierluraschi** [comment]
Can this issue be closed? Or is there anything else blocking this connector?

**Comment by AkhilNairAmey** [comment]
@ChingChuan-Chen, could you please note which versions of spark and cassandra you are using? Am having trouble getting this to work.

**Comment by ChingChuan-Chen** [comment]
I was using Cassandra 2.2.7 and Spark 2.0.0. The problem is solved after restarting computers.

**Comment by prbhadra** [comment]
Hi,
I am new to Spark and Cassandra integration using R. I am wandering how do we pass the cluster IP, user ID and password to connect to a specific keyspace.

I am ok until here 👍 
sc <- sparkR.session(master = "local"", 
                     sparkJars = ""
> sc <- sparkR.session(master = "local", 
+                      sparkJars = "//spark2.1//jars//spark-cassandra-connector_2.10-2.0.0-RC1.jar")

The snippet with sparkly is pretty detailed, however the syntax of passing the uid and password is not mentioned.

Please help me in setting the connection with the steps i need to follow.

**Comment by peddollakishore** [comment]
Hi All

i am connected to spark standalone cluster but when i am importing data from cassandra its keep on waiting stage please help on this, bellow is the code..

library(pipeR)
library(sparklyr)
library(dplyr)

Sys.setenv(SPARK_HOME='/home/ubuntu/spark')
sc <- spark_connect(master = "spark://XXXXXXXXX:7077")
Executed

sparkSession <- invoke_static(sc, "org.apache.spark.sql.SparkSession", "builder") %>>%
invoke("config", "spark.cassandra.connection.host", "XXXXXXXX:9042") %>>%
invoke("getOrCreate")
Executed

cass_df <- invoke(sparkSession, "read") %>>%
invoke("format", "org.apache.spark.sql.cassandra") %>>%
invoke("option", "keyspace", "test") %>>% invoke("option", "table", "kv") %>>%
invoke("load")
Executed

bbh_tbl <- sparklyr:::spark_partition_register_df(sc, cass_df, "bbh", 1, TRUE)
Waiting...........
