### ISSUE TITLE
Support for regParam and weightCol in GLM

### ISSUE THREAD

**Issue by slopp** [rstudio/sparklyr#207]
Add additional parameters to ml_generalized_linear_regression to support the regParam and weightCol optional arguments.

**Comment by kevinushey** [comment]
I just added something that should enable this for 'power users' -- you can now pass something like:

```
ml.options <- ml_options(
    model.transform = function(model) {
        model %>% invoke("setRegParam", 0.25)
    }
)
ml_generalized_linear_regression(..., ml.options = ml.options)   
```

Basically, `model.transform` is just a user-defined function that accepts a Spark model object, and returns a Spark model object. This allows you to access / change things on the model that aren't provided directly by the `sparklyr` API.

**Comment by kevinykuo** [comment]
Implemented as of 0.6.

**Comment by seanzian** [comment]
regParam is the Lambda, am i correct? what about the Alpha? how can we specify Alpha? Thanks.

**Comment by benmwhite** [comment]
@seanzian That option [doesn't appear to be available in MLlib's GLM implementation at this point](https://spark.apache.org/docs/2.4.0/api/scala/index.html#org.apache.spark.ml.regression.GeneralizedLinearRegression).

I would dig through the Spark [Jira page](https://issues.apache.org/jira/projects/SPARK/issues/) to look for GLM-related issues and consider opening a new feature request there if there isn't one open already.
