### ISSUE TITLE
spark_read_source for cassandra

### ISSUE THREAD

**Issue by antonioparry** [rstudio/sparklyr#2070]
# Reporting an Issue with sparklyr
Hi All,

I've just updated sparklyr from 0.9.0 to the latest release 1.0.2 and find out a problem reading cassandra tables from sparlyr.

I was working in a project and use to retrieve data from cassandra like:
tablename <- spark_read_source(sc, "tablename",
                                           "org.apache.spark.sql.cassandra",
                                           list(keyspace = "keyspace", table = "tablename", "spark.cassandra.connection.host" = cassandrahost),
                                           memory = FALSE)

But since update the packet i'm getting the following error: 
Error: java.lang.Exception: No matched method found for class org.apache.spark.sql.DataFrameReader.format

After several hours trying to find out the problem, i've seen that a change was introduce in the function spark_read_source().

Could you please help me to retrieve cassandra tables in another way or find a way to come back to the old function,

thanks in advance

**Comment by javierluraschi** [comment]
Would something like this work? It's been a while since we last tried connecting to Cassandra:

```
sc <- spark_connect(master = "local", version = "2.3", config = list(
  sparklyr.connect.packages = "datastax:spark-cassandra-connector:2.3.1-s_2.11"))

spark_read_source(
  sc, 
  name = "emp",
  source = "org.apache.spark.sql.cassandra",
  options = list(keyspace = "dev", table = "emp"),
  memory = FALSE)
```

**Comment by javierluraschi** [comment]
The code above produces:

```
Error: java.io.IOException: Failed to open native connection to Cassandra at {127.0.0.1}:9042
	at com.datastax.spark.connector.cql.CassandraConnector$.com$datastax$spark$connector$cql$CassandraConnector$$createSession(CassandraConnector.scala:168)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$8.apply(CassandraConnector.scala:154)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$8.apply(CassandraConnector.scala:154)
	at com.datastax.spark.connector.cql.RefCountedCache.createNewValueAndKeys(RefCountedCache.scala:32)
	at com.datastax.spark.connector.cql.RefCountedCache.syncAcquire(RefCountedCache.scala:69)
	at com.datastax.spark.connector.cql.RefCountedCache.acquire(RefCountedCache.scala:57)
	at com.datastax.spark.connector.cql.CassandraConnector.openSession(CassandraConnector.scala:79)
	at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:111)
```

Which is trying to connect to Cassandra, I just don't have one configured at the moment.

**Comment by antonioparry** [comment]
Thanks @javierluraschi  for your quick response, my problem with this method is loading the spark context getting the following error:
```
sc <- spark_connect(master = "local", version = "2.3", config = list(sparklyr.connect.packages = "datastax:spark-cassandra-connector:2.3.1-s_2.11"))
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'C:\Users\user\AppData\Local\Temp\RtmpiArYPf\file4f3862bd3aec_spark.log': Permission denied
```
However, I'm able to connect to spark without the config param:
`sc <- spark_connect(master = "local", version = "2.4.3")`

But also, the parameters i used to pass to the function were: 
`spark_read_source(
  sc, 
  name = "tablename",
  **format**= "org.apache.spark.sql.cassandra",
  options = list(keyspace = "dev", table = "emp"),
  memory = FALSE)`
Note that the parameter format has been deleted in next releases and be change to source and path.

I can't access the code of the function i was using and don't know how to do it. Maybe if i could, i would be able to develop my own function from the old code although the best could be to rescue the old code of the function and add a new function that could be complementary of the new one or even add a specific function for cassandra as the old function was working as expected with cassandra.

**Comment by antonioparry** [comment]
For interest purposes, i've solved the problem installing under windows: 
```
sparklyr 0.9.0
spark 2.3.2  
spark-cassandra-connector-2.3.1-s_2.11 
cassandra 2.4
```
and i'm able to connect R-Spark-cassandra with the following code:

`sc <- spark_connect(master = "local")
tablename <- spark_read_source(sc, "tablename",
                                     source = "org.apache.spark.sql.cassandra",
                                     list(keyspace = "keyspacename", table = "tablename", "spark.cassandra.connection.host" = "127.0.0.1 or your cassandraIP"),
                                     memory = FALSE)`

Hope this helps.

**Comment by abdkumar** [comment]
> For interest purposes, i've solved the problem installing under windows:
> 
> ```
> sparklyr 0.9.0
> spark 2.3.2  
> spark-cassandra-connector-2.3.1-s_2.11 
> cassandra 2.4
> ```
> 
> and i'm able to connect R-Spark-cassandra with the following code:
> 
> `sc <- spark_connect(master = "local")`
> 
> ```
> tablename <- spark_read_source(sc, "tablename",
>                                      source = "org.apache.spark.sql.cassandra",
>                                      list(keyspace = "keyspacename", table = "tablename", "spark.cassandra.connection.host" = "127.0.0.1 or your cassandraIP"),
>                                      memory = FALSE)
> ```
> 
> Hope this helps.

how to connect to remote cassandra with credentials in sparklyr?
