### ISSUE TITLE
Create R date from string by dplyr::mutate

### ISSUE THREAD

**Issue by abrahamdu** [rstudio/sparklyr#2072]
When I use Sparklyr and dplyr to create a R date variable from a string, the return value is always NA. Can you help me with this? I don't have a replicable example for you but try my best to show the process.

The raw field was read into Spark from a parquet file:

a <- spark_read_parquet(sc, name = "a", "/blahblah")

There is a field called 'period' with value like this and it is a string:

01JAN19
02JAN19
03JAN18
....

I use the following to create a new field called 'dt_period' to convert string to R date so that I can compare different dates:

a <- a%>%
            mutate(dt_period= to_date(period,"%d%b%y"), year_period = year(dt_period)) 

When I pull 10 records to double check, it gives me errors:

a %>% 
  select(period,dt_period,year_period) %>% compute() %>% sample_n(10) %>% collect

The two newly created fields show 'NA' as their value.

I also tried dmy function from lubridate package but failed:

a %>% 
mutate(dt_period = dmy(period), year_period = year(dt_cur_period))

Log:
Error : org.apache.spark.sql.AnalysisException: Undefined function: 'DMY'. This function is neither a registered temporary function nor a permanent function registered in the database 'default'.; line 4 pos 3361
	at org.apache.spark.sql.catalyst.analysis.Analyzer$LookupFunctions$$anonfun$apply$15$$anonfun$applyOrElse$50.apply(Analyzer.scala:1396)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$LookupFunctions$$anonfun$apply$15$$anonfun$applyOrElse$50.apply(Analyzer.scala:1396)
	at org.apache.spark.sql.catalyst.analysis.package$.withPosition(package.scala:53)
	at 
I also tried spark_apply():

a <- a%>%
                   spark_apply(function(dff) dplyr::mutate(dff, dt_period = lubridate::ymd(period), year_period = year(dt_period)))

Log:

Error : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 12.0 failed 4 times, most recent failure: Lost task 0.3 in stage 12.0 (TID 295, 10.139.64.7, executor 3): java.lang.Exception: sparklyr worker rscript failure with status 255, check worker logs for details.
	at sparklyr.Rscript.init(rscript.scala:106)
	at sparklyr.WorkerApply$$anon$2.run(workerapply.scala:116)

Can you please help me to correctly create that date field?

**Comment by javierluraschi** [comment]
```r
writeLines("01JAN19\n02JAN19\n03JAN18", "dates.txt")

lirbary(sparklyr)
sc <- spark_connect(master = "local")

spark_read_text(sc, "dates.txt") %>%
  dplyr::mutate(
    month = switch(regexp_replace(line, "[0-9]", ""), JAN = 1, FEB = 2, MAR = 3),
    date_raw = regexp_replace(line, "[a-zA-Z]+", paste0("-0", as.integer(month), "-")),
    date = from_unixtime(UNIX_TIMESTAMP(date_raw, 'dd-MM-yy'))
  )
```
```
# Source: spark<?> [?? x 4]
  line    month date_raw date               
  <chr>   <dbl> <chr>    <chr>              
1 01JAN19     1 01-01-19 2019-01-01 00:00:00
2 02JAN19     1 02-01-19 2019-01-02 00:00:00
3 03JAN18     1 03-01-18 2018-01-03 00:00:00
```

**Comment by abrahamdu** [comment]
Thanks a lot for prompt help.

I used your first way to try but getting the following error:

Error in UseMethod("escape") :
Error in UseMethod("escape") : 
  no applicable method for 'escape' applied to an object of class "function"
In addition: Warning message:
Named arguments ignored for SQL SWITCH 

Any ideas?

BTW, why lubridate::dmy or to_date won't work here?

**Comment by abrahamdu** [comment]
I actually find out if I use Spark SQL date function to_date and parsing my data through its corresponding format, in this case "ddMMMyy" could correctly give me R date.

With this, I will close this issue.
