### ISSUE TITLE
Read csv file with column values containing comma by using spark_read_csv

### ISSUE THREAD

**Issue by abrahamdu** [rstudio/sparklyr#2077]
I am using spark_read_csv function to read my csv file into R. However, some of columns contain comma itself which made the data read through incorrectly.

Here is a snapshot of my data:

100005870186,B,C,01NOV05,1,0,1,0,23,5.5,217876.2,1,"BANK OF AMERICA, N.A.",5.5,"223,000.00",

You can see "BANK OF AMERICA, N.A." and "223,000.00" containing comma while covered by quotation marks. 

Is there a way to correctly read this into R by spark_read_csv?

**Comment by nik-maheshwari** [comment]
Can you show your command?
I was able to read that particular line with no problem -
`test <- spark_read_csv(sc, "test", "~/test.txt")`

**Comment by abrahamdu** [comment]
I eventually corrected the raw input file and read in.
