### ISSUE TITLE
spark_apply always try to infer columns type

### ISSUE THREAD

**Issue by gbouzill** [rstudio/sparklyr#2081]
When I try to run script based on spark_apply, it seems that it always try to infer types of columns even if I specificy the types in the "columns" argument : 

```
res <- spark_apply(tbl_spark, function(df) {
 ... R code ...
},
group_by = c("var1", "var2"),
columns = c("col1" = "Date", "col2" = "numeric"))
```

The problem is that the R code inside can't be executed on the first 10 rows.
According to the documentation, specifying columns types should avoid column's types inference.

Is there something I missunderstood ?

P.S : for those who experience the same kind of problem, i use an ugly workaround for the moment. I added an if/else condition inside R code to test if the df variable has 10 rows (i.e., the inference step). This allow me to return a fake data.frame with columns types consistent with the types specified in the "columns" argument.

**Comment by gbouzill** [comment]
Ok I found the solution. column's types must be passed in a list instead of a named vector. Grouping variables types must be specified as well.

**Comment by Loquats** [comment]
@gbouzill I am having the same issue. Could you please post an example of the solution you found? (passing column types as list)

I tried using a list likes this:
```
columns <- list("character", "numeric", "numeric")
names(columns) <- c("col_a", "col_b", "col_c")
```
but spark_apply still attempts to infer the column types.
