### ISSUE TITLE
sparklyr support for Databricks-Connect?

### ISSUE THREAD

**Issue by kohleth** [rstudio/sparklyr#2088]
Databricks recently released Databricks-connect, which allow rstudio to execute spark job on a remote databricks spark cluster.
https://docs.azuredatabricks.net/user-guide/dev-tools/db-connect.html
However, currently they only support SparkR. 
I wonder if there is an easy way to configure sparklyr to utilize this feature?

**Comment by javierluraschi** [comment]
Thanks, yes, something we were already planning to investigate. We'll close this one and track progress with https://github.com/rstudio/sparklyr/issues/2089 instead.
