### ISSUE TITLE
convert character to numeric

### ISSUE THREAD

**Issue by abrahamdu** [rstudio/sparklyr#2090]
I use spark_read_csv to read the raw data into Spark but one field was character?

"110,000.00"

I want to convert it into number since it means dollar amount but had hard time to decode it correctly? Is there a way to do so?

So I expect to get the field containing value just like this:

110000

**Comment by javierluraschi** [comment]
Use the `columns` parameter, for instance:

```
library(sparklyr)
sc <- spark_connect(master = "local")

data.frame(x = letters, y = 1:length(letters)) %>%
   write.csv("data-csv.csv", row.names = FALSE)

schema <- sapply(read.csv("data-csv.csv", nrows = 10), class)

# change in schema column from char to integer

spark_read_csv(sc, "data-csv.csv", columns = schema)
```

Alternatively, you can use `dplyr::mutate(int_col = as.integer(char_col))`.

**Comment by abrahamdu** [comment]
Thanks again for your help. 

I also find using this works as well:

dplyr::mutate(oupb = as.numeric(str_replace_all(original_balance, ",", "")))

I will close this issue.
