### ISSUE TITLE
Use R functions in Sparklyr

### ISSUE THREAD

**Issue by abrahamdu** [rstudio/sparklyr#2092]
I am researching how to use R function on line but still have hard time figuring out. Please help.

My initial code looks like:

whatever %>% 
  group_by(a) %>%
  summarize(count=n()) %>%
  collect() %>%
  ggplot(aes(x=a, y=count)) +
  geom_point()

I want to repeat this multiple times since there are other columns I want to check with the same function.

So I wrote:

point_dist <- function(dta, vari) {
  dta %>% 
  group_by(vari) %>%
  summarize(count=n()) %>%
  collect() %>%
  ggplot(aes(x=vari, y=count)) +
  gemo_point()
}

point_dist(whatever, a)

but keep telling me:

Error in eval_bare(sym, env) : object 'a' not found

Don't know why.

I either don't know if this is the right direction I shall go.

Thanks again.

**Comment by javierluraschi** [comment]
You can get help on R and `tidyverse` questions here: http://community.rstudio.com -- Closing this one since seems not Spark + R related.

**Comment by benmwhite** [comment]
@abrahamdu Specifically look for RStudio community forum topics and issues related to "tidy evaluation" for the explanation behind your particular error message.
