### ISSUE TITLE
Manually create model estimate for scoring

### ISSUE THREAD

**Issue by abrahamdu** [rstudio/sparklyr#2095]
I have a logistics model estimate done by other language, SAS and want to use Sparklyr's ML component to score large data.

This is a code template I use in Sparklyr to score data.

glm_model <- training %>%
               ml_logistic_regression(a~.)

esti_training <- ml_predict(glm_model, training)

Do you think I can manually create the information from SAS and use ml_predict for scoring?

**Comment by javierluraschi** [comment]
@abrahamdu yeah, you should. To read the SAS files, consider using this extension: https://github.com/r-spark/spark.sas7bdat

**Comment by abrahamdu** [comment]
works for me thanks!
