### ISSUE TITLE
Error in rawToChar(raw)

### ISSUE THREAD

**Issue by hanfernandes** [rstudio/sparklyr#2102]
I am trying to read a file using the spark_read_csv function with 14 million rows and 300 columns. After reading the file, I cannot view the data like this:

```r
df_full %>% glimpse
```
```
Observations: ??
Error in rawToChar(raw) : 
  embedded nul in string: 'NL3\031N\0L\031\0\0L\031\0L\031N\031\0L\031O\031O\0\031O\031O\0\031N\031N\031\0L\031G3\031N\0\031\0L\031\0L\031<NA>\031<NA>\031N\031\0L\0319\031N9\0L\031N\031N\031<NA>\031'
```

```r
df_full %>% head()
```
```
Error in rawToChar(raw) : 
  embedded nul in string: 'NL3\031N\0L\031\0\0L\031\0L\031N\031\0L\031'
```

I did this same reading using pyspark and it worked at the time of displaying the data. 

Does anyone know why this error?

 I am using Spark version 2.4.2.

> R version 3.6.1 (2019-07-05)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Amazon Linux AMI 2018.03
> 
> Matrix products: default
> BLAS:   /usr/lib64/R/lib/libRblas.so
> LAPACK: /usr/lib64/R/lib/libRlapack.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] dplyr_0.8.3         sparklyr_1.0.2.9000

**Comment by javierluraschi** [comment]
@hanfernandes your could try using `spark_read_text()` and then `head()` to load as text, this would probably work. You could then get the schema by saving the `head()` with `writeLines()` and then load the schema and use the schema.

```
library(sparklyr)

sc <- spark_connect(master = "local")
write.csv(mtcars, "cars.csv")

subset <- spark_read_text(sc, "cars.csv") %>% head() %>% dplyr::collect()
writeLines(subset$line, "subset.csv")

schema <- read.csv("subset.csv") %>% lapply(class)

spark_read_csv(sc, "cars.csv", columns = schema) %>% head()
```

Does this approach work?

Would it be possible for you to share the `schema` with us to investigate further?

Thanks!

**Comment by hanfernandes** [comment]
This approach is perfect! It's work.

Thank so much!
