### ISSUE TITLE
pmin and pmax are unsupported

### ISSUE THREAD

**Issue by magarick** [rstudio/sparklyr#211]
Using pmin or pmax to get the elementwise minima or maxima of two columns does not work with a Spark backend. The following code works when using a plain R backend (and I believe most databases too).

`df_test <- data.frame(x=c(1, 2, 3), y=c(2, 1, 2))
df_test %>% mutate(pmin(x,y)) `

However, the following code with the same data in Spark does not.

`sc = spark_connect(master='local')
copy_to(sc, df_test)
sdf_load_table(sc, 'df_test') %>% mutate(pmin(x,y)) 
`

The error comes from Spark itself in Scala. The first line of the stack trace is
`Error: org.apache.spark.sql.AnalysisException: Invalid number of arguments for function min; line 2 pos 23`

With the help of some wiser Spark folks, I see that the min and max functions in Spark expect only one argument. Since the SQL generated by pmin and pmax uses MIN and MAX, I'm not sure where the fix should occur. Thanks for any help.

**Comment by kevinushey** [comment]
We could probably add a function to support this. That said, 

```
df_tbl %>%
  mutate(z = ifelse(x < y, x, y))
```

should work okay now for the two variable case.

**Comment by magarick** [comment]
Thanks! Solution works well.
