### ISSUE TITLE
spark_apply errors when writing to log

### ISSUE THREAD

**Issue by CRWrangler** [rstudio/sparklyr#2110]
I'm trying to create GLMMs using spark_apply.  Despite ensuring that the output is a dataframe, I am getting errors when I run the spark_apply related to the log.  I think this is due to warning text which is generated by the call to glmmPQL which triggers spark to create a log.  I've tried all the solutions I've found online such as installing sparklyr from github.  Please help!  

```r
spark_version <- Spark 2.4.3 for Hadoop 2.7 or later already installed.
sc <- spark_connect(master="local")  ....

# this helper function calls glmmPQL and returns the coefficients in a data frame
helper <- function(data){
  attach(data)
  all <- summary(glmmPQL(Good ~ Balance, family = binomial, random = ~1|Research))
  output<-as.data.frame(rbind(t(rbind(all$coefficients$fixed)), t(rbind(all$coefficients$random$Research[,1]))))
  
  return(output)
}

spark_apply(subset_table,
            function(e) helper(e))

**Error message:**
Warning message:
In file(con, "r") :
  cannot open file 'C:\Users\XXXX\AppData\Local\Temp\RtmpWum9H9\file258023661abd_spark.log': Permission denied

**Comment by javierluraschi** [comment]
@CRWrangler When using Windows, this error can be encountered due to inability from Windows to read a file that a different process (Spark) is writing. One workaround to see the output is to connect using the `config$sparklyr.log.console = TRUE` setting.

To fix your script, it needs to fully qualify libraries, as in `MASS::glmmPQL`, you also don't need to wrap the transformation function into `function(e) helper(e)`, `helper` is sufficient, this script works for me:

```r
library(sparklyr)

sc <- spark_connect(master = "local")
subset_table <- copy_to(sc, subset)

subset <- data.frame(Good = runif(10), Balance = runif(10), Research = runif(10))

helper <- function(data){
    attach(data)
    all <- summary(MASS::glmmPQL(Good ~ Balance, family = binomial, random = ~1|Research))
    output<-as.data.frame(rbind(t(rbind(all$coefficients$fixed)), t(rbind(all$coefficients$random$Research[,1]))))
    
    return(output)
}

spark_apply(subset_table, helper)
```
```
# Source: spark<?> [?? x 1]
          V1
       <dbl>
 1  1.02e+ 0
 2 -1.59e+ 0
 3 -2.21e- 9
 4 -1.56e- 9
 5  1.80e- 9
 6  6.08e-10
 7  8.73e-10
 8 -6.66e-10
 9 -1.82e- 9
10  2.12e- 9
# … with more rows
```

**Comment by CRWrangler** [comment]
Works for me too, thanks very much for the very quick help!
