### ISSUE TITLE
It might be convenient for users to be able to cache SparkDataFrame directly

### ISSUE THREAD

**Issue by teramonagi** [rstudio/sparklyr#2115]
It might be convenient for users to be able to cache SparkDataFrame directly because users do n’t have to worry about a temporal table name.

Pseudo code is like:
### AS-IS
```r    
sdf <- sparklyr::sdf_sql(sc, "select 1")
sparklyr::sdf_register(sdf, "tmp")
sparklyr::tbl_cache(sc, "tmp")
```

### TO-BE
```r
sdf <- sparklyr::sdf_sql(sc, "select 1")
sparklyr::tbl_cache(sdf) 
# or using new function, sparklyr::tbl_cache_sdf(sc, sdf)
```

Does this make sense?
If so, I will implement.

**Comment by teramonagi** [comment]
Should we forcibly call (not exported) this process?
https://github.com/rstudio/sparklyr/blob/6963e1d9db6d4c6534dd78baf87b5f8f6dc505bb/R/tables_spark.R#L20

Or, as [described here](https://github.com/rstudio/sparklyr/blob/6963e1d9db6d4c6534dd78baf87b5f8f6dc505bb/R/tables_spark.R#L57-L60), is this kinda operation contrary to sparklyr's philosophy?

**Comment by benmwhite** [comment]
I've been using `dplyr::compute("table_name")` at the end of my pipes if I want to save the results to memory immediately. 

Does this do something different from registering and then caching the query? They show up with my specified names and exist in-memory on the executors.

**Comment by teramonagi** [comment]
It must be a nice way to write.
But what I wanna do is to write a code that processes without giving a temporal name in the data pipeline.

e.g.
```r
sdf <- sparklyr::sdf_sql(sc, "select 1") %>%
  # Cache directly and return SparkDataFrame object
  sparklyr::tbl_cache() 

sdf %>%
  dplyr::select(x) %>%
  dplyr::filter(x >= 10)
....
```

**Comment by benmwhite** [comment]
Instead of naming it inside `compute()` you can use `compute()` at the end and save it as an R object instead. When I do this it generates a random string for the table name in Spark but I can just use the R object's name to reference the same cached table.

I guess I'm a little confused because this seems to do the same thing you're trying to do in the examples:

```
sdf <- sdf_sql(sc, "select 1") %>% compute()
sdf %>%
  select(x) %>%
  filter(x >= 10)
```

**Comment by teramonagi** [comment]
Ah, I understood it completely.

`dplyr::compute()` is calling `sparklyr:::db_save_query.spark_connection()` on the inside.

https://github.com/rstudio/sparklyr/blob/dfeba30bc7f5bd35ae37bf2a285e7d230f6c0626/R/dplyr_spark.R#L127

So, `dplyr::compute()` automatically cache the `sdf` object, perfect strategy!!!
