### ISSUE TITLE
Model Deployment

### ISSUE THREAD

**Issue by dwy904** [rstudio/sparklyr#212]
I am wondering if it is possible to provide the sample code of ML model deployment on the web from the local cluster ?

**Comment by javierluraschi** [comment]
@dwy904 could you be more specific of what "ML model deployment on the web" you are referring to? Is this perhaps related to provide a way to run an "ML model" at scale, using AWS or similar online technologies?

**Comment by javierluraschi** [comment]
Planning to consider model deployments, examples and docs as part of https://github.com/rstudio/sparklyr/issues/944, closing this one.

**Comment by kevinykuo** [comment]
@dwy904 we now have better support for saving/loading models. This should help with deploying models in "batch" mode. If you're looking to making real-time predictions (e.g. POST a row of data and get a prediction back) that's something Spark doesn't support natively but we're looking into making that easier for R users.
