### ISSUE TITLE
Calculation between integer and double dplyr

### ISSUE THREAD

**Issue by abrahamdu** [rstudio/sparklyr#2122]
I have two columns and want to do calculation but one is integer and the other is double. When I subtract one from the other and it gives me error.

```r
dplyr::mutate(ltv_chg = as.integer(current_ltv - original_ltv)) %>%
```

```r
Error : org.apache.spark.sql.AnalysisException: cannot resolve '(-50.0BD - CAST(tbzwykwcmx.`ltv_chg` AS DECIMAL(10,0)))' due to data type mismatch: differing types in '(-50.0BD - CAST(tbzwykwcmx.`ltv_chg` AS DECIMAL(10,0)))' (decimal(3,1) and decimal(10,0)).; line 14 pos 4746;
```

Any ideas?

**Comment by benmwhite** [comment]
Why not convert one of the columns first? You can do it inside the `mutate()` call.

**Comment by abrahamdu** [comment]
I tried it as well and failed again.

Looks like it is more an issue of Azure itself rather than R's issue. Close this.
