### ISSUE TITLE
Issue with spark_apply and R 3.6.0

### ISSUE THREAD

**Issue by djturpen** [rstudio/sparklyr#2135]
I am having an issue using spark_apply on R.3.6.0. Tested it on R 3.5.3 and didn't have the issue.

Here is the spark connection string I am using: sc <- spark_connect(master = "yarn-client", source="opt/cloudera/parcels/CDH6.3.0-1.cdh6.3.0.p0.1279813/lib/spark/bin/spark-submit", version="2.4.0")

Here is the spark_apply code: sdf_len(sc, length = 5, repartition =1 %>% spark_apply(function(e) I(e))

The error R Studio shows is: java.lang.Exception: sparklyr worker rscript failure with status 255, check worker logs for details

The error the worker log shows is: ERROR sparklyr: RScript (3923) terminated unexpectedly: cannot read workspace version 3 written by R 3.6.0; need R 3.5.0 or newer

Other sparklyr functions seem to run without issue. Any idea what could be causing this?

**Comment by robin-loche** [comment]
Have you also updated R on your workers?

**Comment by djturpen** [comment]
> Have you also updated R on your workers?

You are correct. That was the issue. Silly mistake on my part. Thanks for the suggestion.
