### ISSUE TITLE
How to create a new column with spark_apply

### ISSUE THREAD

**Issue by Scotturbina** [rstudio/sparklyr#2160]
Hello,

I was trying to test some spark_apply features, since I need some features based on Part of speech tagging, I am trying with something very easy as applying the spark_apply function.

What I want to understand is how to create a new column in my dataframe using spark_apply, I try with this but seems not working 

```
require(sparklyr)
require(dplyr)
require(tidyr)

# Create sparklyr connection

sc <- spark_connect(master = "local")

df <- sdf_len(spark, 1000000)
df <- sdf_repartition(df, 5)%>%
    spark_apply(function(df){
  df['new']<-df*10

})

df

```

When I print the df seems that it is not creating the new column.

Definitely it is something I am doing wrong, can anybody help me?

Thank you

Regards

**Comment by benmwhite** [comment]
Your function as written in the example doesn't produce any output, add the line  `return(df)` inside the function and see if that fixes it.

**Comment by javierluraschi** [comment]
```r
library(sparklyr)
sc <- spark_connect(master = "local")

df <- sdf_len(sc, 100)
df <- sdf_repartition(df, 5) %>%
    spark_apply(function(df){
      df['new']<-df$id * 10
      df
    })

df
```

However, try not to use `spark_apply()`, it's meant to for advanced use cases! If you do, consider using `arrow`. What you most likely want to do is to use `dplyr`:

```r
library(sparklyr)
sc <- spark_connect(master = "local")

sdf_len(sc, 100) %>%
  dplyr::mutate(new = id * 10)
```

It is much easier and efficient to use `dplyr`.

**Comment by Scotturbina** [comment]
Thanks @javierluraschi  and  @benmwhite  for the explanation
