### ISSUE TITLE
ml_linear_regression regression weights

### ISSUE THREAD

**Issue by sabraham** [rstudio/sparklyr#217]
Can we add a regression weights parameter to `ml_linear_regression`, similar to the `weights` parameter in `lm()` in the base R package?

**Comment by kevinushey** [comment]
It looks like the Spark APIs here do allow users to set a 'weight' column; I'll have to see if this maps as we expect to R's `lm` weights argument.

**Comment by hcasas1981** [comment]
Here's how I did it, as I commented on SO. I added `weightCol` parameter to the function, and invoked Spark's `setWeightCol` within the function, if weightCol is not null. I don't know if you'd do it differently, but it works and in a number of tests I ran, the results mirror those of `R` base `lm`.

Here's the couple of changes. 

Function definition.

```
ml_linear_regression_w <- function (x, response, features, intercept = TRUE, alpha = 0, 
	lambda = 0, iter.max = 100L, ml.options = ml_options(), weightCol = NULL,
	...) 
```

And invoke `setWeightCol`
```
	if (!is.null(weightCol))
			model <- model %>% invoke("setWeightCol", as.character(weightCol))

```

**Comment by kevinykuo** [comment]
@hcasas1981 Awesome! Couple suggestions:

1. Call `ensure_scalar_character` on the input

2. Use `weights_column` to be consistent with naming of arguments throughout package

Btw here's the SO http://stackoverflow.com/q/43669693/2835778... and just in case, don't confuse me with @kevinushey; I'm not a wizard :P
