### ISSUE TITLE
IDE SparkUI button gives error

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/sparklyr#219]
I see this on both:
- RStudio Server Version 0.99.1259 on EMR 5.0 Cluster
- RStudio Desktop Version 1.0.16 (on Mac) 

- Make a connection to Spark
- In the Spark tab of IDE click on SparkUI. This error is reported:

```
Error in regexec(".*Bound SparkUI to.*and started at (http.*)", uiLine,  : 
  unused argument (perl = TRUE)
```

**Comment by jjallaire** [comment]
Which version of R are you running? (I'm wondering if the perl = TRUE
argument was introduced in a later R release)

**Comment by fereshtehRS** [comment]
On Mac: ‘3.2.3’

On cluster: ‘3.2.2’
