### ISSUE TITLE
n_distinct does not accept more than one column

### ISSUE THREAD

**Issue by ssoulier** [rstudio/sparklyr#220]
In this example, I am using first `dplyr` on a **data frame** and the same code on a **spark table**.
I have the error `Error in n_distinct(Petal_Length, Petal_Width) : unused argument (Petal_Width)` with the spark version

```R
library(sparklyr)

sc = spark_connect(master = "local")
iris_df = iris
iris_spark = copy_to(sc, iris, "iris_spark")

iris_df %>% 
  group_by(Species) %>% 
  summarise(count_unique = n_distinct(Petal.Length, Petal.Width))

iris_spark %>% 
  group_by(Species) %>% 
  summarise(count_unique = n_distinct(Petal_Length, Petal_Width))
```

**Comment by ssoulier** [comment]
Is there any reason that in Spark we can't use more than one variable in `n_distinct` ?

**Comment by kevinushey** [comment]
I think the issue here is simply that `n_distinct` is not implemented for remote sources -- `dplyr` provides `n_distinct` currently only for local data frames. I think it should be possible for us to add this ourselves, however.
