### ISSUE TITLE
extract resulting latent factors from ALS implementation ml_als

### ISSUE THREAD

**Issue by ChristelSwift** [rstudio/sparklyr#2201]
using a modified ALS example from the sparklyr documentation so that we have 3 users and 4 items:
```
library(sparklyr)
sc <- spark_connect(master = "local")

# 3 users, 4 films:
movies <- data.frame(
  user   = c(1, 1, 1, 1, 2, 2, 3, 3, 3, 3),
  item   = c(1, 2, 3, 4, 1, 2, 1, 2, 3, 4),
  rating = c(3, 1, 2, 5, 1, 5, 1, 1, 5, 4)
)
movies_tbl <- sdf_copy_to(sc, movies, overwrite = TRUE)
movies_tbl <- sdf_copy_to(sc, movies)

model <- ml_als(movies_tbl, rating ~ user + item)
```
How can you then extract the resulting latent user and item factors from the model?

**Comment by benmwhite** [comment]
Check `str(model)`, you'll should see something like `model$user_factors` and `model$item_factors` that point to cached Spark data sets with the results you want.

**Comment by ChristelSwift** [comment]
hi Ben, i had thought of `str` and wish it was that simple but it brings back a very long list and you can't just call `model$user_factors` as it brings back NULL.  

I think i got closer with:

```
model_tidy <- tidy(model) %>% collect
 model_tidy
# A tibble: 4 x 3
     id user_factors item_factors
  <int> <list>       <list>      
1     1 <list [10]>  <list [10]> 
2     3 <list [10]>  <list [10]> 
3     2 <list [10]>  <list [10]> 
4     4 <lgl [1]>    <list [10]> 
```
so the list element is <lgl[1}> for ids that don't exist in either the user or item list.
