### ISSUE TITLE
How to create an managed Delta table?

### ISSUE THREAD

**Issue by dah33** [rstudio/sparklyr#2208]
How do you create an managed Delta table in Sparklyr? Here's the Spark SQL equivalent of what I am trying to do:

```
CREATE TABLE events
USING delta
PARTITIONED BY (date)
SELECT action, from_unixtime(time, 'yyyy-MM-dd') as date
FROM json.`/databricks-datasets/structured-streaming/events/`;
```

This registers the table in the Hive metastore, and copies the data into Delta format `/user/hive/warehouse/events`.

The closest thing I can find is `spark_write_delta()`, but requires a `path` parameter, and by implication is creating a unmanaged table. Perhaps a solution would be to add a `delta` option to `spark_write_table()`?

I am using sparklyr 1.05.

**Comment by javierluraschi** [comment]
One option is to use SQL with the `DBI` package:

```r
library(sparklyr)
sc <- spark_connect(master = "local", version = "2.4", packages = "delta")

jsonlite::write_json(list(list(action = "a", time = 1575047538), list(action = "b", time = 1575047539)), "input/data.json")

DBI::dbSendQuery(sc, "CREATE TABLE events
  USING delta
  PARTITIONED BY (date)
  SELECT action, from_unixtime(time, 'yyyy-MM-dd') as date
  FROM json.`input`")
```
```
<DBISparkResult>
  SQL  CREATE TABLE events
USING delta
PARTITIONED BY (date)
SELECT action, from_unixtime(time, 'yyyy-MM-dd') as date
FROM json.`input`
  ROWS Fetched: 0 [complete]
       Changed: 0
```

and then `dplyr`,

```r
dplyr::tbl(sc, "events")
```
```
# Source: spark<events> [?? x 2]
  action date      
  <chr>  <chr>     
1 a      2019-11-29
2 b      2019-11-29
```

If you can find an example of registering managed tables in Scala (instead of SQL), we should be able to create a nicer wrapper for you.

**Comment by dah33** [comment]
I can't find anything in the Scala API. I think Delta is too immature. 

I did find you can "import" a delta file, once written, into the metastore:

> If you specify only the table name and location, for example: 

```
CREATE TABLE events
USING DELTA
LOCATION '/delta/events'
```

> the table in the Hive metastore automatically inherits the schema, partitioning, and table properties of the existing data. This functionality can be used to “import” data into the metastore.

However, this isn't a managed table, as if you `DROP` the table, the data is not deleted.

See the [sample notebook](https://docs.databricks.com/_static/notebooks/delta/quickstart-python.html) and the [documentation](https://docs.databricks.com/delta/delta-batch.html#create-a-table).
