### ISSUE TITLE
Change in string formats during copy_to and collect operations on a cluster

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/sparklyr#221]
I am trying a few simple steps to copy flights data into Spark and then collect it back (using `nycflights13` data). Repeating the exact same steps on my local connection to Spark (on Mac), and also on an EMR cluster. The results are different, and problematic in case of cluster. Not sure where/how this change happens.

1) Steps on Mac Spark:

```
> head(nycflights13::flights$origin)
[1] "EWR" "LGA" "JFK" "JFK" "LGA" "EWR"
> copy_to(sc, flights, "flights_s", overwrite = TRUE)
> flights_tbl <- tbl(sc, 'flights_s')
> f <- flights_tbl %>% collect
> head(f$origin)
[1] "EWR" "LGA" "JFK" "JFK" "LGA" "EWR"
```

2) Steps on the EMR Cluster:

```
> head(nycflights13::flights$origin)
[1] "EWR" "LGA" "JFK" "JFK" "LGA" "EWR"
> copy_to(sc, flights, "flights_s", overwrite = TRUE)
> flights_tbl <- tbl(sc, 'flights_s')
> f <- flights_tbl %>% collect
> head(f$origin)
[1] "\"EWR\"" "\"LGA\"" "\"JFK\"" "\"JFK\"" "\"LGA\"" "\"EWR\""
```

Notice how the values of `origin` column has been modified in second case.

**Comment by javierluraschi** [comment]
Thanks @fereshtehRS, we should fix this one before the CRAN checkpoint. Pushing a fix...

**Comment by fereshtehRS** [comment]
Thanks @javierluraschi. Works fine in new version.

**Comment by javierluraschi** [comment]
Thanks for checking this.
