### ISSUE TITLE
SparkUI URL on EMR clusters

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/sparklyr#224]
This might be fine, but logging it for the record.

On the EMR Cluster, from RStudio IDE, Spark tab, open a connection and then click on SparkUI. This opens a browser page to a specific job page using the internal IP:

```
http://ip-10-136-57-4.ec2.internal:20888/proxy/application_1474384079778_0005/
```

This works fine for the current job. But the drawback is that you cannot browser to other jobs from the root URL: http://ip-10-136-57-4.ec2.internal:20888 (this is forbidden).

**Comment by fereshtehRS** [comment]
I should note that in some ways this is a better URL to access. I have been using the UI on port 18080 (e.g. http://ec2-184-72-178-0.compute-1.amazonaws.com:18080) and we had noticed that some of the information is missing from the UI. But on the internal URL we see everything.

**Comment by javierluraschi** [comment]
My take, I don't think we would want to support EMR specific settings appart from the information present in the Spark logs while connecting to EMR. Rather, the system administrator in this case, should set the `sparklyr.sparkui.url` config setting to configure the preferred endpoint for the Spark UI. Sounds reasonable?

**Comment by fereshtehRS** [comment]
Yeah, definitely.
