### ISSUE TITLE
ERROR: dependency 'config' is not available for package 'sparklyr'

### ISSUE THREAD

**Issue by saraswatmks** [rstudio/sparklyr#230]
Hi
I am facing in trouble in installing sparklyr package. I've followed installation steps as guided on tutorial page. I have installed devtools package successfully, but the next step throws error. Don't know where am I missing. Any help?

The downloaded binary packages are in
> devtools::install_github("rstudio/sparklyr")
Downloading GitHub repo rstudio/sparklyr@master
from URL https://api.github.com/repos/rstudio/sparklyr/zipball/master
Installing sparklyr
Skipping 1 unavailable package: config
"C:/PROGRA~1/MICROS~1/MRO/R-33~1.0/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
 \
  --library="C:/Users/manish/Documents/R/win-library/3.3" --install-tests 
**ERROR: dependency 'config' is not available for package 'sparklyr'**
* removing 'C:/Users/manish/Documents/R/win-library/3.3/sparklyr'
Error: Command failed (1)

**Comment by kevinushey** [comment]
It looks like you're using MRO, which I'm guessing is also checkpointed to a CRAN release that does not have the `config` package available.

You'll have to manually install `config` yourself from https://cran.r-project.org/package=config. Or switch yourself to using the RStudio CRAN mirror, with e.g.

    options(repos = c(CRAN = "https://cran.rstudio.com"))

**Comment by saraswatmks** [comment]
Hi Kevin
It worked. Thanks you so much! 
To install config package I had to explicitly mention the repository address: install.packages("config",repos="http://cran.us.r-project.org")

**Comment by kevinushey** [comment]
Great to hear, thanks!
