### ISSUE TITLE
datediff function

### ISSUE THREAD

**Issue by Tarqui** [rstudio/sparklyr#231]
I wrote datediff function. Probably it would be helpfull to add to the code.

http://spark.apache.org/docs/latest/api/scala/#org.apache.spark.sql.functions$

datediff = function(x, y) build_sql("DATEDIFF(day,", x, ",", y,")")

**Comment by kevinushey** [comment]
The `datediff` function is already made available in `sparklyr`, so this change should be unnecessary. You should already be able to call `datediff` within a mutate call, e.g.

```
mutate(diff = datediff(end, start) 
```

**Comment by Tarqui** [comment]
Yes, you are rigth
