### ISSUE TITLE
spark_write_csv function

### ISSUE THREAD

**Issue by Tarqui** [rstudio/sparklyr#232]
spark_write_csv function does not work correctly.

`library(sparklyr)`
`library(dplyr)`
`sc <- spark_connect(master = "local", version = "1.6.2")`
`iris_tbl <- copy_to(sc, iris, "iris", overwrite = TRUE)`
`spark_write_csv(iris_tbl, path = "iris.csv")`

> Error: java.lang.NoSuchMethodError: scala.Predef$.$conforms()Lscala/Predef$$less$colon$less;
> 	at com.databricks.spark.csv.util.CompressionCodecs$.<init>(CompressionCodecs.scala:29)
> 	at com.databricks.spark.csv.util.CompressionCodecs$.<clinit>(CompressionCodecs.scala)
> 	at com.databricks.spark.csv.DefaultSource.createRelation(DefaultSource.scala:189)
> 	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:222)
> 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:148)
> 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:139)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at sparklyr.Handler.handleMethodCall(handler.scala:118)
> 	at sparklyr.Handler.channelRead0(handler.scala:63)

However, writting in json works perfectly

`spark_write_json(iris_tbl, path = "iris.json")`

**Comment by javierluraschi** [comment]
@Tarqui I noticed this post: https://github.com/databricks/spark-csv/issues/325, you could try:

```{r}
conf <- spark_config()
conf$sparklyr.defaultPackages <- c(
  "com.databricks:spark-csv_2.10:1.3.0",
  "com.amazonaws:aws-java-sdk-pom:1.10.34")

sc <- spark_connect(master = "local", config = conf)
iris_tbl <- copy_to(sc, iris, "iris", overwrite = TRUE)
spark_write_csv(iris_tbl, path = "iris.csv")
```

**Comment by Tarqui** [comment]
It worked, it was a version problem. Thank you
