### ISSUE TITLE
Where does sparklyr look for HTTPS certificate authorities?

### ISSUE THREAD

**Issue by m-stanley** [rstudio/sparklyr#233]
I'm getting the following errors when I try to `spark_connect()`:

```
:::: ERRORS
	Server access error at url https://repo1.maven.org/maven2/com/databricks/spark-csv_2.11/1.3.0/spark-csv_2.11-1.3.0.pom (javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target)

	Server access error at url https://repo1.maven.org/maven2/com/databricks/spark-csv_2.11/1.3.0/spark-csv_2.11-1.3.0.jar (javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target)
```

I presume this is because I'm on a network protected by a firewall/antivirus solution that intercepts all HTTPS connections and re-signs them with an internal certificate. I have the internal certificate authority certificate and can add it to the list of accepted authorities - for example, I have to do this with the `openssl` package's cacert.pem file to enable HTTPS in the `httr` package - but I can't find an equivalent file in `sparklyr`. 

Where is `sparklyr`'s list of certificate authorities, so I can amend it?

**Comment by javierluraschi** [comment]
`sparklyr` does not download these files directly, instead, Spark downloads them from their repo.

This looks to me more like a network connection issue. Would downloading them form that machine with `wget  https://repo1.maven.org/maven2/com/databricks/spark-csv_2.10/1.0.3/spark-csv_2.10-1.0.3.pom` work appropiately? I would follow up with you network administrator to understand if a restriction can be removed or follow Spark documentation to install Spark packages manually.

sparklyr uses this package for the `csv_` functions, so as long you don't need to save/load csv files, you could launch sparklyr with:

```{r}
conf <- spark_config()
conf[["sparklyr.defaultPackages"]] <- c()

sc <- spark_connect(master = "local", config = conf)
```

**Comment by m-stanley** [comment]
You're quite right that this is a network connection issue; the issue as I mentioned is that a secure connection can't be established because all HTTPS connections on this network are signed with an internal CA certificate, which isn't recognised by default. wget works, but only because I've added the certificate authority to wget already.

Your answer did point me in the right direction, though, which is that Spark is downloading the files rather than sparklyr. Spark is using the default Java certificate authority library, which can be found at $JAVA_HOME/lib/security/cacerts and new CA certificates can be added to this file using the Java keytool.

Thanks.

**Comment by javierluraschi** [comment]
@m-stanley Great! Thanks for sharing the solution here, other users will find this really helpful!
