### ISSUE TITLE
Dplyr query in tutorial not the same as on a data.frame

### ISSUE THREAD

**Issue by apapiu** [rstudio/sparklyr#236]
Going over the tutorial [here](http://spark.rstudio.com/#rstudio-ide) and noticed that running this on sparklyr:

```
delay <- flights_tbl %>% 
  group_by(tailnum) %>%
  summarise(count = n(), dist = mean(distance), delay = mean(arr_delay)) %>%
  filter(count > 20, dist < 2000, !is.na(delay)) %>%
  collect()
```

Gives different results from:

```
flights_tbl  %>% collect() -> flights_df

delay_df <- flights_df %>% 
    group_by(tailnum) %>%
    summarise(count = n(), dist = mean(distance), delay = mean(arr_delay)) %>%
    filter(count > 20, dist < 2000)
```

It seems to be because the mean in spark has something like `na.rm = TRUE` by default.

**Comment by kevinushey** [comment]
Indeed, the issue here is that Spark defaults to something like `na.rm = TRUE` for all arithmetic / mathy operations. The results are the same if I force `na.rm = TRUE` on the R equivalent code.

I don't know if there's anything we can do to change this behavior; I imagine we'll just have to make sure it's clearly documented. @javierluraschi, what do you think?

**Comment by javierluraschi** [comment]
Took a look at this... couldn't find any simple way yo reconfigure this behavior to match R to set mean to `NA` when `NA` values are present. Users of `sparklyr` will have to become aware there are differences in behavior between R and Spark, in this case, for `NA`s. This is already the case for `dplyr` where a `dplyr` backend (say Postgress) does not guarantee 100% fidelity between dplyr execution against R. That said, if this becomes a continuous source of confusion, we could consider enhancing `mean()` and others to respect `NA` values.

**Comment by magarick** [comment]
What about something straightforward like printing a warning if certain functions are called and there are `NA`s? If I call functions like `mean` with `na.rm = TRUE` it already spits out a warning anyway, so this would be roughly consistent.

**Comment by konradedgar** [comment]
While running the `mean` on column with `NA`, I've got the warning message:
```r
na.rm not needed in SQL: NULL are always droppedFALSE
```
How this should be understood:

- `na.rm not needed in SQL: NULL are always dropped` : all `NAs` are automatically dropped
- `na.rm not needed in SQL: NULL are always dropped == FALSE`: all `NAs` ***are not*** automatically dropped 
What's the meaning of **`droppedFALSE`** in the above warning message?

**Comment by javierluraschi** [comment]
Closing, since understanding Spark `NA` behavior is expected while using `sparklyr`. The workarounds mentioned, as in checking for `NA`s, have a computation cost associated to it that we would rather avoid. If we hear more feedback from the community on this we can reconsider.
