### ISSUE TITLE
Failed to launch Spark shell. Ports file does not exist.

### ISSUE THREAD

**Issue by pathri-pk** [rstudio/sparklyr#245]
when i try to connect to local spark using
sc <- spark_connect(master = "local")
 Below is the error i am getting, I have the path set to c:\windows\system32
Error in force(code) : 
  Failed to launch Spark shell. Ports file does not exist.
    Path: C:\Users\<usersname>\AppData\Local\rstudio\spark\Cache\spark-2.0.0-bin-hadoop2.7\bin\spark-submit.cmd
    Parameters: --class, sparklyr.Backend, --packages, "com.databricks:spark-csv_2.11:1.3.0","com.amazonaws:aws-java-sdk-pom:1.10.34", "C:\Users\<username>\Documents\R\win-library\3.3\sparklyr\java\sparklyr-2.0-2.11.jar", C:\Users\<username>\AppData\Local\Temp\RtmpqeZblw\file39bc52b151f7.out
    
The input line is too long.

**Comment by javierluraschi** [comment]
@pathri-pk This has been solved in `sparklyr` version `0.4.9`. Could you please install the latest version using the following command and report back if this solves this issue for your configuration?

```{r}
devtools::install_github("rstudio/sparklyr")
```

**Comment by pathri-pk** [comment]
Thanks Javier, version 0.4.9 resolved the issue for my config
