### ISSUE TITLE
lag function

### ISSUE THREAD

**Issue by jwijffels** [rstudio/sparklyr#249]
Can one explain why this happens? Is this an issue in `dplyr` or `sparklyr` or is this no issue at all?
```
library(sparklyr)
library(dplyr)
sc <- spark_connect(master = "local")

data(cars, package = "datasets")
x <- copy_to(sc, cars, overwrite = TRUE)
mutate(x, prev = dplyr::lag(speed))

Source:   query [?? x 3]
Database: spark connection master=local[8] app=sparklyr local=TRUE

Error in UseMethod("escape") : 
  no applicable method for 'escape' applied to an object of class "function"
In addition: Warning messages:
1: In if (name == "local") { :
  the condition has length > 1 and only the first element will be used
2: In if (name %in% c("$", "[[", "[")) { :
  the condition has length > 1 and only the first element will be used
3: In if (name == "remote") { :
  the condition has length > 1 and only the first element will be used

## this works
mutate(x, prev = lag(speed))
mutate(cars, prev = dplyr::lag(speed))
```

**Comment by kevinushey** [comment]
When calling functions using the `dplyr` interface on a Spark table, the call is effectively translated into Spark SQL. That translation doesn't work if you try namespace-qualify the functions you're calling.

I don't think this is an issue; it's just a consequence of how the `dplyr` system works for remote databases.

**Comment by Tarqui** [comment]
Checking lag function. I noticed that the parameter `n` does not work

```
library(sparklyr)
library(dplyr)
sc <- spark_connect(master = "local")

data(cars, package = "datasets")
x <- copy_to(sc, cars, overwrite = TRUE)
mutate(x, prev = lag(dist, n = 2))
```
However, this works:

`mutate(cars, prev = lag(dist, n = 2))
`

**Comment by jwijffels** [comment]
@kevinushey Thanks, for the feedback!
@Tarqui 
You can use.
`mutate(x, prev = lag(dist, n = 2L))
`

**Comment by kevinushey** [comment]
Is the issue here that numeric values are not handled, while integer values are? If so we should fix that in `sparklyr`!

**Comment by kevinushey** [comment]
I just pushed https://github.com/rstudio/sparklyr/commit/00ae2a870be0b3934a8a80f84127ac7237b2d50b, which should ensure that both of these will work:

```
mutate(x, prev = lag(dist, n = 2L))
mutate(x, prev = lag(dist, n = 2))
```

Thanks for reporting!

**Comment by AkhilNairAmey** [comment]
A small comment on the documentation - sparklyr only seems to expect `lag` to have the argument `order`, but dplyr specifies the argument as `order_by`. 

```
Error in lag(position, by = 1, order_by = time) : 
  unused argument (order_by = time)
```

**Comment by alexmosc** [comment]
@kevinushey ,

> When calling functions using the dplyr interface on a Spark table, the call is effectively translated into Spark SQL. That translation doesn't work if you try namespace-qualify the functions you're calling.
> 
> I don't think this is an issue; it's just a consequence of how the dplyr system works for remote databases.

Why does this work fine

```
preprocessed_spark_df  %>% 
          dplyr::arrange(datetime_when)
```
if 

```
preprocessed_spark_df  %>%
          mutate(
               diff_object_action_before = dplyr::lag(What_Action, 1)
          )
```
doesn't?

**Comment by kevinushey** [comment]
Good question. I think it fails for the same reason that this fails:

```
library(DBI)
library(dplyr)
library(RSQLite)

con <- dbConnect(RSQLite::SQLite(), ":memory:")
dbWriteTable(con, "mtcars", mtcars, overwrite = TRUE)
mtcars_tbl <- tbl(con, "mtcars")

mtcars_tbl %>%
  mutate(mpg_lagged = dplyr::lag(mpg))
```

That is, the SQL translation that occurs within a `mutate()` call doesn't understand namespace-qualified functions. However, for the functions themselves (e.g. `arrange()`), those get resolved outside of the SQL translation context, and the job of `arrange()` when the object is a connection to a SQL data store is to translate its arguments into the appropriate SQL. In other words, translation doesn't happen on `arrange()` itself; it happens to the arguments passed to `arrange()`.

**Comment by harryprince** [comment]
this works well for me:

```{r}
group_by(uid) %>%
arrange(key)%>%
lag(value)
```

**Comment by ecoelhor** [comment]
I need help with something that seems to be similar
```
temp <- tibble(
  a = c(1, 2, NA),
  c = c(4, 8, NA),
  b = c("A", NA, "B")
)

temp_spark <- sdf_copy_to(sc, temp, "temp_spark")

> temp_spark %>% summarise(across(where(is.numeric), mean))
Error in UseMethod("escape") : 
  no applicable method for 'escape' applied to an object of class "function"
```

**Comment by yitao-li** [comment]
@ecoelhor Thanks for asking! The `across` syntax is only supported in the recently `dbplyr` 2.0 I believe (`dbplyr` is a DB backend interface that `sparklyr` relies on for working with Spark and `dplyr`).

However, supporting the `where(is.numeric)` is something that requires more `sparklyr` changes as `dbplyr` does not know how to apply the `is.numeric` to Spark dataframe columns unless it works with additional logic in `sparklyr` telling it what Spark data types satisfy the `is.numeric` requirement.

The current state of `sparklyr` is if you re-install `sparklyr` from its github master branch and upgrade `dbplyr` to 2.0.0 or above, then at least the following works:

```
temp_spark %>% summarise(across(everything(), mean)))
```

but

```
temp_spark %>% summarise(across(where(is.numeric), mean))
```

doesn't work yet.
