### ISSUE TITLE
consider setting spark.sql.warehouse.dir by default

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#250]
See: https://github.com/rstudio/sparklyr/issues/229#issuecomment-251584060

Some users have reported that in order to get `dplyr` and `sparklyr` to work in windows, they need to set `spark.sql.warehouse.dir` as follows to unblock a Hive exception:

``` r
library(sparklyr)
library(dplyr)
sc <- spark_connect(master = "spark://address:7077", config = list(spark.sql.warehouse.dir = "d:/Spark2/tmp/hadoop/bin"))
iris_tbl <- copy_to(sc, iris)
```

It is worth considering setting this automatically to "SPARK_HOME/tmp/hadoop/bin" but this would require more investigation to understand if setting `spark.sql.warehouse.dir` is the right approach.

**Comment by kevinushey** [comment]
We should also double-check whether this issue is related to https://github.com/rstudio/sparklyr/issues/239 -- it looks like there's an issue wherein some Spark APIs don't respect these configuration values.

I think we should do something similar to what we do for `spark_install`, e.g.

```
spark_sql_warehouse_dir <- function() {
   getOption("spark.sql.warehouse.dir", default = rappdirs::app_dir("spark-warehouse", "rstudio")$cache())
}
```

Thoughts?

**Comment by kevinushey** [comment]
We should also investigate if this is simply a `PATH` issue (does placing that `bin` directory on the `PATH` help at all?)

**Comment by javierluraschi** [comment]
Not sure that's enough since users reported that `spark.sql.warehouse.dir` needs to point to the `winutils.exe` which we install in `rappdirs::app_dir("spark", "rstudio")$cache()` + `file.path(sparkHome, "tmp", "hive")`. This also looks like a windows-specific issue. But perhaps pointing the config `spark.sql.warehouse.dir` to this directory is all we need. I think it's fine to make this change but we should read more about why we think this is required and not cause, potentially, other side effects, that's the part I'm less convinced about.

**Comment by javierluraschi** [comment]
We do set `spark.sql.warehouse.dir` as part of `spark_install()`, must have been performed as a different fix, the code that performs this is in `install_spark.R`.
