### ISSUE TITLE
question on spark sql functions which are not mapped?

### ISSUE THREAD

**Issue by jwijffels** [rstudio/sparklyr#251]
Can someone explain why this `levenshtein` call works. It is not mapped in the SQL mapping at https://github.com/rstudio/sparklyr/blob/master/R/dplyr_sql.R or https://github.com/rstudio/sparklyr/blob/master/R/dplyr_spark_connection.R.
Is the default behaviour of dplyr if the SQL is not mapped to use the function name?
FYI levenshtein is defined here: https://spark.apache.org/docs/latest/api/java/org/apache/spark/sql/functions.html

```
library(sparklyr)
library(dplyr)
sc <- spark_connect(master = "local")

x <- expand.grid(a = c("hi there", "thank you"), b = c("hi there xyz", "ank you"))
mydata <- copy_to(sc, x, overwrite = TRUE)
dplyr::mutate(mydata, lev = levenshtein(a, b))
```
Where can I find the code where this default behaviour if SQL is not mapped is occurring. In `dplyr` or `sparklyr`?

**Comment by kevinushey** [comment]
Indeed, the default behavior for `dplyr` is to simply generate SQL verbatim for functions without a known translator. In such a case, functions made available by the underlying SQL engine can be used -- in this case, Hive functions.

See https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF for a list of functions; in particular, `levenshtein` is defined as one of the [String functions](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF#LanguageManualUDF-StringFunctions).

The magic happens inside of `dplyr::sql_build` -- you can try debugging it to see how it uses the stored expressions constructed in the various `mutate` calls to construct SQL.

We should probably add some documentation to make this more clear / apparent.

**Comment by jwijffels** [comment]
Never mind, it's documented in ?dplyr::sql_variant, sorry for bothering.
