### ISSUE TITLE
 Change between long and wide format

### ISSUE THREAD

**Issue by dangulod** [rstudio/sparklyr#252]
I wonder if it would be possible to do this with sparklyr. Change between long and wide format like in tidyr package

```
library(sparklyr)
library(dplyr)
library(tidyr)

sc <- spark_connect(master = "local")

stocks <- data.frame(
  time = as.Date('2009-01-01') + 0:9,
  X = rnorm(10, 0, 1),
  Y = rnorm(10, 0, 2),
  Z = rnorm(10, 0, 4)
)

x <- copy_to(sc, stocks, overwrite = TRUE)

x %>% 
  gather(stock, price, -time)

x %>% 
  gather(stock, price, -time) %>% 
  spread(time, price)

stocks %>% 
  gather(stock, price, -time) %>% 
  spread(time, price)
```

**Comment by kevinushey** [comment]
Spark provides `pivot()` as a means of accomplishing this, with some documentation at https://databricks.com/blog/2016/02/09/reshaping-data-with-pivot-in-apache-spark.html, but we don't yet expose a simple mechanism for doing this in `sparklyr`.

Perhaps we should implement our own versions of `gather` and `spread` for `sparklyr`?

**Comment by javierluraschi** [comment]
@kevinushey Yes, I think that + `separate` would add descent coverage for `tidyr` functions. Maybe worth investigating what it would take to implement `tidyr` for `sparklyr`? I don't have a good sense if this is a few days of work or a few weeks, but it would be really awesome to support this!

**Comment by kykuo** [comment]
It makes sense to implement `gather` and `spread` for easy scaling up of "local small data" code and aesthetics. Haven't looked into `pivot` much but it's probably good to expose it for completeness.

**Comment by VadymBoikov** [comment]
Is there a way how I can do this operation using invoke ?

I'm stuck on aggregate expression 

Scala : 
```
 iris
  .groupBy("Species")
  .pivot("Sepal.Width")
  .agg(avg("Sepal.length")) 
```

R :
```
 iris_tbl <- copy_to(sc, iris)
 spark_dataframe(iris_tbl) %>% 
    invoke("groupBy", "Species", list()) %>% 
    invoke("pivot", "Sepal.Width", list()) %>% 
    invoke(  ... ) # <-  how to create aggregate expression?
```

**Comment by kevinykuo** [comment]
@kevinushey How's https://github.com/rstudio/sparklyr/pull/255 coming along? Need more sets of hands? Any blockers?

**Comment by kevinushey** [comment]
@kevinykuo it'd be awesome if you wanted to take a stab at this (either finishing up that PR, or generating your own) -- I'd be happy to review a PR.

**Comment by aliechoes** [comment]
Is there any update on this issue?

**Comment by kevinykuo** [comment]
Marking this as high priority; will get this on the timeline after 0.7 release.
