### ISSUE TITLE
Support hadoop 1.x in spark_install

### ISSUE THREAD

**Issue by trestletech** [rstudio/sparklyr#26]
EC2 spark requires Hadoop 1 to work properly. Currently you have to download that yourself and use `spark_install_tar()`. It would be nice to have this available in `spark_install()`.

Related issue: It’s really hard to figure out what the available versions of Hadoop are. Could we use an array of valid options for `hadoop_versions` in `spark_install` and combine with match.args()?

**Comment by javierluraschi** [comment]
This was removed by JJ since we recommend to point SPARK_HOME rather than instsalling again when a hadoop/spark install is already available.
