### ISSUE TITLE
implement `sdf_persist()`

### ISSUE THREAD

**Issue by kevinushey** [rstudio/sparklyr#260]
For use as a wrapper to the Spark Dataset [`persist`](http://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.sql.Dataset@persist(newLevel:org.apache.spark.storage.StorageLevel):Dataset.this.type) API.

In particular, we need to make it simple to use + access the different `StorageLevel`s, and perhaps make the 'default' storage level user configurable.

**Comment by joandre** [comment]
+1

**Comment by kevinushey** [comment]
This is implemented now, but we should make it easy to learn what the available storage levels are.
