### ISSUE TITLE
extracting column names from a spark data frame

### ISSUE THREAD

**Issue by pbhogale** [rstudio/sparklyr#262]
In base r, it is easy to extract the names of columns (variables) from a data frame

```
> testdf <- data.frame(a1 = rnorm(1e5), a2 = rnorm(1e5), a3 = rnorm(1e5), a4 = rnorm(1e5), a5 = rnorm(1e5), a6 = rnorm(1e5))  
> names(testdf)  
[1] "a1" "a2" "a3" "a4" "a5" "a6"
```

but while using sparklyr, things become more complicated. After copying the data frame to spark,

```
> testdf_tbl <- copy_to(sc, testdf, overwrite = TRUE)  
> names(testdf_tbl)  
[1] "src" "ops"
```

the variable names actually reside deep inside 'ops'

```
> testdf_tbl$ops$vars  
[1] "a1" "a2" "a3" "a4" "a5" "a6"
```

and if this were all, there would be no problems (and no need to ask this question). But, every time an operation happens on testdf_tbl, the names of the columns/variables change their position, as shown below..

```
> testdf_tbl <- testdf_tbl %>% select(-a1)  
> testdf_tbl$ops$vars  
NULL  
> testdf_tbl$ops$x$vars  
[1] "a1" "a2" "a3" "a4" "a5" "a6"  
````

performing another operation adds another $x to the path.. and so on.

```
> testdf_tbl <- testdf_tbl %>% select(-a2)  
> testdf_tbl$ops$x$vars  
NULL  
> testdf_tbl$ops$x$x$vars  
[1] "a1" "a2" "a3" "a4" "a5" "a6"  
```

To make matters worse, the list of variables does not reflect the select operations we have made,  a1, a2 are still listed as column names.

```
> head(testdf_tbl)
Source:   query [?? x 4]
Database: spark connection master=local[24] app=sparklyr local=TRUE

            a3           a4          a5         a6
         <dbl>        <dbl>       <dbl>      <dbl>
1 -1.146368875  1.691698406  0.43231629  1.3349111
2  0.664928710 -1.332242020  0.05380729  1.0139253
3  1.158095695 -0.097098980 -0.61885204  0.1504693
4  0.001595841 -0.003765908  0.27935192 -0.3039085
5 -0.133446040  0.269329076  1.57210274  1.7762602
6  0.006468698 -1.300439537  0.74057307  0.1320428
```

so clearly, the select operations have had an effect is terms of how the spark dataframe is used.

SURELY, there is/should be a simple, straightforward way to extract the current names of variables/columns in sparklyr, a la `names()` in base r.

**Comment by slopp** [comment]
Yes, simply use the `tbl_vars` command:

```r
library(sparklyr)
sc <- spark_connect(master = "local")
iris_tbl <- copy_to(sc, iris, "iris")
tbl_vars(iris_tbl)
# [1] "Sepal_Length" "Sepal_Width"  "Petal_Length" "Petal_Width"  "Species"   
```

Note that if you are using the RStudio Preview ( > v1.0) you can also view the schema of the objects through the Spark pane.

**Comment by pbhogale** [comment]
thanks a lot !

**Comment by admoseremic** [comment]
@slopp , do you know if there's also an easy way to write new names to the spark data frame?  In base R, you can say names(data_frame) <- ... to set new names to a data frame, but it doesn't look like you can do a similar tbl_vars(iris_tbl) = ...

Any thoughts?

**Comment by igornoberto** [comment]
Same issue as @admoseremic

**Comment by kevinykuo** [comment]
@igornoberto @admoseremic you can rename columns with `dplyr::rename()`

**Comment by igornoberto** [comment]
@kevinykuo I'm getting the following error using `dplyr::rename`:

https://github.com/rstudio/sparklyr/issues/900

**Comment by MJFND** [comment]
colnames() also work as tbl_vars
