### ISSUE TITLE
Error While Encoding

### ISSUE THREAD

**Issue by yarrick19** [rstudio/sparklyr#265]
Hi guys,

I was attempting to follow along with the "Comparison of ML Classifiers Using Sparklyr" example on the rstudio page and have encountered errors copying the titanic data into spark.  This was executed on an AWS EMR cluster via the preview edition of RStudio server.  

```
library(sparklyr)
library(dplyr)
library(tidyr)
library(titanic)
library(ggplot2)
library(purrr)

# ----------------------------------
# Connect to Spark
# ----------------------------------
Sys.setenv(SPARK_HOME = "/usr/lib/spark")
sc <- spark_connect(master = "yarn-client", version = '2.0.0')



titanic_tbl <- copy_to(sc, titanic_train, "titanic", overwrite = TRUE)
# ERROR OCCURS HERE

# have to seem to use memory = FALSE Or Error occurs!
titanic_tbl <- copy_to(sc, titanic_train, "titanic", memory = FALSE, overwrite = TRUE)

summarise(titanic_tbl, row_count = n())
# ERROR OCCURS HERE AS WELL
```

The first instance of an error is when attempting to move the titanic_train data frame from R into Spark.  Here is the error:
```
Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 27.0 failed 4 times, most recent failure: Lost task 0.3 in stage 27.0 (TID 48, ip-172-31-15-128.us-west-2.compute.internal): java.lang.RuntimeException: Error while encoding: java.lang.ArrayIndexOutOfBoundsException: 11
if (assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt) null else validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 0, PassengerId), IntegerType) AS PassengerId#879
+- if (assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt) null else validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 0, PassengerId), IntegerType)
   :- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt
   :  :- assertnotnull(input[0, org.apache.spark.sql.Row, true], top l
```
Setting the argument memory = FALSE seems to load the data (to disk I assume) without error.  But, it seems any subsequent action using that table generates a similar error.
For example, trying to get a row count using summarise() results in this error:
```
Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 3.0 failed 4 times, most recent failure: Lost task 0.3 in stage 3.0 (TID 6, ip-172-31-15-128.us-west-2.compute.internal): java.lang.RuntimeException: Error while encoding: java.lang.ArrayIndexOutOfBoundsException: 11
if (assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt) null else validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 0, PassengerId), IntegerType) AS PassengerId#16
+- if (assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt) null else validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object), 0, PassengerId), IntegerType)
   :- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level row object).isNullAt
   :  :- assertnotnull(input[0, org.apache.spark.sql.Row, true], top level
```

**Comment by kevinushey** [comment]
Sorry, but the error messages aren't particularly helpful, so without a reproducible example I don't think there's much we can do.

Can you share the contents of `titanic_train`, or the code that generates it?

**Comment by yarrick19** [comment]
@kevinushey , the titanic_train data is part of the titanic package on cran.  Thanks for the quick response!
```
install.packages('titanic')
library(titanic)
head(titanic_train)
```
Also, in your experience, what is the most stable version of spark to use with sparklyr?

**Comment by kevinushey** [comment]
Oops, thanks @yarrick19 -- you're indeed right; I didn't realize I didn't have `titanic` installed + the dataset was provided by that package.

It looks like the error is caused explicitly when using the `csv_string` serializer (note that this is an documented argument to `copy_to()` we use primarily for testing). That is, you can reproduce locally with something like:

```
library(sparklyr)
library(dplyr)
library(tidyr)
library(titanic)
library(ggplot2)
library(purrr)

sc <- spark_connect(master = "local", version = "2.0.0")

titanic_tbl <- copy_to(sc,
                       titanic_train,
                       "titanic",
                       overwrite = TRUE,
                       serializer = "csv_string")
```

Using `serializer = "csv_file"` instead of `serializer = "csv_string"` seems to work just fine, however.

@javierluraschi, any thoughts on why the `"csv_string"` serializer is failing here?

And to answer your other question -- I would say that staying current with Spark is generally recommended unless you have a very good reason _not_ to; 2.0.1 was just released and it resolves a number of issues + comes with a number of performance improvements as well.

**Comment by kevinushey** [comment]
I think I know what's going on -- the issue is causing by a missing value in the last column of the dataset. A reproducible example:

```
library(sparklyr)
library(dplyr)

sc <- spark_connect(master = "local", version = "2.0.1")

df <- data.frame(
  x = c(1, 2),
  z = c('a', ""),
  stringsAsFactors = FALSE
)

copy_to(sc, df, serializer = "csv_string", overwrite = TRUE)
```

**Comment by kevinushey** [comment]
Indeed, trailing separators are _dropped_ by Java's `String.split` (same as with R's `strsplit`) so we'll likely need to work around that and add an empty element manually if the string to be split ends with the separator.
