### ISSUE TITLE
dplyr is needed to use `copy_to()`?

### ISSUE THREAD

**Issue by navdeep-G** [rstudio/sparklyr#267]
I am trying to run RSparkling and realized that I need to do a library call to dplyr. The following behavior is what I see if I don't call dplyr or try to call `copy_to` from sparklyr:

`
> mtcars_tbl <- copy_to(sc, mtcars, overwrite = TRUE)
Error: could not find function "copy_to"
> mtcars_tbl <- sparklyr::copy_to(sc, mtcars, overwrite = TRUE)
Error: 'copy_to' is not an exported object from 'namespace:sparklyr'

`

Is this expected?

**Comment by kevinushey** [comment]
That's correct + expected (`copy_to()` is a function specific to `dplyr`); I've made the change necessary to import and re-export that function now, however.

**Comment by navdeep-G** [comment]
Ah, i see. Should be fixed now then if i re-install from Github?

**Comment by kevinushey** [comment]
Yes indeed, although note that e.g. `mutate()` and friends will require you to attach the `dplyr` package.

**Comment by navdeep-G** [comment]
Yep. Good to know. Thx!
