### ISSUE TITLE
GC overhead limit exceeded on write parquet file

### ISSUE THREAD

**Issue by hiltonmbr** [rstudio/sparklyr#269]
Dears,

I have been trying to change MemoryStore without successful:

library(sparklyr)
library(dplyr)

sc <- spark_connect(master = "local[*]",
                    config =  list("sparklyr.shell.executor.memory"="8g",
                                   "sparklyr.shell.driver-memory"="8g"))
spark_log(sc)

Log file returns:

INFO MemoryStore: MemoryStore started with capacity 366.3 MB

Then, I cannot write a parquet file
spark_write_parquet(df,path=fname,mode="overwrite")

ERROR Utils: Aborting task
java.lang.OutOfMemoryError: GC overhead limit exceeded

Any idea?

**Comment by kevinushey** [comment]
I think you have a type in your option -- it should be `sparklyr.shell.executor-memory`; that is, you should use a `-` to separate `executor` and `memory`.

**Comment by kevinushey** [comment]
@javierluraschi should we warn about unrecognized options passed through the config?

**Comment by hiltonmbr** [comment]
@kevinushey I changed the config options to:

sc <- spark_connect(master = "local[*]",
config = list("sparklyr.shell.executor-memory"="8g",
"sparklyr.shell.driver-memory"="8g"))

But Log file still returns:

INFO MemoryStore: MemoryStore started with capacity 366.3 MB
BlockManagerMasterEndpoint: Registering block manager 127.0.0.1:62908 with 366.3 MB RAM, BlockManagerId(driver, 127.0.0.1, 62908)

**Comment by hiltonmbr** [comment]
Dears @kevinushey and @kevinushey, could you check for unrecognized options, especially for "spark.driver.memory" option?

For instance, if I use the following procedures it works fine and increases the storage memory for RDD partitions:

library(sparklyr)
dir <- paste0(spark_home_dir(),"/R/lib/")
library("SparkR",lib.loc =dir)
sc <- sparkR.session(master = "local[*]","SparkR",
                     sparkConfig = list(spark.executor.memory="4g",
                                        spark.driver.memory="4g"))

Taking a look on spark UI: http://localhost:4040/executors/
![captura de tela 2016-10-16 as 10 24 35](https://cloud.githubusercontent.com/assets/1009086/19417731/d24b1bf2-938a-11e6-8427-a7c45deb3a90.png)

On the other hand, doing the same with sparklyr:

library(sparklyr)
sc <- spark_connect(master = "local[*]",
                    config = list("spark.executor.memory"= "4g",
                                  "spark.driver.memory"="4g"))
spark_web(sc)

It does not work:
![captura de tela 2016-10-16 as 10 30 53](https://cloud.githubusercontent.com/assets/1009086/19417765/a834cfec-938b-11e6-867e-f9f87d286da7.png)

Am I wrong about config list options in sparkr or it does not recognize correctly?

**Comment by javierluraschi** [comment]
@hiltonmbr the options seem correct, tried your same code and worked for me. We will have to dig deeper in the logs to figure this out, mind sharing `spark_log` after connect?

**Comment by hiltonmbr** [comment]
@javierluraschi after update sparklyr the memory allocation is working fine. Thank you.

library(sparklyr)
 sc <- spark_connect(master = "local[*]",
                     config = list("sparklyr.shell.executor-memory"= "4g",
                                 "sparklyr.shell.driver-memory"="4g"))
 spark_log(sc)
16/10/30 08:44:49 INFO sparklyr session (9998) starting
16/10/30 08:44:50 INFO sparklyr gateway received command identifier (0)
16/10/30 08:44:50 INFO sparklyr gateway found current session (9998)
16/10/30 08:44:54 INFO sparklyr gateway created backend for session (9998)
16/10/30 08:44:54 INFO sparklyr gateway waiting for r process to end in session (9998)
16/10/30 08:44:55 INFO SparkContext: Running Spark version 2.0.1
16/10/30 08:44:57 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/10/30 08:44:58 INFO SecurityManager: Changing view acls to: Hilton_iMac
16/10/30 08:44:58 INFO SecurityManager: Changing modify acls to: Hilton_iMac
16/10/30 08:44:58 INFO SecurityManager: Changing view acls groups to: 
16/10/30 08:44:58 INFO SecurityManager: Changing modify acls groups to: 
16/10/30 08:44:58 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(Hilton_iMac); groups with view permissions: Set(); users  with modify permissions: Set(Hilton_iMac); groups with modify permissions: Set()
16/10/30 08:44:58 INFO Utils: Successfully started service 'sparkDriver' on port 51002.
16/10/30 08:44:58 INFO SparkEnv: Registering MapOutputTracker
16/10/30 08:44:59 INFO SparkEnv: Registering BlockManagerMaster
16/10/30 08:44:59 INFO DiskBlockManager: Created local directory at /private/var/folders/hw/51jrzlkx0vgdrnv_jsz_jcnh0000gn/T/blockmgr-72a956f4-3f47-4388-98e7-fac1b07b157c
16/10/30 08:44:59 INFO MemoryStore: MemoryStore started with capacity 2004.6 MB
16/10/30 08:44:59 INFO SparkEnv: Registering OutputCommitCoordinator
16/10/30 08:45:00 INFO Utils: Successfully started service 'SparkUI' on port 4040.
16/10/30 08:45:00 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://192.168.155.107:4040
16/10/30 08:45:00 INFO SparkContext: Added JAR file:/Users/Hilton_iMac/Library/R/3.3/library/sparklyr/java/sparklyr-2.0-2.11.jar at spark://192.168.155.107:51002/jars/sparklyr-2.0-2.11.jar with timestamp 1477827900755
16/10/30 08:45:01 INFO Executor: Starting executor ID driver on host localhost
16/10/30 08:45:01 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 51003.
16/10/30 08:45:01 INFO NettyBlockTransferService: Server created on 192.168.155.107:51003
16/10/30 08:45:01 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 192.168.155.107, 51003)
16/10/30 08:45:01 INFO BlockManagerMasterEndpoint: Registering block manager 192.168.155.107:51003 with 2004.6 MB RAM, BlockManagerId(driver, 192.168.155.107, 51003)
16/10/30 08:45:01 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 192.168.155.107, 51003)
16/10/30 08:45:01 WARN SparkContext: Use an existing SparkContext, some configuration may not take effect.
16/10/30 08:45:02 WARN SparkContext: Use an existing SparkContext, some configuration may not take effect.
16/10/30 08:45:02 INFO HiveSharedState: Warehouse path is '/Users/Hilton_iMac/spark-warehouse'.

**Comment by javierluraschi** [comment]
Glad to hear this is fixed now.
