### ISSUE TITLE
read from jdbc

### ISSUE THREAD

**Issue by ElianoMarques** [rstudio/sparklyr#270]
Any plans to read data directly from jdbc sources? This would required a jar file to be added to the session and some addition parameters to spark dataframe read. 

See here: 
http://spark.apache.org/docs/latest/sql-programming-guide.html#jdbc-to-other-databases

Thank you,
Eliano

**Comment by ElianoMarques** [comment]
@javierluraschi any thoughts on this?

**Comment by ElianoMarques** [comment]
ok just saw this spark_read_jdbc(). Nice, testing.

**Comment by tarunparmar** [comment]
Hi @ElianoMarques - can you share an example if that worked for you, would like to know how you set it up for Oracle DB.

**Comment by javierluraschi** [comment]
@ElianoMarques yes, functionality is implemented now, thanks for suggesting this.

@tarunparmar example follows:

### Read from JDBC ###

For example, to read data from MySQL: Install MySQL in OS X using brew: `brew install mysql`, start the service `mysql.server start` and login with `mysql -uroot` to create a database as follows:

```{sql}
CREATE DATABASE sparklyr;
USE sparklyr;

CREATE TABLE `person` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `first_name` varchar(30) DEFAULT NULL,
  `last_name` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

INSERT INTO person(first_name, last_name) VALUES("Barack", "Obama");
INSERT INTO person(first_name, last_name) VALUES("Bill", "Clinton");

ALTER USER 'root'@'localhost' IDENTIFIED BY '<password>';

QUIT;
```

`sparklyr` requires a JDBC driver, for MySQL, this can be downloaded from http://dev.mysql.com/downloads/connector/j/. Then, once can connect from sparklyr by setting `sparklyr.shell.driver-class-path` to the driver and settting the right connections options, for this example:

```
config <- spark_config()
config$`sparklyr.shell.driver-class-path` <- 
  "~/Downloads/mysql-connector-java-5.1.41/mysql-connector-java-5.1.41-bin.jar"

sc <- spark_connect(master = "local",
                    version = "2.1.0",
                    config = config)

spark_read_jdbc(sc, "person_jdbc",  options = list(
  url = "jdbc:mysql://localhost:3306/sparklyr",
  user = "root",
  password = "<password>",
  dbtable = "person"))
```

```
Source:     table<person_jdbc> [?? x 3]
Database:   spark_connection

     id first_name last_name
  <int>      <chr>     <chr>
1     1       Bill   Clinton
2     2     Barack     Obama
```

Stop the running MySQL service by running `mysql.server stop`.

**Comment by MCM-Math** [comment]
I keep getting "Unsupported type 101" errors from spark_read_jdbc, and I can't determine why anywhere, and I don't have problems with the same data with other functions.

**Comment by leungi** [comment]
> Hi @ElianoMarques - can you share an example if that worked for you, would like to know how you set it up for Oracle DB.

Many moments later, following @javierluraschi example, for Oracle connection:

1. download [Oracle JDBC](https://www.oracle.com/database/technologies/jdbc-upc-downloads.html)
2. use Oracle connection string format:
```r
config <- spark_config()
config$`sparklyr.shell.driver-class-path` <- 
  "C:/Users/leungi/Downloads/ojdbc8-full/ojdbc8.jar"

sc <- spark_connect(master = "local",
                    version = "2.4",
                    config = config)

tbl<- spark_read_jdbc(sc, "my_tbl",  options = list(
  url = "jdbc:oracle:thin:@server:port/SID",
  user = "user",
  password = "pass",
  dbtable = "schema.table")
)
```

**Comment by mattpollock** [comment]
If you don't want to read the entire table into spark, you can also write a SQL query, wrap it in parenthesis, and pass that to `dbtable`, e.g.
```

config <- spark_config()
config$`sparklyr.shell.driver-class-path` <- 
  "C:/Users/leungi/Downloads/ojdbc8-full/ojdbc8.jar"

sc <- spark_connect(master = "local",
                    version = "2.4",
                    config = config)

tbl<- spark_read_jdbc(sc, "my_tbl",  options = list(
  url = "jdbc:oracle:thin:@server:port/SID",
  user = "user",
  password = "pass",
  dbtable = "(select x, y from z where x = 'a')")
)

**Comment by leungi** [comment]
I'm enlightened; thanks for sharing @mattpollock .

**Comment by gboyega1** [comment]
I would like to know if anyone has been able to establish this connection with Google BigQuery using the Simba JDBC driver for Google BigQuery here:
https://storage.googleapis.com/simba-bq-release/jdbc/SimbaJDBCDriverforGoogleBigQuery42_1.2.25.1029.zip
