### ISSUE TITLE
sparklyr spark_connect issue

### ISSUE THREAD

**Issue by roshnamohan** [rstudio/sparklyr#274]
Hi,

We are using sparklyr 0.4.16 on our cluster and is trying to connect to spark using spark_connect function.
The commands are as follows:
 _Sys.setenv(SPARK_HOME="/opt/cloudera/parcels/CDH/lib/spark/")
 Sys.setenv(SPARK_HOME_VERSION="1.5.0-cdh5.5.4")
 .libPaths(c(file.path(Sys.getenv("SPARK_HOME"), "R", "lib"), .libPaths()))
 library(sparklyr)
 library(DBI)
 sparklyr::spark_install(version = "1.6.2") 
 sc <- spark_connect(master = "yarn-client")_
**Failed while connecting to sparklyr to port (8880) for sessionid (1960): Gateway in port (8880) did not respond.
    Path: /opt/cloudera/parcels/CDH-5.5.4-1.cdh5.5.4.p0.9/lib/spark/bin/spark-submit
    Parameters: --class, sparklyr.Backend, --packages, 'com.databricks:spark-csv_2.11:1.3.0', '', 8880, 1960
    Traceback:
      shell_connection(master = master, spark_home = spark_home, app_name = app_name, version = version, hadoop_version = hadoop_version, shell_args = shell_args, config = config, service = FALSE, extensions = extensions)
      start_shell(master = master, spark_home = spark_home, spark_version = version, app_name = app_name, config = config, jars = spark_config_value(config, "spark.jars.default", list()), packages = spark_config_value(config, "sparklyr.defaultPackages"), extensions = extensions, environment = environment, shell_args = shell_args, service = service)
      tryCatch({
    gatewayInfo <- spark_connect_gateway(gatewayAddress, gatewayPort, sessionId, config = config, isStarting = TRUE)
}, error = function(e) {
    abort_shell(paste("Failed while connecting to sparklyr to port (", gatewayPort, ") for sessionid (", sessionId, "): ", e$message, sep = ""), spark_submit_path, shell_args, output_file, error_file)
})
      tryCatchList(expr, classes, parentenv, handlers)
      tryCatchOne(expr, names, parentenv, handlers[[1]])
      value[[3]](cond)
      abort_shell(paste("Failed while connecting to sparklyr to port (", gatewayPort, ") for sessionid (", sessionId, "): ", e$message, sep = ""), spark_submit_path, shell_args, output_file, error_file)

---- Output Log ----
Ivy Default Cache set to: /root/.ivy2/cache
The jars for the packages stored in: /root/.ivy2/jars
:: loading settings :: url = jar:file:/opt/cloudera/parcels/CDH-5.5.4-1.cdh5.5.4.p0.9/jars/spark-assembly-1.5.0-cdh5.5.4-hadoop2.6.0-cdh5.5.4.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.databricks#spark-csv_2.11 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
        confs: [default]

---- Error Log ----**

This version of sparklyr has been updated from 0.4.0, where the connection error was something like ports file does not exist.

We are running CDH 5.5.4 in the cluster.

Thanks in advance

**Comment by javierluraschi** [comment]
@roshnamohan  1. Unless you've removed the path to a jar in your log dump, it looks like the sparklyr `jar` is missing from the line executing spark-submit (`Parameters: --class, sparklyr.Backend, --packages, 'com.databricks:spark-csv_2.11:1.3.0', '', 8880, 1960`, notice the `''` empty jar parameter`). Could you run `spark_config()` and share the results back? I wonder if the config is overriding the `spark.jars.default` setting which would explain this.

Couple other less relevant thoughts:

 2. The `---- Output Log ----` shows that dependencies are being downloaded, `sparklyr` depends on this package for reading CSV files: `spark-csv_2.10` which sometimes fails/hangs on download if the cluster does not have full internet connectivity available or is restricted in some ways preventing the package to install. You can try this to scope this issue:

```{r}
conf <- spark_config()
conf[["sparklyr.defaultPackages"]] <- c()

sc <- spark_connect(master = "yarn-client")
```

 3. You might be able to get a better error message by running the command directly from a console: `/opt/cloudera/parcels/CDH-5.5.4-1.cdh5.5.4.p0.9/lib/spark/bin/spark-submit --class sparklyr.Backend --packages 'com.databricks:spark-csv_2.11:1.3.0' <PATH to missing sparklyr JAR> 8880 1960`

**Comment by roshnamohan** [comment]
Hi Javier,

Thank you for the quick turnaround!

We seem to have got a temporary fix from what you adviced. Details are as follows:

1) Output for spark_config() is as follows:

> library(sparklyr)
Warning messages:
1: replacing previous import by ‘dplyr::copy_to’ when loading ‘sparklyr’
2: replacing previous import by ‘magrittr::%>%’ when loading ‘sparklyr’
3: replacing previous import by ‘tibble::data_frame’ when loading ‘sparklyr’
> spark_config()
$sparklyr.cores.local
[1] 32

$spark.sql.shuffle.partitions.local
[1] 32

$spark.env.SPARK_LOCAL_IP.local
[1] "127.0.0.1"

$sparklyr.defaultPackages
[1] "com.databricks:spark-csv_2.11:1.3.0"

attr(,"config")
[1] "default"
attr(,"file")
[1] "/usr/lib64/R/library/sparklyr/conf/config-template.yml"

2) The following command was run directly from console as mentioned, however we had to export internet proxy:

`/opt/cloudera/parcels/CDH-5.5.4-1.cdh5.5.4.p0.9/lib/spark/bin/spark-submit --jars .ivy2/jars/spark-csv_2.10-1.3.0.jar --conf "spark.driver.extraJavaOptions=-Dhttp.proxyHost=<proxy_IP> -Dhttp.proxyPort=<port> -Dhttps.proxyHost=<IP> -Dhttps.proxyPort=<port> -Dhttp.proxyUser=<user> -Dhttp.proxyPassword=<*****>" --class sparklyr.Backend --packages 'com.databricks:spark-csv_2.11:1.3.0' /usr/lib64/R/library/sparklyr/java/sparklyr-1.6-2.10.jar 8880 602`

The session iD is random.

This gave us the following output:
======================================
Ivy Default Cache set to: /export/home/<user>/.ivy2/cache
The jars for the packages stored in: /export/home/<user>/.ivy2/jars
:: loading settings :: url = jar:file:/opt/cloudera/parcels/CDH-5.5.4-1.cdh5.5.4.p0.9/jars/spark-assembly-1.5.0-cdh5.5.4-hadoop2.6.0-cdh5.5.4.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.databricks#spark-csv_2.11 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
        confs: [default]
	found com.databricks#spark-csv_2.11;1.3.0 in central
	found org.apache.commons#commons-csv;1.1 in central
        found com.univocity#univocity-parsers;1.5.1 in central
downloading https://repo1.maven.org/maven2/com/databricks/spark-csv_2.11/1.3.0/spark-csv_2.11-1.3.0.jar ...
        [SUCCESSFUL ] com.databricks#spark-csv_2.11;1.3.0!spark-csv_2.11.jar (42ms)
downloading https://repo1.maven.org/maven2/org/apache/commons/commons-csv/1.1/commons-csv-1.1.jar ...
        [SUCCESSFUL ] org.apache.commons#commons-csv;1.1!commons-csv.jar (11ms)
downloading https://repo1.maven.org/maven2/com/univocity/univocity-parsers/1.5.1/univocity-parsers-1.5.1.jar ...
        [SUCCESSFUL ] com.univocity#univocity-parsers;1.5.1!univocity-parsers.jar (27ms)
:: resolution report :: resolve 2212ms :: artifacts dl 88ms
        :: modules in use:
        com.databricks#spark-csv_2.11;1.3.0 from central in [default]
        com.univocity#univocity-parsers;1.5.1 from central in [default]
        org.apache.commons#commons-csv;1.1 from central in [default]
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   3   |   3   |   3   |   0   ||   3   |   3   |
        ---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent
        confs: [default]
        0 artifacts copied, 3 already retrieved (0kB/7ms)
16/10/21 06:15:19 INFO sparklyr session (602) starting
=============================================


After this, we could successfully place a spark_connect.


This does not seem to be a permanent fix though! We have to run the above command from console for each user!

Are there any proper way of doing it? 

Where do we have to copy the spark-csv jar to?

**Comment by roshnamohan** [comment]
After what we thought a successful connect, I ran the following commands from R prompt:

```
> sc <- spark_connect(master = "yarn-client", config = spark_config(), version = "1.6.2")
> sparklyr:::spark_default_app_jar("2.0.0")
[1] "/usr/lib64/R/library/sparklyr/java/sparklyr-2.0-2.11.jar"
> spark_home_dir()
NULL
> list.files(rappdirs::app_dir("spark", "rstudio")$cache(), recursive = TRUE, pattern = ".cmd")
character(0)
```

**Comment by javierluraschi** [comment]
@roshnamohan as a start, since you do need to configure a proxy, this would be the right command to trigger from `sparklyr` (please modified password, etc as needed):

First, please uninstall:
```{r}sparklyr::spark_install(version = "1.6.2") 
```

```{r}
config <- spark_config()
config[["sparklyr.shell.config"]] <- "spark.driver.extraJavaOptions=-Dhttp.proxyHost=<proxy_IP> -Dhttp.proxyPort=<port> -Dhttps.proxyHost=<IP> -Dhttps.proxyPort=<port> -Dhttp.proxyUser=<user> -Dhttp.proxyPassword=<*****>"
sc <- spark_connect(master = "yarn-client", version = "")
```

**Comment by roshnamohan** [comment]
Tried to uninstall spark after loading sparklyr library; however no uninstall has been performed.
```
> spark_uninstall(version = "1.6.2", hadoop_version = "2.6")
spark-1.6.2-bin-hadoop2.6 not found (no uninstall performed)
```
Is there a way we could omit giving the proxy credentials in the command? where should we store the jar so that it can be accessed locally?

**Comment by javierluraschi** [comment]
@roshnamohan I was under the impression that `2.6` was installed on your system. You can try this `sparklyr::spark_installed_versions()` to see which versions are installed and then uninstall `1.6.2` and then run `spark_uninstall(version = "1.6.2", hadoop_version = "")` with the right `hadoop_version`.

Did you try the following command? What was its output?

```{r}
config <- spark_config()
config[["sparklyr.shell.conf"]] <- "spark.driver.extraJavaOptions=-Dhttp.proxyHost=<proxy_IP> -Dhttp.proxyPort=<port> -Dhttps.proxyHost=<IP> -Dhttps.proxyPort=<port> -Dhttp.proxyUser=<user> -Dhttp.proxyPassword=<*****>"
sc <- spark_connect(master = "yarn-client", version = "1.6.2", config = config)
```

**Comment by roshnamohan** [comment]
@javierluraschi 
`sparklyr::spark_installed_versions() ` returns 0 rows:
```
> sparklyr::spark_installed_versions()
[1] spark  hadoop dir
<0 rows> (or 0-length row.names)
```
However, 
```
> packageVersion("sparklyr")
[1] ‘0.4.16’
```
When i run with my IP and creds, 
```
> config <- spark_config()
> config[["sparklyr.shell.conf"]] <- "spark.driver.extraJavaOptions=-Dhttp.proxyHost=<IP> -Dhttp.proxyPort=<port> -Dhttps.proxyHost=<IP> -Dhttps.proxyPort=<port> -Dhttp.proxyUser=<user> -Dhttp.proxyPassword=<******>"
> sc <- spark_connect(master = "yarn-client", version = "1.6.2", config = config)
```
The query hangs there for over half an hour, and I quit the session by pressing Ctrl + C

And the output for the previous query is as follows:

```
> Sys.setenv(SPARK_HOME="/opt/cloudera/parcels/CDH/lib/spark/")
> Sys.setenv(SPARK_HOME_VERSION="1.5.0-cdh5.5.4")
> .libPaths(c(file.path(Sys.getenv("SPARK_HOME"), "R", "lib"), .libPaths()))
> library(sparklyr)
> library(DBI)
> sc <- spark_connect(master = "yarn-client", config = spark_config())
Error in force(code) :
  Failed while connecting to sparklyr to port (8880) for sessionid (597): Gateway in port (8880) does not have the requested session registered
    Path: /opt/cloudera/parcels/CDH-5.5.4-1.cdh5.5.4.p0.9/lib/spark/bin/spark-submit
    Parameters: --class, sparklyr.Backend, --packages, 'com.databricks:spark-csv_2.11:1.3.0', '', 8880, 597
    Traceback:
      shell_connection(master = master, spark_home = spark_home, app_name = app_name, version = version, hadoop_version = hadoop_version, shell_args = shell_args, config = config, service = FALSE, extensions = extensions)
      start_shell(master = master, spark_home = spark_home, spark_version = version, app_name = app_name, config = config, jars = spark_config_value(config, "spark.jars.default", list()), packages = spark_config_value(config, "sparklyr.defaultPackages"), extensions = extensions, environment = environment, shell_args = shell_args, service = service)
      tryCatch({
    gatewayInfo <- spark_connect_gateway(gatewayAddress, gatewayPort, sessionId, config = config, isStarting = TRUE)
}, error = function(e) {
    abort_shell(paste("Failed while connecting to sparklyr to port (", gatewayPort, ") for sessionid (", sessionId, "): ", e$message, sep = ""), spark_submit_path, shell_args, output_file, error_file)
})
      tryCatchList(expr, classes, parentenv, handlers)
      tryCatchOne(expr, names, parentenv, handlers[[1]])
      value[[3]](cond)
      abort_shell(paste("Failed while connecting to sparklyr to port (", gatewayPort, ") for sessionid (", sessionId, "): ", e$message, sep = ""), spark_submit_path, shell_args, output_file, error_file)

---- Output Log ----
Ivy Default Cache set to: /root/.ivy2/cache
The jars for the packages stored in: /root/.ivy2/jars
:: loading settings :: url = jar:file:/opt/cloudera/parcels/CDH-5.5.4-1.cdh5.5.4.p0.9/jars/spark-assembly-1.5.0-cdh5.5.4-hadoop2.6.0-cdh5.5.4.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.databricks#spark-csv_2.11 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
        confs: [default]
        found com.databricks#spark-csv_2.11;1.3.0 in central
        found org.apache.commons#commons-csv;1.1 in central
        found com.univocity#univocity-parsers;1.5.1 in central
:: resolution report :: resolve 286ms :: artifacts dl 9ms
        :: modules in use:
        com.databricks#spark-csv_2.11;1.3.0 from central in [default]
        com.univocity#univocity-parsers;1.5.1 from central in [default]
        org.apache.commons#commons-csv;1.1 from central in [default]
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
        ---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent
        confs: [default]
        0 artifacts copied, 3 already retrieved (0kB/7ms)
java.lang.ClassNotFoundException: sparklyr.Backend
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:270)
        at org.apache.spark.util.Utils$.classForName(Utils.scala:172)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:639)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

---- Error Log ----
```

Which jar is missing here, and how could I load this from local?

Thanks in advance 
Roshna

**Comment by roshnamohan** [comment]
The sesionInfo() is as follows:

```
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.5 (Santiago)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] DBI_0.5-1       sparklyr_0.4.16

loaded via a namespace (and not attached):
 [1] magrittr_1.5    R6_2.1.2        assertthat_0.1  rprojroot_1.0-2
 [5] parallel_3.2.3  tools_3.2.3     withr_1.0.2     dplyr_0.5.0
 [9] yaml_2.1.13     tibble_1.2      Rcpp_0.12.3     config_0.2
[13] digest_0.6.10

```

**Comment by roshnamohan** [comment]
@javierluraschi 
I ran the following command in linux shell and tried to connect to spark from R prompt using spark_connect.

```
 spark-submit --class sparklyr.Backend --packages 'com.databricks:spark-csv_2.11:1.3.0' /usr/lib64/R/library/sparklyr/java/sparklyr-1.6-2.10.jar 8880 900
Ivy Default Cache set to: /root/.ivy2/cache
The jars for the packages stored in: /root/.ivy2/jars
:: loading settings :: url = jar:file:/opt/cloudera/parcels/CDH-5.5.4-1.cdh5.5.4.p0.9/jars/spark-assembly-1.5.0-cdh5.5.4-hadoop2.6.0-cdh5.5.4.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.databricks#spark-csv_2.11 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
        confs: [default]
        found com.databricks#spark-csv_2.11;1.3.0 in central
        found org.apache.commons#commons-csv;1.1 in central
        found com.univocity#univocity-parsers;1.5.1 in central
:: resolution report :: resolve 306ms :: artifacts dl 9ms
        :: modules in use:
        com.databricks#spark-csv_2.11;1.3.0 from central in [default]
        com.univocity#univocity-parsers;1.5.1 from central in [default]
        org.apache.commons#commons-csv;1.1 from central in [default]
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
        ---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent
        confs: [default]
        0 artifacts copied, 3 already retrieved (0kB/7ms)
16/10/25 09:02:28 INFO sparklyr session (900) starting

16/10/25 09:05:30 INFO sparklyr gateway received command identifier (0)
16/10/25 09:05:30 INFO sparklyr gateway searching for session (8564)
16/10/25 09:05:30 INFO sparklyr gateway found no mapping for session (8564)
16/10/25 09:05:31 INFO sparklyr gateway received command identifier (0)
16/10/25 09:05:31 INFO sparklyr gateway searching for session (8564)
16/10/25 09:06:31 INFO sparklyr gateway found no mapping for session (8564)

16/10/25 09:10:06 INFO sparklyr gateway received command identifier (0)
16/10/25 09:10:06 INFO sparklyr gateway searching for session (8071)
16/10/25 09:10:06 INFO sparklyr gateway found no mapping for session (8071)
16/10/25 09:10:07 INFO sparklyr gateway received command identifier (0)
16/10/25 09:10:07 INFO sparklyr gateway searching for session (8071)
16/10/25 09:11:07 INFO sparklyr gateway found no mapping for session (8071)

16/10/25 09:12:32 INFO sparklyr gateway received command identifier (0)
16/10/25 09:12:32 INFO sparklyr gateway searching for session (60)
16/10/25 09:12:32 INFO sparklyr gateway found no mapping for session (60)
16/10/25 09:12:33 INFO sparklyr gateway received command identifier (0)
16/10/25 09:12:33 INFO sparklyr gateway searching for session (60)
16/10/25 09:13:33 INFO sparklyr gateway found no mapping for session (60)
```
I tried to connect to spark using spark_connect 3 different times, and each time I could notice in the console  `INFO sparklyr gateway found no mapping for session (sessionID)`

And the error in R prompt was as mentioned above.

I am stuck at this point and does not know how to proceed!

**Comment by roshnamohan** [comment]
@javierluraschi 
It will be of great help if you provide an update on this.

Thanks in Advance

**Comment by javierluraschi** [comment]
@roshnamohan I noticed you are running Spark `1.5.0` which is currently unsupported, `sparklyr` only supports `1.6.*` and newer. However, if you could install `sparklyr` `0.4.21`, then you should be able to get a warning and at least be able to connect and trigger basic operations. Let us know how this goes.

**Comment by roshnamohan** [comment]
@javierluraschi I upgraded sparklyr to 0.4.21 and could connect to spark using spark_connect only after running 

`/opt/cloudera/parcels/CDH-5.5.4-1.cdh5.5.4.p0.9/lib/spark/bin/spark-submit --jars .ivy2/jars/spark-csv_2.10-1.3.0.jar --conf "spark.driver.extraJavaOptions=-Dhttp.proxyHost=<IP> -Dhttp.proxyPort=<port> -Dhttps.proxyHost=<IP> -Dhttps.proxyPort=<port> -Dhttp.proxyUser=<user> -Dhttp.proxyPassword=<****>" --class sparklyr.Backend --packages 'com.databricks:spark-csv_2.11:1.3.0' /usr/lib64/R/library/sparklyr/java/sparklyr-1.6-2.10.jar 8880 603`

However we are not considering it as an option since credentials are to be given in plain text in console and this is our production cluster.

We are planning on upgrade in the cluster, and will try sparklyr on spark 1.6.0.

Thanks & Regards

**Comment by javierluraschi** [comment]
@roshnamohan a properties file should help here, see: http://spark.apache.org/docs/latest/submitting-applications.html#loading-configuration-from-a-file

Could you try defining the following file `/opt/cloudera/parcels/CDH-5.5.4-1.cdh5.5.4.p0.9/lib/spark/conf/spark-defaults.conf` with the values:

```
spark.driver.extraJavaOptions          -Dhttp.proxyHost=<IP> -Dhttp.proxyPort=<port> -Dhttps.proxyHost=<IP> -Dhttps.proxyPort=<port> -Dhttp.proxyUser=<user> -Dhttp.proxyPassword=<****>
```

and retry reconnect?

**Comment by dsblr** [comment]
Hi Javier,
 I am getting the same error. but the output log is different. I am using the most updated package of sparklyr mentioned in the github. I am getting the same error using Rstudio as well as R gui. Please help me to resolve the issue.


sc <- spark_connect(master = "local",config = config)

Error in force(code) : 
 Failed while connecting to sparklyr to port (8880) for sessionid (2044): Gateway in port (8880) did not respond.
 Path: C:\Users\user1\AppData\Local\rstudio\spark\Cache\spark-1.6.2-bin-hadoop2.6\bin\spark-submit2.cmd
 Parameters: --class, sparklyr.Backend, --packages, "com.databricks:spark-csv_2.11:1.3.0", "D:\Users\user1\R\R-3.3.1\library\sparklyr\java\sparklyr-1.6-2.10.jar", 8880, 2044
 Traceback:
 shell_connection(master = master, spark_home = spark_home, app_name = app_name, version = version, hadoop_version = hadoop_version, shell_args = shell_args, config = config, service = FALSE, extensions = extensions)
 start_shell(master = master, spark_home = spark_home, spark_version = version, app_name = app_name, config = config, jars = spark_config_value(config, "spark.jars.default", list()), packages = spark_config_value(config, "sparklyr.defaultPackages"), extensions = extensions, environment = environment, shell_args = shell_args, service = service)
 tryCatch({
 gatewayInfo <- spark_connect_gateway(gatewayAddress, gatewayPort, sessionId, config = config, isStarting = TRUE)
 }, error = function(e) {
 abort_shell(paste("Failed while connecting to sparklyr to port (", gatewayPort, ") for sessionid (", sessionId, "): ", e$message, sep = ""), spark_submit_path, shell_args, output_file, error_file)
 })
 tryCatchList(expr, classes, parentenv, handlers)
 tryCatchOne(expr, names, parentenv, handlers[[1]])
 value[3]
 abort_shell(paste("Failed while connecting to sparklyr to port (", gatewayPort, ") for sessionid (", sessionId, "): ", e$message, sep = ""), spark_submit_path, shell_args, output_file, error_file)

---- Output Log ----
 The system cannot find the path specified.

---- Error Log ----


Session info: 


R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

attached base packages:
 [1] stats graphics grDevices utils datasets methods base 

other attached packages:
 [1] sparklyr_0.4.21

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7 digest_0.6.10 dplyr_0.5.0 withr_1.0.2 rprojroot_1.1 assertthat_0.1 rappdirs_0.3.1 R6_2.2.0 DBI_0.5-1 backports_1.0.4 magrittr_1.5 devtools_1.12.0
 [13] config_0.2 tools_3.3.1 parallel_3.3.1 yaml_2.1.13 memoise_1.0.0 tibble_1.2

**Comment by dsblr** [comment]
---- Output Log ----
 The system cannot find the path specified.
The above error has been solved by changing the JAVA_HOME, Spark don’t recognise the JAVA_HOME, if \bin added to the end of the JAVA_HOME. So I removed the \bin from JAVA_HOME and it started working.

But now I am getting a different error. Please help me on the same.

Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (3787): Gateway in port (8880) did not respond.
    Path: C:\Users\user1\AppData\Local\rstudio\spark\Cache\spark-1.6.2-bin-hadoop2.6\bin\spark-submit2.cmd
    Parameters: --class, sparklyr.Backend, --packages, "com.databricks:spark-csv_2.11:1.3.0", "D:\Users\user1\R\R-3.3.1\library\sparklyr\java\sparklyr-1.6-2.10.jar", 8880, 3787
    Traceback:
      shell_connection(master = master, spark_home = spark_home, app_name = app_name, version = version, hadoop_version = hadoop_version, shell_args = shell_args, config = config, service = FALSE, extensions = extensions)
      start_shell(master = master, spark_home = spark_home, spark_version = version, app_name = app_name, config = config, jars = spark_config_value(config, "spark.jars.default", list()), packages = spark_config_value(config, "sparklyr.defaultPackages"), extensions = extensions, environment = environment, shell_args = shell_args, service = service)
      tryCatch({
    gatewayInfo <- spark_connect_gateway(gatewayAddress, gatewayPort, sessionId, config = config, isStarting = TRUE)
}, error = function(e) {
    abort_shell(paste("Failed while connecting to sparklyr to port (", gatewayPort, ") for sessionid (", sessionId, "): ", e$message, sep = ""), spark_submit_path, shell_args, output_file, error_file)
})
      tryCatchList(expr, classes, parentenv, handlers)
      tryCatchOne(expr, names, parentenv, handlers[[1]])
      value[[3]](cond)
      abort_shell(paste("Failed while connecting to sparklyr to port (", gatewayPort, ") for sessionid (", sessionId, "): ", e$message, sep = ""), spark_submit_path, shell_args, output_file, error_file)

---- Output Log ----
	  file:/C:/Users/user1/.m2/repository/com/databricks/spark-csv_2.11/1.3.0/spark-csv_2.11-1.3.0.pom

	  -- artifact com.databricks#spark-csv_2.11;1.3.0!spark-csv_2.11.jar:

	  file:/C:/Users/user1/.m2/repository/com/databricks/spark-csv_2.11/1.3.0/spark-csv_2.11-1.3.0.jar

	==== local-ivy-cache: tried

	  C:\Users\user1\.ivy2\local\com.databricks\spark-csv_2.11\1.3.0\ivys\ivy.xml

	==== central: tried

	  https://repo1.maven.org/maven2/com/databricks/spark-csv_2.11/1.3.0/spark-csv_2.11-1.3.0.pom

	  -- artifact com.databricks#spark-csv_2.11;1.3.0!spark-csv_2.11.jar:

	  https://repo1.maven.org/maven2/com/databricks/spark-csv_2.11/1.3.0/spark-csv_2.11-1.3.0.jar

	==== spark-packages: tried

	  http://dl.bintray.com/spark-packages/maven/com/databricks/spark-csv_2.11/1.3.0/spark-csv_2.11-1.3.0.pom

	  -- artifact com.databricks#spark-csv_2.11;1.3.0!spark-csv_2.11.jar:

	  http://dl.bintray.com/spark-packages/maven/com/databricks/spark-csv_2.11/1.3.0/spark-csv_2.11-1.3.0.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: com.databricks#spark-csv_2.11;1.3.0: not found

		::::::::::::::::::::::::::::::::::::::::::::::


:::: ERRORS
	Server access error at url https://repo1.maven.org/maven2/com/databricks/spark-csv_2.11/1.3.0/spark-csv_2.11-1.3.0.pom (javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?)

	Server access error at url https://repo1.maven.org/maven2/com/databricks/spark-csv_2.11/1.3.0/spark-csv_2.11-1.3.0.jar (javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?)


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: com.databricks#spark-csv_2.11;1.3.0: not found]
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1068)
	at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:287)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:154)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

---- Error Log ----

**Comment by roshnamohan** [comment]
@javierluraschi, ours is a cloudera managed cluster, and hence we would not prefer exporting credentials in Cloudera Manager in plain text.

We prefer waiting for a spark update to spark 1.6 instead.

**Comment by javierluraschi** [comment]
@javierluraschi With `sparklyr` `0.4.21` you should be able to connect with the password as plain text and something like:

```{r}
config <- spark_config()
config[["sparklyr.shell.conf"]] <- "spark.driver.extraJavaOptions=-Dhttp.proxyHost=<proxy_IP> -Dhttp.proxyPort=<port> -Dhttps.proxyHost=<IP> -Dhttps.proxyPort=<port> -Dhttp.proxyUser=<user> -Dhttp.proxyPassword=<*****>"
sc <- spark_connect(master = "yarn-client", version = "1.5.0", config = config)
```

I understand that passing the password as plain text is not acceptable and too complicated to give to users, in which case, I would recommend setting a helper function for the users of your cluster, something like:

```{r}
spark_connect_wrapper <- function(proxyUser, proxyPassword) {
    config <- spark_config()
    config[["sparklyr.shell.conf"]] <- paste(
        "spark.driver.extraJavaOptions=-Dhttp.proxyHost=<proxy_IP>",
        " -Dhttp.proxyPort=<port>",
        " -Dhttps.proxyHost=<IP>",
        " -Dhttps.proxyPort=<port>",
        " -Dhttp.proxyUser=", proxyUser
        " -Dhttp.proxyPassword=", proxyPassword
        sep = "")
    sc <- spark_connect(master = "yarn-client", version = "1.5.0", config = config)
}
```

Hope this helps - Best, Javier

**Comment by roshnamohan** [comment]
@javierluraschi we have upgraded the cluster to CDH 5.8.3, with spark version 1.6.0, and the spark connection was successful using the package saprklyr. Now we does not have to export proxy with credentials in plain text.

Current sparklyr version is 0.4.34

Thank you for the prompt support!

**Comment by javierluraschi** [comment]
This issue was resolved for the original opener, if there are additional connection issues, please open new ones with the relevant info, thanks!
