### ISSUE TITLE
Error when connect sparklyr to remote Spark cluster

### ISSUE THREAD

**Issue by aissaelouafi** [rstudio/sparklyr#284]
I installed R Studio on the master node of my Spark cluster at localhost, When I tried to connect `sparklyr` to the master node I get the following error message : 

```
`Erreur : Failed during initialize_connection() No status is returned. Spark R backend might have failed.'
```

I used : 
`sc <- spark_connect(master = "spark://localhost:7077", version ="1.6.0",spark_home = "/usr/local/Cellar/spark")`

**Comment by edgararuiz** [comment]
@aissaelouafi - I think your master setting needs to match to what's in the Spark UI, try navigating to your port 8080, to get the right URL:

![spark_arrow](https://cloud.githubusercontent.com/assets/7875923/19954616/9c799f10-a147-11e6-9bb6-7b5eeb7a97e6.jpg)

**Comment by javierluraschi** [comment]
Edgar's suggestion should resolve the issue, if not, let us know to reopen.
