### ISSUE TITLE
Spark doesn't respect config passed to spark_connect()

### ISSUE THREAD

**Issue by kykuo** [rstudio/sparklyr#286]
Following the example in http://spark.rstudio.com/deployment.html I did the following

```
library(sparklyr)
config <- spark_config()
config$spark.driver.memory <- "100G"
sc <- spark_connect(master = "local", config = config)
```

Now `spark.driver.memory` is getting passed to the launcher, as can be seen in:

![image](https://cloud.githubusercontent.com/assets/5582151/19746533/d563dc80-9ba4-11e6-9992-0f34788d5998.png)

But the setting doesn't seem to be taking effect:
![image](https://cloud.githubusercontent.com/assets/5582151/19746562/f5b99524-9ba4-11e6-9890-f29720d01bf2.png)

However, if we specify
`SPARK_DRIVER_MEMORY=100g` in `spark-env.sh`, it works:

```
spark_disconnect_all()
sc <- spark_connect(master = "local")
```
![image](https://cloud.githubusercontent.com/assets/5582151/19746756/d6036592-9ba5-11e6-8862-fd61665a697f.png)

So it seems like something is missing during the launching of the JVM?

**Comment by javierluraschi** [comment]
@kykuo  See http://stackoverflow.com/questions/26562033/how-to-set-apache-spark-executor-memory

You would need to run instead:

```{r}
config <- spark_config()
config$`sparklyr.shell.driver-memory` <- "4G"
sc <- spark_connect(master = "local", config = config)
```

Reason is that, in local mode, the setting needs to be set before starting the `JVM`.
