### ISSUE TITLE
running sparklyr and getting memory error

### ISSUE THREAD

**Issue by mkaja** [rstudio/sparklyr#287]
> sparklyr::spark_installed_versions()
>   spark hadoop                       dir
> 1 1.6.0    2.6 spark-1.6.0-bin-hadoop2.6
> 2 1.6.1    2.6 spark-1.6.1-bin-hadoop2.6
> packageVersion("sparklyr")
> [1] ‘0.3.7’
> 
> sessionInfo()
> R version 3.3.0 (2016-05-03)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 14.04.4 LTS

l 
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.5.0       sparklyr_0.3.7    fingerprint_3.5.2

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7        digest_0.6.10      withr_1.0.2        rprojroot_1.0-2    assertthat_0.1     rappdirs_0.3.1  
 [7] R6_2.1.3           DBI_0.5            magrittr_1.5       config_0.2         tools_3.3.0        readr_1.0.0  
[13] nycflights13_0.2.0 yaml_2.1.13        parallel_3.3.0     tibble_1.1     

it runs on an emr 4.3

> library(dplyr)
> flights_tbl <- copy_to(sc, nycflights13::flights, "flights")
> 
> vars<-colnames(flights_tbl)[-6]
> fit<-ml_linear_regression(flights_tbl,response = "dep_delay", features = vars )
> Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 27.0 failed 4 times, most recent failure: Lost task 0.3 in stage 27.0 (TID 1942,  ip-ec2.internal): org.apache.spark.SparkException: Values to assemble cannot be null.
>     at org.apache.spark.ml.feature.VectorAssembler$$anonfun$assemble$1.apply(VectorAssembler.scala:154)
>     at org.apache.spark.ml.feature.VectorAssembler$$anonfun$assemble$1.apply(VectorAssembler.scala:137)
>     at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
>     at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
>     at org.apache.spark.ml.feature.VectorAssembler$.assemble(VectorAssembler.scala:137)
>     at org.apache.spark.ml.feature.VectorAssembler$$anonfun$3.apply(VectorAssembler.scala:95)
>     at org.apache.spark.ml.feature.VectorAssembler$$anonfun$3.apply(VectorAssembler.scala:94)
>     at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown

**Comment by javierluraschi** [comment]
@mkaja seems you have and old version of `sparklyr` (`0.3.7`). I would upgrade to the CRAN version `0.4` using:

```{r}
install.packages("sparklyr")
```

or the development version using:

```{r}
devtools::install_github("rstudio/sparklyr")
```

**Comment by mkaja** [comment]
i tried in a diff machine where we have latest , but still fails

> packageVersion("sparklyr")
[1] ‘0.4.6’

Error: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at scala.StringContext.standardInterpolator(StringContext.scala:122)
	at scala.StringContext.s(StringContext.scala:90)
	at org.apache.spark.sql.execution.QueryExecution.toString(QueryExecution.scala:70)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:52)
	at org.apache.spark.sql.DataFrame.withNewExecutionId(DataFrame.scala:2125)
	at org.apache.spark.sql.DataFrame.org$apache$spark$sql$DataFrame$$execute$1(DataFrame.scala:1537)
	at org.apache.spark.sql.DataFrame$$anonfun$org$apache$spark$sql$

**Comment by javierluraschi** [comment]
Could you try increasing memory with something like the following?

```{r}
config <- spark_config()
config$`sparklyr.shell.driver-memory` <- "4G"
config$`sparklyr.shell.executor-memory` <- "4G"
sc <- spark_connect(master = "local", config = config)
```

**Comment by mkaja** [comment]
Thanks Javieluraschi - i tried with that

Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 27.0 failed 4 times, most recent failure: Lost task 0.3 in stage 27.0 (TID 1941, ip- .ec2.internal): ExecutorLostFailure (executor 6 exited caused by one of the running tasks) Reason: Container killed by YARN for exceeding memory limits. 1.4 GB of 1.4 GB physical memory used. Consider boosting spark.yarn.executor.memoryOverhead.
Driver stacktrace:
    at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1431)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1419)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1418)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGSched

**Comment by javierluraschi** [comment]
@mkaja since the log is pointing out `Consider boosting spark.yarn.executor.memoryOverhead.`. Can you try the following?

```{r}
config <- spark_config()
config$`sparklyr.shell.driver-memory` <- "4G"
config$`sparklyr.shell.executor-memory` <- "4G"
config$`spark.yarn.executor.memoryOverhead` <- "1G"
sc <- spark_connect(master = "local", config = config)
```

This documents could help: How to tune your apache Spark jobs [Part 1](https://blog.cloudera.com/blog/2015/03/how-to-tune-your-apache-spark-jobs-part-1/) and [Part 2](https://blog.cloudera.com/blog/2015/03/how-to-tune-your-apache-spark-jobs-part-2/)

**Comment by mkaja** [comment]
> library(sparklyr)
> Sys.setenv(SPARK_HOME= "/home/mkaja/.cache/spark/spark-1.6.0-bin-hadoop2.6")
> Sys.setenv(HADOOP_CONF_DIR= "/etc/hadoop/conf")
> config <- spark_config()
> config$`sparklyr.shell.driver-memory` <- "4G"
> config$`sparklyr.shell.executor-memory` <- "4G"
> config$`spark.yarn.executor.memoryOverhead` <- "1G"
> sc <- spark_connect(master = "yarn-client", config = config)
Error: Failed during initialize_connection() java.lang.NumberFormatException: For input string: "1G"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)

**Comment by mkaja** [comment]
javierluraschi -thanks for ur help - i tried with the spark config settings and still i get resource issues .. ExecutorLostFailure (executor 6 exited caused by one of the running tasks) Reason: Container killed by YARN for exceeding memory limits. 1.7 GB of 1.4 GB physical memory used. Consider boosting spark.yarn.executor.memoryOverhead.

**Comment by javierluraschi** [comment]
@mkaja Looks like the issue is the value of the `spark.yarn.executor.memoryOverhead` is not right, sometimes `1G` is case sensitive, how about:

```{r}
config <- spark_config()
config$`sparklyr.shell.driver-memory` <- "4G"
config$`sparklyr.shell.executor-memory` <- "4G"
config$`spark.yarn.executor.memoryOverhead` <- "1g"
sc <- spark_connect(master = "local", config = config)
```

or

```{r}
config <- spark_config()
config$`sparklyr.shell.driver-memory` <- "4G"
config$`sparklyr.shell.executor-memory` <- "4G"
config$`spark.yarn.executor.memoryOverhead` <- "512"
sc <- spark_connect(master = "local", config = config)
```

**Comment by edgararuiz** [comment]
Could this be caused by actual RAM available in the machine, at the time of copying the data?

**Comment by mkaja** [comment]
Ed - i check the memory usage on server while copying the data and it had free 7g

**Comment by monicarodguev** [comment]
Hi everyone, 

I'm working locally. I'm training a decision tree and I'm getting a similar error. I already defined the driver and executor memory with:

```
config$`sparklyr.shell.driver-memory` <- "4G"
config$`sparklyr.shell.executor-memory` <- "4G"

sc <-
  spark_connect(
    master = "local",
    spark_home = spark_home_dir(version = "2.0.2"),
    config = config
  )
```

When I defined the memory to 4G I get the following error:

`Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 6.0 failed 1 times, most recent failure: Lost task 0.0 in stage 6.0 (TID 6, localhost): org.spark_project.guava.util.concurrent.ExecutionError: java.lang.OutOfMemoryError: GC overhead limit exceeded`

Could you please help me with this error? Please let me know if there is any other important information I'm not telling you.

**Comment by dsblr** [comment]
@javierluraschi thanks for the solution. It works for me.
@monicarodguev try setting up an additional parameter 
config$`spark.yarn.executor.memoryOverhead` <- "1g"  then create sc. It works for me, hope it helps.

**Comment by KarthiAru** [comment]
@javierluraschi thanks for the solution. `512mb` worked for me.

**Comment by javierluraschi** [comment]
Most users are reporting the suggested cluster settings solved this issue.

**Comment by leeivan** [comment]
I choose the model as "local",So I just used:
config$`sparklyr.shell.driver-memory` <- "50G"
It is working for me.
