### ISSUE TITLE
Unable to run spark_connect

### ISSUE THREAD

**Issue by ganesh3** [rstudio/sparklyr#288]
I am running 
Windows 10
sparklyr 0.4
RStudio 0.99.90

sc <- spark_connect(master = "local")
Error in start_shell(master = master, spark_home = spark_home, spark_version = version,  : 
  Failed to launch Spark shell. Ports file does not exist.
    Path: C:\Users\Ganesh Bhat\AppData\Local\rstudio\spark\Cache\spark-1.6.2-bin-hadoop2.6\bin\spark-submit.cmd
    Parameters: --class, sparklyr.Backend, --packages, "com.databricks:spark-csv_2.11:1.3.0","com.amazonaws:aws-java-sdk-pom:1.10.34", "C:\Users\Ganesh Bhat\Documents\R\win-library\3.3\sparklyr\java\sparklyr-1.6-2.10.jar", C:\Users\GANESH~1\AppData\Local\Temp\RtmpqS3fQ4\file100c127175e0.out

'C:\Users\Ganesh' is not recognized as an internal or external command,
operable program or batch file.

R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_India.1252  LC_CTYPE=English_India.1252    LC_MONETARY=English_India.1252
[4] LC_NUMERIC=C                   LC_TIME=English_India.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sparklyr_0.4

loaded via a namespace (and not attached):
 [1] magrittr_1.5    R6_2.1.3        assertthat_0.1  rprojroot_1.0-2 parallel_3.3.1 
 [6] DBI_0.5-1       tools_3.3.1     withr_1.0.2     dplyr_0.5.0     rappdirs_0.3.1 
[11] yaml_2.1.13     tibble_1.2      Rcpp_0.12.7     config_0.2      digest_0.6.10

**Comment by javierluraschi** [comment]
@ganesh3  `sparklyr` `0.4` has some connectivity issues on Windows. A good amount of improvements are available in development branch, if you want to try a fix for this you can install the `devtools` package and run:

```{r}
devtools::install_github("rstudio/sparklyr")
```

**Comment by ganesh3** [comment]
Thanks this worked but now getting a new error:

Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'C:\Users\GANESH~1\AppData\Local\Temp\RtmpcFFW2A\file1d603961543c_spark.log': Permission denied

Please help on this one.

**Comment by ganesh3** [comment]
Its working now not sure what was the issue. Thanks.

**Comment by dsblr** [comment]
@ganesh3 could you please share what changes you made to resolve the error: 
Error in file(con, "r") : cannot open the connection
 In addition: Warning message:
 In file(con, "r") : 
I am also getting the similar error please help me to resolve the issue.

**Comment by vermouthmjl** [comment]
I saw somewhere that on windows, you shouldn't install spark into a folder with space in the path. Typically you would get things of the sort 
`'C:\Users\Ganesh' is not recognized as an internal or external command`
if you do.

**Comment by yijutseng** [comment]
@dsblr 
I got the same error message when I use spark version 2.0.0 & sparklyr 0.5.3-9002.
However, after installing spark version 2.1.0, everything goes well.

`library(sparklyr)`
`library(dplyr)`
`spark_install(version = "2.1.0")`
`sc <- spark_connect(master = "local", version = "2.1.0")`

My session info:
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Btw, I still got the following warnings:

> Warning message:
In prepare_windows_environment(spark_home) :
  HADOOP_HOME was already but does not match current Spark installation

**Comment by dsblr** [comment]
@yijutseng its not the version issue, this issue related to file permission. 
As per my understanding this is related to TEMP and TMP folder level permission on windows. Or this might be related to file creation permission. Every time you start sc <- spark_connect(), its tries to create a folder and file to write the log files.
I have checked with 2.1.0 version as well, same issue persists. 

For warning HADOOP_HOME: Change your HADOOP_HOME to you current SPARK_HOME/tmp/hadoop , you wont get any warning.

**Comment by javierluraschi** [comment]
Original opener reports issue resolved, please open new issues for those that are still experiencing issues, thanks!
