### ISSUE TITLE
Defaults in spark_read_*

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/sparklyr#291]
Wondering why we currently have `memory = TRUE` as default. Shouldn't persisting/caching be deliberate actions?

**Comment by javierluraschi** [comment]
`sparklyr` was designed with a goal to make Spark easy to use to the R community. Therefore, we would want to help the r community maximize their time in the analysis of data while minimizing interactions with the cluster internals.

We set `memory=TRUE` to minimize knowledge of the internals of Spark while still getting great performance, once the cluster limitations become apparent to users (i.e. they run out of memory), they would have to learn about this parameter and deliberately choose the resources that are cached.
