### ISSUE TITLE
sdf_load_table get error

### ISSUE THREAD

**Issue by catlain** [rstudio/sparklyr#294]
using sparklyr 0.5 (installed by devtools::install_github("rstudio/sparklyr") to run sdf_load_table a spark 1.6.1

`mutualInformation<-sdf_load_table(sc, "mutualInformation")`

i get this error(but use sparklyr 0.4 can pass with no error :

> Error: java.lang.AssertionError: assertion failed: No predefined schema found, and no Parquet data files or summary files found under file:/tmp/spark-c42045c6-4644-42f7-8d7f-7870884ca8ea/metastore/mutualInformation.
>   at scala.Predef$.assert(Predef.scala:179)
>   at org.apache.spark.sql.execution.datasources.parquet.ParquetRelation$MetadataCache.org$apache$spark$sql$execution$datasources$parquet$ParquetRelation$MetadataCache$$readSchema(ParquetRelation.scala:512)
>   at org.apache.spark.sql.execution.datasources.parquet.ParquetRelation$MetadataCache$$anonfun$12.apply(ParquetRelation.scala:421)
>   at org.apache.spark.sql.execution.datasources.parquet.ParquetRelation$MetadataCache$$anonfun$12.apply(ParquetRelation.scala:421)
>   at scala.Option.orElse(Option.scala:257)
>   at org.apache.spark.sql.execution.datasources.parquet.ParquetRelation$MetadataCache.refresh(ParquetRelation.scala:421)
>   at org.apache.spark.sql.execution.datasources.parquet.ParquetRelation.org$apache$spark$sql$execution$datasources

sessionInfo is 

`sessionInfo()`

> R version 3.3.1 (2016-06-21)
> Platform: x86_64-redhat-linux-gnu (64-bit)
> Running under: CentOS release 6.5 (Final)
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8  
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] magrittr_1.5     dplyr_0.5.0      rsparkling_0.1.0 h2o_3.10.0.8     statmod_1.4.26   sparklyr_0.4.21 
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.7     withr_1.0.2     digest_0.6.10   rprojroot_1.0-2 assertthat_0.1  bitops_1.0-6    R6_2.1.3        jsonlite_1.1    DBI_0.5-1       devtools_1.12.0
> [11] config_0.2      tools_3.3.1     RCurl_1.95-4.8  parallel_3.3.1  yaml_2.1.13     memoise_1.0.0   tibble_1.2   

and spark sc is like

> $master
> [1] "yarn-client"
> 
> $method
> [1] "shell"
> 
> $app_name
> [1] "sparklyr"
> 
> $config
> $config$spark.env.SPARK_LOCAL_IP.local
> [1] "127.0.0.1"
> 
> $config$sparklyr.cores.local
> [1] 16
> 
> $config$spark.sql.shuffle.partitions.local
> [1] 16
> 
> $config$sparklyr.defaultPackages
> [1] "com.databricks:spark-csv_2.11:1.3.0"    "com.amazonaws:aws-java-sdk-pom:1.10.34" "org.apache.hadoop:hadoop-aws:2.7.1"    
> 
> $config$spark.executor.instances
> [1] 20
> 
> $config$spark.executor.cores
> [1] 9
> 
> $config$spark.memory.fraction
> [1] 0.75
> 
> $config$spark.memory.storageFraction
> [1] 0.5
> 
> $config$spark.sql.shuffle.partitions
> [1] 720
> 
> $config$spark.default.parallelism
> [1] 720
> 
> $config$spark.shuffle.sort.bypassMergeThreshold
> [1] 180
> 
> $config$spark.executor.memory
> [1] "30G"
> 
> $config$spark.driver.cores
> [1] 4
> 
> $config$spark.driver.memory
> [1] "5G"
> 
> $config$spark.driver.maxResultSize
> [1] "3G"
> 
> $config$spark.yarn.queue
> [1] "dev-china"
> 
> $config$spark.yarn.driver.memoryOverhead
> [1] 1024
> 
> $config$spark.yarn.executor.memoryOverhead
> [1] 2096
> 
> $config$spark.task.maxFailures
> [1] 720
> 
> $config$spark.speculation
> [1] TRUE
> 
> $config$spark.speculation.interval
> [1] "2000ms"
> 
> $config$spark.speculation.multiplier
> [1] 2
> 
> $config$spark.speculation.quantile
> [1] 0.85
> 
> $config$spark.yarn.max.executor.failures
> [1] 180
> 
> $config$spark.network.timeout
> [1] 600
> 
> $config$sparklyr.backend.timeout
> [1] 2592000
> 
> $config$spark.executor.extraJavaOptions
> [1] "-XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:+CMSClassUnloadingEnabled"
> 
> $spark_home
> [1] "/usr/hdp/2.4.2.0-258/spark"
> 
> $backend
>         description               class                mode                text              opened            can read           can write 
> "->localhost:54734"          "sockconn"                "wb"            "binary"            "opened"               "yes"               "yes" 
> 
> $monitor
>         description               class                mode                text              opened            can read           can write 
> "->localhost:25997"          "sockconn"                "rb"            "binary"            "opened"               "yes"               "yes" 
> 
> $output_file
> [1] "/tmp/Rtmpxj1Gie/file1676910aa41e0_spark.log"
> 
> $spark_context
> <jobj[25]>
>   class org.apache.spark.SparkContext
>   org.apache.spark.SparkContext@7c25e763
> 
> $java_context
> <jobj[26]>
>   class org.apache.spark.api.java.JavaSparkContext
>   org.apache.spark.api.java.JavaSparkContext@46cf8bbd
> 
> $hive_context
> <jobj[27]>
>   class org.apache.spark.sql.hive.HiveContext
>   org.apache.spark.sql.hive.HiveContext@57bda1fc
> 
> attr(,"class")
> [1] "spark_connection"       "spark_shell_connection" "DBIConnection" 

 thanks

**Comment by catlain** [comment]
and if i run spark_installed_versions() get 

> [1] spark  hadoop dir   
> <0 rows> (or 0-length row.names)

run spark_install_dir() get

> "/home/myaccount/.cache/spark"

**Comment by kevinushey** [comment]
I'm guessing that you need to explicitly set the path to the hive metastore (where these files are saved) explicitly. Maybe the default directory changed?

**Comment by catlain** [comment]
thanks , and how to set this path?

**Comment by catlain** [comment]
btw if i use `sdf_load_table(sc, "dmp.sdk_dau")`  i get error

when i change it to
 `sdf_load_table1 <- function (sc, name) 
{
    session <- spark_session(sc)
    name <- ensure_scalar_character(name)
    reader <- invoke(session, "read")
    sdf <- invoke(reader, "table", name)
    sdf_register(sdf)
} `

it works .  spark 1.6.1

**Comment by javierluraschi** [comment]
This function was deprecated in favor of `spark_read_table` and improvements were made, also from the log looks like the original issue was resolved and/or not clear this was specific to the particular machine configuration.
