### ISSUE TITLE
ML functions do not respect table groupings

### ISSUE THREAD

**Issue by CreRecombinase** [rstudio/sparklyr#296]
functions such as `ml_linear_regression` do not respect the groupings imposed on a `tbl_spark` imposed by `dplyr`'s `group_by` operation. In theory this should be able to work, no? 

`library(sparklyr)`
`library(dplyr)`

`sc <- spark_connect(master="local")`

`iris_tbl <- copy_to(sc,iris,name="iris_tbl")`

`irislm <- group_by(iris_tbl,Species) %>%`
`do(fit=ml_linear_regression(.,response="Sepal_Length",features="Petal_length")) %>%`
`collect()`

`irislm`
`Source: local data frame [3 x 2]`
`Groups: <by row>`

`# A tibble: 3 × 2`
`Species    fit`
`*      <chr> <list>`
`1 versicolor <NULL>`
`2     setosa <NULL>`
`3  virginica <NULL>`

Thanks so much

**Comment by kevinushey** [comment]
It seems like we could make this work with a `do_.tbl_spark` implementation. However, I don't expect that the resulting objects may not be easy to manipulate.

**Comment by edgararuiz** [comment]
@CreRecombinase I'm not sure that this will work in a non-Spark pipe.  I would suggest doing the grouping inside the model's formula.  In a sparklyr session, the results are sent back to your Environment variable so you can easily collect what you need, like the coefficients:

`ilibrary(sparklyr)
library(dplyr)
sc <- spark_connect(master="local")
iris_tbl <- copy_to(sc,iris,name="iris_tbl")

irislm <- (ml_linear_regression(iris_tbl, Sepal_Length~Petal_Length+Species))$coefficients
`

Hope this help you

**Comment by kevinushey** [comment]
FWIW now that we have `do` the following should do what you expect (make sure you have the development version of `sparklyr`)

```
iris_tbl %>%
  group_by(Species) %>%
  do(model = ml_linear_regression(., Sepal_Length ~ Petal_Length + Species))
```

**Comment by javierluraschi** [comment]
Correct, we have support for serial `do`, more info on `sparklyr 0.5` blog post: https://blog.rstudio.org/2017/01/24/sparklyr-0-5/ - In the future, we would like to add support for parallel `do`.
