### ISSUE TITLE
SparkContext lost after stopping operation in console

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/sparklyr#297]
This is annoying since it requires re-launching the spark session...

```
sc <- spark_connect(master = "local", version = "2.0.0")
iris_tbl <- copy_to(sc, iris) ## hit STOP right after executing this line
# > spark_context(sc)
# Error in as.vector(x, "character") : 
#   cannot coerce type 'environment' to vector of type 'character'
```

**Comment by kevinushey** [comment]
The problem here is that interrupting the R session does not also interrupt the pending Spark computation, and so the connection effectively gets out of sync.

@javierluraschi, are we going to be able to recover from this state more nicely with the new connection gateway work?

**Comment by javierluraschi** [comment]
Tracked now by https://github.com/rstudio/sparklyr/issues/948
