### ISSUE TITLE
Error: C stack usage is too close to the limit - ml_random_forest

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/sparklyr#298]
Tried running a random forest classification on a relative large dataset (87mil rows x 3 predictors) and got a C stack error. The Spark log blew up (>200MB) and most of it looks like C code, here's a snippet:

```
/* 115280 */     if (nonnull < 4307) {
/* 115281 */
/* 115282 */       boolean isNull17057 = true;
/* 115283 */       boolean value17057 = false;
/* 115284 */
/* 115285 */       boolean isNull17058 = i.isNullAt(21);
/* 115286 */       UTF8String value17058 = isNull17058 ? null : (i.getUTF8String(21));
/* 115287 */       if (!isNull17058) {
/* 115288 */
/* 115289 */         Object obj4253 = ((Expression) references[4253]).eval(null);
/* 115290 */         UTF8String value17059 = (UTF8String) obj4253;
/* 115291 */
/* 115292 */         isNull17057 = false; // resultCode could change nullability.
/* 115293 */         value17057 = value17058.equals(value17059);
/* 115294 */
/* 115295 */       }
/* 115296 */       boolean isNull17056 = isNull17057;
/* 115297 */       double value17056 = -1.0;
/* 115298 */       if (!isNull17057) {
/* 115299 */         value17056 = value17057 ? 1.0d : 0.0d;
/* 115300 */       }
/* 115301 */       if (!isNull17056 && !Double.isNaN(value17056)) {
/* 115302 */         nonnull += 1;
/* 115303 */       }
/* 115304 */     }
/* 115305 */
/* 115306 */
/* 115307 */     if (nonnull < 4307) {
/* 115308 */
/* 115309 */       boolean isNull17061 = true;
/* 115310 */       boolean value17061 = false;
/* 115311 */
/* 115312 */       boolean isNull17062 = i.isNullAt(21);
/* 115313 */       UTF8String value17062 = isNull17062 ? null : (i.getUTF8String(21));
/* 115314 */       if (!isNull17062) {
/* 115315 */
/* 115316 */         Object obj4254 = ((Expression) references[4254]).eval(null);
/* 115317 */         UTF8String value17063 = (UTF8String) obj4254;
/* 115318 */
/* 115319 */         isNull17061 = false; // resultCode could change nullability.
/* 115320 */         value17061 = value17062.equals(value17063);
/* 115321 */
/* 115322 */       }
/* 115323 */       boolean isNull17060 = isNull17061;
/* 115324 */       double value17060 = -1.0;
/* 115325 */       if (!isNull17061) {
/* 115326 */         value17060 = value17061 ? 1.0d : 0.0d;
/* 115327 */       }
/* 115328 */       if (!isNull17060 && !Double.isNaN(value17060)) {
/* 115329 */         nonnull += 1;
/* 115330 */       }
/* 115331 */     }
/* 115332 */
/* 115333 */
/* 115334 */     if (nonnull < 4307) {
/* 115335 */
/* 115336 */       boolean isNull17065 = true;
/* 115337 */       boolean value17065 = false;
/* 115338 */
/* 115339 */       boolean isNull17066 = i.isNullAt(21);
/* 115340 */       UTF8String value17066 = isNull17066 ? null : (i.getUTF8String(21));
/* 115341 */       if (!isNull17066) {
/* 115342 */
/* 115343 */         Object obj4255 = ((Expression) references[4255]).eval(null);
/* 115344 */         UTF8String value17067 = (UTF8String) obj4255;
/* 115345 */
/* 115346 */         isNull17065 = false; // resultCode could change nullability.
/* 115347 */         value17065 = value17066.equals(value17067);
/* 115348 */
/* 115349 */       }
/* 115350 */       boolean isNull17064 = isNull17065;
/* 115351 */       double value17064 = -1.0;
/* 115352 */       if (!isNull17065) {
/* 115353 */         value17064 = value17065 ? 1.0d : 0.0d;
/* 115354 */       }
/* 115355 */       if (!isNull17064 && !Double.isNaN(value17064)) {
/* 115356 */         nonnull += 1;
/* 115357 */       }
/* 115358 */     }
/* 115359 */
```

Are we deserializing and doing missing handling row by row somewhere?

More info:

Spark WebUI shows the latest failed stage to be `count at NativeMethodAccessorImpl.java:-2` and the reason for failure 

> Job aborted due to stage failure: Task 8 in stage 191.0 failed 1 times, most recent failure: Lost task 8.0 in stage 191.0 (TID 1945, localhost): java.util.concurrent.ExecutionException: java.lang.Exception: failed to compile: org.codehaus.janino.JaninoRuntimeException: Code of method &quot;(Lorg/apache/spark/sql/catalyst/InternalRow;)Z&quot; of class &quot;org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificPredicate&quot; grows beyond 64 KB

C stack info at failure:

```
> Cstack_info()
      size    current  direction eval_depth 
   7969177      15056          1          2 
```

**Comment by kevinushey** [comment]
Thanks for the bug report -- any chance you can provide a reproducible example? (For example, with some R code to generate a data set of sufficient size + shape, copy that to Spark, and then the `ml_` invocation you're using to fit the model)

**Comment by henrikhch** [comment]
Hi, I have the same issue even running logistic regression on a dataset of 6 features.

**Comment by javierluraschi** [comment]
I doubt `sparklyr` is the culprit of this problem, most likely a limitation in spark, unless someone can find this works in python/scala/sparkr; that said, worth investigating on our side.

**Comment by TinyOcean** [comment]
I got the same error applying a "gbt" model to a 15000*544 data.
```
  data_tbl <- data_tbl %>% 
    na.replace(0) # %>%
  data_tbl %>% 
    na.omit() %>%
    sdf_predict(model, .) 
```

>  Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 459.0 failed 1 times, most recent failure: Lost task 1.0 in stage 459.0 (TID 1070, localhost, executor driver): java.util.concurrent.ExecutionException: java.lang.Exception: failed to compile: org.codehaus.janino.JaninoRuntimeException: Code of method "eval(Lorg/apache/spark/sql/catalyst/InternalRow;)Z" of class "org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificPredicate" grows beyond 64 KB
> /* 001 */ public SpecificPredicate generate(Object[] references) {
> /* 002 */   return new SpecificPredicate(references);
> /* 003 */ }
> /* 004 */
> 

So does it mean this problem is unsolvable currently?

**Comment by kevinykuo** [comment]
Closing for now since it doesn't seem like a `sparklyr` problem. If anyone comes across this again and can provide a reprex we'll look into it.
