### ISSUE TITLE
spark_install failure with R 3.3.2

### ISSUE THREAD

**Issue by kevinushey** [rstudio/sparklyr#302]
I'm seeing:

```
> spark_install(version = "1.6.2")
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match
```

with

```
> sessionInfo()
R version 3.3.2 RC (2016-10-25 r71587)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.1
```

I'll dig in more.

**Comment by kevinushey** [comment]
The issue is caused by https://github.com/rstudio/sparklyr/commit/8fed153fc215e174a67728bb6d81dbc65cbbb0e9:

@javierluraschi, I think this change will effectively break any old installations of `sparklyr` that attempt to query for the currently installed version. You can reproduce with e.g.

```
install.packages("sparklyr")
<restart R session>
sparklyr:::spark_versions()
```

I don't think we should change the .csv format here.

**Comment by javierluraschi** [comment]
Thanks @kevinushey, merged this back without a csv schema change.
