### ISSUE TITLE
Rstudio Not Responding Once Open (Mac)

### ISSUE THREAD

**Issue by dwy904** [rstudio/sparklyr#303]
The Rstudio can be opened. 

However, after open it for 3 seconds, I will not be able to click anything on Rstudio. It stuck there forever, I will not be able to do anything with that. After connected to spark last time I worked on the project. It never got back normal.

I have tried multiple versions of Rstudio, it gave the same outcome. And I have no problem using R from the terminal. It works totally fine. 

I have connected to Spark serval times doing my machine learning project through Rstudio. There were some errors popped up when I was using some of the ML functions. The next day I wanna open up my Rstudio, it end up like this. 
	
I can open another Rstudio on terminal ('$open ~/.rstudio-desktop/log/') and write code on it with no problem. But the first Rstudio is still stuck there forever.

I have totally no idea what happened to it.

**Comment by kevinushey** [comment]
Hi Weiye,

Please avoid cross-posting, or let us know specifically when you're cross-posting a post in multiple locations. (https://support.rstudio.com/hc/en-us/community/posts/222224208-Help-Please-Rstudio-Not-Responding-Once-Open-Mac-)

Can you please elaborate on:

> However, after open it for 3 seconds, I will not be able to click anything on Rstudio. It stuck there forever, I will not be able to do anything with that. After connected to spark last time I worked on the project. It never got back normal.

Ie, are you attempting to execute any action, or does the IDE simply become unresponsive after an (otherwise successful) startup?

**Comment by dwy904** [comment]
I apologize for that.

**Comment by kevinushey** [comment]
Thanks (sorry, I definitely didn't want to come off adversarial just that cross-posting is generally discouraged).

You can also try running a diagnostics report: https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report; the output of that may be helpful.

**Comment by dwy904** [comment]
I am not really good at reading that report, would you mind if I can pass
that to you?

**Comment by kevinushey** [comment]
Yes, please feel free to either post it as a GitHub gist (http://gist.github.com) or just send it via email to kevin <at> rstudio <dot> com.

**Comment by dwy904** [comment]
Is the email address 'kevin@rstudio.com' ?

**Comment by kevinushey** [comment]
Yes, that's correct.

**Comment by javierluraschi** [comment]
RStudio issue moved to RStudio forum.
