### ISSUE TITLE
Sparklyr connection issue on Mac OS Sierra

### ISSUE THREAD

**Issue by IgrIss** [rstudio/sparklyr#306]
Hi! i saw lots of issues and resolutions for WINDOWS systems.
However, i didn't find a solution for Mac Os. i tried 'simple' versions to connect without any luck. Then i also tried different versions like this:

> defaultPackages <- NULL
> config <- list("config.sparklyr.cores.local" = 4,"config.spark.sql.shuffle.partitions.local"=4,"sparklyr.defaultPackages"=defaultPackages)
> sc <- spark_connect(master = "local", config = config, version = '2.0.1')
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (2412): Gateway in port (8880) did not respond.
    Path: /Users/user1/Library/Caches/spark/spark-2.0.1-bin-hadoop2.7/bin/spark-submit
    Parameters: --class, sparklyr.Backend, '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/sparklyr/java/sparklyr-2.0-2.11.jar', 8880, 2412

Now, i tried this from Terminal:

> bash$ /Users/user1/Library/Caches/spark/spark-2.0.1-bin-hadoop2.7/bin/spark-submit --class, sparklyr.Backend, '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/sparklyr/java/sparklyr-2.0-2.11.jar', 8880, 2412
> Error: Unrecognized option: --class

However, spark gets up and running by this:
> bash$ /Users/user1/Library/Caches/spark/spark-2.0.1-bin-hadoop2.7/bin/spark-shell
> Setting default log level to "WARN".
> To adjust logging level use sc.setLogLevel(newLevel).
> 16/11/03 14:09:06 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
> 16/11/03 14:09:07 WARN SparkContext: Use an existing SparkContext, some configuration may not take effect.
> Spark context Web UI available at http://172.23.12.12:4040

Pls help ((

**Comment by javierluraschi** [comment]
@IgrIss could you try reconnecting and paste the full log? The log should contain `---- Output Log ----` and `---- Error Log ----` sessions.

If you want to run this from terminal, we need to get rid of the `,` as in:

```
bash$ /Users/user1/Library/Caches/spark/spark-2.0.1-bin-hadoop2.7/bin/spark-submit --class sparklyr.Backend '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/sparklyr/java/sparklyr-2.0-2.11.jar' 8880 2412
```

**Comment by IgrIss** [comment]
@javierluraschi  Without commas it seems to be starting.. although i didn't understand if that's useful.. ((

>bash$ /Users/user1/Library/Caches/spark/spark-2.0.1-bin-hadoop2.7/bin/spark-submit --class sparklyr.Backend '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/sparklyr/java/sparklyr-2.0-2.11.jar' 8880 2412
> 16/11/03 22:18:46 INFO sparklyr session (2412) starting

**Comment by IgrIss** [comment]
as to Error Output log in Rstudio:

---- Output Log ----
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/spark/launcher/Main : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

---- Error Log ----

**Comment by javierluraschi** [comment]
@IgrIss the error seems related to the Java version. Spark supports version 1.7+ and so does `sparklyr`. However, it's possible than some module is being loaded in your system compiled with Java 8 since version `51.0` is Java 7.

Therefore, try installing Java 8 to try to solve this issue.

See. http://stackoverflow.com/questions/28070863/spark-unsupported-class-version-error

**Comment by IgrIss** [comment]
@javierluraschi 
> bash$ java -version
> java version "1.8.0_111"
> Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
> Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

as i said, spark gets up and running from Terminal, while it doesn't from Rstudio.
Could it be some error with the Path variables?  Windows-alike problem?

**Comment by javierluraschi** [comment]
@IgrIss it does seem that it starts from console so it could be the case that some environment variables are not passing through. What's the output from running `system2("java", "-version")` from R?

Can you share `sessionInfo()` from R to see if we spot something in your globals?
