### ISSUE TITLE
Investigate performance regression from 0.4 in ml_linear_regression

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#308]
Feedback from mail: 0.4.21 appears much slower than the official version 0.4 on cran. For example, I fitted a model with ml_linear_regression() using a table of approx. 3 Mio. rows and 150 columns. On my macbook this took about 3 minutes with 0.4 and more than 6 minutes with 0.4.21.

If `do(mod = ml_linear_regression())` takes more than 30 minutes, I receive error message

```
Error in invoke_method.spark_shell_connection(spark_connection(jobj),  : 
  No status is returned. Spark R backend might have failed.
```

**Comment by kevinushey** [comment]
My best guess is that this was caused by a change that forces eager caching of tables when generating a unique ID for each row in a Spark DataFrame, and that caching is slow.

In other words, I wouldn't be surprised if this is the culprit: https://github.com/rstudio/sparklyr/commit/591fd31d3329d76a4a85d6f73050c7a8f763440f

**Comment by kevinushey** [comment]
I wonder if `profvis()` could give us some useful output here, as well? Presumedly not all of the time is spent in the actual model fitting call...

**Comment by javierluraschi** [comment]
@kevinushey the profiler won't help us here since it discards IO time, opened a feature request in `profvis` to investigate if it's feasible to add support for this in `Rprof` and `R` core.

Here are a couple snapshots from Spark with 3M rows using:

```{r}
library(sparklyr)
library(dplyr)
library(nycflights13)

packageVersion("sparklyr")

flights <- nycflights13::flights

sc <- spark_connect(master = "local")

flights10 <- flights[rep(seq_len(nrow(flights)), each=10),]
flights10 <- na.omit(flights10)

flights10_tbl <- copy_to(sc, flights10)

partitions <- flights10_tbl %>% sdf_partition(training = 0.5, test = 0.5, seed = 1099)

system.time({
  partitions$training %>%
    ml_linear_regression(
      response = "dep_delay",
      features = c("arr_time", "sched_arr_time", "arr_delay"))
})

spark_disconnect_all()
```

With `sparklyr` `0.4`:

```
user  system elapsed 
  0.073   0.017   7.412 
```

<img width="1410" alt="screen shot 2016-11-08 at 12 00 02 pm" src="https://cloud.githubusercontent.com/assets/3478847/20114956/490fbe14-a5ab-11e6-896e-c8d24ddb6369.png">

With `sparklyr` `0.4.21`:

```
   user  system elapsed 
  0.114   0.021   8.399 
```

<img width="1410" alt="screen shot 2016-11-08 at 11 59 49 am" src="https://cloud.githubusercontent.com/assets/3478847/20114964/4f410ac2-a5ab-11e6-9360-3eee10f3721d.png">

Since I'm not experiencing a 2X slowdown with this setup, we will need a similar dump to this one to investigate further.

**Comment by kevinushey** [comment]
Interesting that there are four extra `collect` calls in the development version -- those could account for the slowness (depending on how much data is being collected)

**Comment by javierluraschi** [comment]
I'll start taking a look at this one today...

**Comment by javierluraschi** [comment]
Gave this another shot today with increasing size, but no luck reproeing this even with `100` columns and `1M` rows:

```{r}
config <- spark_config()
config[["sparklyr.shell.driver-memory"]] <- "4G"
sc <- spark_connect(master = "local", config = config)
data <- as.data.frame(replicate(100, rnorm(1000000)))
data_tbl <- copy_to(sc, data, overwrite = TRUE)
partitions <- data_tbl %>% sdf_partition(training = 0.5, test = 0.5, seed = 1099)
system.time({
  partitions$training %>%
    ml_linear_regression(
      response = "V1",
      features = paste("V", 2:100, sep = ""))
})
```

```
* No rows dropped by 'na.omit' call
   user  system elapsed 
  0.328   0.046  13.939 
```

which seems like a descent time. As I mentioned in the previous comment, it does seem that there was a bit of an increase, but have not been able to see the reported 2X slowdown after `0.4`. Will try to get more info on this, but hard to make this actionable without a clear repro.

**Comment by kevinushey** [comment]
What version of Spark was this with? My expectation is that we might see slowdown with Spark 2.0.0 and lower, using tables with a large number of columns (> 200).

**Comment by javierluraschi** [comment]
The run above was using `1.6.1`.

**Comment by javierluraschi** [comment]
I've reproed this (or at least a bad perf regression) with users content in Amazon EMR with a single instance, m3.xlarge (16GB ram), ran out of memory locally with also 16GB but having a dedicated box seems to unblocked this. Here are the perf changes since CRAN in this EMR instance:

With `0.4.0` from CRAN:

```
   user  system elapsed 
  1.400   0.144  246.99
```

With `0.4.6` (e0065bf95c03c9d62992c71b7cc40ed03603a3ae)

```
   user  system elapsed 
  1.412   0.308 253.710
```

With `0.4.9` (300162186407feaaf60e023c9fff75be139df198)

```
   user  system elapsed 
  1.420   0.196 254.233 
```

With `0.4.13` (5e403578507b93d008edecf892f0c5983101db74)

```
   user  system elapsed 
  1.404   0.176 250.625 
```

With `0.4.13` (4728843eceb826c0c2f3be348d7f250e0f4f97b4)

```
 ## Ran for 40+ minutes
```

With https://github.com/rstudio/sparklyr/commit/55dae404a36a29a44aaf25179335ba201b50681a

```
   user  system elapsed 
  2.096   0.480 482.511 
```

With https://github.com/rstudio/sparklyr/commit/8c9ca9fd8c0b6846b4aa5056f8e1208974aa61f9

```
   user  system elapsed 
  2.820   0.516 658.038 
```

With https://github.com/rstudio/sparklyr/commit/9bc4934023a6020c35283fe61b15369ed784566f

```
   user  system elapsed 
  3.784   0.736 875.565 
```

**Comment by javierluraschi** [comment]
Bottom line, this is being caused by 4728843 and 591fd31. However, both changes are needed since one matches behavior for `na.action` and the other one to ensure columns are stable across computations. There is still one fix we could implement that reuses the `na` counts to avoid the shuffling when no rows are dropped, pushing that as a PR.

For reference to other users reading about this: It is recommended to use `na.action = NULL` in `ml` routines if one knows that no `NA`s are present in the dataset.

**Comment by kevinushey** [comment]
I don't think there's much we can do about forcing caching after generating an ID, since otherwise the IDs are computed lazily and there's a number of Spark bugs related to lazy computation of those IDs :/

Does caching of the table generating by `dropped` make a big enough difference?

**Comment by javierluraschi** [comment]
Yes, it does make a big difference in my system. However, I'm scoping the caching to only cases where `dropped` generated a table that we are planning to use, otherwise we revert to using the original `df`. Also, the difference is not big to revert back to `0.4` performance since caching always has overhead, but I think this is acceptable given `0.5` produces stable results in which `0.4` does not in all cases.

**Comment by javierluraschi** [comment]
This has been investigated, closing.
