### ISSUE TITLE
spark_connect() Error in validate_java_version() on AWS EMR Cluster

### ISSUE THREAD

**Issue by yarrick19** [rstudio/sparklyr#309]
@kevinushey @javierluraschi 
Hey guys,

I've been having good luck using `sparklyr` with an AWS EMR instance (5.0.3) with Spark 2.0.1.  My EMR spot instance was just terminated so I stood up another cluster with the same setup.  Now, when trying to connect to spark using `spark_connect()` I'm receiving the following java error:
```
> install.packages('devtools')
> devtools::install_github("rstudio/sparklyr")
> library(sparklyr)
> sc <- spark_connect(master = "yarn-client", version = '2.0.1')
Error in validate_java_version() : 
  Java version not detected. Please download and install Java from https://www.java.com/en/
```

This indicates java is installed:
```
> system('java -version')
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b15)
OpenJDK 64-Bit Server VM (build 25.111-b15, mixed mode)
```
Spark starts fine using `spark-shell`.

Sparklyr version installed is: `sparklyr_0.4.21`  (Unfortunately, I don't know the version I was using previously but it was probably downloaded within the last 7 days.

**Comment by kevinushey** [comment]
Thanks -- it looks like our Java version detection is too strict (we seem to expect the printed version string to match the regex `java version \"([0-9])\\.([0-9]).*`). We'll try to fix this up on the `sparklyr` side.

Thanks for reporting!

**Comment by kevinushey** [comment]
I've pushed a commit that should hopefully improve the situation here -- can you try downloading the latest development version and confirm if all is well on your side?

**Comment by yarrick19** [comment]
@kevinushey 

I am now able to connect successfully.  Thanks so much for the quick response!
