### ISSUE TITLE
How to add and save new attributes in Spark dataframe and parquet file?

### ISSUE THREAD

**Issue by hiltonmbr** [rstudio/sparklyr#310]
Is there any way to add and save new attributes (metadata about dataset and variables) in spark data frame? Does sparklyr offer support for these features, especially for attr() function? 

For instance, I have used iris dataset and put variable labels on it.

library(dplyr)
library(sparklyr)
sc <- spark_connect(master = "local[*]")

d <- iris
attr(d,"variable.labels") <- c(Sepal.Length = "My var label 1",
                                                Sepal.Width =  "My var label 2",
                                                Petal.Length =  "My var label 2", 
                                                Petal.Width =  "My var label 3",
                                                Species  = "My var label 4")
attributes(d)
$variable.labels
    Sepal.Length      Sepal.Width     Petal.Length      Petal.Width          Species 
"My var label 1" "My var label 2" "My var label 2" "My var label 3" "My var label 4"

View(d)
![captura de tela 2016-11-05 as 16 09 39](https://cloud.githubusercontent.com/assets/1009086/20032872/599ecc56-a372-11e6-89c2-9325ef35555e.png)

However, doing the same in Spark context:
df <- copy_to(sc,name="tab",path=d)

$names
[1] "src" "ops"

$class
[1] "tbl_spark" "tbl_sql"   "tbl_lazy"  "tbl" 

View(tbl(sc,"tab"))
![captura de tela 2016-11-05 as 16 11 36](https://cloud.githubusercontent.com/assets/1009086/20032887/8c73c8ca-a372-11e6-93aa-0d2e2c19a70c.png)

attr(df,"variable.labels") <- c(Sepal.Length = "My var label 1",
                                                Sepal.Width =  "My var label 2",
                                                Petal.Length =  "My var label 2", 
                                                Petal.Width =  "My var label 3",
                                                Species  = "My var label 4")

View(tbl(sc,"tab"))
![captura de tela 2016-11-05 as 16 11 36](https://cloud.githubusercontent.com/assets/1009086/20032887/8c73c8ca-a372-11e6-93aa-0d2e2c19a70c.png)

Thanks in advance.

**Comment by javierluraschi** [comment]
Not at the moment @hiltonmbr but thanks for this thoughtful suggestion. I agree with you that this would be nice to have if it were supported in Spark. However, Spark does not seem to support attributes in their `DataSet` nor `DataFrame` so implementing this would end up being ad-hoc and not well integrated and potentially a source of bugs, closing this one.
