### ISSUE TITLE
spark_install fails on win10

### ISSUE THREAD

**Issue by jamiemaclennan** [rstudio/sparklyr#311]
Executing spark_install(version = "1.6.2") fails with the following message

tar (child): Cannot connect to C: resolve failed

I worked around the issue by renaming tar.exe so that R could use the internal implementation.

**Comment by kevinushey** [comment]
This should also be resolved in the development version of `sparklyr` -- did you try that as well?

    devtools::install_github('rstudio/sparklyr')

**Comment by jamiemaclennan** [comment]
That works - thanks
