### ISSUE TITLE
sparklyr als getting a java.lang.NullPointerException error when predicting

### ISSUE THREAD

**Issue by blacknred0** [rstudio/sparklyr#313]
Hi - 
Not sure if this is an issue from my side or not.  I am currently trying to use ALS Matrix Factorization [http://spark.rstudio.com/reference/sparklyr/latest/ml_als_factorization.html](url) in sparklyr (v0.4) with R 3.3.2 (Sincere Pumpkin Patch) on *nix (Mac and Linux).  I am also using Apache Spark compile version 2.0.1 with hadoop 2.7.

I found this issue [https://github.com/rstudio/sparklyr/issues/139](url) which it was fixed, but it doesn't seem to work on my particular case, not sure why.  The file that I am using does not have null/NA/blanks values (since I am using spark-2.0.1-bin-hadoop2.7/data/mllib/als/test.data)

Here is the code that I am using

``` R
library(sparklyr)
library(dplyr)

sc <- spark_connect(master = "local", config = spark_config())
test <- read.table('~/Applications/spark-2.0.1-bin-hadoop2.7/data/mllib/als/test.data', 
   header = FALSE, sep = ',')

test_tbl <- copy_to(sc, test, overwrite = TRUE)
als_model <- test_tbl %>%
  ml_als_factorization(user.column = "V1", item.column = "V2", rating.column = "V3", 
  rank = 10L, regularization.parameter = 0.01, iter.max = 10L, ml.options = ml_options())
predictions = als_model$.model %>% invoke("transform", spark_dataframe(test_tbl))
#sdf_predict(als_model, test_tbl)
sdf_predict(predictions, test_tbl) %>%
  collect
spark_disconnect(sc)
```

error
`Error: java.lang.NullPointerException
	at scala.collection.immutable.StringOps$.length$extension(StringOps.scala:47)
	at scala.collection.immutable.StringOps.length(StringOps.scala:47)
	at scala.collection.IndexedSeqOptimized$class.isEmpty(IndexedSeqOptimized.scala:27)
	at scala.collection.immutable.StringOps.isEmpty(StringOps.scala:29)
	at scala.collection.TraversableOnce$class.nonEmpty(TraversableOnce.scala:111)
	at scala.collection.immutable.StringOps.nonEmpty(StringOps.scala:29)
	at org.apache.spark.ml.attribute.AttributeGroup.<init>(AttributeGroup.scala:42)
	at org.apache.spark.ml.attribute.AttributeGroup.<init>(AttributeGroup.scala:65)
	at org.apache.spark.ml.feature.VectorAssembler.transform(VectorAssembler.scala:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.
`

Thanks for your help in advance

**Comment by kevinushey** [comment]
Thanks for the bug report! I think the issue here is simply that an appropriate `sdf_predict()` method has not yet been implemented for `ml_als` model output.

The following (built off of your example) seems to work fine for me:

```
library(sparklyr)
library(dplyr)

sc <- spark_connect(master = "local", config = spark_config())
file <- file.path(spark_home_dir(), "data/mllib/als/test.data")
test <- read.table(file, header = FALSE, sep = ',')

test_tbl <- copy_to(sc, test, overwrite = TRUE)
als_model <- test_tbl %>%
  ml_als_factorization(
    user.column = "V1",
    item.column = "V2",
    rating.column = "V3",
    rank = 10L,
    regularization.parameter = 0.01,
    iter.max = 10L,
    ml.options = ml_options()
  )

predictions <- als_model$.model %>%
  invoke("transform", spark_dataframe(test_tbl)) %>%
  sdf_register()

predictions
```

**Comment by blacknred0** [comment]
thanks for the share! Glad to hear that it was more of a bug than end-user error :).

I can confirm that I ran this section of your code and it worked fine.

``` R
predictions <- als_model$.model %>%
  invoke("transform", spark_dataframe(test_tbl)) %>%
  collect()
```
