### ISSUE TITLE
support for nested object / method access in 'invoke'?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/sparklyr#317]
It might be useful to make it possible to invoke methods on sub-objects more simply with `invoke`, e.g. given a Spark DataFrame, it might be nice to write:

```
invoke(sdf, "na.drop")
```

rather than

```
sdf %>% invoke("na") %>% invoke("drop")
```

In other words, we could manually split the objects according to `.`s found in the string, and then execute the methods sequentially. Would this be useful, or could it lead to potential confusion? (Does Scala ever let you define methods / objects with names that contain a `.` -- I assume not?)

**Comment by javierluraschi** [comment]
I looked at the `sparklyr` codebase and found a few instances:

```
invoke("schema") %>%
      invoke("length")
```

```
  coefficients <- fit %>%
    invoke("coefficients") %>%
    invoke("toArray")
```

```
  coefficients <- fit %>%
    invoke("coefficients") %>%
    invoke("toArray")
```

```
  residuals <- model$.model %>%
    invoke("summary") %>%
    invoke("residuals")
```

```
  object$.model %>%
    invoke("summary") %>%
    invoke("residuals") %>%
    sdf_read_column("residuals")
```

`.` are also not valid Scala names: http://stackoverflow.com/questions/7656937/valid-identifier-characters-in-scala

Not opposed to this but does not seem like it would have significant use.

This is a more common pattern, but not sure there is a clean way to improve it:

```{r}
    sdf %>%
      invoke("col", input) %>%
      invoke("equalTo", level) %>%
      invoke("cast", "double")
```

**Comment by javierluraschi** [comment]
Actually, how about:

```
  sdf %>%
      invoke_prop(col = input, equalTo = level, cast = "double")
```

And

```
invoke_prop("schema", "length")
```

?

**Comment by javierluraschi** [comment]
Invoke improvements tracked now under https://github.com/rstudio/sparklyr/issues/940
