### ISSUE TITLE
drat repository for sparklyr

### ISSUE THREAD

**Issue by jangorecki** [rstudio/sparklyr#318]
Sparklyr is pretty actively developed, and AFAIK you are pushing to master, which potentially makes a risk of sparklyr to be in a state in which it won't pass unit tests. I would like to plug sparklyr devel into my CI pipeline, but it could be painful to depend on a devel package which might not pass own tests. Ideally would be if you could setup drat repository which would be updated only when unit tests passed fine. Then any downstream packages that imports sparklyr wouldn't be affected by a temporary issues that may always appear in master.

**Comment by javierluraschi** [comment]
@jangorecki do you need the latest version of `sparklyr`? The latest stable release is published in CRAN and marked with this tag: https://github.com/rstudio/sparklyr/tree/v0.4, would it make more sense for you to depend on the released version?

**Comment by jangorecki** [comment]
@javierluraschi I'm already using 0.4, but I read in other issues that many changes has been incorporated since 0.4. It is reasonable to assume that some users will use devel sparklyr for that new stuff, thus I would like to make rsparkling always play well with both devel and CRAN sparklyr. It would be troublesome if an sparklyr update on CRAN would affect our functionality and users would need to wait for an update from our side. Better to spot it as soon as possible, but without tested devel sparklyr it can make extra confusion in our CI pipeline. That will also help you to publish more stable releases to CRAN, as more users will be able to plug devel sparklyr in their tests and increase the number of devel testers.

**Comment by javierluraschi** [comment]
@jangorecki please take a dependency directly to `master`. We (@javierluraschi and @kevinushey) have checks in place to prevent `master` from ever being broken (mostly through feature branches and automatic reverts when the Travis breaks).
