### ISSUE TITLE
Consider implementing dim(), nrow(), ncol() for Spark data frames

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#319]
There was a suggestion to support basic data frame operations in https://github.com/rstudio/sparklyr/issues/315.

This would allow this code to work:

```{r}
sc <- spark_connect(master = "local")
iris_tbl <- sdf_copy_to(sc, iris)

dim(iris_tbl)
nrow(iris_tbl)
ncol(iris_tbl)

# others?
```

While this could be really helpful, it could also create the wrong expectations that an `sdf` supports all the functionality of a `df` including the `[]` and `[[]]` operators.  At the very least, we might want to override `[]`, `[[]]` and others to throw errors that make it clear this is unsupported and point users to `dplyrs` equivalents instead.

@jjallaire @kevinushey Not planning to work on this in the short term, but would be good to have your thoughts on this.

**Comment by jjallaire** [comment]
Yeah, I think we either go all the way with these functions or draw the
line at some point. If it's not too, too much work I don't mind going all
the way but it would be good do this from a principled answer to the
question of whether we want to go there.

**Comment by kevinushey** [comment]
I think it's worth going all the way here, although we should think about how exactly to implement the subsetting methods. I think implementing `[` shouldn't be too bad; it should effectively be translated from:

```
df[rows, cols]
```

to something like:

```
df %>% filter(rows) %>% select(cols)
```

The `[[` and `$` methods could return `Column` proxy objects; depending on how far we want to go we could also implement methods for `==`, `!=`, and so on.

**Comment by jjallaire** [comment]
I tend to agree that going all the way would be a good thing here.

**Comment by javierluraschi** [comment]
For the `0.5` release we are addressing dim(), nrow() and ncol(). Closing for now, we can revisit if we have more feedback to implement `[`, `[[`, etc.

**Comment by mikeaalv** [comment]
I have two data frame in sparklyr which cause several GB each. I inner_join them, and use sdf_dim to see into the size of the resulting dataframe. However, in that process, the memory causes increase a lot and finally crash. Does that mean even though the dataframe is not read into R, it still cause similar amount of memory? I have quite limit memory.
