### ISSUE TITLE
Error when trying to connect to spark 

### ISSUE THREAD

**Issue by ramkrisp** [rstudio/sparklyr#321]
Hi,

I am having the following error when trying to create connection with spark:

`library(sparklyr)
> library(dplyr)
> sc <- spark_connect(master = "local")
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (1368): Gateway in port (8880) did not respond.
    Path: C:\Users\krispra\AppData\Local\rstudio\spark\Cache\spark-2.0.1-bin-hadoop2.7\bin\spark-submit2.cmd
    Parameters: --class, sparklyr.Backend, --jars, "C:/Users/krispra/Documents/R/R-3.2.4revised/library/sparklyr/java/spark-csv_2.11-1.3.0.jar","C:/Users/krispra/Documents/R/R-3.2.4revised/library/sparklyr/java/commons-csv-1.1.jar","C:/Users/krispra/Documents/R/R-3.2.4revised/library/sparklyr/java/univocity-parsers-1.5.1.jar", "C:\Users\krispra\Documents\R\R-3.2.4revised\library\sparklyr\java\sparklyr-2.0-2.11.jar", 8880, 1368

---- Output Log ----
Error occurred during initialization of VM
Could not reserve enough space for 1048576KB object heap

---- Error Log ----`

and this is the session info:
`> session_info()
Session info --------------------------------------------------------------------------
 setting  value                                      
 version  R version 3.2.4 Revised (2016-03-16 r70336)
 system   x86_64, mingw32                            
 ui       RStudio (1.0.44)                           
 language (EN)                                       
 collate  English_United States.1252                 
 tz       America/New_York                           
 date     2016-11-10                                 

Packages ------------------------------------------------------------------------------
 package    * version date       source                           
 ada          2.0-5   2016-05-13 CRAN (R 3.2.5)                   
 assertthat   0.1     2013-12-06 CRAN (R 3.2.4)                   
 backports    1.0.4   2016-10-24 CRAN (R 3.2.5)                   
 config       0.2     2016-08-02 CRAN (R 3.2.5)                   
 curl         0.9.7   2016-04-10 CRAN (R 3.2.4)                   
 DBI          0.5-1   2016-09-10 CRAN (R 3.2.5)                   
 devtools   * 1.12.0  2016-06-24 CRAN (R 3.2.5)                   
 digest       0.6.10  2016-08-02 CRAN (R 3.2.5)                   
 dplyr      * 0.5.0   2016-06-24 CRAN (R 3.2.5)                   
 git2r        0.15.0  2016-05-11 CRAN (R 3.2.5)                   
 httr         1.1.0   2016-01-28 CRAN (R 3.2.4)                   
 magrittr     1.5     2014-11-22 CRAN (R 3.2.5)                   
 memoise      1.0.0   2016-01-29 CRAN (R 3.2.5)                   
 R6           2.1.2   2016-01-26 CRAN (R 3.2.4)                   
 rappdirs     0.3.1   2016-03-28 CRAN (R 3.2.5)                   
 Rcpp         0.12.4  2016-03-26 CRAN (R 3.2.4)                   
 rpart        4.1-10  2015-06-29 CRAN (R 3.2.4)                   
 rprojroot    1.1     2016-10-29 CRAN (R 3.2.5)                   
 sparklyr   * 0.4.25  2016-11-11 Github (rstudio/sparklyr@e1475e8)
 tibble       1.2     2016-08-26 CRAN (R 3.2.5)                   
 withr        1.0.2   2016-06-20 CRAN (R 3.2.5)                   
 yaml         2.1.13  2014-06-12 CRAN (R 3.2.4)       `

It worked before, so I am not sure what chanced in my setting that it doesn't work now.

Thanks!

**Comment by javierluraschi** [comment]
@ramkrisp Not enough memory errors, you could try something like:

```{r}
config <- spark_config()
config[["sparklyr.shell.conf"]] <- "spark.driver.extraJavaOptions=-XX:MaxHeapSize=512m"
sc <- spark_connect(master = "local")
```

See http://stackoverflow.com/questions/4401396/could-not-reserve-enough-space-for-object-heap

**Comment by ramkrisp** [comment]
Thanks @javierluraschi for your answer, I tried to run the code that you suggested but still getting the same error (even tried 256m as they suggested in the stackoverflow link). This is weird, since I recently extended the memory from 8 to 16, and it worked fine before that. any other suggestions? Thanks!

**Comment by javierluraschi** [comment]
@ramkrisp How about:

```{r}
config <- spark_config()
config[["sparklyr.shell.conf"]] <- "spark.driver.extraJavaOptions=-XX:MaxHeapSize=2g"
sc <- spark_connect(master = "local")
```

Seems like it might be actually trying to allocate a 1GB object while I assumed it was the size of the head that was trying to set.

**Comment by ramkrisp** [comment]
Hi @javierluraschi , still getting the same error (tried also 4g). Could it related for the H2O package? it worked before I installed this package and I used the following code to install the H2O: 
`localH2O = h2o.init(nthreads=-1)
localH2O <- h2o.init(ip = 'localhost', port = 54321, max_mem_size = '4g')`

Could this is what causing the error?

Thanks!

**Comment by javierluraschi** [comment]
@ramkrisp yes; however, it's not a problem with the package but rather, using this package requires more memory to be allocated which is not available in this machine or additional JVM settings need to be specified. How much ram do you have in this machine?

I would also try:

```{r}
config <- spark_config()

# set starting and max memory to allocate for JVM
config[["spark.executor.memory"]] <- "4g"
config[["spark.driver.memory"]] <- "4g"

sc <- spark_connect(master = "local")
```

**Comment by ramkrisp** [comment]
The ram on my machine is 16g, I checked the memory allocation when I tried your last code and there was more then 9g of ram available (yet still having the error).

**Comment by javierluraschi** [comment]
Right, this looks JVM memory related, posts like https://stackoverflow.com/questions/4401396/could-not-reserve-enough-space-for-object-heap might shed some light. Not much to do in `sparklyr` though; however, ping me in gitter if you want a few more ideas to try.
