### ISSUE TITLE
Including grep, mataches, etc in mutate

### ISSUE THREAD

**Issue by ElianoMarques** [rstudio/sparklyr#329]
Guys, as the other thread for udf and dapply keeping going i wonder if we could try to implement some of the reg. expression into sparklyr. 

Ex. df %>% mutate( text1 = ifelse( col1 %like% "$ text $" , 1, 0 )  ) - this works fine but if the reg expression has multiple attributes and multiple options the like ifelse becomes nasty. 

Ex: df %>% mutate( text1 = ifelse( col1 %like% c("$ text $","$ text2 $")  , 1, 0 )  )  - doesnt work. also is case sensitive. also way less powerful than grep. 

I can create a function that parse the sql element and takes care of all of this but it won't be aligned with grep and or other dplyr syntax. So before i do that, can you let me know if this is something you can easily integrate?

**Comment by kevinushey** [comment]
What regular expression forms are accepted by Spark SQL? Note that `x %like% y` is literally translated to SQL as `x LIKE y`, so whatever we want to implement here (right now) needs to fit into Spark SQL.

It looks like (from the documentation at https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF) that the following things are supported:

- A [NOT] LIKE B
- A RLIKE B
- A REGEXP B
- regexp_extract(subject, pattern, index)
- regexp_replace(subject, pattern, replace)

I'm also not sure what you expect from

    col1 %like% c("$ text $","$ text2 $")

Could you just write `$ text $|$ text2 $`?

**Comment by kevinushey** [comment]
It's also possible that `sparklyr` could introduce its own set of UDFs as part of the jars it distributes.

**Comment by ElianoMarques** [comment]
So lets say we want to create a new flag variable that is product A or product B from a column that contains text. 

```
df_products = tbl(sc, "products") 
#products have a column with a name product_description
df_products = df_products %>% mutate( product_flag = ifelse( product_description %in% c("fruit1","fruit2","fruit3"), "productA", "productB") 

#the challenge is: product description is something like this
#  type of fruit1 
# linked to type fruit2
# Fruit3
# many different variations of the above can exist in the data, fruit with Fruit, FRUIT and etc 
```
Yes we can write multiple like types but something where we can pass multiple patterns to match a particular product (assuming the example above) would be more useful.  grep assumes text|text2 for example. I've tried $ text $|$ text2 $ but the output was not as expected. the only result that gave the correct output was multiple likes. 

I think this is something that would benefit many others too but definitely something that a udf creator option would help.

**Comment by randomgambit** [comment]
@kevinushey 

> It's also possible that sparklyr could introduce its own set of UDFs as part of the jars it distributes.

I think that would be an amazing idea. I am coming from Pig, and Pig having its own set of UDFs was very useful (via piggybank). I think its a must have for sparklyr. The Hive UDFs are OK, but very crude and basic.
