### ISSUE TITLE
restore version and appname checks for idempontent connections

### ISSUE THREAD

**Issue by jjallaire** [rstudio/sparklyr#33]
See: https://github.com/rstudio/sparklyr/commit/ca8312084bade9c26b5951e66462f6394bfa4cb7

We need to update the connection viewer protocol to have an opaque id in addition to a host.

**Comment by javierluraschi** [comment]
Fixed with a check to `app_name` and `master`. Users can specify a different `app_name` to enable more than one connection to the same cluster.

**Comment by jjallaire** [comment]
Needs work in the IDE to implement the same check before merging.

**Comment by javierluraschi** [comment]
Fixed with @30cd44ef2f85a8d438527e9e55370165d505f790
