### ISSUE TITLE
spark_connect throws "Failed to create Hive context, falling back to SQL."

### ISSUE THREAD

**Issue by d8aninja** [rstudio/sparklyr#330]
following along with the rstudio blog walkthrough, got the error where it asked me to get winutils.exe from Loughran's repo.  Did that reran, 

`sc <- spark_connect(master = ''local'')
`
and get
`Warning message:
In create_hive_context_v1(sc) :
  Failed to create Hive context, falling back to SQL. Some operations, like window-functions, will not work
`

Here are my system and package specs:
`>packageVersion('sparklyr')
[1] ‘0.4’
`
`> Sys.getenv()
ALLUSERSPROFILE              C:\ProgramData
APPDATA                      C:\Users\jvangeete\AppData\Roaming
CommonProgramFiles           C:\Program Files\Common Files
CommonProgramFiles(x86)      C:\Program Files (x86)\Common Files
CommonProgramW6432           C:\Program Files\Common Files
COMPUTERNAME                 LAT-JVANGEETE
ComSpec                      C:\windows\system32\cmd.exe
DISPLAY                      :0
FP_NO_HOST_CHECK             NO
GFORTRAN_STDERR_UNIT         -1
GFORTRAN_STDOUT_UNIT         -1
HOME                         C:/Users/jvangeete/Documents
HOMEDRIVE                    C:
HOMEPATH                     \Users\jvangeete
LOCALAPPDATA                 C:\Users\jvangeete\AppData\Local
LOGONSERVER                  \\RUSTY
NUMBER_OF_PROCESSORS         4
OS                           Windows_NT
PATH                         C:\Program
                             Files\R\R-3.2.2\bin\x64;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program
                             Files\Intel\WiFi\bin\;C:\Program Files\Common
                             Files\Intel\WirelessCommon\;C:\Program
                             Files\TortoiseSVN\bin;C:\Program Files
                             (x86)\Skype\Phone\;C:\Program
                             Files\Git\cmd;C:\Users\jvangeete\AppData\Local\Continuum\Anaconda2;C:\Users\jvangeete\AppData\Local\Continuum\Anaconda2\Scripts;C:\Users\jvangeete\AppData\Local\Continuum\Anaconda2\Library\bin
PATHEXT                      .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE       AMD64
PROCESSOR_IDENTIFIER         Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
PROCESSOR_LEVEL              6
PROCESSOR_REVISION           3a09
ProgramData                  C:\ProgramData
ProgramFiles                 C:\Program Files
ProgramFiles(x86)            C:\Program Files (x86)
ProgramW6432                 C:\Program Files
PSModulePath                 C:\windows\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC                       C:\Users\Public
R_ARCH                       /x64
R_DOC_DIR                    C:/PROGRA~1/R/R-32~1.2/doc
R_HOME                       C:/PROGRA~1/R/R-32~1.2
R_LIBS_USER                  C:/Users/jvangeete/Documents/R/win-library/3.2
R_USER                       C:/Users/jvangeete/Documents
RMARKDOWN_MATHJAX_PATH       C:/Program Files/RStudio/resources/mathjax-23
RS_LOCAL_PEER                \\.\pipe\46121-rsession
RS_RPOSTBACK_PATH            C:/Program Files/RStudio/bin/rpostback
RS_SHARED_SECRET             63341846741
RSTUDIO                      1
RSTUDIO_MSYS_SSH             C:/Program Files/RStudio/bin/msys-ssh-1000-18
RSTUDIO_PANDOC               C:/Program Files/RStudio/bin/pandoc
RSTUDIO_SESSION_PORT         46121
RSTUDIO_USER_IDENTITY        jvangeete
SESSIONNAME                  Console
SystemDrive                  C:
SystemRoot                   C:\windows
TEMP                         C:\Users\JVANGE~1\AppData\Local\Temp
TMP                          C:\Users\JVANGE~1\AppData\Local\Temp
USERDNSDOMAIN                IMM.CORP
USERDOMAIN                   IMM
USERNAME                     jvangeete
USERPROFILE                  C:\Users\jvangeete
windir                       C:\windows
windows_tracing_flags        3
windows_tracing_logfile      C:\BVTBin\Tests\installpackage\csilogfile.log
`

**Comment by d8amonk** [comment]
Worth noting that I alread tried to set `config = list()` inside the call to `spark_connect()` as well as the `options("sparkapi.ports.file" = "ports.out")` suggestion...

**Comment by d8amonk** [comment]
Also worth noting that I (literally by chance) came across a RAM upgrade from my IT department (from 8 to 16) and the `spark_connect()` call worked

**Comment by ecocarlisle** [comment]
Failed to create Hive context, falling back to SQL. Some operations, like window-functions, will not work

I'm getting the same error after upgrading to the newest version of RStudio Server.  No problems on RStudio desktop.

**Comment by javierluraschi** [comment]
We need a bit more info to troubleshoot these ones, usually, requires 5-10 messages to pinpoint the problem. That said, we've made improvements to prevent a common `Instance0` error in the logs that prevents us from creating the Hive context, I'm closing hoping that this issue is no longer present in your environments with the latest version of `sparklyr`; however, if someone is still having issues, please reopen a new issue to assist.
