### ISSUE TITLE
Investigate Livy configuration while using `copy_to` with large files

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#333]
So far, using `copy_to(sc, flights)` with livy requires the following configuration options; however, there are additional settings that need to be tuned to get this working:

```
flights <- nycflights13::flights

config <- spark_config()
config[["livy.rsc.rpc.max.size"]] <- 104857600
config[["spark.driver.memory"]] <- "4G"
config[["spark.executor.memory"]] <- "4G"

sc <- spark_connect(master = "local", method = "livy")
copy_to(sc, flights)
```

Latest exception:

```
  Failed to execute Livy statement with error: java.lang.ClassFormatError: Unknown constant tag 77 in class file $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at scala.tools.nsc.interpreter.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:85)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

**Comment by hansharhoff** [comment]
I can confirm the inability to use copy_to with the documentation examples.

```
library(sparklyr)
library(dplyr)
sessionInfo()
config <- spark_config()
config[["livy.rsc.rpc.max.size"]] <- 1048576000 # 100 MB
config[["spark.driver.memory"]] <- "4G"
config[["spark.executor.memory"]] <- "4G"

liv_conf <- livy_config(config = config, username = 'hahad')

sc <- sparklyr::spark_connect(master = "http://mylivyserver:8998", method = "livy", config = liv_conf)
# spark.master is yarn-client

# Fails 
flights_tbl <- dplyr::copy_to(sc, nycflights13::flights, "flights")
```
Outputs:

> Error in force(code) : 
  Failed to execute Livy statement with error: java.lang.ClassFormatError: Unknown constant tag 102 in class file $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC

The batting example also fails:

>batting_tbl <- dplyr::copy_to(sc, Lahman::Batting, "batting")
 Error in force(code) : 
  Failed to execute Livy statement with error: java.lang.ClassFormatError: Unknown constant tag 102 in class file $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC

**Comment by javierluraschi** [comment]
Enabled upload of large files through `copy_to` tracked now by https://github.com/rstudio/sparklyr/issues/949.
