### ISSUE TITLE
sparklyr complains about "same name columns" in join with dplyr and Spark 1.6.2

### ISSUE THREAD

**Issue by JohnMount** [rstudio/sparklyr#338]
sparklyr complains about "same name columns" in join with dplyr and Spark 1.6.2, this is even with columns that are the join condition.  Example with outcome in [link](https://github.com/WinVector/replyr/blob/master/issues/copyissue162.md).

The issue is illustrated below.  Using the current CRAN versions of dplyr and sparklyr (as of 2017-03-30') we get an error message "Use Spark2" when there are any duplicate column names: even in the "by" columns (which are often deliberately the same).  The problem is in real production systems you can choose your version of dplyr and sparklyr, but you often can not choose your version of Spark as it is part of a possibly shared cluster.

``` r
library("dplyr")
```

``` r
packageVersion("dplyr")
```

    ## [1] '0.5.0'

``` r
library("sparklyr")
packageVersion("sparklyr")
```

    ## [1] '0.5.4'

``` r
sc <- spark_connect(master = "local", 
                    version = "1.6.2")

d1 <- copy_to(sc, 
              data.frame(x=c('a','b'), y=c(1,2)),
              name= 'd1',
              overwrite = TRUE)
d2 <- copy_to(sc, 
              data.frame(x=c('b'), z=c(3)),
              name= 'd2',
              overwrite = TRUE)
```

``` r
left_join(d1, d2, by='x')
```

    ## Error in sql_join.spark_connection(con, from_x, from_y, type = query$type, : This dplyr operation requires a feature not supported in Spark 1.6.2 . Try Spark 2.0.0 instead or avoid using same-column names in joins.

``` r
left_join(d1, rename(d2, xb = x), by= c('x'='xb'))
```

    ## Source:   query [2 x 4]
    ## Database: spark connection master=local[4] app=sparklyr local=TRUE
    ## 
    ##       x     y    xb     z
    ##   <chr> <dbl> <chr> <dbl>
    ## 1     a     1  <NA>   NaN
    ## 2     b     2     b     3

**Comment by duttashi** [comment]
@JohnMount, try upgrading the `dplyr` and `sparklyr` versions. 
I tried reproducing the aforementioned error, but could not. The following code works for me
```
> library(dplyr)
> packageVersion("dplyr")
[1] ‘0.7.0’
> library(sparklyr)
> packageVersion("sparklyr")
[1] ‘0.5.6’
> spark_version(sc)
[1] ‘1.6.2’
# connecting to spark local cluster
sc <- spark_connect(master = "local", version = "1.6.2")
> d1 <- copy_to(sc, 
+               data.frame(x=c('a','b'), y=c(1,2)),
+               name= 'd1',
+               overwrite = TRUE)
> d2 <- copy_to(sc, 
+               data.frame(x=c('b'), z=c(3)),
+               name= 'd2',
+               overwrite = TRUE)
> src_tbls(sc)
[1] "d1" "d2"
> d1
# Source:   table<d1> [?? x 2]
# Database: spark_connection
      x     y
  <chr> <dbl>
1     a     1
2     b     2
> d2
# Source:   table<d2> [?? x 2]
# Database: spark_connection
      x     z
  <chr> <dbl>
1     b     3
> left_join(d1, d2, by='x')
# Source:   lazy query [?? x 3]
# Database: spark_connection
      x     y     z
  <chr> <dbl> <dbl>
1     a     1   NaN
2     b     2     3
```
@javierluraschi I think this issue can be closed. As you can see above, it works with the latest `dplyr` and `sparklyr` versions.

**Comment by JohnMount** [comment]
Looks good for me also.  Thank you very much.

``` r
library("dplyr")
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
packageVersion("dplyr")
#> [1] '0.7.1.9000'
library("sparklyr")
#> 
#> Attaching package: 'sparklyr'
#> The following object is masked from 'package:dplyr':
#> 
#>     top_n
packageVersion("sparklyr")
#> [1] '0.5.6.9010'
packageVersion("dbplyr")
#> [1] '1.1.0.9000'

sc <- spark_connect(master = "local", 
                    version = "1.6.2")

d1 <- copy_to(sc, 
              data.frame(x=c('a','b'), y=c(1,2)),
              name= 'd1',
              overwrite = TRUE)
d2 <- copy_to(sc, 
              data.frame(x=c('b'), z=c(3)),
              name= 'd2',
              overwrite = TRUE)
left_join(d1, d2, by='x')
#> # Source:   lazy query [?? x 3]
#> # Database: spark_connection
#>       x     y     z
#>   <chr> <dbl> <dbl>
#> 1     a     1   NaN
#> 2     b     2     3
```
