### ISSUE TITLE
sparklyr fails to create temp table in _join(copy=TRUE) with dplyr and Spark 2.0.0

### ISSUE THREAD

**Issue by JohnMount** [rstudio/sparklyr#339]
sparklyr fails to create temp table in _join(copy=TRUE) with dplyr and Spark 2.0.0.  Example with outcome in [link](https://github.com/WinVector/replyr/blob/master/issues/copyissue200.md).

**Comment by javierluraschi** [comment]
Thank you, working as expected now, using latest `saprklyr`/`dplyr` and Spark 2.2:

```
> d1 <- copy_to(sc,data.frame(x=c(1,2),y=c('a','b')),'d1')
> d2 <- data.frame(y=c('a','b'),z=c(3,4))
> d1 %>% dplyr::inner_join(d2,by='y',copy=TRUE)
# Source:   lazy query [?? x 3]
# Database: spark_connection
      x     y     z
  <dbl> <chr> <dbl>
1     1     a     3
2     2     b     4
```

However, this is most likely fixed in `sparklyr`/`dplyr` and unrelated to Spark version.
