### ISSUE TITLE
Would be more faithful to data if sparklyr represented NA as Spark lit(null:*) instead of blank and NaN.

### ISSUE THREAD

**Issue by JohnMount** [rstudio/sparklyr#340]
For Spark 2.0.0 spark-2.0.0-bin-hadoop2.7, sparklyr 0.4.26, dplyr 0.5.0, R 3.3.2, on OSX 10.11.6 I am seeing `NA` converted to blank (for strings/factors) and `NaN` for numeric when moving data from a local `data.frame` to `Spark`.  This seems needlessly unfaithful, as I think `Spark` has a NULL representation (please see [here](http://stackoverflow.com/questions/32067467/create-new-dataframe-with-empty-null-field-values) for some notes).  A complete example of the issue can be found [here](https://github.com/WinVector/replyr/blob/master/issues/NAvalues.md), and I am pasting the example below.

```
library('sparklyr')
packageVersion('sparklyr')
s200 <- my_db <- sparklyr::spark_connect(version='2.0.0', 
   master = "local")

d2 <- data.frame(x=factor(c('z1',NA,'z3')),y=c(3,5,NA),z=c(NA,'a','z'),
                 stringsAsFactors = FALSE)
print(d2)

d2r <- copy_to(s200,d2,'d2',
               temporary = FALSE,overwrite = TRUE)
print(d2r)
d2x <- as.data.frame(d2r)
print(d2x)
summary(d2x)
str(d2x)

    ## 'data.frame':    3 obs. of  3 variables:
    ##  $ x: chr  "z1" "" "z3"
    ##  $ y: num  3 5 NaN
    ##  $ z: chr  "" "a" "z"
```

**Comment by kevinushey** [comment]
I believe this is a duplicate of https://github.com/rstudio/sparklyr/issues/151.

I think using `NaN` is the right thing to do for numeric types, but for characters + factors we definitely need to get to the bottom of the empty string vs. NA value issue!

**Comment by JohnMount** [comment]
Thanks (and sorry about the dup).  I agree the library should be as faithful as practical, but most databases allow NULL in numeric columns.  So I think NULL~NA and NaN~NaN is possible.

**Comment by JohnMount** [comment]
Does look like a dup of https://github.com/rstudio/sparklyr/issues/151 , I'll close this one.
