### ISSUE TITLE
cran examples strategy

### ISSUE THREAD

**Issue by jwijffels** [rstudio/sparklyr#342]
As CRAN does not allow long running calculations in examples of packages.
May I ask, what is your current/future strategy regarding documentation of examples of this package?
I'm interested especially in order to identify broken dependencies of packages which import sparklyr.

**Comment by javierluraschi** [comment]
@jwijffels we have different levels of automated tests: travis runs a medium suite of tests, locally we run some longer ones. In distributed systems, some issues will only be identified at scale, which we currently don't automate. Instead, we have a lockdown period before release to CRAN where we don't fix bugs, focus on testing at scale and ask the community to upgrade to this pre-CRAN build to identify potential regressions.

That said, it would be great to have automated testing that runs at scale by: provisioning a cluster, running the tests, reporting results with performance benchmarks and shuts down. This is not on our radar on the short term, but definitely something we would like to see at some point.

**Comment by jwijffels** [comment]
That's clear. Many thanks for the feedback!
