### ISSUE TITLE
ml_tree_feature_importance

### ISSUE THREAD

**Issue by jwijffels** [rstudio/sparklyr#343]
It looks to me that the following code in ml_tree_feature_importance
`if (class(model)[1] != "ml_model_decision_tree") spark_require_version(sc, "2.0.0")`
should be replaced with
`if (class(model)[1] %in% c("ml_model_decision_tree", "ml_model_gradient_boosted_trees")) spark_require_version(sc, "2.0.0")`

As it is only org.apache.spark.ml.regression.DecisionTreeRegressor and org.apache.spark.ml.regression.GBTRegressionModel which do not have a featureImportances method in Spark 1.6, while org.apache.spark.ml.regression.RandomForestRegressionModel already has this in Spark 1.6

The following gives errors for that reason.

```
library(PASWR)
library(sparklyr)
sc <- spark_connect(master = "local", version = "1.6.2", hadoop_version = "2.6")

data(titanic3, package = "PASWR")
x <- titanic3[, c("name", "pclass", "survived", "fare", "age", "sex")]
x <- na.exclude(x)
x <- copy_to(dest = sc, df = x, 
             name = "titanic3", overwrite = TRUE)

## Fit regression tree
m <- ml_decision_tree(x, response = fare ~ survived + age + sex, 
                      max.bins = 32, max.depth = 5,
                      type = "regression")
ml_tree_feature_importance(sc, m)
Error: failed to invoke spark command (unknown reason)
```

**Comment by kevinushey** [comment]
Thanks for reporting! This should be fixed up now.
