### ISSUE TITLE
unable to count number of rows

### ISSUE THREAD

**Issue by dsblr** [rstudio/sparklyr#346]
I am trying to get the number of rows and number of columns after reading the file from csv. But I am unable to get the number of rows. Please suggest some solution.
 test_data <- spark_read_csv(sc = sc, name = "test1",path ="C:/Users/user1/data/bk_test1.csv")

dim(test_data)
 [1] NA 15
 ncol(test_data)
 [1] 15
 nrow(test_data)
 [1] NA

**Comment by kevinushey** [comment]
This is fixed in the development version of `sparklyr` and will be going to CRAN soon. Install it with:

```R
if (!require("devtools")) install.packages("devtools")
devtools::install_github("rstudio/sparklyr")
```

**Comment by dsblr** [comment]
Thanks @kevinushey

**Comment by solunsteve** [comment]
Still doesn't work...

**Comment by benmwhite** [comment]
@solunsteve `sdf_nrow()`

**Comment by BKDaugherty** [comment]
@kevinushey - tagging you because you closed this. Did this ever go to CRAN?

I can definitely use `sdf_nrow()` here, but it feels like `nrow `/ `ncol` should be able to give me the answer, and inline with the rest of the `sparklyr` philosophy.

**Comment by kevinushey** [comment]
It looks like the answer here is no:

```
> sparklyr:::dim.tbl_spark
function (x) 
{
    c(NA_real_, sdf_ncol(x))
}
```

I'm not involved with `sparklyr` development anymore so I can't say whether we could use `sdf_nrow(x)` instead of `NA_real_` here, though -- it's possible that invoking `count` here could force table materialization and hence be slow in some contexts?

**Comment by kevinushey** [comment]
For posterity, I'd recommend opening an new issue to discuss whether this could be changed.
