### ISSUE TITLE
fromJSON/sparklyr

### ISSUE THREAD

**Issue by TarasDerevianko** [rstudio/sparklyr#347]
Hi!
I need transform tbl_spark with json column to normal spark_dataframe object. For example in R i can do this transformation in following way
`l = data.frame(stringsAsFactors = F,
               ID = 1:2,
               a =c('[{"hash":"dfgh","id":"51245145","partner":149548,"weight":1552637,"class":["mrsadcr"]}]',
                   '[{"hash":"cKpALIKG","id":"51245146","partner":149548,"weight":1858015,"class":["mrsadcr"]}]'),
               b = sample(letters, 2))

l = l %>% 
  group_by(ID) %>%
  do(cbind(data.frame(stringsAsFactors = F,
                      b = .$b[1]),
           fromJSON(.$a[1], flatten = T)))
print(l)
`

`> print(l)
Source: local data frame [2 x 7]
Groups: ID [2]

     ID     b     hash       id partner  weight     class
  <int> <chr>    <chr>    <chr>   <int>   <int>    <list>
1     1     q     dfgh 51245145  149548 1552637 <chr [1]>
2     2     y cKpALIKG 51245146  149548 1858015 <chr [1]>`

How it looks in sparklyr?

**Comment by javierluraschi** [comment]
Use `spark_apply()` available in `sparklyr 0.6`, something like:

```
json_columns_tbl %>% spark_apply(function(e) {
  # read JSON from dataframe e
  # return dataframe with splitted columnd
})
```
