### ISSUE TITLE
sc <- spark_connect(master = "local", config = list())

### ISSUE THREAD

**Issue by nLakshmipathi** [rstudio/sparklyr#352]
Error in start_shell(master = master, spark_home = spark_home, spark_version = version,  : 
  Failed to launch Spark shell. Ports file does not exist.
    Path: C:\spark-2.0.2-bin-hadoop2.7\bin\spark-submit.cmd
    Parameters: --class, sparklyr.Backend, "C:\Users\ananthas\Documents\R\win-library\3.3\sparklyr\java\sparklyr-2.0-2.11.jar", C:\Users\ananthas\AppData\Local\Temp\RtmpAx8ghI\file1a5c36d42e82.out
    
The filename, directory name, or volume label syntax is incorrect.

**Comment by javierluraschi** [comment]
@nLakshmipathi We have been improving connection errors to help diagnose issues, could you try connecting with the latest version of `sparklyr` using:

`devtools::install_github("rstudio/sparklyr")` and retry `spark_connect`?

**Comment by nLakshmipathi** [comment]
Thank you javierluraschi for your reply for my query. But again i am getting the same problem.
Could you please let me know the steps to be followed to work with sparklyr.
I'll tell you what i have done:
1) installed Apache spark in mystem
2) scala also installed
3) R installed
4) Rstudio installed
5) set the environment variables properly.
But Spark context is not working.  Could you please provide me the solution for my problem.

**Comment by nLakshmipathi** [comment]
Thank you javierluraschi for your reply for my query. But again i am getting the same problem.
Could you please let me know the steps to be followed to work with sparklyr.
I'll tell you what i have done:

    installed Apache spark in mystem
    scala also installed
    R installed
    Rstudio installed
    set the environment variables properly.
    But Spark context is not working. Could you please provide me the solution for my problem.
