### ISSUE TITLE
Error in ml_multilayer_perceptron_validate_layers

### ISSUE THREAD

**Issue by ecocarlisle** [rstudio/sparklyr#356]
I'm running through the sparklyr example (https://beta.rstudioconnect.com/content/1518/notebook-classification.html) and trying to run the following line of code on the titanic dataset:

...
# Model survival as a function of several predictors
ml_formula <- formula(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked + Family_Sizes)
...
## Neural Network
ml_nn <- ml_multilayer_perceptron(train_tbl, ml_formula, layers = c(7,6,2))

and getting the following error:
Error in ml_multilayer_perceptron_validate_layers(x, response, features,  : 
  the first element of 'layers' should be the same length as the 'features' vector

**Comment by javierluraschi** [comment]
@ecocarlisle Improved the error here with the latest version of `sparklyr` to point out to the correct number of features to use, you will need to change `7` to the total of features as specified in the error, most likely `c(11,6,2)`.

The difference from the formula comes from `sparklyr` auto-creating additional features for the types that require them. For instance `Pclass` is likely being split into 2 features, etc.
