### ISSUE TITLE
consider refactoring 'spark_api' family of functions

### ISSUE THREAD

**Issue by kevinushey** [rstudio/sparklyr#36]
It's often not clear to me what a particular `spark_api_*` function does; in particular, it always takes me a few minutes to figure out what the function accepts, and what the function returns, when I can use it, etc.

The word `api` in this context is not particularly evocative, so I hope we can choose more informative names. For functions that return a (static) `jobj` attached to `sc` or its associated `sconInst`, I think these functions should also (only?) accept the plain `sparklyr_connection` object if possible.

**Comment by javierluraschi** [comment]
Refactoring completed.
