### ISSUE TITLE
sdf_partition fails to resolve automatically renamed columns after join

### ISSUE THREAD

**Issue by samurainate** [rstudio/sparklyr#364]
I am having trouble using sdf_partition on the result of a join when columns in the lhs and rhs had name conflicts and were renamed name.x and name.y respectively.  If I drop or rename all of the .x and .y columns causing problems after the join before calling sdf_partition, it still fails.  If I rename columns with name conflicts before the join, then sdf_partition succeeds.

**Comment by samurainate** [comment]
Stack trace

Error: org.apache.spark.sql.AnalysisException: cannot resolve '`rectype.x`' given input columns: [..., rectype.x, ..., rectype.y, ...]; line 1 pos 0
##  at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
##  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAnalysis.scala:77)
##  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAnalysis.scala:74)
##  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:301)
##  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:301)
##  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:69)
##  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:300)
##  at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionUp$1(QueryPlan.scala:190)
##  at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$2(QueryPlan.scala:200)
##  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$2$1.apply(QueryPlan.scala:204)
##  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
##  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
##  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
##  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
##  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
##  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
##  at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$2(QueryPlan.scala:204)
##  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$5.apply(QueryPlan.scala:209)
##  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:179)
##  at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionsUp(QueryPlan.scala:209)
##  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:74)
##  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:67)
##  at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:126)
##  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.checkAnalysis(CheckAnalysis.scala:67)
##  at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:58)
##  at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:49)
##  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:64)
##  at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$withPlan(Dataset.scala:2589)
##  at org.apache.spark.sql.Dataset.select(Dataset.scala:969)
##  at org.apache.spark.sql.Dataset.selectExpr(Dataset.scala:1004)
##  at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
##  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
##  at java.lang.reflect.Method.invoke(Method.java:497)
##  at sparklyr.Invoke$.invoke(invoke.scala:94)
##  at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
##  at sparklyr.StreamHandler$.read(stream.scala:55)
##  at sparklyr.BackendHandler.channelRead0(handler.scala:49)
##  at sparklyr.BackendHandler.channelRead0(handler.scala:14)
##  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
##  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
##  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
##  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
##  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
##  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
##  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
##  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
##  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
##  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
##  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
##  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
##  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
##  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
##  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
##  at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
##  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
##  at java.lang.Thread.run(Thread.java:745)

**Comment by samurainate** [comment]
This error is specific to Spark 2.  With Spark 1.6.x, sparklyr fails gracefully with a message to use spark 2 or rename conflicting columns before joining.  

Some code to recreate this error:

require(dplyr)
require(sparklyr)
sc <- spark_connect(master="local",version = "2.0.0")
iris1 <- copy_to(sc,iris,name="iris1")
iris2 <- copy_to(sc,iris,name="iris2")
head(iris1)
head(iris2)
xprod_within_species <- iris1 %>% inner_join(iris2, by='Species') 
head(xprod_within_species) # this line throws the error
spark_disconnect(sc)

**Comment by samurainate** [comment]
debug message with sql from dbSendQuery appears valid.  

Narrowed the failure down to the first dbFetch call after dbSendQuery

**Comment by javierluraschi** [comment]
Fixed with latest `dplyr`, `sparklyr` and `Spark 2.2`:

```
> head(xprod_within_species) # this line throws the error
# Source:   lazy query [?? x 9]
# Database: spark_connection
  Sepal_Length.x Sepal_Width.x Petal_Length.x Petal_Width.x Species Sepal_Length.y
           <dbl>         <dbl>          <dbl>         <dbl>   <chr>          <dbl>
1            5.1           3.5            1.4           0.2  setosa            5.0
2            5.1           3.5            1.4           0.2  setosa            5.3
3            5.1           3.5            1.4           0.2  setosa            4.6
4            5.1           3.5            1.4           0.2  setosa            5.1
5            5.1           3.5            1.4           0.2  setosa            4.8
6            5.1           3.5            1.4           0.2  setosa            5.1
# ... with 3 more variables: Sepal_Width.y <dbl>, Petal_Length.y <dbl>, Petal_Width.y <dbl>
```
