### ISSUE TITLE
copy_to(sc, iris) error if spark_connect(master ="spark://abc:7077), but OK if master="local"

### ISSUE THREAD

**Issue by eijoac** [rstudio/sparklyr#366]
spark 2.0.2 cluster (1 master + 2 workers) already running in the stand alone mode.

`sc = spark_connect(master ="spark://abc:7077)` runs OK (can see the app running in Web GUI), but when doing `iris_tbl <- copy_to(sc, iris)`, got the following error,

Error: Unknown TZ UTC
In addition: Warning message:
In OlsonNames() : no Olson database found

If I use `sc = spark_connect(master ="local")`, then `iris_tbl <- copy_to(sc, iris)` is fine.

**Comment by eijoac** [comment]
Solved! The error message, I believe, is coming from the 'readr' package. It appears that on my cluster OlsonNames(), which is in R core and used by 'readr', cannot find the zone.tab file to read time zone info. On a Linux system, the zone.tab file is usually in /usr/share/zoneinfo, but somehow it's not there on nodes of my cluster. Since I am using a university computing environment, I can do nothing in /usr/share/ directory, so I copied the whole zoneinfo directory from somewhere else to my home R directory and set the TZDIR environment variable to the dir in my home. Then, everything worked out. See details about this zone.tab and TZDIR here, http://web.mit.edu/r/current/lib/R/library/base/html/timezones.html.

**Comment by javierluraschi** [comment]
Glad you were able to workaround; however, seems like eaither `sparklyr` or `readr` or `base` might need a fix in`OlsonNames()`; unless your university has a very particular computing environment that somehow removed this file. Closing for now.
