### ISSUE TITLE
Error connecting to livy on EMR cluster with R 3.2.2

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/sparklyr#368]
Connection from `sparklyr` to `livy` on the EMR cluster is failing with this error: (after fixing issues mentioned in #367):

```
Error in value[[3L]](cond) : 
  Failed to initialize livy connection: Failed to load utils.scala: unused argument (perl = TRUE)
```

@javierluraschi thinks it is the version of R (3.2.2) that is causing this. I will upgrade and see what happens, but wanted to track it here if we need to fix something or bump our minimum version.

**Comment by javierluraschi** [comment]
Thanks! Fixed in `0.4.38`
