### ISSUE TITLE
spark_disconnect does not close a Livy connection 

### ISSUE THREAD

**Issue by edgararuiz** [rstudio/sparklyr#372]
After succesfully connecting to Livy and performing some operations, the connection is not closing when passing the spark_disconnect(sc) command.  The Spark application remains open.  Here's my connection string:

```
devtools::install_github("rstudio/sparklyr")

library(sparklyr)

library(dplyr)

sc <- spark_connect(master="http://[ip address]:8998" ,
                method="livy", config=list()) 
```

**Comment by javierluraschi** [comment]
Thanks! Fixed in `0.4.39`
