### ISSUE TITLE
reading csv with escaped quote chars.

### ISSUE THREAD

**Issue by timyates** [rstudio/sparklyr#374]
_"Normally"_ the way of escaping quotes in CSVs is with a second double quote:

```csv
10,"Tim ""Danger"" Yates","oranges",14
```

But sparklyr seems to use `\"`

Is there a way of reading _"normal"_ csvs?

**Comment by javierluraschi** [comment]
@timyates `spark_read_csv` uses https://github.com/databricks/spark-csv, there are a few option you can tweak like the `escape` character, etc. but there is no way to use `""` to escape a quote, instead one needs to use `\"`, to my knowledge.

At some point, we want to provide arbitrary R code execution in `sparklyr` to help cleanup data in this way, in the meantime, you could transform the `""` to `\"` as follows using the `spark-shell` in scala:

```scala
val csvRdd = sc.textFile("iris.csv", 1)
val csvFixedRdd = csvRdd.map(s => s.replaceAll("\"\"", "\\"""))
csvFixedRdd.saveAsTextFile("iris2.csv")
```
