### ISSUE TITLE
How to control Random Forest

### ISSUE THREAD

**Issue by dsblr** [rstudio/sparklyr#377]
Hi Team,
this is not an issue, but this is a query to know basic functionality of **sparklyr ml_random_forest** package.
I would like to know how can I do the following operations ? 
1) to control the number of variable at each split
2) to control the sample size
3) to control the cutoff value

Please help me to do the above parameter tuning.

**Comment by kevinykuo** [comment]
We should expose these arguments/document them so users don't have to pass them through `ml.options`. Will work on this.

**Comment by kevinykuo** [comment]
@dsblr these have been implemented and documented as of https://github.com/rstudio/sparklyr/pull/896. Please give the latest dev version a try and feel free to open another issue if needed.

**Comment by dsblr** [comment]
@kevinykuo Thanks for your support. Is there a way we can find OOB(out of bag error) from trained random forest model as R Random forest model. Please help me on OOB for sparklyr Random Forest.
