### ISSUE TITLE
Failure when JSON fields contain `\n` or `\r` characters

### ISSUE THREAD

**Issue by timyates** [rstudio/sparklyr#378]
Given the following json file:

```
path <- '/tmp/jsonissue.json'
cat('{"name":"Tim", "desc":"Multiline\\nText"}\n{"name":"Yates", "desc":"Single Text"}', file=path)
```

When we attempt to parse this with `sparklyr`:

```
library(sparklyr)
sc <- spark_connect(master = "local", config = spark_config())
stock <- spark_read_json(sc, "stock", path)
head(stock)
spark_disconnect_all()
```

We get the following error:

```
Source:   query [2 x 2]
Database: spark connection master=local[4] app=sparklyr local=TRUE

Error: Variables must be length 1 or 3.
Problem variables: 'name' 
```

Running the same thing in SparkR gives the expected result:

```
library(SparkR)
sc <- sparkR.session(master = 'local')
stock <- read.json(path)
head(stock)
             desc  name
1 Multiline\nText   Tim
2     Single Text Yates
```

The problem is in the way sparklyr is parsing the `\\n` chars in the input json, as can be seen if we just go down to the single record in the json:

```
cat('{"name":"Tim", "desc":"Multiline\\nText"}', file=path)
sc <- spark_connect(master = "local", config = spark_config())
stock <- spark_read_json(sc, "stock", path)
head(stock)
```

Which gives the result:

```
Source:   query [1 x 2]
Database: spark connection master=local[4] app=sparklyr local=TRUE

       desc  name
      <chr> <chr>
1 Multiline   Tim
2      Text   Tim
```

As you can see, the multiline field is applied across multiple records 😿

**Comment by timyates** [comment]
Looks like this may be [a bug in Hive](https://issues.apache.org/jira/browse/HIVE-1898)...  amazed this bug has been around for 5 years.  Wonder if there is an option I need to set somewhere...

**Comment by timyates** [comment]
Tried:

```
  hive.query.result.fileformat: "SequenceFile"
  hive.default.fileformat: 'SequenceFile'
```

in my `config.yml` but with no success..   Hard to say with spark/hive options though as they are documented sparsely, so I may just be typing words that are having no effect...

**Comment by kevinykuo** [comment]
Related: https://github.com/rstudio/sparklyr/issues/411
