### ISSUE TITLE
"Failed to execute Livy statement with state waiting" error happens occasionally

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/sparklyr#383]
Using sparklyr 0.4.41

I have seen this error happening a few times, but not consistently:

```
 fit_sparklyr <- by_cyl %>% do(mod = ml_linear_regression(mpg ~ disp, data = .))
Error in livy_post_statement(sc, statement$code) : 
  Failed to execute Livy statement with state waiting
```

```
sdf_copy_to(sc, iris)
Error in livy_post_statement(sc, statement$code) : 
  Failed to execute Livy statement with state waiting
```

Seems like when the operation takes long we might run into this.

**Comment by ybjoony** [comment]
+1 for this.
Using sparklyr 0.51, this is blocking me from connecting R studio with livy at all as it keeps happening on livyconnection. I can connect to spark from R Studio just fine, and this failed executions start livy sessions normally, but just can't connect it with R Studio.

**Comment by ybjoony** [comment]
created PR for this. [https://github.com/rstudio/sparklyr/pull/421](https://github.com/rstudio/sparklyr/pull/421) any feedback will be appreciated.

**Comment by javierluraschi** [comment]
Thank you @ybjoony
