### ISSUE TITLE
Address breaking change in dplyr to use con_acquire()

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#387]
https://github.com/hadley/dplyr/commit/818c6fd9791a63b83b5b53dad8432d30f3aa54e5

**Comment by kevinushey** [comment]
FWIW I can confirm that this does indeed break `sparklyr` -- the attempt to access `con` in some places now fails, and so calls to `spark_connection()` fails.

I think we only need to adapt in one spot:

```
R/dplyr_spark.R
10:  x$con
```

**Comment by javierluraschi** [comment]
I believe this is fixed, thanks Kevin!
