### ISSUE TITLE
Spark doesn't respect config passed to spark_connect() v2

### ISSUE THREAD

**Issue by yarrick19** [rstudio/sparklyr#389]
@javierluraschi @kevinushey 

I'm currently using Amazon's EMR cluster with sparklyr version `0.4.41` and needed to increase memory configs (code below).  I see the config values set in the "Environment" tab in the Spark UI.

![image](https://cloud.githubusercontent.com/assets/9707200/21282783/f427e81a-c3ad-11e6-8212-2ea65346e3e1.png)

But, the "Executors" tab does not reflect an increase in storage memory.

![image](https://cloud.githubusercontent.com/assets/9707200/21282795/1c67d7e0-c3ae-11e6-8534-5934d85df2df.png)

This looks very similar to  #286 , but this is not a local cluster.

```
Sys.setenv(SPARK_HOME = "/usr/lib/spark")

config <- spark_config()
config$spark.executor.memory <- "10g"
config$spark.driver.memory <- "8g"

sc <- spark_connect(master = "yarn-client", version = '2.0.1', config = config)
```

Any ideas?

**Comment by edgararuiz** [comment]
Hi @yarrick19, it seems that in Yarn Client mode these settings may need to be setup in a different way or using different Spark setting like `spark.yarn.am.memory` (https://spark.apache.org/docs/2.0.1/running-on-yarn.html)

**Comment by yarrick19** [comment]
@edgararuiz  Thanks for the response!  It does look like `spark.yarn.am.memory` should be used in place of `spark.driver.memory` in client mode.  

But it still looks like `spark.executor.memory` should work no matter if its client mode or cluster mode.  And I don't see any alternatives in the documentation.
![image](https://cloud.githubusercontent.com/assets/9707200/21290453/9dac9126-c46f-11e6-962a-c9b135a443c5.png)

Again, the value i set in the `spark_config()` for `spark.executor.memory` shows in the Spark Properties in the Environment tab, but is not reflected in the Executors tab which seems like its not being respected.

**Comment by edgararuiz** [comment]
I wonder a non-Spark setting, like the `yarn.nodemanager.resource.memory-mb`, is constricting the amount of memory allowed to be allocated to your executors

**Comment by yarrick19** [comment]
@edgararuiz 

Based on the AWS node type I'm using, `yarn.nodemanager.resource.memory-mb` should be set to ~ 11g.  

![image](https://cloud.githubusercontent.com/assets/9707200/21291004/07327362-c485-11e6-9030-f1d77e164572.png)

The cluster resource manager seems to reflect these settings.
![image](https://cloud.githubusercontent.com/assets/9707200/21291057/e89a8424-c486-11e6-82cf-a61a55f05869.png)


But the Executors UI for Spark only shows 414.4 MB.

**Comment by edgararuiz** [comment]
Ok, it looks like EMR is actually fixing those values, please see this article: http://docs.aws.amazon.com/ElasticMapReduce/latest/ReleaseGuide/emr-spark-configure.html 

As per the article too, it seems there's a way to overcome that limitation.

Here's the excerpt: 

> Spark Defaults Set By Amazon EMR
> 
> 
> The following defaults are set by Amazon EMR regardless of whether other settings are set to true, such as spark.dynamicAllocation.enabled or maximizeResourceAllocation.
> 
>     spark.executor.memory
> 
>     spark.executor.cores

**Comment by yarrick19** [comment]
@edgararuiz Thanks for the link!  The below configuration seems to successfully set the resources on the YARN cluster in client mode.  Wish there was some more concise documentation - but realize that is difficult with all the different cluster options that are available.  Closing this thread.
```
config <- spark_config()
config$'sparklyr.shell.executor-memory' <- "10g"
config$'sparklyr.shell.driver-memory' <- "10g"
config$spark.yarn.am.memory <- "6g"
```
