### ISSUE TITLE
Unable to install version 0.5 with RStudio 1.0.44

### ISSUE THREAD

**Issue by carlosbkm** [rstudio/sparklyr#390]
Hi,

I just tried to upgrade to version 0.5 of sparklyr but got the following error: 

```
Installing package into ‘/home/cgarciar/R/x86_64-redhat-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/sparklyr_0.5.tar.gz'
Content type 'unknown' length 732895 bytes (715 KB)
==================================================
downloaded 715 KB

* installing *source* package ‘sparklyr’ ...
** package ‘sparklyr’ successfully unpacked and MD5 sums checked
** R
Warning in .file_append_ensuring_LFs(outFile, codeFiles) :
  write error during file append
Error in .install_package_code_files(".", instdir) : 
  unable to write code files
ERROR: unable to collate and parse R files for package ‘sparklyr’
* removing ‘/home/cgarciar/R/x86_64-redhat-linux-gnu-library/3.3/sparklyr’
Warning in install.packages :
  installation of package ‘sparklyr’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmp4s0SGe/downloaded_packages’

```
These are the versions of my environment:
R version 3.3.1 (2016-06-21)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)
Rstudio version: 1.0.44

My workaround was to install 0.4 version again with:
`devtools::install_version("sparklyr", version = "0.4", repos = "http://cran.us.r-project.org")`

And that works perfectly, so I guessed it must be a problem with the new version.

Kind regards.

**Comment by javierluraschi** [comment]
@carlosbkm thanks, yes this is expected since we are in the process of releasing version `0.5.1` to CRAN, version `0.5` was patched due to a failing test. Usually, the CRAN mirrors update within 72 hours, but in practice, this should already be fixed by now.
