### ISSUE TITLE
Consider: Should sdf_collect return a dplyr frame?

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#393]
I believe we want `sdf_collect` to be independent from `dplyr`, in general, all `sdf_` functions probably should. That's the only one I've seen with a dependency so far.

**Comment by kevinushey** [comment]
I think I agree -- users of `dplyr` / `tibble` can explicitly convert as required; we should just return a plain `data.frame` and let the user decide what the most appropriate final representation is.

**Comment by javierluraschi** [comment]
`sdf_collect` already returns `as_data_frame(fixed, stringsAsFactors = FALSE, optional = TRUE)`, closing.
