### ISSUE TITLE
Cannot use first function inside summary

### ISSUE THREAD

**Issue by infocrat** [rstudio/sparklyr#395]
I am trying to use "first" function inside summary:
`
zones %>%
  group_by(Date, Client) %>%
  summarize(Zone = first(Zone))
`
Error: could not find function "first"

**Comment by edgararuiz** [comment]
hi @infocrat, I think this is accomplished with the top_n function, using mtcars it would be something like this: 
mtcars %>%
  group_by(am) %>%
  top_n(1, mpg)
