### ISSUE TITLE
select function demands column name to be in lower case while in fact it is not

### ISSUE THREAD

**Issue by infocrat** [rstudio/sparklyr#396]

**Comment by edgararuiz** [comment]
@infocrat, can you share more details of what you're trying to accomplish?

**Comment by infocrat** [comment]
I have a table in Hive, I am trying to accomplish something like this and :
cr <- myTable %>% filter(CurrentRate>0) %>% select(CurrentRate)
Error in eval(expr, envir, enclos): object 'CurrentRate' not found

While this works fine:
cr <- myTable %>% filter(CurrentRate>0) %>% select(currentrate)

**Comment by javierluraschi** [comment]
Not really...

```
iris %>% select(species)
Error in overscope_eval_next(overscope, expr) : 
  object 'species' not found

> iris %>% filter(Species !=  "") %>% select(species)
Error in overscope_eval_next(overscope, expr) : 
  object 'species' not found
```

We match `dplyr` behavior for `dplyr` functions in `sparklyr.
