### ISSUE TITLE
Error on Connect instruction on new machine

### ISSUE THREAD

**Issue by gbortz27** [rstudio/sparklyr#398]
sc <- spark_connect(master = "local")
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (4008): Gateway in port (8880) did not respond.
    Path: C:\Users\bortz_g\AppData\Local\rstudio\spark\Cache\spark-2.0.2-bin-hadoop2.7\bin\spark-submit2.cmd
    Parameters: --class, sparklyr.Backend, "C:\Users\bortz_g\Documents\R\win-library\3.3\sparklyr\java\sparklyr-2.0-2.11.jar", 8880, 4008

**Comment by gbortz27** [comment]
An output log follows the above.

Question: What java versions do I need and how do I set the Java Home and path ..are these needed? Must they be installed prior to SparklyR.

Log:
---- Output Log ----
java.lang.UnsupportedClassVersionError: org/apache/spark/launcher/Main : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$000(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
Could not find the main class: org.apache.spark.launcher.Main.  Program will exit.
Exception in thread "main" 

---- Error Log ----
In addition: Warning message:
In readLines(output_file) :
  incomplete final line found on 'C:\Users\bortz_g\AppData\Local\Temp\RtmpK2fOBS\fileabc2e4727dd_spark.log'

**Comment by edgararuiz** [comment]
Hi @gbortz27, yes, you'll need to have a version of Java installed in your pc, check under C:/Program Files/Java to see if you may already have 1.8 installed.  

If it's there, or once you download and install it, you can setup the path inside your R Script, this one is the one I use on my Windows pc:

java_path <- normalizePath('C:/Program Files/Java/jre1.8.0_66')
Sys.setenv(JAVA_HOME=java_path)
library(sparklyr)
sc <- spark_connect(master = "local")

**Comment by edgararuiz** [comment]
The Spark directory doesn't look right to me, can you send me the result to these commands please?
spark_home_dir()
spark_installed_versions()

**Comment by gbortz27** [comment]
spark_home_dir()
[1]
"C:\\Users\\grbortz\\AppData\\Local\\rstudio\\spark\\Cache/spark-1.6.2-bin-hadoop2.6"
> spark_installed_versions()
  spark hadoop                       dir
1 1.6.2    2.6 spark-1.6.2-bin-hadoop2.6



Is something getting mixed up?


*I also installed the latest  Sparkly R from github ..I send you the
response to this and the sc connect*

*I saw some people had the problem sorted out when doing this ,
unfortunately not with me !*

devtools::install_github("rstudio/sparklyr")
Downloading GitHub repo rstudio/sparklyr@master
from URL https://api.github.com/repos/rstudio/sparklyr/zipball/master
Installing sparklyr
"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \

"C:/Users/grbortz/AppData/Local/Temp/RtmpSqkfxY/devtools22bc65a57149/rstudio-sparklyr-1a614a2"
 \
  --library="C:/Users/grbortz/Documents/R/win-library/3.2" --install-tests

* installing *source* package 'sparklyr' ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (sparklyr)
Reloading installed sparklyr
> sc <- spark_connect(master = "local")
Error in force(code) :
  Failed while connecting to sparklyr to port (8880) for sessionid (4449):
Gateway in port (8880) did not respond.
    Path:
C:\Users\grbortz\AppData\Local\rstudio\spark\Cache\spark-1.6.2-bin-hadoop2.6\bin\spark-submit2.cmd
    Parameters: --class, sparklyr.Backend, --jars,
"C:/Users/grbortz/Documents/R/win-library/3.2/sparklyr/java/spark-csv_2.11-1.3.0.jar","C:/Users/grbortz/Documents/R/win-library/3.2/sparklyr/java/commons-csv-1.1.jar","C:/Users/grbortz/Documents/R/win-library/3.2/sparklyr/java/univocity-parsers-1.5.1.jar",
"C:\Users\grbortz\Documents\R\win-library\3.2\sparklyr\java\sparklyr-1.6-2.10.jar",
8880, 4449


---- Output Log ----
Warning: Skip remote jar
C:/Users/grbortz/Documents/R/win-library/3.2/sparklyr/java/spark-csv_2.11-1.3.0.jar.
Warning: Skip remote jar
C:/Users/grbortz/Documents/R/win-library/3.2/sparklyr/java/commons-csv-1.1.jar.
Warning: Skip remote jar
C:/Users/grbortz/Documents/R/win-library/3.2/sparklyr/java/univocity-parsers-1.5.1.jar.
17/01/01 23:09:42 INFO sparklyr: Session (4449) starting
17/01/01 23:09:42 INFO sparklyr: Registering session (4449) into gateway
port (8880)
(17/01/01 23:10:03 ERROR sparklyr: Server shutting down: failed with
exception ,java.net.ConnectException: Connection timed out: connect)

---- Error Log ----

**Comment by edgararuiz** [comment]
Ok, can we try this?
```
sc <- spark_connect(master="local", spark_home=spark_home_dir())

**Comment by gbortz27** [comment]
> SAME RESULT.   SEE BELOW

Question:is it ok to have the one forward forward slash in the path  ie
after "Cache" below.?

"C:\\Users\\grbortz\\AppData\\Local\\rstudio\\spark\\Cache/spark-1.6.2-bin-hadoop2.6"

Also do we not have to add the bin directory to the path? ie
.....spark-1.6.2-bin-hadoop2.6\\bin

I used the following command  in the .R file: before running sc
 ".libPaths(c(file.path(Sys.getenv("SPARK_HOME"),"R","lib"),.libPaths()))"
  is this correct

HERE IS THE RESULT OF YOUR SUGGESTION!

 sc <- spark_connect(master="local", spark_home=spark_home_dir())
Error in force(code) :
  Failed while connecting to sparklyr to port (8880) for sessionid (2970):
Gateway in port (8880) did not respond.
    Path:
C:\Users\grbortz\AppData\Local\rstudio\spark\Cache\spark-1.6.2-bin-hadoop2.6\bin\spark-submit2.cmd
    Parameters: --class, sparklyr.Backend, --jars,
"C:/Users/grbortz/Documents/R/win-library/3.2/sparklyr/java/spark-csv_2.11-1.3.0.jar","C:/Users/grbortz/Documents/R/win-library/3.2/sparklyr/java/commons-csv-1.1.jar","C:/Users/grbortz/Documents/R/win-library/3.2/sparklyr/java/univocity-parsers-1.5.1.jar",
"C:\Users\grbortz\Documents\R\win-library\3.2\sparklyr\java\sparklyr-1.6-2.10.jar",
8880, 2970


---- Output Log ----
Warning: Skip remote jar
C:/Users/grbortz/Documents/R/win-library/3.2/sparklyr/java/spark-csv_2.11-1.3.0.jar.
Warning: Skip remote jar
C:/Users/grbortz/Documents/R/win-library/3.2/sparklyr/java/commons-csv-1.1.jar.
Warning: Skip remote jar
C:/Users/grbortz/Documents/R/win-library/3.2/sparklyr/java/univocity-parsers-1.5.1.jar.
17/01/01 23:30:42 INFO sparklyr: Session (2970) starting
17/01/01 23:30:42 INFO sparklyr: Registering session (2970) into gateway
port (8880)
(17/01/01 23:31:03 ERROR sparklyr: Server shutting down: failed with
exception ,java.net.ConnectException: Connection timed out: connect)

---- Error Log ----

**Comment by gbortz27** [comment]
Do you not believe I have a firewall on? How do i switch it off?

Strange that the loading of Sparkly from Github ( asI have done ) fixed the
8880 port problem for other people as noted on the Sparkly R studio site

Graham

**Comment by gbortz27** [comment]
See my environmental variables, attached

I do not have a Spark Home here ..but isnt that what we set in R studio. I
do have a java home though.

But check my Hadoop Home and its pointing to my Spark 2.0.2 install ..Is
this correct??

Graham

**Comment by gbortz27** [comment]
Hi

After correcting the Haddoop home directory I now get the following

sc <- spark_connect(master="local", spark_home=spark_home_dir())
Warning messages:
1: In value[[3L]](cond) :
  java.lang.RuntimeException: java.lang.RuntimeException: The root scratch
dir:
C:/Users/grbortz/AppData/Local/rstudio/spark/Cache/spark-1.6.2-bin-hadoop2.6/tmp/hive
on HDFS should be writable. Current permissions are: rw-rw-rw-
at
org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:522)
at
org.apache.spark.sql.hive.client.ClientWrapper.<init>(ClientWrapper.scala:204)
at
org.apache.spark.sql.hive.client.IsolatedClientLoader.createClient(IsolatedClientLoader.scala:238)
at
org.apache.spark.sql.hive.HiveContext.executionHive$lzycompute(HiveContext.scala:218)
at
org.apache.spark.sql.hive.HiveContext.executionHive(HiveContext.scala:208)
at org.apache.spark.sql.hive.HiveContext.setConf(HiveContext.scala:440)
at org.apache.spark.sql.SQLContext$$anonfun$4.apply(SQLContext.scala:272)
at org.apache.spark.sql.SQLContext$$anonfun$4.apply(SQLContext.scala:271)
at scala.collection.Iterator$class.foreach(Iterator.scala:727)
at scala.collection.AbstractIterator.for [... truncated]
2: In create_hive_context_v1(sc) :
  Failed to create Hive context, falling back to SQL. Some operations, like
window-functions, will not work

-----------------------------------------------------------------

The command

sc

 gives the following

>*sc*
$master
[1] "local[4]"

$method
[1] "shell"

$app_name
[1] "sparklyr"

$config
$config$sparklyr.cores.local
[1] 4

$config$spark.sql.shuffle.partitions.local
[1] 4

$config$spark.env.SPARK_LOCAL_IP.local
[1] "127.0.0.1"

$config$sparklyr.csv.embedded
[1] "^1.*"

$config$`sparklyr.shell.driver-class-path`
[1] ""

attr(,"config")
[1] "default"
attr(,"file")
[1]
"C:\\Users\\grbortz\\Documents\\R\\win-library\\3.2\\sparklyr\\conf\\config-template.yml"

$spark_home
[1]
"C:\\Users\\grbortz\\AppData\\Local\\rstudio\\spark\\Cache\\spark-1.6.2-bin-hadoop2.6"

$backend
        description               class                mode
 text
"->localhost:59938"          "sockconn"                "wb"
 "binary"
             opened            can read           can write
           "opened"               "yes"               "yes"

$monitor
       description              class               mode               text
"->localhost:8880"         "sockconn"               "rb"           "binary"
            opened           can read          can write
          "opened"              "yes"              "yes"

$output_file
[1]
"C:\\Users\\grbortz\\AppData\\Local\\Temp\\RtmpEb40w1\\file119c4d754316_spark.log"

$spark_context
<jobj[5]>
  class org.apache.spark.SparkContext
  org.apache.spark.SparkContext@393ce018

$java_context
<jobj[6]>
  class org.apache.spark.api.java.JavaSparkContext
  org.apache.spark.api.java.JavaSparkContext@73a43424

$hive_context
<jobj[8]>
  class org.apache.spark.sql.SQLContext
  org.apache.spark.sql.SQLContext@75168a30

attr(,"class")
[1] "spark_connection"       "spark_shell_connection" "DBIConnection"

BUT THEN GIVING THE COMMAND

iris_tbl <- copy_to(sc, iris)


RESULTS IN

Error: org.apache.spark.SparkException: Job aborted due to stage failure:
Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in
stage 0.0 (TID 0, localhost): java.io.IOException: No FileSystem for
scheme: C
at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2584)
at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2591)
at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:91)
at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2630)
at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2612)
at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:370)
at org.apache.spark.util.Utils$.getHadoopFileSystem(Utils.scala:1686)
at org.apache.spark.util.Utils$.doFetchFile(Utils.scala:598)
at org.apache.spark.util.Utils$.fetchFile(Utils.scala:395)
at
org.apache.spark.executor.Executor$$anonfun$org$apache$spark$executor$Executor$$updateDependencies$5.apply(Executor.scala:430)
at
org.apache.spark.executor.Executor$$anonfun$org$apache$spark$executor$Executor$$updateDependencies$5.apply(Executor.scala:422)
at
scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
..............


Are we progressing ?

Graham

**Comment by gbortz27** [comment]
Back to this now

sc <- spark_connect(master = "local")
Error in force(code) :
  Failed while connecting to sparklyr to port (8880) for sessionid (6062):
Gateway in port (8880) did not respond.
    Path:
C:\Users\grbortz\AppData\Local\rstudio\spark\Cache\spark-1.6.2-bin-hadoop2.6\bin\spark-submit2.cmd
    Parameters: --class, sparklyr.Backend, --jars,
"C:/Users/grbortz/Documents/R/win-library/3.2/sparklyr/java/spark-csv_2.11-1.3.0.jar","C:/Users/grbortz/Documents/R/win-library/3.2/sparklyr/java/commons-csv-1.1.jar","C:/Users/grbortz/Documents/R/win-library/3.2/sparklyr/java/univocity-parsers-1.5.1.jar",
"C:\Users\grbortz\Documents\R\win-library\3.2\sparklyr\java\sparklyr-1.6-2.10.jar",
8880, 6062

**Comment by edgararuiz** [comment]
Ok, I think I was able to recreate the error.  And solved it once I setup the JAVA_HOME to an existing installation in my laptop .  

Before:

```
Created default hadoop bin directory under: C:\Users\Edgar\AppData\Local\rstudio\spark\Cache\spark-1.6.2-bin-hadoop2.6\tmp\hadoop
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (7382): Sparklyr gateway did not respond while retrieving ports information after 60 seconds
    Path: C:\Users\Edgar\AppData\Local\rstudio\spark\Cache\spark-1.6.2-bin-hadoop2.6\bin\spark-submit2.cmd
    Parameters: --class, sparklyr.Backend, --jars, "C:/Users/Edgar/Documents/R/win-library/3.3/sparklyr/java/spark-csv_2.11-1.3.0.jar","C:/Users/Edgar/Documents/R/win-library/3.3/sparklyr/java/commons-csv-1.1.jar","C:/Users/Edgar/Documents/R/win-library/3.3/sparklyr/java/univocity-parsers-1.5.1.jar", "C:\Users\Edgar\Documents\R\win-library\3.3\sparklyr\java\sparklyr-1.6-2.10.jar", 8880, 7382
```
This is how I set the Java Home...

```
java_path <- normalizePath('C:/Program Files/Java/jre1.8.0_66')
Sys.setenv(JAVA_HOME=java_path)
```
I recall you have a jdk path, maybe trying it with a jre?

From you comment:
```
Sys.getenv('JAVA_HOME') [1] "C:\\Program Files\\Java\\jdk1.8.0_112"
```

**Comment by gbortz27** [comment]
Hi Edgar


Really appreciate you helping me.

I changed it to read from my jre version now
No difference. It should work with jdk though.

Thanks
Graham
On 4 Jan 2017 03:26, "Edgar Ruiz" <notifications@github.com> wrote:
>
> Ok, I think I was able to recreate the error. And solved it once I setup
the JAVA_HOME to an existing installation in my laptop .
>
> Before:
>
> Created default hadoop bin directory under: C:\Users\Edgar\AppData\Local\
rstudio\spark\Cache\spark-1.6.2-bin-hadoop2.6\tmp\hadoop
> Error in force(code) :
>   Failed while connecting to sparklyr to port (8880) for sessionid
(7382): Sparklyr gateway did not respond while retrieving ports information
after 60 seconds
>     Path: C:\Users\Edgar\AppData\Local\rstudio\spark\Cache\spark-1.6.
2-bin-hadoop2.6\bin\spark-submit2.cmd
>     Parameters: --class, sparklyr.Backend, --jars,
"C:/Users/Edgar/Documents/R/win-library/3.3/sparklyr/java/
spark-csv_2.11-1.3.0.jar","C:/Users/Edgar/Documents/R/win-
library/3.3/sparklyr/java/commons-csv-1.1.jar","C:/
Users/Edgar/Documents/R/win-library/3.3/sparklyr/java/univocity-parsers-1.5.1.jar",
"C:\Users\Edgar\Documents\R\win-library\3.3\sparklyr\java\sparklyr-1.6-2.10.jar",
8880, 7382

**Comment by edgararuiz** [comment]
@gbortz27 , can we try installing and connecting to a 2.0.0 version instead of 1.6.2?

**Comment by gbortz27** [comment]
I am on version 2.0.2

**Comment by edgararuiz** [comment]
Oh, you latest comment had this: 

sc <- spark_connect(master = "local")
Error in force(code) :
  Failed while connecting to sparklyr to port (8880) for sessionid (6062):
Gateway in port (8880) did not respond.
    Path:
C:\Users\grbortz\AppData\Local\rstudio\spark\Cache\ **spark-1.6.2-bin-hadoop2.6\bin\spark-submit2.cmd**

**Comment by gbortz27** [comment]
This is what happened now!


> library(sparklyr)
> spark_install(version="2.0.2")
*Spark 2.0.2 for Hadoop 2.7 or later already installed.*
> Sys.getenv('JAVA_HOME')
*[1] "C:\\Program Files\\Java\\jre1.8.0_112"*
> Sys.getenv('SPARK_HOME')
*[1]
"C:\\Users\\grbortz\\AppData\\Local\\rstudio\\spark\\Cache\\spark-2.0.2-bin-hadoop2.7"*
> Sys.getenv("HADOOP_HOME")
*[1]
"C:\\Users\\grbortz\\AppData\\Local\\rstudio\\spark\\Cache\\spark-2.0.2-bin-hadoop2.7\\tmp\\hadoop"*

> sc <- spark_connect(master = "local")
*Error in file(con, "r") : cannot open the connection*
*In addition: Warning message:*
*In file(con, "r") :*
*  cannot open file
'C:\Users\grbortz\AppData\Local\Temp\Rtmp6zaoRi\file214834723dcf_spark.log':
Permission denied*

*I tried it again !!!*

> sc <- spark_connect(master = "local")
*Error in force(code) : *
*  Failed while connecting to sparklyr to port (8880) for sessionid (6885):
Gateway in port (8880) did not respond.*
*    Path:
C:\Users\grbortz\AppData\Local\rstudio\spark\Cache\spark-2.0.2-bin-hadoop2.7\bin\spark-submit2.cmd*
*    Parameters: --class, sparklyr.Backend,
"C:\Users\grbortz\Documents\R\win-library\3.2\sparklyr\java\sparklyr-2.0-2.11.jar",
8880, 6885*

*---- Output Log ----17/01/04 21:13:38 INFO sparklyr: Session (6885)
starting17/01/04 21:13:38 INFO sparklyr: Registering session (6885) into
gateway port (8880)(17/01/04 21:13:59 ERROR sparklyr: Server shutting down:
failed with exception ,java.net.ConnectException: Connection timed out:
connect)*


Ithink there is something major going on here. I tried to run SparkR and it
came back saying the Java Virtual Machine wont run

Thanks
Graham

**Comment by gbortz27** [comment]
my connection is up

but on the dplyr command i get R code execution error block coming up

and then

Error: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at
org.apache.spark.sql.hive.client.IsolatedClientLoader.createClient(IsolatedClientLoader.scala:258)
at
org.apache.spark.sql.hive.HiveUtils$.newClientForMetadata(HiveUtils.scala:359)
at
org.apache.spark.sql.hive.HiveUtils$.newClientForMetadata(HiveUtils.scala:263)
at
org.apache.spark.sql.hive.HiveSharedState.metadataHive$lzycompute(HiveSharedState.scala:39)
at
org.apache.spark.sql.hive.HiveSharedState.metadataHive(HiveSharedState.scala:38)
at org.apache.spark.sql.hive.HiveSharedState.externalCatalog$lzycomp

**Comment by edgararuiz** [comment]
Seeing this and your other issue, I think @kevinushey is right, all is left are security restrictions.

**Comment by gbortz27** [comment]
I have all this done from the start

**Comment by gbortz27** [comment]
Can i use jdk instead of jre..1.8 of course0

**Comment by javierluraschi** [comment]
@gbortz27 this error `No FileSystem for scheme: C` is now fixed with the latest version of `sparklyr`, this was a regression introduced during January that is now resolved. It affected Windows systems and Spark 1.6.

Looks like the comment you provided on `January 1st` got you to the `No FileSystem for scheme` error, if you follow those same steps, this error should not be present anymore.

Feel free to reopen this issue if there is more to investigate, thank you!

**Comment by javierluraschi** [comment]
To upgrade to this fix is enough to:

```
remove.packages("sparklyr")
install.packages("sparklyr")
```
