### ISSUE TITLE
Gateway did not respond

### ISSUE THREAD

**Issue by corneversloot** [rstudio/sparklyr#400]
Hello,

We have setup sparklyr (with RStudioServer) on a MapR Hadoop edge node which works fine. However, running R scripts from the cluster nodes which have the exact same R installation raises the following exception:
```
Error in query_gateway_for_port(gateway, sessionId, config, isStarting) :
  Sparklyr gateway did not respond while retrieving ports information after 1 seconds
Calls: spark_connect ... start_shell -> spark_connect_gateway -> query_gateway_for_port
Execution halted
```
The code executed is as follows:
```
library(sparklyr)
sc <- spark_connect(master = 'yarn', spark_home = '/opt/mapr/spark/spark-2.0.0-bin-2.2.0')
```
I am not quite sure which sparklyr version we use since we pulled it from this git repo around 6 weeks ago. 

Executing a spark-shell on yarn from these nodes works fine so it does not seem to be a Spark problem. Any idea how to solve this issue?

EDIT: possibly relevant to mention that these nodes have two network interaces...

**Comment by edgararuiz** [comment]
Hi @corneversloot, can you try 'yarn-client' as the master please?

**Comment by corneversloot** [comment]
Hi @edgararuiz, thanks for your reply. I tried it with yarn-client but the outcome is the same.

**Comment by corneversloot** [comment]
I am trying to debug this issue and my main question is regarding the function of this gateway. What is its purpose (just open a socket?) and what would it mean if the gateway does not get ports information. This seems to be triggerd by
```
length(backendSessionId) == 0 || length(redirectGatewayPort) == 0 || length(backendPort) == 0
```
Which leads to the question what would cause any of these to be 0?

**Comment by corneversloot** [comment]
I figured it out, so for others comming across this error. It turned out to result from the fact that the default port 8880 sparklyr wants to use is already taken.

Solutions:
from code:
```
config <- spark_config()
config$sparklyr.gateway.port = <a free port>
```
Or using config.yml:
```
default:
 sparklyr.gateway.port: <a free port>
```

**Comment by abdkumar** [comment]
> I figured it out, so for others comming across this error. It turned out to result from the fact that the default port 8880 sparklyr wants to use is already taken.
> 
> Solutions:
> from code:
> 
> ```
> config <- spark_config()
> config$sparklyr.gateway.port = <a free port>
> ```
> 
> Or using config.yml:
> 
> ```
> default:
>  sparklyr.gateway.port: <a free port>
> ```
```
conf[["sparklyr.gateway.port"]] = xxxx
conf[["sparklyr.gateway.start.timeout"]] = 120
```
setting geteway.start.timeout solves the issue
