### ISSUE TITLE
Add download information for Spark 2.1.0

### ISSUE THREAD

**Issue by kevinushey** [rstudio/sparklyr#407]

**Comment by ricardo-bion** [comment]
hey @kevinushey, ETA for sparklyr to support Spark 2.1?

**Comment by kevinushey** [comment]
I just added download links for Spark 2.1.0, so we should be good to go.

**Comment by kevinushey** [comment]
Hrm, it looks like something is going wrong here:

```
> sparklyr::spark_connect(master = "local", version = "2.1.0")
Error in start_shell(master = master, spark_home = spark_home, spark_version = version,  :
  sparklyr does not currently support Spark version: 2.1.0
```

@javierluraschi, can you take a look when you have time?

**Comment by erikriverson** [comment]
https://github.com/rstudio/sparklyr/blob/master/R/spark_extensions.R#L99 is looking for `sparklyr/java/sparklyr-2.1-2.11.jar` , but it is not present.

**Comment by kevinushey** [comment]
Thanks for digging in @erikriverson -- you're exactly right; we needed to rebuild the sparklyr jars against Spark 2.1.0. I've done that now and pushed to master so sparklyr + Spark 2.1.0 should be good to go!

**Comment by ricardo-bion** [comment]
awesome!! when is the next CRAN submission?

**Comment by kevinushey** [comment]
The next submission will probably come in the next ~1-2 months.

**Comment by zhiboz** [comment]
a workaround would be upgrade to the latest version of `sparklyr`

`devtools::install_github("rstudio/sparklyr")`

tested with `RStudio 1.0`, `R 3.3.1`, `Spark 2.1.0`

**Comment by monicarodguev** [comment]
Hello!

@kevinushey is Spark 2.1.0 available in `Sparklyr`? I tried to downloaded and it failed:

```r
> spark_install(version = "2.1.0")
Installing Spark 2.1.0 for Hadoop 2.7 or later.
Downloading from:
- 'https://d3kbcqa49mib13.cloudfront.net/spark-2.1.0-bin-hadoop2.7.tgz'
Installing to:
- 'C:\Users\c12751a\AppData\Local\rstudio\spark\Cache/spark-2.1.0-bin-hadoop2.7'
trying URL 'https://d3kbcqa49mib13.cloudfront.net/spark-2.1.0-bin-hadoop2.7.tgz'
Content type 'application/x-tar' length 195636829 bytes (186.6 MB)
downloaded 188 KB

Error in untar2(tarfile, files, list, exdir, restore_times) : 
  incomplete block on file
```

**Comment by kevinushey** [comment]
Hi @monicarodguev,

Based on the output, it looks like your download was cut off prematurely:

```
- 'C:\Users\c12751a\AppData\Local\rstudio\spark\Cache/spark-2.1.0-bin-hadoop2.7'
trying URL 'https://d3kbcqa49mib13.cloudfront.net/spark-2.1.0-bin-hadoop2.7.tgz'
Content type 'application/x-tar' length 195636829 bytes (186.6 MB)
downloaded 188 KB
```

Note that the archive is 186.6MB in size, but for some reason only 188KB was downloaded.

**Comment by slavakx** [comment]
got the following error during installation from devtools::install_github("rstudio/sparklyr")

Error : object 'db_data_type' not found whilst loading namespace 'sparklyr'

Environment: RStudio Server Version 1.0.136, R: 3.3.2, Spark 2.1.0

**Comment by GriffinRidgeback** [comment]
I just got the same error; relatively same configuration as @slavakx.  One post said that tibble was the problem but there was a fix which included tibble. I did it manually, deleted my dplyr installation, re-ran the devtools command, still no luck!!!

**Comment by lazariv** [comment]
I've got the same error on the same configuration, except R: 3.2

**Comment by GriffinRidgeback** [comment]
This is NOT fixed!  Tried to install on a new R environment for work I HAVE to do in sparklyr and still got:

Error : object 'db_data_type' not found whilst loading namespace 'sparklyr'

Why is this still not working?  I have a customer who is depending on me being able to transform their code into sparklyr format but I have no environment in which to do this.

Please help!!  What diagnostic information can I provide that will help in this?  Has anyone installed this package successfully?  Under what versions of R and installed packages did it work?

Thanks!!

**Comment by mashaye** [comment]
I have the same problem as above. 
Error : object 'db_data_type' not found whilst loading namespace 'sparklyr'
Error: package or namespace load failed for ‘sparklyr’"

I have spark 2.1; R 3.3.1; rstudio server;

**Comment by GriffinRidgeback** [comment]
Looks like it is fixed now ;->

**Comment by mashaye** [comment]
Yea, it is fixed. Thanks!

**Comment by tristanz** [comment]
I tested both cran and devtools, it looks like this fix isn't published to CRAN yet.  Any chance this can get updated now that 2.1 is widely distributed?

**Comment by javierluraschi** [comment]
`sparklyr 0.5.4` was published to CRAN and contains patch to support Spark 2.1.0.

**Comment by igornoberto** [comment]
Does it have support to spark 2.1.1?
