### ISSUE TITLE
Collecting string columns with new line characters splits into multiple rows

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#411]
Hit an issue where collecting a data frame with data `"this\ntest"` would collect as two rows instead of one. This could also break collection if the rows get out of sync, I believe. See for instance `sdf_deserialize_column` which splits based on `\n`, etc.

**Comment by kevinykuo** [comment]
So I've been playing around with this and couldn't figure this out: if we escape `\n` on the JVM side (via `_.replaceAll("\n", "\\n")` in `collectColumnString` it somehow gets unescaped backed to `n` during deserialization. I.e. `aa\\nbb` in JSON gets collected as `aabb` after `spark_read_json`. Thoughts?

**Comment by kevinushey** [comment]
One thought I had before was whether we could use the ASCII record separator (`\30`) but if I recall correctly this did not play well with `livy` / JSON fields.

**Comment by kevinykuo** [comment]
@javierluraschi I've tried a few ways (mostly escaping/unescaping) to work around this to no avail. I think the issue breaks a lot of use cases and should be looked at soon.

**Comment by kevinushey** [comment]
I can't even copy a `data.frame` containing newlines into Spark, so it seems like there's far more fundamental issues than just what's in sparklyr.

```R
library(sparklyr)
sc <- spark_connect(version = "2.1.0", master = "local")
df <- data.frame(
  x = 1:3,
  y = c("a\nb", "c\nd", "e\nf"),
  stringsAsFactors = FALSE
)
copy_to(sc, df)
```

vomits

```
 Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 1 times, most recent failure: Lost task 0.0 in stage 1.0 (TID 1, localhost, executor driver): java.lang.NumberFormatException: For input string: "b""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:272)
	at scala.collection.immutable.StringOps.toInt(StringOps.scala:29)
	at org.apache.spark.sql.execution.datasources.csv.CSVTypeCast$.castTo(CSVInferSchema.scala:250)
	at org.apache.spark.sql.execution.datasources.csv.CSVRelation$$anonfun$csvParser$3.apply(CSVRelation.scala:125)
	at org.apache.spark.sql.execution.datasources.csv.CSVRelation$$anonfun$csvParser$3.apply(CSVRelation.scala:94)
	at org.apache.spark.sql.execution.datasources.csv.CSVFileFormat$$anonfun$buildReader$1$$anonfun$apply$2.apply(CSVFileFormat.scala:167)
	at org.apache.spark.sql.execution.datasources.csv.CSVFileFormat$$anonfun$buildReader$1$$anonfun$apply$2.apply(CSVFileFormat.scala:166)
...
```

The CSV file looks like this:

```
"x","y"
1,"a
b"
2,"c
d"
3,"e
f"
```

That is, the newlines are in quoted fields, so I assume either we're invoking Spark's CSV serializer wrong, or there is a bug there.

**Comment by kevinushey** [comment]
See also: https://github.com/databricks/spark-csv/issues/10

**Comment by kevinykuo** [comment]
Some recent developments: https://issues.apache.org/jira/browse/SPARK-19610

**Comment by kevinykuo** [comment]
So I guess #378 is a separate issue then? What should we expect here?

```
sc <- spark_connect(version = "2.1.0", master = "local")
df2 <- data.frame(
  x = 1:3,
  y = c("a\\nb", "c\\nd", "e\\nf"),
  stringsAsFactors = FALSE
)
copy_to(sc, df2)
# Source:     table<df2> [?? x 2]
# Database:   spark connection master=local[8] app=sparklyr local=TRUE
# 
# x     y
# <int> <chr>
#   1     1   anb
# 2     2   cnd
# 3     3   enf
```

**Comment by javierluraschi** [comment]
Fixed with referenced PR.
