### ISSUE TITLE
please help me to slove this error

### ISSUE THREAD

**Issue by neerajkr666** [rstudio/sparklyr#412]
> sc <- spark_connect(master = "spark://local:8880",  config = spark_config(), version = "2.0.0")
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (4646): Gateway in port (8880) did not respond.
    Path: C:\home\spark\bin\spark-submit2.cmd
    Parameters: --class, sparklyr.Backend, "C:\Users\bobinks\Documents\R\R-3.3.2\library\sparklyr\java\sparklyr-2.0-2.11.jar", 8880, 4646

---- Output Log ----

---- Error Log ----
In addition: Warning messages:
1: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:\home\spark/bin/spark-submit2.cmd": The system cannot find the path specified
2: running command '"C:\home\spark\bin\spark-submit2.cmd" --class sparklyr.Backend "C:\Users\bobinks\Documents\R\R-3.3.2\library\sparklyr\java\sparklyr-2.0-2.11.jar" 8880 4646' had status 127

**Comment by dsblr** [comment]
@neerajkr666 try the following; it may resolve the issue.
set JAVA_HOME, SPARK_HOME and HADOOP_HOME.
then sc <- spark_connect(master = "local")

**Comment by javierluraschi** [comment]
@neerajkr666 try with the latest version of `sparklyr`, should be much better, you could also validate `C:\home\spark/bin/spark-submit2.cmd` exists.
