### ISSUE TITLE
Failed to find Spark jars directory.

### ISSUE THREAD

**Issue by neerajkr666** [rstudio/sparklyr#413]
sc <- spark_connect(master = "local",  config = spark_config(), version = "2.0.0")
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (1399): Gateway in port (8880) did not respond.
    Path: C:\home\spark\bin\spark-submit2.cmd
    Parameters: --class, sparklyr.Backend, "C:\Users\bobinks\Documents\R\R-3.3.2\library\sparklyr\java\sparklyr-2.0-2.11.jar", 8880, 1399

---- Output Log ----
Failed to find Spark jars directory.
You need to build Spark before running this program.

---- Error Log ----

**Comment by dsblr** [comment]
@neerajkr666 have you installed spark-hadoop distribution ?

**Comment by javierluraschi** [comment]
Please use `spark_install()` or configure Spark properly in Windows.

**Comment by hafez-ahmad** [comment]
same error
