### ISSUE TITLE
Disable hive support

### ISSUE THREAD

**Issue by raphael-psr** [rstudio/sparklyr#415]
Is it possible to disable the hive support in _sparklyr_?

Similar in _sparkR_:
`sparkR.session(master="local[*]", enableHiveSupport=FALSE)`

**Comment by javierluraschi** [comment]
This would make sense for those without Hive enabled. @raphael-psr what is the side effect you are experiencing? I'm asking since `sparklyr` fallsback to no Hive support when it's not available, so in theory, this would work for your use case.

**Comment by elgalu** [comment]
@raphael-psr did you find a way? I'm facing the same issue.

**Comment by kevinykuo** [comment]
The fix for https://github.com/rstudio/sparklyr/issues/1496 should provide a way to do this. Should have a PR within the next day or so.
