### ISSUE TITLE
object '.sparkREnv' not found

### ISSUE THREAD

**Issue by neerajkr666** [rstudio/sparklyr#417]
> cc <- sparkR.init(master = "local", appName = "SparkR", sparkHome = Sys.getenv("SPARK_HOME"))
  Error in exists(".sparkRjsc", envir = .sparkREnv) : 
  object '.sparkREnv' not found

**Comment by kevinushey** [comment]
`sparklyr` and `SparkR` are separate packages: sorry, we do not provide support for `SparkR`. See http://spark.apache.org/community.html.
