### ISSUE TITLE
Disabling Firewall/Mcafee Solves Connection Problem..Almost..Need directory list

### ISSUE THREAD

**Issue by gbortz27** [rstudio/sparklyr#420]
On disabling the firewall/Mcafee Virus **completely** , the program Sparkly R , works without problem!!! But at the enterprise level this is not sustainable. He can only disable the firewall to particular directories..not to the Temp directory as a whole !, only files or subdirectories in the Temp..(company rules )

We tried to disable the firewall to only the following directories
"C:\\Users\\grbortz\\AppData\\Local\\rstudio\\spark\\Cache\\spark-2.0.2-bin-hadoop2.7"
"C:\\Users\\grbortz\\AppData\\Local\\rstudio\\spark\\Cache\\spark-2.0.2-bin-hadoop2.7\\tmp\\hadoop"
'C:\Users\grbortz\AppData\Local\Temp\

The following Errors are occuring now
> sc <- spark_connect(master = "local")
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'C:\Users\grbortz\AppData\Local\Temp\RtmpyQvjkq\file9f06da6313_spark.log': 
Permission denied

On connecting again after the above 

> library(sparklyr)
> library(dplyr)
> sc <- spark_connect(master = "local")
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (5627): Gateway in port (8880) did not respond.
    Path: C:\Users\grbortz\AppData\Local\rstudio\spark\Cache\spark-2.0.2-bin-hadoop2.7\bin\spark-submit2.cmd
    Parameters: --class, sparklyr.Backend, "C:\Users\grbortz\Documents\R\win-library\3.2\sparklyr\java\sparklyr-2.0-2.11.jar", 8880, 5627

Please inform me of the full directory list and files that I need to disable Mcafee antivirus/ Firewall on to get this to work. WE CANNOT DISABLE MCAFEE/FIREWALL OVER THE WHOLE PC...THE COMPANY WONT ALLOW THIS!  It works when we do this ...but its of no use.

Thanks
Graham

**Comment by kevinushey** [comment]
You will need to disable the firewall on all directories constructed within `'C:\Users\grbortz\AppData\Local\Temp\`, if that is not happening already. The R session directory is constructed using a unique directory name within that path, and R + RStudio will need to be able to read and write files in that directory.

**Comment by gbortz27** [comment]
Hi Kevin

He has disabled this ...\Temp directory ( not sustainable ...though) but
even this didnt work.  He states that even if it did work the company would
not allow this as this directory is prone to virus attack. He would
therefore have to Prename the temp sub directories that need to be unlocked
 and the files that spark creates. Are these subdirectories and files  the
same or are they created on each new spark session so they wont be seen by
 Mcafee on startup? Is this not going to be a problem for everybody that is
subject to corporate rules..and normally at enterprise level this would be
the case?  By scaling R using Spark, is it not the intention to use R at
the Enterprise level. Do you not see this as a problem for the deployment
and expansion in the use of Sparkly R?

We also notice that e ports are different each session and the Mcafee
controller has to also free up ports, but if they are dynamic and unique
for each session this is impossible. The first port mentioned 8880 is the
same, but the second is changing for each execution!

The strange thing is that Mcafee Picked up all the directories mentioned
and that these directories are blocked ie the Hadoop / Spark directories
and the Temp directory. However it is still giving a connection problem anf
Mcafee does not pick up the blockage.

We will be getting support from Mcafee to see why the firewall is still
blocking.  The local Mcafee expert asked if perhaps there is an exe file
that should be run by rstudio  when the connection is set up but is being
blocked from execution and where this executble may lie. We only see the
.cmd files.

We know its the Mcafee Firewall as I am told that Mcafee disables the
Window Firewall and uses its own. As soon as we disable it entirely the
code on the Tutorial home page runs perfectly.

This is most unfortunate as it may end my attempt to get to use Sparkly R
:(😞😞

Is the no way Rstudio can produce a workaround. How are other people
,subject to corporate rules (controlled by  a central network adminstrator
, where the user does not have FULL rights , and where Mcafee is used),
coping with this ?

This does not occur with Defender apparently as that still uses the windows
firewall, which can be controlled.

Regards
Thanks
Graham

**Comment by gbortz27** [comment]
In conclusion I must however thank you guys at Rstudio and the community
for all the support given to me over thislast few weeks,. Although I havent
been able to make a  success of this yet, your attempts are still
appreciated, especially Kevin and Edgar.

Regards
Graham

**Comment by kevinushey** [comment]
You can configure the temporary directory that R uses for resources by setting the `TMP` environment variable. The easiest way to do this in an R-specific way is to create a file a file in your home directory called `.Renviron`, and add the lines:

````
TMP = C:\path\to\tmp
```

See e.g. `?tempdir` and `?Startup` for some more information. In general, these deployment issues are the responsibility of the organization attempting to deploy Spark + sparklyr to handle, but we do try to provide as much direction as possible.

@javierluraschi, is it possible to configure the port used for gateway connections? (The port returned by the gateway for connection to the Spark backend)

**Comment by edgararuiz** [comment]
@gbortz27 - I'm sorry, but I can't recall if I already asked you to copy the entire spark-2.0.2-bin-hadoop2.7 folder to your workspace (which you should have full control on).  Then try to connect but setting the spark_home argument to point to that new copy.  

@kevinushey / @javierluraschi  - Is it possible to default the Spark installation to the user's workspace instead of their AppData folder?  I think the restriction is that the anti virus is blocking the winutils.exe file because it's trying to start inside the AppData folder.

**Comment by kevinushey** [comment]
@edgararuiz: I think the installation directory can be configured by setting the `spark.install.dir` R option; e.g.

```
options(spark.install.dir = "C:/path/to/Spark")
```

This would need to be specified in a startup file (e.g. `.Rprofile`) to make sure that new R and RStudio sessions make use of it.

**Comment by gbortz27** [comment]
Hi All

I tried to follow your suggestion by bringing the Spark directory over to
the home directory (which if correct is my Username directory ie
Users\username.... and ten change the environmental variables to point to
the Spark Home and the Hadoop home ( as well as setting and cheacking this
using Sys,getenv() and Sys.setenv() ..and it still gave same error ..in the
error message it is still pointing to the original Spark directory where
Rstudio put Spark....

As far as the Temp directory is concerned ..we tried (although it wouldnt
be permanent ) again by  freeing up  the Temp directory to test the
software and it still came up with the same error messages that it couldnt
access a file or directory.

But we will try Kevins suggestion of reallocating the Temp directory to a
different (say Home directory ) and revert.

Still keen to get an answer on moving the Spark Home out of Apps path...is
there more instructions that I need to give rstudio to force it out.

Maybe Mcaffee will be able to assist ..

I cant remember but does R studio , on install , give the user the chance
to change to directory where spark installs and not accept default.

Many Thanks
Graham

**Comment by gbortz27** [comment]
@edgararuiz <https://github.com/edgararuiz>: I think the installation
directory can be configured by setting the spark.install.dir R option; e.g.

options(spark.install.dir = "C:/path/to/Spark")

This would need to be specified in a startup file (e.g. .Rprofile) to make
sure that new R and RStudio sessions make use of it.


 Where exactly would I put this startup file ..does the file exist and do I
put it in the R studio or R path and exactly where

**Comment by gbortz27** [comment]
Due to Mcafee I need to cahnge the temp directory. It seems taht I have succeeded in forcing R to initiate Spark from a new directory out of Appdata directory path. I think this is correct as the error I get says it invoked Spark.cmdr2 from the new Spark directory. 

I need to change the default temp directory setting for R , I tried your suggestion in the Renviron file and it made no difference ..same error. Can you set the default temp directory for R in the .rprofile file and what is the command. Can I just add it at the bottom of the file.

Will this change the scratchpad for Spark to that directory ie say C:\Users\grbortz\tmp

**Comment by dsblr** [comment]
@gbortz27 
The way I changed the default temp directory for R is to a new location by changing this from Rprofile.site
In the following way you can edit the file Rprofile.site. Location of this file is R_installed_directory/etc 
.First <- function() cat("\n   Welcome to R!\n\n")
setwd("E:/RWORKINGDIR")
Sys.setenv(R_USER = "E:/Users/user1")
Sys.setenv(TMPDIR = "D:/R_packages/Rspark/Temp")
Sys.setenv(TEMP = "D:/R_packages/Rspark/Temp/4")
Sys.setenv(TMP = "D:/R_packages/Rspark/Temp/4")
Sys.setenv(SPARK_HOME = "D:/R_packages/Rspark/spark-2.0.0-bin-hadoop2.6")
.Last <- function()  cat("\n   Goodbye!\n\n")

But unfortunately I still the hive/metastore issue. This is a major issue in windows of sparklyr for spark version > 1.6.2. Till 1.6.2 my sparklyr works fine.
@kevinushey @javierluraschi this is most critical issue.  Please have a look into the same.

**Comment by javierluraschi** [comment]
@gbortz27 sorry for the late reply, the suggestions from dsblr should help here.

@dsblr have you tried with `sparklyr 0.6`? Sems like the `hive/metastore` issue is unrelated to antivirus software, correct? If that's the case, could you open a new issue if you are still experiencing this?

For reference, I ran with the default McAffee trial in Windows 10 under a VM and things worked just fine:

<img width="1029" alt="screen shot 2017-08-24 at 10 23 06 am" src="https://user-images.githubusercontent.com/3478847/29679646-091f8236-88b7-11e7-86fb-b28e88437957.png">

<img width="1029" alt="screen shot 2017-08-24 at 10 25 14 am" src="https://user-images.githubusercontent.com/3478847/29679647-0922914c-88b7-11e7-9754-88ee6391e4a0.png">
