### ISSUE TITLE
Availability of toDebugString when using classification trees -Question

### ISSUE THREAD

**Issue by monicarodguev** [rstudio/sparklyr#424]
Hello everyone, 

Is the function toDebugString() available when using decision trees? If yes, how should be invoked?

Thank you!

Monica

**Comment by kevinushey** [comment]
Questions like these can typically be answered by browsing the [Spark Scala API](https://spark.apache.org/docs/latest/api/scala/#package). See e.g. for decision tree output:

https://spark.apache.org/docs/latest/api/scala/#org.apache.spark.ml.classification.DecisionTreeClassificationModel

Indeed, it seems to be available in the latest version of Spark.

https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.ml.classification.DecisionTreeClassificationModel@toDebugString:String

**Comment by monicarodguev** [comment]
You're right. My question is not clear. What I meant to ask is how that method can be invoked using sparlyr.

**Comment by kevinushey** [comment]
Gotcha, sorry about that -- something like the following should work:

```
fit <- ml_decision_tree(...)
invoke(fit$.model, "toDebugString")
```

That is, `sparklyr` model objects contain a reference to the actual Scala / Spark object as a member called `.model`, and so invoke can be called on that.

**Comment by monicarodguev** [comment]
Excelent! Many thanks.

**Comment by kevinushey** [comment]
Glad I could help!
