### ISSUE TITLE
QuantileDiscretizer not finding setNumBuckets method

### ISSUE THREAD

**Issue by mbconnor** [rstudio/sparklyr#425]
Hello,

I'm currently trying to use ft_quantile_discretizer as follows:

`test <- ft_quantile_discretizer(df, 
                        input_col = col1,
                        output_col = col1_bin,
                        n_buckets = 5L)`

The following error is produced:

Error: failed to invoke spark command
17/01/12 17:25:39 WARN cannot find matching method class org.apache.spark.ml.feature.QuantileDiscretizer.setNumBuckets. Candidates are:
17/01/12 17:25:39 WARN setNumBuckets(int)
17/01/12 17:25:39 ERROR setNumBuckets on 86 failed

I have also tried calling the function explicitly, such as:

`transformed <- discretizer %>% invoke("setInputCol", col1) %>% 
  invoke("setOutputCol", col1_bin) %>% invoke("setNumBuckets", 
                                                as.numeric(5L)) %>% invoke("fit", df) %>% invoke("transform", 
                                                                                                        df)`

And the same error is produced.  I have also tried using the default value for n_buckets.  Any insight regarding this?

**Comment by kevinushey** [comment]
What version of sparklyr are you using? This should already be fixed in the current CRAN release (0.5.3).

**Comment by mbconnor** [comment]
Ah, could be.  I'm using 0.4 - thanks!

**Comment by javierluraschi** [comment]
Fixed.
