### ISSUE TITLE
cov, cor, sd, var are not available for use in mutate with Spark data frames

### ISSUE THREAD

**Issue by MilesMcBain** [rstudio/sparklyr#426]
This code:
```r
library(sparklyr) # v 0.5.1
library(tibble) # v 1.2
library(dplyr) # v 0.5.0

dat <- tribble(
  ~A, ~B,
  1,  1, 
  1,  5, 
  1,  10, 
  1,  5, 
  1,  1 
)

sc <- spark_connect(master = "local", version = "2.0.2")
spark_dat <- copy_to(sc, dat)

spark_dat %>%
  group_by(B) %>%
  mutate(A_sd = sd(A))
```

results in: `Error in eval(expr, envir, enclos) : could not find function "sd"`

Also fails in same manner for `cov`, `cor` and `var`.

**Comment by kevinushey** [comment]
Looks like this is an issue with the use of the `sql_prefix` function in our dplyr interface wrappers:

https://github.com/rstudio/sparklyr/blob/master/R/dplyr_spark_connection.R#L70-L73

Rather than using `sql_prefix()` we should just write the function names out by hand.

**Comment by Deninc** [comment]
hi, 
I understand that this issue was solved right?
I've installed the latest sparklyr version but it's still showing the same error: `Error in eval: could not find function "sd"`

**Comment by farrellm** [comment]
I started digging through the code because I am very interested in seeing this bug resolved.
I think the problem is here:
https://github.com/rstudio/sparklyr/blob/master/R/dplyr_spark_connection.R#L80-L90
Inside of a ```mutate``` we need window functions, not aggregate functions (I managed to get a different error message by adding a window entry for "sd").

**Comment by javierluraschi** [comment]
See https://github.com/tidyverse/dplyr/issues/2887, ideally we want this implemented in `dplyr`. 

In the meantime, here is a workaround:

```r
spark_dat %>%
  group_by(B) %>%
  summarize(A_sd = sd(A)) %>% left_join(spark_dat)
```

```
# Source:   lazy query [?? x 3]
# Database: spark_connection
      B  A_sd     A
  <dbl> <dbl> <dbl>
1     1     0     1
2     1     0     1
3    10   NaN     1
4     5     0     1
5     5     0     1
```
