### ISSUE TITLE
is the SVM implemented in sparklyr ?

### ISSUE THREAD

**Issue by jz1584** [rstudio/sparklyr#431]

**Comment by kevinushey** [comment]
Unfortunately no -- the `SVM` implementation provided by Spark is only available with the older RDD-based API; `sparklyr` exclusively uses the DataFrame-based API.

You'll have to make a feature request on the Spark JIRA page: https://issues.apache.org/jira/browse/spark/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel

**Comment by monicarodguev** [comment]
@kevinushey any idea when it will be implemented? Regards!

**Comment by kevinushey** [comment]
It looks like it will be available as part of Spark 2.2.0:

https://issues.apache.org/jira/browse/SPARK-14709?jql=text%20~%20%22SVM%20ml%22

Once that's released, we can think about adding a wrapper there.
