### ISSUE TITLE
defined schema dynamically

### ISSUE THREAD

**Issue by liuxiaodnn** [rstudio/sparklyr#434]
It seems a proper schema needs to be defined when using the SparkR function, dapply. In my case, the schema is dynamic, for example, it could be
schema <- structType(structField("v1", "double"),
                     structField("v2", "double"),
                     structField("v3", "double"))
or maybe the output data frame has 4 columns:
schema <- structType(structField("v1", "double"),
                     structField("v2", "double"),
                     structField("v3", "double"),
                     structField("v4", "double"))
Is there a good way to dynamically define the schema?

**Comment by kevinushey** [comment]
`SparkR` is a separate project from `sparklyr` -- you likely want to ask this on one of the Spark mailing lists. (See e.g. http://spark.apache.org/community.html)
