### ISSUE TITLE
NullPointerException in ft_string_indexer

### ISSUE THREAD

**Issue by monicarodguev** [rstudio/sparklyr#439]
Hello!

I tried to use `ft_string_indexer` with two variables of a dataframe I loaded into `spark`. With one of them the result was fine. But with the other one I got the following error:

```
Error: java.lang.NullPointerException
	at org.apache.spark.sql.types.Metadata$.org$apache$spark$sql$types$Metadata$$hash(Metadata.scala:215)
	at org.apache.spark.sql.types.Metadata$$anonfun$org$apache$spark$sql$types$Metadata$$hash$2.apply(Metadata.scala:203)
	at org.apache.spark.sql.types.Metadata$$anonfun$org$apache$spark$sql$types$Metadata$$hash$2.apply(Metadata.scala:203)
...
```

The code I used is:

```
base2<-bas %>%
+   ft_string_indexer(input_col = 'REGIONAL_COLOCACION', output_col = 'REGIONAL_COLOCACION_num')
```

I checked the column is in the dataframe with:

```
bas %>%
+   select(REGIONAL_COLOCACION) %>%
+   summarise(count = n() )
Source:   query [1 x 1]
Database: spark connection master=local[4] app=sparklyr local=TRUE

   count
   <dbl>
1 400766
```

Thanks for your help!

**Comment by kevinushey** [comment]
My best guess -- the `REGIONAL_COLOCACION` variable contains NULL values (or possibly empty values) and that's causing issues for the feature transformer.

You might have to explicitly drop missing values with e.g. `na.omit()`.

**Comment by monicarodguev** [comment]
Hi! Your guess is right, when I do the following I can use `ft_string_indexer`. 

```r
base2<-bas %>%
  select(REGIONAL_COLOCACION) %>%
  na.omit() %>%
  ft_string_indexer(input_col = 'REGIONAL_COLOCACION', output_col = 'REGIONAL_COLOCACION_NUM')
```

Nevertheless, when I do: 

```r
base2<-bas %>%
  select(REGIONAL_COLOCACION, var1, var2, ..., var25) %>%
  na.omit() %>%
  ft_string_indexer(input_col = 'REGIONAL_COLOCACION', output_col = 'REGIONAL_COLOCACION_NUM')
```

R  reply `* Dropped 27276 rows with 'na.omit' (400766 => 373490)` and then it never respond. Do you have any idea what I'm doing wrong?

Thanks!

**Comment by kevinushey** [comment]
My only guess is that the string indexer is working much more slowly than one might expect -- if you look at the Spark UI, do you see any active jobs re: the `ft_string_indexer` call?

**Comment by monicarodguev** [comment]
I tried at first selecting 8 variables and it worked perfectly. Now I'm selecting 31 variables and it is not responding. 
Now, regarding to your question: no, I don't see any active executors at the Saprk UI.

Any idea? Thanks!

**Comment by edgararuiz** [comment]
Hi @monicarodguev , the code/data be hitting against the limit of the computer or Spark session.  A couple of settings to check:

conf <- spark_config()
conf$`sparklyr.shell.driver-memory` <- "16G"
conf$spark.memory.fraction <- 0.8

The driver memory has to be adjusted based on the RAM in your computer.  The memory fraction reserves part of the memory requested for metadata and other tasks.  

Also, instead of going from 8 to 31 variables, can we try half that difference and try 20 first?

**Comment by monicarodguev** [comment]
Hello @edgararuiz ,

I made the settings. But my machine is not that good so I configured Spark with:

```
config <- spark_config()
config$"sparklyr.shell.driver-memory" <- "6G"
config$spark.memory.fraction <- 0.8
```

I tried with 10 variables and it worked, but it didn't when I tried with 12.

Something to mention is: my initial dataframe has 31 variables. If I remove the `select` line (I use all the 31 variables), the statement runs correctly.

**Comment by javierluraschi** [comment]
@monicarodguev sorry for the late reply, a few things to try:

- Upgrade the `sparklyr` package from CRAN.
- Try with `Spark 2.1` using `spark_installed_versions()`, `spark_unintall()`, `spark_install()` to uninstall your current version and move up.

Just to make sure this is not related to number of columns, I ran this over the `flights` table which comes with `19` columns:

```
library(sparklyr)
library(dplyr)
library(nycflights13)

sc <- spark_connect(master = "local", version = "2.1.0")
flights_tbl <- copy_to(sc, flights)

flights_tbl %>%
  na.omit(tailnum) %>%
  ft_string_indexer(input.col = "tailnum", output.col = "tailnum_idx")
```

```
* Dropped 9430 rows with 'na.omit' (336776 => 327346)
# Source:   table<sparklyr_tmp_26f195cebb2> [?? x 20]
# Database: spark_connection
    year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time arr_delay
   <int> <int> <int>    <int>          <int>     <dbl>    <int>          <int>     <dbl>
 1  2013     1     1      517            515         2      830            819        11
 2  2013     1     1      533            529         4      850            830        20
 3  2013     1     1      542            540         2      923            850        33
 4  2013     1     1      544            545        -1     1004           1022       -18
 5  2013     1     1      554            600        -6      812            837       -25
 6  2013     1     1      554            558        -4      740            728        12
 7  2013     1     1      555            600        -5      913            854        19
 8  2013     1     1      557            600        -3      709            723       -14
 9  2013     1     1      557            600        -3      838            846        -8
10  2013     1     1      558            600        -2      753            745         8
# ... with more rows, and 11 more variables: carrier <chr>, flight <int>, tailnum <chr>,
#   origin <chr>, dest <chr>, air_time <dbl>, distance <dbl>, hour <dbl>, minute <dbl>,
#   time_hour <dbl>, tailnum_idx <dbl>
```

I'll close this one but do open a new one if you are still experiencing issues, thank you!
