### ISSUE TITLE
ft_string_indexer with multiple variables

### ISSUE THREAD

**Issue by monicarodguev** [rstudio/sparklyr#442]
Hello guys,

I'm trying to use `ft_string_indexer `  with multiple variables as input. I tried two ways but neither of them worked. What I'm doing is the following:

**Trial 1**

```r
base1 <- base %>% na.omit()
base2 <- base1 %>% ft_string_indexer(input_col = c('var1','var2'), output_col=c('var1_n','var2_n'))
```
In this case, base has 15 columns, and only two are categorical. The error I get is:

```
Error in invoke_method.spark_shell_connection(spark_connection(jobj),  : 
  No status is returned. Spark R backend might have failed.
In addition: Warning message:
In if (is.na(object)) { :
  the condition has length > 1 and only the first element will be used
```

**Trial 2**

In this case I do not define the output col parameter: `base2 <- base1 %>% ft_string_indexer(input_col = c('var1','var2'))`. In this case the R session is aborted.

Thanks for your help.

**Comment by kevinushey** [comment]
Unfortunately, as far as I know, the Spark `StringIndexer` only accepts a single input column. You might need to manually join your two columns first, with e.g.

    base %>%
        mutate(pasted = paste(var1, var2))

**Comment by monicarodguev** [comment]
Ok thanks. I missunderstood the documentation.

**Comment by javierluraschi** [comment]
Looks resolved, closing.
