### ISSUE TITLE
Count performance [e.g., GROUP BY vs. COUNT(*)]

### ISSUE THREAD

**Issue by GaryWMN** [rstudio/sparklyr#443]
I have several ORC tables stored in HDFS on a 3-node cluster (accessed from an edge node -- can provide more connection details if that helps). 

When I run a simple count against either the entire table or a selected single column, the query takes about 50 times longer to come back than a query that groups and then counts. 

When I run a simple SELECT count(*) FROM sameTable in Hive (CLI or Web UI) the results come back almost instantaneously. 

Is this normal? Is there a better way to code the total counts? (For what it's worth, we want to use SparklyR in order to avoid having to craft our own SQL and pass it through [although the select count is obviously simple].)

Some samples are included below. 

**Sample code and results for the long running total count**

> someTable_tbl <- tbl(sc,"someTable")
someTable_tbl_ref <- someTable_tbl %>% select(someField) %>% count
someTable_tbl_ref

    Source:   query [1 x 1]
    Database: spark connection master=yarn-client app=sparklyr local=FALSE
       n
     <dbl>
    1 31443593

     user  system elapsed 
    1.021   1.253 588.105 

**Sample code and results for the faster running count by grouped column**

> someTable_tbl <- tbl(sc,"someTable")
someTable_tbl_cntbySomeField <- someTable_tbl %>% group_by(someField) %>% summarize(count = n())
someTable_tbl_cntbySomeField_d <- collect(someTable_tbl_cntbySomeField)
someTable_tbl_cntbySomeField_d

        user  system elapsed 
       0.152   0.049  13.959 

> someTable_tbl_cnttot_d <- someTable_tbl_cntbySomeField_d %>% ungroup() %>%  summarize(SomeFieldDistinct = n(), cntrows = sum(count))
someTable_tbl_cnttot_d

SomeFieldDistinct | cntrows
-------- | --------
\<int\> | \<dbl\>
11085 | 31443593	

**Sample code and results in Hive CLI**

> hive> select count(*) from someTable_tbl;

    OK
    31443593
    Time taken: 1.058 seconds, Fetched: 1 row(s)

**Comment by javierluraschi** [comment]
@GaryWMN Consider the following code:

```{r}
>library(sparklyr)
>library(dplyr)

>sc <- spark_connect(master = "local", version = "2.0.1")
>iris_tbl <- copy_to(sc, iris)

>iris_tbl %>% select(Petal_Width) %>% count %>% sql_render
<SQL> SELECT count(*) AS `n`
FROM (SELECT `Petal_Width` AS `Petal_Width`
FROM `iris`) `qyggirrgrp`

>iris_tbl %>% count %>% sql_render
<SQL> SELECT count(*) AS `n`
FROM `iris`
```

As you can see, selecting the `Petal_Width` field is creating a nested query that is increasing execution times as you correctly point out. We could consider optimizing queries in `dplyr` or `sparklyr`; however, for correctness, it should be the `Spark` project the ones that take this task since there might be cases where the optimization is not performant or possible at all.

Bottomline, we should try to write `dplyr` and `SQL` statements that are as concise as possible to reduce overhead.

**Comment by GaryWMN** [comment]
Thanks for the feedback and patience with a learner.
