### ISSUE TITLE
Bug when assign NA to a column 

### ISSUE THREAD

**Issue by VadymBoikov** [rstudio/sparklyr#448]
When I assign column to NA ( _or NaN, or NULL_), a spark dataframe makes it as list, not as actual NA value

```
> iris_tbl <- copy_to(sc, iris)
> x <- iris_tbl %>% mutate(Sepal_Width = NA)
> head(x)
Source:   query [6 x 5]
Database: spark connection master=yarn-client app=sparklyr local=FALSE

  Sepal_Length Petal_Length Petal_Width Species Sepal_Width
         <dbl>        <dbl>       <dbl>   <chr>      <list>
1          5.1          1.4         0.2  setosa   <lgl [1]>
2          4.9          1.4         0.2  setosa   <lgl [1]>
3          4.7          1.3         0.2  setosa   <lgl [1]>
4          4.6          1.5         0.2  setosa   <lgl [1]>
5          5.0          1.4         0.2  setosa   <lgl [1]>
6          5.4          1.7         0.4  setosa   <lgl [1]>
> head(collect(x)$Sepal_Width)
[[1]]
[1] NA
[[2]]
[1] NA
[[3]]
[1] NA
...
```

**Comment by kevinushey** [comment]
Some extra investigation: given this code

```
library(sparklyr)
library(dplyr)
sc <- spark_connect(master = "local", version = "2.1.0")

iris_tbl <- copy_to(sc, iris)
query <- iris_tbl %>%
  mutate(Sepal_Width = NA)
sql_render(query)
```

The query is rendered as:

```
> sql_render(query)
<SQL> SELECT `Sepal_Length`, `Petal_Length`, `Petal_Width`, `Species`, NULL AS `Sepal_Width`
FROM `iris`
```

We should instead use something like `cast(NULL as DOUBLE)`?

**Comment by javierluraschi** [comment]
@kevinushey found out when assigning `NA`, the column was being assigned a `NullType` which is now being collected as String, collecting/casting as double would also worked, just picked string collection since it's currently and we default to string for other non-standard data types.

**Comment by kevinushey** [comment]
@javierluraschi, I'm not sure if that solution is complete. For example, this:

```
iris_tbl %>% mutate(Sepal_Width = NaN)
```

will now generate a character vector, rather than a numeric vector containing `NaN`s.

Similarly, explicitly setting a column to `NULL` normally removes that column; e.g. with a local R `data.frame`:

```
> as_data_frame(iris) %>% mutate(Sepal.Width = NULL)
# A tibble: 150 × 4
   Sepal.Length Petal.Length Petal.Width Species
          <dbl>        <dbl>       <dbl>  <fctr>
1           5.1          1.4         0.2  setosa
```

We should double-check if that same behavior is expected for remote data stores.

Alternatively, we could just document that users should enforce types on their `NA` values, e.g.

```
iris_tbl %>% mutate(Sepal_Width = as.numeric(NA))
```
