### ISSUE TITLE
pivoting table using invoke

### ISSUE THREAD

**Issue by VadymBoikov** [rstudio/sparklyr#452]
Is there a way to do pivoting using invoke ?

I'm stuck on aggregate expression
```
 iris_tbl <- copy_to(sc, iris)
 spark_dataframe(iris_tbl) %>% 
    invoke("groupBy", "Species", list()) %>% 
    invoke("pivot", "Sepal.Width", list()) %>% 
    invoke(  ... ) # <-  how to create aggregate expression?
```

Original Scala code:
```
 iris
  .groupBy("Species")
  .pivot("Sepal.Width")
  .agg(avg("Sepal.length")) 
```

**Comment by javierluraschi** [comment]
How about?

```{r}
library(sparklyr)

sc <- connect(master = "local")
iris_tbl <- copy_to(sc, iris)

avgColumn <- invoke_static(sc, "org.apache.spark.sql.functions", "avg", "Sepal_Length")
spark_dataframe(iris_tbl) %>% 
    invoke("groupBy", "Species", list()) %>% 
    invoke("pivot", "Sepal_Width", list()) %>%
    invoke("agg", avgColumn, list())
```

For more generic column expressions, one could defined them as follows instead:

```{r}
avgColumn <- invoke_static(sc, "org.apache.spark.sql.functions", "expr", "avg(Sepal_Length)")
```

**Comment by javierluraschi** [comment]
Support for `sdf_pivot` was added to development version, will be available in CRAN under `sparklyr 0.6` on next release.

**Comment by dkincaid** [comment]
What functions can we use with sdf_pivot? Seems like the only one that works is "count". I tried "avg" and "sum" and both throw an exception - `No matched method found for class org.apache.spark.sql.RelationalGroupedDataset`

**Comment by kevinushey** [comment]
@dkincaid The set of supported functions are listed here:

https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.sql.RelationalGroupedDataset

The unit tests also show how you might use these functions:

https://github.com/rstudio/sparklyr/blob/133b2028e653d896f9eb762bf480113381b0d2ef/tests/testthat/test-pivot.R#L29-L45

https://github.com/rstudio/sparklyr/blob/133b2028e653d896f9eb762bf480113381b0d2ef/tests/testthat/test-pivot.R#L60-L64

**Comment by kevinushey** [comment]
We should probably make it easier to construct Spark column expressions and use those within `sdf_pivot()`.

**Comment by dkincaid** [comment]
Yes, agree if you can make it easier that would be great. Or at least include some examples in the documentation.  I did figure out that the easiest way to use this is to provide a list and then it's pretty easy to specify "sum" or "avg", etc.

**Comment by kevinykuo** [comment]
Once the `tidyr` functions are implemented we probably want to steer users toward them. We'll have to think about if we want to support both APIs then.
