### ISSUE TITLE
spark_normalize_path

### ISSUE THREAD

**Issue by niklasvm** [rstudio/sparklyr#454]
Hi @javierluraschi. With reference to #446, the *spark_normalize_path* function does not work correctly on windows using relative references.

the following code fixes the issue:

```{r}
function (path)
{
  if (normalizePath("s3n://", mustWork = FALSE) == "s3n://") {
    normalizePath(path, mustWork = FALSE)
  }
  else {
    if (substr(path,1,6)=='s3n://') {
      path
    } else {
      normalizePath(path, mustWork = FALSE)
    }
  }
}
```

**Comment by javierluraschi** [comment]
@niklasvm Thank you for the heads up, again! For anything urgent, feel free to drop me a ling to javier at rstudio.com. Pushing a fix now.

**Comment by andreasose** [comment]
I am not sure if this is the right place to ask, but the normalizePath acts weird on my Windows 7 system. 

`> normalizePath("hdfs://nameservice1/recommendations/datalake/lake")`
`[1] "C:\\R\\Innsikt_repo\\Sparklyr\\hdfs:\\nameservice1\\recommendations\\datalake\\lake"`
As you see, normalizePath defaults to pasting on the working directory, making the relative path absolute. So reading a parquet file fails.

Is it possible to have a some way of using the spark_read_parquet that avoids normalizing the path?
