### ISSUE TITLE
Malformed \uxxxx encoding error during spark_connect - result: sparklyr unusable

### ISSUE THREAD

**Issue by awchisholm** [rstudio/sparklyr#457]
I have installed the latest sparklyr
> packageVersion("sparklyr")
[1] ‘0.5.3.9000’

I have Spark 2.0.0 installed locally
> spark_installed_versions()
  spark hadoop                       dir
1 2.0.0    2.7 spark-2.0.0-bin-hadoop2.7

I'm running on Windows 7

When I run this
 > sc <- spark_connect(master = "local", spark_home=spark_home_dir(version = "2.0.0"))

I get this error
> Exception in thread "main" java.lang.IllegalArgumentException: Malformed \uxxxx encoding.

To try and troubleshoot this, I have edited the cmd files that are called within the Spark folder by simply turning echo on. The last file that is called is 

 > load-spark-env.cmd 

and the error that is logged is as follows

    "C:\Program Files\Java\jre1.8.0_74\bin\java" -Xmx128m -cp   ""C:\Users\myuser\AppData\Local\rstudio\spark\Cache\SPARK-~1.7\bin\..\jars"\*"  org.apache.spark.launcher.Main org.apache.spark.deploy.SparkSubmit --class sparklyr.Backend  "C:\Program Files\R\R-3.3.1\library\sparklyr\java\sparklyr-2.0-2.11.jar" 8880 6853   1>C:\Users\myuser\AppData\Local\Temp\spark-class-launcher-output-12543.txt 
    Exception in thread "main" java.lang.IllegalArgumentException: Malformed \uxxxx encoding.

It's something to do with path names I reckon but I can't get past it. Any ideas about what to do?

**Comment by javierluraschi** [comment]
Right, seems related to `/` vs `\`, bit of background https://stackoverflow.com/questions/17043037/ant-malformed-uxxxx-encoding-in-propertyfile-task, I would try with the latest version of `sparklyr`, if it still fails, open a new bug with as much information as possible, which OS, Spark version, sparklyr, etc. would be ideal if you could reproduce this on a VM with Windows installed from scratch for us to reproduce.
