### ISSUE TITLE
Path problem using spark_write_csv on windows 10 to Livy / Spark on Linux

### ISSUE THREAD

**Issue by Peter-pj** [rstudio/sparklyr#460]
sparklyr_0.5.3-9000

Im using sparklyr from RStudio on windows 10, connecting via Livy to a spark cluster in Azure (HDInsight), running Linux.

When calling spark_write_csv, my local (windows) user directory is appended to the path, which is of course not available on the cluster, see error below. The problem seems to be related to the use of the function normalizePath, which normalizes the path for Windows even though the path is going to be referenced  by Spark running on Linux. 

iris_tbl <- copy_to(sc, iris, "iris")
>spark_write_csv(iris_tbl, path = "iris.csv")

java.net.URISyntaxException: Relative path in absolute URI: C:%5CUsers%5Cpeter.johansson%5CDocuments%5Csparklyr%5Ciris.csv
...

**Comment by javierluraschi** [comment]
Seems resolved already, tried the following against Azure HDInsights running Spark 2.1:

```
> library(sparklyr)
> config <- spark_config()
> config <- livy_config(user = "admin", password = "<password>")
> sc <- spark_connect(master = "https://javierp-test.azurehdinsight.net/livy/", method = "livy", config = config)
> library(dplyr)
> iris_tbl <- copy_to(sc, iris, "iris")
```
