### ISSUE TITLE
Results of ft_one_hot_encoder() are short by one state when input contains zeroes

### ISSUE THREAD

**Issue by richierocks** [rstudio/sparklyr#464]
To reproduce, here is a data frame with 3 states, including zero.

```r
library(tibble)
library(sparklyr)
d <- data_frame(
  x = sample(c(0, 1, 2), 10, replace = TRUE)
)

sc <- spark_connect("local")
d_tbl <- copy_to(sc, d) 

d_tbl %>% 
  ft_one_hot_encoder("x", "y") %>% 
  View()
```

Each vector in `y` has length 2, but it should have length 3, since there are three states.

Wherever `x = 2`, the vector contains all zeroes (which is not "one hot").

**Comment by richierocks** [comment]
A related problem is that `ft_one_hot_encoder()` doesn't accept `integer` columns, which is odd, since the inputs must be whole numbers.  To see this, change the previous example to 

```r
d <- data_frame(
  x = sample(0:2, 10, replace = TRUE)
)
```

I see the error

```
Error in View : java.lang.IllegalArgumentException: requirement failed: Column x must be of type DoubleType but was actually IntegerType.
```

**Comment by richierocks** [comment]
Likewise, the `ft_one_hot_encoder()` should probably support `character` and `factor` inputs, since the documentation explicitly talks about turning categorical features into continuous features.

**Comment by kevinushey** [comment]
That's just how the `OneHotEncoder` works. Typically, you need to use e.g. `ft_string_indexer()` to convert a string to a double type, then call `ft_one_hot_encoder()` on the generated column. (See also the example at https://spark.apache.org/docs/2.0.2/ml-features.html#onehotencoder).

Note that that the `ft_` interface here is relatively lower level -- it only allows you to do what you might do on the Scala side. Building easier to use tools on top of our `ft_*` functions is something that's yet to come.

The default behavior of the one hot encoder feature transformer is to leave one class out as well (as it's primarily intended for use with logistic regression). See the documentation here for more details: https://spark.apache.org/docs/2.0.2/api/scala/index.html#org.apache.spark.ml.feature.OneHotEncoder

In particular, the `setDropLast()` API might be used here to ask Spark whether or not to drop the last entry. This isn't exposed currently in our interface; I'll see if I can make that change.

**Comment by richierocks** [comment]
OK, maybe this is another thing that just needs some documentation to explain that although it looks weird from an R point of view, it makes sense from a Spark perspective.

**Comment by javierluraschi** [comment]
No code change but need to improve documentation.

**Comment by patarol** [comment]
Is quite frustrating trying to use a function which its documentation is missing. You could add examples to [help users](http://r-pkgs.had.co.nz/man.html).
