### ISSUE TITLE
ft_binarizer() adds numeric field rather than logical

### ISSUE THREAD

**Issue by richierocks** [rstudio/sparklyr#465]
After calling `ft_binarizer()`, the output column is of type `DoubleType`. I expected it to be `BooleanType`, since the whole point is to convert a continuous variable into one with two states.

I guess that that behavior is to match Spark routine. If so, I don't know whether the best thing is to change the behavior to be more natural and return a `BooleanType`, or to keep the behavior and document that it is a little strange, and that you should remember to `mutate` your column afterwards.

**Comment by kevinushey** [comment]
Note that even modeling functions that expect 'binary' columns still want a 'double' type, hence why this is the default Spark behavior. (We do more work in our modeling routines to ensure that inputs and outputs are of the expected type, however)

**Comment by richierocks** [comment]
@kevinushey OK, maybe it just needs an example in the `?ft_binarizer` page to explain why it works the way it does.

**Comment by GriffinRidgeback** [comment]
On this topic, I can't seem to get ft_binarizer to work.  I'm following a simple example using the iris table.  I copy_to my sc and then issue the following code and get the displayed error:

ft_binarizer(iris_tbl)
Error in ensure_scalar_character(input.col) : 
  'NULL' is not a length-one character vector

iris_tbl is a 2-element structure, with the spark connection (src) and ops as its members.  I wish there were some good examples in the ?ft_* help pages.  

Any ideas on why this is happening?

Thanks in advance.

**Comment by javierluraschi** [comment]
Maybe no code change, but improve documentation?

**Comment by GriffinRidgeback** [comment]
That would be quite acceptable, thank you
