### ISSUE TITLE
Need ability to control boundaries in ft_quantile_discretizer()

### ISSUE THREAD

**Issue by richierocks** [rstudio/sparklyr#468]
If I call `ft_quantile_discretize()` on a continuous variable, I get one more bucket than I asked for, with the largest value in its own bucket.

To reproduce:

```r
d <- data_frame(
  x = rnorm(100)
)

sc <- spark_connect("local")

d_tbl <- copy_to(sc, d , overwrite = TRUE)
d_tbl %>% 
  ft_quantile_discretizer("x", "y") %>% 
  group_by(y) %>% 
  summarize(low = min(x), high = max(x), n = n()) 
```

The results look like this:

```
      y        low       high     n
  <dbl>      <dbl>      <dbl> <dbl>
1     0 -2.3703908 -0.9010508    19
2     1 -0.8490781 -0.2302440    20
3     2 -0.2194429  0.3725199    20
4     4  0.9299230  1.9267482    20
5     3  0.4111308  0.7920473    20
6     5  2.0935753  2.0935753     1
```

It looks like values on the boundaries aren't being handled sensibly. I guess this is just how Spark calculates things, but it would be nice to have some control over this.

**Comment by kevinykuo** [comment]
Closing, we're gonna be consistent with Spark here to ensure compatibility of pipelines.
