### ISSUE TITLE
[ml_lda()] Some Fundamental Question after Fitting ml_lda()

### ISSUE THREAD

**Issue by iamkbpark** [rstudio/sparklyr#471]
Dear Team:

Based on the clear example of ml_lda(), now I can successfully fit the model with my data. Compared to the fitting speed of LDA() from topicmodels package in my single PC, it is such an amazing experience as a novice user of Spark & SparklyR. I do appreciate that.

Since I am R-myopic user and have only got accustomed to use LDA() from topicmodels, several questions still remain unanswered though Spark Documentation seems well explained.
Some of the questions are as follows:

It seems there are two notable output objects after fitting ml_lda(): topic.matrix & estimated.doc.concentration
topic.matrix: my main question is, "How could I interpret the value of this table?" or "What values are these?"
Spark Document says (https://spark.apache.org/docs/1.4.0/api/java/org/apache/spark/mllib/clustering/LDAModel.html#vocabSize()), it is a VocabSize & K, but I still don't understand what the cell value means and how I can interpret those.

estimated.doc.concentration: Also, please advise how to interpret these values. (Are these Alpha?)

How could I access or examine the actual words ofVocabSize? What I would like to explore is the fundamental output in LDA() such as Top-Terms in each Topic(ex. get_terms(), terms(), topics() functions in topicmodles package)

Lastly, How could I access the outputs similar to LDA() such as Beta, Gamma, Log-Likelihood(to find Optimal K)?

I am a bit confused about parameters used in ml_lda() since I am a newbie and if you could advise aforementioned questions, it will be greatly appreciated.
Thank you so much for your effort, time and help.

Sincerely,
K.B. Park

**Comment by serenasignorelli** [comment]
Hi, I'm experiencing the same problem. 

I found a solution here: [http://stackoverflow.com/questions/31780376/trouble-in-understanding-the-lda-topic-model-in-mllib](url) but don't know how to implement it into sparklyr. 

They suggest to call DistributedLDAModel.topicDistributions() or DistributedLDAModel.javaTopicDistributions() in Spark 1.4. 

Anyone cal help?

Thank you,
Serena

**Comment by javierluraschi** [comment]
@iamkbpark @serenasignorelli good questions, take a look at https://github.com/rstudio/sparklyr/pull/968 and open a new github issue if you still think there are gaps to close. Thank you for this feedback!

**Comment by iamkbpark** [comment]
@javierluraschi I do appreciate your work and help!
