### ISSUE TITLE
SparklyR only connecting to 2/6 workers on standalone spark cluster

### ISSUE THREAD

**Issue by renegademonkey** [rstudio/sparklyr#472]
Hi there,

I've just finally managed to set up my stack to use RStudio to connect to a standalone spark cluster (with file storage in CassandraDB) via sparklyR.

The only issue I still haven't been able to resolve is how to get my sparklyR connection to utilise all the available worker nodes on cluster (there are 6 in total). Every time I connect, the Executor Summary page shows only 2 workers are being utilised by the sparklyR connection (with 1 executor on each node). There are plenty of resources (cores / ram) still available on the cluster, and the config file limits executor memory and cores to a reasonable fraction of the total. 

I've tried playing around with the config.yml file for the spark_connect call, including setting `spark.executor.instances: 6` and `spark.num.executors: 6`, but that doesn't make a difference. Is there another setting I can use to get sparklyR to use all the nodes? Can I somehow pass a list of all the worker IP addresses to spark_connect so that it connects to them all?

My setup is as follows: 
RStudio: 1.0.136, 
sparklyR: 0.5.3-9000, 
Spark version (on cluster & locally): 2.0.0.

**Comment by edgararuiz** [comment]
Hi @renegademonkey, can you try what's in this Stackoverflow article and let me know if it works for you? http://stackoverflow.com/questions/29955133/how-to-allocate-more-executors-per-worker-in-standalone-cluster-mode

There seems to be some changes that  can be made to the ```conf/spark-env.sh``` file that may be the last piece we need.

**Comment by renegademonkey** [comment]
Hi @edgararuiz - thanks for the prompt response!

I had previously looked at that, but changing the conf file on the cluster is not the problem - other Spark applications on the cluster (i.e. run from Java clients) have no problem accessing all 6 workers, and there are plenty of resources spare for sparklyR to use.

Any other ideas?

**Comment by renegademonkey** [comment]
Finally solved it! It was so simple and obvious I cannot believe I missed it.

The config file had the settings:

```
spark.executor.cores: 5
spark.cores.max: 12

```
Which of course means it could not start more than 2 (5-core) executors, since the max number of cores the entire app was allowed was 12.

**Comment by edgararuiz** [comment]
So is the new setting spark.cores.max: 30?

Thanks

Edgar Ruiz. Solutions Engineer. RStudio.com <https://www.rstudio.com/>| edgar@rstudio.com <mailto:edgar@rstudio.com>(228)-697-9248 | LinkedIn <https://www.linkedin.com/in/edgararuiz>

**Comment by renegademonkey** [comment]
yes. and THEN sparklyr sets up 6 workers, one on each of the available cluster nodes.
