### ISSUE TITLE
Error while connecting with spark with sparkly using RStudio with Kerberos enabled machines

### ISSUE THREAD

**Issue by GitanjaliThete** [rstudio/sparklyr#475]
I have 2 machine clustor. I am trying to connect to spark. When I try to connect using R shell, It is working fine.
Getting following error from Rstudio.

Connection:

sc <- spark_connect(master="yarn-client",spark_home = "/usr/hdp/2.5.3.0-37/spark",
config = list(
default = list(
spark.submit.deployMode= "client",
spark.yarn.keytab= "path/keytab",
spark.yarn.principal= "user",
spark.executor.instances= 1,
spark.executor.memory= "250M",
spark.executor.cores= 4,
spark.driver.memory= "250M")))

Error:

Failed during initialize_connection: org.apache.hadoop.service.ServiceStateException: java.io.IOException: Failed on local exception: java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]; Host Details : local host is: "host1"; destination host is: "host2":8020;

**Comment by javierluraschi** [comment]
@GitanjaliThete are you using RStudio Server PRO? Kerberized sessions are only supported in the RStudio Server PRO. If that's the case, you would have to configure:

- /etc/pam.d/rstudio-original
- /etc/pam.d/rstudio-session
- /etc/rstudio/rserver.conf

For details, see http://docs.rstudio.com/ide/server-pro/r-sessions.html#kerberos - Has this been configured already?

**Comment by GitanjaliThete** [comment]
Thank javierluraschi!

Yes, I installed RStudio Server Pro 1.0.136 on CentOS. Also configured following files for PAM
Still not able to connect. Please let me know in case made some mistake.

/etc/pam.d/rstudio
#%PAM-1.0
auth sufficient pam_rootok.so
session required pam_env.so readenv=1
session required pam_env.so readenv=1 envfile=/etc/default/locale
session required pam_limits.so
@include common-auth
@include common-account
@include common-session
auth include system-auth
auth optional pam_mount.so use_first_pass
account required pam_unix.so


/etc/pam.d/rstudio-session 

auth       sufficient pam_rootok.so
session    required   pam_env.so readenv=1
session    required   pam_env.so readenv=1 envfile=/etc/default/locale
session    required   pam_limits.so
@include common-auth
@include common-account
@include common-session
auth     include    system-auth
auth     optional   pam_mount.so use_first_pass
account  required   pam_unix.so


/etc/rstudio/rserver.conf

# Server Configuration File
auth-pam-sessions-profile=rstudio-session 
auth-pam-sessions-use-password=1

**Comment by kevinykuo** [comment]
Try opening up a terminal from within the browser (tools -> shell?) and run `kinit`

**Comment by GitanjaliThete** [comment]
It is working after kinit. Thanks :)
