### ISSUE TITLE
Error: Variables must be length 1 or 1.

### ISSUE THREAD

**Issue by kenahoo** [rstudio/sparklyr#477]
I have an Amazon EMR cluster with RStudio 1.0.136, sparklyr 0.5.3.9000 (installed via `devtools::install_github()` today, so I believe it's at commit 78bbbf0162d8), and EMR release `emr-5.3.0` (including Spark 2.1.0 and R 3.2.2).

In a fresh RStudio session, I get the following error when I try to read from an S3 bucket:

```
> library(sparklyr)
> library(dplyr)
> sc <- spark_connect(master = "local")
> cv <- spark_read_csv(sc, path='s3://wl-applied-math-dev/solar-forecasting/pi_data', name='pidata', memory=FALSE, infer_schema=FALSE)
Error: Variables must be length 1 or 1.
Problem variables: 'database'
```

I also get a dialog box that pops up when the call finishes:

<img width="386" alt="screen shot 2017-02-08 at 11 14 08 am" src="https://cloud.githubusercontent.com/assets/111939/22748488/d8835ccc-edef-11e6-8150-88366d6ea453.png">

The returned value `cv` *is* an object of class `"tbl_spark"` that I can get data out of.  It reports dimensions of 22,619,520 x 4 and has the columns I expect.

Through interactive debugging in RStudio, it looks like the errors are emitted inside the `spark_read_csv -> spark_partition_register_df -> on_connection_updated` call.  Looks like it's trying to update RStudio's listing of tables maybe?

**Comment by kevinushey** [comment]
Any chance you can provide an example that reproduces the issue with a local Spark cluster running?

I'm fairly sure this is an issue caused by the `tibble` package; does updating / reinstalling that package make a difference?

What's your `sessionInfo()`?

**Comment by kenahoo** [comment]
In the above example I used `master="local"`, do you mean something else by "local Spark cluster"?

Here's my `sessionInfo()`:

```
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Amazon Linux AMI 2016.09

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.5.0         sparklyr_0.5.3-9000

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9     withr_1.0.2     digest_0.6.12   rprojroot_1.2   assertthat_0.1  mime_0.5       
 [7] R6_2.2.0        jsonlite_1.2    xtable_1.8-2    DBI_0.5-1       backports_1.0.5 magrittr_1.5   
[13] httr_1.2.1      rstudioapi_0.6  config_0.2      tools_3.2.2     shiny_1.0.0     parallel_3.2.2 
[19] yaml_2.1.14     httpuv_1.3.3    base64enc_0.1-3 htmltools_0.3.5 tibble_1.2     
```

I'm at version 1.2 of `tibble`, which is the latest release.  Would you recommend a GitHub install?

**Comment by kevinushey** [comment]
Sorry, I misread that! I'll try your repro case and see if I can figure out what's going on.

**Comment by kenahoo** [comment]
Looks like I can trigger the same error by doing this:

```
.Call("rs_connectionUpdated", "Spark", "local - sparklyr", "pidata")
```

My "Spark" pane in RStudio shows a "local" connection, but not a "local - sparklyr" connection, so I'm thinking that's the mismatch?

**Comment by javierluraschi** [comment]
@kevinushey this seems to only repro with `Spark 2.1.0`, the problem seems to be somewhat related with `sdf_collect` since one of the columns returns a `character(0)` for the `database` field while the others return entries, I have not looked into this further than this. I think this is enough to reproduce:

```
sc <- spark_connect(master = "local", version = "2.1.0")
copy_to(sc, iris)
```

**Comment by kevinushey** [comment]
Okay, I've found the issue -- it's indeed a problem in `sparklyr` whereby a column containing a single empty string is turned into an empty vector. I'll get this fixed!

**Comment by kevinushey** [comment]
Should be fixed with https://github.com/rstudio/sparklyr/commit/355810e3e2bdc74cb79ce30835876be007b69e35 -- thanks for reporting!

**Comment by kenahoo** [comment]
Cool, thanks for the quick turnaround.

**Comment by ray-p144** [comment]
@javierluraschi Is there a reason that this fix isn't implemented in any of the releases? When I download the releases (0.5.5, 0.5.6, or bugfix/hotfix-0.5.6) and install them manually (or use `install.packages("sparklyr")` to download `sparklyr 0.5.5` from cran directly) the old version of `sdf_collect` is still being used (I've been manually fixing it so far with `assignInNamespace` when using one of these versions), but when I pull the current dev version from master the correct version of the function is being used. 

```r
devtools::install_github("rstudio/sparklyr", ref = "bugfix/hotfix-0.5.6", force = TRUE)
library(dplyr)
library(sparklyr)
sc <- spark_connect(master = "local")
mt_tbl <- copy_to(sc, mtcars)
# Error: Column `database` must be length 1 or 1, not 0

# Popup error: "R code execution error"

spark_disconnect_all()

detach("package:sparklyr", unload = TRUE)

devtools::install_github("rstudio/sparklyr", ref = "master", force = TRUE)
# commit 14a8bb332d24161f67089e6762b9d8d66e102e4c
library(dplyr)
library(sparklyr)
sc <- spark_connect(master = "local")
mt_tbl <- copy_to(sc, mtcars)
# No error or popup occurs

spark_disconnect_all()
```
Note: This error only occurs when using RStudio, not when using the console. I'm assuming because it is trying to update the spark connection view panel.

**Comment by randomgambit** [comment]
Hello, I am getting the same error by simply using `spark_read_csv`. I have the latest version of `sparklyr` coming from Cran. My csvs contain text and yes, they may contain missing values. How can I fix that? I tried to get the current master but I only see a zip file (I am on linux with limited admin rights)
