### ISSUE TITLE
Easy way to run Scala code within sparklyr?

### ISSUE THREAD

**Issue by jukiewiczm** [rstudio/sparklyr#479]
Hello,
I have question regarding running custom Scala code through sparklyr. I wanted to integrate the Scala code I have already written with some additional R/sparklyr code. Basically, my Scala code creates some DataFrames which I would like to preprocess later in sparklyr.

Is there a clean way to do this?

Thanks

**Comment by javierluraschi** [comment]
@jukiewiczm yes, we have an example here: https://github.com/javierluraschi/sparkhello

**Comment by jukiewiczm** [comment]
@javierluraschi Great, thanks! I believe I can close this one now. Thanks for your great work on sparklyr!
