### ISSUE TITLE
Get rotated data from ml_pca()

### ISSUE THREAD

**Issue by richierocks** [rstudio/sparklyr#483]
If I run a PCA using `stats::prcomp()`, I get the rotated data returned.  That is, a matrix where each row contains data for a row of input data, and each column contains data for a principal component.

For example,

```r
pca_model_local <- prcomp(USArrests, scale = TRUE)
pca_model_local$x
```

If I use `ml_pca()`, I don't get this matrix back.

```r
sc <- spark_connect("local")
us_arrests <- copy_to(sc, USArrests)
pca_model_spark <- us_arrests %>% ml_pca()
str(pca_model_spark)
```

**Comment by dsblr** [comment]
@richierocks try pca_model_spark$components  you will get the rotation.

iris_dat <- copy_to(sc,iris, overwrite = TRUE)
ir_pc_dat <- iris_dat %>% select(-Species) %>% ml_pca()
ir_pc_dat$components

                                    PC1         PC2         PC3        PC4
Sepal_Length -0.36138659 -0.65658877  0.58202985  0.3154872
Sepal_Width   0.08452251 -0.73016143 -0.59791083 -0.3197231
Petal_Length -0.85667061  0.17337266 -0.07623608 -0.4798390
Petal_Width  -0.35828920  0.07548102 -0.54583143  0.7536574

Hope it helps.
