### ISSUE TITLE
Unable to submit job using livy in yarn mode 

### ISSUE THREAD

**Issue by ggittu** [rstudio/sparklyr#499]
Trying to connect to a remote server using livy
config <- livy_config(user = "xxxx", password = "yyy")
sc <- spark_connect(master = "http://livy-host-url:xxxx",
                    method = "livy",
                    app_name = "sparklyr",
                    config = config)

The job gets submitted to the remote cluster, but its getting submitted in local spark mode in cluster. Is it possible to submit a parameter to livy setting "spark.master": "yarn-cluster" so livy understand to connect in yarn mode? 

I saw to connect in yarn-mode need to specify "master = yarn-client" inside spark_connect, but while connecting via livy I am supposed to give livy url here. Is there any way I can achieve this ?

**Comment by javierluraschi** [comment]
@ggittu Could you set `spark.master` to `yarn-client` in `spark-defaults.conf`?

Notice that `sparklyr 0.5` does not currently support `yarn-cluster` mode, but `yarn-client` is sufficient for most configurations.

**Comment by ggittu** [comment]
@javierluraschi I did set spark.master to yarn-client, but still it is connecting in local mode. Am I still missing something?
Is there a way to submit yarn job to a remote spark cluster without using livy ?

**Comment by edgararuiz** [comment]
Hi @ggittu, just curios, what steps did you take to install Livy in that cluster?

**Comment by ggittu** [comment]
@edgararuiz We are using Hortonworks Stack, installation is pretty much straight forward. All other services say zeppelin is connecting in yarn mode via livy.

**Comment by javierluraschi** [comment]
@ggittu Looks like in Hortonworks, Zeppelin might be the one starting Livy so you might need to change the Zeppelin config or start Livy standalone yourself? See https://community.hortonworks.com/questions/50886/livy-server-with-yarn-cant-connect.html

From a standalone Livy confix, setting `spark.master` should be enough, see: https://issues.cloudera.org/browse/LIVY-29

Does this help?

**Comment by ggittu** [comment]
@javierluraschi Livy is separated from zeppelin in hortonworks stack or in other words Livy have no dependency with zeppelin( it is running by itself). I just mentioned about zeppelin just to point out that other services can make use of the livy server to run in yarn-client mode. To make sure I even tried to submit job to livy using rest API and it works in yarn-mode. And our spark.master is set to yarn-client.

**Comment by hj1210** [comment]
I had the same problem. Changing the spark default config didn't help me. I had to set livy.spark.master=yarn-client in livy.conf

**Comment by javierluraschi** [comment]
Thanks hj1210 for the `livy.spark.master=yarn-client` in `livy.conf` suggestion, this suggestion should work for @ggittu, closing.

Related, there are now more connections options available from https://github.com/rstudio/sparklyr/pull/969
