### ISSUE TITLE
Working with YARN cluster in client mode

### ISSUE THREAD

**Issue by dselivanov** [rstudio/sparklyr#50]
How to connect to yarn cluster in `yarn-client` mode?
With `SparkR` my connection looks like:
```r
spark_env = list('spark.executor.memory' = '8g', 
                 'spark.executor.instances' = '32',
                 'spark.executor.cores' = '4',
                 'spark.driver.memory' = '4g',
                 'spark.kryoserializer.buffer.max' = '1g',
                 'spark.yarn.executor.memoryOverhead' ='1000')
sc <- sparkR.init(master = "yarn-client", appName = "sparkr", sparkEnvir = spark_env)
```

**Comment by javierluraschi** [comment]
sc <- spark_connect(master = "yarn-client")

with the SPARK_HOME pointing to the right spark directory?

To pass the config values you can use the config parameter in spark_connect or the config.yaml file based on the template included in inst/config

**Comment by dselivanov** [comment]
Indeed, it works. When I tried to connect first time, for some reason it get stuck for several minutes. `spark_log` also  showed nothing, so I decided to ask... 
But now it works fine. Thank you, closing.
