### ISSUE TITLE
Installation issue on Windows

### ISSUE THREAD

**Issue by niklasvm** [rstudio/sparklyr#513]
I have just tried to install the latest development version with

```{r}
devtools::install_github('rstudio/sparklyr')
```
and am getting the following error:
```{r}
* installing *source* package 'sparklyr' ...
** R
** inst
** tests
** preparing package for lazy loading
Error in conformMethod(signature, mnames, fnames, f, fdef, definition) : 
  in method for 'sqlParseVariables' with signature 'conn="spark_connection"': formal arguments (conn = "spark_connection", sql = "spark_connection", ... = "spark_connection") omitted in the method definition cannot be in the signature
Error : unable to load R code in package 'sparklyr'
ERROR: lazy loading failed for package 'sparklyr'
* removing '###############/Documents/R/R-3.3.2/library/sparklyr'
Error: Command failed (1)
```

I am usually able to install development versions without issue.

I was able to install this version on a linux machine successfully.

**Comment by javierluraschi** [comment]
@niklasvm Do you happen to be using the latest version of `DBI`? Could you try with the CRAN version of `DBI` instead?

**Comment by alberthkcheng** [comment]
I encountered the same problem and solve it using the way @javierluraschi suggested. Thanks.

`install.packages("DBI")`

**Comment by javierluraschi** [comment]
The suggestion seemed to resolve this issue for at least one of us, closing.
