### ISSUE TITLE
How to connect ORACLE and read table using sparklyr

### ISSUE THREAD

**Issue by Venkatraman92** [rstudio/sparklyr#517]
selectionquery <- "Select * from tablename"
dbjarhome <- c('Java_path,'odbc_jar') 
urldetails <-c('oracle.jdbc.driver.OracleDriver','jdbc:oracle:thin:@port:database_name','username','password')
drv = JDBC(urldetails[[1]],dbjarhome[[2]], identifier.quote='`')
con <- dbConnect(drv, urldetails[[2]], urldetails[[3]], urldetails[[4]])
data<- dbGetQuery(con, selectionquery)
spk_data <- DBI::dbWriteTable(sc, tablename, data)

Error in dbExistsTable(conn, name) : 
  object 'tablename' not found

Note: is it a right syntax m i following to connect oracle using sparklyr?

**Comment by kevinykuo** [comment]
I'd start with looking at `spark_read_jdbc`

**Comment by Venkatraman92** [comment]
#kevinykuo is there any other option to connect oracle to sparklyr?
I need that spark_read_jdbc function, R u still working on it?

**Comment by tarunparmar** [comment]
@kevinushey Hi Kevin, are you folks planning to have `spark_read_jdbc` function anytime soon?
Also as @Venkatraman92 asked, would that be a correct syntax to connect from scratch ?

**Comment by kevinushey** [comment]
`spark_read_jdbc()` is already available in the development version of `sparklyr`. @javierluraschi, do we have any examples of its use?

**Comment by edgararuiz** [comment]
@kevinushey & @javierluraschi - If there's not, this may be a great opportunity to see if we want to write this as a vignette inside the package and then I can pull it into the site via pkgdown, or if you'd prefer an article about it on the site.  The same goes for the issue we have opened for the site for different connection settings.

**Comment by javierluraschi** [comment]
We do not have examples yet, but @tarunparmar @Venkatraman92 if you hit any issues with `spark_read_jdbc` let us know to address them.

**Comment by tarunparmar** [comment]
hi @javierluraschi , current help does not provide and example and this is what Usage says `spark_read_jdbc(sc, name, options = list(), repartition = 0,
  memory = TRUE, overwrite = TRUE)`.
Can you give a sample example on how to incorporate Oracle db info, I am guessing it goes inside `options = list()` but just want to make sure I follow the correct way.

**Comment by tarunparmar** [comment]
Hi @javierluraschi, This is what I tried but that did not work...

`spark_read_jdbc(sc, "temp",
                options = list(url = "jdbc:oracle:thin://databasename:1521/servicename?user=abcd&password=abc123",
                               driver = "oracle.jdbc.driver.OracleDriver",
                               dbtable = "dbschema.sampletable"),
                memory = TRUE)`

**Comment by edgararuiz** [comment]
@tarunparmar - Can you give me some background of where are you testing this? Is this a Hadoop cluster, standalone Spark?

**Comment by tarunparmar** [comment]
We are setting up RStudio Pro - spark cluster, no hadoop. So I thought would be best to test something with sparklyr to get data directly from Oracle db into spark rather ran getting into memory through R and then move it to spark.
I saw some exmples of it with SparkR package and learned that it can be done using JDBC.

**Comment by edgararuiz** [comment]
Ok, in that case, would it be possible to ETL the data into individual files, maybe split by transaction day or something like that?  If placed on a share that all of the nodes in your cluster can access then they will be able to read the files in parallel (aka faster) and without a dependency on a connection to Oracle.  Basically the approach delineated in this article, but with a network share instead of S3: http://spark.rstudio.com/example-s3.html

**Comment by javierluraschi** [comment]
@tarunparmar this is the best example we have so far for `spark_read_jdbc`: https://gist.github.com/javierluraschi/87f2e90ca2a682b7013fdbdd28a8f55c - Let us know if you need more pointers. I have not tried this against the Oracle JDBC driver, but in theory, it should work as well as the sample I provide using MySQL.

**Comment by javierluraschi** [comment]
@tarunparmar closing this one with the JDBC example provided; however, shoot me an email to javier at rstudio.com if you still hit issues using JDBC data extraction.

**Comment by MCM-Math** [comment]
spark_read_jdbc seems to have noticable limitations as to what kinds of data it can work with, and little if any documentation describing them.  I keep getting "Unsupported type 101" from this function, where I don't get that error elsewhere for the same data.
