### ISSUE TITLE
Error on "reached elapsed time limit" when reloading R session in a cluster

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/sparklyr#52]
- Installed `sparklyr` 0.2.7 (commit ca52f8700c09183feb596bc465760b51e660953d) in the AWS cluster environment
- Restarting R session after install was complete gave this error:

```
Restarting R session...

Loading required package: sparklyr
Error in .recMembers(members, .methodsNamespace) : 
  reached elapsed time limit
```

and every time I restart I get a variation of that error:

```
Restarting R session...

Loading required package: sparklyr
Error in getGeneric(what, FALSE, where) : reached elapsed time limit

Restarting R session...

Loading required package: sparklyr
Error in is(f, "groupGenericFunction") : reached elapsed time limit
```

**Comment by javierluraschi** [comment]
Would you mind setting and environment for us where this reproes and give @kevinushey and me access to it?

**Comment by kevinushey** [comment]
Also curious what objects were available in your global environment -- I've discovered that strange things  go wrong when attempting to `save()` / `load()` S4 objects.

**Comment by javierluraschi** [comment]
@kevinushey what would be an easy way for @fereshtehRS to dump her global environment here? maybe `str(as.list(.GlobalEnv))`?

**Comment by kevinushey** [comment]
Yeah, that would be a simple way. If we wanted to actually inspect the objects `save.image("image.RData")` would be useful as well; may be okay as long as the objects aren't prohibitively large.

**Comment by kevinushey** [comment]
Another thing -- have you set the rsession option for `limit-cpu-time-minutes`? Is it possible that this is timing out for some reason?

**Comment by fereshtehRS** [comment]
@kevinushey @javierluraschi 
This is not happening at the moment. But may be I can get the global environment next time that I run into the error.
I checked that environment, and `limit-cpu-time-minutes` was not set.

**Comment by fereshtehRS** [comment]
This might be a generic IDE warning; nothing to do with sparklyr.
I was doing something else in the IDE, and got this:

```
Warning message:
In rootVP(pvp) : reached elapsed time limit
```

**Comment by kevinushey** [comment]
@fereshtehRS, can you please execute this code so we can see what's going on?

    trace(setTimeLimit, quote(cat(paste("-", sys.calls(), collapse = "\n"))))

Hopefully, you should see a call stack printed to the console whenever `setTimeLimit` is called, and we can see where it's being called from. (I believe this is the function responsible for that message)

**Comment by fereshtehRS** [comment]
@kevinushey I set that in my IDE Desktop, and ran an R script, which produced a very long debug output. The end part of that is: (let me know if you want to see everything in the console)

```
- tryCatchList(expr, classes, parentenv, handlers)
- tryCatchOne(expr, names, parentenv, handlers[[1]])
- doTryCatch(return(expr), name, parentenv, handler)
- .rs.valueFromStr(obj)
- .rs.withTimeLimit(1, fail = "<truncated>", {
    capture.output(try(str(val), silent = TRUE))
})
- setTimeLimit()
- .doTrace(cat(paste("-", sys.calls(), collapse = "\n")), "on entry")
- eval.parent(exprObj)
- eval(expr, p)
- eval(expr, envir, enclos)
```

Right after this I ran a head() command, and that caused the warning, but no debug messages:

```
Warning message:
In match(x, table, nomatch = 0L) : reached elapsed time limit
```

**Comment by javierluraschi** [comment]
@fereshtehRS I've been working my way from oldest to newest bugs and I've finally reached this point.

Could you upgrade to the latest version of spark and rerun this issue? We've been polishing package-dependency issues so I'm hoping one of them improved this as well.

If this is still an issue in the latest build, could you reming me the url/credentials through slack?

**Comment by fereshtehRS** [comment]
I haven't been able to reproduce this for the past few days. Closing the ticket.
