### ISSUE TITLE
Add feature : read/write avro file format

### ISSUE THREAD

**Issue by wouwou4444** [rstudio/sparklyr#524]
I need to read and write to an hdfs cluster where the format of files is "avro"

Is there any way to get arround the standard functions to do it ?
It would be great to have a spark_read_avro and spark_write_avro which are also standard format in hdfs environments.

**Comment by chezou** [comment]
I've started to work as extension of sparklyr https://github.com/chezou/sparkavro

**Comment by chezou** [comment]
I've finished the implementation of the first version of sparkavro.
https://github.com/chezou/sparkavro

If you have any issue please file in my github repo.

**Comment by chezou** [comment]
@javierluraschi Do you have a plan to include [spark-avro](https://github.com/databricks/spark-avro)? Or, could you add [my extension](https://github.com/chezou/sparkavro) into [the document](http://spark.rstudio.com/extensions.html)? After that, I think it would be time to close this issue.

**Comment by edgararuiz** [comment]
Hi @chezou, thanks for your extension.  I just added it to the list in the Extensions page as you requested: http://spark.rstudio.com/extensions.html (cc: @javierluraschi )

**Comment by chezou** [comment]
Thanks @edgararuiz !

**Comment by javierluraschi** [comment]
@chezou Thanks! Really neat extension!
