### ISSUE TITLE
spark_write_csv fails when writing to aws  

### ISSUE THREAD

**Issue by stevetbright** [rstudio/sparklyr#526]
I am trying to write output to an s3 directory that has already been removed ( with `aws s3 rm s3://bucket/dir --recursive` )

When I run `spark_write_csv( tbl, 's3://bucket/dir/' )` I get

`Error: org.apache.spark.sql.AnalysisException: path  s3://bucket/dir/ already exists`

This is after explicitly removing that directory and verifying that it is no longer there

Is there a way to specify overwriting ? or is there some other way to ensure that spark can properly see that this directory is removed?

**Comment by javierluraschi** [comment]
Implemented in development `sparklyr` and planned to be released in `sparklyr 0.6`. With latest version, try:

```
spark_write_csv(tbl, "s3://bucket/dir/", mode = "overwrite")
```

See: https://github.com/rstudio/sparklyr/pull/579
