### ISSUE TITLE
Error in Connection to Spark

### ISSUE THREAD

**Issue by wenbo5565** [rstudio/sparklyr#529]
RStudio Version 0.99.903 on Windows 8.1

Thanks.

> sc = spark_connect(master="local")

Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (8344): Gateway in port (8880) did not respond.
    Path: C:\Users\wenbma\AppData\Local\rstudio\spark\Cache\spark-1.6.2-bin-hadoop2.6\bin\spark-submit2.cmd
    Parameters: --class, sparklyr.Backend, --jars, "C:\Users\wenbma\Documents\R\win-library\3.3\sparklyr\java\spark-csv_2.11-1.3.0.jar","C:\Users\wenbma\Documents\R\win-library\3.3\sparklyr\java\commons-csv-1.1.jar","C:\Users\wenbma\Documents\R\win-library\3.3\sparklyr\java\univocity-parsers-1.5.1.jar", "C:\Users\wenbma\Documents\R\win-library\3.3\sparklyr\java\sparklyr-1.6-2.10.jar", 8880, 8344

---- Output Log ----
'C:\Users\wenbma\AppData\Local\rstudio\spark\Cache\SPARK-~1.6\bin\SPARK-~4.CMD' is not recognized as an internal or external command,
operable program or batch file.

---- Error Log ----

**Comment by javierluraschi** [comment]
@wenbo5565 I've never seen `~` in the Spark path. What do you get from running:

```
sparklyr::spark_home_dir()
normalizePath(sparklyr::spark_home_dir())
normalizePath(file.path(sparklyr::spark_home_dir(), "bin", "spark-submit2.xmd")
```

The problem might be that your system is configured to convert long folder names to relative paths or something around those lines.

**Comment by javierluraschi** [comment]
This issue is not actionable without requested information, also, haven't seen new issues reporting this one. Please open a new github issue if someone can still reproduce this, thanks!
