### ISSUE TITLE
Error when installing sparklyr, error in curl: timeout was reached

### ISSUE THREAD

**Issue by cinkie** [rstudio/sparklyr#53]
When I tried to install sparklyr this message came out. It's still there even I tried 
`options(download.file.method = "wininet") ` or reset proxy

`Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Timeout was reached`

**Comment by javierluraschi** [comment]
@cinkie which version of http and curl you have? You can run: `packageVersion("curl")` and `packageVersion("httr")`

**Comment by javierluraschi** [comment]
@cinkie Could you please which command did you run with parameters included and the full original error without overriding `download.file.method`?

**Comment by cinkie** [comment]
> getOption("download.file.method")
[1] "wininet"
> packageVersion("curl")
[1] ‘0.9.7’
> packageVersion("httr")
[1] ‘1.2.0’

It could be the firewall of my work computer. I have no issue installing in my personal laptop.

**Comment by kevinushey** [comment]
Right; my best guess is that this is related to a firewall / other connectivity issues.

I assume that you are installing with `devtools::install_github()`? Note that `devtools` always uses the `curl` package for downloads; it does not respect the global `download.file` options.

**Comment by javierluraschi** [comment]
@cinkie here is another workaround:

1. Download the spark version from http://spark.apache.org/downloads.html
2. Extract into, for OSX: `/Users/<name>/Library/Caches/spark/spark-<ver>-bin-hadoop<ver>` for windows: `c:\Users\<name>\AppData\local\rstudio\spark\spark-<ver>-bin-hadoop<ver>`

This should be enough to have the manually-installed version in the IDE. You can verify this by running `spark_installed_versions()`.

Finally, would the following command work on the machine with this problem?

```
download.file("http://www.google.com", destfile = "google.html")
```

**Comment by javierluraschi** [comment]
@cinkie I'm closing this issue since it has been inactivate for a few days. However, if you find that the last set of instructions do not resolve this issue, please reactivate to suggest a different approach.

**Comment by cinkie** [comment]
@javierluraschi  I don't have `\Users\<name>\AppData\local\rstudio\` directory on my computer so I end up placing the spark folder to  `\Users\<name>\Program Files\Rstudio\`. And it still gets the same error message when trying `devtools::install_github("rstudio/sparklyr")`.

**Comment by javierluraschi** [comment]
@cinkie you could also try to manually download the following packages:

https://github.com/rstudio/sparkapi/archive/master.zip
https://github.com/rstudio/sparklyr/archive/master.zip

and build each manually from RStudio?

Alternatively, if this is not sufficient, I would rather open an issue in the `devtools` package (specially if other packages are also failing to install using `devtools`): https://github.com/hadley/devtools

**Comment by javierluraschi** [comment]
This one is not a `sparklyr` package issue... we can provide more pointers but best follow up would be thorugh `devtools` packge.

**Comment by cinkie** [comment]
This issue is resolved through installing manually. Thanks Javier.
