### ISSUE TITLE
Error: Variables must be length 1 or 180.

### ISSUE THREAD

**Issue by ruizhuhuang** [rstudio/sparklyr#531]
I use spark_read_parquet to load parquet files and get the following error. I am wondering this issue may be similar to issue #477 (https://github.com/rstudio/sparklyr/issues/477)

Source:   query [56 x 22]
Database: spark connection master=local[8] app=sparklyr local=TRUE

Error: Variables must be length 1 or 180.
Problem variables: 'cput', 'end_date', 'end_ts', 'exit_status', 'groupname', 'hostlist', 'hostlist_array', 'jobid', 'mem_kb', 'module_array', 'nodes', 'nproc', 'queue', 'software', 'start_date', 'start_ts', 'submit_date', 'submit_ts', 'sw_app', 'vmem_kb', 'walltime'

> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.1

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sparklyr_0.5.3-9002

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9     withr_1.0.2     digest_0.6.12   dplyr_0.5.0    
 [5] rprojroot_1.2   assertthat_0.1  rappdirs_0.3.1  mime_0.5       
 [9] R6_2.2.0        jsonlite_1.3    xtable_1.8-2    DBI_0.5-1      
[13] backports_1.0.5 magrittr_1.5    httr_1.2.1      rstudioapi_0.6 
[17] config_0.2      tools_3.3.2     shiny_1.0.0     parallel_3.3.2 
[21] yaml_2.1.14     httpuv_1.3.3    base64enc_0.1-3 htmltools_0.3.5
[25] tibble_1.2

**Comment by behrica** [comment]
I have the same problem.
Reading a certian parquet file from local disk,  get:

```
Source:   query [1.049e+04 x 47]
Database: spark connection master=local[4] app=sparklyr local=TRUE

Error: Variables must be length 1 or 364.
Problem variables: 'ACI_ADDITIONAL_INFO', 'ADDRESS_ID', 'BUSINESS_PHONE', 'DATA_SHARING', 'DATE_LAST_EMAIL_REMINDER', 'DATE_LAST_MODIFIED', 'DATE_REGISTERED', 'DATE_SUBMITTED', 'DOI_ID', 'EDUCATIONS', 'EFSA_INTERNAL', 'EMAIL', 'EMAIL2', 'EXCLUDED', 'EXPERT_ID', 'FAX', 'GENDER_ID', 'INCLUDED', 'INVITED', 'MOBILE_PHONE', 'NAME', 'NATIONALITY_ID', 'NEWEMAIL', 'NEWPASSWORD', 'NOT_VALID', 'ORG_ADDRESS_ID', 'ORG_EMAIL', 'ORG_NAME', 'ORG_PHONE', 'ORG_TYPE_ID', 'ORG_URL', 'OTHER_COMPETENCIES', 'PASSWORD', 'PROFESSIONAL_EXPERIENCES', 'PROFESSIONAL_SITUATION_ID', 'REMINDER_STATUS', 'SALT', 'SAMACCOUNTNAME', 'SOURCE', 'STATUS', 'SURNAME', 'TITLE_ID', 'TYPE', 'UPDATE_REQUESTED', 'VERSION', 'YEARS_OF_EXP_RA'
```

To read the same file with SparkR::read.parquet(..) works fine.

I converted the fle to json, and get the same problem.

**Comment by behrica** [comment]
I debugged this a bit, and it seems to happen if there are charatcer columns with new line characters in them. So maybe it relates to #411 

But then it would fail, every time as there is a character column with newlines in.

**Comment by renegademonkey** [comment]
Hi there,

I am having the same issue, reading files from a cassandra database. Does anyone know of a fix or workaround for this?

**Comment by dkincaid** [comment]
Show stopper for us. Makes sparklyr unusable for my current work since I have a field I need to work with the definitely has newline characters in it. Hoping you guys can figure out the problem and get it fixed soon. Meanwhile, does anyone have a workaround?

**Comment by javierluraschi** [comment]
@dkincaid @renegademonkey @behrica @ruizhuhuang I believe this should have been resolved by https://github.com/rstudio/sparklyr/commit/27693990b7a097e3aceb383bfc3a613c409ec7c5 which fixed a pair of issues tracking newline terminators.

If that's not the case, please let me know, this is obviously a blocker that needs to be addressed. You can chat with us about this issue in https://gitter.im/rstudio/sparklyr.

**Comment by behrica** [comment]
Works now for me
