### ISSUE TITLE
Return list of character vectors from ft_tokenizer(), ft_regex_tokenizer()

### ISSUE THREAD

**Issue by richierocks** [rstudio/sparklyr#536]
At the moment, `ft_tokenizer()` returns a list of lists of character vectors.

```r
library(dplyr)
library(sparklyr)

sc <- spark_connect("local")

text_data <- data_frame(
  x = c("This is a sentence", "So is this")
)
text_data_tbl <- copy_to(sc, text_data)

tokenized <- text_data_tbl %>%
  ft_tokenizer("x", "word") %>%
  collect()
tokenized$word
## [[1]]
## [[1]][[1]]
## [1] "this"
## 
## [[1]][[2]]
## [1] "is"
## etc.
```
It would be simpler to work with a list of character vectors.

In particular, in order to do sentiment analysis on Spark using `tidytext`, the data should be in the form of one word per row. So I want to call `ft_tokenizer()` followed by `unnest()`.

This requires the simpler return value from `ft_tokenizer()`, and implementations of `tidyr` methods for `tbl_spark`s, as discussed in https://github.com/rstudio/sparklyr/issues/252.

`ft_regex_tokenizer()` has the same form for the return values.

**Comment by kevinushey** [comment]
I agree a list of character vectors would be nicer here.

**Comment by kevinykuo** [comment]
We probably don't want to change the serialization but I think you can get to what you want via

```
text_data_tbl %>%
  ft_tokenizer("x", "word") %>%
  mutate(word = explode(word)) %>%
  collect()

# A tibble: 7 x 2
x     word
<chr>    <chr>
1 This is a sentence     this
2 This is a sentence       is
3 This is a sentence        a
4 This is a sentence sentence
5         So is this       so
6         So is this       is
7         So is this     this
```

For text mining at scale we probably want to wrap https://databricks.com/blog/2017/10/19/introducing-natural-language-processing-library-apache-spark.html instead of collecting the data to R.
