### ISSUE TITLE
Simplify return value from sdf_schema()

### ISSUE THREAD

**Issue by richierocks** [rstudio/sparklyr#537]
At the moment, `sdf_schema()` returns a list of lists. It would be easier to work with if the return value was a tibble with two columns: `name` and `type`.

For example, this is verbose, hard to read, and hard to program with.

```r
library(dplyr)
library(sparklyr)

sc <- spark_connect("local")
iris_tbl <- copy_to(sc, iris)

sdf_schema(iris_tbl)
## $Sepal_Length
## $Sepal_Length$name
## [1] "Sepal_Length"
## 
## $Sepal_Length$type
## [1] "DoubleType"
## 
## 
## $Sepal_Width
## $Sepal_Width$name
## [1] "Sepal_Width"
## 
## $Sepal_Width$type
## [1] "DoubleType"
## 
## 
## $Petal_Length
## $Petal_Length$name
## [1] "Petal_Length"
## 
## $Petal_Length$type
## [1] "DoubleType"
## 
## 
## $Petal_Width
## $Petal_Width$name
## [1] "Petal_Width"
## 
## $Petal_Width$type
## [1] "DoubleType"
## 
## 
## $Species
## $Species$name
## [1] "Species"
## 
## $Species$type
## [1] "StringType"
```

This is much nicer, but it is a pain having to do this transformation myself.

```r
sdf_schema(iris_tbl) %>% 
  lapply(function(x) do.call(data_frame, x)) %>% 
  bind_rows()
## # A tibble: 5 × 2
##           name       type
##          <chr>      <chr>
## 1 Sepal_Length DoubleType
## 2  Sepal_Width DoubleType
## 3 Petal_Length DoubleType
## 4  Petal_Width DoubleType
## 5      Species StringType
```

**Comment by kevinushey** [comment]
I don't think we can change the return value of an already exported function (it would potentially break already-existing code). I would suggest just using your own wrapper that transforms it as needed.

**Comment by richierocks** [comment]
@kevinushey Would a new function `src_schema()` that returns this be acceptable?  (I'm thinking of `dplyr::src_tbls()` as a parallel.) Though I guess this should have a generic in `dplyr` and method here.

**Comment by kevinushey** [comment]
That sounds reasonable to me; I think it's worth filing in `dplyr` to see if Hadley thinks it's worth implementing.

**Comment by kevinykuo** [comment]
Closing to track at https://github.com/r-dbi/DBI/issues/75
