### ISSUE TITLE
Issues installing SparklyR since this morning ("Lazy loading failed")

### ISSUE THREAD

**Issue by HugoHehn** [rstudio/sparklyr#538]
Having some issues installing SparklyR on a Linux server using the same code that has been working smoothly up until yesterday. Have tried it with various combinations of DBI, jsonlite and dplyr installed/ uninstalled.

Everything seems to be running great up until this point:

`* installing *source* package ‘sparklyr’ ...`
`** package ‘sparklyr’ successfully unpacked and MD5 sums checked`
`** R`
`** inst`
`** preparing package for lazy loading`
`Note: the specification for S3 class “AsIs” in package ‘jsonlite’ seems equivalent to one from package ‘DBI’: not turning on duplicate class definitions for this class.`
`Error in conformMethod(signature, mnames, fnames, f, fdef, definition) : `
`  in method for ‘sqlParseVariables’ with signature ‘conn="spark_connection"’: formal arguments (conn = "spark_connection", sql = "spark_connection", ... = "spark_connection") omitted in the method definition cannot be in the signature`
`Error : unable to load R code in package ‘sparklyr’`
`ERROR: lazy loading failed for package ‘sparklyr’`

Not sure if this has something to do with the March 8 commit (24643429a8ba5196ff8ded9723f6e51c28ac9d4e), but loading the earlier version does not seem to help either. Any ideas?

**Comment by learndm** [comment]
Unfortunately the I meet the same issue:

![image](https://cloud.githubusercontent.com/assets/10106978/23753695/b96c50c6-04da-11e7-8704-233f59c3a194.png)

What could be needed ?

**Comment by learndm** [comment]
Hi there, some problem:

![image](https://cloud.githubusercontent.com/assets/10106978/23753812/1792a3a8-04db-11e7-9ffd-52da0d7005cf.png)

Any suggestions ? thanks

**Comment by Javi6perez** [comment]
Got the same problem working

**Comment by javierluraschi** [comment]
@learndm @Javi6perez thanks for reporting this, a patch to `sparklyr` with version `0.5.3` was submitted and accepted to CRAN today, it might take a day to fully replicate in CRAN but for most users, a retry should fix this issue. This was caused by a breaking change in `DBI 0.6`.

**Comment by HugoHehn** [comment]
@javierluraschi Thank you so much for the quick response - will try it out tomorrow.

**Comment by javierros** [comment]
Hi, why the sparklyr-2.1-2.11.jar is only in the master branch and not in CRAN or the tagged versions? Now if you try to use the master branch with devtools::install_github("rstudio/sparklyr") it fails with the DBI problem.

**Comment by javierluraschi** [comment]
@javierros merging... https://github.com/rstudio/sparklyr/pull/543, `devtools::install_github("rstudio/sparklyr")` should work now as appropiate as well.

`sparklyr-2.1-2.11.jar` is not included in the CRAN version since support for Spark 2.1.0 will be supported until the next major release of `sparklyr`, planning to do this for around April or May.
