### ISSUE TITLE
Problems building : Error in conformMethod .. cannot be in sig

### ISSUE THREAD

**Issue by Nova-Boy** [rstudio/sparklyr#539]
Running into the following when issuing either 

> devtools::install_github('rstudio/sparklyr')
or
> install.packages("sparklyr")
```

** inst
** tests
** preparing package for lazy loading
Error in conformMethod(signature, mnames, fnames, f, fdef, definition) : 
  in method for ‘sqlParseVariables’ with signature ‘conn="spark_connection"’: formal arguments (conn = "spark_connection", sql = "spark_connection", ... = "spark_connection") omitted in the method definition cannot be in the signature
Error : unable to load R code in package ‘sparklyr’
ERROR: lazy loading failed for package ‘sparklyr’
* removing ‘/home/mtz/R/x86_64-redhat-linux-gnu-library/3.3/sparklyr’
Error: Command failed (1)
```

This is on RHEL 7.3 running R version 3.3.2 

I did notice this:  https://github.com/rstudio/sparklyr/issues/513  and installed DBI in CRAN as a result.  No change.

Thanks!

**Comment by HugoHehn** [comment]
Seems to be the same basic problem as I posted this morning (clarified the title just now as it might not have been evident):

https://github.com/rstudio/sparklyr/issues/538

**Comment by javierluraschi** [comment]
@Nova-Boy @HugoHehn Tahnk you, patch to `sparklyr` as `0.5.3` was submitted and accepted to CRAN this morning, it might take up to a day to replicate in CRAN, but for most users, reinstalling should work as expected now. There was a breaking change in `DBI 0.6` that required a patch in `sparklyr`, all should be good now.

**Comment by Nova-Boy** [comment]
Thanks! Confirming that it looks good.  I'm able to install 0.5.3 w/o issue.

**Comment by javierluraschi** [comment]
Thanks for confirming!
