### ISSUE TITLE
Some issues related to copy_to() and flights data in a cluster environment

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/sparklyr#54]
I don't really know how the cluster interactions are different than when we run locally. But I have had some observations and will mention them here for the record, and the possibility that there might be an issue.

I have tried this on 2 different cluster setups:

1) AWS: 
one master and 1 worker node
instances are m3.medium, 3.75G RAM

- start with a fresh R session (RSP running on the master node)
- Run spark_connect()
- Run copy_to with `flights` data
- It takes 17-18 minutes, but it is successful.
- Listed below are how memory usage of the processes goes up

Right after spark_connect:

```
rstudio   1585  3.6  1.6 671316 65232 ?        Sl   20:31   0:05 /usr/lib/rstudio-server/bin/rsession -u rstudio
rstudio   1630 80.7 10.1 2166624 393476 ?      Sl   20:32   0:34 /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.101.x86_64/jre/bin/java -cp /home/rstudio/.cache/spark/spark-1.6.1-bin-hadoop1/conf/:/home/rstudio/.cache/spark/spark-1.6.1-bin-hadoop1/lib/spark-assembly-1.6.1-hadoop1.2.1.jar:/home/rstudio/.cache/spark/spark-1.6.1-bin-hadoop1/lib/datanucleus-core-3.2.10.jar:/home/rstudio/.cache/spark/spark-1.6.1-bin-hadoop1/lib/datanucleus-api-jdo-3.2.6.jar:/home/rstudio/.cache/spark/spark-1.6.1-bin-hadoop1/lib/datanucleus-rdbms-3.2.9.jar -Xms1g -Xmx1g -XX:MaxPermSize=256m org.apache.spark.deploy.SparkSubmit --packages com.databricks:spark-csv_2.11:1.3.0,com.amazonaws:aws-java-sdk-pom:1.10.34 --jars /home/rstudio/R/x86_64-redhat-linux-gnu-library/3.2/sparklyr/java/rspark_utils.jar sparkr-shell /tmp/RtmptdhPah/file6317574d10d.out
```

After copy_to is finished:

```
rstudio   1585 68.0 32.1 1858736 1241176 ?     Sl   20:31  14:51 /usr/lib/rstudio-server/bin/rsession -u rstudio
rstudio   1630 13.4 35.8 2328756 1384792 ?     Sl   20:32   2:41 /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.101.x86_64/jre/bin/java -cp /home/rstudio/.cache/spark/spark-1.6.1-bin-hadoop1/conf/:/home/rstudio/.cache/spark/spark-1.6.1-bin-hadoop1/lib/spark-assembly-1.6.1-hadoop1.2.1.jar:/home/rstudio/.cache/spark/spark-1.6.1-bin-hadoop1/lib/datanucleus-core-3.2.10.jar:/home/rstudio/.cache/spark/spark-1.6.1-bin-hadoop1/lib/datanucleus-api-jdo-3.2.6.jar:/home/rstudio/.cache/spark/spark-1.6.1-bin-hadoop1/lib/datanucleus-rdbms-3.2.9.jar -Xms1g -Xmx1g -XX:MaxPermSize=256m org.apache.spark.deploy.SparkSubmit --packages com.databricks:spark-csv_2.11:1.3.0,com.amazonaws:aws-java-sdk-pom:1.10.34 --jars /home/rstudio/R/x86_64-redhat-linux-gnu-library/3.2/sparklyr/java/rspark_utils.jar sparkr-shell /tmp/RtmptdhPah/file6317574d10d.out
```

After spark_disconnect():

```
rstudio   1585 63.7 32.1 1860796 1241272 ?     Sl   20:31  14:53 /usr/lib/rstudio-server/bin/rsession -u rstudio
```

2) Google Could Platform Hadoop/Spark Cluster
one master and 2 worker nodes
instances are: n1-standard-2, 7.5G RAM

- start with a fresh R session (RSP running on the master node)
- Run spark_connect()
- Run copy_to with `flights` data
- after about 10-11 minutes it fails with this error:

```
Error: failed to invoke spark command
16/06/29 20:07:17 ERROR org.apache.spark.api.r.RBackendHandler: createDataFrame on utils failed
```

There is no more error in the log when I run spark_log()

- Listed below are how memory usage of the processes goes up

Right after spark_connect():

```
test1     1363 47.6 13.4 4684108 1035408 ?     Sl   19:55   0:47 /usr/lib/jvm/java-8-openjdk-amd64/bin/java -cp /usr/lib/spark/conf/:/usr/lib/spark/lib/spark-assembly-1.6.1-hadoop2.7.2.jar:/usr/lib/spark/lib/datanucleus-core-3.2.10.jar:/usr/lib/spark/lib/datanucleus-api-jdo-3.2.6.jar:/usr/lib/spark/lib/datanucleus-rdbms-3.2.9.jar:/etc/hadoop/conf/:/etc/hadoop/conf/:/usr/lib/hadoop/lib/native/:/usr/lib/hadoop/lib/*:/usr/lib/hadoop/*:/usr/lib/hadoop/../hadoop-hdfs/lib/*:/usr/lib/hadoop/../hadoop-hdfs/*:/usr/lib/hadoop/../hadoop-mapreduce/lib/*:/usr/lib/hadoop/../hadoop-mapreduce/*:/usr/lib/hadoop/../hadoop-yarn/lib/*:/usr/lib/hadoop/../hadoop-yarn/*:/etc/hive/conf/:/usr/share/java/mysql.jar:/etc/hive/conf/ -Dscala.usejavacp=true -Xms1920m -Xmx1920m -Xbootclasspath/p:/usr/local/share/google/alpn/alpn-boot-8.1.7.v20160121.jar org.apache.spark.deploy.SparkSubmit --packages com.databricks:spark-csv_2.11:1.3.0,com.amazonaws:aws-java-sdk-pom:1.10.34 --jars /home/test1/R/x86_64-pc-linux-gnu-library/3.3/sparklyr/java/rspark_utils.jar sparkr-shell /tmp/RtmpPxIdco/file78b04f19b71e.out
test1    30896  0.2  1.1 625332 88612 ?        Sl   18:35   0:10 /usr/lib/rstudio-server/bin/rsession --server-shared-storage-path 
```

After copy_to returns with error:

```
test1     1363  6.9 13.4 4687184 1030060 ?     Sl   19:55   0:59 /usr/lib/jvm/java-8-openjdk-amd64/bin/java -cp /usr/lib/spark/conf/:/usr/lib/spark/lib/spark-assembly-1.6.1-hadoop2.7.2.jar:/usr/lib/spark/lib/datanucleus-core-3.2.10.jar:/usr/lib/spark/lib/datanucleus-api-jdo-3.2.6.jar:/usr/lib/spark/lib/datanucleus-rdbms-3.2.9.jar:/etc/hadoop/conf/:/etc/hadoop/conf/:/usr/lib/hadoop/lib/native/:/usr/lib/hadoop/lib/*:/usr/lib/hadoop/*:/usr/lib/hadoop/../hadoop-hdfs/lib/*:/usr/lib/hadoop/../hadoop-hdfs/*:/usr/lib/hadoop/../hadoop-mapreduce/lib/*:/usr/lib/hadoop/../hadoop-mapreduce/*:/usr/lib/hadoop/../hadoop-yarn/lib/*:/usr/lib/hadoop/../hadoop-yarn/*:/etc/hive/conf/:/usr/share/java/mysql.jar:/etc/hive/conf/ -Dscala.usejavacp=true -Xms1920m -Xmx1920m -Xbootclasspath/p:/usr/local/share/google/alpn/alpn-boot-8.1.7.v20160121.jar org.apache.spark.deploy.SparkSubmit --packages com.databricks:spark-csv_2.11:1.3.0,com.amazonaws:aws-java-sdk-pom:1.10.34 --jars /home/test1/R/x86_64-pc-linux-gnu-library/3.3/sparklyr/java/rspark_utils.jar sparkr-shell /tmp/RtmpPxIdco/file78b04f19b71e.out
test1    30896 11.0 15.8 1759920 1213960 ?     Sl   18:35  10:24 /usr/lib/rstudio-server/bin/rsession --server-shared-storage-path /var/lib/rstudio-server/shared-storage -p 0da29cfc78a31 -s f1043a18 -u test1
```

After spark_disconnect():

```
test1    30896 10.5 15.8 1759920 1213960 ?     Sl   18:35  10:24 /usr/lib/rstudio-server/bin/rsession --server-shared-storage-path /var/lib/rstudio-server/shared-storage -p 0da29cfc78a31 -s f1043a18 -u test1
```

Concerns:
a- Failure in Google cluster. May be something is wrong with setup, but we can load iris data just fine. More likely to be a memory issue
b- Time it takes for this operation to complete or fail
c- rsession process memory usage, and the fact that it does not go down after disconnect

**Comment by kevinushey** [comment]
This error:

```
Error: failed to invoke spark command
16/06/29 20:07:17 ERROR org.apache.spark.api.r.RBackendHandler: createDataFrame on utils failed
```

I believe this implies that perhaps our utility JAR (`rspark_utils.jar`) was not loaded, and so Spark failed to resolve the `createDataFrame` method.

**Comment by nicornk** [comment]
I am getting the same error on my cluster setup. I checked the logs and the rspark_utils.jar are loaded.
`16/07/05 15:28:57 INFO SparkContext: Added JAR file:/Users/********/Library/R/3.3/library/sparklyr/java/rspark_utils.jar at http://141.52.195.202:59724/jars/rspark_utils.jar with timestamp 1467725337625
`
Any idea how we can debug this further?

**Comment by kevinushey** [comment]
Any chance we can get a minimally reproducible example? It may also depend on the version of Spark used.

**Comment by fereshtehRS** [comment]
I have been using Spark 1.6 in the cluster environment.

As for minimally reproducible, hard to say. Flights data works fine in my local environment, and relatively fast. In a cluster environment, smaller datasets such as iris work fine. What do you suggest to try?

May be we can address the error in Google cluster. You had mentioned `I believe this implies that perhaps our utility JAR (rspark_utils.jar) was not loaded, and so Spark failed to resolve the createDataFrame method.`  What would cause this JAR not to be loaded?

**Comment by kevinushey** [comment]
I can't think of anything that would cause the jar not to be loaded -- it seems like we'd probably see an error occurring earlier as well if that were the case.

The other possibility is that we're attempting to call `createDataFrame` with the wrong arguments -- perhaps some assumptions we're making here are wrong?

https://github.com/rstudio/sparklyr/blob/master/R/data_copy.R#L59-L68

**Comment by javierluraschi** [comment]
@fereshtehRS replaced cluster serialization with something better. Tried int, double and chars. We should test other data types like booleans, etc. Except for dates/times which I believe another github issue is tracking this already.

**Comment by fereshtehRS** [comment]
Thanks @javierluraschi 
Great improvement. I now see the following:

1) On AWS:

```
system.time(flights_tbl <- copy_to(sc, flights, "flights", overwrite = TRUE))
   user  system elapsed 
 49.407   0.456 123.710 
```

2) On Google Dataproc:

```
system.time(flights_tbl <- copy_to(sc, flights, "flights", overwrite = TRUE))
   user  system elapsed 
 24.620   0.332  62.354 
```

**Comment by javierluraschi** [comment]
@fereshtehRS yes, this is much better! Thanks for getting these numbers!

BTW. @kevinushey might improve this further, we will let you know when this happens to make sure we don't regress.
