### ISSUE TITLE
Support dplyr select helpers for ml_* and ft_* functions

### ISSUE THREAD

**Issue by richierocks** [rstudio/sparklyr#540]
It would be useful to support `dplyr`s select helper functions to select columns for the `features` argument to `ml_*` functions, and for the `input.col` argument to `ft_*` functions.

I want to write something like this:

```r
library(dplyr)
library(sparklyr)
sc <- spark_connect("local")
iris_tbl <- copy_to(sc, iris)
iris_tbl %>% 
  ml_linear_regression("Species", starts_with("Petal"))
```

The current workaround is to use something like this, which is not as nice.

```r
library(stringr)
iris_tbl %>% 
  ml_linear_regression("Species", str_subset(colnames(.), "^Petal"))
```

**Comment by javierluraschi** [comment]
Noted, thank you, Richie!

**Comment by kevinykuo** [comment]
Closing to track in https://github.com/rstudio/sparklyr/issues/1267
