### ISSUE TITLE
Rstudio - Cannot read from s3n using spark_read_csv or spark_read_parquet when connected to remote spark

### ISSUE THREAD

**Issue by charles2588** [rstudio/sparklyr#549]
Cannot read from s3n using spark_read_csv or spark_read_parquet when connected to remote spark
##specify keys as environment variables
Sys.setenv("AWS_ACCESS_KEY_ID" = "XXXXXXX",
           "AWS_SECRET_ACCESS_KEY" = "XXXXXX")

library(sparklyr)
library(dplyr)

#connect to spark
sc <- spark_connect(config = "Apache Spark-ic")

Spark is connected and i can read from local filesytem of remote spark's driver.
But when it comes to s3n, i get weird error
usercsv_tbl <- spark_read_csv(sc,name = "usercsvtlb",path = "s3n://charlesbuckets31/FolderA/users.csv")

Error in as.hexmode(x) : 'x' cannot be coerced to class "hexmode"
In addition: Warning message:
In mapply(function(x, y) { :
  longer argument not a multiple of length of shorter

**Comment by javierluraschi** [comment]
@charles2588 does this help? http://spark.rstudio.com/example-s3.html

`ACCESSKEY` and `SECRETKEY` in correct format?

**Comment by ElianoMarques** [comment]
@javierluraschi perhaps you want to add the above example to standard examples in the website? (just checked its not)

**Comment by edgararuiz** [comment]
Hi, thank you for your suggestion, we have it listed under Deployment / Deployment Examples: http://spark.rstudio.com/deployment_examples.html.

**Comment by ElianoMarques** [comment]
ahhhh! thanks for letting me know.

**Comment by javierluraschi** [comment]
Looks resolved, I'm glad, closing.

**Comment by dvasilen** [comment]
Both links are dead. What was the work around for this issue?

<img width="913" alt="image" src="https://user-images.githubusercontent.com/3604906/39248019-9edc0542-4860-11e8-88ae-6e1b385681f5.png">

<img width="897" alt="image" src="https://user-images.githubusercontent.com/3604906/39248055-b5f7af9c-4860-11e8-8196-98f02cc14588.png">

**Comment by edgararuiz** [comment]
Hi, please try this link: http://spark.rstudio.com/examples/

I'll make sure to have the old link forward to this page going forward, in the meanwhile, please feel free to use the one above.

Thanks
