### ISSUE TITLE
persistent spark path

### ISSUE THREAD

**Issue by TaylorAndrew** [rstudio/sparklyr#55]
Not sure if this is an Rstudio preview or sparklyr issue or something that is/should be done in the base R. 

I have spark located at say: C:/Spark1_6/

I can specify:

    Sys.setenv(SPARK_HOME = 'C:/Spark1_6/')
    library(sparklyr)
    spark_connect(master = 'local')

To connect to spark in that location.

But if I restart I cannot connect. It would be nice if rstudio could save this environment so I can connect via the GUI or `spark_connect()` without having to invoke the Sys.setenv() every time.

If this is possible somewhere in RStudio/sparklyr, and I'm not seeing it, I apologize. If this is a base R thing that I should clearly know already, I apologize even more.

**Comment by javierluraschi** [comment]
You can set this persistently as a global Windows environment variable using this form R:

```system2("SETX", c("HADOOP_HOME", "<path>"))```

Or using the Windows UI. Please close issue once you verify this works for you.

**Comment by TaylorAndrew** [comment]
It actually not working. When I use

    system2("SETX", c("HADOOP_HOME", "<path>"))

It is not changing the path, as investigated with `Sys.getenv()` whereas when I use `Sys.setenv()` it does change when I look at `Sys.getenv()`, though only temporarily.

It seems like this is not a sparklyr issue though, so I will still be closing it.

**Comment by javierluraschi** [comment]
@TaylorAndrew with SETX you would need an rsession restart, but agree, setting this global environment variable is not and issue in sparklyr, thanks for closing.

**Comment by jjallaire** [comment]
I would set the environment variable within .Rprofile or .Renviron
