### ISSUE TITLE
Persistently getting `Gateway in port (8880) did not respond`.                  

### ISSUE THREAD

**Issue by navdeep-G** [rstudio/sparklyr#550]
Hi,

I am seeing the following error come up quite frequently in my workspace: 

`Failed while connecting to sparklyr to port (8880) for sessionid (*Some ID): Gateway in port (8880) did not respond`.

I have seen this come up for others as well. Is there a solution?

Thanks

**Comment by navdeep-G** [comment]
Full error log: 

> library(sparklyr)
> library(rsparkling)
> spark_installed_versions()
  spark hadoop                       dir
1 1.6.0    2.6 spark-1.6.0-bin-hadoop2.6
2 1.6.2    2.6 spark-1.6.2-bin-hadoop2.6
3 2.0.0    2.7 spark-2.0.0-bin-hadoop2.7
4 2.0.1    2.7 spark-2.0.1-bin-hadoop2.7
5 2.0.2    2.7 spark-2.0.2-bin-hadoop2.7
6 2.1.0    2.7 spark-2.1.0-bin-hadoop2.7
> options(rsparkling.sparklingwater.version = Sys.getenv("SPARKLINGWATER_VERSION","2.0.5"))
> sc <- spark_connect(master = "local", version = "2.0.2")
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (271): Gateway in port (8880) did not respond.
    Path: /Users/navdeepgill/Library/Caches/spark/spark-2.0.2-bin-hadoop2.7/bin/spark-submit
    Parameters: --class, sparklyr.Backend, --packages, 'ai.h2o:sparkling-water-core_2.11:2.0.5','ai.h2o:sparkling-water-ml_2.11:2.0.5','ai.h2o:sparkling-water-repl_2.11:2.0.5', '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/sparklyr/java/sparklyr-2.0-2.11.jar', 8880, 271


---- Output Log ----
	org.apache.commons#commons-math3;3.3 from central in [default]
	org.apache.directory.studio#org.apache.commons.lang;2.6 from central in [default]
	org.apache.httpcomponents#httpclient;4.3.6 from central in [default]
	org.apache.httpcomponents#httpcore;4.3.3 from central in [default]
	org.codehaus.jackson#jackson-core-asl;1.9.13 from central in [default]
	org.codehaus.jackson#jackson-mapper-asl;1.9.13 from central in [default]
	org.eclipse.jetty#jetty-continuation;8.1.17.v20150415 from central in [default]
	org.eclipse.jetty#jetty-http;8.1.17.v20150415 from central in [default]
	org.eclipse.jetty#jetty-io;8.1.17.v20150415 from central in [default]
	org.eclipse.jetty#jetty-jndi;8.1.17.v20150415 from central in [default]
	org.eclipse.jetty#jetty-plus;8.1.17.v20150415 from central in [default]
	org.eclipse.jetty#jetty-security;8.1.17.v20150415 from central in [default]
	org.eclipse.jetty#jetty-server;8.1.17.v20150415 from central in [default]
	org.eclipse.jetty#jetty-servlet;8.1.17.v20150415 from central in [default]
	org.eclipse.jetty#jetty-util;8.1.17.v20150415 from central in [default]
	org.eclipse.jetty#jetty-webapp;8.1.17.v20150415 from central in [default]
	org.eclipse.jetty#jetty-xml;8.1.17.v20150415 from central in [default]
	org.eclipse.jetty.aggregate#jetty-servlet;8.1.17.v20150415 from central in [default]
	org.eclipse.jetty.orbit#javax.activation;1.1.0.v201105071233 from central in [default]
	org.eclipse.jetty.orbit#javax.mail.glassfish;1.4.1.v201005082020 from central in [default]
	org.eclipse.jetty.orbit#javax.servlet;3.0.0.v201112011016 from central in [default]
	org.eclipse.jetty.orbit#javax.transaction;1.1.1.v201105210645 from central in [default]
	org.javassist#javassist;3.18.2-GA from central in [default]
	org.joda#joda-convert;1.7 from central in [default]
	org.slf4j#slf4j-api;1.7.7 from central in [default]
	org.tukaani#xz;1.5 from central in [default]
	org.xerial.snappy#snappy-java;1.1.1.3 from central in [default]
	:: evicted modules:
	com.google.guava#guava;19.0 by [com.google.guava#guava;16.0.1] in [default]
	joda-time#joda-time;2.3 by [joda-time#joda-time;2.8.1] in [default]
	org.apache.httpcomponents#httpclient;4.1 by [org.apache.httpcomponents#httpclient;4.3.6] in [default]
	org.apache.httpcomponents#httpcore;4.1 by [org.apache.httpcomponents#httpcore;4.3.3] in [default]
	commons-logging#commons-logging;1.1.1 by [commons-logging#commons-logging;1.1.3] in [default]
	commons-codec#commons-codec;1.4 by [commons-codec#commons-codec;1.6] in [default]
	com.google.guava#guava;18.0 by [com.google.guava#guava;16.0.1] in [default]
	commons-codec#commons-codec;1.3 by [commons-codec#commons-codec;1.4] in [default]
	commons-logging#commons-logging;1.0.4 by [commons-logging#commons-logging;1.1.1] in [default]
	commons-codec#commons-codec;1.2 by [commons-codec#commons-codec;1.4] in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   72  |   0   |   0   |   10  ||   62  |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent
	confs: [default]
	0 artifacts copied, 62 already retrieved (0kB/30ms)
17/03/13 13:26:41 INFO sparklyr: Session (271) starting
17/03/13 13:26:41 INFO sparklyr: Registering session (271) into gateway port (8880)
(17/03/13 13:27:07 ERROR sparklyr: Server shutting down: failed with exception ,java.net.ConnectException: Operation timed out)

---- Error Log ----

**Comment by javierluraschi** [comment]
I have not seen this, you still hitting this?

**Comment by javierluraschi** [comment]
Ah, yes, this is well known now:

```
Server shutting down: failed with exception ,java.net.ConnectException: Operation timed out.
```

`sparklyr` waits for `60s` to initialize and fails otherwise, the workaround is to change the timeout in the `config` as:

```r
config <- spark_config()

# wait for 5 minutes for dependencies to download
config$sparklyr.gateway.start.timeout <- 60 * 5

sc <- spark_connect(master = "local", config = config)
```

**Comment by javierluraschi** [comment]
Tried a few times with this workflow, no repro so far. @navdeep-G could you open a new issue if you can still hit this one with latest `sparklyr`?

If you can, I would open `http://127.0.0.1:4040/` (most likely the UI from the running gateway instance) and see if you spot any particular error.

Grabbing the logs could also help here, closing for now since this one is not very actionable without more info.

Thanks!
