### ISSUE TITLE
sparklyr java extension - spark DataFrame created, but not accessible in R

### ISSUE THREAD

**Issue by renegademonkey** [rstudio/sparklyr#551]
Hi there,

I've just written my first sparklyr extension - it's a small java program that fetches a particular Cassandra database, selects a subset of columns, and returns a spark DataFrame which could then be further manipulated in R. 

It SEEMS to be working as intended, however the created DataFrame cannot be registered in R. I can see it exists on the spark server via the Spark gui, it is visible in the RStudio 'Spark' tab, I can preview it in R by clicking on it, and it is visible when running `src_tbls(sc)`. 

However, it is not registered in R, and when I try to register it (using either `sdf_register` or `spark_partition_register_df`), I keep getting `object not found` errors. 

Any ideas why this might be? Is there another way to get a spark DataFrame to register?

Some  sessionInfo is as follows:

```
> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.5.0         sparklyr_0.5.3-9002 fileparserr_0.0.0  
```

**Comment by AkhilNairAmey** [comment]
Hard to know what might be the issue without any code.  I've been trying a similar thing and this seems to work for me:

```
library(pipeR)
# With spark_session in scope
spark_load_cassandra_table = function(keyspace, table, spark_table_name, partition_filter = FALSE, select_cols = FALSE, cache_table = FALSE) {
  cass_df =
    sparklyr::invoke(spark_session, "read") %>>%
    sparklyr::invoke("format", "org.apache.spark.sql.cassandra") %>>%
    sparklyr::invoke("option", "keyspace", keyspace) %>>%
    sparklyr::invoke("option", "table", table) %>>%
    sparklyr::invoke("load")

  if(is.character(partition_filter)) {
    # partition_filter must contain all partition keys and only a single equality for each for the connector to pushdown correctly
    cass_df = cass_df %>>% sparklyr::invoke("where", partition_filter)
  }

  if(is.character(select_cols)) {
    if(length(select_cols) == 1) {
      cass_df = cass_df %>>% sparklyr::invoke("select", select_cols, list())
    } else if(length(select_cols) > 1) {
      cass_df = cass_df %>>% sparklyr::invoke("select", select_cols[[1]], as.list(select_cols[2:length(select_cols)]))
    }
  }

  spark_tbl = sparklyr:::spark_partition_register_df(sc, cass_df, spark_table_name, 0, cache_table)
  spark_tbl
}
```

**Comment by javierluraschi** [comment]
@renegademonkey maybe we need to return it back from the new Cassandra function? We don't keep track of dataframes in R/sparklyr, expect as variables, so I would expect that if you write a `spark_read_cassandra` function, I would be able to do this:

```
iris_csd <- spark_read_cassandra()
```

Then one should be able to use `iris_csd` in `dplyr` or with `ml_` functions. Does this make sense? basically, `sprklyr` does not track objects globally but rather only variable references. You probably want to return the result from `sdf_register` which users of your extension can store the pointer to that table.

If you share the code, I can give more specific feedback, hard to guess without looking at this.

**Comment by javierluraschi** [comment]
@renegademonkey See for instance: https://github.com/rstudio/sparklyr/blob/master/R/data_interface.R#L452-L463

**Comment by renegademonkey** [comment]
Hi there. Thanks for the fast responses! 

@AkhilNairAmey: You originally posted another response with some suggested code to bring a cassandra db into R via R only - interestingly, I have previously tried to import this cassandra table directly from withing R/Sparklyr using almost identical methods to what you posted (see code below), but kept getting errors at the end relating to `Variables must be length 1 or xxx` (very similar to issue [531](https://github.com/rstudio/sparklyr/issues/531, and perhaps [411](https://github.com/rstudio/sparklyr/issues/411). I posted a comment on issue 531 hoping to get some clarification. As I haven't been able to figure out what went wrong in R or how to get around it, I've been trying to do something similar in Java. Hence my current predicament. I have now also tried using `tbl(sc, "spark_table_name")` to create and R reference, and that didn't work either . 

@javierluraschi, thanks for the suggestions. As mentioned above, I have previously loaded cassandra tables into R without a problem, however, I am having major issues with this one table. 

My R code for bringing Cassandra tables into R natively is as follows:

```
# list of columns to import form table
cols <- list("col1", "col2", "col3") 

session <- spark_session(sc)

cass_df <- session %>% 
  invoke("read") %>% 
  invoke("format", "org.apache.spark.sql.cassandra") %>% 
  invoke("options", as.environment(list(keyspace = <cass_keyspace>, table = <cass_table>))) %>% 
  invoke("load") %>% 
  invoke("select", cols[[1]], cols[2:length(cols)]) # <- use this to select all from the 'cols' list

cass_df_tbl <- sparklyr:::spark_partition_register_df(
         sc,
         cass_df,
         name = cass_table,
         repartition = 0,
         memory = T)
)
```

This code works completely fine with other tables and I can manipulate them with dplyr and collect results. With this table, although the import into Spark and registration in R seems to work (and the table exists on spark cluster), if I try to preview it I get errors saying `Variables must be length 1 or xxxxx` and a dialogue box stating `R code execution error.` It's been suggested that because some of the strings have newline characters (`\n`), they are being broken up into multiple variables? Is that possible? Any other suggestions?

**Comment by javierluraschi** [comment]
@renegademonkey correct, there was an issue collecting data with `\n` completely unrelated with Cassandra, https://github.com/rstudio/sparklyr/pull/574 fixes this issue some I'm closing this issue now. Feel ree to reopen if we are missing something.

BTW. If you are planning to make this extension public we can list it here, let us know! http://spark.rstudio.com/extensions.html

**Comment by abdkumar** [comment]
> nterestingly, I have previously tried to import this cassandra table directly from withing R/Sparklyr using almost identical methods to what you posted (see code below), but kept getting errors at the end relating to `Varia`

@renegademonkey  when iItry the same code iI get 
`Error: java.lang.NoClassDefFoundError: org/apache/commons/configuration/ConfigurationException`
