### ISSUE TITLE
Add a method to get the data from a model

### ISSUE THREAD

**Issue by richierocks** [rstudio/sparklyr#555]
It's sometimes useful to be able to extract the data from model objects returned by `ml_*` functions. It currently takes a bit of digging to figure out what to do.

Here's my suggestion:

```r
tbl.ml_model <- function(x) {
  sdf_register(x$data)
}
```

Then you can just get the data in the natural way, using `tbl(a_model)`.

**Comment by kevinykuo** [comment]
Is a `tbl` method appropriate or should we write something like `ml_model_data`?

**Comment by kevinushey** [comment]
I think I prefer `ml_model_data()` over a `tbl()` method. The first argument to `tbl()` is typically a data source (e.g., in `sparklyr`, a `spark_connection` object); I don't think models fit that mold very well.
