### ISSUE TITLE
bind_cols() gives "incompatible number of rows" error

### ISSUE THREAD

**Issue by richierocks** [rstudio/sparklyr#556]
To reproduce:

```r
sc <- spark_connect("local")
d1 <- data_frame(
  x = 1:5
)
d2 <- data_frame(
  y = runif(5)
)
tbl1 <- copy_to(sc, d1) 
tbl2 <- copy_to(sc, d2) 

bind_cols(tbl1, tbl2)
## Error in cbind_all(x) : incompatible number of rows (1, expecting 11)
```

**Comment by kevinushey** [comment]
`bind_cols()` is provided by `dplyr`, but as far as I can tell it's not actually a generic, so we can't provide our own custom methods for it. Perhaps something to file upstream?

**Comment by kevinykuo** [comment]
@richierocks would you mind sharing the use case for this? Implementing `cbind` would involving some plumbing due to partitioning of the data. See also https://github.com/rstudio/sparklyr/issues/35.

**Comment by richierocks** [comment]
@kevinykuo This came about from trying to write a residuals method for `ml_model` objects. See https://github.com/rstudio/sparklyr/issues/557.

My first attempt looked like this:

```r
residuals.ml_model <- function(x, ...) {
  actual <- sdf_register(x$data)  %>%
    select_(actual = x$response)
  predicted <- data_frame(predicted = predict(x)) 
  both <- bind_cols(actual, predicted)
  both %>%
      transmute(residual = predicted - actual)
}
```

The more general case is fortifying dataset with other tibbles. If you want to add a column to a tibble, use mutate. But if you want to add a whole tibble, it's natural to bind by columns.

Column binding is really just an inner join, so I think you can implement it by adding a dummy ID column (see how `predict.ml_model()` uses `sdf_with_unique_id()`), inner joining by that ID, then dropping the ID again.

**Comment by javierluraschi** [comment]
`sdf_bind_rows` and `sdf_bind_cols` is merged. We asked for support in `dplyr` to make `dplyr::bind_rows` and `dplyr::bind_cols` generic, once we have that we can make this work as you would expect, Richie. In the meantime, `sdf_bind_rows` and `sdf_bind_cols` is the way to go.

**Comment by kevinykuo** [comment]
Closing in favor of https://github.com/rstudio/sparklyr/issues/888
