### ISSUE TITLE
install error on mac: subscript out of bounds

### ISSUE THREAD

**Issue by koaning** [rstudio/sparklyr#56]
With devtools preinstalled, the install gives an error. 

```
> devtools::install_github("rstudio/sparklyr")
Downloading GitHub repo rstudio/sparklyr@master
from URL https://api.github.com/repos/rstudio/sparklyr/zipball/master
Installing sparklyr
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found
Warning in download.packages(x$name, destdir = dest_dir, repos = x$repos,  :
  download of package ‘config’ failed
Error in download.packages(x$name, destdir = dest_dir, repos = x$repos,  : 
  subscript out of bounds
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  download had nonzero exit status
```

I can download the zipball from the direct link. The local install gave other errors. 

```
> install.packages('/Users/code/Downloads/rstudio-sparklyr-ab7f008', repos = NULL, type="source")
ERROR: dependencies ‘sparkapi’, ‘config’, ‘rappdirs’ are not available for package ‘sparklyr’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/sparklyr’
Warning in install.packages :
  installation of package ‘/Users/code/Downloads/rstudio-sparklyr-ab7f008’ had non-zero exit status
```

**Comment by javierluraschi** [comment]
@koaning One workaround is to install each dependency explicitly, but thanks for bringing this up.

@kevinushey @jimhester: Are there cases in which dependencies from devtools won't auto-install? Is there something worth considering changing in sparklyr to automate this during te install?

**Comment by koaning** [comment]
To anybody installing this manually: `sparkapi` can be installed via  

```
devtools::install_github("rstudio/sparkapi")
```

`rappdirs` and `config` appear to be on CRAN.

**Comment by koaning** [comment]
Can confirm that the manual workaround seems to work.

**Comment by jjallaire** [comment]
No, they'll always auto-install, however one issue is that if the version
of R is < 3.2 then there are no binaries from CRAN to install the failure
above might be encountered. I believe as of R 3.2 R will try source
packages as a fallback but that doesn't solve the problem for 3.1.

What version of R are you running?

**Comment by javierluraschi** [comment]
Great! Thanks for validating this.

**Comment by koaning** [comment]
This is the R version I am now running. 

```
               _                           
platform       x86_64-apple-darwin13.4.0   
arch           x86_64                      
os             darwin13.4.0                
system         x86_64, darwin13.4.0        
status                                     
major          3                           
minor          2.1                         
year           2015                        
month          06                          
day            18                          
svn rev        68531                       
language       R                           
version.string R version 3.2.1 (2015-06-18)
nickname       World-Famous Astronaut      
```

**Comment by koaning** [comment]
Also ... I'm really liking what I'm seeing here you guys. Nice work! 

I've seen a couple of clients switch their stack from R to python in the last year because of spark (all the while complaining about the lack of a good plotting library). This new rstudio feature might just get people back on the R-bandwagon.

**Comment by kevinushey** [comment]
Is it possible that `devtools` needs to be updated? (Perhaps it's one of the older versions that doesn't understand the `Remotes:` field?)

**Comment by kevinushey** [comment]
The error here:

```
Warning in download.packages(x$name, destdir = dest_dir, repos = x$repos,  :
  download of package ‘config’ failed
```

I'm guessing this could just be due to connectivity issues.

**Comment by koaning** [comment]
i have tried it on two different wifi networks, that was not it. Upgrading `devtools` seems to have done the trick.
