### ISSUE TITLE
sdf_predict for RF takes lots of time to predict

### ISSUE THREAD

**Issue by dsblr** [rstudio/sparklyr#560]
Hi team,
sdf_predict taking more than 30 minutes to get the prediction on 1300 hundred observations, where model build using ml_random_forest with 500 trees.

Please help me to reduce the sdf_predict function processing time.

**Comment by edgararuiz** [comment]
Hi @dsblr, have you tried using ```ft_string_indexer``` for your categorical features during data preparation?  I noticed an overall increase in performance after reading how some pipeline models do this before performing vector transformations.  Here's a quick R Notebook I put together to show how it could be used: http://rpubs.com/edgarruiz/262323

**Comment by dsblr** [comment]
@edgararuiz Thanks for your input, but I am not using any categorical input/independent variable. All the input/independent variable are quantitative and only the outcome us categorical with two label.

**Comment by javierluraschi** [comment]
@dsblr slow performance for RF in `sparklyr` is almost-definetely not an `sparklyr` issue but rather an implementation improvement needed in Spark MLlib. I would also try with [rsparkling](https://github.com/h2oai/rsparkling) from [H2O](http://www.h2o.com) or find some articles/benchmarks that help optimize cluster nodes and configurations to improve performance of RF in Spark in general.
