### ISSUE TITLE
Implicit Function calls for ALS

### ISSUE THREAD

**Issue by harishrvt** [rstudio/sparklyr#561]
I'm using the ALS algorithm and the model doesn't have a parameter for using Implicit ALS. Here's the scala code that I would normally use for the same purpose. 

val als = new ALS()
  .setMaxIter(5)
  .setRegParam(0.01)
  .setImplicitPrefs(true) // Not available
  .setUserCol("userId")
  .setItemCol("movieId")
  .setRatingCol("rating")

**Comment by chezou** [comment]
I've started to work on this https://github.com/chezou/sparklyr/tree/implicit-als

**Comment by harishrvt** [comment]
Great! In the meantime, do you have an alternative way to invoke the trainImplicit function? I can't seem to get it working on my side and I can't find (much) documentation either

**Comment by chezou** [comment]
I created PR on #565 . Could you check it?
