### ISSUE TITLE
cannot copy dataframe to spark, httr:read_csv error 

### ISSUE THREAD

**Issue by koaning** [rstudio/sparklyr#57]
I've been able to install `sparklyr` but I seem to hit an error when copying and pasting the hello world example on http://spark.rstudio.com/index.html. This code:

```
library(sparklyr)
library(dplyr)
sc <- spark_connect(master = "local")
iris_tbl <- copy_to(sc, iris)
```

I can confirm that `spark_web(sc)` and `spark_log(sc)` work. But the last line causes this error: 

```
Error in readr::read_csv(column, col_names = FALSE, col_types = "c", na = character(),  : 
  unused argument (trim_ws = FALSE)
```

Apon inspecting the trace it seems like there's something being passed to `readr::read_csv` that it cannot do anything with. 

```
8. readr::read_csv(column, col_names = FALSE, col_types = "c", na = character(), trim_ws = FALSE, progress = FALSE)
7. spark_dataframe_read_column(tbls, "tableName")
6. src_tbls.sparklyr_connection(sc)
5. src_tbls(sc)
4. match(x, table, nomatch = 0L)
3. name %in% src_tbls(sc)
2. copy_to.sparklyr_connection(sc, iris, trim_ws = FALSE)
1. copy_to(sc, iris, trim_ws = FALSE)
``` 

Any quickfix?

**Comment by jjallaire** [comment]
You may have an older version of readr (it looks like the trim_ws argument
was added in 0.2). Our DESCRIPTION doesn't state that read >= 0.2 is
required though, so it wouldn't have been upgraded on install. I'll change
this.

**Comment by javierluraschi** [comment]
JJ submitted a fix for this, it is required to uninstall and install sparklyr to pick this change. @koaning could you check this works for you and close if it does?

**Comment by koaning** [comment]
```
> sc <- spark_connect(master = "local")
> iris_tbl <- copy_to(sc, iris)
```

No error. LTGM. Thanks.
