### ISSUE TITLE
Can't access to S3 bucket through flintrock & sparklyr tool chain

### ISSUE THREAD

**Issue by statkclee** [rstudio/sparklyr#582]
I could not figure out the follwoing problems.

My workflow is as follows;
1. Set up Spark cluster through flintrock
2. Install R, libcurl, openssh, rstudio server
3. Install sparklyr 

I checked out the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY over and over.
------------------------------------------------------------------------------------
### R code to access S3 bucket
Sys.setenv(AWS_ACCESS_KEY_ID="")
Sys.setenv(AWS_SECRET_ACCESS_KEY="")

Sys.setenv(SPARK_HOME="/home/ec2-user/spark")
.libPaths(c(file.path(Sys.getenv("SPARK_HOME"), "R", "lib"), .libPaths()))

### s3 access pkg
config <- spark_config()
config$sparklyr.defaultPackages[[1]] <- "org.apache.hadoop:hadoop-aws:2.7.3"

### Spark cluster
sc <- spark_connect(master = "spark://ip-172-XX-X-XXX:7077",
                    spark_home = "/home/ec2-user/spark",
                    config = config)

### local dataframe to sc
iris_tbl <- copy_to(sc, iris)
head(iris_tbl)
-----> OK !!!

### load iris on s3
iris_tbl <- spark_read_csv(sc, "iris", path="s3://victor-seoul/iris.csv")
---> Error
--------------------------------------------------------------------
Error: org.apache.hadoop.fs.s3.S3Exception: org.jets3t.service.S3ServiceException: Service Error Message. -- ResponseCode: 403, ResponseStatus: Forbidden, XML Error Message: <?xml version="1.0" encoding="UTF-8"?><Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><AWSAccessKeyId>

--------------------------------------------------------------------

> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Amazon Linux AMI 2016.09

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.5.0.9001    sparklyr_0.5.3-9003

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10     rstudioapi_0.6   magrittr_1.5     hms_0.3          devtools_1.12.0  xtable_1.8-2    
 [7] R6_2.2.0         rlang_0.0.0.9004 httr_1.2.1       tools_3.3.2      parallel_3.3.2   config_0.2      
[13] DBI_0.6          git2r_0.18.0     withr_1.0.2      htmltools_0.3.5  yaml_2.1.14      assertthat_0.1  
[19] digest_0.6.12    rprojroot_1.2    tibble_1.2       shiny_1.0.0      readr_1.1.0      base64enc_0.1-3 
[25] curl_2.4         memoise_1.0.0    glue_0.0.0.9000  mime_0.5         backports_1.0.5  jsonlite_1.3    
[31] httpuv_1.3.3

**Comment by statkclee** [comment]
It's very strange because when I access to S3 bucket with aws.s3 package, there is no problem.

But, with spark_install() functions, I could not access to S3 bucket. 

Moreover, when I follow the instrunctions from https://www.santoshsrinivas.com/installing-apache-spark-on-ubuntu-16-04/, I've got the similar errors; AWS Access Key ID and Secret Access Key.

-------------------------------------

Error: java.lang.IllegalArgumentException: AWS Access Key ID and Secret Access Key must be specified as the username or password (respectively) of a s3 URL, or by setting the fs.s3.awsAccessKeyId or fs.s3.awsSecretAccessKey properties (respectively)

**Comment by javierluraschi** [comment]
@statkclee try using `s3a://` instead of `s3://` to reference the bucket, take a look at this resources as well:

- https://spark.rstudio.com/articles/deployment-amazon-s3.html
- https://medium.com/@subhojit20_27731/apache-spark-and-amazon-s3-gotchas-and-best-practices-a767242f3d98

This is probably not an issue on `sparklyr`, so I'll be closing this. Try to find me in gitter if you want a few more pointers: https://gitter.im/rstudio/sparklyr, a question in stackoverflow could also help reach out the AWS community as well.
