### ISSUE TITLE
Error: object 'db_data_type' not found whilst loading namespace 'sparklyr'

### ISSUE THREAD

**Issue by navdeep-G** [rstudio/sparklyr#583]
I am seeing the following issue when trying to download sparklyr from github:

`Error: object 'db_data_type' not found whilst loading namespace 'sparklyr'`

**Comment by AlexYoung757** [comment]
Error: object 'db_data_type' not found whilst loading namespace 'sparklyr' . i also find this error

**Comment by GriffinRidgeback** [comment]
This is NOT fixed! Tried to install on a new R environment for work I HAVE to do in sparklyr and still got:

Error : object 'db_data_type' not found whilst loading namespace 'sparklyr'
I saw somewhere that this had been fixed but evidently not.

Why is this still not working? I have a customer who is depending on me being able to transform their code into sparklyr format but I have no environment in which to do this.

Please help!! What diagnostic information can I provide that will help in this? Has anyone installed this package successfully? Under what versions of R and installed packages did it work?

Thanks!!

**Comment by kevinykuo** [comment]
@AlexYoung757 @GriffinRidgeback for the time being installing from @navdeep-G's repo worked for me

**Comment by navdeep-G** [comment]
@kevinykuo @AlexYoung757 @GriffinRidgeback Should be fixed now. @javierluraschi merged my PR this morning. Will close this issue.
