### ISSUE TITLE
Random forest in Spark R -Accuracy or Rsquared problem

### ISSUE THREAD

**Issue by am9090** [rstudio/sparklyr#590]
Hi guys

I was running random forest using spark in R 

Can any one tell me how I get accuracy

Please help its urgent

I would have got normall r square but it drops certain row when random forest runs

so to get r square I need equal rows in original data and predicted data

**Comment by javierluraschi** [comment]
```
ml_classification_eval(predicted_tbl, label, predicted_lbl, metric = "accuracy")
```

**Comment by am9090** [comment]
I tried but its not working

maybe  i am doing somewrong, is there an example of that something like this?

kmeans_model <- iris_tbl %>%
  select(Petal_Width, Petal_Length) %>%
  ml_kmeans(centers = 3)

# print our model fit
print(kmeans_model

**Comment by javierluraschi** [comment]
@am9090 you could calculate accuracy with a hand-labeled dataset with something like:

```r
sub_tbl <- iris_tbl %>% select(-Species)
ml_fit <- ml_kmeans(sub_tbl, centers = 3)
ml_pred <- sdf_predict(ml_fit, iris_tbl)

# for example purposes I'll assume all my labeled data should point to the second cluster, here you would have to introduce your own dataset
ml_pred <- mutate(ml_pred, actual = 2.0, prediction = as.double(prediction))

ml_classification_eval(ml_pred, "actual", "prediction", "accuracy")
```
```
[1] 0.4066667
```

Closing this one with above reference.
