### ISSUE TITLE
Spark Connection Issues

### ISSUE THREAD

**Issue by deepu2015** [rstudio/sparklyr#595]
I was following the instructions at 'http://spark.rstudio.com/' & got struck at this command.(I updated the dplyr package from gitbub/hadley). I have the latest version of R- 3.3.3.

`import_iris <- copy_to(dest = sc,df = iris,name = "spark_iris",overwrite = T)`

**Error in tbl.spark_connection(sc, name) : could not find function "src_sql"**

_Surprisingly src_sql() function seems to be missing though dplyr package is loaded._

I then reinstalled dplyr package from CRAN & I get the below message when I try to load sparklyr package.

**namespace ‘dplyr’ 0.5.0 is being loaded, but >= 0.5.0.9000 is required**

**Comment by albit3** [comment]
Try restarting your R session and installing developer versions of dplyr and sparklyr

if (packageVersion("devtools") < 1.6) {
  install.packages("devtools")
}
devtools::install_github("hadley/lazyeval")
devtools::install_github("hadley/dplyr")
devtools::install_github("rstudio/sparklyr")

**Comment by deepu2015** [comment]
Thank you. I will give it a try. By the way, which version of Spark should I install ? 1.6.2 or 2.0.0 or 2.0.1 ?
I plan to use it as a local cluster.

**Comment by edgararuiz** [comment]
2.1.0 would be the best one if you're using the  devel version of sparklyr

**Comment by deepu2015** [comment]
Thank you albit3 & edgararuiz. That worked for me. However when I run the copy_to() command, it throws an error 'UNexpected data type' & the dataset is not listed under the Spark tab. When I re-run it, it will say that the dataset already exists. When I click on SparkUI, it opens up a web page & under storage tab, I can see my 'spark_iris' dataset. I couldn't figure out why it throws that error !!!

**Comment by albit3** [comment]
Hey Deepu,

I had the same issue. Resolved it by installing sparlyr before dplyr. Both from CRAN, no the developer version.

Let me know if tu this solves it.

Albit

Sent from my iPhone

On Apr 3, 2017, at 1:14 PM, Deepu A <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you albit3 & edgararuiz. That worked for me. However when I run the copy_to() command, it throws an error 'UNexpected data type' & the dataset is not listed under the Spark tab. When I re-run it, it will say that the dataset already exists. When I click on SparkUI, it opens up a web page & under storage tab, I can see my 'spark_iris' dataset. I couldn't figure out why it throws that error !!!

**Comment by javierluraschi** [comment]
The original issue was resolved with Edgar's suggestion, the second one should be fixed by upgrading `sparklyr` and ideally RStudio to 1.1.
