### ISSUE TITLE
Unexpected data type when creating connection or reading data

### ISSUE THREAD

**Issue by GriffinRidgeback** [rstudio/sparklyr#596]
Hello,
I am on a MacBook Pro and keep getting this error (see attached screen shot) whenever I connect to my local Spark instance or read data of any sort.  At first I thought it was a problem with my customer's dataset but I get the same error when I try the examples on the sparklyr website, such as copy_to using the iris table.

Please help.

Thanks,
Kevin
<img width="416" alt="screen shot 2017-04-03 at 9 35 35 am" src="https://cloud.githubusercontent.com/assets/10776639/24611922/ae8ce35c-1851-11e7-9360-781d7312918a.png">

**Comment by GriffinRidgeback** [comment]
More information:

Using the examples provided under the **dplyr** section on GitHub, I get the following results:

``` 
flights_tbl %>% filter(dep_delay == 2)
```
```
Source:     lazy query [?? x 19]
Database:   spark_connection
```
Whereas in the example, it looks like this:

```
## Source:   query [6,233 x 19]
## Database: spark connection master=local[8] app=sparklyr local=TRUE
```

**Comment by GriffinRidgeback** [comment]
Also, I see no tables in my Spark tables tab in RStudio

**Comment by deepu2015** [comment]
I too face the same problem. However try clicking on the 'SparkUI' button under the 'Spark' tab which will open up a webpage. Click on 'Storage' & your 'iris_tbl' might be there.

**Comment by GriffinRidgeback** [comment]
thanks @deepu2015 , that worked.  I can see my tables there.

I'm trying to understand just exactly what I'm working with.  Using **spark_read_csv**, the documentation says I should get a _Spark Dataframe_ from the CSV file I'm reading in.  I should be able to work with this DF the same way I do in R but I don't seem to have a data frame.  What I have is an object with two fields:   **src and ops**.  
There are numerous sub-fields in there, none of which get me to my data.  So, I can do something like **QueryData$field1** but I get _NULL_ as the result.  I can use the **dplyr** verb like _filter_, which returns results but I think I need to do things like **QueryData$field1** that access that fields directly (non-dplyr verbs).  Here's an example:

```
> is.na(QueryData$JobDesc)
logical(0)
Warning message:
In is.na(QueryData$JobDesc) :
  is.na() applied to non-(list or vector) of type 'NULL'
```

**Comment by deepu2015** [comment]
Glad that it worked for you. I am also brand new to Spark (just 2 days) & hence have limited knowledge in it. So far I could see that the R syntax to work with Spark datasets are slightly different though not entirely sure about it. The following link might be of use for you. 
http://spark.rstudio.com/images/sparklyr-cheatsheet.pdf

**Comment by GriffinRidgeback** [comment]
Thanks, @deepu2015 I will have a look.

**Comment by wang950312** [comment]
I also fact that problem, and my spark version is 2.0.1. Maybe the latest version will led the problem?

**Comment by GriffinRidgeback** [comment]
I am using Spark 2.1.0 on my local machine, running Spark in master mode.  I'm still looking at the cheatsheet, which is promising.  I don't know if (a) this is how it is supposed to work and I just don't understand the paradigm yet (b) there is a problem with my platform [Mac, Spark 2.1.0] or (c) something in sparklyr?

**Comment by javierluraschi** [comment]
I was able to reproduce the "Unexpected data type" error using `sparklyr 0.5.6` from CRAN and `RStudio 1.0`. The problem is already fixed but requires using the development version of `sparklyr` as follows:

```
devtools::install_github("rstudio/sparklyr")
```
