### ISSUE TITLE
calling date function from spark_data frame

### ISSUE THREAD

**Issue by haridwarj** [rstudio/sparklyr#597]
Hi,
   Id;Name;city;start_date;end_date
1;xxxx;xxxxx;20170101;20170103
2;xxxx;xxxxx;20170101;20170105
.............................................
...........................................................
2;xxxx;xxxxx;20170101;20170109

this data is in csv format.

I have made sparklyR custom jar in scala and added using
conf[["sparklyr.jars.default"]] <- c("../inst/java/DateTime-2.0.2-2.11.jar")
In above jar below scala code has written that is simple date conversion...

package DateTime

import java.text.SimpleDateFormat
import java.sql.Date
object DateAndTimeOprn {
def convertDate(startDate:String) = {
    var sdf1 = new SimpleDateFormat("yyyyMMdd");
    var parsed:java.util.Date = sdf1.parse(startDate);
    var sqlStartDate:java.sql.Date = new Date(parsed.getTime());
    sqlStartDate
  }
}
##############################################################
here I have corresponding code of scala in R
convert_date <- function(sc, date1) {
  sparklyr::invoke_static(sc, "DateTime.DateAndTimeOprn", "convertDate", date1)
}

Now When I will call like :- 
convert_date(sc,"20190909")
this will work fine...
but when I will call function using sparklyr/dplyr then 

test_data <- spark_read_csv(sc,"test_data","/csvInput/abc.csv", header = TRUE,
                           infer_schema = TRUE, delimiter = ";", memory = TRUE)
test_tbl <- copy_to(sc, test_data, overwrite = TRUE)
test_tbl <- test_tbl %>% mutate(Begin_DATE=convert_date(sc, start_date))

Then lot of error is coming...
??? can any one help me.

**Comment by javierluraschi** [comment]
@haridwarj `convert_date` would need to be registered as a Spark UDF, I create an example for you here: https://github.com/javierluraschi/sparklyudf.
