### ISSUE TITLE
Decision tree/Gradient tree visualization/Spark Ml algorithms

### ISSUE THREAD

**Issue by am9090** [rstudio/sparklyr#598]
Hi everyone

I ran ml spark algorithms and got the output but how do I get decision tree in visual form

the output I get is
class.org,apache.spark.ml.decisontreeregression model
 is uid=dtr_125661g256kr something like that

Please help

**Comment by javierluraschi** [comment]
I believe @edgararuiz might be able to share a couple visualization thoughts...

**Comment by javierluraschi** [comment]
Visualization is currently not within the scope of `sparklyr`, the recommended approach is to retrieve the data you need to R and visualize it there with, say, `ggplot2` or many other packages provided by the R community.

To retrieve the model, currently you could run something like:

```r
iris_tbl <- copy_to(sc, iris)
model <- iris_tbl %>%
  ml_decision_tree(Species ~ Sepal_Width + Sepal_Length + Petal_Width,
                               type = "classification",
                               impurity = "entropy", max.bins = 16L,
                               max.depth = 3L, min.info.gain = 1e-5, min.rows = 2L,
                               thresholds = c(1/2, 1/3, 1/4), seed = 42L)
invoke(model$.model, "toDebugString") %>% cat()
```

```
DecisionTreeClassificationModel (uid=dtc_57b1c706f6e3) of depth 3 with 9 nodes
  If (feature 2 <= 0.5)
   Predict: 2.0
  Else (feature 2 > 0.5)
   If (feature 2 <= 1.7)
    If (feature 2 <= 1.3)
     Predict: 0.0
    Else (feature 2 > 1.3)
     Predict: 0.0
   Else (feature 2 > 1.7)
    If (feature 1 <= 5.9)
     Predict: 1.0
    Else (feature 1 > 5.9)
     Predict: 1.0
```

We can consider improving this with [broom](https://github.com/rstudio/sparklyr/issues/1002) support.
