### ISSUE TITLE
Add .toPMML spark methods for MLlib into sparklyr

### ISSUE THREAD

**Issue by TaylorAndrew** [rstudio/sparklyr#60]
I'm trying export my models as PMML. In scala one would use

myModel.toPMML("./myModelPMML.xml")

I'm not currently seeing a way to do this, nor a way to 'inject' raw scala so that I could do it myself, similar to how I can use `ft_sql_transformer()` to submit raw sql to the SparkSQL database instead of using dplyr language.

Are either of these two options possible currently, or are they on the horizon?

**Comment by kevinushey** [comment]
You should be able to do this 'by hand', with something like:

```
model <- ml_kmeans(<...>)
sparkapi::invoke(model$.model, "toPMML", "./myModelPMML.xml")
```

Note that `sparkapi::invoke` basically gives you access to the Scala API for any Spark object (represented as a proxy `jobj` on the R side) so this should get you going in the right direction.

Is this a common enough action that it would make sense to expose a function / API on the `sparklyr` side?

**Comment by TaylorAndrew** [comment]
I'll keep playing with `sparkapi::invoke()` but at this moment I wasn't able to get it to work.

Instead of saving to xml, I just tried the simplest option, to print to the console.

I created a kmeans cluster model:

    kmeans <- ml_kmeans(kmeans_tbl, 3)

    sparkapi::invoke(kmeans$.model, ".toPMML") 

Should conceptually print the PMML model to the console, but instead I get:

     Warning in readLines(log) :
     cannot open file 'C:\Users\taylo\AppData\Local\Temp\Rtmp6hiGlI\filea7c7b2172b8_spark.log': Permission denied
     Show Traceback
     Error: failed to invoke spark command (unknown reason)

I'm sure many use cases will have people keep the model in spark and make new predictions there. In which case `predict()` works just fine interactively in R (or just using said model in an application that can hook up to spark). But for people who who need to export the model to be scored with ADAPA, easy access to the PMML via sparklyr would be great.

**Comment by kevinushey** [comment]
Gotcha -- it sounds like we should think of implementing something like `ml_model_save(..., format = "PMML")` and `ml_model_load(...)`, perhaps?

I'm less sure about the spark log problem -- perhaps that file is being creating by Spark, which is being running with elevated permissions / alternate permissions and hence isn't user accessible. @javierluraschi, does that sound correct?

**Comment by jjallaire** [comment]
The log problem is a red herring (on Windows we can't currently access the
log because it's locked exclusively by the spark shell (we need to find a
workaround for this).

In terms of saving and loading models, I believe that Spark 2.0 now enables
you to save and load models to e.g. HDFS in some sort of native form so we
should be sure to support this alongside PPML.

**Comment by javierluraschi** [comment]
@TaylorAndrew The call should not contain a `.` on it. Try this instead `sparkapi::invoke(kmeans$.model, "toPMML") `.

**Comment by jjallaire** [comment]
Javier, shouldn't our model objects implement the spark_jobj S3 method so
that accessing the .model property directly isn't required (i.e. just pass
the kmeans object directly to invoke?

**Comment by javierluraschi** [comment]
@jjallaire yes, that would be a good addition. Opened: https://github.com/rstudio/sparklyr/issues/61

**Comment by kevinushey** [comment]
Hrm, to my surprise, even though this appears to be exported on the Scala side, it seems like we can't access it from the RBackendHandler. Perhaps because [PMMLExportable](https://spark.apache.org/docs/1.6.1/api/scala/index.html#org.apache.spark.mllib.pmml.PMMLExportable) is part of the so-called 'developer API'?

We might have to dig a bit more to make this work, unfortunately.

**Comment by kevinushey** [comment]
Ahhh, I know what's going on. We use the `ml` package of algorithms for model fitting; not `mllib`. Unfortunately, the models returned by routines in the `ml` package do not implement the `PMMLExportable` interface, and so those methods are not available.

It looks like it's still possible to save these ML model objects; just not as PMML. :-/

**Comment by javierluraschi** [comment]
Marking as feature request since as Kevin mentions, we are based on the newer `ml` library that does not support this yet.

BTW. Wouldn't it be possible to get the predictive model and manually map the output into the [pmml](https://cran.r-project.org/web/packages/pmml/index.html) package?

**Comment by kevinushey** [comment]
Maybe, but I would strongly prefer filing a feature request on the Spark side to add this, rather than trying to implement it ourselves.

**Comment by javierluraschi** [comment]
K, marking as feature request here as well.

**Comment by ElianoMarques** [comment]
This would be a good feature to add. Also the ability to save and load spark models, which is one of the main features in 2.0.

**Comment by ElianoMarques** [comment]
@kevinushey @javierluraschi perhaps the easiest way for this would be to leverage this: 
https://github.com/jpmml/jpmml-converter 
and the https://github.com/jpmml/jpmml-sparkml?

**Comment by mrjoseph84** [comment]
@kevinushey are there any updates on exporting sparklyr models to pmml? is this already supported by the package?

**Comment by kevinushey** [comment]
Unfortunately no. As far as I can see, these still haven't been ported from `mllib` to `ml` on the Spark side. See e.g.

https://issues.apache.org/jira/browse/SPARK-11171
https://issues.apache.org/jira/browse/SPARK-11237
https://issues.apache.org/jira/browse/SPARK-11239

As far as I can see, the work here has unfortunately fallen off the radar somewhat.

**Comment by kevinykuo** [comment]
@mrjoseph84 just curious what's your use case with pmml?

**Comment by mrjoseph84** [comment]
@kevinushey  Thanks for the update and links - I will be monitoring this issues
@kevinykuo We are developing sparklyr scripts in analytical sandpits. We are planning to use PMML as a way to export predictive models written in sparklyr to visualization tools like MicroStrategy, Shiny, D3, etc.

**Comment by kevinykuo** [comment]
Closing this since this is unlikely to be supported in Spark and we support saving/loading pipelines and models now.
