### ISSUE TITLE
Unexpected data type

### ISSUE THREAD

**Issue by longhowlam** [rstudio/sparklyr#601]
Hi RStudio,

When I copy data from R to Spark I am getting the following error: 

![sparklyerrro](https://cloud.githubusercontent.com/assets/11842869/24693615/bdd37982-19de-11e7-9486-2a9b0741dba2.png)

`iris_tbl <- copy_to(sc, iris)`

Any Ideas? The data is loaded, but it is not visible in the Spark GUI.

>  src_tbls(sc)
[1] "iris"

Regards,
Longhow

Some information on my environment:

sparklyr version 0.5.3.9004
dplyr version 0.5.0.9001

Spark 2.1.0

R version

> platform       x86_64-redhat-linux-gnu     
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          3.2                         
year           2016                        
month          10                          
day            31                          
svn rev        71607                       
language       R                           
version.string R version 3.3.2 (2016-10-31)
nickname       Sincere Pumpkin Patch 

> $master
[1] "yarn-client"

$method
[1] "shell"

$app_name
[1] "sparklyr"

$config
$config$sparklyr.cores.local
[1] 16

$config$spark.sql.shuffle.partitions.local
[1] 16

$config$spark.env.SPARK_LOCAL_IP.local
[1] "127.0.0.1"

$config$sparklyr.csv.embedded
[1] "^1.*"

$config$`sparklyr.shell.driver-class-path`
[1] ""

attr(,"config")
[1] "default"
attr(,"file")
[1] "/home/hadoop/R/x86_64-redhat-linux-gnu-library/3.3/sparklyr/conf/config-template.yml"

$spark_home
[1] "/usr/lib/spark"

$backend
        description               class                mode                text              opened 
"->localhost:45698"          "sockconn"                "wb"            "binary"            "opened" 
           can read           can write 
              "yes"               "yes" 

$monitor
       description              class               mode               text             opened           can read 
"->localhost:8880"         "sockconn"               "rb"           "binary"           "opened"              "yes" 
         can write 
             "yes" 

$output_file
[1] "/tmp/Rtmp1sMLdd/file639f1b35e079_spark.log"

$spark_context
<jobj[4]>
  class org.apache.spark.SparkContext
  org.apache.spark.SparkContext@2975650c

$java_context
<jobj[5]>
  class org.apache.spark.api.java.JavaSparkContext
  org.apache.spark.api.java.JavaSparkContext@7fdf326f

attr(,"class")
[1] "spark_connection"       "spark_shell_connection" "DBIConnection"

**Comment by albit3** [comment]
Hey,

I had this issue. Try installing non-developer version of sparklyr followed by dplyr. Then spark_install version 1.6.2.

**Comment by longhowlam** [comment]
We have an existing spark 2.1.0 cluster, the non developer sparklyr 0.5.3 does not support spark 2.1.0

**Comment by edgararuiz** [comment]
That's correct

**Comment by GriffinRidgeback** [comment]
The table shows up in storage tab on Spark UI

**Comment by edgararuiz** [comment]
@javierluraschi / @kevinushey - I was just able to recreate this issue in colorado.rstudio.com.  It looks like the error is returned by the Spark tab inside the IDE. I can refer to the table with no problem, it just doesn't show up in the UI

**Comment by GriffinRidgeback** [comment]
The table won't show up in the **RStudio IDE Spark tab** but it should show up when you click the **Spark UI tab** and then click the **Storage tab** in the browser.

**Comment by mattpollock** [comment]
Is there any way to suppress the pop up? Perhaps by disabling the Spark tab in the IDE somehow?

**Comment by edgararuiz** [comment]
I believe the latest PR fixed the issue, please reinstall sparklyr and try again

**Comment by mattpollock** [comment]
Thanks. I'll test right after I get past https://github.com/hadley/rlang/issues/96

**Comment by longhowlam** [comment]
It works, Thanks Rstudio!!!

**Comment by mattpollock** [comment]
Fixed now. Thanks much.

**Comment by javierluraschi** [comment]
Looks like this one has been resolved, thanks all for this investigation.
