### ISSUE TITLE
How to use the tm and slam packages in sparklyr 

### ISSUE THREAD

**Issue by GriffinRidgeback** [rstudio/sparklyr#602]
Hello -

I am converting my customer's code from straight R into sparklyr.  However, I think I have hit a major roadblock.  His code makes heavy use of the **tm** and **slam** packages to create DocumentTermMatrix and simple_triplet_matrix.  I want to be able to run the relevant functions on the data I have loaded into the SparkContext so that I can take advantage of the parallelizing of Spark executors.  I know I can use `sdf_read_column` to pull a column from my Spark data frame into local R for some lightweight computations but the heavy lifting **_must_** be done on the cluster.

Does anyone know if this is even possible?  

Thanks in advance to all who respond,
Kevin

**Comment by javierluraschi** [comment]
@GriffinRidgeback it is currently not possible with `sparklyr` but we are actively developing this feature in the next couple months. How is your timeline looking like?

**Comment by GriffinRidgeback** [comment]
Thanks, Javier - I’m no longer working on that project, so I no longer have any immediate need.  Thank you for addressing it - I may need it sometime in the future should I be engaged in an NLP project again.

Thanks,

Kevin D'Elia
(301)785-4751

**Comment by javierluraschi** [comment]
@GriffinRidgeback see https://blog.rstudio.com/2017/07/31/sparklyr-0-6/ which introduces `spark_apply()`, that would enable using `tm` and `slam` packages.
