### ISSUE TITLE
Guidance on Setting up RStudio Server and Connecting to a Hadoop Cluster

### ISSUE THREAD

**Issue by NikkieThomas** [rstudio/sparklyr#604]
Hi,
I am sorry if this is not the right place to ask the question as it is not an issue.
We are intending to setup a server with RStudioServer Pro installed and users connect to it from their laptop/desktop via browser to access the RStudioIDE.
We have a Hadoop cluster already setup (HPD 2.4)
We need to use sparklyr (installed on the RStudioServer) access the Hadoop cluster.
Unfortunately, we dont have an Edge Node setup for our cluster. I cant install RStudioServer in one of the cluster machines, it has to be setup in a separate server/machine.

I would like to understand 
1)What setup is required in the new server (where we install RStudioServer) to connect to the Hadoop cluster ? i.e should I have spark installed on this machine or should just copy some libraries from my existing cluster(if so which are they) etc
2)What networking /configs are required in this new server to connect to the cluster ?
2)I noticed from sparkly cluster deployment option/cheetsheat that I could use master=yarn-client for Hadoop cluster and provide my spark_home of the cluster . 
Is that all required?

Apologies, if it is a very basic question . I am newbie to the RStudio and sparkly

Thanks
Nikkie

**Comment by jabberwockkie** [comment]
i'm on CDH and used Cloudera Manager to deploy to the RStudio server as an additional edgenode. you'll need the HDFS, Spark, and YARN clients installed (sorry i'm not familiar enough with Hortonworks to help with that). Best test is to run the spark-shell from the CLI and once that is working, sparklyr will work as well, just install from the CRAN.

for networking, if using Ambari to deploy, the configs should deploy as well and you'll just need to ensure that you have appropriate connectivity/access to the HDFS/YARN/Spark servers. if you're using a multihome setup with Kerberos & HDFS encryption, let me know as that requires additional configuration that we recently discovered.

if the above 2 things are working, then within R, you just load the sparklyr library and instantiate the connection as specified in the docs. then you can use Spark SQL or dplyr to query Hive data.

**Comment by GaryWMN** [comment]
I'm no expert, but I found the following documents useful...

[Prepare the Environment](http://docs.hortonworks.com/HDPDocuments/Ambari-2.2.2.18/bk_ambari-installation/content/_prepare_the_environment.html) -- List of things to check and consider when adding a node to your environment. Goal: get Ambari talking from the parent node (of the cluster) to the edge node (check esp. SSH), then use Ambari to add the necessary "client" services on the edge node. 

[Hortonworks Community](https://community.hortonworks.com/questions/6352/networking-and-edge-nodes.html) -- Search here for plenty of people who have asked other questions about setting up their edge nodes. 

Bon voyage!

**Comment by javierluraschi** [comment]
@NikkieThomas 

1) Yes you need Spark installed in the machine and it MUST match the version/distribution of the cluster. You want to install `RStudio Server` within the cluster, ideally, same authentication, same network, etc.
2) That varies, but I would start without any specific configs and fine tune as needed once the cluster is up and running.
3) Yes, that's it, you can use `yarn-client` and yes, you need to specify `SPARK_HOME`.

I'm closing this issue as this is covered in our and Sparks own documentation. Good luck!
