### ISSUE TITLE
Looking for how to mimic the behavior of the tm DocumentTermMatrix method in Spark API

### ISSUE THREAD

**Issue by GriffinRidgeback** [rstudio/sparklyr#607]
Hello,

I am converting my customer's code from R to sparklyr.  I have been able to figure out how to create N-Grams and StopWords but now need to convert his use of DocumentTermMatrix to something in the Spark MLlib API.  I can't seem to find a suitable analog and am hoping someone else has faced this issue and has a reasonable solution.

Thanks in advance to all who help.

**Comment by javierluraschi** [comment]
Have you tried using `ft_count_vectorizer `? See also https://blog.rstudio.com/2017/07/31/sparklyr-0-6/#improved-text-mining-with-lda.

Feel free to open a new github issue if this is not sufficient, thank you!
