### ISSUE TITLE
ml_gradient_boosted_trees() is slow

### ISSUE THREAD

**Issue by richierocks** [rstudio/sparklyr#622]
Unclear if it's a `sparklyr` problem or a Spark MLlib problem, but I think it's worth a quick investigation here.

`ml_gradient_boosted_trees()` seems to be pretty slow, even for moderately sized datasets.

For example, predicting the price in the `diamonds` dataset takes ~ 20 seconds:

```r
library(dplyr)
library(sparklyr)
library(stringr)

data(diamonds, package = "ggplot2")
diamonds <- diamonds %>%
  mutate(
    cut = str_replace(cut, " ", "_")
  )
sc <- spark_connect("local")

diamonds_tbl <- copy_to(sc, diamonds, overwrite = TRUE)

feature_cols <- diamonds_tbl %>% 
  colnames() %>% 
  setdiff("price")
system.time(
  model <- diamonds_tbl %>% 
    ml_gradient_boosted_trees("price", feature_cols)
)
```

compared to about 4 seconds for the equivalent using `mboost::mboost()`.

```r
library(mboost)

system.time(
  model2 <- mboost(
    price ~ carat + cut + color + clarity + depth + table + x + y + z, 
    diamonds
  )
)
```

I realize that the routines are not exactly comparable, but it seems a big enough difference to warrant some exploration.

**Comment by chezou** [comment]
IMHO, it is useless to compare both using small size dataset. Basically, Spark has overheads such as launching executor etc...

**Comment by richierocks** [comment]
@chezou Yes, it's a bad comparison, but I don't think that Spark overhead is the whole story, since `ml_random_forest()` doesn't suffer in the same way. From playing around with a few datasets, `ml_gradient_boosted_trees()` is consistently awfully slow. As I said in the original post, I have know idea if this is a `sparklyr` problem, or if it is somewhere on the Spark side. Worth spending a few minutes looking for optimizations though.

**Comment by kevinushey** [comment]
FWIW this is probably relevant: https://roamanalytics.com/2016/10/28/are-categorical-variables-getting-lost-in-your-random-forests/

The fact that we use dummy variables for categorical variables likely implies exactly the kind of slowness discussed here.

**Comment by javierluraschi** [comment]
@kevinykuo mind taking a look at this one at some point? I'm trying to stay away from changing `ml_` methods while you work on them, especially since this fix does not look like a one line change.

**Comment by kevinykuo** [comment]
@javierluraschi yep I think I have an idea on what this might be. spark.ml provides higher level APIs to deal with encoding categorical variables which may be more efficient. I'm utilizing those in the refactoring so hopefully things will go faster. Will track this one at https://github.com/rstudio/sparklyr/issues/944

**Comment by kevinykuo** [comment]
Well not sure if the refactoring helped, but I'm clocking at around 10s for GBT and 3s for RF now...

Note that RF is supposed to run faster since gradient boosting is sequential. Like @chezou mentioned these benchmarks would be more meaningful with bigger data.

```
system.time(
  model <- diamonds_tbl %>% 
    ml_gradient_boosted_trees(price ~ .)
)
# user  system elapsed 
# 0.327   0.109  11.189 
system.time(
  model2 <- diamonds_tbl %>% 
    ml_random_forest(price ~ .)
)
# user  system elapsed 
# 0.317   0.075   3.258 
```
