### ISSUE TITLE
CRAN version 0.5.3 of sparklyr incompatible with dev version of dplyr 0.5.0.9002

### ISSUE THREAD

**Issue by JohnMount** [rstudio/sparklyr#623]
With the dev version of dplyr installed (4/15/2017,  0.5.0.9002 commit d7d2f10167b4ac919e876eb9a891fd53345be985) the CRAN version of sparklyr (4/15/2017,   0.5.3 ) will not load:

```
library("sparklyr")
# Error : object 'sql_build' not found whilst loading namespace 'sparklyr'
# Error: package or namespace load failed for ‘sparklyr’
```
Problem goes away with dev-version of sparklyr (4/15/2017,  0.5.3-9005 commit 58fcd949d7709b4be44e2789a1c5355a6bd148f3).

**Comment by kevinushey** [comment]
We're aware of this -- `dplyr 0.6.0` will be coming to CRAN soon, and we plan to update `sparklyr` at that time as well. For now, if you are using the development version of `dplyr` you should use the development version of `sparklyr`.

**Comment by edgararuiz** [comment]
@kevinushey - Would simply installing dbplyr (https://github.com/hadley/dbplyr/) be another solution?  That way he can keep the versions of the packages he currently has

**Comment by JohnMount** [comment]
Thanks, I was hoping the answer was along the lines that there was a planned sparklyr release prior to the dplyr 0.6.0 release.

**Comment by kevinushey** [comment]
I'm not sure if installing `dbplyr` would help -- it's specifically designed to work with the development version of `dplyr`; I don't think it will work in tandem with the CRAN version of `dplyr`.

**Comment by javierluraschi** [comment]
`0.5.4` is on CRAN now: https://cran.r-project.org/web/packages/sparklyr/index.html
