### ISSUE TITLE
Allow collection/persistence of ml_model objects

### ISSUE THREAD

**Issue by richierocks** [rstudio/sparklyr#630]
I want to be able to reuse a model across connections.

Here's a linear regression of the [`cars`](https://www.rdocumentation.org/packages/datasets/topics/cars) dataset.

```r
library(dplyr)
library(sparklyr)

sc <- spark_connect("local")

# The classic cars dataset, plus some data to predict with
cars_tbl <- copy_to(sc, cars)
new_car_data <- data.frame(speed = seq(0, 100, 10))

# Any model will do; here's a linear regression
model <- cars_tbl %>% 
    ml_linear_regression("dist", "speed")
```

If I disconnect and reconnect, then making predictions no longer works.

```r
spark_disconnect(sc)
sc <- spark_connect("local")
new_car_data_tbl <- copy_to(sc, new_car_data)
model %>% predict(new_car_data_tbl)
## Error: java.lang.IllegalArgumentException: Object not found 139
```

I tried to persist the model using `sdf_persist()`, but that throws an error.

```r
sdf_persist(model)
## Error: Unable to retreive a Spark DataFrame from object of class ml_model_linear_regression ml_model
```

Some of the elements of the model are `spark_jobj`s, which (if I've understood them correctly) are connections to things in Spark. For example

```r
str(model$.model)
## Classes 'spark_jobj', 'shell_jobj' <environment: 0x1123e7120>
ls(model$.model)
## [1] "connection" "id"
```

I tried to collect the model to bring it into R, but no method has been implemented.

```r
collect(model)
## Error in UseMethod("collect") : 
##   no applicable method for 'collect' applied to an object of class "c('ml_model_linear_regression', 'ml_model')"
```

Due to the presence of these connection objects, saving the model using `saveRDS()` is also useless.

Have I missed some way to store an ml_model object? Or is it not currently possible?

**Comment by kevinushey** [comment]
You likely want to use `ml_save()` and `ml_load()`, which should work fine at least with a local Spark connection.

**Comment by richierocks** [comment]
@kevinushey Wow, I can't believe I missed those. Thanks.
