### ISSUE TITLE
Feature request: something to pull apart ml_* probability columns.

### ISSUE THREAD

**Issue by JohnMount** [rstudio/sparklyr#648]
Many of the `sparklyr` machine learning methods return class probabilities in a column of vectors. That is for each row we have a vector that has a probability per-class.  `ml_logistic_regression` is one example.  I have a worked example of the problem here: 
https://github.com/WinVector/Examples/blob/master/SparkTips/VSlicing/VSlicing.md .

These column of vectors values are hard to work with if you need to stay "on Spark" (i.e. the data is too big to call dplyr::collect() on). `sdf_read_column()` doesn't seem to be answer either as it returns a very large list of spark_job results (a possibly too large and very opaque structure).

My feature request is a function something like the following a new function with signature:
  `sdf_slice_vector(dataHandle, columnNameToTakeFrom, indexToTake, columnNameToWriteTo)` .
This would be the equivalent of of running the following `R` code:
  `dataHandle[[columnNameToWriteTo]] <- unlist(lapply(dataHandle[[columnNameToTakeFrom]], function(vi) { vi[[indexToTake]]}))`
but with all the steps happening on the Spark side (no data moving to/from `R`).

Note this could be solved by a solution to the following issue: https://github.com/rstudio/sparklyr/issues/649 .

**Comment by javierluraschi** [comment]
@kevinushey provided support for `sdf_separate_column` with https://github.com/rstudio/sparklyr/pull/667

Try something like:

```
library(dplyr)

sc <- spark_connect(master = "local")
mtcars_tbl <- copy_to(sc, mtcars)

model <- ml_logistic_regression(
  mtcars_tbl,
  response = "vs",
  features = "mpg"
)

fitted <- sdf_predict(model)

sdf_separate_column(
    fitted,
    "probability",
    list("on" = 1)
) %>% select(mpg, vs, on)
```

Would this be sufficient @JohnMount?

**Comment by MZLABS** [comment]
(John Mount here): that is perfect.  I was able to move up to the dev-version of Sparklyr and use it: https://github.com/WinVector/Examples/blob/master/SparkTips/VSlicing/VSlicing.md . Thanks!
