### ISSUE TITLE
Documentation request/query: what is guaranteed about row order in sparklyr?

### ISSUE THREAD

**Issue by JohnMount** [rstudio/sparklyr#650]
I have a documentation request: is it know or documented what is guaranteed about row order in sparklyr?  Correctly using a lot of code (such as even using `sdf_read_column()`) depends on the answer.

For R-local data (native data.frame, tibbles, and presumably data.table) row order is guaranteed preserved between operations (such as dplyr::mutate()).  For traditional database data sources (such as PostgreSQL) row order is not guaranteed and if the user wants such they must arrange by an explicit keyset.  

What is the answer for sparklyr and Spark?  And is their a referable document saying if row order is preserved or not?  Does it depend on the data source (maybe yes for Parquet files and Hive tables, and maybe no for others?).  Is order preserved on collect()?  I think it is critical to have a referable document that states what the guarantees are (else it is hard to tell if a lot of code is correct).

**Comment by kevinykuo** [comment]
This is definitely a little tricky, and there's not much documentation per se, see e.g. https://issues.apache.org/jira/browse/SPARK-16207 and http://stackoverflow.com/questions/29284095/which-operations-preserve-rdd-order.

I agree we should have some documentation so folks used to R data.frames are not surprised by some results. Where would we put them though?

**Comment by kevinushey** [comment]
`sparklyr`, for the most part, doesn't do any work to guarantee row order, and I agree this is problematic (especially for routines like `sdf_read_column()` where one might expect that a vector in the same row order as the dataset is retrieved).

We do try to ensure row order in some routines, e.g. you can see what we do here:

https://github.com/rstudio/sparklyr/blob/4794dd7120f7bee437007d898319424a11e59e8d/R/ml_utils.R#L97-L126

where we generate a (unique, monotonically increasing) ID column, perform the predict operation, and then re-order based on that ID. But we should very likely be doing the same for other column-reading operations as well.

**Comment by JohnMount** [comment]
Thanks for the crisp answers- having a clear statement of the limits makes it much easier to teach and work around them.

**Comment by kevinykuo** [comment]
@kevinushey Doesn't `sdf_read_column()` preserve row order? I thought we're just selecting + collecting?

**Comment by kevinushey** [comment]
I should elaborate -- what I mean is that `sparklyr` doesn't explicitly attempt to maintain row order with `sdf_read_column()`; it just calls Spark APIs as e.g.:

```
  def collectColumnDouble(df: DataFrame, colName: String): Array[Double] = {
    df.select(colName).rdd.map(row => {
       val element = row(0)
       if (element.isInstanceOf[Double]) element.asInstanceOf[Double] else scala.Double.NaN
    }).collect()
  }
```

For this to preserve row order, we have to assume that all of `select()`, `rdd()`, and `map()` methods preserve row order. If I understand correctly, we are safe in making this assumption but that isn't really explicitly documented anywhere on the Spark side.
