### ISSUE TITLE
sparkR on hives in secured environment

### ISSUE THREAD

**Issue by NatalieI** [rstudio/sparklyr#655]
I have R and sparkR package installed on hives (that's new to me), waiting to get RHive installed too,   Spark is running on those hive tables. Now, when I run  sc<-sparkR.init() it immediately tells me that spark submit command is not found
First i run library(sparkR),and then sc<-sparkR.init() and I thought that's sufficient. Still doesn't work. 
On the other hand, the hives tables are in secured environment. I have the credentials (IP, port and a database name). Should I somehow log in to that first via an R line? Also, is having RHive library absolutely mandatory in order to run sparkR? 
Any advice will be highly appreciated. 
Previously I ran R only on my local drive, so all these hive tables are new to me.

**Comment by kevinykuo** [comment]
@NatalieI this isn't the SparkR JIRA, but consider giving sparklyr a shot, see http://spark.rstudio.com/deployment.html ;)

**Comment by javierluraschi** [comment]
Closing this issue but yes, give `sparklyr` a shot 👍

**Comment by NatalieI** [comment]
OK Thanks!
