### ISSUE TITLE
Where are we setting the tbl_spark class?

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/sparklyr#659]
Quick noob question... I can't find any `class<-` calls in the code but we obviously have `tbl_spark` objects and methods. :S

**Comment by kevinushey** [comment]
You can see the constructors at e.g.

```
dplyr_spark.R
46:  tbl_sql("spark", src = src, from = from, ...)
53:  src <- src_sql("spark", src)
54:  tbl_sql("spark", src = src, from = from, ...)
```

Basically, the `tbl()` function from `dplyr` takes care of assigning the `tbl_spark` class in those calls.

**Comment by kevinykuo** [comment]
@kevinushey Thanks!
