### ISSUE TITLE
`collect.tbl_spark()` is in package description but says can't be found in console.

### ISSUE THREAD

**Issue by JosiahParry** [rstudio/sparklyr#66]
`> collect.tbl_spark()
Error: could not find function "collect.tbl_spark"`

but `?collect.tbl_spark()` brings up the documentation.

**Comment by javierluraschi** [comment]
@JosiahParry `collect.tbl_spark()` is an internal function, instead, we should always use `collect()` which is defined in `dplyr`.  Have you already run `library(dplyr)`?

**Comment by JosiahParry** [comment]
collect works. Based on documentation I thought `collect.tbl_spark()` was the equivalent for sparklyr. similar to how I would use `sdf_mutate()` potentially.

**Comment by javierluraschi** [comment]
removed collect.tbl_spark from docs since it's more adequate to read dplyr documentation.
