### ISSUE TITLE
Sparklyr::spark_read_csv connection to Google Cloud storage (gs://)

### ISSUE THREAD

**Issue by kuzeyCL** [rstudio/sparklyr#666]
Hello, 

is it possible to access csv files in Google Cloud storage and directly handover files from googleCloudStorageR to sparklyr? Because it is not possible to use (gs:// address)

Thanks!

**Comment by javierluraschi** [comment]
@kuzeyCL yes, but you need the right connector and configuration settings, by using something like:

```
conf$`sparklyr.shell.driver-class-path` <- "/usr/google/gcs/lib/gcs-connector-1.5.5-hadoop2.jar"
spark_connect(master = "", config = conf)
```

**Comment by javierluraschi** [comment]
The suggestion seems sufficient, closing. @kuzeyCL Feel free to open a new issue if this persists in your environment.
