### ISSUE TITLE
Sparklyr rename fails with dev version of dplyr

### ISSUE THREAD

**Issue by MZLABS** [rstudio/sparklyr#678]
Rename fails in Sparklyr, think it depends on verison of dplyr. Definitely seeing it in the dev version of dplyr as of 5-14-2017.

Submitted as [`Sparklyr` issue]() and [`dplyr` issue]().

``` r
# devtools::install_github("tidyverse/dplyr")
# devtools::install_github('tidyverse/dbplyr')
suppressPackageStartupMessages(library('dplyr'))
packageVersion("dplyr")
```

    ## [1] '0.5.0.9004'

``` r
library('sparklyr')
packageVersion("sparklyr")
```

    ## [1] '0.5.4'

``` r
if(requireNamespace("dbplyr", quietly = TRUE)) {
  packageVersion("dbplyr")
}
```

    ## [1] '0.0.0.9001'

``` r
R.Version()$version.string
```

    ## [1] "R version 3.4.0 (2017-04-21)"

``` r
dLocal <- data.frame(x = 1:2,
                     origCol = c('a', 'b'),
                     stringsAsFactors = FALSE)

sc <- sparklyr::spark_connect(version='2.0.2', 
   master = "local")

d <- copy_to(sc, dLocal, 'd')

# works
rename(dLocal, x2 = x, origCol2 = origCol)
```

    ##   x2 origCol2
    ## 1  1        a
    ## 2  2        b

``` r
# throws
rename(d, x2 = x, origCol2 = origCol)
```

    ## Source:     lazy query [?? x 2]
    ## Database:   spark_connection

    ## Error in names(select)[match(old_vars, vars)] <- new_vars: NAs are not allowed in subscripted assignments

``` r
spark_disconnect(sc)
rm(list=ls())
gc(verbose = FALSE)
```

**Comment by kevinykuo** [comment]
Replicated as of tidyverse/dplyr@c7ca374

**Comment by kevinykuo** [comment]
Seems to work if you `rename` one at a time.

**Comment by kevinushey** [comment]
The query looks fine to me:

```
> dbplyr:::sql_render(query)
<SQL> SELECT `x` AS `x2`, `origCol` AS `origCol2`
FROM `d`
```

Perhaps `sparklyr` just needs to provide its own `rename()` method to work around whatever is going on?

**Comment by kevinushey** [comment]
Hmm, it looks like whatever is going on is a bit more involed -- I'll try to take a deeper look soon...

**Comment by JohnMount** [comment]
Thanks for looking into this.  I just re-tested and the issue remains with `0.7.0` `dplyr` plus current (2017-06-09) `sparklyr`.  (`dbplyr`  changes depending which of `sparklyr` or `dplyr` is installed last.)  I did try to give `dplyr` a "heads-up" on this: [`dplyr` issue 2776](https://github.com/tidyverse/dplyr/issues/2776) to improve package to package coordination.

``` r
suppressPackageStartupMessages(library('dplyr'))
packageVersion("dplyr")
#> [1] '0.7.0'
library('sparklyr')
packageVersion("sparklyr")
#> [1] '0.5.5.9002'
if(requireNamespace("dbplyr", quietly = TRUE)) {
  packageVersion("dbplyr")
}
#> [1] '0.0.0.9001'
R.Version()$version.string
#> [1] "R version 3.4.0 (2017-04-21)"

dLocal <- data.frame(x = 1:2,
                     origCol = c('a', 'b'),
                     stringsAsFactors = FALSE)

sc <- sparklyr::spark_connect(version='2.0.2', 
                              master = "local")

d <- copy_to(sc, dLocal, 'd')

# works
rename(dLocal, x2 = x, origCol2 = origCol)
#>   x2 origCol2
#> 1  1        a
#> 2  2        b

# throws
rename(d, x2 = x, origCol2 = origCol)
#> Error in names(select)[match(old_vars, vars)] <- new_vars: NAs are not allowed in subscripted assignments
```

**Comment by JohnMount** [comment]
It may be related to this: [dplyr 2860](https://github.com/tidyverse/dplyr/issues/2860).

**Comment by javierluraschi** [comment]
I find this to be working correctly in `sparklyr devel`.

The cause seems to be related to `sparklyr` overriding `dplyr 0.5` feature to support `LIMIT` (see https://github.com/rstudio/sparklyr/blob/bugfix/hotfix-0.5.6/R/dplyr_spark_table.R#L3-L36); however, now that `dplyr 0.7` is released, we don't need this functionality and has already been removed.

The `sparklyr 0.6` release is not far away so my plan is to recommend using `sparklyr devel` both, as a way to help us test the upcoming `sparklyr` release and as a way to unblock issues like this one.

Can we close @JohnMount?

**Comment by JohnMount** [comment]
Sounds good to close to me.  Thanks for your support and caution.

**Comment by atroiano** [comment]
I am running into this issue with the following environment. I installed the dev version of sparklyr and it didn't resolve the issue.

   "R version 3.4.0 (2017-04-21)"
    packageVersion("sparklyr")
    [1] ‘0.5.6.9004’
   packageVersion("dplyr")
  [1] ‘0.7.1.9000’
