### ISSUE TITLE
How to read csv file with delimiter = ";" using spark_read_csv() ?

### ISSUE THREAD

**Issue by hiltonmbr** [rstudio/sparklyr#68]
Is possible to set options such as "delimiter" or "header" to read csv files?

**Comment by JosiahParry** [comment]
I got around this using the generic `read.csv()`, then used the `copy_to()`

**Comment by hiltonmbr** [comment]
It may be feasible to small csv files (< 4GB), but I have a very large CSV and it can't fit on memory RAM. Therefore, how to load CSV similar to: 
 df <- read.df(sc, file,
                  source = "com.databricks.spark.csv",
                  header="false",delimiter= ";",
                  nullValue="",treatEmptyValuesAsNulls="true",
                  inferSchema="true",charset="Latin1"
                   )
I'd like to get all improvement of com.databricks.spark.csv for large files controlling for header, delimiter, etc. 

Thanks.

**Comment by javierluraschi** [comment]
Thanks, this is a valid point. Let me address this as I would agree users would like to control this.

**Comment by hiltonmbr** [comment]
The same suggestion is valid to the function spark_write_csv, allowing to controlling for features such as header, delimiter, chartset, codec = "org.apache.hadoop.io.compress.CompressionCodec". 
https://github.com/databricks/spark-csv

**Comment by javierluraschi** [comment]
Added support for additional options, version `0.2.12` contains the additional parameters to read and write from csv.
