### ISSUE TITLE
sparklyr should install with github using only one command.

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#681]
Need to investigate why explicit installs have been reported while isntalling from github, as in:

```
install.packages(c("readr", "rappdirs", "rprojroot", "base64enc", "shiny", "DBI", "config"))
devtools::install_github("hadley/dbplyr")
devtools::install_github("rstudio/sparklyr")
```

when this should be sufficient:

```
devtools::install_github("rstudio/sparklyr")
```

**Comment by falaki** [comment]
Just tried without explicitly installing `dbplyr` from github and `sparklyr` installation from github worked fine. I still have to manually update all the other packages.

**Comment by kevinykuo** [comment]
I tried it on a fresh HDInsight instance maybe last week and it was a huge pain.

**Comment by javierluraschi** [comment]
This worked for me:

1. Create Amazon Linux AMI 2017.03.0 (HVM), SSD Volume Type - ami-c58c1dd3 instance.
2. Connect to the instance and run:

```
sudo yum-config-manager --enable epel
sudo yum install R
sudo yum install openssl-devel
sudo yum install libcurl-devel
sudo R
install.packages("sparklyr")
library(dplyr)
spark_install()
sc <- spark_connect(master = "local")
copy_to(sc, iris)
spark_disconnect(sc)
```

@falaki I investigated this as a follow up from your install instructions; however, was not able to hit this issue. If you have a consistent repro I would be happy to investigate more; otherwise, I would recommend we suggest installing `sparklyr` only with `devtools::install_github("rstudio/sparklyr")`.
