### ISSUE TITLE
converting string to datetime?

### ISSUE THREAD

**Issue by 3zhang** [rstudio/sparklyr#684]
I am using spark_read_csv to read a csv file. After loading the data, I want to convert a datetime column, which is character type currently, to a timestamp type. In SparkR I can use unix_timestamp to do this. But how can I acheive the same thing in sparklyr?

**Comment by kevinushey** [comment]
All of the functions defined in https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF are accessible in the `dplyr` interface, so you should be able to accomplish this with something like:

```
tbl %>% mutate(timestamp = unix_timestamp(column))
```

**Comment by 3zhang** [comment]
@kevinushey Thanks. Problem solved.
