### ISSUE TITLE
Problem connecting to Spark Stand Alone Cluster 

### ISSUE THREAD

**Issue by abjorling** [rstudio/sparklyr#687]
Hi!
I am trying to establish a connection to a Spark Stand Alone Cluster from RStudio Server using Spaklyr. My cluster is running on Ubuntu 16.04 server, Hadoop 2.7.3 (only running HDFS) and SPARK  2.1.0. RStudio Server is running on the Driver Node.

I have been following your "getting started" guide in ["sparklyr-cheatsheet" ](http://spark.rstudio.com/images/sparklyr-cheatsheet.pdf) below please see command used and the resulting error / logs:

> spark_connect(master="spark://10.0.0.108:7077", version = "2.0.1",spark_home = "/usr/local/spark-2.1.0-bin-hadoop2.7")

> Fejl i force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (7448): Gateway in port (8880) did not respond.
    Path: /usr/local/spark-2.1.0-bin-hadoop2.7/bin/spark-submit
    Parameters: --class, sparklyr.Backend, '/home/bdcluster/R/x86_64-pc-linux-gnu-library/3.4/sparklyr/java/sparklyr-2.1-2.11.jar', 8880, 7448

>  ---- Output Log ----
17/05/17 10:23:20 INFO sparklyr: Session (7448) starting
17/05/17 10:23:20 INFO sparklyr: Registering session (7448) into gateway port (8880)
17/05/17 10:23:20 INFO sparklyr: Waiting for registration of (7448) into gateway port (8880)
17/05/17 10:23:20 INFO sparklyr: Finished registration of session (7448) into gateway port (8880) with status (0)

>  Error Log ----

Have been going through the similar postings here, but so fare I have not come across a solution that have been able to fix this issue.  I am beginner in this field, so I hope that someone here can point me in the right direction - Thanks!

**Comment by javierluraschi** [comment]
The problem could be that something else might be using already port `8880`. Try using instead: 

```r
config <- spark_config()
config$sparklyr.gateway.port <- 8881
spark_connect(master="spark://10.0.0.108:7077",
              version = "2.0.1",
              spark_home = "/usr/local/spark-2.1.0-bin-hadoop2.7"
              config = config)
```

**Comment by abjorling** [comment]
Thank you for the help.
I actually managed to resolve this problem by downloading your latest package using devtool package as you also describe in your guide.....
