### ISSUE TITLE
Implementing functionality not available in older Spark versions

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/sparklyr#688]
If we write a function in e.g. `utils.scala` that depends on a Spark function not available before `2.0.0`, it won't compile when we build against `1.6`. We probably don't want to *not* implement newer features just because we support older versions. What's the best way to handle this and what should we do in the meantime?

**Comment by kevinushey** [comment]
Although we don't use this yet, my initial thought was to enable this through the use of a filter in the compilation spec:

https://github.com/rstudio/sparklyr/blob/d7ccc2e10a84eb69276a66c1bdf623ba645859c0/R/spark_compile.R#L50-L52

https://github.com/rstudio/sparklyr/blob/d7ccc2e10a84eb69276a66c1bdf623ba645859c0/R/spark_compile.R#L229-L263

The idea there being, we could add some custom filters that add / remove Scala files according to the version of Spark being compiled against.

I'm still not sure what the best way of organizing this would be though; e.g. do we want to have version-specific folders that add custom code for a particular version of Spark? E.g. what's some convention we could adopt that says, "use this code when compiling against Spark 2.0 only, use this code when compiling against Spark 2.0 and above", and so on.

**Comment by kevinykuo** [comment]
Since Scala doesn't support partial classes (i.e. splitting a class into different files), I wonder if we can do something like the following:

Have a `java/spark-1.6` folder with the current Scala code, but change objects to traits and append the version associated, e.g. `trait Utils16`. Then we'd have the same structure in `java/spark-2.0` but it would only contain the "diff" to include new methods. Now we'd have files under `java` for object declarations, e.g. `spark16.scala` might say `object Utils extends Utils16` and `spark20.scala` might say `object Utils extends Utils16 with Utils20`.

In the compilation spec we'd compile the folders with spark version up to the one each jar is built against, plus the file that declares the objects.

This assumes that we'll be able to resolve any breaking changes to the Spark API from one version to the next.

**Comment by kevinykuo** [comment]
@javierluraschi @kevinushey thoughts?

**Comment by kevinushey** [comment]
We could also just perform the indirection at the R level -- have a bunch of different versioned `Utils` objects, and figure out which one should be used at runtime with R, rather than dealing with Scala inheritance. Does that make sense?

In other words, from R, we just explicitly call e.g.

```
invoke_static(sc, "sparklyr.UtilsV2", ...)
```

where `UtilsV2` is a plain Scala object providing methods that require Spark 2.0.0 or above, and it is only compiled + used if the Spark version is 2.0 or greater. Does that make sense?

**Comment by kevinykuo** [comment]
@kevinushey Yeah this is definitely cleaner. Will put together a PR and we can discuss folder structure/naming.
