### ISSUE TITLE
How can I achieve "case when" in sparklyr?

### ISSUE THREAD

**Issue by 3zhang** [rstudio/sparklyr#689]
Function case_when is supported by dplyr, but seems that I cannot use it in sparklyr:

```
Error: org.apache.spark.sql.catalyst.parser.ParseException: 
mismatched input '~' expecting {')', ',', '.', '[', 'OR', 'AND', 'IN', NOT, 'BETWEEN', 'LIKE', RLIKE, 'IS', 'OVER', EQ, '<=>', '<>', '!=', '<', LTE, '>', GTE, '+', '-', '*', '/', '%', 'DIV', '&', '|', '^'}(line 1, pos 435)
```

**Comment by chezou** [comment]
It would be nice you to write the specific code you wrote.

**Comment by kevinykuo** [comment]
@3zhang `case_when()` was supported as of dbplyr 1.1.0 so we should be good here. Please reopen with reprex if you run into issues. Thanks!
