### ISSUE TITLE
Why ml_create_dummy_variables does not omit reference variable in sparklyr

### ISSUE THREAD

**Issue by celina-oliv** [rstudio/sparklyr#692]
I need to omit the reference dummy to avoid multicollinearity. I understand I should put the reference argument. As an example, I have a variable called "cnae2" with 5 levels where level 4 should be the reference and therefore should not appear a vector called cnae2_4.

```
load("~/bf_fe.RData") #dataframe R
bf_fe$cnae2=factor(bf_fe$cnae)
levels(bf_fe$cnae2)=c("1","2","3","4","5")

bf <- copy_to(sc,bf_fe) #spark dataframe
z=select(bf,cnae2,esc)

x=ml_create_dummy_variables(z,"cnae2",reference="4")

x
Source:   query [2.821e+06 x 7]
Database: spark connection master=local[8] app=sparklyr local=TRUE

Source:   query [2.821e+06 x 7]
Database: spark connection master=local[8] app=sparklyr local=TRUE

   cnae2   esc cnae2_1 cnae2_2 cnae2_3 cnae2_4 cnae2_5
   <chr> <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
1      4     4       0       0       0       1       0
2      4     3       0       0       0       1       0
3      4     3       0       0       0       1       0
4      4     4       0       0       0       1       0
5      4     3       0       0       0       1       0
6      4     4       0       0       0       1       0
7      4     3       0       0       0       1       0
8      4     3       0       0       0       1       0
9      4     4       0       0       0       1       0
10     4     3       0       0       0       1       0
# ... with 2.821e+06 more rows
```

**Comment by kevinushey** [comment]
Thanks! This appears to be a bug -- `sparklyr` should indeed drop the reference column when explicitly specified. As a workaround for now, you might just explicitly drop that column, e.g.

    x = select(x, -cnae2_4)

**Comment by celina-oliv** [comment]
Thank for reply! For now I'll use it. But if I have many factor variables to turn into dummies? Does not this function allow put more than one vector? For example:
```
d=c("cnae","esc","uf","cbo")
x=ml_create_dummy_variables(z,d)
```

**Comment by kevinushey** [comment]
Right, the function currently only accepts a single column name. As an alternative, you could just call this function repeatedly for each column you want to split:

```R
columns <- c("cnae","esc","uf","cbo")
for (column in columns)
  x <- ml_create_dummy_variables(x, column)
```

**Comment by celina-oliv** [comment]
Hello, i apreciate your help.
I followed your tip. My problem is that I have an id_worker vector with total of 169,099 and id_firm with total of 7,245, plus other variables. After creating these dummies I have spark.data.frame of 1,860,089 rows by 176.407 columns. Without the use of sparklyr, the only way to get this dataframe was with  sparse matrix, however when estimation of a lasso with cv.glmnet the pc stopped, it gave memory allocation problem, so I chose to use Sparklyr.

My big question is in the process of generating dummies that take about 8 hours and when it ends I can't access almost anything, the memory is totally occupied by a java process. I would like to know if there is anything I can configure at the beginning, in connection with spark, to speed up the process and not take up too much memory.

Please apologize for the lack of use of technical terms, my knowledge about programming is very limited.
Thanks for any help.

```
rm(list=ls(all=TRUE))
gc()
load("~/bf_fe.RData")

library(sparklyr)

 config <- spark_config()
 config$`sparklyr.shell.driver-memory` <- "64G"
 config$`sparklyr.shell.executor-memory` <- "64G"
 config$`spark.yarn.executor.memoryOverhead` <- "64G"
   
  config$`spark.driver.cores` <- 8
  config$`spark.executor.cores` <- 8
  config$`spark.executor.instances` <- 8
  config$`sparklyr.cores.local`<- 32
  config$`spark.sql.shuffle.partitions.local`<-32
   
  sc <- spark_connect(master = "local[8]", config = config)
  bf <- copy_to(sc,bf_fe)
 columns<-c("id_firm","uf","esc","cbo","estrang","branco","id_worker")

   for (column in columns)
     bf <- ml_create_dummy_variables(bf, column)

bf_d = dplyr::select(bf, -c(uf_11,esc_1,cbo_1,estrang_0,branco_0,id_worker_1,id_firm_1))

```
I need do this:
```
#lasso regression
    #formula
  
z<-c(colnames(bf_d[,c(3:5,27:ncol(bf_d))]))
  z<-paste(z,collapse = "+")   
  fz <- as.formula(paste("ln_w","~",z))
  
lasso=ml_linear_regression(bf_d, fz, intercept = TRUE, alpha = 1, lambda = 10)
  ```
But, i can't.   ```z  ```  take long time.

**Comment by kevinykuo** [comment]
@celina-oliv string indexing and one-hot encoding should be taken care of automatically when you call `ml_linear_regression()` if the column is a character (you may have to do something like `mutate(bf_fe, cnae2 = as.character(cnae2))`. The reference level is chosen by Spark (to be the most populated level) and there's no way to change it as of Spark 2.2.
