### ISSUE TITLE
Better printing of tbl_spark with jobjs

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/sparklyr#693]
Basically instead of showing a bunch of `<S3: spark_jobj>` can we print `jobj_info(x)$repr`?

We shouldn't need to pull apart columns with more "exotic" content just to be able to see them.

Would this be done through providing a `print.tbl_spark`?

**Comment by kevinushey** [comment]
I think we would accomplish this by implementing a `type_sum` method for `tbl_spark` objects. (The method is provided by `tibble`: https://github.com/tidyverse/tibble/blob/b4c590599804856e5502633657ba7eaaa4c5e940/R/type-sum.r#L43)

**Comment by kevinykuo** [comment]
Wow that was easy... I overlooked `type_sum` thinking it was just for column headers.
