### ISSUE TITLE
Documentation for `...` arg for `ml`.

### ISSUE THREAD

**Issue by JosiahParry** [rstudio/sparklyr#70]
`...	Other arguments passed on to methods.`

What are the other arguments we can pass?

**Comment by kevinushey** [comment]
The `...` arguments are actually unused at the moment, other than a 'secret' `only_model` parameter that's used to return a wrapper to the Spark model fitting object as opposed to the result of fitting the associated model with that object.

I'll amend the documentation to make that more clear.
