### ISSUE TITLE
Failed to detect version from SPARK_HOME

### ISSUE THREAD

**Issue by mubeenarasack** [rstudio/sparklyr#703]
sc <- spark_connect(master = 'Local', config = spark_config())
Error in spark_version_from_home(spark_home, default = spark_version) : 
  Failed to detect version from SPARK_HOME or SPARK_HOME_VERSION. Try passing the spark version explicitly. 

Can anyone help on this..thanks in advance

**Comment by kevinykuo** [comment]
Try `master = "local"` not `"Local"`

**Comment by mubeenarasack** [comment]
thanks ..but i am getting a new error now
rror in shell_connection(master = master, spark_home = spark_home, app_name = app_name,  : 
  Failed to connect to Spark (SPARK_HOME is not set).

**Comment by javierluraschi** [comment]
As Kevin points out, `master = "local"` is case sensitive. For the other issue, feel free to open a new issue with full connection being performed and output log to take a look. Thanks.
