### ISSUE TITLE
Support for Spark 2.1.0+

### ISSUE THREAD

**Issue by pcavatore** [rstudio/sparklyr#710]
Current version of sparklyr does not support Spark 2.1.0 and above yet.
When is that expected to happen?

sc <- spark_connect(master = "local")
Error in start_shell(master = master, spark_home = spark_home, spark_version = version,  : 
  sparklyr does not currently support Spark version: 2.1.0

**Comment by JohnMount** [comment]
I think the dev version supports 2.1.0 already.  I remember using it for a while after doing "devtools::install_github('rstudio/sparklyr')".  If I am remembering correctly, I remember it working quite well.

**Comment by edgararuiz** [comment]
Hi @pcavatore , I believe the latest patch that was submitted to CRAN does support 2.1.0.  Are you running sparklyr 0.5.5?

**Comment by pcavatore** [comment]
I was running 0.5.4...updated to 0.5.5 from source and it's working, thanks.
Any idea whether the correct ML API in use is SparkML rather the old MLlib?

**Comment by edgararuiz** [comment]
Yes, it's using ML.  It's very easy to check the API call it's using on a given model. Just pull up the R script that corresponds to the model you need, like here's the one inside `ml_linear_regression.R`: `envir$model <- "org.apache.spark.ml.regression.LinearRegression"`

**Comment by pcavatore** [comment]
Much appreciated @edgararuiz
