### ISSUE TITLE
Feature request: it would be very handy to have an official way to get table name and data source.

### ISSUE THREAD

**Issue by JohnMount** [rstudio/sparklyr#711]
Feature request: it would be very handy to have an official way to get table name and data source.

Below I have a reprex showing example implementations of the two functions I would like ( table_name and data_source ) with ad-hoc implementations that work by looking directly into the dplyr 0.5.0 data structures (obviously not the right way for external code, as this is unlikely to be stable across different data providers and sparklyr/dplyr versions).

The utility is: if you have handle to remote data you may want to delete the underlying data at some point as part of a clean up. The data_source has the additional use for copy_to as is already an option in the dplyr join verbs.

``` r
suppressPackageStartupMessages(library("dplyr"))
library("sparklyr")
my_db <- spark_connect(version='2.0.2', 
                       master = "local")
d <- copy_to(my_db, data.frame(x=1:3), 'dsparkname')

# would like a version of this function that works
# accross multiple dplyr data sources: 
#  Spark, PostgreSQL, RSQLite, ...
# should return NULL if d is local data (data.frame/ tibble)
# should return NULL if d is not a trivial query.
table_name <- function(d) {
  as.character(d$ops$x)
}

# would like a version of this function that works
# accross multiple dplyr data sources: 
#  Spark, PostgreSQL, RSQLite, ...
# should return NULL if d is local data (data.frame/ tibble)
data_source <- function(d) {
  d$src$con
}

# The above two functions would let us write
# code such as the following:

name <- table_name(d)
dataSource <- data_source(d)

db_drop_table(dataSource, name)

spark_disconnect(my_db)
```

**Comment by chezou** [comment]
It seems those functions should be responsible for dplyr, because they are not only for Spark dataframe.

**Comment by JohnMount** [comment]
Actually that sounds right (especially data source).  I've filed the issue there also.
