### ISSUE TITLE
How about creating the issue template?

### ISSUE THREAD

**Issue by chezou** [rstudio/sparklyr#712]
Just a proposal to reduce of costs of interaction to solve many issues. It would be nice to have our issue template to clarify specific problem. 
See also: https://github.com/blog/2111-issue-and-pull-request-templates

In [my project](https://github.com/chezou/tabula-py/blob/master/.github/ISSUE_TEMPLATE.md), I request environmental info, issue summary, example code, output and what intend to be. That works fine for me.

Feel free to close if this proposal doesn't much to sparklyr.

**Comment by kevinushey** [comment]
I think this is a great idea -- we should definitely get an issue template for `sparklyr`.
