### ISSUE TITLE
Copying a vector to Spark builds a copy of the vector for each row instead of using vector as a column

### ISSUE THREAD

**Issue by MZLABS** [rstudio/sparklyr#717]
Copying a vector to Spark builds a copy of the vector for each row instead of using vector as a column.

``` r
# set up
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
#> [1] '0.5.0'
library("sparklyr")
packageVersion("sparklyr")
#> [1] '0.5.5'
sc <- sparklyr::spark_connect(version='2.0.2', 
                              master = "local")
d <- data.frame(x=1:3)
v <- c(2,3,2)

# expected behavior
d %>% 
  mutate(y=v)
#>   x y
#> 1 1 2
#> 2 2 3
#> 3 3 2

# Sparklyr vector behavior
dS <- copy_to(sc, d)
res <- dS %>%
  mutate(y=v) %>%
  collect()
res$y[[1]]
#> <jobj[29]>
#>   class org.apache.spark.sql.catalyst.expressions.GenericRowWithSchema
#>   [2.0,3.0,2.0]

# clean up
spark_disconnect(sc)
```

**Comment by kevinushey** [comment]
The problem here is that `dbplyr` generates this sort of query here:

```
> sql_render(res)
<SQL> SELECT `x`, (4, 5, 6) AS `y` FROM `df`
```

Is there a Spark SQL equivalent for creating a column with raw data?

**Comment by kevinykuo** [comment]
I think this is expected SQL behavior but can be confusing for R users... maybe file in dplyr?

**Comment by MZLABS** [comment]
I've filed this as dplyr issue 2830 https://github.com/tidyverse/dplyr/issues/2830 .

**Comment by javierluraschi** [comment]
`dplyr` has the last say here since `sparklyr` provides a backend but does not try to extend `dplyr` functionality, closing.

BTW. In more recent versions of `sparklyr` we collect StructFields so this now produces:

```r
res <- dS %>%
     mutate(y=v) %>%
     collect()
res$y[[1]]
```
```[[1]]
[1] 2

[[2]]
[1] 3

[[3]]
[1] 2
```
