### ISSUE TITLE
How to enable mode overwrite or append in spark_write_parquet() function?

### ISSUE THREAD

**Issue by hiltonmbr** [rstudio/sparklyr#72]
Dear @javierluraschi,  would you mind adding support for options such as overwrite or append in spark_write_parquet() function?

On the other hand, spark_read_parquet() allows users controlling for mergeSchema = "true" or mergeSchema = "false"? I think it is an important option due to schema evolution in many data bases along time, starting with a simple schema, and gradually adding more columns to the schema as needed. The function loadDF in SparkR package allows users set the option mergeSchema, keeping it false by default. http://spark.apache.org/docs/latest/sql-programming-guide.html#schema-merging

Thanks.

**Comment by javierluraschi** [comment]
Closing since the suggested parquet options are now implemented. @hiltonmbr: let us know if you find something missing or not working as you would expect regarding the `options` and `mode` parquet parameters.
