### ISSUE TITLE
Add support for distributing/installing packages with `spark_apply`

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#729]
The following code works fine in a local installation:

```{r}
library(sparklyr)
library(stringr)
sc <- spark_connect(master = "local", version = "2.1.0")
iris_tbl <- copy_to(sc, iris)

iris_tbl %>% select("Species") %>% spark_apply(function(row) stringr::str_count(row, "a"))
```

```
# Source:   table<sparklyr_tmp_f89733580a95> [?? x 1]
# Database: spark_connection
   Species
     <int>
 1       1
 2       1
 3       1
 4       1
 5       1
 6       1
 7       1
 8       1
 9       1
10       1
# ... with 140 more rows
```

This also works fine under `master = "yarn-client"`, etc. as long as the cluster has the correct package versions installed; however, if the cluster lacks this package, execution will fail.

A possible workaround for some clusters/packages would be to check installation directly under the closure:

```{r}
iris_tbl %>% select("Species") %>% spark_apply(function(row) {
  if (!"stringr" %in% rownames(installed.packages())) install.packages("stringr")

  stringr::str_count(row, "a")
})
```

This is obviously not ideal and therefore, a better mechanism for distributing packages is necessary.

**Comment by datalee** [comment]
good, i also need this function.

**Comment by datalee** [comment]
> iris_tbl %>% select("Species") %>% spark_apply(function(row) stringr::str_count(row, "a"))
# Source:   table<sparklyr_tmp_13995d56e12f> [?? x 1]
# Database: spark_connection
  Species
    <int>
1       0

why ?

**Comment by javierluraschi** [comment]
Distributing packages is supported now, see https://blog.rstudio.com/2017/07/31/sparklyr-0-6/.

@datalee the code provided is equivalent to running:

```r
iris %>% select("Species") %>% stringr::str_count("a")
```

which also returns:

```
[1] 0
```

Since `stringr` works with vectors, not data frames, in this case what we probably need is:

```
iris_tbl %>% select("Species") %>%
  spark_apply(function(row) stringr::str_count(row$Species, "a"))
```

To validate, we can run this locally with `dplyr` as follows:

```r
iris_str <- iris %>% 
  pull(Species) %>%
  stringr::str_count("a")

data.frame(Species = iris_str) %>%
  group_by(Species) %>%
  count()
```
```
# A tibble: 2 x 2
# Groups:   Species [2]
  Species     n
    <int> <int>
1       0    50
2       1   100
```

which matches the `spark_apply()` computation,

```r
iris_tbl %>%
  select("Species") %>%
  spark_apply(function(row) stringr::str_count(row$Species, "a")) %>%
  group_by(Species) %>%
  count()
```
```
# Source:   lazy query [?? x 2]
# Database: spark_connection
# Groups:   Species
  Species     n
    <int> <dbl>
1       1   100
2       0    50
```
