### ISSUE TITLE
How to connect to spark?

### ISSUE THREAD

**Issue by yoonespi** [rstudio/sparklyr#73]
I installed packages sparklyr and dplyr and added a Spark pane.
But I can't connect to spark

> library(sparklyr)
> library(dplyr)
> sc <- spark_connect(master = 'local')
Error in identical(scon$sconRef, NULL) : object 'scon' not found

How can I do?
Thank you.

**Comment by javierluraschi** [comment]
@yoonespi are you connecting into a local cluster or remote cluster that someone already installed for you?

Are you connecting through the RStudio UI? If you are, which version of RStudio you have?

If it's a local cluster, have you already run `spark_install()`?

If this still doesn't work, please let us know: operating system and version.

**Comment by yoonespi** [comment]
I tried to connect through latest version RStudio 0.99.1249.
spark version : 1.6.1
Hadoop version : 2.6
It dose not work.

**Comment by javierluraschi** [comment]
@yoonespi which operating system?

**Comment by kevinushey** [comment]
My guess here is that the `sparklyr` / `sparkapi` packages need to be updated / reinstalled.

**Comment by javierluraschi** [comment]
@yoonespi we've removed this code so you won't be hitting this particular issue anymore.

However, please open a new issue if you can't connect still and attach the output of `spark_log(sc)` for us to be able to provide a workaround or fix.

This one is a duplicate issue from: https://github.com/rstudio/sparklyr/issues/85 - Closing
