### ISSUE TITLE
Support ML pipelines

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/sparklyr#734]
This seems relatively straightforward... except for the naming scheme. For example, what do we call the function that creates a `LogisticRegression`?

Related: https://github.com/rstudio/sparklyr/issues/593

cc @kevinushey @chezou

**Comment by peddollakishore** [comment]
Hi All

i am connected to spark standalone cluster but when i am importing data from cassandra its keep on waiting stage please help on this, bellow is the code..

library(pipeR)
library(sparklyr)
library(dplyr)

Sys.setenv(SPARK_HOME='/home/ubuntu/spark')
sc <- spark_connect(master = "spark://XXXXXXXXX:7077")
Executed

sparkSession <- invoke_static(sc, "org.apache.spark.sql.SparkSession", "builder") %>>%
invoke("config", "spark.cassandra.connection.host", "XXXXXXXX:9042") %>>%
invoke("getOrCreate")
Executed

cass_df <- invoke(sparkSession, "read") %>>%
invoke("format", "org.apache.spark.sql.cassandra") %>>%
invoke("option", "keyspace", "test") %>>% invoke("option", "table", "kv") %>>%
invoke("load")
Executed

bbh_tbl <- sparklyr:::spark_partition_register_df(sc, cass_df, "bbh", 1, TRUE)
Waiting...........

**Comment by kevinushey** [comment]
Can you elaborate a bit more? Based on #593, it seems like there's two main paths forward:

1. Provide a function like `spark_pipeline()`, that accepts an array of `PipelineStage` objects,
2. Provide something like `spark_array()` that can be used to explicitly construct a Spark array of 'stuff'.

I'm marginally in favor of 1), but curious whether you have something separate in mind.

**Comment by kevinykuo** [comment]
@kevinushey I'm aligned with you here, but am thinking it'd be nice to have syntactic sugar for making the `PipelineStage` objects. E.g. instead of writing

```
lr <- invoke_new(sc, "org.apache.spark.ml.classification.LogisticRegression") %>%
  invoke("setMaxIter", ensure_scalar_integer(10))
```

the user can write something like

```
lr <- ???_logistic_regression(sc, max_iter = 10L)
```

where `???` is the prefix for this type of function, and we'd have nice print methods for them.

**Comment by kevinushey** [comment]
Ahh, got it. Perhaps we want something like:

```
spark_linear_regressor()
spark_logistic_regressor()
```

That is, use the `spark_` prefix to help make it somewhat more clear that these create Spark (JVM) objects that are mainly intended for lower-level usages, and change the form of the function name (when appropriate) to make it more clear that this is defining / creating an object, and not immediately defining + training a model.

**Comment by kevinykuo** [comment]
Tracking in #944
