### ISSUE TITLE
sparklyr/RStudio reports error on dplyr::copy_to()

### ISSUE THREAD

**Issue by JohnMount** [rstudio/sparklyr#747]
When I run the follow reprex I always see the message "Error: Column `database` must be length 1 or 1, not 0".  Doesn't seem to get printed in the reprex (so I think it is a Spark error demoted to a warning or a message which is not printed).

```r
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
#> [1] '0.7.0'
suppressPackageStartupMessages (library("sparklyr"))
packageVersion("sparklyr")
#> [1] '0.5.6'
sc <- spark_connect(master= 'local',
                    version = '2.1.0')
d <- data.frame(x=1:9,
                y=rep(c('a','b','c'),3))
d <- copy_to(sc, d, 'd')
##>> Error: Column `database` must be length 1 or 1, not 0
```

The error is in the RStudio Spark viewer.  Pressing refresh on the viewer repeats the error with a message pop-up on RStudio saying "Error R code execution error."  RSTudio version: 1.0.143 .

**Comment by ray-p144** [comment]
If you install the current dev version of the package this error is fixed. I'm not sure why the fix hasn't been implemented on the release versions but you can do this for now:
```r
devtools::install_github("rstudio/sparklyr", ref = "master");
```
Also see #477

**Comment by randomgambit** [comment]
@ray-p144 I am using 86_64-ubuntu14-linux-gnu (64-bit), how can I get the development version of sparklyr? I cannot have devtools installed....

Thanks!

**Comment by randomgambit** [comment]
the reason why I am asking is that I get the same error with `0.5.6` on Cran .. Thanks!

**Comment by kevinykuo** [comment]
@randomgambit does `install.packages("devtools")` not work for you or is your sysadmin not willing to install the linux dependencies?

**Comment by randomgambit** [comment]
@kevinykuo  thanks for your help ! its hard to get anything installed on my machine. 

I can, however, install any package I want using the install from local file options in `RStudio`. In windows, I would use the development tarballs on CRAN but I dont find anything for linux... Do you see any solution here?

**Comment by randomgambit** [comment]
yeah just to be clear. sysadmin not willing to install the depedencies...

**Comment by kevinykuo** [comment]
@randomgambit RStudio desktop or server?

**Comment by randomgambit** [comment]
@kevinykuo I believe its the linux server version

**Comment by kevinykuo** [comment]
@randomgambit See if this works:

1. Download the source as zip from this repo
2. Upload to your home directory via the RStudio interface
3. Open the `sparklyr` project
4. Build -> Build and reload

**Comment by randomgambit** [comment]
@kevinykuo amazing!!! thanks. thats working now. the error is fixed on my side.

**Comment by javierluraschi** [comment]
Thanks @kevinykuo!

**Comment by AdityaAshima** [comment]
I tried executing the solutions provided here but it didnt work out. Please help me with better solutions

iris_tbl<-copy_to(sc,iris)
Error: Column `database` must be length 1 or 1, not 0   


Sessioinfo:-
 sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.2     withr_1.0.2     memoise_1.1.0   digest_0.6.12   devtools_1.13.2
