### ISSUE TITLE
error when converting millisecond timestamps?

### ISSUE THREAD

**Issue by randomgambit** [rstudio/sparklyr#754]
Hello,

I am using more and more this amazing package for data analysis!
 I loaded a dataframe with `spark_read_csv` and the data looks like

```
# Source:   table<df> [?? x 32]
# Database: spark_connection
 NAME       Date        
<chr>       <chr>       
1  AA 2011-03-01T00:00:04.226Z 
```

I want to convert the Date string to a timestamp, and change its timezone.

I am able to do use the Hive date functions (https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF#LanguageManualUDF-DateFunctions) by typing

 `mutate( mytime = unix_timestamp(Date,  "yyyy-MM-dd'T'hh:mm:ss.SSS'Z'") )` that gives me back `1298955604`

However, I dont get how I can change the timezone or even get a `Timestamp` type back. 

All of these solution below fail. 

```
df %>%
  mutate(myminute = hour(mytime)) 

```
`Error: org.apache.spark.sql.AnalysisException: cannot resolve 'hour(rxsbltsgvb.`mytime`)' due to data type mismatch: argument 1 requires timestamp type, however, 'rxsbltsgvb.`mytime`' is of bigint type.; line 1 pos 296;`

``` 
df %>%
  mutate(myminute = from_utc_timestamp(mytime, 'UTC'))

df %>%
  mutate(myminute = as.POSIXct(mytime))

```
This is puzzling. Indeed,  `from_utc_timestamp` should accept primitive types such as BigInt

Any ideas? Being able to process timestamps in Spark is extremely important to me.
Many thanks!

**Comment by randomgambit** [comment]
@kevinushey @kevinykuo sorry to bring you in, but I believe this is an important issue for everyone involved with big datasets and timestamp variables. Could you please have a quick look an tell me if something is wrong here? Why can't I call these date functions?

Thanks!!!

**Comment by kevinushey** [comment]
Although I don't quite know the underlying reason why this isn't working as-is, it looks like you can explicitly convert arguments to timestamps and then construct using that, e.g.

```R
library(dplyr)
library(sparklyr)
sc <- spark_connect(master = "local", version = "2.1.0")

df <- data.frame(dtime = as.numeric(Sys.time()))
tbl <- copy_to(sc, df, overwrite = TRUE)
tbl %>%
  mutate(time = from_utc_timestamp(timestamp(dtime), "UTC"))
```

Is that sufficient for you here?

**Comment by randomgambit** [comment]
switched `regexp_extract` with `regexp_replace`. Still does not work...

**Comment by kevinushey** [comment]
It looks like backslashes need to be double-escaped (not yet sure why), e.g.

```
tbl %>%
  mutate(time = from_utc_timestamp(timestamp(dtime), "UTC")) %>%
  mutate(chartime = as.character(time)) %>%
  mutate(year = regexp_extract(chartime, '(\\\\d+)'))
```

**Comment by alexanderchernyakovgithub** [comment]
@kevinushey: i see you are using the timestamp function.. where is the doc for that? it doesn't seem to be listed in the Hive UDF docs and it also seems the only way to convert a string in the  "YYYY-MM-DD HH:MM:SS.fffffffff" format to an actual TimestampType

**Comment by kevinykuo** [comment]
@alexanderchernyakovgithub see https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF

**Comment by alexanderchernyakovgithub** [comment]
@kevinykuo already saw this page: timestamp isn't a function listed on there unless i'm being terribly dense

**Comment by kevinykuo** [comment]
@alexanderchernyakovgithub yeah doesn't seem like that function is documented, my guess is that it's SQL for casting to timestamp. BTW what's the string that's giving you trouble? Have you tried using the format string `"yyyy-MM-dd HH:MM:SS"`?

**Comment by alexanderchernyakovgithub** [comment]
@kevinykuo  yes, i think you are right.. the way to convert back to strings seems to be `string()` which is also undocumented. i think what must be happening internally is that they are casting. thanks for taking a look. i wonder where @kevinushey knew to use the function from

**Comment by kevinushey** [comment]
Good question! I can't remember where I found it; but I do recall seeing it in some of Spark's own code, e.g. https://github.com/apache/spark/blob/7f2e62ee6b9d1f32772a18d626fb9fd907aa7733/sql/core/src/test/resources/sql-tests/inputs/inline-table.sql#L50-L51
