### ISSUE TITLE
R code execution error - Error: Column 'database' must be length 1 or 1, not 0

### ISSUE THREAD

**Issue by sutapunt** [rstudio/sparklyr#758]
I tried to use R programming by using RStudio_Server_1.0.143, spark-2.1.1-bin-hadoop2.7, and sparklyr_0.5.6. When I'm running the code

library(sparklyr)
library(dplyr)
library(ggplot2)

Sys.setenv(SPARK_HOME="/usr/local/spark")
config <- spark_config()

sc <- spark_connect(master = "yarn-client", config = config)
spark_read_csv(sc, name="palo", path = "/inputs/palo-alto/201612.csv", header = TRUE)

I got the error 'R code execution error' - Error: Column 'database' must be length 1 or 1, not 0

I tried to search on the website for solutions and tried to update sparklyr, dplyr, and also tibble to latest version as recommendation on the website, but I still got error.

Here is my sessionInfo():

![1](https://user-images.githubusercontent.com/29476745/27218469-72806974-52a8-11e7-86fb-fa6008517ab4.jpg)

Here is error:

![10](https://user-images.githubusercontent.com/29476745/27218938-130739b2-52aa-11e7-8af2-fb586ae1dc20.jpg)

However, when I try to run R via terminal. No error occurred.

Here the result from terminal:

![11](https://user-images.githubusercontent.com/29476745/27218931-0d57dc88-52aa-11e7-8303-4c4fbedbd053.png)

Any suggestion?
Many Thanks...

Note:
My environment has no internet connection, when I updated the sparklyr, dplyr, and others. I download the latest version and related packages from CRAN and used the following command to update it.

library(tools)
write_PACKAGES("/home/hdmaster/Downloads/library")
install.packages("sparklyr",contriburl = "file:/home/hdmaster/Downloads/library")

**Comment by randomgambit** [comment]
I am getting the same error using Rstudio. Related https://github.com/rstudio/sparklyr/issues/477 and https://github.com/rstudio/sparklyr/issues/747

**Comment by sutapunt** [comment]
I got it, the problem is fixed...

For offline site, follow this instructions.

![1](https://user-images.githubusercontent.com/29476745/27267497-1285cbfe-54d3-11e7-99bb-8dafdbbfd66b.jpg)

**Comment by javierluraschi** [comment]
Right, this has been fixed in the `sparklyr` development version, we will try to get this version to CRAN soon, thanks for reporting this!
