### ISSUE TITLE
How to overwrite a spark dataframe?

### ISSUE THREAD

**Issue by 3zhang** [rstudio/sparklyr#759]
As a R user, I really don't know how to do this.

```
iris1=copy_to(sc,iris,overwrite=T)
iris2=mutate(iris1,V1=Sepal_Length+1,V2=paste0(Species,Species))
sdf_register(iris2,'iris')
tbl_cache(sc,'iris')
```

I supposed the above code could overwrite the original iris table. But it just created a new one. Now I can see two iris tables with the same table name (iris) in Spark UI (storage tab) but with different memory sizes. This indicates that they are two different objects.
So how can I overwrite my computation result into the original table?

**Comment by randomgambit** [comment]
I think it is an interesting question. I am still confused by the differences between `sdf_register` and `copy_to`. Aren't we creating a `Spark` dataframe in both cases?

**Comment by kevinushey** [comment]
`sdf_register()` takes an existing Spark DataFrame (as a raw jobj) and wraps it up in a `tbl` object suitable for use with `dplyr` (which involves calling `registerTempTable()` behind the scenes). `copy_to()` copies a local `data.frame` to Spark, and then does the same registration work as `sdf_register()`.

I didn't realize that attempting to register multiple tables with the same name would actually generate duplicates (I assumed it would overwrite the old one).

Perhaps we should call `dropTempTable()` before registering that table?

**Comment by randomgambit** [comment]
I see @kevinushey 

then, would this be another way to create a Spark Dataframe suitable for use with `dplyr`?

**Comment by kevinushey** [comment]
Yes, I think that's exactly fine -- `sparklyr` should be doing something similar behind the scenes with `sdf_register()` and friends.

**Comment by randomgambit** [comment]
@kevinushey @3zhang  

Here is a more general problem. suppose `myfile` is a list of files.

```
for (i in i:10){
 df <- spark_read_json(sc,myfile[i],
                        repartition = 0,
                        name = "df", 
                        memory = FALSE,
                        overwrite = TRUE)
  spark_write_parquet(df,myfile[i], mode = "overwrite" )
}
```
will keep using the same file (the first one) unless one adds:

 ` dplyr::db_drop_table(sc, "df")` at the end of each loop

**Comment by randomgambit** [comment]
well I thought it would work.. it doesnt apparently. Still getting the same parquet file being writted over and over again

**Comment by javierluraschi** [comment]
I don't see any issue, am I missing something? This is what I tried:

```r
json_files <- c("iris-setosa.json", "iris-versicolor.json")
parquet_files <- c("iris-setosa.parquet", "iris-versicolor.parquet")

iris %>% filter(Species == "setosa") %>% jsonlite::write_json(json_files[1])
iris %>% filter(Species == "versicolor") %>% jsonlite::write_json(json_files[2])

for (i in 1:2){
  df <- spark_read_json(sc,json_files[i],
                        repartition = 0,
                        name = "df", 
                        memory = FALSE,
                        overwrite = TRUE)
  spark_write_parquet(df, parquet_files[i], mode = "overwrite")
}
```

Then these files look correct:

```
spark_read_parquet(sc, "x1", parquet_files[[1]])
# Source:   table<x1> [?? x 5]
# Database: spark_connection
   Petal.Length Petal.Width Sepal.Length Sepal.Width Species
          <dbl>       <dbl>        <dbl>       <dbl>   <chr>
 1          1.4         0.2          5.1         3.5  setosa
 2          1.4         0.2          4.9         3.0  setosa
```

```
spark_read_parquet(sc, "x2", parquet_files[[2]])
# Source:   table<x2> [?? x 5]
# Database: spark_connection
   Petal.Length Petal.Width Sepal.Length Sepal.Width    Species
          <dbl>       <dbl>        <dbl>       <dbl>      <chr>
 1          4.7         1.4          7.0         3.2 versicolor
 2          4.5         1.5          6.4         3.2 versicolor
```

**Comment by javierluraschi** [comment]
Closing, but feel free to open a new one or comment back if we are missing something, thanks!
