### ISSUE TITLE
filter() not working in sparklyr after a group-by?

### ISSUE THREAD

**Issue by randomgambit** [rstudio/sparklyr#760]
Hello,

I am reading a csv using `spark_read_csv` and it seems I cannot use the filter function. What I am trying to do is simple, group by a character variable and take the first observation is each group

```
> df
# Source:   lazy query [?? x 1]
# Database: spark_connection
         Date
         <chr>
 1 08-JUL-2016
 2 08-JUL-2016
 3 08-JUL-2016
 4 08-JUL-2016
 5 08-JUL-2016
 6 08-JUL-2016
```

Unfortunately

```
df %>% group_by(Date) %>% filter(row_number() == 1) 
Error: org.apache.spark.sql.AnalysisException: Window function row_number() requires window to be ordered, please add ORDER BY clause.
```

and 

```
> df %>% group_by(Date) %>% slice(1L)
Error in slice_.tbl_spark(.data, .dots = compat_as_lazy_dots(...)) : 
  Slice is not supported in this version of sparklyr
```

are these bugs? Am I missing something? I am using the latest versions

`dbplyr_1.0.0    lubridate_1.5.6 h2o_3.10.4.8    dplyr_0.7.0     sparklyr_0.5.6  MKLthreads_0.1 `

Thanks!

**Comment by randomgambit** [comment]
Specifying a variable in `row_number()` seems to work without errors but then the output of the filtering depends on which variable is chosen. 

That is, `filter(row_number(another_var) == 2)` will return the second non-missing row for another_var, which is not what I want. I want the second row irrelevant of missing values anywhere..

Thanks!!

**Comment by randomgambit** [comment]
found out a working solution. One MUST  use `dplyr::arrange()` before `row_number()`. Is that expected?

**Comment by kevinykuo** [comment]
@randomgambit ordering is tricky in databases and especially in Spark, see e.g. https://issues.apache.org/jira/browse/SPARK-16207. It's safer to sort before you filter if you know the ordering you want.
