### ISSUE TITLE
Consider to standardizecolumn names used for the generated probability / predicted columns

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#762]
From @nathan: Here are three outputs of sdf_predict for logistic, decision trees, and neural net respectively. Notice that prediction is different for logistic and decision trees. Notice there is no probability column for neural nets. Spark ML is creating different output formats based on the model:

![image 1](https://user-images.githubusercontent.com/3478847/27246215-e325b0a2-52a4-11e7-9407-f2b4b7a1c67f.png)

![image 2](https://user-images.githubusercontent.com/3478847/27246216-e3283e26-52a4-11e7-8ebc-86353c9e743b.png)

![image 3](https://user-images.githubusercontent.com/3478847/27246217-e32ac31c-52a4-11e7-90fc-54ded9a45705.png)

I think "prediction" is correct. The change would have to be on the tree based classifiers. The "prediction" column should be called "probability".

**Comment by kevinykuo** [comment]
Closing, this should be addressed in #937
