### ISSUE TITLE
ChangeFileModeByMask error 

### ISSUE THREAD

**Issue by mubeenarasack** [rstudio/sparklyr#767]
Hi

I have executed the code below 
 sc <- spark_connect(master = "local", version = "1.6.2")

 I got the error message
"ChangeFileModeByMask error (5): Access is denied."

But if  I am executing the same again it will show 
"Re-using existing Spark connection to local"

I dont know why it occuring always..Can anyone help me.Thanks in advance

**Comment by javierluraschi** [comment]
@mubeenarasack looks like you might have to manually change the execution permissions of say, `spark-submit2` for windows or `spark-submit` for linux.

`file.path(sparklyr::spark_home_dir(), "bin")` should give you the path to `spark-submit` and `spark-submit2`, then make sure both are readable and executable.

There is some info [here](https://stackoverflow.com/questions/36168135/running-spark-on-windows-error-5-access-denied-even-when-running-as-admin), hope this helps.
