### ISSUE TITLE
Sys.getenv('SPARK_HOME') returns empty string

### ISSUE THREAD

**Issue by dwy904** [rstudio/sparklyr#769]
I tried to connect to local spark cluster, but it fail to connect because the default code could not find my spark_home directory. 

When I tried typing:
**Sys.getenv('SPARK_HOME')** , it returns a empty string.

In order to connect to spark I have to manually type this everytime:

**sc <- spark_connect(master = "local", config = config, spark_home = '~/Library/Caches/spark/spark-1.6.2-bin-hadoop2.6')**

The default code works before I install the newest edition of sparklyr a few days ago by typing:
**devtools::install_github("rstudio/sparklyr"**

I am wondering if there's any alternative way to fix this.

**Comment by kevinykuo** [comment]
@dwy904 try updating sparklyr again; a fix was merged yesterday.

**Comment by dwy904** [comment]
Thank you so much, it works now.
