### ISSUE TITLE
Creating new tbl with `sdf_partition()` doesn't show up in spark environment.

### ISSUE THREAD

**Issue by JosiahParry** [rstudio/sparklyr#77]
```
absences_tbl <- absences_tbl %>% mutate(avg_score = (G1 + G2 + G3)/3)

# create binary
absences_tbl <-  absences_tbl %>% sdf_mutate(p_live_together = ft_string_indexer("Pstatus"), 
                                             school_index = ft_string_indexer("school"),
                                             sex_index = ft_string_indexer("sex")) 


# using sparklyr to partition data
partition_tbl <- sdf_partition(absences_tbl, training = 0.75, test = 0.25, seed = 0)
```

A couple things regarding this. The changes to the table do not show up in the environment, they're there and can use them in creating a model, just not visible. 

Secondly I can create the `partition_tbl`, it exists, just not in the spark environment.

In addition any way to select a single column without having to use `df %>% filter()`? Perhaps like `df[ ,x]`?

**Comment by slopp** [comment]
Behind the scenes two different APIs are being used. In the mutate statement we use Spark SQL, but in the ft_* commands we use Spark Transformers.

To explicitly see the result of a Spark Transformer in the environment you have to register the table use sdf_register().

sdf_partition returns an object with two tables, train and test. Please see the docs for an example.

Currently, to select a single column you would use the dplyr command select(col_name) as opposed to filter.

**Comment by JosiahParry** [comment]
Okay, so after using `sdf_mutate()` I would pipe results to `sdf_register()`?

Like:
```
absences_tbl <-  absences_tbl %>% sdf_mutate(p_live_together = ft_string_indexer("Pstatus")) %>%
                                                            sdf_register()
```

**Comment by slopp** [comment]
Correct, but you also would supply a name argument for the table, ie:

`absences_tbl <-  absences_tbl %>% sdf_mutate(p_live_together = ft_string_indexer("Pstatus")) 
%>% sdf_register("absences")`

**Comment by JosiahParry** [comment]
Perf. You're the man. Loving this package. WAYYYY more accessible than SparkR.

**Comment by JosiahParry** [comment]
Perhaps the partition function should automatically pipe to sdf_register?

**Comment by kevinushey** [comment]
We didn't want to automatically register tables generated by `sdf_partition` as one might generate many temporary tables that they don't necessarily want to see e.g. in the Spark pane of RStudio.

We might revisit this in the future, but I think this is an acceptable compromise for now.

**Comment by kevinykuo** [comment]
Users should explicitly register results of `sdf_partition()` if they want to. Closing.
