### ISSUE TITLE
full_join does not support cartesian

### ISSUE THREAD

**Issue by statmatt** [rstudio/sparklyr#771]
See example:

```paramgrid <- sdf_register(sdf_import(data.frame(gridcell = (1:n_paramgrid)), sc, repartition=n_paramgrid), "paramgrid");```

```iters <- sdf_register(sdf_import(data.frame(iter = (1:n_iter)), sc, repartition=n_iter), "iters");```

```
paramgrid %>% full_join(iters)
```
the final statement should produce the cartesian product of all rows in paramgrid and all rows in iter; today it fails with an error bc the by= parameter is not set.

**Comment by javierluraschi** [comment]
Unsupported by `dplyr`, opened https://github.com/tidyverse/dplyr/issues/2924, proposing PR as well.

**Comment by javierluraschi** [comment]
I'm going to close this one since we can track this in `dplyr` now tidyverse/dplyr#2924, PR proposed: https://github.com/tidyverse/dbplyr/pull/24.
