### ISSUE TITLE
Specify temp directory in spark_connect()

### ISSUE THREAD

**Issue by TaylorAndrew** [rstudio/sparklyr#78]
I'm running on a corporate machine that is connected to a couple non-writable drives.

When I run:

    library(sparklyr)
    library(dplyr)
    sc <- spark_connect(master = "local")

It tries this:
    
    Created default hadoop bin directory under: M:\tmp\hadoop

This is a non-writable directory. Is there any way to specify a temp directory to create default hadoop bin in?

**Comment by javierluraschi** [comment]
@TaylorAndrew yes in Spark, but sparklyr currently doesn't provide any helpers to make this easier to configure. I would like to move sparklyr from using the default dir `c:\tmp\hadoop` in windows into using a directory under the user account, but to unblock this yourself before this becomes supported, here is an outline of the changes you would need:

-  Create two directories, one for hadoop and one for hive.
- The hadoop directory needs to contain a subdirectory named `bin` which contains the `winutils.exe` file, this can be copied from `sparklyr:::winutils_source_path()`
- There needs to be an environment variable `HADOOP_HOME` pointing to the Hadoop directory (not the hadoop bin directory)
- Need to configure `hive-site.xml` to point to the custom hive directory, there should be references online on how to configure those. See `hive.exec.*dir` under for instance `https://github.com/apache/spark/blob/master/sql/hive/src/test/resources/data/conf/hive-site.xml`
- Finally, `winutils chmod 777 <path-to-hive-directory>` must be run.

**Comment by javierluraschi** [comment]
@TaylorAndrew sparklyr `0.2.22` contains a fix that avoids using the `c:\tmp` directory, it's not configurable but this should solve this problem. The following steps should get you past this issue:

1. Upgrade to the latest version of sparklyr, instructions here: https://github.com/rstudio/sparklyr#installation
2. Rerun 1spark_install()1, optionally, specify the version parameter.
3. Optional, but recommended, delete the `c:\Users\<user-name>\AppData\local\Temp` directory, not only the contents but the actual `Temp` directory as well.
4. Connect again as `sc <- spark_connect(master = "local")`.
5. If something fails, please run `spark_log(sc)` and post the log in here.

**Comment by javierluraschi** [comment]
@TaylorAndrew I'm closing this issues since it has been inactive for a few days; however, if you find out that the above instructions do not resolve this issue, please reactivate to help find a different resolution.

**Comment by TaylorAndrew** [comment]
I had tested it and it worked. Sorry, I meant to close it myself.

**Comment by javierluraschi** [comment]
@TaylorAndrew great, that's all that matters. Thanks for confirming this is closed.
