### ISSUE TITLE
wrong/low number of cores allocated?

### ISSUE THREAD

**Issue by randomgambit** [rstudio/sparklyr#790]
Hi,

I am having a hard time getting a large number of cores. I see in the Spark UI that:

`Cores: 500 (60 granted, 440 left)` 

despite the fact that I set the following options

```
config <- spark_config()
config$`spark.executor.memory` <- "30GB"
config$`spark.executor.cores` <- "5"
config$`spark.local.dir` <- "/mydir"
config$`spark.cores.max`<- "500"
config$`driver.memory`<- "50GB"
config[["sparklyr.shell.num-executors"]] <- 20
config$`driver.cores`<- "20"
config[["spark.executors.instances"]] <- 10

Sys.setenv(SPARK_HOME="myhome")
sc <- spark_connect(master = "spark://sparknode01", config = config)
```

Is there some option that does not get transmitted when I initialize my connection?

**Comment by randomgambit** [comment]
@kevinushey @kevinykuo I checked some older similar issues in the sparklyr github, but nobody mentions the number of cores. Do you have an idea? 

Thanks and keep up the good work!!!

**Comment by kevinykuo** [comment]
@randomgambit what happens if you don't pass a `config`? How many cores do you get then?

**Comment by randomgambit** [comment]
@kevinykuo much less. I think 6.

**Comment by randomgambit** [comment]
@kevinykuo I think there may be some default that limits the number of cores, perhaps based on some rule (based on executors memory/core etc)?

**Comment by kevinykuo** [comment]
I was thinking you might have ran out of RAM before cores when allocating, but that's probably not the case if you're getting <6 cores with default configs. It's hard to tell what's going on and I don't have much experience with standalone mode... you might have to step through `spark_connect()` and see what exactly you're executing to get the session.

Have you tried doing this through vanilla `spark-shell`?

Also, somewhat related -- https://issues.apache.org/jira/browse/SPARK-15917

**Comment by randomgambit** [comment]
@kevinykuo thanks for your help. you mean using something like this

```
config[["sparklyr.shell.num-executors"]] <- 150
config[["sparklyr.shell.executor-memory"]] <- 10
config[["sparklyr.shell.executor-cores"]] <- 15
```

Am I supposed to put a string or a number for the shell executor executor-memory option in sparklyr?

**Comment by randomgambit** [comment]
@kevinykuo its something on SPARK side. Thanks for the apache issue
