### ISSUE TITLE
Error in UseMethod("spark_write_csv") :   no applicable method for 'spark_write_csv' applied to an object of class "data.frame"

### ISSUE THREAD

**Issue by duttashi** [rstudio/sparklyr#798]
In attempting to write a data frame obtained by `dbGetQuery()` of `library(DBI)`, to a local csv file, the following error is generated;

`Error in UseMethod("spark_write_csv") :   no applicable method for 'spark_write_csv' applied to an object of class "data.frame"`

Please note, if I attempt to write data that was copied to a local spark instance as shown below, `spark_write_csv()` works. But, it fails to work with data frame obtained from `dbGetQuery()`

```
# Copy data to spark local instance
flights_tbl <- copy_to(sc, nycflights13::flights, "flights", overwrite = TRUE)
spark_write_csv(flights_tbl,"local_csv_file/flight_detail.csv") # This works
```

A minimum reproducible example is as follows;

```
library(sparklyr)
library(dplyr)
library(DBI)
# show session info
> sessionInfo()
# connecting to spark local cluster
> sc <- spark_connect(master = "local", version = "1.6.2")
# Copy data to spark local instance
> flights_tbl <- copy_to(sc, nycflights13::flights, "flights", overwrite = TRUE)
# check data tables in spark local cluster
src_tbls(sc)
> flightdetail.df<-dbGetQuery(sc, "select flight, tailnum, origin, dest FROM flights where year=2013")
> str(flightdetail.df)
'data.frame':	336776 obs. of  4 variables:
 $ flight : int  1545 1714 1141 725 461 1696 507 5708 79 301 ...
 $ tailnum: chr  "N14228" "N24211" "N619AA" "N804JB" ...
 $ origin : chr  "EWR" "LGA" "JFK" "JFK" ...
 $ dest   : chr  "IAH" "IAH" "MIA" "BQN" ...
# Writing Data to a local .csv file
> spark_write_csv(flightdetail.df,"local_csv_file/flight_detail.csv", header=TRUE)
# Error in UseMethod("spark_write_csv") :   no applicable method for 'spark_write_csv' applied to an object of class "data.frame"
```

My session information is as follows;
```
> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] DBI_0.7            sparklyr_0.5.6     magrittr_1.5       dplyr_0.7.0        nycflights13_0.2.2

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11     rstudioapi_0.6   hms_0.3          rappdirs_0.3.1   xtable_1.8-2    
 [6] R6_2.2.2         rlang_0.1.1      httr_1.2.1       tools_3.3.3      parallel_3.3.3  
[11] config_0.2       dbplyr_1.0.0     withr_1.0.2      htmltools_0.3.6  yaml_2.1.14     
[16] assertthat_0.2.0 rprojroot_1.2    digest_0.6.12    tibble_1.3.3     shiny_1.0.3     
[21] readr_1.1.1      base64enc_0.1-3  glue_1.1.1       mime_0.5         backports_1.1.0 
[26] jsonlite_1.5     httpuv_1.3.3 
``` 

Am I missing something? do advise.

Thank you

**Comment by kevinykuo** [comment]
`dbGetQuery()` returns a local data.frame so use `write.csv` or the readr package.

**Comment by duttashi** [comment]
@kevinykuo thanks, `write.csv` works. 
Can you give a minimum reproducible example for `spark_write_csv`?

**Comment by kevinykuo** [comment]
@duttashi you got a good one in the OP with `flights_tbl` I think

**Comment by duttashi** [comment]
@kevinykuo so what do I change in the OP to make, `spark_write_csv` work?

**Comment by kevinykuo** [comment]
@duttashi refer to the last snippet here to see how to return a `tbl_spark` using Spark SQL: https://github.com/rstudio/sparklyr/issues/742

**Comment by duttashi** [comment]
@kevinykuo the last snippet  at [#742](https://github.com/rstudio/sparklyr/issues/742) `DBI::dbSendQuery(sc, "CREATE TABLE mytable AS SELECT * FROM df)` works, but does not extract records, because as per [documentation](https://www.rdocumentation.org/packages/DBI/versions/0.5-1/topics/dbSendQuery) for `dbSendQuery`, 

```
<DBISparkResult>
  SQL  CREATE TABLE mytable AS SELECT * FROM flights
  ROWS Fetched: 0 [complete]
       Changed: 0

```

> The dbSendQuery() method only submits and synchronously executes the SQL query to the database engine. It does not extract any records — for that you need to use the dbFetch() method, and then you must call dbClearResult() when you finish fetching the records you need. For interactive use, you should almost always prefer dbGetQuery().

So, this method `DBI::dbSendQuery(sc, "CREATE TABLE mytable AS SELECT * FROM df)` but its not returning any data. Its only returning an empty table in the spark cluster and `spark_write_csv()` is happy to write the empty table to spark cluster.

**Comment by kevinykuo** [comment]
Ahh okay. I'll take a look.

**Comment by kevinykuo** [comment]
@duttashi the correct syntax here would be

`tbl(sc, sql("select flight, tailnum, origin, dest FROM flights where year=2013"))`

Thanks @javierluraschi !

**Comment by javierluraschi** [comment]
Sounds like we are good to close this one? Closing, let me know if that's not the case.

**Comment by duttashi** [comment]
@kevinykuo and @javierluraschi , thank you both for the correct syntax. I confirm, `spark_write_csv()`, now works. I provide below the complete code for any future reference.

#### LOAD REQUIRED LIBRARIES
library(nycflights13)
library(sparklyr)

#### connecting to spark local cluster
sc <- spark_connect(master = "local", version = "1.6.2")
#### check data tables in spark local cluster
src_tbls(sc) # should print null as there is no tables in the spark cluster 
#### Copy data to spark local instance
copy_to(sc, nycflights13::flights, "flights", overwrite = TRUE)
#### check data tables in spark local cluster
src_tbls(sc) # flights

#### USING SQL 
library(DBI)
#### sql computation done in spark local cluster 
flights2013<- tbl(sc, sql("select flight, tailnum, origin, dest FROM flights where year=2013"))
#### write results to local
spark_write_csv(flights2013,"local_csv_file/flights2013.csv", header=TRUE)
