### ISSUE TITLE
spark_read_json prohibitively slow with many json files

### ISSUE THREAD

**Issue by randomgambit** [rstudio/sparklyr#799]
@kevinushey @kevinykuo I have about 40 very large json files (each is about 100GB) and I try to load them using

`spark_read_json(mypath/files_json*, memory = FALSE)`

However, **no matter what my cluster allocation is** (number of executors, number of cores, allocated RAM), the reading spawns 500k tasks and takes forever. I have the impression only one executor is trying to map all the data while this is something that can easily be parallelized. 

Some files can fit into the RAM of one cluster, but not all of them (some of them are much larger than the RAM available on a single node)

Any idea what `read_spark_json` is doing here?

**Comment by kevinykuo** [comment]
@randomgambit 40 files isn't very many so I suspect this is due to schema inference; the reader will iterate through your data even if you're not caching it in memory. We currently don't have a very friendly way to pass a schema to `spark_read_json()`, though it can be done. Would you be able to provide a sanitized sample of your json with the relevant structure (e.g. nested or not)? Looking at some use cases will help us shape the features.

**Comment by randomgambit** [comment]
@kevinykuo do you mean there is a workaround right now? I would be really interested to know it. I tried to convert my json to parquet, but this is a pain.

The json are really simple., There is only one field that is nested (it contains the longitude-latitude). There are about 15 fields including strings and numbers.

**Comment by randomgambit** [comment]
@kevinykuo is the workaround similar to the one in http://spark.rstudio.com/example-s3.html 

like

```
flights <- spark_read_csv(sc, "flights_spark", 
                          path =  "s3a://flights-data/full", 
                          memory = TRUE, 
                          columns = list(
                            Year = "character",
                            Month = "character",
                            DayofMonth = "character"
```

Do you think that will seriously cut the number of tasks generated?

**Comment by kevinykuo** [comment]
@randomgambit yeah but it's gonna be a bit more involved. The `csv` case is more well supported (in fact you can just pass `infer_schema = FALSE`). For json right now I think you'd have to get hacky and do something like

```
string_type <- invoke_new(sc, "org.apache.spark.sql.types.StringType")
integer_type <- invoke_new(sc, "org.apache.spark.sql.types.IntegerType")
metadata <- invoke_new(sc, "org.apache.spark.sql.types.MetadataBuilder") %>%
  invoke("build")
struct_field_1 <- invoke_new(
  sc,
  "org.apache.spark.sql.types.StructField",
  "my_string_column",
  string_type,
  ensure_scalar_boolean(TRUE),
  metadata
)

struct_field_2 <- invoke_new(
  sc,
  "org.apache.spark.sql.types.StructField",
  "my_integer_column",
  integer_type,
  ensure_scalar_boolean(TRUE),
  metadata
)

my_struct_type <- invoke_new(sc, "org.apache.spark.sql.types.StructType") %>%
  invoke("add", struct_field_1) %>%
  invoke("add", struct_field_2)
my_struct_type
# <jobj[681]>
#   class org.apache.spark.sql.types.StructType
# StructType(StructField(my_string_column,org.apache.spark.sql.types.StringType@37671448,true), StructField(my_integer_column,org.apache.spark.sql.types.IntegerType@26cce37a,true))
```
then pass `my_struct_type` to `spark_read_json()` via `options`.

I think we'd want an interface closer to `spark_read_csv()`, but we need to think about how it's gonna work with nested stuff.

@javierluraschi is this a fair assessment of the current state or am I missing something?

**Comment by randomgambit** [comment]
@kevinykuo @javierluraschi woooooot this is not what I call a workaround!! :D

**Comment by javierluraschi** [comment]
I'll take a look, we added `infer_schema = FALSE` for `sparklyr 0.6` so setting the `columns` parameter should be enough...

**Comment by randomgambit** [comment]
@javierluraschi I just wonder how you can specify the variable type for nested variables?

**Comment by javierluraschi** [comment]
@randomgambit could you update `sparklyr` with `devtools::instsall_github("rstudio/sparklyr")` followed by using the new `columns` parameter? Something like:

```r
spark_read_json(
  "mypath/files_json*",
  memory = FALSE,
  columns = list(col1 = "character", col2 = "character")
)
```

setting them all as "character" is fine here since we are interested in troubleshooting the performance issue you are reporting more than getting the right types.
