### ISSUE TITLE
Failed to launch Spark shell. Ports file does not exist

### ISSUE THREAD

**Issue by fissehab** [rstudio/sparklyr#80]
Following the instructions on the website, I tried to connect to a local Spark instance:
  ```
    install.packages("devtools")
    devtools::install_github("rstudio/sparklyr")
    library(sparklyr)
    spark_install(version = "1.6.1")

    library(sparklyr)
    library(dplyr)
```

When I try to connect to a local Spark instance using
    ` sc <- spark_connect(master = "local")`

I get the error message below:

      Error in start_shell(scon, list(), jars, packages) : 
       Failed to launch Spark shell. Ports file does not exist.
       Path: C:\Users\username\AppData\Local\rstudio\spark\Cache\spark-1.6.1-  bin-hadoop2.6\bin\spark-submit.cmd
       Parameters: --packages "com.databricks:spark-csv_2.11:1.3.0,com.amazonaws:aws-java-sdk-    pom:1.10.34" --jars "C:\Users\user\Documents\R\win-library\3.3\sparklyr\java\rspark_utils.jar"   sparkr-shell C:\Users\aaaa\AppData\Local\Temp\Rtmpw9PBxS\filea5860886dd1.out

      'cmd' is not recognized as an internal or external command,
       operable program or batch file.

I am using   R version 3.3.1 (2016-06-21)   and Rstudio 0.99.1246. I am on windows 10.

**Comment by javierluraschi** [comment]
@fissehab Could you post the output of `sys.etenv()`. Could you make sure that `C:\Windows\system32` (or whichever the path is on your system) is on the `PATH` environment variable?

**Comment by fissehab** [comment]
Thank you! Adding C:\Windows\system32 to the System Variables Path solved it. Before, it was added to User variables path only.

**Comment by javierluraschi** [comment]
Glad to hear this, closing.

**Comment by pagepiccinini** [comment]
I have the same problem on a Mac, OSX 10.10.5. Is there something I should add to my path?

**Comment by javierluraschi** [comment]
@pagepiccinini this issue was specific to windows, please open a separate github issue to assist you with the Mac OSX 10.10.5 problem you are experiencing. On the new issue, please include the output of the console to help troubleshoot.

**Comment by koaning** [comment]
On mac I am experiencing the same issue but only when I edit the `config.yml` file. I wanted to mention this because it might help debugging. In particular, it is the final line here:

```
default:
  sparklyr.cores.local: 8
  sparklyr.shell.driver-memory: 4GB
```

**Comment by codingbutstillalive** [comment]
I am using Windows 8 64bit, and adding "C:\Windows\System32" didn't solve the issue.

**Comment by javierluraschi** [comment]
@codingbutstillalive fixes have been added to improve diagnostics in Windows; therefore, I would retry with latest `sparklyr` version installed through `devtools::install_github("rstudio/sparklyr")`, please open a new github issue to troubleshoot this further since this one is already closed.
