### ISSUE TITLE
spark_write_json writes json as folder?!

### ISSUE THREAD

**Issue by randomgambit** [rstudio/sparklyr#800]
@kevinushey @kevinykuo I dont think this is the expected output for `spark_read_json`.
This is my current setup to process some large json files.

```

df <- spark_read_json(sc, "/mypath/large_file",
                      repartition = 0,
                      name = "test", memory = FALSE)

#convert to Parquet for later processing
spark_write_parquet(df,"/mypath/file_parquet")

df_new <-spark_read_parquet(sc, "/mypath/file_parquet", name = "data", memory = FALSE)

myquery <- df_new %>% filter(text %rlike% 'hello') 

spark_write_json(myquery, "file:///mypath/myoutput")
```

Then instead of having a nice `output.json` file, I have a folder containing many `.part_0001.crc` files. Is there a problem with the `spark_read_json` function?

**Comment by kevinykuo** [comment]
This looks like expected output if your file is distributed. If you want one file you'll want to collect via `sdf_reparitition(df, 1)` or `sdf_coalesce()` when https://github.com/rstudio/sparklyr/pull/806 is merged.

**Comment by randomgambit** [comment]
@kevinykuo thanks looking forward to that new function

**Comment by javierluraschi** [comment]
@kevinykuo added support for `sdf_calesce`, we good to close?
