### ISSUE TITLE
 java.io.IOException: No space left on device

### ISSUE THREAD

**Issue by randomgambit** [rstudio/sparklyr#812]
Hi,

I am getting the dreaded `no space left on device` error despite having set up `local.dir` in my config file

```
config <- spark_config()

config$`spark.executor.memory` <- "20GB"
config$`spark.executor.cores` <- "5"
config$`spark.executor.instances` <- "100"
config$`spark.executor.instances` <- "100"
config$`spark.local.dir` <- "/mypath/"
config$`spark.cores.max`<- "1000"
config$`spark.default.parallelism`<- "2000"
config$`spark.total-executor-cores`<- "50"
config$`sparklyr.shell.driver-memory` <- "40G"
config$`sparklyr.shell.executor-memory` <- "40G"
config$`spark.yarn.executor.memoryOverhead` <- "40G"
config$`sparklyr.shell.num-executors` <- "40"
config$`spark.memory.fraction` <- "0.8"
```

where `mypath` has more than 5TB of free space.

I am running something really simple like
```

df_new <-spark_read_parquet(sc, "/mypath/parquet_*", name = "df_new", memory = FALSE)

myquery <- df_new %>% group_by(text) %>% summarize(mycount = n()) %>% 
  arrange(desc(mycount)) %>% head(10)
```

running `collect(myquery)` returns the error. Is there a `sparklyr` parameter that overrides the writing of temporary files to the `/mypath` folder? Any ideas @kevinykuo @javierluraschi ?

Thanks!!

**Comment by randomgambit** [comment]
@kevinykuo @javierluraschi now that I think about it, this error may be related to some imbalances where after the `group_by` some keys have disproportionately large number of observations. How can I handle that in sparklyr in your opinion?

**Comment by randomgambit** [comment]
@kevinushey @javierluraschi could it be that sparklyr does not allow for different group_by methods such as `groupByKey` and `ReduceByKey` (this one being optimized for skewed data like mine) ?

thanks!!!

**Comment by kevinushey** [comment]
Although I'm not able to give you a direct answer, I would start by inspecting the generated SQL:

```
myquery <- df_new %>% group_by(text) %>% summarize(mycount = n()) %>% 
  arrange(desc(mycount)) %>% head(10)
sql_render(myquery)
```

Does the generated SQL look correct?

**Comment by randomgambit** [comment]
@kevinushey I actually get some crazy stuff

```
> myquery <- df_new %>% group_by(u) %>% summarize(mycount = n()) %>% 
+   arrange(desc(mycount)) %>% head(10)
> sql_render(myquery)
<SQL> SELECT *
FROM (SELECT *
FROM (SELECT `u`, count(*) AS `mycount`
FROM `df_new`
GROUP BY `u`) `jpdowetklw`
ORDER BY `mycount` DESC) `jhdbjylver`
LIMIT 10
```

u is a `url` address in my data. Any ideas?

**Comment by javierluraschi** [comment]
@randomgambit `jpdowetklw` is a temp table to the `spark_read_parquet` operation. Could you share the full stack trace of the `No space left on device` exception?

**Comment by randomgambit** [comment]
@javierluraschi  here it is:

```
 Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 5231 in stage 4.0 failed 4 times, most recent failure: Lost task 5231.3 in stage 4.0 (TID xxxx, xx.xx.xxx.xx, executor xx): java.io.IOException: No space left on device
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:345)
	at org.apache.spark.storage.TimeTrackingOutputStream.write(TimeTrackingOutputStream.java:58)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at net.jpountz.lz4.LZ4BlockOutputStream.flush(LZ4BlockOutputStream.java:225)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:141)
	at java.io.DataOutputStream.flush(DataOutputStream.java:123)
	at org.apache.spark.sql.execution.UnsafeRowSerializerInstance$$anon$2.flush(UnsafeRowSerializer.scala:91)
	at org.apache.spark.storage.DiskBlockObjectWriter.commitAndGet(DiskBlockObjectWriter.scala:170)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:157)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by javierluraschi** [comment]
@randomgambit does this happen to run correctly?

```r
DBI::dbGetQuery(sc, "SELECT `u`, count(*) AS `mycount` FROM `df_new` GROUP BY `u` ORDER BY `mycount` DESC")
```

This would be the simplified query, wondering if the nested select `dplyr` is generating is causing a performance degradation here.

**Comment by randomgambit** [comment]
@javierluraschi let me try this. but arent you missing a LIMIT somewhere? my query has a head at the end. thanks!

**Comment by randomgambit** [comment]
@javierluraschi tried the SQL and nope, still getting this error unfortunately...

**Comment by randomgambit** [comment]
@javierluraschi with the additional twist just before the no space left error

```
> output<- DBI::dbGetQuery(sc, "SELECT `u`, count(*) AS `mycount` FROM `df_new` GROUP BY `u` ORDER BY `mycount` DESC LIMIT 10" )
Error in if (ncol(df) > 0) df else invisible(df) : 
  argument is of length zero
In addition: Warning message:
In value[[3L]](cond)
 org.apache.spark.SparkException: Job aborted due to stage failure: Task 573 bla bla bla
```

**Comment by javierluraschi** [comment]
Yes, forgot the `LIMIT` clause. We shouldn't be getting a `Error in if (ncol(df) > 0) df else invisible(df)`, do you also get an error for `DBI::dbGetQuery(sc, "SELECT 1")`?

**Comment by randomgambit** [comment]
getting some ever more CRAZY stuff!!!!

```
df_new <-spark_read_parquet(sc, "/mypath/parquet_*", name = "df_new", memory = FALSE)
> DBI::dbGetQuery(sc, "SELECT 1 FROM `df_new`")
Error in if (ncol(df) > 0) df else invisible(df) : 
  argument is of length zero
In addition: Warning message:
In value[[3L]](cond) :
  org.apache.spark.SparkException: Job aborted due to stage failure: Total size of serialized results of 14908 tasks (1024.0 MB) is bigger than spark.driver.maxResultSize (1024.0 MB)
```

**Comment by javierluraschi** [comment]
@randomgambit can you share your `sessionInfo()`, I barely recall seeing this issue from a `DBI`/`sparklyr` version missmatch, you already ran `devtools::install_github("rstudio/sparklyr")` correct?

**Comment by randomgambit** [comment]
@javierluraschi yes  

```
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-ubuntu14-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] dbplyr_1.0.0        jsonlite_1.5        DBI_0.6-1           readr_1.0.0         pryr_0.1.2          lubridate_1.5.6    
 [7] h2o_3.10.4.8        dplyr_0.7.0         listviewer_1.4.0    sparklyr_0.5.6-9012 MKLthreads_0.1     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11     plyr_1.8.4       base64enc_0.1-3  bitops_1.0-6     tools_3.3.1      digest_0.6.9     tibble_1.3.3    
 [8] nlme_3.1-128     lattice_0.20-33  rlang_0.1.1      psych_1.6.6      shiny_1.0.3      rstudioapi_0.6   yaml_2.1.13     
[15] parallel_3.3.1   withr_1.0.2      httr_1.2.1       stringr_1.0.0    htmlwidgets_0.8  rprojroot_1.2    grid_3.3.1      
[22] glue_1.1.0       R6_2.1.2         reshape2_1.4.1   tidyr_0.5.1      magrittr_1.5     codetools_0.2-14 backports_1.1.0 
[29] htmltools_0.3.5  assertthat_0.1   mnormt_1.5-4     mime_0.5         xtable_1.8-2     httpuv_1.3.3     config_0.2      
[36] stringi_1.1.1    RCurl_1.96-0     lazyeval_0.2.0   broom_0.4.2     
```

**Comment by randomgambit** [comment]
@javierluraschi does that ring a bell?

**Comment by javierluraschi** [comment]
@randomgambit ah yes, the problem seems to be that the data frame has no columns, from looking at the code, this error is thrown when a dataset with no columns is read, I'll fix that today.

However, that fix won't solve your loading issue, can you explain how your parquet files are structured? Do all of the have the same schema, if not, have you considered using `mergeShema` from [read.parquet](https://spark.apache.org/docs/2.0.2/api/java/org/apache/spark/sql/DataFrameReader.html#parquet(scala.collection.Seq))

**Comment by randomgambit** [comment]
@javierluraschi related to this is https://github.com/rstudio/sparklyr/issues/799

what I ended up doing is load each json separately and write the corresponding parquet file. Compression and data loading seems much faster with parquet. Then I load all the parquet using

`df_new <-spark_read_parquet(sc, "/mypath/parquet_*", name = "df_new", memory = FALSE)`

Indeed, some of the files MAY have an extra field or two. Not entirely sure about that. Does that matter?

**Comment by javierluraschi** [comment]
Rather than loading everything, I would start with one file first... something like:

```
df_new <-spark_read_parquet(sc, "/mypath/parquet_1/", name = "df_new", memory = FALSE)
```

and see if that loads correctly.

Could you also rerun `devtools::install_github("rstudio/sparklyr")` to pick `sparklyr 0.5.6-9013` that contains this https://github.com/rstudio/sparklyr/pull/821 fix which I'm hoping will give us a better error message.

**Comment by randomgambit** [comment]
@javierluraschi sure I can do that hold on a few minutes

**Comment by randomgambit** [comment]
@javierluraschi hummm does not look good at all

```
df_new <-spark_read_parquet(sc, "mypath/parquet_01", name = "df_new", memory = FALSE)
output<- DBI::dbGetQuery(sc, "SELECT 1 FROM `df_new`" )

81      1
882      1
883      1
884      1
885      1
886      1
887      1
888      1
889      1
890      1
891      1
892      1
893      1
894      1
895      1
896      1
897      1
898      1
899      1
900      1
901      1
902      1
903      1
904      1
905      1
906      1
907      1
908      1
909      1
910      1
911      1
912      1
913      1
914      1
915      1
916      1
917      1
918      1
919      1
920      1
921      1
922      1
923      1
924      1
925      1
926      1
927      1
928      1
929      1
930      1
931      1
932      1
933      1
934      1
935      1
936      1
937      1
938      1
939      1
940      1
941      1
942      1
943      1
944      1
945      1
946      1
947      1
948      1
949      1
950      1
951      1
952      1
953      1
954      1
955      1
956      1
957      1
958      1
959      1
960      1
961      1
962      1
963      1
964      1
965      1
966      1
967      1
968      1
969      1
970      1
971      1
972      1
973      1
974      1
975      1
976      1
977      1
978      1
979      1
980      1
981      1
982      1
983      1
984      1
985      1
986      1
987      1
988      1
989      1
990      1
991      1
992      1
993      1
994      1
995      1
996      1
997      1
998      1
999      1
1000     1
 [ reached getOption("max.print") -- omitted 47875099 rows ]
```

**Comment by javierluraschi** [comment]
@randomgambit maybe we need to take a step back and troubleshoot how the parquet file got saved?

**Comment by randomgambit** [comment]
@javierluraschi but what is puzzling is that 
`
sample <-df_new %>% head()`
returns the correct first rows. I can look at them using `glimpse`. Variable types are `character`, `list` and `double`.

Anyway, the code I used to create each parquet is the following
```

for(i in 1:length(file_names)){
  df <- spark_read_json(sc, paste("//mypath/",file_names[i], sep = ""),
                        repartition = 0,
                        name = "df",
                        memory = FALSE,
                        overwrite = TRUE)
  spark_write_parquet(df,paste("//mypath/","parquet_",file_names[i], sep = ""), mode = "overwrite" )
  dplyr::db_drop_table(sc, "df")
}

```

**Comment by javierluraschi** [comment]
@randomgambit So you are saying that this works:

```
df_new %>% head()
```

but

```
df_new
```

wont?

**Comment by randomgambit** [comment]
@javierluraschi not quite

`df_new %>% head()` WORKS
`df_new` WORKS
`output<- DBI::dbGetQuery(sc, "SELECT 1 FROM `df_new`" )` FAILS (assuming SELECT 1 returns the first row and not only ones?!)

**Comment by randomgambit** [comment]
@javierluraschi so this does not seem to be the source of the problem after all?

**Comment by randomgambit** [comment]
@javierluraschi Indeed, running
`
 output<- DBI::dbGetQuery(sc, "SELECT `u`, count(*) AS `mycount` FROM `df_new` GROUP BY `u` ORDER BY `mycount` DESC LIMIT 10" ` 

**WORKS** on the single parquet file. So mine is a problem that comes when I combine all of the parquet together.

**Comment by javierluraschi** [comment]
@randomgambit good to know... and the main problem is still the performance issue, right? The query just hangs with multiple parquet files, correct?

Can you run a simple query over all the dataset? As in `dataset %>% count()`?

**Comment by randomgambit** [comment]
@javierluraschi worked really easy on the full dataset. spawned 17k tasks that were finished in about 34 s.
something like 10 billion observations in total

**Comment by javierluraschi** [comment]
@randomgambit it's interesting that it spawned 17K tasks, which works for `counts()` but not for aggregations, I think we need to find a way to reduce the number of tasks that get created after reading the data. Could you try something like

`dataset %>% sdf_repartition(partitions = 50) %>% count()`?

I would expect the count to run over less tasks, if this works, then you can try something more complicated using your aggregation. In general, I've noticed Spark is not optimized to deal with thousands of tasks (unless you have a giant cluster), but instead, tasks should be as big as possible without breaking the bennefits of parallelizing them, can be tricy but looks to me you are on the right track.

**Comment by randomgambit** [comment]
here is what I see exactly:

`df_new <-spark_read_parquet(sc, "//mypath/parquet_*", name = "df_new", memory = FALSE)`
spawns 
- one `collect at utils.scala:58` 
- three `parquet at NativeMethodAccessorImpl.java:0` (two with 71 tasks, one with 1 task)

each of them less than 3 seconds.

then `df_new %>% count()`


spawns

- two `count at NativeMethodAccessorImpl.java:0` (one with 17k tasks, one with 1 task)
- two `collect at utils.scala:196` (one with 17k tasks, one with 1 task)

whole process about 35 seconds.

Last, `df_new %>% sdf_repartition(partitions = 50) %>% count()`

spawns:
- three `count at NativeMethodAccessorImpl.java:0` (17k tasks, 50 tasks, 1 task)
- three `collect at utils.scala:196` (17k tasks, 50 tasks, 1 task)

whole process takes about 1 minute (so its slower).

Is that expected?
Thanks again for your invaluable input!!

**Comment by javierluraschi** [comment]
yes, I think repartitioning is expected to cause an overhead, but at times where data is too-fragmented, it could actually speed up things for more complicated queries. Give it a shot with the real query to see how it goes. Something like:

```
df_new %>% 
  sdf_repartition(partitions = 50) %>%
  group_by(text) %>%
  summarize(mycount = n()) %>% 
  arrange(desc(mycount)) %>%
  head(10)
```

**Comment by randomgambit** [comment]
@javierluraschi that is a very interesting possibility but there is some weird behavior here

` df_new %>% sdf_repartition(partitions = 50) %>% group_by(u) %>% summarize(mycount = n()) %>% arrange(desc(mycount)) %>% head(10)`

spawns:
-  4  `count at NativeMethodAccessorImpl.java:0` stages 

where the **first one** has 17k tasks (and FAILS with no space left error). 
The other stages (pending) have 1, 200 and 50 tasks.

Is that the expected behavior?

**Comment by randomgambit** [comment]
@javierluraschi  closing this one. Thanks!
