### ISSUE TITLE
master branch not functional

### ISSUE THREAD

**Issue by geoHeil** [rstudio/sparklyr#828]
When installing the latest version via: `devtools::install_github("rstudio/sparklyr")` the package is not useable and complains about a premature end of file.

**Comment by kevinykuo** [comment]
Related: https://github.com/rstudio/sparklyr/issues/831

@javierluraschi

**Comment by geoHeil** [comment]
When executing:
`devtools::install_github("rstudio/sparklyr",lib="")`
https://github.com/rstudio/sparklyr/issues/829#issuecomment-314417936 it works

**Comment by geoHeil** [comment]
but this means that it now only works on the command line the panel in RStudio is still broken! Below are the logs.
```
Fehler: parse error: premature EOF
                                       
                     (right here) ------^
Fehler: parse error: premature EOF
                                       
                     (right here) ------^
Fehler: parse error: premature EOF
                                       
                     (right here) ------^
```

**Comment by geoHeil** [comment]
The error occurs when executing
`spark_install(version="2.1.1")`
I tried to move back to the old version released on CRAN but that one fails to download this link (404) for available spark versions.
https://raw.githubusercontent.com/rstudio/sparklyr/master/inst/extdata/install_spark.csv

**Comment by geoHeil** [comment]
Actually https://github.com/rstudio/sparklyr/issues/831 is fixing the JSON parsing problem. The download now works fine for me.

**Comment by javierluraschi** [comment]
My bad @geoHeil, it's fixed in the latest sources now with: https://github.com/rstudio/sparklyr/commit/e88632e06aa2ff65cc85f7cb2b175bcf88018282
