### ISSUE TITLE
spark 2.1.0 missing

### ISSUE THREAD

**Issue by geoHeil** [rstudio/sparklyr#829]
When using `spark_available_versions()` in the latest released version to CRAN only below versions are returned. The README mentions that `2.1.0` should already be available. How can I obtain this version?
```
spark_install(version = "2.0.2", hadoop_version = "2.7")
26  spark_install(version = "2.0.2", hadoop_version = "2.6")
27  spark_install(version = "2.0.2", hadoop_version = "2.4")
28  spark_install(version = "2.0.2", hadoop_version = "2.3")
```

**Comment by shoreshgithub** [comment]
Hi you should uppdate sparklyr by 
devtools::install_github("rstudio/sparklyr",lib="")
spark_available_versions()

**Comment by geoHeil** [comment]
What is the lib parameter for?
shoreshgithub <notifications@github.com> schrieb am Di. 11. Juli 2017 um
13:43:

**Comment by geoHeil** [comment]
This works. Thanks.
