### ISSUE TITLE
placing predicted values into spark dataframes

### ISSUE THREAD

**Issue by koaning** [rstudio/sparklyr#84]
As a normal R user, I am used to running a pattern like this. 

```
library(sparklyr)
library(dplyr)
sc <- spark_connect(master = "local")
iris_tbl <- copy_to(sc, iris)

mod <- iris_tbl %>% 
  ml_random_forest(
    response = "Species", 
    features = c("Sepal_Length", "Sepal_Width",  "Petal_Length", "Petal_Width")
  )

pred <- predict(mod, newdata = iris_tbl)

iris_tbl %>% 
  mutate(pred = predict(mod, newdata = iris_tbl)) %>% 
  collect
```

This seems to not work as the `predict` function returns values back into R-land, not into spark-land. In this case you'll get an error because `sparklyr` is trying to translate the predict statement into sql. 

```
Error in UseMethod("escape") : 
  no applicable method for 'escape' applied to an object of class "c('ml_model_random_forest', 'ml_model')"
In addition: Warning message:
Named arguments ignored for SQL PREDICT 
```

In this case it's not such a terrible thing because the iris dataset is nice and small and the [tutorial](http://spark.rstudio.com/mllib.html#linear_regression) deals with this situation by first bringing all the data back into Rland. But if the dataset was very big then I would prefer the confusion matrix to be calculated on the spark side. 

Is there a way to get predicted values back into the spark-dataframe? The usecase would be to check performance in a training set and run some custom metrics against it. Spark tends to have it's [own metrics](http://spark.apache.org/docs/latest/mllib-evaluation-metrics.html) which potentially could offer an alternative here as well but I have not seen that supported in the docs.

**Comment by kevinushey** [comment]
You should be able to use `sdf_predict()` to get the predictions back as part of a Spark DataFrame / `tbl_spark`, e.g.

```R
library(sparklyr)
library(dplyr)
sc <- spark_connect(master = "local")
iris_tbl <- copy_to(sc, iris)

mod <- iris_tbl %>% 
  ml_random_forest(
    response = "Species", 
    features = c("Sepal_Length", "Sepal_Width",  "Petal_Length", "Petal_Width")
  )

sdf_predict(mod, iris_tbl)
```

Is that sufficient here?

**Comment by koaning** [comment]
d0h. didn't see the documentation on that one. my bad. 

solution is perfect here.
