### ISSUE TITLE
Feature request: send _arbitrary_ R code transformations to the spark cluster?

### ISSUE THREAD

**Issue by carioca67** [rstudio/sparklyr#847]
I understand that's possible via library(sparkR). I also saw some info that spark_apply can do it, but does the latter accept any generic R-function?

**Comment by javierluraschi** [comment]
@carioca67 Yes, it supported generic R-functions and even the use of packages and groups. Please take a look at https://spark.rstudio.com/articles/guides-distributed-r.html. would appreciate any feedback you might have on this article, thanks!

**Comment by carioca67** [comment]
Thanks Javier!
