### ISSUE TITLE
Feature Request: Write to JDBC

### ISSUE THREAD

**Issue by JakeRuss** [rstudio/sparklyr#851]
Per @javierluraschi's request I'm opening this issue and migrating the discussion away from Gitter.

I'd like to write to database sources directly from Spark. Currently, I can import data from, say, MySQL, directly into Spark via `spark_read_jdbc()`. But, if I perform a calculation in Spark and then wanted to send the data back to MySQL and update a table, it looks like I would have to collect the data into R and then use one of the R/DBI/RMySQL functions to perform the writing.

Javier's comments

> Should be fairly straightforward to implement this wrapper, we basically need to write one of this 

> (https://github.com/rstudio/sparklyr/blob/602043e87085830365dbe876f684e62a3b8553d1/R/data_interface.R#L473-L541) but for these parameters: https://github.com/rstudio/sparklyr/blob/602043e87085830365dbe876f684e62a3b8553d1/R/data_interface.R#L564.

So, I propose `spark_write_jdbc()`

**Comment by javierluraschi** [comment]
Fixed with https://github.com/rstudio/sparklyr/pull/852.
