### ISSUE TITLE
Add ability to add custom headers for livy config

### ISSUE THREAD

**Issue by srvvb** [rstudio/sparklyr#856]
New feature -

Currently livy_config only supports username and password.  It will be helpful to add custom headers as in some case its behind firewalls.

New syntax
livy_config(config = spark_config(), username = NULL, password = NULL, custom_header=custom_headers())

**Comment by javierluraschi** [comment]
@srvvb custom headers are already supported in the latest version of `sparklyr` which is not yet on CRAN. Try:

```r
devtools::install_github("rstudio/sparklyr")
```

The signature of `livy_config` was updated to:

```r
livy_config <- function(
   config = spark_config(),
   username = NULL,
   password = NULL,
   custom_headers = list("X-Requested-By" = "sparklyr")
)
```

**Comment by srvvb** [comment]
@javierluraschi  Thanks.
