### ISSUE TITLE
Error in ensure_scalar_character(output.col) : 'NULL' is not a length-one character vector

### ISSUE THREAD

**Issue by encore137** [rstudio/sparklyr#867]
I have the fitted model (randomForestSRC). The purpose is to load this model and perform the disturbed prediction proccess.
Here is my code:

```r
library(sparklyr)
library(dplyr)

sc <- spark_connect(master = "local")

localTestData <- readRDS("./trainData.rds")
model <- readRDS("./model.rds")

spark_data_tbl <- copy_to(sc, localTestData, "spark_data", overwrite = TRUE)
loaded_model <- ml_model(class(model), model = model)

predicted <- sdf_predict(loaded_model, spark_data_tbl) %>% collect
```

I get the following error:

Error in ensure_scalar_character(output.col) : 'NULL' is not a length-one character vector
![localdata](https://user-images.githubusercontent.com/28949053/28630744-c7392802-7233-11e7-90a6-dfaa0130c386.png)
![sparkdata](https://user-images.githubusercontent.com/28949053/28630743-c7313e9e-7233-11e7-957c-317cc0e21db7.png)

when i try:
```
> class(spark_data_tbl$FILIAL_ID)
[1] "NULL"
```
it shows NULL. i guess the problem is somewhere here (look at the screenshots).
Please, could you point what i'm doing wrong?

**Comment by kevinushey** [comment]
I don't think you can use `saveRDS()` / `readRDS()` for saving and loaded Spark models. Have you seen `sparklyr::ml_save()` and `sparklyr::ml_load()`?

**Comment by encore137** [comment]
@kevinushey,
i have a model myrf (survival random forest, package randomForestSRC). it was trained locally and have special R type (Large rfsrc - 40 elements, 64.4Mb - that's what Rstudio tells me).

When i try:
```class(myrf)```
i see 
```> class(myrf) 
[1] "rfsrc" "grow"  "surv"
```
then, according to your answer, i am trying to save the model using ```ml_save```:
```ml_save(ml_model(class(myrf), myrf), "./models/")```
and get the error:

Error in UseMethod("invoke") :    no applicable method for 'invoke' applied to an object of class "c('rfsrc', 'grow', 'surv')"

Is that seem that i can't save randomForestSrc model from my R object myrf?

**Comment by kevinykuo** [comment]
@encore137 The issue here is that `sdf_predict()` only works with models fit using Spark ML `ml_*` functions and not arbitrary R model objects. Could you elaborate your use case, e.g. are you trying to speed up computing predictions for really big scoring datasets?
