### ISSUE TITLE
Spark 2.2 in sparklyr 0.6.0 ?

### ISSUE THREAD

**Issue by andrekos2** [rstudio/sparklyr#870]
I can't see and can't install Spark 2.2, as suggested in the release notes  https://github.com/rstudio/sparklyr/releases 
'Use the Latest Frameworks including dplyr 0.7, DBI 0.7, RStudio 1.1 and Spark 2.2.'

It's not from CRAN yet, but from the Source code (tar.gz) provided. 

Ideally, I should see this list jsonlite::fromJSON("https://api.github.com/repos/apache/spark/tags")$name

![image](https://user-images.githubusercontent.com/26861595/28659837-5f88de22-72e3-11e7-9e10-782db5185162.png)

**Comment by kevinykuo** [comment]
@andrekos2 This should work now. Please reopen if you're still running into issues. Thanks!

**Comment by andrekos2** [comment]
Thanks. I've now installed from CRAN and there seems to be no issues.
