### ISSUE TITLE
Consider support for `:` and other formula operators in `ml_*` functions

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#875]
[Model Formulae](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/formula.html) support additional terms like `:`, `^`, etc. Customers have reached out at least to support `:` but others should be considered.

**Comment by kevinykuo** [comment]
See also https://github.com/rstudio/sparklyr/issues/554

**Comment by kevinykuo** [comment]
Closing in favor of https://github.com/rstudio/sparklyr/issues/554
