### ISSUE TITLE
Error about loaded version of sparkapi when install of sparklyr is comleted

### ISSUE THREAD

**Issue by fereshtehRS** [rstudio/sparklyr#88]
Using RStudio Desktop Version 0.99.1242 on Mac OS X 10_11_2

- Install `sparklyr` package from github (installing 0.2.18)
- When install is completed this message is logged:
```
Reloading installed sparklyr
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘sparkapi’ 0.3.3 is already loaded, but >= 0.3.6 is required
```

Since we already install the required version of `sparkapi` (0.3.6 for this case), could we just reload that instead of giving error? (or prompt user for it?)

**Comment by kevinushey** [comment]
@javierluraschi just bumped the required version of `sparkapi` so this should be handled now, I think:

https://github.com/rstudio/sparklyr/blob/master/DESCRIPTION#L71

**Comment by dfalty** [comment]
This looks to be blocking me from loading sparklyr now.

`> library(sparklyr)
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘sparkapi’ 0.3.6 is already loaded, but >= 0.3.8 is required
Error: package or namespace load failed for ‘sparklyr’`

**Comment by javierluraschi** [comment]
@jimhester: Any thoughts form this error? Apparently, here we are getting stuck loading `sparkapi` version `0.3.6` but running `packageVersion("sparkapi")` does show version `0.3.8`. Looping you since you might already be familiar with this error, otherwise, no worries.

**Comment by dfalty** [comment]
Looks like uninstalling sparkapi, restarting the rsession, and reinstalling sparkapi fixed this for me.

**Comment by javierluraschi** [comment]
@jimhester better question: Is there a way to force package reload (without having to restart the rsession) when running `devtools::install_github`?

**Comment by jimhester** [comment]
It looks like this problem is the dependencies are not unloaded, only the package being installed by `devtools::install_github()`.

This will unload the sparkapi namespace directly.
```r
library(devtools)
unload(inst("sparkapi"))
```

**Comment by javierluraschi** [comment]
Thanks @jimhester.

**Comment by kevinushey** [comment]
In general, you should assume that if you're updating / reinstalling a package, you'll need to restart your R session afterwards to ensure everything works.

**Comment by javierluraschi** [comment]
@fereshtehRS did restarting the rsession worked for you? If it did, we should close this one.

**Comment by fereshtehRS** [comment]
@javierluraschi Restarting R session, or just loading `sparkapi` package works fine. My point was that instead of showing error, would look better to automatically unload/load the package.
This definitely is not a high priority issue. Should we just mention it in the readme?

**Comment by javierluraschi** [comment]
@fereshtehRS Yes for sure, we can add a couple lines to the README. Added already some to the install section.

**Comment by javierluraschi** [comment]
Entry to README was added, closing.
