### ISSUE TITLE
Rotate data using PCA components found

### ISSUE THREAD

**Issue by ilanfri** [rstudio/sparklyr#884]
# New functionality: Provide rotated data after PCA

Perhaps I have somehow missed this functionality, and if so apologies and it would be great if you could point me in the right direction, but at the moment I haven't been able to find a way to retrieve data as obtained after rotating by the PCA components found by ml_pca(): that is, the PCA components are easily accessible using $components, but the result of matrix multiplication of the input data by the PCA components doesn't seem to be accessible.

I have tried to go into ml_pca() and hack the input dataframe conversion into RowMatrix() and then do the multiplication to obtain the transformed data, but so far unsuccessfully.

If this functionality could be added, or if you can point me in the right direction to convert the data input in ml_pca() into a RowMatrix so I can do the matrix multiplication in Spark that would be great.

---

The desired output is the "projected" variable shown [here in the Spark documentation](https://spark.apache.org/docs/2.1.0/mllib-dimensionality-reduction.html#principal-component-analysis-pca):

val mat: RowMatrix = new RowMatrix(dataRDD)

// Compute the top 4 principal components.
// Principal components are stored in a local dense matrix.
val pc: Matrix = mat.computePrincipalComponents(4)

// Project the rows to the linear space spanned by the top 4 principal components.
val projected: RowMatrix = mat.multiply(pc)

**Comment by kevinykuo** [comment]
@ilanfri I whipped something together at https://github.com/rstudio/sparklyr/pull/901, if you can give it a whirl that'd be great. See https://github.com/kevinykuo/sparklyr/blob/5d30a77a482c41847a46cd91cfc70fa82c7f9cad/tests/testthat/test-ml-pca.R for examples.

**Comment by ilanfri** [comment]
@kevinykuo Absolutely brilliant. Works a charm. Thank you!! :)

Just a quick question: am I safe to assume that row ordering is preserved? The reason I ask is because the column used to identify the entries has to be dropped when feeding the data into ml_pca(), and then reattached afterwards, like so:

ids= table %>% select(ID)
tmp = table %>% ml_pca(k = dimensions, features = cols_of_interest) %>% sdf_project() %>% select(dplyr::starts_with("PC"))
new_table = sdf_bind_cols(ids, tmp)

Is it safe to assume the row ordering is preserved (despite partitioning and all) through ml_pca() and sdf_bind_cols()?

**Comment by kevinykuo** [comment]
@ilanfri row ordering is always tricky in Spark. I'm not sure if the underlying linear algebra methods preserve row order, but `sdf_bind_cols()` does (albeit not very efficiently.) To get around this, we usually try to keep ID columns intact through chains.

Could you see if something like this works for your use case?

```
table %>% 
  ml_pca(k = dimensions, features = cols_of_interest) %>% 
  sdf_project() %>% 
  select(starts_with("PC"), ID)
```

**Comment by ilanfri** [comment]
@kevinykuo Simpler and safer than my workaround, what you suggested worked perfectly! Thanks so much for the help and the quick turnaround time! Makes using Sparklyr that much more productive and enjoyable :)

I'll close this now as I think the issue is fully dealt with.

P.S. Out of interest: will this branch be merged into the master branch and included in the next release?

(I ask because one of our fears of relying on development branches for code that will be used in production is that it will diverge and become incompatible with later releases, the technical debt that would create, etc.)

**Comment by kevinykuo** [comment]
@ilanfri we're getting the code reviewed right now and we plan to merge it soon. It'll be included in the next feature release. Thanks for submitting the issue!
