### ISSUE TITLE
unable to set java.io.tmpdir with spark_config

### ISSUE THREAD

**Issue by randomgambit** [rstudio/sparklyr#895]
Hello @javierluraschi @kevinushey @kevinykuo 

Thanks for this new amazing version of Sparklyr!!

I am trying to set `java.io.tmpdir` in Sparklyr 0.6 using the following syntax

```
config <- spark_config()
config$`spark.java.io.tmpdir` <- "/mypath"
Sys.setenv(SPARK_HOME="/mypath/myspark")
sc <- spark_connect(master = "spark://mynodeabc", config = config, version = "2.1.1") 
```

But this option does not seem to be considered. In my environment tab, I still see the default `tmp` directory for `java.io.tmpdir`.

Is this expected? Am I using the correct syntax?

Thanks!

**Comment by kevinykuo** [comment]
Good to hear from you!

Give this a try:

```
config$spark.driver.extraJavaOptions <- "-Djava.io.tmpdir=/mypath"
config$spark.executor.extraJavaOptions <- "-Djava.io.tmpdir=/mypath"
```

In local mode, you'll have to do

```
config$`sparklyr.shell.driver-java-options` <- "-Djava.io.tmpdir=/mypath"
```

**Comment by randomgambit** [comment]
Hi @kevinykuo thanks!
I have set these (and they work correctly) but what I am trying to set up is `java.io.tmpdir` in the system properties that I see in the Spark environment tab. Is this something configurable from within Sparklyr?

**Comment by kevinykuo** [comment]
Yeah, it's not showing up on your end?

<img width="1008" alt="screenshot 2017-08-03 11 58 23" src="https://user-images.githubusercontent.com/5582151/28931146-216f0714-7843-11e7-8e19-136c7a6318ff.png">

**Comment by randomgambit** [comment]
@kevinushey nope, that's weird...

**Comment by randomgambit** [comment]
@kevinushey could this be related to some Java issue? What Java version do you use on your system?

**Comment by kevinykuo** [comment]
It's a little tough to troubleshoot since I don't have a standalone cluster with me, but could you try using this config:

```
config <- spark_config()
config$`sparklyr.shell.driver-java-options` <- "-Djava.io.tmpdir=/mypath"
config$spark.driver.extraJavaOptions <- "-Djava.io.tmpdir=/mypath"
config$spark.executor.extraJavaOptions <- "-Djava.io.tmpdir=/mypath"
```

Btw it's @kevinykuo ;)

**Comment by randomgambit** [comment]
haha @kevinykuo sorry about that!

**Comment by kevinykuo** [comment]
@randomgambit which setting (if any) ended up working for you?

**Comment by randomgambit** [comment]
hi @kevinykuo your suggestion worked! thx!
