### ISSUE TITLE
This is not an issue - it's meant to be a Big Thanks!

### ISSUE THREAD

**Issue by codingbutstillalive** [rstudio/sparklyr#909]
Dear Javier, dear others,

I really want to appreciate your joint efforts for this awesome package. Today, I stumbled upon the latest release note on RStudio:

https://blog.rstudio.com/2017/07/31/sparklyr-0-6/

Great work!!!

**Comment by javierluraschi** [comment]
Thank you for this note @codingbutstillalive, really appreciated! Cheers, Javier
