### ISSUE TITLE
 Error in summary method with lasso regression

### ISSUE THREAD

**Issue by slopp** [rstudio/sparklyr#91]
Reproducible Example:

```R
library(sparklyr)
sc  <- spark_connect(master = "local")
mtcars_tbl  <- copy_to(sc, mtcars, "mtcars")
m <- mtcars_tbl %>% 
            ml_linear_regression(mpg ~cyl + disp + hp + drat + wt + qsec + vs + am + gear + carb,
                                               lambda = 1, alpha = 1)
print(m) # works
summary(m) #fails
 ```

<details>
Session info ----------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.2 (2015-08-14)
 system   x86_64, linux-gnu           
 ui       RStudio (0.99.1242)         
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       <NA>                        
 date     2016-07-07                  

Packages --------------------------------------------------------------------------------
 package    * version     date       source                           
 assertthat   0.1         2013-12-06 CRAN (R 3.2.2)                   
 codetools    0.2-14      2015-07-15 CRAN (R 3.2.2)                   
 config       0.1.0       2016-06-08 cran (@0.1.0)                    
 DBI          0.4-1       2016-05-08 cran (@0.4-1)                    
 devtools     1.11.1.9000 2016-05-31 Github (hadley/devtools@75b7d12) 
 digest       0.6.9       2016-01-08 CRAN (R 3.2.2)                   
 dplyr      * 0.5.0       2016-06-24 cran (@0.5.0)                    
 foreach    * 1.4.3       2015-10-13 CRAN (R 3.2.2)                   
 glmnet     * 2.0-5       2016-03-17 CRAN (R 3.2.2)                   
 iterators    1.0.8       2015-10-13 CRAN (R 3.2.2)                   
 lattice      0.20-33     2015-07-14 CRAN (R 3.2.2)                   
 lazyeval     0.2.0       2016-06-12 cran (@0.2.0)                    
 magrittr     1.5         2014-11-22 CRAN (R 3.2.2)                   
 Matrix     * 1.2-2       2015-07-08 CRAN (R 3.2.2)                   
 memoise      1.0.0       2016-01-29 CRAN (R 3.2.2)                   
 R6           2.1.2       2016-01-26 CRAN (R 3.2.2)                   
 rappdirs     0.3.1       2016-03-28 cran (@0.3.1)                    
 Rcpp         0.12.5      2016-05-14 CRAN (R 3.2.2)                   
 readr        0.2.2       2015-10-22 CRAN (R 3.2.2)                   
 sparkapi     0.3.9       2016-07-07 Github (rstudio/sparkapi@a06f6bb)
 sparklyr   * 0.2.22      2016-07-07 Github (rstudio/sparklyr@36f28c4)
 tibble       1.1         2016-07-04 cran (@1.1)                      
 withr        1.0.2       2016-06-20 cran (@1.0.2)                    
 yaml         2.1.13      2014-06-12 CRAN (R 3.2.2)  
</details>

**Comment by kevinushey** [comment]
Thanks for the bug report! I'll take a look.
