### ISSUE TITLE
Segfault on reinitialising connection

### ISSUE THREAD

**Issue by AkhilNairAmey** [rstudio/sparklyr#919]
Reopening #840 in a new issue as suggested:

@javierluraschi Finally think I've tracked this down...

Here's a Dockerfile reproducing the environment from `rocker/tidyverse`

```
FROM rocker/tidyverse:latest

RUN apt update && apt install r-cran-rjava -y

RUN install2.r sparklyr

RUN R -e 'sparklyr::spark_install("2.0.2")'

RUN printf "library(sparklyr)\n\nsc = spark_connect('local')\nspark_disconnect(sc)\nspark_connect('local')\n" > script.r
```

That last little bit of script sent into `script.r` is

```
library(sparklyr)

sc = spark_connect('local')
spark_disconnect(sc)
spark_connect('local')
```

Running `docker run --rm -it coredump Rscript script.r` yields

```
* Using Spark: 2.0.2
* Using Spark: 2.0.2

 *** caught segfault ***
address 0x55a590f25003, cause 'memory not mapped'
*** Error in `/usr/local/lib/R/bin/exec/R': malloc(): memory corruption: 0x000055a590e7d920 ***
```

What I've found is that putting a sleep in for 10 seconds between the disconnect and the reconnect solves this.  

___
My use case for doing this (connecting, disconnecting, reconnecting) is making certain all the memory is completely wiped and make reavailable when running sequential 2 hour long independent queries.  This shouldn't be a problem to me now as I know how to avoid the segfault, but thought you might wanna know what was going on!

Akhil

**Comment by javierluraschi** [comment]
Thanks, taking a look to this repro!

**Comment by javierluraschi** [comment]
This `dockerfile` still crashes:

```
FROM rocker/tidyverse:latest

RUN apt update && apt install r-cran-rjava -y

RUN apt-get install libc6-dbg gdb valgrind -y

RUN install2.r devtools

RUN R -e 'devtools::install_github("rstudio/sparklyr")'

RUN R -e 'sparklyr::spark_install("2.0.2")'

RUN printf "library(sparklyr)\n\nsc = spark_connect('local')\nspark_disconnect(sc)\nspark_connect('local')\n" > script.r
```

but this one not anymore:

```
FROM rocker/tidyverse:latest

RUN apt update && apt install r-cran-rjava -y

RUN apt-get install libc6-dbg gdb valgrind -y

RUN install2.r devtools

RUN R -e 'devtools::install_github("rstudio/sparklyr", ref = "bugfix/reconnect-sigpipe")'

RUN R -e 'sparklyr::spark_install("2.0.2")'

RUN printf "library(sparklyr)\n\nsc = spark_connect('local')\nspark_disconnect(sc)\nspark_connect('local')\n" > script.r
```

**Comment by AkhilNairAmey** [comment]
Thank you! Highly appreciate how efficient you are at dispatching these issues.

**Comment by AkhilNairAmey** [comment]
Hi @javierluraschi,

I'm seeing this again on the current master (`d49ea49`). The fix you made was definitely pulled in (the commit message is still there on `R/core_invoke.r`), but the `Dockerfile` above fails again.  I just changed the `ref` to make sure:

```
FROM rocker/tidyverse:latest

RUN apt update && apt install r-cran-rjava -y

RUN apt-get install libc6-dbg gdb valgrind -y

RUN install2.r devtools

RUN R -e 'devtools::install_github("rstudio/sparklyr", ref = "d49ea49")'

RUN R -e 'sparklyr::spark_install("2.0.2")'

RUN printf "library(sparklyr)\n\nsc = spark_connect('local')\nspark_disconnect(sc)\nspark_connect('local')\n" > script.r
```

Apologies to reopen this.
