### ISSUE TITLE
How to set all column names of spark data frame?

### ISSUE THREAD

**Issue by hiltonmbr** [rstudio/sparklyr#92]
I have a large CSV file which header contains the description of the variables (including blank spaces and other characters) instead of valid names for parquet file. First, I have read the CSV without the header:
df <- spark_read_csv(sc,name="mytable",path=myfile,
header=FALSE,memory=FALSE)
df

Source: query [?? x 28]
Database: spark connection master=local[*] app=sparklyr local=TRUE
_c0 _c1 _c2 _c3
1 110028 26417 0 10
2 110020 15890 0 10
3 110009 20109 0 10

On the other hand, I have a vector including valid names of the variables :
v <- c("name1","name2", ... )

Thus, I've tried to set the column names of Spark data frame without collect it using:

colnames(df) <- v

It returns an error. 

Therefore, how to set all column names without collect spark data frame ? I cannot collect it because the file is large and does not fit in RAM memory. Any ideia?

**Comment by javierluraschi** [comment]
@hiltonmbr how about using `rename` from dplyr? For instance:

```
df <- spark_read_csv(sc,name="mytable",path=myfile, header=FALSE,memory=FALSE)
df2 <- rename(df, col1 = _c0, col2 = _c1)
```

Would this work for your case?

**Comment by hiltonmbr** [comment]
It does not work and returns the following errors:

df2 <- rename(df, col1 = _c0, col2 = _c1)
Error: unexpected input in "df2 <- rename(df, col1 = _"

df2 <- rename(df, col1 = "_c0", col2 = "_c1")
Error: Arguments to `rename()` must be unquoted variable names.
Arguments `col1`, `col2` are not.

df2 <- rename(df, col1 = X_c0, col2 = X_c1)

Source:   query [?? x 41]
Database: spark connection master=local[*] app=sparklyr local=TRUE

Error: org.apache.spark.sql.AnalysisException: cannot resolve '`X_c0`' given input columns: [_c20, _c19, _c18, _c29, _c30, _c8, _c27, _c26, _c14, _c0, _c38, _c15, _c3, _c39, _c36, _c35, _c37, _c17, _c5, _c11, _c31, _c33, _c6, _c25, _c34, _c28, _c10, _c12, _c40, _c32, _c9, _c2, _c21, _c22, _c1, _c23, _c4, _c7, _c13, _c24, _c16]; line 2 pos 13
	at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
df$ops$vars
 [1] "X_c0"  "X_c1"  "X_c2"  "X_c3"  "X_c4"  "X_c5"  "X_c6"  "X_c7"  "X_c8"  "X_c9"  "X_c10"
[12] "X_c11" "X_c12" "X_c13" "X_c14" "X_c15" "X_c16" "X_c17" "X_c18" "X_c19" "X_c20" "X_c21"
[23] "X_c22" "X_c23" "X_c24" "X_c25" "X_c26" "X_c27" "X_c28" "X_c29" "X_c30" "X_c31" "X_c32"
[34] "X_c33" "X_c34" "X_c35" "X_c36" "X_c37" "X_c38" "X_c39" "X_c40"

**Comment by hiltonmbr** [comment]
Dear @javierluraschi,  my solution was:

# (1) A function to fix colnames (remove blanks and characters)
fix.names <- function(x) { ...}

# (2) Load SparkR package via sparklyr
Sys.setenv(SPARK_HOME=paste0(spark_install_dir(),"/",spark_installed_versions()$dir))
.libPaths(c(file.path(Sys.getenv("SPARK_HOME"),"R","lib"),.libPaths()))
library(SparkR)

# (3) Open a connection using SparkR
sc <- sparkR.init(master="local[*]",
                  sparkEnvir = list('spark.executor.memory' = '3g', 
                                    'spark.driver.memory' = '3g',
                                    'spark.driver.maxResultSize'= '3g',
                                    'spark.speculation'='false',
                                    'spark.sql.parquet.mergeSchema'='true'),
                  sparkPackages="com.databricks:spark-csv_2.11:1.4.0")
sc <- sparkRSQL.init(sc)

# (4) Read CSV file using read.df:
df <- read.df(sc, myfile,
              source = "com.databricks.spark.csv",
              header="true",delimiter= ";",
              nullValue="",treatEmptyValuesAsNulls="true",
              inferSchema="true",charset="Latin1"
                )

# (5) Finally, fix colnames:
colnames(df) <- fix.names(colnames(df))

In my understanding, SparkR package provides a lot of interesting functions such as cast(), regexp_replace() and so on... http://spark.apache.org/docs/latest/api/R/index.html

How about you enable users of sparklyr loading SparkR funcions in a easy way? For instance, in multiple connections, how to convert a SparkDataFrame loaded by sparkRSQL.init(sc) to a DataFrame similar to sparklyr (which can handle by dplyr as lazy as possible) ?

**Comment by kevinushey** [comment]
You might need to quote the variable names with e.g. `` `_c1` `` -- does that help?

**Comment by kevinushey** [comment]
We might also want to consider setting the default column names (when no header is specified) to something like `V1`, `V2`, ..., to be more in line with what R does, and also because these will be easier to interact with / mutate from the R side.

**Comment by hiltonmbr** [comment]
It returns the same error. 

df2 <- rename(df, col1 =`_c0`, col2 = `_c1`)

Source: query [?? x 41]
Database: spark connection master=local[*] app=sparklyr local=TRUE

Error: org.apache.spark.sql.AnalysisException: cannot resolve "`_c0`" given input columns: [_c20, _c19, _c18, _c29, _c30, _c8, _c27, _c26, _c14, _c0, _c38, _c15, _c3, _c39, _c36, _c35, _c37, _c17, _c5, _c11, _c31, _c33, _c6, _c25, _c34, _c28, _c10, _c12, _c40, _c32, _c9, _c2, _c21, _c22, _c1, _c23, _c4, _c7, _c13, _c24, _c16]; line 2 pos 13
at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)

**Comment by hiltonmbr** [comment]
For instance, in data.table fread function, the default column names are V1, V2, .... as you pointed out.

**Comment by kevinushey** [comment]
Thanks @hiltonmbr -- just to complicate matters a bit, it looks like the default column names used differ between Spark 1.6.1 and Spark 2.0.0:

```
> library(sparklyr)
> sc  <- spark_connect(master = "local", version = "1.6.1")
> file <- tempfile()
> cat("1,2,3\n4,5,6\n7,8,9\n", file = file, sep = "\n")
> spark_read_csv(sc, "data", normalizePath(file), header = FALSE, memory = FALSE)
Source:   query [?? x 3]
Database: spark connection master=local[8] app=sparklyr local=TRUE

     C0    C1    C2
  <chr> <chr> <chr>
1     1     2     3
2     4     5     6
3     7     8     9
```

versus

```
> library(sparklyr)
> sc  <- spark_connect(master = "local", version = "2.0.0-preview")
> file <- tempfile()
> cat("1,2,3\n4,5,6\n7,8,9\n", file = file, sep = "\n")
> spark_read_csv(sc, "data", normalizePath(file), header = FALSE, memory = FALSE)
Source:   query [?? x 3]
Database: spark connection master=local[8] app=sparklyr local=TRUE

    _c0   _c1   _c2
  <int> <int> <int>
1     1     2     3
2     4     5     6
3     7     8     9
```

We should definitely normalize the names for unnamed tables so that they are consistent across Spark versions with our API.

**Comment by kevinushey** [comment]
I just pushed a commit that normalizes the column names as `V1`, `V2`, ... when `header = FALSE` in `spark_read_csv`. With this, the `dplyr::rename` interface should function as you expect. Can you try reinstalling `sparklyr` from master and let us know if that fixes things for you?

    devtools::install_github('rstudio/sparklyr')

**Comment by javierluraschi** [comment]
No additional changes seem required here... closing.

**Comment by D3V4N5H** [comment]
Hi. Excellent fix.

I am trying to 
```df.write.format("parquet").saveAsTable(table_name)```

Can you add this serialization for this too?
Because I'm getting 
```org.apache.spark.sql.AnalysisException: Attribute name &#34;Summary Quote&#34; contains invalid character(s) among &#34; ,;{}()\n\t=&#34;. Please use alias to rename it.;```

because I have a space in a column's name.
