### ISSUE TITLE
Error setting spark_config params

### ISSUE THREAD

**Issue by keccah** [rstudio/sparklyr#93]
When connecting to yarn cluster, the only param accepted is sparklyr.driver.memory. I'm setting sparklyr.num.executors and a set of other params that are being ignored by Spark config. What am I doing wrong?

**Comment by javierluraschi** [comment]
@keccah The properties you intend to pass to spark-submit can be pass with the prefix `sparklyr.shell.` (for a list of available parameters see https://spark.apache.org/docs/latest/submitting-applications.html#launching-applications-with-spark-submit). For the `--num-executors` parameter you would want to pass is as:

```
config <- spark_config()
config[["sparklyr.shell.num-executors"]] <- 2
sc <- spark_connect(master = "local", config = config)
```

To set parameters in the `SparkContext`, you can pass them with the prefix `spark.`, so, for all these properties (http://spark.apache.org/docs/latest/configuration.html#available-properties) can be passed as:

```
config <- spark_config()
config[["spark.executor.memory"]] <- "2G"
sc <- spark_connect(master = "local", config = config)
```

**Comment by javierluraschi** [comment]
@keccah let us know if the suggestion above did not resolve this issue. I would also recommend upgrading to the latest version of sparklyr by running `devtools::install_github("rstudio/sparklyr")` followed by a restart of your r session. In the meantime, I'll be closing this issue but feel free to activate if this code doesn't work as your would expect.

**Comment by keccah** [comment]
Still not working. The params are not being passed to Spark.

![image](https://cloud.githubusercontent.com/assets/833577/16780920/2b10638c-484f-11e6-9bc8-6f7cf0d4c1c2.png)

I'm using yarn-client as master.

First I set a number of environment variables: HADOOP_CONF_DIR, HADOOP_USER_NAME, SPARK_HOME

Then I write:
`config <- spark_config()
config[["sparklyr.shell.num-executors"]] <- 4
config[["sparklyr.shell.executor-memory"]] <- "16G"
config[["sparklyr.shell.driver-memory"]] <- "4G"
config[["sparklyr.shell.executor-cores"]] <- 5
sc <- spark_connect(master = "yarn-client", hadoop_version = "2.4", config = config)`

The connection is made and Spark UI opens but without the parameters I'm passing.

**Comment by keccah** [comment]
This works. But only in SparkR (not Sparklyr).

`Sys.setenv('SPARKR_SUBMIT_ARGS'='"-v" "--packages" "com.databricks:spark-csv_2.10:1.3.0" "--conf" "spark.driver.memory=4g" "--conf" "spark.executor.memory=16g" "--conf" "spark.executor.cores=5" "--conf" "spark.executor.instances=4" "sparkr-shell"')`

Not I get all my parameters. 

![image](https://cloud.githubusercontent.com/assets/833577/16781836/6fbe4ec8-4853-11e6-98b4-8e0de599e7ad.png)

I tried the same thing in sparklyr but --conf was passing only one parameter no matter what.

**Comment by javierluraschi** [comment]
@keccah I believe you want to use this instead:

```
config <- spark_config()
config[["spark.executors.instances"]] <- 4
config[["spark.executor.memory"]] <- "16G"
config[["spark.driver.memory"]] <- "4G"
config[["spark.executor.cores"]] <- 5
sc <- spark_connect(master = "yarn-client", config = config)
```

There are a couple different ways to pass parameters into Spark:
1) Passing them through the shell, using `sparklyr.shell.*`
2) Passing them through the SparkContext, using `spark.*`
3) Passing them through the HiveContext or SessionContext, using `spark.sql.*`

Let us know how this goes.

**Comment by fereshtehRS** [comment]
@keccah I am running on Google Dataproc, and followed @javierluraschi's instructions as follows:

config <- spark_config()
config[["spark.executor.memory"]] <- "4G"
sc <- spark_connect(master = "yarn-client", config = config)

With this settings and connection, I ran a job and disconnected, and then checked the environment in the job status; it was set correctly:

![spark-config](https://cloud.githubusercontent.com/assets/4906984/16782844/69414ba8-484f-11e6-9394-931d96034e85.png)

**Comment by fereshtehRS** [comment]
Let us know what environment you are running on, may be there is a difference.

**Comment by keccah** [comment]
I did exactly as @javierluraschi did. Still not working. T_T

![image](https://cloud.githubusercontent.com/assets/833577/16821377/577b1146-492c-11e6-961d-a07ce6bd4e13.png)

**Comment by keccah** [comment]
@javierluraschi and @fereshtehRS it worked! 

![image](https://cloud.githubusercontent.com/assets/833577/16841059/f5760f64-49ad-11e6-8cd8-776a5ef1e84b.png)

I wonder though if there's anyway to make the query using "spark_read_parquet" and not uploading the table to memory until I do any collect command.

**Comment by fereshtehRS** [comment]
Nice :)
Did you have to do anything special to make it work?

I don't know the answer to your question; leave it to @javierluraschi to answer.

**Comment by javierluraschi** [comment]
@keccah you can load the data with `spark_read_parquet(sc, name, path, memory = FALSE)`. By default, sparklyr loads all data into memory.
