### ISSUE TITLE
Out of Bag (OOB) for sparklyr Random Forest

### ISSUE THREAD

**Issue by dsblr** [rstudio/sparklyr#935]
Hello Sparklyr team,
This is not an issue. I would like to know more about sparklyr randomforest implementation.

Is there a way we can find OOB(out of bag error) from trained random forest model as R Random forest model?
Please help me on OOB for sparklyr Random Forest.

Thanks for your support.

**Comment by kevinykuo** [comment]
@dsblr I don't think this is currently supported in Spark ML and it wouldn't be easy for us to extract it. Note that we're just wrapping the Spark implementation in sparklyr.

**Comment by kevinykuo** [comment]
Closing for now, feel free to open another issue if you discover this is implemented in Spark.
