### ISSUE TITLE
ML Pipelines

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#944]
Related to:
- https://github.com/rstudio/sparklyr/issues/196: cross validation function and parameter tuning
- https://github.com/rstudio/sparklyr/issues/212: consider support for model deployment and docs
- https://github.com/rstudio/sparklyr/issues/336: ml_save fails in yarn-client mode, pipelines would allow us to save models with ease?
- https://github.com/rstudio/sparklyr/issues/1070 model persistence issues
- https://github.com/rstudio/sparklyr/issues/907: order of probabilities in output vector is confusing
- https://github.com/rstudio/sparklyr/issues/928: difficult to get predicted labels
- https://github.com/rstudio/sparklyr/issues/762: inconsistent prediction output column names
- https://github.com/rstudio/sparklyr/issues/605: `ft_index_to_string()` doesn't behave as expected
- #593: How to create Array of `PipelineStage`
- #734: Support ML pipelines
- https://github.com/rstudio/sparklyr/issues/692 and https://github.com/rstudio/sparklyr/issues/954: dummy variable creation doesn't respect reference level argument
- https://github.com/rstudio/sparklyr/issues/986: Bisecting k-means
- https://github.com/rstudio/sparklyr/issues/622: Efficiency of categorical variable transformations
- https://github.com/rstudio/sparklyr/issues/554: Support interactions in formulas

**Comment by efh0888** [comment]
So any update on this (#196)?

**Comment by kevinykuo** [comment]
@efh0888 see the reply at https://github.com/rstudio/sparklyr/issues/196. Thanks!
