### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/sparklyr#948]
Milestone feature tracking, in priority:

1. Making Spark operations cancellable
2. Showing Spark operations progress

Related to:
- https://github.com/rstudio/sparklyr/issues/297: SparkContext lost after stopping operation in console
- https://github.com/rstudio/sparklyr/issues/157: Long operations do not always cancel

**Comment by javierluraschi** [comment]
We will probably need something like:
- [SparkStatusTracker](https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.SparkContext@statusTracker:org.apache.spark.SparkStatusTracker)
- [Support to flush connections](https://github.com/rstudio/sparklyr/commit/25a30576858572854df522b1f5d9b1d7eff16ccf)

Currently, `sparklyr` waits for the server to respond, when a connection gets interrupted the connection breaks but not closes. The problem is that triggering a command after a connection is interrupted will read the network buffer from the previous connection. Instead, we want to "flush" the read buffer before running `invoke()` to prevent previous old/inconsistent responses from being read. This [commit](https://github.com/rstudio/sparklyr/commit/25a30576858572854df522b1f5d9b1d7eff16ccf) explores a potential solution which is to use a non-blocking socket and manage the reads ourselves. However, we will also need to check the status of the job and cancel it if we trigger an `invoke()` after an interruption; otherwise, we could still get results from the previous invoke when the long invoke finishes after the interruption.

**Comment by russellpierce** [comment]
@javierluraschi It seems like closing the connection that is in a bad state and reopening it is sufficient to allow one to resume working on Spark.  As a stop gap, is there a way to detect that the connection has gone into a bad state / could we build one?  It seems clear something in printing a spark context in this state creates an error, but it just prints to console rather than showing up as an error.  If we could surface that the connection went into a bad state at least we'd have a way of recovering.

**Comment by javierluraschi** [comment]
@russellpierce improvements are now enabled in `master` branch, you can install with:

```
devtools::install_github("rstudio/sparklyr")
```

Notice that I expect there to be a few issues to be sorted out in the next week or so, so consider reverting to CRAN version and opening github issues as needed. Feedback welcomed, thanks!

**Comment by russellpierce** [comment]
I'm out of office this week, but I'll install in my test environment on Monday and see what shakes out.

**Comment by javierluraschi** [comment]
@russellpierce forgot to mention, if you are interested in support for cancelling operations, installing `sparklyr` is enough; if you want to try out also the job progress UI in RStudio, you would need the latest daily build: [dailies.rstudio.com](https://dailies.rstudio.com).
