### ISSUE TITLE
Joins are not registering all columns in table

### ISSUE THREAD

**Issue by AndersAsa** [rstudio/sparklyr#960]
Joins are not registering the second "by" column which prevents more than one join at a time, or joins inside of loops.

```r
spark_version <- "2.1.0"
sc <- spark_connect(master = "local", version = spark_version)

x <- data.frame(a = c(NA,"b","b,","c"), b = 1:4) %>% copy_to(sc,.,'x')
y <- data.frame(c = c("a","b","b,",NA), d = 5:8) %>% copy_to(sc,.,'y')
z <- data.frame(e = c("a","b",NA,"c"), f = 9:12) %>% copy_to(sc,.,'z')

joined <- x %>% full_join(y, by = c("a" = "c"))

full_join(joined,z, by = c("c" = "e"))
```
Error: `by` can't contain join column `c` which is missing from LHS

```r
tbl_vars(joined)
```
[1] "a" "b" "d"
```r
tbl_vars( joined %>% collect() )
```
[1] "a" "b" "c" "d"

**Comment by kevinykuo** [comment]
This is expected behavior, column `c` is dropped since `a` is kept in the first join.

**Comment by AndersAsa** [comment]
Actually, column c is not dropped. Column c is still in the spark table as is shown after the collect() command. Also, whenever there is a value for column c without a match in column a, column a becomes NA. This is not the behavior I would expect if column c is to be dropped. I would expect column a to take the value of column c.

**Comment by kevinykuo** [comment]
@AndersAsa Weird, I'm unable to reproduce:

```
> joined
# Source:   lazy query [?? x 3]
# Database: spark_connection
      a     b     d
  <chr> <int> <int>
1     b     2     6
2  <NA>     1    NA
3  <NA>    NA     8
4     a    NA     5
5     c     4    NA
6    b,     3     7
> collect(joined)
# A tibble: 6 x 3
      a     b     d
  <chr> <int> <int>
1     b     2     6
2  <NA>     1    NA
3  <NA>    NA     8
4     a    NA     5
5     c     4    NA
6    b,     3     7
```

Could you update `dplyr` + `dbplyr` and try again?

**Comment by AndersAsa** [comment]
Thanks, look like this was a problem with older versions of dplyr + dbplyr
