### ISSUE TITLE
spark_apply: subscript out of bounds

### ISSUE THREAD

**Issue by haifenghan** [rstudio/sparklyr#962]
Following the tutorial, I run the following R code:
```
library(sparklyr)
sc <- spark_connect(master = "local")
library(dplyr)
iris_tbl <- copy_to(sc, iris)
spark_apply(iris_tbl, function(data) {rbind(data,data)})
```
Now everything is OK. 

However, to run the following similar code there will be an error:

`spark_apply(iris_tbl, function(data) {cbind(data,data)})`

> Error in column_names[[idx]] : subscript out of bounds

Consulting the manual for the function f:

> A function that transforms a data frame partition into a data frame. The function f has signature f(df, group1, group2, ...) where df is a data frame with the data to be processed and group1 to groupN contain the values of the group_by values. When group_by is not specified, f takes only one argument.

My function definition receives a data.frame argument and returns a data.frame argument. It obey above rules. I can't understand the error message. 

Could you please help me with it?

Thanks

**Comment by javierluraschi** [comment]
@haifenghan for sure, in `sparklyr 0.6.2` (the published version in CRAN), `spark_apply()` requires all column names to be specified, so you want to run instead something like:

```
spark_apply(
  iris_tbl,
  function(data) {cbind(data,data)},
  columns = c(colnames(iris_tbl), paste0(colnames(iris_tbl), "2"))
)
```

Alternatively, you could install `sparklyr` from github since `spark_apply()` now supports auto-naming missing columns by running:

```
devtools::install_github("rstudio/sparklyr")
```

**Comment by haifenghan** [comment]
Yes, I tried the latest version and it works fine. The output is:

```
# Source:   table<sparklyr_tmp_af6be8986f3> [?? x 10]
# Database: spark_connection
   Sepal_Length Sepal_Width Petal_Length Petal_Width Species    X6    X7    X8
          <dbl>       <dbl>        <dbl>       <dbl>   <chr> <dbl> <dbl> <dbl>
 1          5.1         3.5          1.4         0.2  setosa   5.1   3.5   1.4
 2          4.9         3.0          1.4         0.2  setosa   4.9   3.0   1.4
 3          4.7         3.2          1.3         0.2  setosa   4.7   3.2   1.3
 4          4.6         3.1          1.5         0.2  setosa   4.6   3.1   1.5
 5          5.0         3.6          1.4         0.2  setosa   5.0   3.6   1.4
 6          5.4         3.9          1.7         0.4  setosa   5.4   3.9   1.7
 7          4.6         3.4          1.4         0.3  setosa   4.6   3.4   1.4
 8          5.0         3.4          1.5         0.2  setosa   5.0   3.4   1.5
 9          4.4         2.9          1.4         0.2  setosa   4.4   2.9   1.4
10          4.9         3.1          1.5         0.1  setosa   4.9   3.1   1.5
# ... with more rows, and 2 more variables: X9 <dbl>, X10 <chr>

```
