### ISSUE TITLE
Issues with spark_apply() in datasets containing NA

### ISSUE THREAD

**Issue by kovla** [rstudio/sparklyr#971]
This is related to the issue #774. Even though that issue has been closed, it would seem that even in version 0.6.0 the issue still exists in some form. Here is an example: 

```
library(sparklyr)
library(dplyr)

sc <- spark_connect(master = 'local')

na_tbl_local <- structure(list(A = c(1L, 1L, 1L, 1L, 1L, 1L), 
                               B = c(NA, 1L, NA, 1L, 1L, NA), 
                               C = c(NA, NA, 1L, NA, NA, NA), 
                               D = c(1L, NA, NA, NA, NA, NA), 
                               E = c(NA, NA, NA, 1L, NA, NA), 
                               F = c(NA, NA, NA, NA, NA, 1L)), 
                          .Names = c("A", "B", "C", "D", "E", "F"), 
                          row.names = c(NA,-6L), 
                          class = c("tbl_df", "tbl", "data.frame"))

iris_tbl <- copy_to(sc, iris)
na_tbl <- copy_to(sc, na_tbl_local, name="na_tbl")

spark_apply(iris_tbl, function(data) {
  I(data)
})

spark_apply(na_tbl, function(data) {
  I(data)
})
```

The first `spark_apply()` performs adequately, whereas the second one throws an error. I've first tried running this example on a remote EC2 cluster with spark 2.2.0 and sparklyr 0.6.0, and I appended the error in a comment to #774, so I won't repeat it here. Today I've installed the development version from github (0.7.0-9014), and tried running the same code locally. The error is then: 

```
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'C:\Users\MAXIMK~1\AppData\Local\Temp\RtmpeUitBY\file2ea0b34c56_spark.log': Permission denied
```

**Comment by javierluraschi** [comment]
@kovla thanks for pointing this out, fixed. Please upgrade to `sparklyr 0.7.0-9016`.

**Comment by javierluraschi** [comment]
@kovla Please use version `0.7.0-9017` instead, the previous one was missing to rebuild `jars`

**Comment by northeastloon** [comment]
I am also getting this error using glm within spark apply. All na / nulls were removed on the data beforehand.
