### ISSUE TITLE
Possible reversion on dim()/ncol()?

### ISSUE THREAD

**Issue by JohnMount** [rstudio/sparklyr#976]
It looks like none of dim()/ncol()/nrow() are currently returning non-`NA` values on the current version of `sparklyr`.  I get that counting rows is expensive (and you may not want to do that) but it seems like the system had fewer `NA`s when this was addressed in [issue 346](https://github.com/rstudio/sparklyr/issues/346).

``` r
suppressPackageStartupMessages(library("dplyr"))
library("sparklyr")
packageVersion("dplyr")
#> [1] '0.7.2.9000'
packageVersion("sparklyr")
#> [1] '0.6.2'
packageVersion("dbplyr")
#> [1] '1.1.0.9000'

sc <- spark_connect(master = 'local')
#> * Using Spark: 2.1.0
d <- dplyr::copy_to(sc, data.frame(x = 1:2))
dim(d)
#> [1] NA
ncol(d)
#> [1] NA
nrow(d)
#> [1] NA


spark_disconnect(sc)
```

**Comment by kevinykuo** [comment]
See https://github.com/rstudio/sparklyr/pull/890

**Comment by kevinykuo** [comment]
Thanks for the writeup at http://www.win-vector.com/blog/2017/08/why-to-use-the-replyr-r-package/. Leaving this open so we can take a deeper look before the next release; I think at a minimum we should have a message on why these functions don't work if nothing else.

**Comment by JohnMount** [comment]
@kevinykuo Thanks for all you do on this project- I have been impressed.  I do understand it is not my decision.

**Comment by kevinykuo** [comment]
Closing this one. Now we have `nrow()` returning NA (`NA_real_`) and `ncol()` returning a value to be consistent with other backends. Note that `ncol()` can still be expensive.
