### ISSUE TITLE
livy and config()

### ISSUE THREAD

**Issue by xhudik** [rstudio/sparklyr#978]
```
livy_service_start()
config <- spark_config()
config$spark.sql.exec.dynamic.partition <- "true"
config$spark.sql.exec.dynamic.partition.mode <- "nonstrict"

config
$sparklyr.cores.local
[1] 8

$spark.sql.shuffle.partitions.local
[1] 8

$spark.env.SPARK_LOCAL_IP.local
[1] "127.0.0.1"

$sparklyr.csv.embedded
[1] "^1.*"

$`sparklyr.shell.driver-class-path`
[1] ""

$spark.sql.exec.dynamic.partition
[1] "true"

$spark.sql.exec.dynamic.partition.mode
[1] "nonstrict"

attr(,"config")
[1] "default"
attr(,"file")
[1] "/home/tomas/DataScience/moory/packrat/lib/x86_64-pc-linux-gnu/3.4.1/sparklyr/conf/config-template.yml"
```

If I try to connect:

```
sc <- spark_connect(master = "http://example:8998", method = "livy", config = config)
Error in value[[3L]](cond) : 
  Failed to initialize livy connection: no applicable method for 'invoke' applied to an object of class "function"
```

however it works if I connect locally, or connect remotely but without customized `config` 
```
#works
sc <- spark_connect(master = "local", method = "livy", config = config)
17/08/31 09:37:20 INFO InteractiveSession$: Creating LivyClient for sessionId: 0
17/08/31 09:37:20 WARN RSCConf: Your hostname, kovral, resolves to a loopback address; using 172.16.245.1  instead (on interface vmnet8)
17/08/31 09:37:20 WARN RSCConf: Set 'livy.rsc.rpc.server.address' if you need to bind to another address.
17/08/31 09:37:20 INFO InteractiveSessionManager: Registering new session 0
17/08/31 09:37:21 INFO ContextLauncher: 17/08/31 09:37:21 INFO RSCDriver: Connecting to: 172.16.245.1:41993
17/08/31 09:37:21 INFO ContextLauncher: 17/08/31 09:37:21 INFO RSCDriver: Starting RPC server...
...

#works
sc <- spark_connect(master = "http://example:8998", method = "livy")
```

I would guess it has something in common with https://github.com/rstudio/sparklyr/issues/957 (there are some sparklyr functions that works locally but have issues if there is a real network; or there is something wrong with ports and the error message is misleading)

**Comment by kevinykuo** [comment]
I'm unable to reproduce. Could you try updating sparklyr/spark/livy?

```
> library(sparklyr)
> config <- spark_config()
> config$spark.sql.exec.dynamic.partition <- "true"
> config$spark.sql.exec.dynamic.partition.mode <- "nonstrict"
> sc2 <- spark_connect(master = "http://localhost:8998/", method = "livy",
+                      config = config)
> sc2
$master
[1] "http://localhost:8998"

$sessionId
[1] 3

$config
$config$sparklyr.cores.local
[1] 8

$config$spark.sql.shuffle.partitions.local
[1] 8

$config$spark.env.SPARK_LOCAL_IP.local
[1] "127.0.0.1"

$config$sparklyr.csv.embedded
[1] "^1.*"

$config$`sparklyr.shell.driver-class-path`
[1] ""

$config$spark.sql.exec.dynamic.partition
[1] "true"

$config$spark.sql.exec.dynamic.partition.mode
[1] "nonstrict"

attr(,"config")
[1] "default"
attr(,"file")
[1] "/Library/Frameworks/R.framework/Versions/3.4/Resources/library/sparklyr/conf/config-template.yml"

$code
<environment: 0x11220c0b0>

$log
[1] "/var/folders/1z/808_xcnx2fx8d9d2l4d8_hqr0000gn/T//RtmpUqjnYA/file2d9824805417.log"

$spark_context
<jobj[0]>
  class org.apache.spark.SparkContext
  org.apache.spark.SparkContext@59fe9973

$java_context
<jobj[1]>
  class org.apache.spark.api.java.JavaSparkContext
  org.apache.spark.api.java.JavaSparkContext@1c4691dd

$hive_context
<jobj[4]>
  class org.apache.spark.sql.SparkSession
  org.apache.spark.sql.SparkSession@3a51d357

attr(,"class")
[1] "spark_connection" "livy_connection"  "DBIConnection"   
[4] "DBIConnection"   
> 
```

**Comment by xhudik** [comment]
Hi Kevinykou,

I like the trick with master (`master="http://localhost:8998/"`) !

Well, the situation is that I have newest *livy* (version: 3.0.0; this is true for client as well as server) and newest sparklyr (from github), however I cannot change Spark since it is server (more people is using it). Spark is 2.0.1

Question - can we say that sparklyr works only with some versions of spark and if the version is different it can emit strange, meaningless error messages?

**Comment by kevinykuo** [comment]
Oh my bad I just re-read your post and you're having issues with a *remote* livy connection so of course I wasn't able to reproduce it!

It could be that the server doesn't like the `spark.sql.exec.dynamic.partition` settings; I'm not familiar with that one but does `hive.exec.dynamic.partition` work?

Regarding your question regarding versions – we try to support Spark 1.6 and later and give informative error messages if a feature isn't supported, and we can probably do better than `Failed to initialize livy connection: no applicable method for 'invoke' applied to an object of class "function"`.

It may be tougher to troubleshoot this one since we don't have access to your server, but could you post the `traceback()` result after the error?

**Comment by xhudik** [comment]
you are right - it is hard to troubleshoot...

I tried to reproduce on localhost with Spark 2.0.0 but livy doesnt work with "versions":
```
library(sparklyr)
config <- spark_config()
config$spark.sql.exec.dynamic.partition <- "true"
config$spark.sql.exec.dynamic.partition.mode <- "nonstrict"
livy_service_start()
sc3 <- spark_connect(master = "http://localhost:8998/",version = "2.0.0", method = "livy",config = config)

...
Warning message:
In livy_connection_not_used_warn(version) :
  Livy connections do not support version parameter :(
```


I'm wondering if it is something with Spark version, or network (i dont think it is network, since other livy commands work well)

**Comment by kevinykuo** [comment]
Not sure if you have ssh access to a node on the cluster, but have you tried using this `spark.sql.exec.dynamic.partition` config via `spark-shell`? I wasn't able to locate the setting in a search but `hive.exec.dynamic.partition` came up so I wonder if that would serve your purpose?

**Comment by andresperezl** [comment]
@xhudik What happens if you use `livy_config()` function instead of `spark_config` when creating the configuration object

**Comment by xhudik** [comment]
hmm, strange with a new HDP 2.6 and Spark 2.2 - it is working well.

What might had been problem: I set `SPARK_MAJOR_VERSION=2` which is fine, however I might have accidentally run `livy-server` instead of `livy2-server`

thanks!
