### ISSUE TITLE
how to combine multiple operations at once without loading the data multiple times?

### ISSUE THREAD

**Issue by randomgambit** [rstudio/sparklyr#979]
Hello there!

Great job! The new version of `sparklyr` is much more efficient than before and the documentation has been hugely improved! Keep up the good work.

There is something I was not able to figure out. Lets say I have a huge dataset and I do something like:

```
df <- spark_read_csv(sc, "df", "2008.csv.bz2", memory = FALSE)
df_one <- df %>% filter(myvar == 'one') %>% collect()
df_two <- df %>% filter(myvar == 'two') %>% collect()
```

Right now, the data gets loaded **ENTIRELY TWO TIMES** to create df_one and df_two. But theoretically, the two tasks could be combined with just one pass on the data. Is `Sparklyr` able to do so? Am I missing something?

Thanks!

**Comment by kevinykuo** [comment]
To speed things up, try
1. Call `spark_read_csv()` with `infer_schema = FALSE`. This prevents Spark from going through the entire file.
2. Cache or persist intermediate datasets. If `df` is too big to fit into memory, try persisting `filter(df, myvar %in% c("one", "two"))`.

**Comment by randomgambit** [comment]
@kevinykuo thanks! solution 2. is very nice indeed. you mean using caching right? regarding solution 1. I dont see what `infer_schema` is doing or not doing. There is nothing about this in the documentation.

Thanks again!

**Comment by javierluraschi** [comment]
1. Right, as in `df_subset <- df %>% filter(myvar %in% c("one", "two")) %>% compute()`
2. You do need to specify your own schema, in the docs we mention:

```
columns: A vector of column names or a named vector of column types.
```

So for character columns, you could pass `columns = list(one = "character", two = "character")`

**Comment by randomgambit** [comment]
@javierluraschi  very useful, thanks!

**Comment by kevinykuo** [comment]
BTW, from `?spark_read_csv`: 

> infer_schema | Boolean; should column types be automatically inferred? Requires one extra pass over the data. Defaults to TRUE.

IIRC you might be able to get away without specifying a schema; it should read everything in as `character`.

**Comment by javierluraschi** [comment]
Closing this one, seems we've addressed all/most of the questions.
