### ISSUE TITLE
rollapply for large data using sparklyr

### ISSUE THREAD

**Issue by jairajgupta** [rstudio/sparklyr#981]
Can you please help with this problem:
https://stackoverflow.com/questions/46024271/rollapply-for-large-data-using-sparklyr

**Comment by javierluraschi** [comment]
Followed up on https://stackoverflow.com/questions/46024271/rollapply-for-large-data-using-sparklyr/46064211#46064211, closing this one.

**Comment by kevinykuo** [comment]
@jairajgupta if your VaR calculation is univariate in the sense that you're calculating it for each symbol, you may be able to use `spark_apply()` assuming that you can collect each symbol's data onto one node. Here's a snippet (not working yet) that should get you started:

```
var_sp <- lmanagers_sp %>%
  spark_apply(function(df) {
    require(dplyr)
    df %>%
      arrange(variable, date) %>%
      mutate(var=zoo::rollapply(
        value, 10,
        FUN=function(x) PerformanceAnalytics::VaR(x, p=.95, method="modified",align = "right"), partial=T))
  }, group_by = "variable")
```
