### ISSUE TITLE
sparklyr spark_connect issue from RStudio

### ISSUE THREAD

**Issue by gvshankar** [rstudio/sparklyr#984]
# Reporting an Issue with sparklyr
I have a problem that seems to come only from RStudio, but works fine from R.  

Have R (R version 3.3.2), RStudio (Version 1.0.153) installed on a Linux server (Red Hat Enterprise Linux Server release 6.7 (Santiago)).  I am just running these 4 commands, works fine under R, but RStudio give errors.

```r
----
R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
> library(sparklyr)
> library(dplyr)
> config <- spark_config()
> sc <- spark_connect(master="yarn-client", config=config, version = '2.2.0')
>
```

RStudio:
```r
R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
> library(sparklyr)
> library(dplyr)
> config <- spark_config()
> sc <- spark_connect(master="yarn-client", config=config, version = '2.2.0')
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (4960): Gateway in port (8880) did not respond.
    Path: /opt/cloudera/parcels/SPARK2-2.2.0.cloudera1-1.cdh5.12.0.p0.142354/lib/spark2/bin/spark-submit
    Parameters: --class, sparklyr.Shell, '/usr/lib64/R/library/sparklyr/java/sparklyr-2.2-2.11.jar', 8880, 4960
    Log: /tmp/Rtmpvtp1bo/file3b22eb8d9f0_spark.log

---- Output Log ----
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream
	at org.apache.spark.deploy.SparkSubmitArguments.handleUnknown(SparkSubmitArguments.scala:465)
	at org.apache.spark.launcher.SparkSubmitOptionParser.parse(SparkSubmitOptionParser.java:178)
	at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:104)
-------
```

JAVA:  /usr/java/jdk1.8.0_92/jre
SPARK:  spark-2.2

I have one other Hadoop environment running under Linux 7, everything works fine there.

Shankar

**Comment by javierluraschi** [comment]
@gvshankar my guess is that we are missing to set environment variables in your RStudio session.

Could you compare `Sys.getenv()` while running from R and while running from RStudio, find the ones that could be Spark/HDFS/Yarn related and set them in your RStudio session with `Sys.setenv()` and retry connecting?

Some other questions if the above suggestion does not work:
- Could you share `Sys.getenv()` from R and RStudio?
- Is that the full output in `---- Output Log ----`?
- Which distribution of Spark is the cluster running? Standalone? CDH? Hortonworks?
- Do you happen to know if HDFS is enabled in the cluster?

**Comment by gvshankar** [comment]
I did see some differences between the R session and RStudio which I have corrected.  But the error still comes up in RStudio.  
> sc <-spark_connect(master="yarn-client", config=config, version = '2.1.0')

Error inforce(code) : 

  Failedwhile connecting to sparklyr to port (8880) for sessionid (6791): Gateway inport (8880) did not respond.

   Path:/opt/cloudera/parcels/SPARK2-2.2.0.cloudera1-1.cdh5.12.0.p0.142354/lib/spark2/bin/spark-submit

   Parameters: --class, sparklyr.Shell,'/usr/lib64/R/library/sparklyr/java/sparklyr-2.2-2.11.jar', 8880, 6791

   Log: /tmp/RtmpkFXR7T/filef374fe6572b_spark.log


 
Also get the same error on both R and RStudio, when trying to use "rsparkling" and "h2o".
Like I mentioned before, I have a Hadoop cluster running under Linux 7, there I don't have any problem.
[ham-lnx-vs-0086]$ RR version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
> Sys.getenv()HADOOP_CONF_DIR         /etc/hadoop/conf.cloudera.hdfsHADOOP_HOME             /opt/cloudera/parcels/CDHHIVE_CLASSPATH          $(find $HADOOP_HOME/lib/hive/lib/ -name *.jar -not -name guava* -print0 | sed s/\x0/,/g)JAVA_HOME               /usr/java/jdk1.8.0_92/jreKRB5CCNAME              FILE:/tmp/krb5cc_550598_EA4TMNLD_LIBRARY_PATH         /usr/lib64/R/lib:/usr/java/jdk1.8.0_92/jre/lib/amd64/serverPATH                    $HADOOP_HOME/bin:$PATHR_HOME                  /usr/lib64/RR_INCLUDE_DIR           /usr/include/RR_LIBS_SITE             /usr/local/lib/R/site-library:/usr/local/lib/R/library:/usr/lib64/R/library:/usr/share/R/libraryR_LIBS_USER             ~/R/x86_64-redhat-linux-gnu-library/3.3SPARK_DIST_CLASSPATH    /etc/hadoop/conf:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop/lib/*:                        $HADOOP_HOME/lib/hadoop/libexec/../../hadoop/.//*:                        $HADOOP_HOME/lib/hadoop/libexec/../../hadoop-hdfs/./:                        $HADOOP_HOME/lib/hadoop/libexec/../../hadoop-hdfs/lib/*:                        $HADOOP_HOME/lib/hadoop/libexec/../../hadoop-hdfs/.//*:                        $HADOOP_HOME/lib/hadoop/libexec/../../hadoop-yarn/lib/*:                        $HADOOP_HOME/lib/hadoop/libexec/../../hadoop-yarn/.//*:                        $HADOOP_HOME/lib/hadoop-mapreduce/lib/*:                        $HADOOP_HOME/lib/hadoop-mapreduce/.//*SPARK_HOME              /opt/cloudera/parcels/SPARK2/lib/spark2YARN_CONF_DIR           /etc/hadoop/conf.cloudera.yarn>
------------------------------------------------------------------------
RStudio:
R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
> Sys.getenv()HADOOP_HOME             /opt/cloudera/parcels/CDHHADOOP_CONF_DIR         /etc/hadoop/conf.cloudera.hdfsHIVE_CLASSPATH          $(find /opt/cloudera/parcels/CDH/lib/hive/lib/ -name *.jar -not -name guava* -print0 | sed s/\x0/,/g)JAVA_HOME               /usr/java/jdk1.8.0_92/jreLD_LIBRARY_PATH         /usr/lib64/R/lib::/lib:/usr/java/jdk1.8.0_92/jre/lib/amd64/serverPATH                    $HADOOP_HOME/bin:$PATHR_HOME                  /usr/lib64/RR_INCLUDE_DIR           /usr/include/RR_LIBS_SITE             /usr/local/lib/R/site-library:/usr/local/lib/R/library:/usr/lib64/R/library:/usr/share/R/libraryR_LIBS_USER             ~/R/x86_64-redhat-linux-gnu-library/3.3RSTUDIO                 1RSTUDIO_HTTP_REFERER    http://ham-lnx-vs-0086.int.8451.com:8787/RSTUDIO_PANDOC          /usr/lib/rstudio-server/bin/pandocSPARK_DIST_CLASSPATH    /etc/hadoop/conf:/opt/cloudera/parcels/CDH/lib/hadoop/libexec/../../hadoop/lib/*:                        /opt/cloudera/parcels/CDH/lib/hadoop/libexec/../../hadoop/.//*:                        /opt/cloudera/parcels/CDH/lib/hadoop/libexec/../../hadoop-hdfs/./:                        /opt/cloudera/parcels/CDH/lib/hadoop/libexec/../../hadoop-hdfs/lib/*:                        /opt/cloudera/parcels/CDH/lib/hadoop/libexec/../../hadoop-hdfs/.//*:                        /opt/cloudera/parcels/CDH/lib/hadoop/libexec/../../hadoop-yarn/lib/*:                        /opt/cloudera/parcels/CDH/lib/hadoop/libexec/../../hadoop-yarn/.//*:                        /opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/lib/*:                        /opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/.//*SPARK_HOME              /opt/cloudera/parcels/SPARK2/lib/spark2YARN_CONF_DIR           /etc/hadoop/conf.cloudera.yarn>
2. Yes, that's the whole error log (besides the Port 8880 not responding message)

---- Output Log----Exception in thread"main" java.lang.NoClassDefFoundError:org/apache/hadoop/fs/FSDataInputStream       at org.apache.spark.deploy.SparkSubmitArguments.handleUnknown(SparkSubmitArguments.scala:465)       atorg.apache.spark.launcher.SparkSubmitOptionParser.parse(SparkSubmitOptionParser.java:178)       atorg.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:104)       at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:112)       at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)Caused by:java.lang.ClassNotFoundException: org.apache.hadoop.fs.FSDataInputStream       at java.net.URLClassLoader.findClass(URLClassLoader.java:381)       at java.lang.ClassLoader.loadClass(ClassLoader.java:424)       at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)       at java.lang.ClassLoader.loadClass(ClassLoader.java:357)       ... 5 more
 
---- Error Log ----

3. I have both Spark 1.6 and Spark 2.2 running on my Cloudera Cluster.  My Cloudera distribution is  CDH 5.10.1
4. I am not sure of the last comment "Is HDFS enabled in the cluster".  The short answer is Yes.  The data is in HDFS, and the regular R runs off of one of the Edge Nodes in the cluster.  R don't have any problem talking to the data in HDFS (sparklyr package) from straight R.
Shankar.

**Comment by hlendway** [comment]
I'm probably missing something but I figured I'd throw out a comment, that's the error I get when I'm no longer authenticated to connect to spark/hadoop via rstudio server.  When that happens, in Rstudio Server I open a shell (tools, shell) and run a kinit, enter my password and then I can connect to spark.

**Comment by gvshankar** [comment]
That definitely is a good point.  I have seen references for it on some of the blogs.  I would try that.
While doing some of these config with RStudio, I have hitting this one problem and it is really frustrating.  I went added some of these missing environment variables to the /usr/lib64/R/etc/Renviron file.  But RStudio doesn't seem to recognize the changes at all.  
Mainly I set the PATH variable by mistake in that file.  I have since then removed it from the file and cycled the "rstudio-server".  But once login and go into RStudio, the PATH variable still has the old wrong value, so I have lost access to all the system functions.
Previously I left the word "export" in front of one of the variable for the HADOOP_HOME variable in this "Renviron" file by mistake.  I have cycled the "rstudio-server".  But when I go into "RStudio", it still shows the "export" word in the "Sys.getenv()" output.
My question is, how do I refresh this list of environment variables for "Sys.getenv()" for RStudio.  The regular R session, always reads from the shell everytime.  But RStudio seems to keep a copy of these variables somewhere.
Any idea how to resolve this problem?  I have seen a couple of blogs all complaining about the same.
Shankar

**Comment by gvshankar** [comment]
I went and killed all the RStudio sessions, cycled the server, cleared the browser cache, then logged back into RStudio.  Now the output of "Sys.getenv()", shows the environment variables correctly.  
I also did a "fresh" kinit in the "shell", entered the password, and got a fresh Kerberos ticket.  'klist', shows my my Kerberos ticket correctly too.  RStudio still gives the same error.

R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
> system2('klist')
Ticket cache: FILE:/tmp/krb5cc_550598
Default principal: v550598@INT.8451.COM

Valid starting     Expires            Service principal
09/08/17 17:15:45  09/09/17 03:15:51  krbtgt/INT.8451.COM@INT.8451.COM
	renew until 09/15/17 17:15:45-----------------------------------------------------------------------------> Sys.getenv()DISPLAY :0EDITOR viGIT_ASKPASS rpostback-askpassHADOOP_CONF_DIR /etc/hadoop/conf.cloudera.hdfsHADOOP_HOME /opt/cloudera/parcels/CDHHIVE_CLASSPATH $(find $HADOOP_HOME/lib/hive/lib/ -name *.jar -not -name guava* -print0 | sed s/\x0/,/g)HOME /home/v550598JAVA_HOME /usr/java/jdk1.8.0_92/jreLANG en_US.UTF-8LD_LIBRARY_PATH /usr/lib64/R/lib::/lib:/usr/java/jdk1.8.0_92/jre/lib/amd64/serverLN_S ln -sLOGNAME v550598MAKE makePAGER /usr/bin/lessPATH  /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/binR_BROWSER /usr/bin/xdg-openR_BZIPCMD /usr/bin/bzip2R_DOC_DIR /usr/share/doc/R-3.3.2R_GZIPCMD /usr/bin/gzipR_HOME /usr/lib64/RR_INCLUDE_DIR /usr/include/RR_LIBS_SITE /usr/local/lib/R/site-library:/usr/local/lib/R/library:/usr/lib64/R/library:/usr/share/R/libraryR_LIBS_USER ~/R/x86_64-redhat-linux-gnu-library/3.3R_PAPERSIZE a4R_PDFVIEWER /usr/bin/xdg-openR_PLATFORM x86_64-redhat-linux-gnuR_PRINTCMD lprR_RD4PDF times,hyperR_SESSION_TMPDIR /tmp/RtmphnCfjAR_SHARE_DIR /usr/share/RR_SYSTEM_ABI linux,gcc,gxx,gfortran,?R_TEXI2DVICMD /usr/bin/texi2dviR_UNZIPCMD /usr/bin/unzipR_ZIPCMD RMARKDOWN_MATHJAX_PATH /usr/lib/rstudio-server/resources/mathjax-26RS_RPOSTBACK_PATH /usr/lib/rstudio-server/bin/rpostbackRSTUDIO 1RSTUDIO_HTTP_REFERER http://ham-lnx-vs-0086.int.8451.com:8787/RSTUDIO_PANDOC /usr/lib/rstudio-server/bin/pandocRSTUDIO_SESSION_STREAM v550598-dRSTUDIO_USER_IDENTITY v550598RSTUDIO_WINUTILS bin/winutilsSED /bin/sedSPARK_DIST_CLASSPATH  /etc/hadoop/conf:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop/lib/*:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop/.//*:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop-hdfs/./:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop-hdfs/lib/*:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop-hdfs/.//*:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop-yarn/lib/*:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop-yarn/.//*:$HADOOP_HOME/lib/hadoop-mapreduce/lib/*:$HADOOP_HOME/lib/hadoop-mapreduce/.//*SPARK_HOME /opt/cloudera/parcels/SPARK2/lib/spark2SSH_ASKPASS rpostback-askpassTAR /bin/gtarUSER v550598YARN_CONF_DIR /etc/hadoop/conf.cloudera.yarn>
> library(sparklyr)
> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> config <- spark_config()
> sc <- spark_connect(master="yarn-client", config=config, version = '2.2.0')
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (552): Gateway in port (8880) did not respond.
    Path: /opt/cloudera/parcels/SPARK2-2.2.0.cloudera1-1.cdh5.12.0.p0.142354/lib/spark2/bin/spark-submit
    Parameters: --class, sparklyr.Shell, '/usr/lib64/R/library/sparklyr/java/sparklyr-2.2-2.11.jar', 8880, 552
    Log: /tmp/RtmphnCfjA/file178a21d8f758_spark.log


---- Output Log ----
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream
	at org.apache.spark.deploy.SparkSubmitArguments.handleUnknown(SparkSubmitArguments.scala:465)
	at org.apache.spark.launcher.SparkSubmitOptionParser.parse(SparkSubmitOptionParser.java:178)
	at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:104)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:112)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.fs.FSDataInputStream
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more

---- Error Log ----
> Shankar

**Comment by hlendway** [comment]
If you look in your .bash_profile in your home directory on the server do you have a JAVA_HOME set?
Mine is the following, yours is likely different pending your JDK number and location....
export JAVA_HOME="/usr/java/jdk1.8.0_92/"

That was also an error I saw before setting up my java home and you are getting a java.lang.ClassNotFoundException.  Worth a check.

**Comment by gvshankar** [comment]
Don't have anything set in the .bash_profile or .bashrc.  All the environment variables other than PATH are set through the /usr/lib64/R/etc/Renviron file.  Besides the defaults, I have added the following to that file
## Spark 1.6.1# SPARK_HOME="/opt/cloudera/parcels/CDH/lib/spark"## Spark 2.2HADOOP_HOME=/opt/cloudera/parcels/CDHSPARK_HOME="/opt/cloudera/parcels/SPARK2/lib/spark2"HADOOP_CONF_DIR="/etc/hadoop/conf.cloudera.hdfs"YARN_CONF_DIR="/etc/hadoop/conf.cloudera.yarn"JAVA_HOME=/usr/java/jdk1.8.0_92/jre
SPARK_DIST_CLASSPATH=/etc/hadoop/conf:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop/lib/*:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop/.//*:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop-hdfs/./:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop-hdfs/lib/*:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop-hdfs/.//*:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop-yarn/lib/*:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop-yarn/.//*:$HADOOP_HOME/lib/hadoop-mapreduce/lib/*:$HADOOP_HOME/lib/hadoop-mapreduce/.//*
HIVE_CLASSPATH=$(find $HADOOP_HOME/lib/hive/lib/ -name '*.jar' -not -name 'guava*' -print0 | sed 's/\x0/,/g')
--------------------------------------------
The thing that bother me is the difference between R and RStudio.  Both R and RStudio are installed on the same server which is an Edge Node on the Hadoop Cluster.  My Hadoop cluster is running on the Oracle Big Data Appliance running under Linux 6.7.
R session seems to read the environment correctly everytime, but RStudio seems to remember the old session values, and I can't seem to make RStudio function intune with R.
Shankar

**Comment by gvshankar** [comment]
I found out that the JAVA JDK version on the Edge Node (where R / RStudio is running) was slightly lower version (/usr/java/jdk1.8.0_92) than the Hadoop Nodes (/usr/java/jdk1.8.0_121).  So, I went and upgraded the JAVA on the R node to the latest (jdk1.8.9_144).  I then reinstalled the "dplyr", "sparklyr" packages in R.
Now, both the R and RStudio give the same error.  
[v550598@ham-lnx-vs-0086 ~]$ R
R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"...> library(sparklyr)> library(dplyr)> config <- spark_config()> sc <- spark_connect(master="yarn-client", config=config, version = '2.2.0')Error in force(code) :  Failed while connecting to sparklyr to port (8880) for sessionid (5895): Gateway in port (8880) did not respond.    Path: /opt/cloudera/parcels/SPARK2-2.2.0.cloudera1-1.cdh5.12.0.p0.142354/lib/spark2/bin/spark-submit    Parameters: --class, sparklyr.Shell, '/usr/lib64/R/library/sparklyr/java/sparklyr-2.2-2.11.jar', 8880, 5895    Log: /tmp/RtmphaTTBJ/file48411ec63e74_spark.log

---- Output Log ----Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream        at org.apache.spark.deploy.SparkSubmitArguments.handleUnknown(SparkSubmitArguments.scala:465)        at org.apache.spark.launcher.SparkSubmitOptionParser.parse(SparkSubmitOptionParser.java:178)        at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:104)        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:112)        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.fs.FSDataInputStream        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)        ... 5 more
---- Error Log ----

> system2('klist')Ticket cache: FILE:/tmp/krb5cc_550598_qiy8EMDefault principal: v550598@INT.8451.COM
Valid starting     Expires            Service principal09/11/17 12:16:29  09/11/17 22:16:29  krbtgt/INT.8451.COM@INT.8451.COM        renew until 09/18/17 12:16:29

> Sys.getenv()HADOOP_CONF_DIR         /etc/hadoop/conf.cloudera.hdfs
HADOOP_HOME                /opt/cloudera/parcels/CDHHIVE_CLASSPATH             $(find $HADOOP_HOME/lib/hive/lib/ -name *.jar -not -name guava* -print0 | sed s/\x0/,/g)JAVA_HOME                       /usr/java/jdk1.8.0_144/jre
LD_LIBRARY_PATH           /usr/lib64/R/lib:/usr/java/jdk1.8.0_92/jre/lib/amd64/serverPATH                                   /opt/anaconda2/bin:/usr/lib64/qt-3.3/bin:/opt/cloudera/parcels/CDH/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/v550598/binSPARK_HOME                   /opt/cloudera/parcels/SPARK2/lib/spark2YARN_CONF_DIR             /etc/hadoop/conf.cloudera.yarn
>
This error appears like that I have missed an environment variable somewhere, just like you suspected, but can't figure out what that could be.  Changing the JAVA seemed to have broken the R session also which used to work before.  I am seeing many blogs with this error, but none of the solutions listed apply.
---- Output Log ----Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream        at org.apache.spark.deploy.SparkSubmitArguments.handleUnknown(SparkSubmitArguments.scala:465)

Shankar      From: Viswanathan Shankar <gvshankar@yahoo.com>
 To: rstudio/sparklyr <reply@reply.github.com>; rstudio/sparklyr <sparklyr@noreply.github.com> 
Cc: Mention <mention@noreply.github.com>
 Sent: Monday, September 11, 2017 9:31 AM
 Subject: Re: [rstudio/sparklyr] sparklyr spark_connect issue from RStudio (#984)
   
Don't have anything set in the .bash_profile or .bashrc.  All the environment variables other than PATH are set through the /usr/lib64/R/etc/Renviron file.  Besides the defaults, I have added the following to that file
## Spark 1.6.1# SPARK_HOME="/opt/cloudera/parcels/CDH/lib/spark"## Spark 2.2HADOOP_HOME=/opt/cloudera/parcels/CDHSPARK_HOME="/opt/cloudera/parcels/SPARK2/lib/spark2"HADOOP_CONF_DIR="/etc/hadoop/conf.cloudera.hdfs"YARN_CONF_DIR="/etc/hadoop/conf.cloudera.yarn"JAVA_HOME=/usr/java/jdk1.8.0_92/jre
SPARK_DIST_CLASSPATH=/etc/hadoop/conf:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop/lib/*:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop/.//*:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop-hdfs/./:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop-hdfs/lib/*:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop-hdfs/.//*:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop-yarn/lib/*:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop-yarn/.//*:$HADOOP_HOME/lib/hadoop-mapreduce/lib/*:$HADOOP_HOME/lib/hadoop-mapreduce/.//*
HIVE_CLASSPATH=$(find $HADOOP_HOME/lib/hive/lib/ -name '*.jar' -not -name 'guava*' -print0 | sed 's/\x0/,/g')
--------------------------------------------
The thing that bother me is the difference between R and RStudio.  Both R and RStudio are installed on the same server which is an Edge Node on the Hadoop Cluster.  My Hadoop cluster is running on the Oracle Big Data Appliance running under Linux 6.7.
R session seems to read the environment correctly everytime, but RStudio seems to remember the old session values, and I can't seem to make RStudio function intune with R.
Shankar

**Comment by hlendway** [comment]
Hmmm we have a similar setup (R and RStudio Server installed on an edge node in the hadoop cluster)  and the only environment variable we set in the Renviron file is the SPARK_HOME="/opt/cloudera/parcels/CDH/lib/spark"
Then I have my JAVA_HOME setup in my bach profile.  
I assumed you've recycled the server again.  Can you try setting the JAVA_HOME in your bash_profile to see if it picks that up and at least gets you up and running?

**Comment by javierluraschi** [comment]
@gvshankar There are some references here: http://community.cloudera.com/t5/Advanced-Analytics-Apache-Spark/spark-2-0-with-spark1-6/m-p/49146 mentioning `These errors indicate some kind of classpath problem`.

We recommend connecting to Cloudera as follows without any further settings:

```
library(sparklyr)
library(dplyr)
library(ggplot2)

sc <- spark_connect(master = "yarn-client", version="1.6.0", spark_home = '/opt/cloudera/parcels/CDH/lib/spark/')
```

Seems yours is set to `SPARK_HOME="/opt/cloudera/parcels/CDH/lib/spark"` which is correct, but somewhere it might be the case that `SPARK_HOME` is not propagating.

Can you try connecting by explicitly passing `spark_home` as a parameter ot `spark_connect()` as suggested above?

**Comment by gvshankar** [comment]
No luck still.  Tried for both the Spark 1.6 and Spark 2.2, both give the same error.
> library(sparklyr)> library(dplyr)> > sc <- spark_connect(master = "yarn-client", config=spark_config(), version="1.6.0", spark_home = '/opt/cloudera/parcels/CDH/lib/spark/')
Error in force(code) :   Failed while connecting to sparklyr to port (8880) for sessionid (9221): Gateway in port (8880) did not respond.    Path: /opt/cloudera/parcels/CDH-5.10.1-1.cdh5.10.1.p0.10/lib/spark/bin/spark-submit    Parameters: --class, sparklyr.Shell, --jars, '/usr/lib64/R/library/sparklyr/java/spark-csv_2.11-1.3.0.jar','/usr/lib64/R/library/sparklyr/java/commons-csv-1.1.jar','/usr/lib64/R/library/sparklyr/java/univocity-parsers-1.5.1.jar', '/usr/lib64/R/library/sparklyr/java/sparklyr-1.6-2.10.jar', 8880, 9221    Log: /tmp/RtmppXOMhe/file6d2759686df7_spark.log
---- Output Log ----Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream at org.apache.spark.deploy.SparkSubmitArguments.handle(SparkSubmitArguments.scala:394).... ... 5 more
> 

> sc <- spark_connect(master = "yarn-client", config=spark_config(), version="2.2.0", spark_home = '/opt/cloudera/parcels/SPARK2/lib/spark2/')Error in force(code) :   Failed while connecting to sparklyr to port (8880) for sessionid (2837): Gateway in port (8880) did not respond.    Path: /opt/cloudera/parcels/SPARK2-2.2.0.cloudera1-1.cdh5.12.0.p0.142354/lib/spark2/bin/spark-submit    Parameters: --class, sparklyr.Shell, '/usr/lib64/R/library/sparklyr/java/sparklyr-2.2-2.11.jar', 8880, 2837    Log: /tmp/RtmppXOMhe/file6d2738c008ad_spark.log
---- Output Log ----
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream at org.apache.spark.deploy.SparkSubmitArguments.handleUnknown(SparkSubmitArguments.scala:465).... ... 5 more
> 

Shankar

**Comment by javierluraschi** [comment]
@gvshankar It's interesting that `/usr/java/jdk1.8.0_92` was working fine for R, I'm investigating this, but in the meantime, would be interesting to downgrade to `/usr/java/jdk1.8.0_92`, validate R works fine, and then check if/why-not `/usr/java/jdk1.8.0_92` is being used within RStudio.

**Comment by gvshankar** [comment]
I finally found the answer.  It looks like within RStudio, you cannot reference one environment variable within another.
The problem variable in my case was the SPARK_DIST_CLASSPATH which referenced the $HADOOP_HOME variable a lot.  Once I replaced the $HADOOP_HOME with the actual value, things started working fine.  Didn't see that big a difference between JAVA1.8.0_92 vs any of the newer versions.  
Another thing to constantly check was the Kerberos ticket (system('klist')).  Now I constantly check for it as in our environment, we have a 10 hour window.
Thanks for hanging with me in this.  You (Javier) and Heather have been very helpful.  At least now I know what to avoid.
# IMPORTANT!! Do NOT reference a environment variable within another environment variable.  RStudio doeesn't#               seem to translate this well.  All directory locations should be hard-coded.#               In the example below, $HADOOP_HOME is used within $SPARK_DIST_CLASSPATH## SPARK_DIST_CLASSPATH=/etc/hadoop/conf:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop/lib/*:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop/.//*:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop-hdfs/./:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop-hdfs/lib/*:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop-hdfs/.//*:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop-yarn/lib/*:$HADOOP_HOME/lib/hadoop/libexec/../../hadoop-yarn/.//*:$HADOOP_HOME/lib/hadoop-mapreduce/lib/*:$HADOOP_HOME/lib/hadoop-mapreduce/.//*#SPARK_DIST_CLASSPATH="/etc/hadoop/conf:/opt/cloudera/parcels/CDH/lib/hadoop/libexec/../../hadoop/lib/*:/opt/cloudera/parcels/CDH/lib/hadoop/libexec/../../hadoop/.//*:/opt/cloudera/parcels/CDH/lib/hadoop/libexec/../../hadoop-hdfs/./:/opt/cloudera/parcels/CDH/lib/hadoop/libexec/../../hadoop-hdfs/lib/*:/opt/cloudera/parcels/CDH/lib/hadoop/libexec/../../hadoop-hdfs/.//*:/opt/cloudera/parcels/CDH/lib/hadoop/libexec/../../hadoop-yarn/lib/*:/opt/cloudera/parcels/CDH/lib/hadoop/libexec/../../hadoop-yarn/.//*:/opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/lib/*:/opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/.//*"
Shankar

**Comment by hlendway** [comment]
Great news!  Happy to contribute ideas :)

**Comment by javierluraschi** [comment]
@gvshankar AWESOME! One question...

If I set `.Renviron` to:

```
RENVIRON_VALUE=Hello
RENVIRON_VALUE2=Something;$RENVIRON_VALUE
```

and then launch the R session, to run the following:

```
Sys.getnv()
```

I don't get environment variables resolved:

```
...
RENVIRON_VALUE          Hello
RENVIRON_VALUE2         Something;$RENVIRON_VALUE
...
```

Is it perhaps the case that something else is setting `SPARK_DIST_CLASSPATH ` for bash that is not for RStudio?

In anycase, closing.
