### ISSUE TITLE
Feature request: Implementation of bisect k-means algorithm

### ISSUE THREAD

**Issue by seawaR** [rstudio/sparklyr#986]
Hi there, first of all thanks for this great Spark interface.

I was wondering if you could implement bisecting k-means algorithm from [mllib](https://spark.apache.org/docs/latest/mllib-clustering.html#bisecting-k-means) as it can be faster than regular k-means and may produce clearer structures.

**Comment by kevinykuo** [comment]
@seawaR thanks for the FR, I'll make sure this gets included in the ML revamp tracked at #944

**Comment by kevinykuo** [comment]
Implemented in devel, see `?ml_bisecting_kmeans()`
