### ISSUE TITLE
na.omit() not working efficiently. 

### ISSUE THREAD

**Issue by kevinlzheng** [rstudio/sparklyr#988]
# Reporting an Issue with sparklyr na.omit()

---
Unfortunately I can not provide an workable example but here is my issue.
I have a dataset with 50 features, only 1 feature has a lot of missing values for this particular example and I want to use na.omit to remove ones with missingness. 

```r
spark_version <- "2.1.0"
sc <- spark_connect(master = "local", version = spark_version)
data <- spark_read_csv(sc,'final', "hdfs://...")
           features <- paste0("V", 1:50)
            # only one with missing values is feature 1
            mod.dat <- data %>% select(features[1:10]) %>% na.omit()
```
* Dropped 7173698 rows with 'na.omit' (7985217 => 811519)
It created a nice mod.dat for my models. Running time is about 17 seconds. 

```r
            mod.dat <- data %>% select(features[1:30]) %>% na.omit()
```
* Dropped 7173698 rows with 'na.omit' (7985217 => 811519)
Then it will wait forever, NO OUTPUT, NO ERROR! It seemed to be waiting a calculation to be completed. 

So I had to use an alternative coding as follow:
```r
           mod.dat <- data %>% select(features[1]) %>% na.omit() 
           dftmp <- data %>% select(features[-1])
           mod.dat <- right_join(dftmp, mod.dat, by = "parcelid")
```
* Dropped 7173698 rows with 'na.omit' (7985217 => 811519)
Nice and easy! Running time is 15 seconds.
Just wondering how na.omit is behaving in the example. Apparently it has detection 7173698 rows with na or null values. Why does it take so long to process the additional features which donot  have nas?

**Comment by javierluraschi** [comment]
@kevinlzheng The only reason I can think of would be that `na.omit` caches data by default when rows are dropped, we just performed a change to allow users to disable this behavior, would you mind trying this out?

First, install the latest version,

```
devtools::install_github("rstudio/sparklyr")
```

then run,

```
options(na.omit.cache = FALSE)
```

Followed by,

```
mod.dat <- data %>% select(features[1:30]) %>% na.omit()
```

**Comment by kevinlzheng** [comment]
@javierluraschi Unfortunately, after install the newest sparklyr, the dim and nrow functions do not work any more so I can't run further test. I had the same problem with <2.0 Spark version. Any idea what could have affected that?

**Comment by kevinlzheng** [comment]
After reinstalling Sparklyr, the entire project does not work any more, starting from nrow and dim function. Any idea? @javierluraschi

> spark_version(sc)
[1] ‘2.1.1.2.6.1.0’

> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sparklyr_0.6.2 dplyr_0.7.2    ggplot2_2.2.1 

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12     dbplyr_1.1.0     compiler_3.4.0   plyr_1.8.4      
 [5] bindr_0.1        base64enc_0.1-3  tools_3.4.0      digest_0.6.12   
 [9] jsonlite_1.5     tibble_1.3.4     gtable_0.2.0     nlme_3.1-131    
[13] lattice_0.20-35  pkgconfig_2.0.1  rlang_0.1.2      psych_1.7.5     
[17] shiny_1.0.5      DBI_0.7          rstudioapi_0.6   yaml_2.1.14     
[21] parallel_3.4.0   bindrcpp_0.2     withr_2.0.0      stringr_1.2.0   
[25] httr_1.3.1       knitr_1.16       rprojroot_1.2    grid_3.4.0      
[29] glue_1.1.1       R6_2.2.2         foreign_0.8-67   tidyr_0.6.3     
[33] reshape2_1.4.2   magrittr_1.5     backports_1.1.0  scales_0.4.1    
[37] htmltools_0.3.6  assertthat_0.2.0 mnormt_1.5-5     mime_0.5        
[41] colorspace_1.2-7 xtable_1.8-2     httpuv_1.3.5     config_0.2      
[45] stringi_1.1.5    lazyeval_0.2.0   munsell_0.4.3    broom_0.4.2

**Comment by kevinlzheng** [comment]
Just realized that dim and nrow might have been deprecated. sdf_dim and sdf_nrow could have used to replace both.

**Comment by kevinlzheng** [comment]
I re-installed the github version of Sparklyr and followed the instruction as directed above, but did not have any luck! 

* Dropped 1046729 rows with 'na.omit' . .......... long .....wait..................... > 5 minutes..still no results..

**Comment by javierluraschi** [comment]
@kevinlzheng the problem with `dim()` and `nrow()` is that other packages assume they will execute fast enough to perform their computation. For instance, `tibble`, which we use to print tables has `if()` checks using `nrow()` that cause printing to hand for big tables.

If you really miss them I would encourage you to create a package that overrides them and provide this for the `sparklyr` community, I can add this new package to the extensions list in [spark.rstduio.com](http://spark.rstudio.com), see for instance: [Extending Spark using sparklyr and R](https://www.rstudio.com/resources/webinars/extending-spark-using-sparklyr-and-r/) to get you up and running.

@kevinlzheng we'll have to troubleshoot this further, could help us here if you could find if this is trigger by a particular column and explain to us the data type and type of information it contains, or if this is specific to the number of columns. Sounds like this could also be a limitation in Spark, so it would help to reproduce this in Scala with the same dataset and report back your findings.

In any case, thanks for sending this feedback our way!

**Comment by kevinlzheng** [comment]
@javierluraschi  Thanks for the clarification! I am ok with the sdf replacement. 

I generated an example dataset for this na.omit problem. There could be a heap limit for it to work I assume. 

```r
   df1 <- data.frame(cbind(matrix(sample(c(0,0, 1,1, NA),100000, replace =T), ncol=10), matrix(sample(c(rnorm(9000),rep(NA, 1000)),100000, replace =T),  ncol =10)) )

   dfspark <- copy_to(sc, df1, overwrite = TRUE )
   
   for(i in 1:20) {
     t0 <- proc.time()
     df1 <- dfspark %>% select(colnames(dfspark)[1:i]) %>% na.omit()
     print(proc.time() - t0)
   }
```
Here below is the data and running time for each steps
```
* Dropped 1985 rows with 'na.omit' (10000 => 8015)
   user  system elapsed 
  0.091   0.009   1.110 
* Dropped 3607 rows with 'na.omit' (10000 => 6393)
   user  system elapsed 
  0.082   0.005   0.657 
* Dropped 4881 rows with 'na.omit' (10000 => 5119)
   user  system elapsed 
  0.079   0.010   0.637 
* Dropped 5874 rows with 'na.omit' (10000 => 4126)
   user  system elapsed 
  0.082   0.011   0.669 
* Dropped 6722 rows with 'na.omit' (10000 => 3278)
   user  system elapsed 
  0.083   0.009   0.799 
* Dropped 7348 rows with 'na.omit' (10000 => 2652)
   user  system elapsed 
  0.085   0.008   1.064 
* Dropped 7841 rows with 'na.omit' (10000 => 2159)
   user  system elapsed 
  0.088   0.001   0.848 
* Dropped 8248 rows with 'na.omit' (10000 => 1752)
   user  system elapsed 
  0.093   0.002   0.975 
* Dropped 8610 rows with 'na.omit' (10000 => 1390)
   user  system elapsed 
  0.080   0.013   0.832 
* Dropped 8883 rows with 'na.omit' (10000 => 1117)
   user  system elapsed 
  0.083   0.007   1.345 
* Dropped 8983 rows with 'na.omit' (10000 => 1017)
   user  system elapsed 
  0.090   0.009   2.852 
* Dropped 9079 rows with 'na.omit' (10000 => 921)
   user  system elapsed 
  0.106   0.007   8.248 
* Dropped 9152 rows with 'na.omit' (10000 => 848)
   user  system elapsed 
  0.146   0.025  27.273 
* Dropped 9237 rows with 'na.omit' (10000 => 763)
   user  system elapsed 
  0.354   0.079 105.318 
* Dropped 9310 rows with 'na.omit' (10000 => 690)
   user  system elapsed 
  1.233   0.444 449.049 
* Dropped 9378 rows with 'na.omit' (10000 => 622)
   user  system elapsed 
  2.233   0.744 1649.011
.... forever... 
```

**Comment by javierluraschi** [comment]
@kevinlzheng thank you for this insightful repro! Fix underway... https://github.com/rstudio/sparklyr/pull/1007
